### ISSUE TITLE
Tracking issue for things found by fuzzing gie.

### ISSUE THREAD

**Issue by schwehr** [OSGeo/PROJ#1009]
I've finally got around to hacking up an ugly fuzzer for gie.  There are a number of things found in gie.c and I'll use this issue to track them.

I switched gie.c to build with C++ and replaced main with this.  It just writes the fuzzer data to disk and reads it back, which is super slow.  However, I think there is something else that is causing the fuzzer to run super slow (~1 exec/s)...  I'm currently limiting artifacts to 200 bytes.

```C++
static void proj_logger(void * /* app_data */, int /* level */, const char * /* msg*/) {
  // Drop the message.
}

extern "C" int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {
  pj_ctx_set_logger(pj_get_default_ctx(), proj_logger);
  const string data2(reinterpret_cast<const char *>(data), size);

  const char kFilename[] = "a.gie";
  TempPath temp_path(TempPath::Local);
  string filepath = file::JoinPath(temp_path.path(), kFilename);

  CHECK_OK(file::SetContents(filepath, data2, file::Defaults()));

  memset (&T, 0, sizeof (T));
  T.dir = PJ_FWD;
  T.verbosity = 1;
  T.tolerance = 5e-4;
  T.ignore = 5555;

  T.fout = fopen("/dev/null", "w");

  F = ffio_create (gie_tags, n_gie_tags, 1000);
  process_file (filepath.c_str());
  ffio_destroy(F);
  return 0;
}
```

And hopefully there will be some useful gie test cases in the ~10K artifacts that I got in the first couple hours of fuzzing.

**Comment by schwehr** [comment]
For `ffio_create`, what does max_record_size refer to?

Is it the maximum number of characters per line in a gie file?

**Comment by kbevers** [comment]
@schwehr Is this issue still relevant?
