### ISSUE TITLE
Centralize time functionality

### ISSUE THREAD

**Issue by kbevers** [OSGeo/PROJ#1016]
We are starting to use various time-related functions more and more. This necessitates a collection of time function that are safe to use in a portable way.

This issue is in reaction to comments in https://github.com/OSGeo/proj.4/pull/1015.

Several things need to be done:

- [ ] Create `proj_time.h` \ `proj_time.c`
- [ ] Add a portable version of `localtime_r()` to the PROJ namespace, e.g. `pj_localtime_r()`
- [ ] Add a `pj_param_t_final()` or equivalent function, c.f. the `+t_final` parameter in `PJ_[h|v]gridshift.c`.

**Comment by rouault** [comment]
> Add a portable version of localtime_r() to the PROJ namespace, e.g. pj_localtime_r()

Aiming for gmtime / gmtime_r() would make more sense. We don't care about the local time but more some universal time. Anyway given the low accuracy needed for time in the proj context, the difference between both has no practical importance

**Comment by kbevers** [comment]
Works for me. As long as we can get resolution of about a days time I am happy. Anything more fine grained than that will not be needed in the foreseeable future.
