### ISSUE TITLE
Enhancing unitconvert to support angular units ?

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#1052]
I'm in the process of adding a "export to PROJ string" method to my ISO-19111 based objects, and I'm considering in particular the export of GeographicCRS
For a few esoteric / old GeographicCRS, the unit of the ellipsoidal coordinate system is not degree. For example EPSG:4807 / "NTF (Paris)" uses grad. So users should normally provide coordinates in grad. A possibility to handle that would to extend the xy_in and xy_out parameters to support angular units (probably restricted to radian, grad and degree for now)

The export of EPSG:4807 would then be
```
+proj=pipeline +step +proj=unitconvert +xy_in=grad +xy_out=radian +step=axisswap +order=2,1 +step +proj=longlat +ellps=clrk80ign +pm=paris
```

Thoughts ?

**Comment by rouault** [comment]
(above pipeline corrected to use xy_out=radian, as we use gradian internally for angular measures)

**Comment by rouault** [comment]
That would also mean that 'cct' shouldn't do automatic conversion of input parameters from degree to radian is the first step is +proj=unit_convert +xy_in={some_angular_unit}, and shouldn't do automatic conversion of output parameter from radian to degree is the last step is +proj=unit_counter +xy_out={some_angular_unit}

**Comment by kbevers** [comment]
This has been discussed in the past:https://github.com/OSGeo/proj.4/issues/121

I think it would an okay addition to unitconvert. I think you can make sure that `cct` behaves correctly by setting `P->right` to something different than `PJ_IO_UNITS_ANGULAR`. Currently it is set to `PJ_IO_UNITS_WHATEVER` which is probably fine. Additionally, if you set `P->left` to `PJ_IO_UNITS_ANGULAR`  `pipeline` will check that the units passed `unitconvert` are in fact angular (of they are not it will fail).
