### ISSUE TITLE
Homepage is too noisy

### ISSUE THREAD

**Issue by hobu** [OSGeo/PROJ#1056]
The landing page of proj4.org has way too much detail on it and scares users with four blocks of warnings. We need to be a bit more gentle. 

Let's refactor it a bit to be more inviting:

* A NEWS major page with all the release information
* Move all the scary warnings to the Development section
* A prominent link to the PDF version of the site
* A prominent link to Download

**Comment by mloskot** [comment]
First paragraph may also need updating to give better overview of what the current PROJ is/offers, instead of just:

> PROJ is a standard UNIX filter function
