### ISSUE TITLE
Size of the PROJ git repository will go unwidely due to gh-pages commits

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#1059]
The size of the .git subdirectory is large for a somewhat small project like proj:  360 MB.  I believe this is due to the fact we add commits to the gh-pages branch, and in particular proj.pdf, instead of forced-pushing them into a single commit. We don't need history for gh-pages as this is the deterministic result of the master branch.

I manually remove the references to gh-pages from the .git/packed-refs and .git/info/refs files (for some reason "git branch -d" doesn't work for remote branches), and then issued a "git gc --prune=now" to simulate removing completely this branch, and the resulting .git size was down to 170 MB (which still feels large, but is probably explained by the changes done on the projection .png images), which is consistent with the size of the .git subdir resulting from "git clone --branch master --single-branch git@github.com:OSGeo/proj.4.git"

**Comment by kbevers** [comment]
Yeah, I have been aware of this problem for a while but has not really found the courage to do something about. @mwtoews also pointed out that there's a bunch of stale files from discontinued pages from old versions of the docs. 

Seems like a good idea to just force push updates to gh-pages. Are you up for making the necessary changes @rouault ?

**Comment by mwtoews** [comment]
For the record, stale web pages were noted in #996 and I agree that the `gh-pages` branch can be purged in one way or another.

**Comment by rouault** [comment]
Proposed fix in PR #1060
