### ISSUE TITLE
Maybe typo in migration.rst file?

### ISSUE THREAD

**Issue by bylee20** [OSGeo/PROJ#1062]
From migration.rst,
```c
...
    while (scanf("%lf %lf", &c.lp.lam, &c.lp.phi) == 2) {
        c.lp.lam = proj_todeg(c.lp.lam);
        c.lp.phi = proj_todeg(c.lp.phi);
        c = proj_trans(P, PJ_FWD, c);
        printf("%.2f\t%.2f\n", c.xy.x, c.xy.y);
    }
...
```

As far as I know, PROJ.4 requires longitude/latitude in radians. I think `proj_todeg`s here should be `proj_torad`s.

**Comment by kbevers** [comment]
That is correct. Nice catch. You are probably the first that has read the migration guide :-)

**Comment by kbevers** [comment]
Fixed with https://github.com/OSGeo/proj.4/commit/b6fc41cd7cbc78fd0e6d31168096a62b27dd0194
