### ISSUE TITLE
Compilation error when using arm-linux-gnueabi-g++

### ISSUE THREAD

**Issue by dalishi** [OSGeo/PROJ#1066]
Hi guys,
I m trying to compile proj4 for use on arm. I configured as 
`./configure CC=arm-linux-gnueabi-g++ --prefix=/home/user/thirdparty/proj4`
when I make, I got the follow error:
`dmstor.c: In function 'double dmstor_ctx(projCtx, const char*, char**)':
dmstor.c:73:23: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
  if (*s && (p = strchr(sym, *s))) {`

I tried to figure out the prototype of this strchr() function in arm-linux-gnueabi-g++ but it seemed it is exactly the same as my gcc compiler.

`/usr/arm-linux-gnueabi/include/string.h:211:14: note: candidates are: char* strchr(char*, int)
/usr/arm-linux-gnueabi/include/string.h:213:20: note:                 const char* strchr(const char*, int)`

Quite confused that why I m getting this error with arm-linux-gnueabi while with GCC it compiled just fine.

**Comment by flying-ming** [comment]
@dalishi Hi!
Can you show me, the cross compilation command? 
I use the 
`./configure --prefix=/filePath  CXX=/usr/bin/arm-linux-gnueabi-g++-7 CC=/usr/bin/arm-linux-gnueabi-gcc --build=x86_64-linux-gnu  --host=arm-linux-gnueabi ` 
, but always out 'Exec format error'.

**Comment by dalishi** [comment]
> @dalishi Hi!
> Can you show me, the cross compilation command?
> I use the
> `./configure --prefix=/filePath CXX=/usr/bin/arm-linux-gnueabi-g++-7 CC=/usr/bin/arm-linux-gnueabi-gcc --build=x86_64-linux-gnu --host=arm-linux-gnueabi `
> , but always out 'Exec format error'.

Hi @flying-ming it's been long time and as far as i can recall i just use the following command. Hope it helps.
./configure CC=arm-linux-gnueabi-gcc --prefix=/home/user/thirdparty/proj4

**Comment by flying-ming** [comment]
thanks a lot!
