### ISSUE TITLE
k vs k_0 for proj=tmerc

### ISSUE THREAD

**Issue by bylee20** [OSGeo/PROJ#1067]
The document for transverse mercator(https://proj4.org/operations/projections/tmerc.html) mentions `k_0` option for scale factor:

> `+k_0=<value>`
> Scale factor. Determines scale factor used in the projection.

Defaults to 1.0.

However, the example shows `k` option for scale factor:

```
$ echo 9 51 | proj +proj=tmerc +lat_0=0 +lon_0=9 +k=1 +x_0=3500000 +y_0=0 +ellps=bessel +datum=potsdam +units=m +no_defs
3500000.00  5651505.56
```

On the other hand, I can also find some codes which use `k_0` as scale factor, for instance, from `https://github.com/OSGeo/proj.4/blob/master/nad/world`:
```
<bwi> # British West Indies
	proj=tmerc ellps=clrk80 lon_0=62W
	x_0=400000 k_0=0.9995
	no_defs <>
```

I confirmed that both of `k` and `k_0` option actually work.
Maybe `k` is an alias for `k_0`? Or there would be a difference which I didn't notice.

Anyway, it would be nice to clarify about `k` and `k_0` option in document.

**Comment by kbevers** [comment]
`+k` and `+k_0` are aliases, with the former being deprecated for the last 15-20 years.

I'll update the `tmerc` docs. Thanks for raising this issue.
