### ISSUE TITLE
Remove +ellps from +proj=helmert examples

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#1068]
The examples in https://proj4.org/operations/transformations/helmert.html have a +ellps= parameter, but as far as I an see the ellipsoid definition is completely unused by Helmert being a pure geocentric operation. Should we remove +ellps in the examples ?

**Comment by kbevers** [comment]
Yeah, they should be removed. They may be there because previously there was some problems if the ellipsoid wasn't specified but as far as I can tell that's not a problem any more.
