### ISSUE TITLE
Clean up FAQ in the docs

### ISSUE THREAD

**Issue by kbevers** [OSGeo/PROJ#1070]
The [FAQ](https://proj4.org/faq.html) is horribly outdated and should be cleaned up thoroughly. Perhaps removed all together.

At least half of the questions are either irrelevant or the answer is outdated.

**Comment by kbevers** [comment]
With changes in 82ee14c the only thing missing for this to be closed i a revision of the Webmercator question.

**Comment by SunveerSingh** [comment]
Hello, if this issue is not outdated, I would like to work on it!

**Comment by kbevers** [comment]
@SunveerSingh There's still room for improvement, so feel free to add a pull request with your suggestions for changes

**Comment by kbevers** [comment]
Adding thins isn't exactly cleaning up :-) Both questions are answered elsewhere on the website, but you are welcome to add those questions with links to the relevant sections. Here's a few pointers:

1. This is literally answered on the frontpage: https://proj4.org/ 
2. https://proj4.org/community/contributing.html

**Comment by kbevers** [comment]
Closed with #1309
