### ISSUE TITLE
vertcon .gtx grids are in millimeters instead of meters

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#1071]
Investigating vertical datum transformations, I tried the gtx grids of https://download.osgeo.org/proj/vdatum/vertcon/ and came to the same conclusion as http://lists.maptools.org/pipermail/proj/2011-December/006041.html , that is that the vertical offsets in the grids is in millimeters and not in meters. This comes directly from the raw vertconc.94, vertcone.94 and vertconw.94 files of https://www.ngs.noaa.gov/PC_PROD/VERTCON/VERTCON.zip that are themselves in millimeters (the Fortran code with them does a x 0.001 conversion). There is nothing in the .gtx header for the vertical unit, so we are a bit stuck.
There are 2 options I can see:
- regenerate the grids with values in meters instead of millimeters (this shouldn't cause too much issue since the values are in Float32 and presumably only 3 decimal figures are signficant, so Float32 precision is enough)
- leave them as such, and as ad-hoc code in the PROJ code to detect this situation (we can check the filenames + one value in them to ensure it is the expected value in millimeters) and apply on the fly the mm to m conversion.

Thoughts ?

**Comment by kbevers** [comment]
I don't like the second option. I think re-creating the grids using meters instead of milimeters is the way to go. At the same time they could be added to [OSGeo/proj-datumgrid]( https://github.com/OSGeo/proj-datumgrid) in a new NorthAmerica sub-package. It's probably a good idea to change the names slightly. That also gives you a chance to better clarify that the units have changed.

**Comment by rouault** [comment]
OK, another issue is the sign convention. The original grid and thus the .gtx is the offset to add to NGVD 29 to get a NAVD 88 height, and this matches the https://www.epsg-registry.org/export.htm?gml=urn:ogc:def:coordinateOperation:EPSG::7969 transformation method. But in the forward_3D() of vgridshift, we actually substract values. I guess I can workaround this in my WKT to PROJString code to use the inverse step...

> a new NorthAmerica sub-package

You mean there https://github.com/OSGeo/proj-datumgrid/tree/master/north-america ? Or a subdirectory of it ?

**Comment by kbevers** [comment]
> OK, another issue is the sign convention. The original grid and thus the .gtx is the offset to add to NGVD 29 to get a NAVD 88 height, and this matches the epsg-registry.org/export.htm?gml=urn:ogc:def:coordinateOperation:EPSG::7969 transformation method. But in the forward_3D() of vgridshift, we actually substract values. I guess I can workaround this in my WKT to PROJString code to use the inverse step...

Yes, I have been going back and forth on the sign convention for that operation. The current convention stems from the conversion of ellipsoidal heights (h) to orthometric heights (H): `H = h - N` where N is the geoid undulation (e.g. egm96_15.gtx). But that isn't universal for all applications of `vgridshift` so maybe it should have been the other way round from the start. Perhaps adding a flag specifying if the grid is meant to be subtracted or added would be a better generic solution?

> You mean there OSGeo/proj-datumgrid:north-america@master ? Or a subdirectory of it ?

Yeah, that's the one. I forgot we had already created a NA package.
