### ISSUE TITLE
Documentation on compiling from source incorrect

### ISSUE THREAD

**Issue by matthewhanson** [OSGeo/PROJ#1073]
The documentation says to run ./configure. However, unlike 4.9.2 there is no configure distributed.

The configure file should be able to be generated with autogen.sh but this requires an additional dependency, automake, which should be noted. However, even with automake installed and run, when I run the resulting ./configure file I get:
```
configure: error: cannot find install-sh, install.sh, or shtool in . "."/
```

I am trying to update to proj 5.1 in [geolambda](https://github.com/developmentseed/geolambda), so this is being run on a base Amazon linux image:

https://github.com/developmentseed/geolambda/blob/proj5/Dockerfile#L36

**Comment by kbevers** [comment]
Are you by any chance compiling directly from the git repository and not the source distribution?

**Comment by kbevers** [comment]
Yeah, I see your problem now:

>    wget https://github.com/OSGeo/proj.4/archive/$PROJ4_VERSION.tar.gz; \

Don't do that. That file is just a copy of what's in the git repo at a given tag (it can't be disabled, otherwise I'd do that). You need to get the archives from https://proj4.org/download.html
