### ISSUE TITLE
latlong to utm conversion issue fo 

### ISSUE THREAD

**Issue by vijaymadhavan** [OSGeo/PROJ#1076]
converting Australian latlong to utm(54H) result wrong value for UTM Easting.

    eg: Latitude: -35.3413679583, Longitude: 143.517785097
>The UTM value for zone 54H should be,
    
    UTM Easting: 728818.37, UTM Northing:6086190.19

>But in proj4
    
    var newLong = 143.517785097
    var newLat = -35.3413679583
    var secondProjection = "+proj=utm +zone=" + 54 +" +ellps=WGS84 +datum=WGS84 +units=m +no_defs";
    proj4(secondProjection, [newLon, newLat])

showing (728818.368345 , -3913809.81573)

why **UTM Northing** is showing wrong

**Comment by dtutic** [comment]
You are using UTM coordinate system for northern hemisphere. Each UTM zone has two coordinate systems, for northern (+y_0=0) and southern hemisphere (+y_0=10000000). Therefore you need:

var secondProjection = "+proj=utm +zone=" + 54 +" **+south** +ellps=WGS84 +datum=WGS84 +units=m +no_defs";

10000000  - 3913809.81573 = 6086190,18427

**Comment by kbevers** [comment]
>  Therefore you need: ... +south 

This is the correct answer. I'll update the docs so that https://proj4.org/operations/projections/utm.html includes that information.
