### ISSUE TITLE
What is the project stance on the ChangeLog?

### ISSUE THREAD

**Issue by schwehr** [OSGeo/PROJ#1086]
https://github.com/OSGeo/proj.4/commits/master/ChangeLog

It appears that folks abandoned the ChangeLog in 2015.  It might be worth discussing what should be done with the changelog now that we are in the era of DVCS.  `NEWS` is still being updated.  Could we just drop the ChangeLog?  Also, with the NEWS file, I find it hard to view (but less overwhelming than GDAL's).  It would be nice to be able to have an entry fit all on one page so that users could grok it quickly, but maybe it's more important to have it all layed out.  I personally don't like all the extra white space in the bulleted lists as they take more than one page to view (we should stop fixing so many things??? :)

This issue is primarily because of me commenting here:

https://github.com/Unidata/UDUNITS-2/commit/ba9be316adc245811d76e498088c3a093d2f9f03#commitcomment-30036935

**Comment by kbevers** [comment]
@schwehr Do you want to move on with this or can I close the issue?

**Comment by schwehr** [comment]
Closing it.  It's not worth any more thought.  I remove the ChangeLog and NEWS files in my local repo anyway :)
