### ISSUE TITLE
CMake C++11 configuration

### ISSUE THREAD

**Issue by hobu** [OSGeo/PROJ#1118]
We are manually setting CFLAGS for `-std=c++11` all over the place. This is problematic for a wide constelation of compilers. CMake takes care of it for us if we use 

```
set (CMAKE_CXX_STANDARD 11)
```

but we need to increase our CMake minimum version to 3.1+ to take advantage of it.

**Comment by QuLogic** [comment]
It seems [relatively good](https://repology.org/metapackage/cmake/versions), except for those few old systems that aren't even >=3.

**Comment by mloskot** [comment]
BTW, it's trivially easy to (re)install the latest CMake on (old) Linux:

```bash
#!/bin/sh
set -x

sudo rm -rf /usr/local/bin/cmake*
sudo rm -rf /usr/local/bin/ctest*
sudo rm -rf /usr/local/doc/cmake
sudo rm -rf /usr/local/man/man1/cmake*
sudo rm -rf /usr/local/man/man1/ctest*
sudo rm -rf /usr/local/man/man7/cmake*
sudo rm -rf /usr/local/share/cmake*

wget -O cmake-linux.sh https://cmake.org/files/v3.12/cmake-3.12.2-Linux-x86_64.sh
sudo sh cmake-linux.sh -- --skip-license --prefix=/usr/local
cmake --version
```

**Comment by mloskot** [comment]
Ubuntu LTS could be a reference point perhaps, ie. 14.04 LTS offers CMake 3.5

IMHO, there switching 2.8 to 3.1 is not worth the CMake modernisation overhaul. Better do it when jumping to 3.5 at least.

**Comment by kbevers** [comment]
> Ubuntu LTS could be a reference point perhaps, ie. 14.04 LTS offers CMake 3.5

Debian stable is usually quite conservative too, it seem to be at CMake 3.6 so yeah, 3.5 is probably not a bad choice. Going over the list @QuLogic supplied it generally seems that CMake 3.5 or newer is available on all major distributions. And most lesser known as well.

No objection from me on going for a minimum version 3.5. I am interested to hear if there are arguments against that I haven't considered.

**Comment by kbevers** [comment]
Let's hear some of the usual suspects opinion on this. @hobu, @cffk, @schwehr Any arguments against requiring a minimum version of CMake 3.5?

**Comment by schwehr** [comment]
On (almost) debian testing, I get

```
cmake --version
cmake version 3.10.2
```

I really have no idea what the changes are between cmake versions.  Are there any features that people need from any more recent versions?  I'm a cmake noob.

https://cmake.org/cmake/help/latest/release/index.html

The things of interest that I see:
- 3.6 ninja, CLANG_TIDY, FindGTest improvements
- 3.7 android improvements
- 3.8 C++17 support, improved memory sanitizer support
- 3.9 gtest_add_tests()

And I ran out of energy even for skimming.

Would be nice to have a rule about rolling the version forward.  Maybe something like 2 year grace?
March 2016: https://blog.kitware.com/cmake-3-5-0-available-for-download/

**Comment by cffk** [comment]
This is fine by me.  However, it might be worth preserving (and
documenting?) some extra backward compatibility in the cmake config
files for find_package (PROJ4 ...).  I.e.,

* the minimum CMake version for building PROJ4 is 3.5;
* the minimum CMake version for a dependent package is 3.0 (for
  example).

The only issue for find_package support that I'm aware of is the use of
target_include_directories which appeared in 2.8.11.

**Comment by mloskot** [comment]
@schwehr 
> I really have no idea what the changes are between cmake versions.
> Are there any features that people need from any more recent versions? 

It's not easy to collect a definite list. From my experience, CMake 2.8 does not even know about C++11 compilation. CMake 3.0 is a first release of so called 'modern CMake'. Fast-forward, CMake 3.4 is, AFAIU, a major overhaul Find-modules with exported targets and CMake 3.5 introduce those in FindBoost.cmake. Since Boost is quite a common dependency, perhaps that is the reason why many projects require 3.5 or laster, to be able to `target_link_libraries` against Boost with `Boost::boost`, `Boost::file_system`, etc. Certainly, that history does not necessarily (may) affect PROJ4.

However, I personally have never tried any CMake modernisation with anything older than CMake 3.5, so to be on safe side...

**Comment by mloskot** [comment]
@kbevers 
>> @cffk
>> the minimum CMake version for a dependent package is 3.0 (for example).
>
> Excuse my ignorance, is this possible? If so, how difficult is it? It sounds like a good idea to me.

Not sure what @cffk has in mind, but in case I grasped the idea:

- it's safe to assume `cmake_minimum_required(VERSION 3.5` in `CMakeLists.txt` of PROJ does not affect PROJ users, unless someone uses by `add_subdirectory` or embeds PROJ similarly
- then, it's matter to ensure that written/generated `proj-config.cmake`, `proj-targets.cmake` etc. deployed during installation are compatible with CMake 3.0 - this I think is pretty feasible.

**Comment by cffk** [comment]
@kbevers For example, PROJ4's CMakeLists.txt might use CMake's recent idiom for specifying that C++11 should be used, whereas this might be (is?) irrelevant to a dependency of PROJ4.

**Comment by mloskot** [comment]
The question is if C++11 is only build requirement or also a usage requirement of PROJ.

If the latter too, and users `#include`-ing headers and linking against PROJ are required to use C++11 or later, then that is a usage requirement and it should be included in PROJ-s exported target(s) that users 'link' against.

One of major shift in modern CMake is concern and separation of [Build Specification and Usage Requirements](https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html).

**Comment by cffk** [comment]
@mloskot Yes, I understand.  But suppose lame random package depends on PROJ and handles figuring out the C++11 flags the old-fashioned way (e.g., by test compiles), then I recommend that we let the maintainers of that package figure out to increment their cmake minimum version rather than forcing the change with a new version of PROJ.

**Comment by rouault** [comment]
> The question is if C++11 is only build requirement or also a usage requirement of PROJ.

It will be a usage requirement for people wanting to use its C++ API

**Comment by mloskot** [comment]
@cffk 
> @mloskot Yes, I understand. But suppose lame random package depends on PROJ and handles figuring out the C++11 flags the old-fashioned way (e.g., by test compiles),

In such case, no CMake configuration of PROJ should interfere indeed.

People seem to use CMake in all sorts of ways, pulling dependencies with `add_subdirectory`, `ExternalProject_Add`, from installed then using either CMake's or own Find-modules, from installed and using Config-files  profvided by a library (modern way), etc.  There may be situation where PROJ's requirement on minimum CMake will interfere, but it's hard to predict.

**Comment by kbevers** [comment]
@hobu, @mloskot, @schwehr, @cffk is either one of you willing to make the changes mentioned in this issue within the next couple of days so that they can be part of PROJ 6?

**Comment by mloskot** [comment]
I will try to make a PR tonight.

To summary the whole discussion so far, extent of the expected changes is something like this:

```
set(CMAKE_CXX_STANDARD 11 CACHE STRING "C++ standard version to use (default is 11)")

message(STATUS "PROJ.4 Require C++${CMAKE_CXX_STANDARD}")
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
```

TBH, I'm not sure about setting `CXX_STANDARD` on any public targets, in the Config-files, etc.
I'm trying to confirm some best practices on `#cmake` channel at cpplang.slack.com.

**Comment by kbevers** [comment]
Awesome! Thanks @mloskot.

**Comment by mloskot** [comment]
@kbevers Please, have a look at #1262
