### ISSUE TITLE
Add Bertin1953 projection

### ISSUE THREAD

**Issue by Fil** [OSGeo/PROJ#1120]
I documented and added the Bertin1953 projection to D3 a while ago. Would there be interest in porting it to proj.4?

https://visionscarto.net/bertin-projection-1953
https://github.com/d3/d3-geo-projection#geoBertin1953

(It is very often used by French cartographers.)

![](https://visionscarto.net/local/cache-vignettes/L1376xH930/visionscarto8f6c-fea65.png?1508882652)

**Comment by rouault** [comment]
Maybe you want have a try at implementing yourself ? https://github.com/OSGeo/proj.4/pull/1090 is a good example of how to add a new projection method to PROJ

**Comment by Fil** [comment]
I can give it a try. I've dl'ed and compiled proj.4, and I'm at a point where I need to figure out how to use the build to visualize the results. Is there a simple tool that will "draw a map" directly from the command line?

**Comment by kbevers** [comment]
> I can give it a try

Awesome!

> Is there a simple tool that will "draw a map" directly from the command line?

Take a look at the scripts in `/docs/plot`

**Comment by kbevers** [comment]
See https://github.com/OSGeo/proj.4/commit/cf0e6926b21019c835e4f0f11f1a4f11e5fd8fdc. I've added a conda env file and made a few slight updates to the plot script. With this you should be able to get going.

**Comment by Fil** [comment]
thank you!  For the record
```
> cd docs/plot
docs/plot> conda env create
docs/plot> source activate proj
docs/plot> bash plot.sh
```

**Comment by Fil** [comment]
I've tried to port the code but I'm blocked by a few issues:
- the rotation parameters. I need to apply  [p.rotate([-16.5, -42]);](https://github.com/d3/d3-geo-projection/blob/master/src/bertin.js#L37) before doing the computations, and I hoped giving `"projstring": "+proj=bertin1953 +lon_0=-16.5 +lat_0=-42",` in plotdefs.json would do the trick. I'm not sure what to do about this.
- I'd like to import hammer and reuse it (instead of copying the contents)
- the graticule explodes

**Comment by kbevers** [comment]
Here you can see what `+lon_0` (`P->lam0`) does to your input longitude before it ends up in your projection code:

https://github.com/OSGeo/proj.4/blob/cf0e6926b21019c835e4f0f11f1a4f11e5fd8fdc/src/pj_fwd.c#L89

It is simply just subtracting the `+lon_0` value from the input longitude, effectively rotating the earth.

There is no standard treatment of `+lat_0`. You will have to do that yourself in the projection code. The value set with `+lat_0` can be accessed as `P->phi0`.

**Comment by Fil** [comment]
![bertin1953](https://user-images.githubusercontent.com/7001/45848204-e0f30100-bd2d-11e8-91c9-cd2bb8642da5.png)

**Comment by kbevers** [comment]
Looks like your on the right track. Good job!

**Comment by Fil** [comment]
Thank you! How can I test my build with QGIS?

**Comment by kbevers** [comment]
I guess you build QGIS and have et point towards your version of PROJ? This question is probably better suited for the QGIS guys.

**Comment by Fil** [comment]
Now that QGIS ships with Proj 6.3.2 using this projection is as easy as creating a custom CRS with the formula:
>  proj=bertin1953

![bertin1953-qgis](https://user-images.githubusercontent.com/7001/115857251-bf021380-a42d-11eb-8bba-08ff3adef4f1.png)


it took two years, but it's done! thank you @kbevers
