### ISSUE TITLE
Pull website from current maintenance branch 

### ISSUE THREAD

**Issue by kbevers** [OSGeo/PROJ#1122]
At the moment we rebuild the docs every time a commit hits the master branch. This is not a problem per se, but it has the unfortunate effect of adding documentation for not yet released features. 

The docs has been undergoing some major work the last year or so. While doing this it has been nice to have the most recent version published straight away. Now that the docs are converging to something more stable I think it is time to only update the website when necessary and disconnect it from active development.

With this change, updates to the website will have to be committed to the current maintenance branch (5.2 at the moment). Commits to this branch should trigger a website rebuild.

**Comment by hobu** [comment]
Yes, I agree it is time to do this. The PDAL source tree does so, and you can steal from its Travis config on the build/generation/push of the docs for the maintenance branch.

**Comment by mwtoews** [comment]
Is there any reason why the PROJ docs are not hosted at https://readthedocs.org ? I mention this because it supports multiple versions.

**Comment by hobu** [comment]
> Is there any reason why the PROJ docs are not hosted at https://readthedocs.org ?

It's something for someone to explore.  Maintenance of our PDF generation is important, but it looks like RTD has that covered.

**Comment by kbevers** [comment]
Having several versions of the docs online would be nice to have but is that something we can realistically offer at this point? Anything before 5.0.0 is basically non-existant. 5.0.0-5.1.0 is missing quite large chunks of information.
