### ISSUE TITLE
 incomplete type 'PJ_ELLPS' when using public API from "proj.h"

### ISSUE THREAD

**Issue by basiliscos** [OSGeo/PROJ#1147]
My code just includes "proj.h". The types like `PJ_COORD` is found and complete, i.e. i can work with it's members (documented in `datatypes.html`); but the following code

```cpp
    auto p =  proj_list_ellps();
    while (p) {
        std::count << p->id << "\n";
    ...
    }
```

leads to error 

```
error: invalid use of incomplete type 'const struct PJ_ELLPS'
         std::count << p->id << "\n";
                        ^~
````

**Comment by basiliscos** [comment]
my proj version is `5.2.0`

**Comment by kbevers** [comment]
Does it change anything if you include `projects.h` as well as `proj.h`?

**Comment by basiliscos** [comment]
I cannot do that, as the `UV` internal type conflicts with perl internal type `UV` :

```
In file included from src/xs/proj.h:6,                                                                                                                                                        
                 from Proj.xs:11:                                                                                                                                                             
/home/b/development/crazy-panda/clean-realcraft-server/meia/var/lib/x86_64-linux/CPP/proj4.x/i/projects.h:167:15: error: conflicting declaration 'typedef struct PJ_UV UV'                    
 typedef PJ_UV UV;                                                                                                                                                                            
               ^~                                                                                                                                                                             
In file included from Proj.xs:5:                                                                                                                                                              
/home/b/perl5/perlbrew/perls/perl-5.26.1/lib/5.26.1/x86_64-linux/CORE/perl.h:1655:16: note: previous declaration as 'typedef long unsigned int UV'                                            
 typedef UVTYPE UV;                                                                                                                                                                           
                ^~                                                                                                                                                                            
```

(Yep, I'm writing perl-adapters for Proj).

**Comment by busstoptaktik** [comment]
Nice catch here - I think we didn't finish discussing whether proj_list_ellps() belonged in the 4D-API (i.e. the proj_-namespace). It probably should be moved to proj-4D-API.c and documented as an API function.

Your best workaround for now would be to copy the definition of struct PJ_ELLPS from projects.h after including proj.h (which forward declares the material).

**Comment by basiliscos** [comment]
Thank you, work around works fine!

I think I'll keep the issue open, until it will be resolved in the sources.

**Comment by kbevers** [comment]
> I cannot do that, as the UV internal type conflicts with perl internal type UV 

Good thing we are getting rid of that soon then!

>  I think we didn't finish discussing whether proj_list_ellps() belonged in the 4D-API (i.e. the proj_-namespace).

It does. It replaces `pj_get_ellps_ref()` which is defined in `projects.h` and thus will be removed with the next version.

> I think I'll keep the issue open, until it will be resolved in the sources.

Keeping this issue open is fine. The fix should be fairly simple, basically applying Thomas' work-around, removing `pj_get_ellps_ref()` and making a few adjustments around the code. When I have an hour or two to spare I'll look into it.

**Comment by kbevers** [comment]
> JFYI: the same relates to PJ_UNITS, and PJ_PRIME_MERIDIANS structures.

Yeah, that makes sense. For now the work-around will have to be to include `projects.h` as well or copying the definitions as Thomas suggests. Luckily most people will not have the issue of clashing with Perl's internal data structures. I'll take care of the other structures too.
