### ISSUE TITLE
Convert affine transformation parameters to wkt or proj-string

### ISSUE THREAD

**Issue by CarstenL** [OSGeo/PROJ#1155]
Two weeks ago, you implement the affine transformation in proj4 #535 .

GDAL and GeoServer works with wkt and/or proj-string.
I think it will be useful to have a converter between affine parameters (A-I) and wkt and / or proj-string.
So, we can call proj4 (or cs2cs?) with our affine parameters and the output will be in your format you defined as a paramter.
Maybe something like this:
`cs2cs -affine -A 1.0 -B 2.0 -C 35 -D -1.0 -E -5.1 -F 10.85 -format wkt`
`cs2cs -affine -A 1.0 -B 2.0 -C 35 -D -1.0 -E -5.1 -F 10.85 -format proj`

**Comment by kbevers** [comment]
See the proposed [RFC2](https://github.com/OSGeo/proj.4/pull/1149), specifically the section on [`projinfo`](https://github.com/OSGeo/proj.4/blob/9ae6713916f495b6f150915609a545275c5de699/docs/source/community/rfc/rfc-2.rst#utilities)

You should be able to something similar to what you are requesting once the work described in RFC2 is finished and released.

**Comment by CarstenL** [comment]
with projinfo it is possible to generate the PROJ string of a known coordinatesystem, right?
But for local coordinatesystem it doesnt work. 
So if your local coordinatesystem is based on WGS84 and rotated 23 degress, and x-offest of 15 (for example), you have to use a affine transformation.
And for the result of this transformation, it will be useful to generate the PROJ-string to add this in epsg-file of GDAL.

**Comment by kbevers** [comment]
> with projinfo it is possible to generate the PROJ string of a known coordinatesystem, right?

Or a WKT from a PROJ string, as shown in the [linked example](https://github.com/OSGeo/proj.4/blob/9ae6713916f495b6f150915609a545275c5de699/docs/source/community/rfc/rfc-2.rst#specify-crs-by-proj-string-and-specify-output-formats). I don't see why that isn't doing exactly what you are asking for. It is roughly the same amount of work to write `-affine -A 1.0 -B 2.0 -C 35 -D -1.0 -E -5.1 -F 10.85` as the equivalent PROJ string. The parameters have different names but it does the same thing.
