### ISSUE TITLE
rHEALPix (and HEALPix) issue (possible bug)

### ISSUE THREAD

**Issue by rbejar** [OSGeo/PROJ#1157]
I sent a [message to the mailing list](http://lists.maptools.org/pipermail/proj/2018-October/008420.html) with details with a problem I have using [rHEALPix](https://proj4.org/operations/projections/rhealpix.html) with Proj.4 version 5.2.0 on Kubuntu 18.04 (compiled from sources). 
The issue is that Proj.4 seems unable to project points on the edges of some of the squares of the projection. For example, the inverse projection of (-PI, 3*PI/4) should work and give something around lon 90, lat 42, but it just fails (if I understand properly rHEALPix). But this command in the current version of Proj.4 produces this output:
```
$proj -EIf '%.4f' +proj=rhealpix +lon_0=0 +a=1 +ellps=WGS84 +north_square=0 +south_square=0
-3.14 2.35
-3.14 2.35      *       *
```
I suspected first some tolerance issues, but the problem is larger than that.

I have taken a look at the code and the problem would seem to be that rHEALPix is using as `P->right` the value `PJ_IO_UNITS_CLASSIC` (by default?), and that uses a scaling factor that takes my -3.14 and transforms it to a number less than -PI, making it impossible to compute the inverse projection. A simple fix (workaround?, lucky shot? time bomb? new-bug-to-be-born?) seems to be adding `P->right = PJ_IO_UNITS_ANGULAR` in the `PJ *PROJECTION(rhealpix)` function in ` PJ_healpix.c`. This would make sense because rHEALPix units are actually radians. With this change, the corner seems to be properly projected:
```
-3.14 2.35
-3.14 2.35      90.2642 42.0418
```
By the way, if this makes sense, I assume that I would make sense to do the same in the `PJ *PROJECTION(healpix)` function.

However, this change, of course :cry:, breaks the tests. This may, or may not, mean something depending on how the values used for those tests were generated.

Does this make any sense to any of you? I have written this after some time reading about, and making tests with, rHEALPix, and about 3 hours with the code of Proj.4 (after more than 15 years since my last time using C), so it could be anything from naive self-delusion to brilliant bug smashing :wink:. At this point I certainly need some help.

**Comment by rbejar** [comment]
After a night sleep and some re-reading rHEALPix and HEALPix docs I think that it is not a bug in the implementation of rHEALPix in Proj.4 but a couple of misunderstings I had:

- The values of the coordinates of these projections are not radians. They are projected and in units of the authalic radius. By using all the time +a=1 in my tests they looked similar and that got me confused.
- The authalic sphere of the WGS84 ellipsoid with semi-major axis == 1 does not have a radius of 1 but slightly smaller. This would be the reason why some values on the "edges" were not converted. If I use +a=1.00336409 with +ellps=WGS84 (ratio between its semi-major and semi-minor axes) the authalic sphere has a radius slightly larger than 1 and I can convert points on the "edges".

I am closing the issue now.

**Comment by kbevers** [comment]
Thank you for the update, @rbejar. Do we need to update the documentation to reflect your findings better?

**Comment by rbejar** [comment]
Hi @kbevers. Thank you, but I think that anything short of writing a tutorial on rHEALPix and its peculiarities would not be much better than the current documentation. And that would be, I think, way out of the scope of Proj.4.

**Comment by kbevers** [comment]
All right, great. Have you come across good resources that we can link to to help users in similar situation as yours?

**Comment by rbejar** [comment]
The [preprint of the manuscript where rHEALPix is specified](https://raichev.net/files/rhealpix_dggs_preprint.pdf), and a [Nodejs small library](https://github.com/substack/healpix) which is the simplest implementation of HEALPix (without the r-) coordinate conversion that I have found, and that has convinced me that the implementation in Proj.4 is correct. Those two, and Wikipedia, of course :wink:.
