### ISSUE TITLE
Doc: free grids mentionned in non-free grid paragraph

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#1159]
https://proj4.org/resource_files.html#non-free-grids mentions that NTv2, Germany and Great Britain grids as non free, whereas they are and already included in proj-datumgrid

**Comment by mwtoews** [comment]
See also #1123 (esp. fc26ed705584a0c7bd124d67af875a8f4d3f243d)
Looks like Great Britain is the remainder that needs to be addressed.

**Comment by rouault** [comment]
I've cherry-picked the commits of #1123 to the 5.2 branch, from which the online website is refreshed
