### ISSUE TITLE
Implement Molodensky-Badekas transformation

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#1160]
This is a variation of Helmert 7 parameters where the rotation is not applied regarding the Earth centre, but with a reference point (in cartesian space). So X,Y,Z  input coordinates are expressed regarding this Xp,Yp,Zp evaluation point, the Helmert rotation is applied, and then we re-add Xp,Yp,Zp, and then the translation terms of Helmert. So the existing PJ_helmert could just be enhanced with those Xp,Yp,Zp coordinates (one can convince oneself easily that when Xp=Yp=Zp=0, this is standard 7-parameter Helmert). Of course this is better documented in EPSG guidance 7.2

Used for example for https://www.epsg-registry.org/export.htm?gml=urn:ogc:def:coordinateOperation:EPSG::1066

**Comment by kbevers** [comment]
The existing Helmert is already a complicated beast. My immediate thought is that it would be better to put this in it's own operation that leverages the code in `PJ_helmert.c`. Would that be possible without creating a big web of spaghetti?

**Comment by kbevers** [comment]
> My reasoning for including this in PJ_helmert is that it is should be just a matter of doing something like

I am aware that the math is simple this way. I am just worried about the growing number of parameters in Helmert.

The Molodensky-Badekas only uses the first 7 Helmert parameters, right? We could make a `molobadekas` (or whatever...), use the code you just proposed for both `helmert` and `molobadekas`, have the `TRANSFORMATION(molobadekas, 0)` setup only read the relevant parameters and use `helmert_forward_3d()` and `helmert_reverse_3d()`? Obviously a new function for reading the shared parameters would be useful in this approach.

I think this will also communicate better what transformation is performed.

> (by the way the use of lpz.lam and lpz.phi here is super confusing as we are in the cartesian space in input space)

I agree. Feel free to fix it by adding a `PJ_COORD` for the input data.

**Comment by rouault** [comment]
@kbevers Your drafted plan sounds good to me. Indeed having a 18-parameter Helmert is not super user friendly :-)
