### ISSUE TITLE
Off-by-one in Robinson projection?

### ISSUE THREAD

**Issue by QuLogic** [OSGeo/PROJ#1172]
In Robinson, `i` is limited by:
https://github.com/OSGeo/proj.4/blob/330e8bf686f9c4524075ca1ff50cbca6c9e091da/src/PJ_robin.c#L87-L91
to `0 <= i <= NODES - 1` and `i + 1` is never used in `s_forward`. [Here](https://github.com/OSGeo/proj.4/blob/330e8bf686f9c4524075ca1ff50cbca6c9e091da/src/PJ_robin.c#L73), `NODES` is set to 18, but there are _19_ entries in `X` and `Y`. In `s_inverse`, `i + 1` _is_ used.

So, is the last entry in the `X` and `Y` tables supposed to be applied in `s_forward` (and accidentally not), or is it only there for `s_inverse`? If this is intentional, I guess a comment would be helpful to make this clear. Of am I just misreading something here?

**Comment by kbevers** [comment]
I have no idea, to be honest. It does seem plausible that there's been made a mistake here. Usually when these types of problems show up I have a look in the original papers that describe the projection. I haven't got the time for that at the moment so I would suggest you do that yourself if you need a quick answer to this :-)
