### ISSUE TITLE
Compiling JNIWrap - javac doesn't support 'module-source-path' attribute

### ISSUE THREAD

**Issue by mws-rmain** [OSGeo/PROJ#1173]
OS: Ubuntu 16.04
Apache Ant v 1.10.1
Java 9 (Oracle jdk-11.0.1)

Running ant javadoc in 'proj.4/jniwrap'
Resulted in: 
BUILD FAILED
./proj.4/jniwrap/build.xml:23: javac doesn't support the "module-source-path" attribute

Changing build.xml:23 from 'module-source-path' to 'modulesourcepath' allowed the compile to complete.

**Comment by rouault** [comment]
Old JNI bindings have been removed from PROJ master
