### ISSUE TITLE
cmake: default include and lib subdirs for Windows

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#1177]
cmake/ProjInstallPath.cmake has set(DEFAULT_LIB_SUBDIR local/lib) and set(DEFAULT_INCLUDE_SUBDIR local/include) for the WIN32 case. @hobu I see you were the one to commit those lines ;-) : any reason for that local/ prefix, and not using the Unix layout ?

**Comment by hobu** [comment]
This pattern originated in libLAS, and I blame @mloskot for it 😄 

It can be cleaned up.
