### ISSUE TITLE
"geos" projection documentation - contradiction in the sweep angle axis explanation

### ISSUE THREAD

**Issue by magau** [OSGeo/PROJ#1179]
While reading the "geos" projection documentation I've found, what is in my opinion, a contradiction in the sweep angle axis explanation.

https://github.com/OSGeo/proj.4/blob/master/docs/source/operations/projections/geos.rst

Actually what seems to be wrong isn't the sweep angle axis explanation it self but the GOES/Meteosat respective values x or y.

Consider the following citations:

"In the image above, the outer-gimbal axis, or sweep-angle axis, is the N/S axis (y) (...). This example represents the scanning geometry of the Meteosat series satellite. However, the GOES satellite series use the opposite scanning geometry, with the E/W axis (x) as the sweep-angle axis, ..."

"Thus, the scanning geometry of the Meteosat series satellite should take sweep as x, and GOES should take sweep as y."

My usage experience tells me that the last sentence is wrong (i.e. "+sweep=y" should be for the Meteosat while "sweep=x" for GOES).

Thanks in advance. Please clarify me if I'm wrong... :)

**Comment by rouault** [comment]
Yes, you're right: the MSG and MSGN drivers in GDAL for Meteosat use the default value for +sweep, that is y. I'm going to correct the last sentence "Thus, the scanning geometry..."

**Comment by magau** [comment]
Thanks Even!
By the way, in the "Language bindings" section I've noticed that there are no official bindings for Fortran.
I've being recently working on updating an old git repository: 
https://gitlab.com/joao.macedo/proj4-fortran
It would be nice if it could be integrated in future releases.
Can you advice me what's the right procedure?

**Comment by kbevers** [comment]
@magau 	What do you mean by "integrating"? That PROJ should come with the fortran bindings as a default? Or do you simply just want to link to the fortran bindings on the website (as we do with most bindings for other languages)?

**Comment by magau** [comment]
@kbevers, whatever you would find useful. For me a link on the website wold be great!
Actually the original code wasn't written by me, its from [Magnus Hagdorn](https://github.com/mhagdorn) (Magnus.Hagdorn@ed.ac.uk), that I'd need to consult.
He did a very nice job, but it hasn't being updated since 2013...  I've just refactor it and create a new release [v1.1.0](https://gitlab.com/joao.macedo/proj4-fortran/tags/1.1.0) in a forked repository.
Thanks for the opportunity of contribute for such a nice Proj-ect!

**Comment by kbevers** [comment]
> whatever you would find useful. For me a link on the website wold be great!

That is what I prefer. You are welcome to submit a PR adding it to https://github.com/OSGeo/proj.4/blob/master/docs/source/development/bindings.rst
