### ISSUE TITLE
Create a 'noop' operation ?

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#1185]
The new C++ code that creates operations can return an empty PROJ string when the transformation is a no opeation. Currently it instanciates a dummy +proj=affine for that purpose, but probably a 'noop' operation would be better

**Comment by jidanni** [comment]
OK, but be sure to mention on
https://proj.org/en/9.2/operations/conversions/noop.html
the motivations for creating it, else people will scratch their heads.
Do add an example of how it is useful, there.
