### ISSUE TITLE
Document cs2cs changes done per https://github.com/OSGeo/proj.4/pull/1182

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#1186]
https://github.com/OSGeo/proj.4/pull/1182 modifies cs2cs . Update documentation acordingly

**Comment by kbevers** [comment]
This also regards `proj_create_crs_to_crs()` which has been changed in the same PR. If I am not mistaken there's also addition of new functions to `proj.h` that is not handled by Doxygen, e.g. `proj_area_create()`, `proj_area_set_bbox() and others.
