### ISSUE TITLE
Change projinfo default to WKT2_2018 when identifying transformations

### ISSUE THREAD

**Issue by kbevers** [OSGeo/PROJ#1187]
As seen below, `projinfo` doesn't output WKT when `--identify` is combined with `-s\-t` because it is not possible in the WKT2_2015 default. I think using WKT2_2018 here would produce more useful ouput. In general I would prefer using WKT2_2018 as the default anywhere but I guess it is still only a draft. Obviously we should not release a PROJ version that defaults to the 2018 standard before it exists in it's final form. Any idea when it can be expected to be finished?

```
>bin\projinfo --identify -s EPSG:25832 -t EPSG:23032
PROJ string:
+proj=pipeline +step +inv +proj=utm +zone=32 +ellps=GRS80 +step +proj=utm +zone=32 +ellps=intl

WKT2_2015 string:
Error when exporting to WKT2_2015: Transformation can only be exported to WKT2:2018
```

**Comment by rouault** [comment]
> I think using WKT2_2018 here would produce more useful ouput.

I've just realized unfortunately that WKT2_2018 CONCATENATEDOPERATION doesn't allow to put a CONVERSION in a STEP. Although the Topic 2 modelling allow this. So currently this WKT2_2018 output is actually an extension of the upcoming WKT2_2018. I've just raised this issue

> Any idea when it can be expected to be finished?

I've just asked the question.

**Comment by kbevers** [comment]
All right, let's see if you are able to get the standard fixed. If the release of the final version of the WKT2_2018 standard is close to the release of version 6.0 I think we should go with the 2018-version as the default in `projinfo`.

**Comment by rouault** [comment]
Regarding WKT2_2018, update I just got from Roger Lott: "In parallel, the ISO ballot commenced today 3rd December and closes on 25th February.  My plan is for OGC to make comments into the ISO ballot - those editorial ones I have alluded to from the OGC ballot, together with anything from the
discussion at next week's SWG meeting (Wed 12th, 1015-1200 UTC-5 = 1615-1800
for you in France)."

He also agrees that CONVERSION should be allowed in CONCATENATEDOPERATION and that will be discussed in the next week's SWG meeting.

**Comment by kbevers** [comment]
>  closes on 25th February

Perfect timing for a March 1st release of PROJ :-) (provided that the ballot is successful)

**Comment by rouault** [comment]
Regarding CONVERSION in CONCATENATEDOPERATION, the today CRS OGC SWG meeting confirmed that it would be an OGC suggested editorial change to the ISO ballot, so there's a good chance it is in the final doc.

**Comment by kbevers** [comment]
What is the status on this? Is it too risky to bet on WKT2_2018 being finalized more or less at the same time as the March 1st release of version 6 and just set that as the default? Or should we wait until a minor version release later in the year?

**Comment by rouault** [comment]
I'll switch to WKT2_2018. I don't think its syntax should evolved at that point.

**Comment by kbevers** [comment]
Great. I was reminded of this by your question on the GDAL list yesterday. I think we should adopt a policy that says that the most recent version of WKT/WKT2 is always used. Of course now is a bit of a special situation but from now on when a new revision of the standard is available that is what we should use in the following PROJ release. Well, except patch releases. Do you agree?

**Comment by rouault** [comment]
> Do you agree?

Policies without workforce to implement them are just policies... :-) And sometimes you want to be a bit behind the latest version for interoperability reasons with other implementations. In that case as the user can select an older version easily, that isn't much an issue.

**Comment by kbevers** [comment]
> Policies without workforce to implement them are just policies... :-)

That's why we've got you :-) Of course, if no one wants to implement the changes then there's no issue of updating the defaults. I suspect it will be some time again before the standard is revised again so this can also be handled later.
