### ISSUE TITLE
proj_create_crs_to_crs doesn't handle changes in ellipsoids correctly

### ISSUE THREAD

**Issue by kbevers** [OSGeo/PROJ#1188]
When trying to use `cs2cs` to transform from ETRS89/UTM32 to ED50/UTM32 I have encountered a few problems. In general the datum shift doesn't seem to be applied at all, that may be because the EPSG registry doesn't describe that transformation properly so let's ignore that for now. That leaves us with a transformation that is from UTM coordinates on one ellipsoid to UTM coordinates on another ellipsoid. The change in ellipsoid between the two systems isn't done correctly. This is how `projinfo` suggests to do the transformation:

```
> bin\projinfo.exe -s EPSG:25832 -t EPSG:23032
PROJ string:
+proj=pipeline +step +inv +proj=utm +zone=32 +ellps=GRS80 +step +proj=utm +zone=32 +ellps=intl
```

that is, backprojecting UTM to geodetic coordinates (using the parameters of the GRS80 ellipsoid as projection parameters) then projecting the geodetic coordinates to UTM again (using the Hayford ellipsoid parameters as projection parameters). This is not the correct way to do a shift in ellipsoids. To do so we have to convert the geodetic coordinates to cartesian (using the ellipsoid parameters of the first system) then back to geodetic (using the ellipsoid parameters of the second system). We need this to have a proper physical representation of the coordinates in relation to the center of the Earth. Here's an example:

```
> bin\cct.exe +proj=pipeline +step +proj=utm +zone=32 +inv +step +proj=cart +ellps=GRS80 +step +proj=cart +ellps=intl +inv +step +proj=utm +zone=32
687071.44       6210141.33 0
  687067.7581   6210226.0728     -188.2678           inf
```

This output should be compared to the transformation provided by `projinfo` \ `cs2cs`:

```
> bin\cs2cs.exe EPSG:25832 EPSG:23032
687071.44       6210141.33
687080.63       6210278.55 0.00

# this is the same transformation, just in it's proj-string form:,
> cct +proj=pipeline +step +inv +proj=utm +zone=32 +ellps=GRS80 +step +proj=utm +zone=32 +ellps=intl
687071.44       6210141.33 0
  687080.6293   6210278.5490        0.0000           inf
```

To fix this `proj_create_crs_to_crs()`, or whatever function it delegates the work to, should provide the transformation that includes the `+proj=cart` steps in the pipeline.

**Comment by kbevers** [comment]
> Are you really sure of that ? I did that way on purpose, based on the fact that in the PROJ 4.6 cycle, pj_transform() stopped doing geocentric conversion when there was a lack of datum transformation between two CRS.

Yes I am, but I see your point. Your method is probably better in terms of communicating that there is no transformation defined that is valid across all of Europe. But then again, I didn't realize that from the provided output so maybe something else should be added to. I think the string from the `--summary` would be useful in this case. For example:

```
>bin\projinfo.exe -s EPSG:25832 -t EPSG:23032
unknown id, Inverse of UTM zone 32N + Null geographic offset from ETRS89 to ED50 + UTM zone 32N, unknown accuracy, World

PROJ string:
+proj=pipeline +step +inv +proj=utm +zone=32 +ellps=GRS80 +step +proj=utm +zone=32 +ellps=intl

WKT2_2015 string:
Error when exporting to WKT2_2015: Transformation can only be exported to WKT2:2018
```

> By default, projinfo only sets up the coordinate operation finder to return transformations that are valid for the extent of both source and target CRS.

This make sense, although it probably leads to many transformations that are not as good as they could be. Can we make it easier for users to select the correct transformation? Perhaps something like `projinfo --area DK -s EPSG:25832 -t EPSG:23032`? The key here being the textual representation of a bounding box (who can remember the bounds of the country they live in?). I have no idea if the EPSG registry makes this possible or if it would require some additional work by us. If the latter is the case it shouldn't be prioritized at the moment but if it is fairly easy it could be a nice feature I think.

On a side note, what does it take for an operation to have a "known id" in the summary string?

**Comment by kbevers** [comment]
> But looks like we are trading garbage result vs (a bit less) garbage result :-)

Yes, that's what I realized as well before writing my above comment :-)

**Comment by kbevers** [comment]
> The database includes
INSERT INTO "area" VALUES('EPSG','1080','Denmark','Denmark - onshore and offshore.',54.36,58.27,3.24,16.51,0);
So I could potentially allow to specify either the short name ( or the EPSG code )

That would be really cool. I guess it would be "projinfo --area Denmark" - that's fine. How would it work with the EPSG code? `projinfo EPSG:1080` would be equivalent to `projinfo -s EPSG:25832 -t EPSG:23032 --bbox 8,55,12,56`?

> It must be an operation that is registered in the database with a code. Here for UTM to UTM, the operation is a synthetic one chaining UTM conversion and geodetic CRS transformations. There's no registered object for that (the number of all possible operations is huge). If you just do geographic CRS to geographic CRS, you'll see the EPSG (or other authority) id.

Makes sense. Thanks for the clarification.

**Comment by rouault** [comment]
> How would it work with the EPSG code? `projinfo EPSG:1080` would be equivalent to `projinfo -s EPSG:25832 -t EPSG:23032 --bbox 8,55,12,56`?

No, EPSG:1080 is an are of use, which can be refered to by multiple CRS or coordinate operations. So you can't use it to define a unique transformation. My thinking was to allow either --area Denmark or --area EPSG:1080, but you'd still need to specify -s and -t.

**Comment by kbevers** [comment]
> No, EPSG:1080 is an are of use, which can be refered to by multiple CRS or coordinate operations. So you can't use it to define a unique transformation.

Of course. It is easy to get confused when operations, CRS's, areas etc follow the same naming convention. In the future it could of course also make sense to allow both `projinfo EPSG:1626` and `cct EPSG:1626` (EPSG:1626 being the transformation ED50 -> ETRS89 in Denmark).

> My thinking was to allow either --area Denmark or --area EPSG:1080, but you'd still need to specify -s and -t.

That sounds like a good idea.

**Comment by rouault** [comment]
>  In the future it could of course also make sense to allow both `projinfo EPSG:1626`

That's actually possible currently for projinfo. You just need to add '-k operation' (k is for kind) to disambiguate the nature of the object to query. Or alternatively you can use `projinfo urn:ogc:def:coordinateOperation:EPSG::1626`

**Comment by kbevers** [comment]
> You just need to add '-k operation' (k is for kind) to disambiguate the nature of the object to query.

Aha, so that's what that's for!
