### ISSUE TITLE
CF projection support

### ISSUE THREAD

**Issue by snowman2** [OSGeo/PROJ#1193]
Are there plans for supporting creating projection objects using CF conventions using logic based in: https://github.com/OSGeo/gdal/blob/master/gdal/frmts/netcdf/netcdfdataset.cpp? If not, is there interest to have this functionality?

**Comment by rouault** [comment]
I don't think this belongs to PROJ. Otherwise we might migrate a lot of CRS functionnality from GDAL that is specific to the way each data format encodes its CRS : old ESRI .prj encoding, Erdas, Panorama, MapInfo, etc...

**Comment by snowman2** [comment]
Fair enough. I think the functionality currently supported is quite a nice set.
