### ISSUE TITLE
pyproj functionality desires

### ISSUE THREAD

**Issue by snowman2** [OSGeo/PROJ#1195]
The features added to proj.4 for WKT support are fantastic! I really like what has been done with the gdalbarn project. This is a "it would be nice if" request. And maybe it has been done already or is in the plans and I am just not finding it.

For the updated version of `pyproj` it would be nice to have some of the features of the GDAL to be able to reconstruct some of the functionality that is contained in other classes such as the rasterio [CRS class](https://github.com/mapbox/rasterio/blob/c13f0943b95c0eaa36ff3f620bd91107aa67b381/rasterio/_crs.pyx) 
or the opendatacube [CRS class](https://github.com/opendatacube/datacube-core/blob/83bae20d2a2469a6417097168fd4ede37fd2abe5/datacube/utils/geometry/_base.py
) . To do this, it would be nice to have similar functionality in `proj.h`.

#### More useful features
- OSRIsGeographic
- OSRIsProjected
- OSRAutoIdentifyEPSG
#### Less important, but would be nice
- OSRGetAttrValue
- OSRGetSemiMajor
- OSRGetSemiMinor
- OSRGetInvFlattening

**Comment by kbevers** [comment]
Without being an expert in the recent gdalbarn developments (or GDAL for that matter) I think `proj_obj_get_type()` should be able to do what `OSRIsGeographic` and `OSRIsProjected` does. There's also `proj_angular_output()`. I believe `proj_obj_get_id_code()` is what you are looking for as a replacement for `OSRAutoIdentifyEPSG`.

`proj_obj_ellipsoid_get_parameters()` does most of what you ask for in the less important department.

**Comment by snowman2** [comment]
Thanks @kbevers, I will take a look at those functions. They definitely look like they have what I need.

On another note, I am using `proj_obj_get_id_code` currently and I think it is equivalent to `OSRGetAuthorityCode`. However, it does not currently seem to find the EPSG code for some reason. So, my next guess was that `OSRAutoIdentifyEPSG` would be needed in this case? 
```python
if OSRAutoIdentifyEPSG(osr) == 0:
    epsg_code = OSRGetAuthorityCode(osr, NULL)
```
Or definitely could be something on my end. This is how I am currently using it:
```python
code = proj_obj_get_id_code(proj_obj, 0)
```

**Comment by snowman2** [comment]
@kbevers all the functions you recommended worked great with the exception of the `proj_obj_get_id_code` function. Thanks for pointing them out!

**Comment by kbevers** [comment]
@snowman2 	Note that there's also `proj_obj_get_id_auth_name()`. Perhaps that is useful in combination with `proj_obj_get_id_code()`?

**Comment by snowman2** [comment]
No, that does not seem to provide the needed information. It just says EPSG on it.

What I want to happen occurs in test_c_api.cpp:
```
    auto code = proj_obj_get_id_code(obj, 0);
    ASSERT_TRUE(code != nullptr);
    EXPECT_EQ(code, std::string("4326"));
```
