### ISSUE TITLE
proj_obj_get_id_code not seeming to find epsg code

### ISSUE THREAD

**Issue by snowman2** [OSGeo/PROJ#1196]
In the process of updating `pyproj` I am using proj_obj_get_id_code currently and I think it is equivalent to OSRGetAuthorityCode. However, it does not currently seem to find the EPSG code for some reason. It works in your tests, so I am confused at his point. My next guess was that an equivalent to OSRAutoIdentifyEPSG would be needed in this case?
```python
if OSRAutoIdentifyEPSG(osr) == 0:
    epsg_code = OSRGetAuthorityCode(osr, NULL)
```
Or definitely could be something on my end. This is how I am currently using it:
```python
code = proj_obj_get_id_code(proj_obj, 0)
```
Test output:
```
>>> import pyproj
>>> proj = pyproj.Proj(init='epsg:4326', preserve_units=True)
>>> proj.to_string(5)
'+proj=pipeline +step +proj=longlat +ellps=WGS84 +step +proj=unitconvert +xy_in=rad +xy_out=rad'
>>> proj.to_epsg()
>>> proj = pyproj.Proj(init='epsg:6404', preserve_units=True)
>>> proj.to_string(5)
'+proj=pipeline +step +proj=axisswap +order=2,1 +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=tmerc +lat_0=31 +lon_0=-111.916666666667 +k=0.9999 +x_0=213360 +y_0=0 +ellps=GRS80'
>>> proj.to_epsg()
>>> 
```

**Comment by rouault** [comment]
proj_obj_get_id_code() only returns a code if it is explicitly attached to a CRS object, that is if you created the CRS from the database with proj_obj_create_from_database() or proj_obj_create_from_name(), or if you imported it with WKT and the WKT has a AUTHORITY/ID node. 

See https://github.com/OSGeo/proj.4/commit/696fc1eb108478ae1eeecf6f113a60ff979f0cf9#diff-17dcc1c0a4dbfde0d666b88fbba5d881R636

On the contrary, if you import from a PROJ string, there's no explicit code attached to it. You may use proj_obj_identify() that will return a list of candidate objects from the database that match the object the most, and is the equivalent of OSRAutoIdentifyEPSG() / OSRFindMatches()

**Comment by snowman2** [comment]
Woohoo, that did it. Thanks @rouault 
```
>>> import pyproj
>>> prj = pyproj.Proj('+proj=pipeline +step +proj=longlat +ellps=WGS84 +step +proj=unitconvert +xy_in=rad +xy_out=rad', preserve_units=True)
>>> prj.to_epsg()
4326
>>> prj = pyproj.Proj('+init=epsg:4326', preserve_units=True)
>>> prj.to_epsg()
4326
```
Are they returned in order so that if I pick the first one it will be the most likely candidate?
```python
        cdef PJ_OBJ_LIST * proj_list
        proj_list  = proj_obj_identify(self.projctx,
            self.projobj,
            b"EPSG",
            NULL,
            NULL
        )
        cdef PJ_OBJ* proj_obj
        proj_obj = proj_obj_list_get(self.projctx, proj_list, 0)
        cdef const char* code
        code = proj_obj_get_id_code(proj_obj, 0)

```

**Comment by snowman2** [comment]
Okay, good to know. Thanks for your assistance!

**Comment by snowman2** [comment]
The current version of what I am working on is at is [here](https://github.com/snowman2/pyproj/blob/f64d1493517d754c3e0e5f8cbe9265b60c95590f/pyproj/_proj.pyx#L237-479). I am hopefully doing error/memory handling okay, but I may be missing pieces. If you have any suggestions or notice any glaring issues (i am not freeing something I should be), please let me know. Thanks!

**Comment by rouault** [comment]
The Doxygen doc of the functions in c_api.cpp should tell you what to free with which function

**Comment by snowman2** [comment]
Yes, the documentation is fantastic and very useful for finding the information about freeing memory. I read through them for the functions I was using after I saw the one you posted earlier. But, always good to have a second set of eyes for QC - definitely not required though as I know y'all are busy. Thanks again for your help navigating the API!
