### ISSUE TITLE
pj_get_spheroid_defn add to proj.h?

### ISSUE THREAD

**Issue by snowman2** [OSGeo/PROJ#1211]
I have been looking around and have seen that most of cartopy is convertible to the new API in proj.4. However, I cannot seem to find an equivalent for `pj_get_spheroid_defn`. If there is one, feel free to share. If not, would you be interested in adding it to `proj.h`?

Thanks for your helpful responses & happy new year :tada: !

**Comment by kbevers** [comment]
There's `proj_get_ellipsoid()` and `proj_ellipsoid_get_parameters()` which in combination should give you similar functionality. See the tests for examples:

https://github.com/OSGeo/proj.4/blob/5b5c788bedfd3aabe9902bf6a99bfcdc8e7eadb8/test/unit/test_c_api.cpp#L898-L928

@rouault We have the [`PJ_ELLPS`](https://proj4.org/development/reference/datatypes.html#c.PJ_ELLPS) struct for holding info relating to ellipsoids - any particular reason you didn't use that for `proj_ellipsoid_get_parameters()`? To me it seems more clean to just return a struct containing all the available ellipsoid parameters. For instance:

```
PJ_ELLPS ellps = proj_ellps_params(ctx, P);
printf("a: %f, b: %f\n", ellps.major, ellps.minor);
```

Of course `PJ_ELLPS` would have to be extended to include more parameters than it holds currently.

**Comment by kbevers** [comment]
> any particular reason you didn't use that for proj_ellipsoid_get_parameters()?

I guess I can answer that myself... PJ_ELLPS is storing the values as strings which is not that nice. We *can* change the struct since there are not legacy API constraints but that may not be the best idea.

**Comment by snowman2** [comment]
Thanks @kbevers, that definitely does the trick!
