### ISSUE TITLE
add notes in proj.h to clarify what functions work with PJ objects created with proj_create versus PJ objects created with proj_create_from_user_input

### ISSUE THREAD

**Issue by snowman2** [OSGeo/PROJ#1213]
PJ object created with `proj_create()` do not play well with the other functions that used to have the proj_obj namespace (i.e. objects created with `proj_create_from_user_input()`).

Also, PJ objects created with `proj_create_from_user_input()` do not play well with functions that were meant to be used with PJ objects created with `proj_create()`.

To prevent confusion, it would be good to have it documented in the proj.h file which functions work best with which PJ objects.

Related to #1208

**Comment by kbevers** [comment]
I think this is a case of "*Don't document the problem, fix it*". I'd much rather see #1214 resolved than this one. If that is not going to happen before the release of 6.0.0 this behaviour should be documented properly which also requires changes to the Sphinx docs and not just the Doxygen comments in `proj.h`.
