### ISSUE TITLE
+units being dropped

### ISSUE THREAD

**Issue by snowman2** [OSGeo/PROJ#1219]
For some reason, the +units are being dropped in the current version PROJ.4 string:
```
$ ./proj_dir/bin/projinfo '+proj=longlat +ellps=krass +units=m +no_defs'
PROJ.4 string:
+proj=longlat +ellps=krass +no_defs
...
```
Is this behavior expected?

**Comment by rouault** [comment]
Yes, units=m makes no sense for proj=longlat that is a geodetic CRS, so with angular units

**Comment by snowman2** [comment]
Okay, that is definitely interesting. For some reason something worked before when exporting to a proj.5 string, but it is not working with the new proj.4 string export. I will have to dig into and and see the what changed. Thanks!
