### ISSUE TITLE
Usage of __attribute__((const)) where it is not applicable

### ISSUE THREAD

**Issue by aaronpuchert** [OSGeo/PROJ#1224]
The attribute is used on numerous member functions, according to the rationale that "this is for getters of immutable [objects]." This is a misunderstanding. Functions marked with `__attribute__((const))` are supposed to be pure functions in the mathematical sense, meaning that they only depend on the parameter *values*. If these are pointers (or references in C++), the function must not depend on the memory referenced by the pointer. Example:

```cpp
const util::optional<common::Scale> &
Ellipsoid::inverseFlattening() PROJ_CONST_DEFN {
    return d->inverseFlattening_;
}
```

The returned value isn't a mathematical function of the value of `this`, because it depends on `this->d`. Generally, member functions declared with `__attribute__((const))` are [not allowed]( https://stackoverflow.com/a/40770330) to access member variables, so they're are essentially `static`.

The [GCC docs](https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html) state clearly:

> Note that a function that has pointer arguments and examines the data pointed to must not be declared const if the pointed-to data might change between successive invocations of the function. In general, since a function cannot distinguish data that might change from data that cannot, const functions should never take pointer or, in C++, reference arguments.

One might argue that the pointed-to data doesn't change between successive invocations, but that is not the case here. Whether objects are immutable is irrelevant:
```cpp
struct ImmutableObject {
    const int value;
    int get() const __attribute__((const)) { return value; }
};

for (int i = 0; i < 10; ++i) {
    ImmutableObject obj{i};
    int j = obj.get();
}
```

The compiler is allowed to assume that `get` always returns the same value, because that value only depends on the parameter value, which is the `this` pointer. In most compilers, the location of `obj` will not change between iterations.

The documentation for Clang is less ambiguous. It translates `__attribute__((const))` to `readnone`, which [means](http://llvm.org/docs/LangRef.html):

> On a function, this attribute indicates that the function computes its result (or decides to unwind an exception) based strictly on its arguments, *without dereferencing any pointer arguments* or otherwise accessing any mutable state (e.g. memory, control registers, etc) visible to caller functions.

The only (inofficial?) exception regarding memory access is that accesses to constant memory are unproblematic, meaning memory that doesn't change over the *entire runtime* of a program.

Note that `__attribute__((pure))` is fine on getter functions, unless they modify `mutable` members.

**Comment by rouault** [comment]
You're right. Fixed per 3fc48e6

**Comment by aaronpuchert** [comment]
ICC was apparently giving a hint:

```cpp
// If using __attribute__((const)), ICC on an expression like
// Angle(x).getSIValue() will create the object, destroy it and then call
// getSIValue(). Fallback to ((pure)), which is weaker
```

This isn't a compiler bug, it's exactly what `__attribute__((const))` means. Other compilers might also do this in the future.

**Comment by aaronpuchert** [comment]
Thanks for fixing this so quickly!
