### ISSUE TITLE
Change of behaviour in cs2cs in master regarding datum transforms

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#1229]
The cs2cs manual has an example for `cs2cs +proj=latlong +datum=NAD83 +to +proj=utm +zone=10 +datum=NAD27 `

In master, this no longer outputs the results mentionned in the manual.
The reason is simple: when proj_create_crs_to_crs() computes the transform between 2 CRS, given that there is no area of use, it defaults to doing a null geographic shift between the 2 datums since selecting one of the potential grids (USA, Canada, ...) requires an area of use to be set, whereas the old code using the early-binding approach, had an hardcoded `+nadgrids=@conus,@alaska,@ntv2_0.gsb,@ntv1_can.dat` for the +datum=NAD27 expansion, which did the job in practice.

The issue goes beyond this particular case and extend to situations where a +towgs84 was for exemple selected (potentially wrongly) for a EPSG CRS definition, and where there is now several candidates depending on the area of use.

In the cs2cs case, a potential solution would be to compute the best pipeline for each input coordinate, doing first an approximate coordinate transformation from the input coordinate to geographic coordinates to compute the bounding box of the area of use, passing it to proj_create_crs_to_crs and then doing the actual coordinate trannsformation . This would have of course non neglectable runtime cost.

Actually in my GDAL branch, I've implemented a strategy in the OGRCTProj class that does coordinate transformation to precompute all the potential pipelines, and reproject the bounding box of their area of use to the input CRS, which then speeds up selection of the appropriate pipeline (just point-in-rectangle tests)

I'm wondering if this logic shouldn't be ported to PROJ itself:
* proj_create_crs_to_crs() would precompute the potential pipelines and store them in PJ, when no area of use is passed and that several candidate coordinate operations are returned in the PROJ_SPATIAL_CRITERION_PARTIAL_INTERSECTION mode.
* proj_trans() would select the appropriate pipeline from the cached ones. (One potential oddity of this is that proj_pj_info(P).definition would change after running proj_trans())

**Comment by rouault** [comment]
@kbevers Thoughts ?

**Comment by rouault** [comment]
Just wanting to raise the issue as I believe that people are going to complain about this (they complain even when results change in the direction of a better accuracy :-)).

In that case, a workaround for people wanting a behavior similar to previous versions is to add an override transform in the database with the combined multigrid strategy @conus,@alaska,@ntv2_0.gsb,@ntv1_can.dat for NAD27->NAD83 on the total area of use of both CRS. (but that's not immediately trivial)

I let this ticket open for now.

**Comment by kbevers** [comment]
>  believe that people are going to complain about this (they complain even when results change in the direction of a better accuracy :-)).

I agree with this - both parts :-)

I feel you may have misunderstood me. I am in favour of the solution you proposed since I can't see any other way to solve this problem. I would prefer if there was a better way to go about it but as always the past puts constraints on solution. As far as I can tell, with your proposal the `cs2cs +proj=latlong +datum=NAD83 +to +proj=utm +zone=10 +datum=NAD27` command would yield results similar, if not identical, to what cs2cs from <5.2 delivers. In the end that is what matters.

**Comment by busstoptaktik** [comment]
@rouault said:

> reproject the bounding box of their area of use to the input CRS, which then speeds up selection of the appropriate pipeline (just point-in-rectangle tests)

This sounds a bit puzzling, since in general a rectangle (bounding box) in one system does not translate into a rectangle in another. I suppose it works in your implementation, but how?

**Comment by rouault** [comment]
> since in general a rectangle (bounding box) in one system does not translate into a rectangle in another

Yes, it takes sampling points along the bounding box expressed in long/lat, reproject them in the source CRS (resp. target CRS), and consider the bounding box of their reprojected coordinates. This is an approximation of course. Will not work in all cases, but should help for most common situations
