### ISSUE TITLE
nad2bin being run while building prevents cross compiling

### ISSUE THREAD

**Issue by 3nids** [OSGeo/PROJ#1235]
I am trying to compile Proj 5.2 for Android and I am facing this error:

![image](https://user-images.githubusercontent.com/127259/51610848-c901d880-1eeb-11e9-939a-6d7e9bf951e5.png)

It tries to run nad2bin on the environnement, but nad2bin has been compiled for Android.

What is the proper approach?
I am using autotools, but I failed to disable building nad2bin (is it possible?). But is it the right approach?

**Comment by 3nids** [comment]
and if I try with cmake, here is the issue I have
![image](https://user-images.githubusercontent.com/127259/51616227-a07fdb80-1ef7-11e9-84d9-ba865cf5c0e6.png)
although I tried to disable the tests:
`cmake -DCMAKE_INSTALL_PREFIX:PATH=$STAGE_PATH -DBUILD_GTEST=OFF -DPROJ_TESTS=OFF -DBUILD_NAD2BIN=OFF $BUILD_proj`

**Comment by kbevers** [comment]
I haven't got an answer to your question. But I have a counter-question to my fellow PROJ developers: Do we still have a need for `nad2bin`? We have moved all grids, except `null`, to https://github.com/OSGeo/proj-datumgrid where we manage the grids in binary form. I can't see why we would stille keep it around except for building `null` from `null.lla` but we can get around that by just distributing the `null` grid in binary form.

@rouault @sebastic thoughts?

**Comment by sebastic** [comment]
`nad2bin` is required to convert the `.lla` sources, this is part of the proj-datumgrid build process. I strongly object to keeping only the binaries and removing `nad2bin`. The `.lla` files are the preferred form for modification.

The Debian package for PROJ 5.2 builds fine on arm*, including tests.

This issue doesn't have enough information to determine what causes the issue. It may be a cross-compilation issue.

**Comment by kbevers** [comment]
> nad2bin is required to convert the .lla sources, this is part of the proj-datumgrid build process.

We can move `nad2bin` to proj-datumgrid. I feel like it has served it's purpose as part of the main PROJ package now that all the *.lla files have moved elsewhere.

**Comment by 3nids** [comment]
@sebastic I'd be happy to provide more info, what would you need? Or do you have a reference to a script that build on arm? cheers!

**Comment by rouault** [comment]
@sebastic It compiles *on* ARM in the Debian case. Not cross-compilation ?

I can indeed see that nad/Makefile.am assumes to be able to run the nad2bin executable that it has compiled, which can be problematic with cross-compilation indeed. But I don't see why it would have worked better in 4.9 as you mentionned in your email @3nids . Maybe you need to tweak nad/Makfile.am to run a nad2bin executable of the architecture on which you build on.

**Comment by sebastic** [comment]
> We can move `nad2bin` to proj-datumgrid. I feel like it has served it's purpose as part of the main PROJ package now that all the *.lla files have moved elsewhere.

In my opinion it belongs in the PROJ source tree. No need to complicate the proj-datumgrid project by having to build C programs.

> @sebastic I'd be happy to provide more info, what would you need?

Details about your build environment & full build logs for starters.

> Or do you have a reference to a script that build on arm?

See the Debian package sources.

> It compiles on ARM in the Debian case. Not cross-compilation ?

**On**, build and target architectures are the same. There are arm64 build daemons that also build armhf packages.

**Comment by 3nids** [comment]
Maybe asking this differently, is there a way to use the cmake option `BUILD_NAD2BIN=OFF` with autotools?
I tried `--without-nad2bin` and `--disable-nad2bin` without success.

**Comment by rouault** [comment]
> Maybe asking this differently, is there a way to use the cmake option `BUILD_NAD2BIN=OFF` with autotools?
> I tried `--without-nad2bin` and `--disable-nad2bin` without success.

No, you'll have to hack into nad/Makefile.am to disable the use of nad2bin

**Comment by 3nids** [comment]
Thanks @rouault 
I gave it a try but changing the Makefile requires having automake-1.16 and I am running this on xenial where it is not available....I might wait for this to land in master! Thanks again

**Comment by rouault** [comment]
> I gave it a try but changing the Makefile requires having automake-1.16 and I am running this on xenial where it is not available...

I'm running Xenial too. No problem for me with hacking Makefile.am. You probably just need to run ./autogen.sh

**Comment by ndarilek** [comment]
Any chance this might land in a release soon? I just encountered it myself under the exact same circumstances--attempting to cross-compile from Ubuntu to Android.

Thanks!

**Comment by QuLogic** [comment]
See #1267.
