### ISSUE TITLE
projinfo returns invalid +towgs84 value for epsg:3068

### ISSUE THREAD

**Issue by mj10777** [OSGeo/PROJ#1245]
Based on the entries found in the proj.db as of this morning:

./projinfo --main-db-path "../share/proj/proj.db"  -o all EPSG:3068

EPSG:3036 ('Soldner Berlin') seems to be picking out 'EPSG	15869	DHDN to WGS 84 (3)	' because it is geographicly inside that given area (EPSG	1343	Germany - East Germany all states	Germany).
* causing : '+towgs84=612.4,77,440.2,-0.054,0.057,-2.797,2.55' to be used (for Gauss-Kruger, with Krassowsky 1940)
Correct would be EPSG	1777	DHDN to WGS 84 (2),
* '+towgs84=598.1,73.7,418.2,0.202,0.045,-2.455,6.7' (for Cassini-Soldner and Gauss-Kruger, with Bessel 1841)  and was the value used in previous versions
EPSG:3036 ('Soldner Berlin')  has its one area defined in the 'area' TABLE
* EPSG	2898	Germany - Berlin	Germany - Berlin.
--> which is inside the 'EPSG	1343	Germany - East Germany all states	Germany' area

PROJ.4 string:
+proj=cass +lat_0=52.4186482777778 +lon_0=13.6272036666667 +x_0=40000 +y_0=10000 +ellps=bessel +towgs84=612.4,77,440.2,-0.054,0.057,-2.797,2.55 +units=m +no_defs +type=crs

WKT1_GDAL:
PROJCS["DHDN / Soldner Berlin",
    GEOGCS["DHDN",
        DATUM["Deutsches_Hauptdreiecksnetz",
            SPHEROID["Bessel 1841",6377397.155,299.1528128,
                AUTHORITY["EPSG","7004"]],
            TOWGS84[612.4,77,440.2,-0.054,0.057,-2.797,2.55],
            AUTHORITY["EPSG","6314"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4314"]],
    PROJECTION["Cassini_Soldner"],
    PARAMETER["latitude_of_origin",52.4186482777778],
    PARAMETER["central_meridian",13.6272036666667],
    PARAMETER["false_easting",40000],
    PARAMETER["false_northing",10000],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AUTHORITY["EPSG","3068"]]

---------------------------------------
previous GDAL versions:

PROJCS["DHDN / Soldner Berlin",
    GEOGCS["DHDN",
        DATUM["Deutsches_Hauptdreiecksnetz",
            SPHEROID["Bessel 1841",6377397.155,299.1528128000008,
                AUTHORITY["EPSG","7004"]],
            TOWGS84[598.1,73.7,418.2,0.202,0.045,-2.455,6.7],
            AUTHORITY["EPSG","6314"]],
        PRIMEM["Greenwich",0],
        UNIT["degree",0.0174532925199433],
        AUTHORITY["EPSG","4314"]],
    PROJECTION["Cassini_Soldner"],
    PARAMETER["latitude_of_origin",52.41864827777778],
    PARAMETER["central_meridian",13.62720366666667],
    PARAMETER["false_easting",40000],
    PARAMETER["false_northing",10000],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AUTHORITY["EPSG","3068"]]

**Comment by rouault** [comment]
Projected CRS EPSG:3068 "DHDN / Soldner Berlin" has AREA["Germany - Berlin"],                BBOX[52.33,13.09,52.65,13.76]]

Operation EPSG:15869 "DHDN to WGS 84 (3)" has AREA["Germany - East Germany all states"],                BBOX[50.2,9.92,54.74,15.04]], with an accuracy of 2 m

Operation EPSG:1777 "DHDN to WGS 84 (2)" has AREA["Germany - West Germany all states"],                BBOX[47.27,5.87,55.09,13.84]], with an accuracy of 3m

So selecting  "DHDN to WGS 84 (3)"  seems a better fit than "DHDN to WGS 84 (2)". I don't see why the new behaviour would be wrong ? Seems to me to be more correct than was done before

**Comment by mj10777** [comment]
There is a almost a half meter difference between the 2.
Soldner Berlin uses bessel (as did West Germany and the whole of Berlin)  and the other (East) German ones use Krassoaski.

**Comment by rouault** [comment]
> Soldner Berlin uses bessel (as did West Germany and the whole of Berlin) and the other (East) German ones use Krassoaski.

Hum, so you're meaning that for political/historical reasons, Soldner Berlin should use the transformations associated to West Germany. Interesting... Is there any authority that states this ? I'm not sure how we can handle that...

**Comment by mj10777** [comment]
The difference is based on the value when used with the beta2007 grid (0.15 and 0,49)

**Comment by rouault** [comment]
OK, so just use the grid then. Using the CRS PROJ string or the GDAL WKT1 grid is legacy behaviour. If the grid is available in your installation, it will be used

```
$ src/projinfo -s  EPSG:3068 -t EPSG:4326
-------------------------------------
Operation n°1:

unknown id, Inverse of Soldner Berlin + DHDN to WGS 84 (4), 1 m, Germany - onshore

PROJ string:
+proj=pipeline +step +proj=axisswap +order=2,1 +step +inv +proj=cass +lat_0=52.4186482777778 +lon_0=13.6272036666667 +x_0=40000 +y_0=10000 +ellps=bessel +step +proj=hgridshift +grids=BETA2007.gsb +step +proj=unitconvert +xy_in=rad +xy_out=deg +step +proj=axisswap +order=2,1
```

**Comment by mj10777** [comment]
gauss kruger also  used bessel before the soviets intoduced  Krassowski inside the warsaw packt. That is why thetre are Pulkovo and dhdn for the same zones.

**Comment by mj10777** [comment]
And when not installed?

**Comment by mj10777** [comment]
When no towgs or grid the difference is 196.0 meters

**Comment by rouault** [comment]
> And when not installed?

Not having grids is a degraded behaviour. I don't discard your concern about this case, but I would welcome authoritative evidence than we actually need to have a special case here. That would probably require adding a new table in the database to associate (or exclude) transformations for particular CRS tuples, and dedicated code to handle that. Not something trivial

**Comment by mj10777** [comment]
I have a bad internet connection (box is broken), so I cannot look for the link. Somewhere I have the documentation as pdf (in german) which I will send.

**Comment by dg0yt** [comment]
> Not having grids is a degraded behaviour

Where is this documented or logged?

I now found from git that former "stand-alone" CRS based on the Potsdam datum require the BETA2007.gsb file from proj-datumgrids since 5.0.0 ([OSGeo/proj.4@3b95052](https://github.com/OSGeo/proj.4/commit/3b95052), [OSGeo/proj.4@09f9727](https://github.com/OSGeo/proj.4/commit/09f9727)). Unfortunately this is not mentioned in the changelogs/news and thus going unnoticed until someone/some unit test happens to check these CRS.
- https://github.com/OpenOrienteering/mapper/issues/1207
- Fedora has [updated from 4.9 to 5.2 (and to datumgrids 1.8)](https://src.fedoraproject.org/rpms/proj/c/29b6a3295a2eaad3dc837889731be9cbca45d95a?branch=master), but didn't package the new grids, and they don't seem to run the tests. I'm unwilling to create another account just to report this to Fedora. But I would kindly asked PROJ to make the changed requirements explicit in the news/changelog.

**Comment by kbevers** [comment]
> Where is this documented or logged?

Here https://proj4.org/resource_files.html and here https://github.com/OSGeo/proj.4/blob/master/README.md

> * Fedora has [updated from 4.9 to 5.2 (and to datumgrids 1.8)](https://src.fedoraproject.org/rpms/proj/c/29b6a3295a2eaad3dc837889731be9cbca45d95a?branch=master), but didn't package the new grids, and they don't seem to run the tests.

If they didn't include the grids then I think it is wrong of them to claim that they upgraded to datumgrids 1.8. And things are bound to go wrong if they don't run the tests.

> * But I would kindly asked PROJ to make the changed requirements explicit in the news/changelog.

I would suggest you take a look at the two links above and if you still feel that it is necessary to improve the installation guidelines please open a PR with your proposed improvements. I am more than happy to accept such a PR!

**Comment by dg0yt** [comment]
https://github.com/OSGeo/proj.4/blob/master/README.md doesn't give explicit information. All you find is "In addition to the PROJ software package, distributions of datum conversion grid files and PROJ parameter files are also available" and "The regional packages contain resources that are not essential", somewhat indicating that the non-regional package might be essential.

https://proj4.org/resource_files.html makes it explicitly, indeed:
>  "For a functioning PROJ installation of the proj-datumgrid is needed."

But this is not the first place where I did look for changes or usage requirements. On
https://proj4.org/install.html#compilation-and-installation-from-source-code, I now find explicit statements in the autotools section:
> Before proceeding with the installation we need to add the datum grids. ... Alternatively the grids can be installed manually in the directory pointed to by the PROJ_LIB environment variable.

> The test suite requires that the proj-datumgrid package is installed in `PROJ_LIB`.

The CMake section only has the test suite statement.

Summary: 
- My preferred statement is: "For a functioning PROJ installation of the proj-datumgrid is needed."
- I still think there should be a changelog/news entry. However, I don't know how much the requirement was valid before 5.0.0.

FTR Fedora runs tests but ignores the result (` || exit 0` :bomb: )

**Comment by kbevers** [comment]
> * I still think there should be a changelog/news entry. However, I don't know how much the requirement was valid before 5.0.0.

Also required before 5.0, although there were probably less consequences of not installing the grids back then compared to now. And in any case, I don't want to issue retroactive changes to the release notes. I agree that the installation description should be more clear in this regard.

**Comment by QuLogic** [comment]
> Fedora has [updated from 4.9 to 5.2 (and to datumgrids 1.8)](https://src.fedoraproject.org/rpms/proj/c/29b6a3295a2eaad3dc837889731be9cbca45d95a?branch=master), but didn't package the new grids, and they don't seem to run the tests. I'm unwilling to create another account just to report this to Fedora. But I would kindly asked PROJ to make the changed requirements explicit in the news/changelog.

See https://src.fedoraproject.org/rpms/proj/pull-requests

**Comment by QuLogic** [comment]
Based on discussions here and on the mailing list, I've updated the above PRs in Fedora so that `proj` Requires `proj-datumgrids`, and Recommends the regional `proj-datumgrids-*`. The former will always be installed, and the latter will be installed by default, but can be skipped if asked (e.g., package builder machines don't install Recommends.)

Does this sound reasonable for upstream? (There's also the even weaker Suggests, which doesn't install at all, but is just sort of there as a hint.)

**Comment by kbevers** [comment]
> Does this sound reasonable for upstream?

Yes

**Comment by kbevers** [comment]
As best as I can tell this issue is resolved.

**Comment by mj10777** [comment]
>> Is there any authority that states this ? 

I assume you mean an authority that states that in the city of Berlin (both East and West) only 'Soldner Berlin' EPSG:3068 was used.

Problem here is (in most cases) this an only be found in German.

 A general overview of  **Bezugssystem 42/83 u. 40/83** can be found here:
* source: State of Brandenburg (which surrounds Berlin)

https://www.geobasis-bb.de/geodaten/bezug-42-83.html

this implies that this system was used, in East Germany (DDR), from some time in the 1950's untill it was phased out in the 1990's.
Berlin itsself is not mentioned.

---
An english based source: **Using Oracle Spatial with Coordinate Systems Based on Any Regional Geodetic Datum** (from I assume 2009)

https://www.fig.net/resources/proceedings/2009/lakebaikal_2009_comm6/papers/04_manthe_clemen_gruendig.pdf

States the reasons (since the 1920's, when most of the Soldner Systems were replaced) why the **Gauß-Krüger** systems where not used:

>> Due to the history and the location of Berlin between two different projection zones
the Berlin Soldner system is still official. It represents a coordinate system with a
special very easy-to-use non-conformal projection developed by the German scientist
Johann Georg Soldner in the 19 th century. The projection used is also well-known and
predefined in Oracle as Cassini projection, which was developed in the 18 th century by
Dominique Cassini in France.

If, at least, the older (pre 1950's) and present **Bessel** values were retrieved (DHDN), then there would be no problem.

But at the moment the **Krassowski** values, which were only in use for about 40 years (and never for 'Soldner Berlin'), are being retrieved.

So the retrieved information is simply incorrect since there is a mixing Ellipsoid values.

Existing POINTS will be incorrectly transformed.

---
>> I'm not sure how we can handle that...

'Soldner Berlin' is defined as being DHDN.
The area is also known **BBOX[52.33,13.09,52.65,13.76]**

So mayby searching for the **smallest** area instead (I assume) the first area found might resolve this.
