### ISSUE TITLE
Pipeline initialized twice

### ISSUE THREAD

**Issue by kbevers** [OSGeo/PROJ#1249]
When creating a pipeline with `cct` (and most likely anything else) it is initialized twice. See this example:

```
$ echo 12 56 0 2000 | ./bin/cct -vvv +proj=pipeline +step +proj=axisswap +order=2,1 +step +proj=utm +zone=32
cct: Running in very verbose mode
pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
pj_ellipsoid - final:
Pipeline: Building arg list for step no. 0
Pipeline: init - proj=axisswap, 2
    order=2,1
pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
pj_ellipsoid - final:    ellps=GRS80
Pipeline: Step 0 (proj=axisswap) at 0x7fc165500b70
Pipeline at [0x7fc1655004b0]:    step at [0x7fc165500b70] (proj=axisswap) done
Pipeline: Building arg list for step no. 1
Pipeline: init - proj=utm, 2
    zone=32
pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
pj_ellipsoid - final:    ellps=GRS80
Pipeline: Step 1 (proj=utm) at 0x7fc1655010e0
Pipeline at [0x7fc1655004b0]:    step at [0x7fc1655010e0] (proj=utm) done
Pipeline: 2 steps built. Determining i/o characteristics
pj_open_lib(proj.db): call fopen(/usr/local/share/proj/proj.db) - succeeded
pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
pj_ellipsoid - final:
Pipeline: Building arg list for step no. 0
Pipeline: init - proj=axisswap, 2
    order=2,1
pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
pj_ellipsoid - final:    ellps=GRS80
Pipeline: Step 0 (proj=axisswap) at 0x7fc165602580
Pipeline at [0x7fc165601f10]:    step at [0x7fc165602580] (proj=axisswap) done
Pipeline: Building arg list for step no. 1
Pipeline: init - proj=utm, 2
    zone=32
pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
pj_ellipsoid - final:    ellps=GRS80
Pipeline: Step 1 (proj=utm) at 0x7fc165602af0
Pipeline at [0x7fc165601f10]:    step at [0x7fc165602af0] (proj=utm) done
Pipeline: 2 steps built. Determining i/o characteristics
Final: proj=pipeline step proj=axisswap order=2,1 step proj=utm zone=32 argc=9 pargc=7
 6231950.5383   1920310.7127        0.0000     2000.0000
```

The memory adresses in the output indicate that there are in fact being created two different pipelines. I guess the second `PJ` creating happens somewhere in the ISO19111 code. I am sure there are good reasons for that but it shouldn't output duplicate debug information. This can probably be avoided by overriding the debugging level in certain parts of the code.

**Comment by kbevers** [comment]
Seems like it is the ISO19111 projstring formatter that is playing tricks on me. It is quite frustrating since I can't control the final pipeline that is generated. Below is an example. I am currently extending the pipeline operation with a coordinate stack that allows overriding results in one step with results from previous steps. Notice the `push=1` and `pop=1` parameters that are passed through in the first version of the pipeline and then discarded in the next version (which instead include extra `unitconvert` steps that is unnecessary in this context).

```
$ echo 12 56 0 2020 |./bin/cct -vvv +proj=pipeline +ellps=GRS80 +step +proj=cart +push=1 +step +proj=helmert +x=1000 +y=2000 +z=3000 +step +proj=cart +pop=1 +inv 
pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
pj_ellipsoid - final:    ellps=GRS80
pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
pj_ellipsoid - final:    ellps=GRS80
Pipeline: Building arg list for step no. 0
Pipeline: init - proj=cart, 3
    push=1
    ellps=GRS80
pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
pj_ellipsoid - final:    ellps=GRS80
Pipeline: Step 0 (proj=cart) at 0x7fed6950def0
Pipeline at [0x7fed6950d620]:    step at [0x7fed6950def0] (proj=cart) done
Pipeline: Building arg list for step no. 1
Pipeline: init - proj=helmert, 5
    x=1000
    y=2000
    z=3000
    ellps=GRS80
pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
pj_ellipsoid - final:    ellps=GRS80
Helmert parameters:
x=  1000.00000  y=  2000.00000  z=  3000.00000
rx=  0.00000  ry=  0.00000  rz=  0.00000
s=   0.00000  exact=0
dx=  0.00000  dy=  0.00000  dz=  0.00000
drx= 0.00000  dry= 0.00000  drz= 0.00000
ds=  0.00000  t_epoch= 0.00000  t_obs= 0.00000
Pipeline: Step 1 (proj=helmert) at 0x7fed6950e4a0
Pipeline at [0x7fed6950d620]:    step at [0x7fed6950e4a0] (proj=helmert) done
Pipeline: Building arg list for step no. 2
Pipeline: init - proj=cart, 4
    pop=1
    inv
    ellps=GRS80
pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
pj_ellipsoid - final:    ellps=GRS80
Pipeline: Step 2 (proj=cart) at 0x7fed6950ebb0
Pipeline at [0x7fed6950d620]:    step at [0x7fed6950ebb0] (proj=cart) done
Pipeline: 3 steps built. Determining i/o characteristics
pj_open_lib(proj.db): call fopen(/usr/local/share/proj/proj.db) - succeeded
pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
pj_ellipsoid - final:    ellps=GRS80
pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
pj_ellipsoid - final:
Pipeline: Building arg list for step no. 0
Pipeline: init - proj=unitconvert, 3
    xy_in=deg
    xy_out=rad
pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
pj_ellipsoid - final:    ellps=GRS80
xy_in unit: Degree
xy_out unit: Radian
Pipeline: Step 0 (proj=unitconvert) at 0x7fed695136f0
Pipeline at [0x7fed69512f90]:    step at [0x7fed695136f0] (proj=unitconvert) done
Pipeline: Building arg list for step no. 1
Pipeline: init - proj=cart, 2
    ellps=GRS80
pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
pj_ellipsoid - final:    ellps=GRS80
Pipeline: Step 1 (proj=cart) at 0x7fed69513c80
Pipeline at [0x7fed69512f90]:    step at [0x7fed69513c80] (proj=cart) done
Pipeline: Building arg list for step no. 2
Pipeline: init - proj=helmert, 4
    x=1000
    y=2000
    z=3000
pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
pj_ellipsoid - final:    ellps=GRS80
Helmert parameters:
x=  1000.00000  y=  2000.00000  z=  3000.00000
rx=  0.00000  ry=  0.00000  rz=  0.00000
s=   0.00000  exact=0
dx=  0.00000  dy=  0.00000  dz=  0.00000
drx= 0.00000  dry= 0.00000  drz= 0.00000
ds=  0.00000  t_epoch= 0.00000  t_obs= 0.00000
Pipeline: Step 2 (proj=helmert) at 0x7fed69514250
Pipeline at [0x7fed69512f90]:    step at [0x7fed69514250] (proj=helmert) done
Pipeline: Building arg list for step no. 3
Pipeline: init - inv, 3
    proj=cart
    ellps=GRS80
pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
pj_ellipsoid - final:    ellps=GRS80
Pipeline: Step 3 (inv) at 0x7fed69514920
Pipeline at [0x7fed69512f90]:    step at [0x7fed69514920] (inv) done
Pipeline: Building arg list for step no. 4
Pipeline: init - proj=unitconvert, 3
    xy_in=rad
    xy_out=deg
pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
pj_ellipsoid - final:    ellps=GRS80
xy_in unit: Radian
xy_out unit: Degree
Pipeline: Step 4 (proj=unitconvert) at 0x7fed69514e90
Pipeline at [0x7fed69512f90]:    step at [0x7fed69514e90] (proj=unitconvert) done
Pipeline: 5 steps built. Determining i/o characteristics
Transformation parameters for observation t_obs=2020 (t_epoch=0):
x: 1000
y: 2000
z: 3000
s: 0
rx: 0
ry: 0
rz: 0
theta: 0
Rotation Matrix:
  |      1       0      -0 |
  |     -0       1       0 |
  |      0      -0       1 |
```

Do I need to do something special to allow my new parameters `push` and `pop` to pass through the projstring formatter? They seem to only be gobbled away in some cases (likely caused by the `helmert` step).

Unrelated: The debug output really needs a clean up!

**Comment by rouault** [comment]
> Do I need to do something special to allow my new parameters `push` and `pop` to pass through the projstring formatter? They seem to only be gobbled away in some cases (likely caused by the `helmert` step).

Ah yes, there's logic in PROJStringParser::createFromPROJString() to detect this particular construct ( cart, helpert, inv cart ) and build a proper Transformation object from it. Look for the call to buildHelmertTransformation() in io.cpp. Currently it ignores the push / pop flags. If there are here, we might want to instanciate a Helmert transformation object in the Geographic 2D domain ( EPSG_CODE_METHOD_POSITION_VECTOR_GEOGRAPHIC_2D, EPSG_CODE_METHOD_COORDINATE_FRAME_GEOGRAPHIC_2D or EPSG_CODE_METHOD_GEOCENTRIC_TRANSLATION_GEOGRAPHIC_2D )  and its export to PROJ string (in  Transformation::_exportToPROJString() ) should re-add them.

**Comment by kbevers** [comment]
> Ah yes, there's logic in PROJStringParser::createFromPROJString() to detect this particular construct ( cart, helpert, inv cart ) and build a proper Transformation object from it. Look for the call to buildHelmertTransformation() in io.cpp. Currently it ignores the push / pop flags. Currently it ignores the push / pop flags.

Okay, I'll have a look around and see if I can figure it out. Thanks for the hints.

> If there are here, we might want to instanciate a Helmert transformation object in the Geographic 2D domain ( EPSG_CODE_METHOD_POSITION_VECTOR_GEOGRAPHIC_2D, EPSG_CODE_METHOD_COORDINATE_FRAME_GEOGRAPHIC_2D or EPSG_CODE_METHOD_GEOCENTRIC_TRANSLATION_GEOGRAPHIC_2D ) and its export to PROJ string (in Transformation::_exportToPROJString() ) should re-add them.

I don't understand what this means.

I've open a PR with my preliminary work so you can get a feel for what I am doing: https://github.com/OSGeo/proj.4/pull/1250

**Comment by kbevers** [comment]
But anyway, back to the real topic of this issue. Is there anything that can be done to avoid the double-instantiation of pipelines in `cct`? E.g. is there a `proj_create`-type function left that doesn't go through the ISO19111 code and just sets up the "raw" pipeline as written by the caller? That may be more suitable for a bare-bones, close-to-the-metal application like `cct`.

**Comment by rouault** [comment]
> is there a `proj_create`-type function left that doesn't go through the ISO19111 code and just sets up the "raw" pipeline as written by the caller?

Yes, pj_create_internal() but it isn't CPL_DLL exported right now, and it would probably be preferable not doing so.
What you observe is that pj_create_internal() is currently called by PROJStringParser::createFromPROJString() in io.cpp to validate that the string is valid from what used to be the C part of PROJ, and then it is also called in pj_obj_create() in c_api.cpp. It is not obvious to me how to prevent this double call. But we could probably shut up logging in the pj_obj_create() path since that one is an internal implementation detail from the user point of view.

**Comment by kbevers** [comment]
> What you observe is that pj_create_internal() is currently called by PROJStringParser::createFromPROJString() in io.cpp to validate that the string is valid from what used to be the C part of PROJ, and then it is also called in pj_obj_create() in c_api.cpp. It is not obvious to me how to prevent this double call.

I figured it was something like that. 

> But we could probably shut up logging in the pj_obj_create() path since that one is an internal implementation detail from the user point of view.

Isn't the `PJ` returned by `pj_ob_create` the one that eventually get's used by `cct` (and others)? Logging should not be turned of for that one, rather the the one used for verifying the proj-string.

**Comment by rouault** [comment]
> Isn't the `PJ` returned by `pj_ob_create` the one that eventually get's used by `cct` (and others)? Logging should not be turned of for that one, rather the the one used for verifying the proj-string.

yeah, probably makes more sense

**Comment by kbevers** [comment]
Fixed in https://github.com/OSGeo/proj.4/pull/1250/commits/54df6833b2f7f1907e16ada7c52f136da2668dbb
