### ISSUE TITLE
Add geodesic.h to sphinx documentation

### ISSUE THREAD

**Issue by kbevers** [OSGeo/PROJ#1258]
The only documentation of `geodesic.h` around is found in `man/man3/geodesic.3` which is quite brief. A page in the sphinx documentation that describes the functions in `geodesic.h` should be added. `man/man3/geodesic.3` should be replaced by a man page automatically created from the sphinx docs. Or possibly just removed altogether.

**Comment by kbevers** [comment]
@cffk how would you feel about removing `man/man3/geodesic.3` from the source distribution? It is sort of an outlier alongside with `man/man3/pj_init.3` since we do not provide man3 files for other header files from the library. `pj_init.3` will disappear with PROJ 7 which only leaves `geodesic.3` behind. All the other man files we distribute is automatically generated from the Sphinx docs and unfortunately I forget to update version numbers etc in the .3-files every other release...

**Comment by cffk** [comment]
Yes it's OK to remove geodesic.3
