### ISSUE TITLE
CMake's ability to find SQLite3

### ISSUE THREAD

**Issue by mwtoews** [OSGeo/PROJ#1266]
I'm having a bit of difficulty sorting out how to fulfill CMake's ability to find the SQLite3 dependency.

On this particular computer, the library is stored in somewhere like `/opt/SQLite/3.25.3` (which has `include`, `lib`, etc.). Currently, there is no clear documentation on how to configure CMake for situations like this, so my best attempt is:
```bash
$ export SQLITE3_INCLUDE_DIRS=/opt/SQLite/3.25.3/include
$ cmake ..
```
But I get a "sqlite3 dependency not found!" error. (Is there a better way to pass vars to CMake?)

Note that CMake found `/opt/SQLite/3.25.3/bin/sqlite3` without issue (via `find_program(EXE_SQLITE3 sqlite3)`, so I'm wondering how difficult it would be to try and add some relative path checks into `cmake/FindSqlite3.cmake`? I've started [a patch](https://github.com/mwtoews/proj.4/tree/cmake) to try to improve the cmake configuration, but I'd appreciate some tips here from the CMake pros.

**Comment by kbevers** [comment]
I am in no way a CMake pro... Have you tried
```
cmake -DSQLITE3_INCLUDE_DIRS=/opt/SQLite/3.25.3/include ..
```

I usually turn to the CI setups when I am in doubt about something related to building PROJ but I see that all on our UNIX-like CI targets it just works out of the box. All it seems to take is to install the sqlite3 package. In some situations a sqlite3-dev packages is also required. I suspect this will work in most cases.

**Comment by mloskot** [comment]
@kbevers Your syntax is almost correct: no plural `S`, but singular `SQLITE3_INCLUDE_DIR`. That is according to the current `FindSqlite3.cmake` module (N.B. this module is not great, should be rewritten as part of #1263).

@mwtoews  CMake accepts configuration variables (aka cache entries) with `-D` option,  see https://cmake.org/cmake/help/latest/manual/cmake.1.html

**Comment by mwtoews** [comment]
Right, thanks all for corrections and tips. Setting only one of `SQLITE3_INCLUDE_DIR` or `DSQLITE3_LIBRARY` did not work, but setting both did work. I.e.:
```
cmake -DSQLITE3_INCLUDE_DIR=/opt/SQLite/3.25.3/include -DSQLITE3_LIBRARY=/opt/SQLite/3.25.3/lib ..
```

@mloskot rewriting `FindSqlite3.cmake` would be nice, as it doesn't seem to find the SQLite3 library for this situation.

I'll assemble a smallish PR to try and document some CMake tips found above.

**Comment by mwtoews** [comment]
With `cmake --build .`, a few related issues appear after a few minutes:
```
...
Scanning dependencies of target cs2cs
[ 78%] Building CXX object src/CMakeFiles/cs2cs.dir/apps/cs2cs.cpp.o
[ 78%] Building CXX object src/CMakeFiles/cs2cs.dir/apps/emess.cpp.o
[ 79%] Linking CXX executable ../bin/cs2cs
../lib/libproj.so.14.0.2: error: undefined reference to 'sqlite3_snprintf'
../lib/libproj.so.14.0.2: error: undefined reference to 'sqlite3_vfs_find'
../lib/libproj.so.14.0.2: error: undefined reference to 'sqlite3_value_type'
../lib/libproj.so.14.0.2: error: undefined reference to 'sqlite3_value_double'
../lib/libproj.so.14.0.2: error: undefined reference to 'sqlite3_value_int64'
../lib/libproj.so.14.0.2: error: undefined reference to 'sqlite3_vfs_register'
../lib/libproj.so.14.0.2: error: undefined reference to 'sqlite3_create_function'
../lib/libproj.so.14.0.2: error: undefined reference to 'sqlite3_open_v2'
../lib/libproj.so.14.0.2: error: undefined reference to 'sqlite3_result_int'
../lib/libproj.so.14.0.2: error: undefined reference to 'sqlite3_result_null'
../lib/libproj.so.14.0.2: error: undefined reference to 'sqlite3_reset'
../lib/libproj.so.14.0.2: error: undefined reference to 'sqlite3_bind_text'
../lib/libproj.so.14.0.2: error: undefined reference to 'sqlite3_bind_double'
../lib/libproj.so.14.0.2: error: undefined reference to 'sqlite3_column_count'
../lib/libproj.so.14.0.2: error: undefined reference to 'sqlite3_step'
../lib/libproj.so.14.0.2: error: undefined reference to 'sqlite3_column_text'
../lib/libproj.so.14.0.2: error: undefined reference to 'sqlite3_prepare_v2'
../lib/libproj.so.14.0.2: error: undefined reference to 'sqlite3_errmsg'
../lib/libproj.so.14.0.2: error: undefined reference to 'sqlite3_finalize'
../lib/libproj.so.14.0.2: error: undefined reference to 'sqlite3_close'
../lib/libproj.so.14.0.2: error: undefined reference to 'sqlite3_vfs_unregister'
../lib/libproj.so.14.0.2: error: undefined reference to 'sqlite3_result_double'
collect2: error: ld returned 1 exit status
gmake[2]: *** [bin/cs2cs] Error 1
gmake[1]: *** [src/CMakeFiles/cs2cs.dir/all] Error 2
gmake: *** [all] Error 2
```
(Note that Autotools' `./configure && make` does not have this issue on this particular computer)
Is there a missing library include path somewhere?

**Comment by mwtoews** [comment]
More info found within the configure:
```
...
-- Configuring done
WARNING: Target "proj" requests linking to directory "/opt/SQLite/3.25.3/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "cs2cs" requests linking to directory "/opt/SQLite/3.25.3/lib".  Targets may link only to libraries.  CMake is dropping the item.
...
```
Also, if it matters:
```bash
$ ls /opt/SQLite/3.25.3/lib
libsqlite3.a   libsqlite3.so    libsqlite3.so.0.8.6
libsqlite3.la  libsqlite3.so.0  pkgconfig
```

**Comment by mloskot** [comment]
@mwtoews  Typically, you either need none or both, `<lib>_INCLUDE_DIR` and `<lib>_LIBRARY`

CMake Find-modules, `Find<lib>.cmake`, are **guessers** and as such they do not guarantee a library will be found - it does not probe all possible variety of locations, environments and systems. That is why Find-modules are hinted with `-D<lib>_INCLUDE_DIR` and `-D<lib>_LIBRARY` locations.

**Comment by mloskot** [comment]
@mwtoews Try

```
VERBOSE=1 make
VERBOSE=1 cmake --build .
```

to see actual compiler/linker commands.

**Comment by mwtoews** [comment]
Ok, I've just understood that `-D<lib>_LIBRARY` want's a library file, not a library directory, therefore `-DSQLITE3_LIBRARY=/opt/SQLite/3.25.3/lib/libsqlite3.so`? Is this too specific for documenting in https://proj4.org/install.html?

**Comment by kbevers** [comment]
> s this too specific for documenting in [proj4.org/install.html](https://proj4.org/install.html)?

No, those are some good hints to add to the CMake section. I often find that things like that is missing from install guides!

**Comment by kbevers** [comment]
If you add a few lines about the sqlite dependency in general you have more or less closed https://github.com/OSGeo/proj.4/issues/1221

**Comment by mloskot** [comment]
@mwtoews 
> I've just understood that `-D<lib>_LIBRARY` want's a library file, not a library directory,

See https://cmake.org/cmake/help/latest/manual/cmake-developer.7.html, specifically:

```
The following names should not usually be used in CMakeLists.txt files, but are typically cache variables for users to edit and control the behaviour of find modules (like entering the path to a library manually)

Xxx_LIBRARY
    The path of the Xxx library (as used with find_library(), for example).
Xxx_Yy_LIBRARY
    The path of the Yy library that is part of the Xxx system. It may or may not be required to use Xxx.
Xxx_INCLUDE_DIR
    Where to find headers for using the Xxx library.
Xxx_Yy_INCLUDE_DIR
    Where to find headers for using the Yy library of the Xxx system. 
```

**Comment by mwtoews** [comment]
This is has been resolved by #1268

Another method to specify [CMAKE_PREFIX_PATH](https://cmake.org/cmake/help/latest/variable/CMAKE_PREFIX_PATH.html) to the custom SQLite3 prefix, e.g. `-DCMAKE_PREFIX_PATH=/opt/SQLite`

**Comment by mloskot** [comment]
FYI, The current module should be replaced with [new FindSQLite3.cmake provided by CMake 3.14](https://gitlab.kitware.com/cmake/cmake/merge_requests/2557).  This is the plan in #1263

**Comment by alionteo** [comment]
@mwtoews If I am on mac machine, where I can find these paths ?

`opt/SQLite/3.25.3/include` and `opt/SQLite/3.25.3/lib ..`

When i do `which sqlite3` I get `/usr/bin/sqlite3`
Thanks

**Comment by mwtoews** [comment]
@alionteo I don't know. Every platform and toolset often require custom attention that only the user of that computer would know (or could find out). This issue was closed by adding details [to this section of the docs](https://proj.org/install.html#build-requirements).
