### ISSUE TITLE
Compile warnings from Intel compilers

### ISSUE THREAD

**Issue by mwtoews** [OSGeo/PROJ#1269]
With Linux Intel compilers, a few warnings are raised:
```
$ cmake -DCMAKE_C_COMPILER=icc -DCMAKE_CXX_COMPILER=icpc ..
$ make
...
In file included from /tmp/src/proj.4/src/jniproj.cpp(45):
/tmp/src/proj.4/src/proj_config.h(32): warning #47: incompatible redefinition of macro "HAVE_PTHREAD_MUTEX_RECURSIVE"
  #define HAVE_PTHREAD_MUTEX_RECURSIVE /**/
          ^
...
In file included from /tmp/src/proj.4/src/mutex.cpp(43):
/tmp/src/proj.4/src/proj_config.h(32): warning #47: incompatible redefinition of macro "HAVE_PTHREAD_MUTEX_RECURSIVE"
  #define HAVE_PTHREAD_MUTEX_RECURSIVE /**/

...
In file included from /tmp/src/proj.4/src/strtod.cpp(41):
/tmp/src/proj.4/src/proj_config.h(32): warning #47: incompatible redefinition of macro "HAVE_PTHREAD_MUTEX_RECURSIVE"
  #define HAVE_PTHREAD_MUTEX_RECURSIVE /**/
...
/tmp/src/proj.4/src/iso19111/io.cpp(289): warning #3924: attribute namespace "clang" is unrecognized
          PROJ_FALLTHROUGH
          ^
...
/tmp/src/proj.4/src/iso19111/io.cpp(297): warning #3924: attribute namespace "clang" is unrecognized
          PROJ_FALLTHROUGH
          ^
...
```
No errors are raised, and all tests pass!

---

With GCC 7.1 on the same system, some similar warnings are also raised:
```
...
In file included from /tmp/src/proj.4/src/jniproj.cpp:45:0:
/tmp/src/proj.4/src/proj_config.h:32:0: warning: "HAVE_PTHREAD_MUTEX_RECURSIVE" redefined
 #define HAVE_PTHREAD_MUTEX_RECURSIVE /**/
 
<command-line>:0:0: note: this is the location of the previous definition
[ 20%] Building CXX object src/CMakeFiles/proj.dir/mutex.cpp.o
In file included from /tmp/src/proj.4/src/mutex.cpp:43:0:
/tmp/src/proj.4/src/proj_config.h:32:0: warning: "HAVE_PTHREAD_MUTEX_RECURSIVE" redefined
 #define HAVE_PTHREAD_MUTEX_RECURSIVE /**/
 
<command-line>:0:0: note: this is the location of the previous definition
...
In file included from /tmp/src/proj.4/src/strtod.cpp:41:0:
/tmp/src/proj.4/src/proj_config.h:32:0: warning: "HAVE_PTHREAD_MUTEX_RECURSIVE" redefined
 #define HAVE_PTHREAD_MUTEX_RECURSIVE /**/
 
<command-line>:0:0: note: this is the location of the previous definition
...
```
Similarly, no errors are raised, and all tests pass.

**Comment by kbevers** [comment]
I have seen these from time to time as well but haven't been able to get rid of them succesfully yet. Unfortunately I can't remember which combination of compiler and operating system I saw the warnings on so I am having a hard time debugging this at the moment.

**Comment by mwtoews** [comment]
There are two issues here. None of them are big, as they are just warnings.

The first issue, related only to Intel, is `warning #3924: attribute namespace "clang" is unrecognized`. This could be related to various define logic in `include/proj/internal/internal.hpp`.

The other issue (that also happens with GCC) is circumstantial, depending on what has been done/built in the source directory. With a clean directory from proj-6.0.0RC1, here is the culprit mix of Autoconf and CMake:
```bash
$ cd /tmp
$ tar xfz proj-6.0.0RC1.tar.gz
$ cd proj-6.0.0/
$ ls src/proj_config.h*
src/proj_config.h.in
$ ./configure > /dev/null  # oh no!
$ ls src/proj_config.h*
src/proj_config.h  src/proj_config.h.in
$ mkdir build && cd build
$ cmake .. > /dev/null
$ cmake --build . > /dev/null 
-- Loading resources from /tmp/proj-6.0.0/build/data/all.sql.in
In file included from /tmp/proj-6.0.0/src/jniproj.cpp:45:0:
/tmp/proj-6.0.0/src/proj_config.h:32:0: warning: "HAVE_PTHREAD_MUTEX_RECURSIVE" redefined
 #define HAVE_PTHREAD_MUTEX_RECURSIVE /**/
 ^
<command-line>:0:0: note: this is the location of the previous definition
In file included from /tmp/proj-6.0.0/src/mutex.cpp:43:0:
/tmp/proj-6.0.0/src/proj_config.h:32:0: warning: "HAVE_PTHREAD_MUTEX_RECURSIVE" redefined
 #define HAVE_PTHREAD_MUTEX_RECURSIVE /**/
 ^
<command-line>:0:0: note: this is the location of the previous definition
In file included from /tmp/proj-6.0.0/src/strtod.cpp:41:0:
/tmp/proj-6.0.0/src/proj_config.h:32:0: warning: "HAVE_PTHREAD_MUTEX_RECURSIVE" redefined
 #define HAVE_PTHREAD_MUTEX_RECURSIVE /**/
 ^
<command-line>:0:0: note: this is the location of the previous definition
```
without the unnecessary `./configure` step, there is no issue since `src/proj_config.h` has not yet been created. It seems like src/jniproj.cpp somehow references the Autoconf version of proj_config.h while everything else use the CMake version of proj_config.h, which is different:
```diff
$ diff src/proj_config.h ../src/proj_config.h 
0a1,6
> /* src/proj_config.h.  Generated from proj_config.h.in by configure.  */
> /* src/proj_config.h.in.  Generated from configure.ac by autoheader.  */
> 
> /* define if the compiler supports basic C++11 syntax */
> #define HAVE_CXX11 1
> 
3a10,12
> /* Define to 1 if the compiler supports -Wzero-as-null-pointer-constant */
> #define HAVE_GCC_WARNING_ZERO_AS_NULL_POINTER_CONSTANT 1
> 
12a22,24
> /* Define to 1 if you have the `pthread' library (-lpthread). */
> #define HAVE_LIBPTHREAD 1
> 
18a31,33
> /* Define if your pthreads implementation have PTHREAD_MUTEX_RECURSIVE */
> #define HAVE_PTHREAD_MUTEX_RECURSIVE /**/
> 
26c41
< /* #undef HAVE_STRINGS_H */
---
> #define HAVE_STRINGS_H 1
42a58,60
> /* Define to the sub-directory where libtool stores uninstalled libraries. */
> #define LT_OBJDIR ".libs/"
> 
57a76,78
> /* Define to the home page for this package. */
> #define PACKAGE_URL "https://proj4.org"
> 
65c86
< /* #undef VERSION */
---
> #define VERSION "6.0.0"
```

**Comment by QuLogic** [comment]
This is why you don't mix in-source with out-of-source builds. However, I'm not sure why why `jniproj.cpp` would be different as all the other files include `proj_config.h` the same way:
```
src/mutex.cpp
43:#include "proj_config.h"

src/strtod.cpp
41:#include "proj_config.h"

src/jniproj.cpp
45:#include "proj_config.h"
```

Actually, it looks like `jniproj.cpp` is part of `SRC_LIBPROJ_CORE` at its definition, regardless of `JNI_SUPPORT`. This seems wrong, but may not be related.

**Comment by QuLogic** [comment]
Oh, okay, it's actually all three with the warning. It seems that CMake puts source before build, which is a bit odd:
```
cd .../proj.4/build/src && /usr/lib64/ccache/c++  \
    -DHAVE_C99_MATH=1 \
    -DHAVE_PTHREAD_MUTEX_RECURSIVE=1 \
    -DMUTEX_pthread \
    -DPROJ_COMPILATION=1 \
    -DPROJ_LIB=\"/usr/local/share/proj\" \
    -Dproj_EXPORTS \
    -I.../proj.4/src -I.../proj.4/include -I.../proj.4/build/src \
    -fvisibility=hidden -Wall -Wextra -Wswitch -Wshadow -Wunused-parameter -Wmissing-declarations -Wformat -Wformat-security -O2 -DNDEBUG -fPIC \
    -std=c++11 \
    -o CMakeFiles/proj.dir/strtod.cpp.o -c \
    .../proj.4/src/strtod.cpp
```
It looks like CMake is setting a few things on the command line instead of the header file like autotools.

**Comment by QuLogic** [comment]
Something like this might work?
```patch
diff --git a/src/lib_proj.cmake b/src/lib_proj.cmake
index f28a1d68..db682134 100644
--- a/src/lib_proj.cmake
+++ b/src/lib_proj.cmake
@@ -244,7 +244,7 @@ source_group("Source Files\\ISO19111" FILES ${SRC_LIBPROJ_ISO19111})
 
 include_directories(${CMAKE_SOURCE_DIR}/include)
 
-include_directories( ${CMAKE_CURRENT_BINARY_DIR})
+include_directories(BEFORE ${CMAKE_CURRENT_BINARY_DIR})
 source_group("CMake Files" FILES CMakeLists.txt)
 
```

**Comment by mwtoews** [comment]
@QuLogic I see the include order too in the verbose build commands, and this fix does reverse the order of the flags in the verbose build. However, there are still two `proj_config.h` files that are effectively included, which seems problematic due their inconsistencies.

I can't think of a simple solution except to caution against mixing build toolsets in a single source directory. Any other solution would involve getting CMake or Autoconf to write `proj_config.h` in a unique location, which seems messy. Or perhaps `rewrite proj_config.h.in` / `proj_config.cmake.in` to guard against this scenario.

**Comment by mwtoews** [comment]
I have a small patch for that can take one of two possibilities, but I'll need some guidance from the CMake pros here.

In `cmake/ProjConfig.cmake`, a block `if(EXISTS ${CMAKE_SOURCE_DIR}/src/proj_config.h)` can either:
 1. Provide a `message(WARNING ...)`, suggesting the user do `make distclean` to clean up these types of files, or
 2. Just go ahead and `file(REMOVE ${CMAKE_SOURCE_DIR}/src/proj_config.h)`, which would only work if the user has the appropriate permissions to the source directory.

Option 1 is the safest, but doesn't directly fix the issue. Is it bad form for CMake to modify files in the source directory, as is done in option 2?

**Comment by kbevers** [comment]
I won't claim to be a CMake pro (quite the contrary) but I don't think that it's a big deal if CMake removes an existing `proj_config.h'. 

In a sitation were a user first makes a autotools build, then CMake and then finally another autotools build, how will the autotools build handle it when the `proj_config.h` it made is now missing? Create a new one or fail miserably?

**Comment by mwtoews** [comment]
Doing some tests with mixed build toolsets shows that Autoconf will generate an identical `proj_config.h` upon either `./configure` or `make`, so it seems that CMake can remove this file without a big consequence.

**Comment by kbevers** [comment]
> Doing some tests with mixed build toolsets shows that Autoconf will generate an identical `proj_config.h` upon either `./configure` or `make`, so it seems that CMake can remove this file without a big consequence.

Great! If you can prepare a PR with your changes within the next 8-10 hours they can become part of PROJ 6RC2.

**Comment by QuLogic** [comment]
> I won't claim to be a CMake pro (quite the contrary) but I don't think that it's a big deal if CMake removes an existing `proj_config.h'.

I'd disagree with this. You make a separate build directory because you want to isolate your build from the source. Even deleting files from the source directory breaks that isolation, unless it's under an explicit command (like updating checked-in translation files, for example.)

**Comment by mwtoews** [comment]
Should a just a warning be provided (option 1 above)?

**Comment by QuLogic** [comment]
Is changing build directory priority not viable? Preferring build over source is what meson and autotools do.

Interestingly, if you configure in the source, and then a separate build directory, autotools refuses to actually do it.

**Comment by kbevers** [comment]
@mwtoews, are the changes in #1282 cause for closing this issue?

**Comment by mwtoews** [comment]
I'll look into the Intel warning sometime later (after 6.0), so keep it open until I have a further look.
