### ISSUE TITLE
PROJ_DATA versus PROJ_LIB

### ISSUE THREAD

**Issue by snowman2** [OSGeo/PROJ#1273]
What is the preferred environment variable to set for the directory of the `datumgrids`, `proj.db`, etc. files? I see `PROJ_DATA` and `PROJ_LIB` being used and was just curios about the background and the future plans for which one would be better to use.

**Comment by kbevers** [comment]
Where did you get `PROJ_DATA` from? `PROJ_LIB` is what is used by PROJ.

**Comment by rouault** [comment]
No reference to PROJ_DATA in the codebase. Perhaps you're confusing with GDAL_DATA ?

**Comment by snowman2** [comment]
Huh, I think you are right. Must have mixed the two in my mind. No idea where it came from. But, I think that resolved the issue :laughing:

**Comment by snowman2** [comment]
On another thought to do with the `PROJ_LIB` dir, what is the recommended method to have the `PROJ_LIB` set with an old version of PROJ.4 and the current version of PROJ.4 installed without conflicts with the `proj.db` dependency?

**Comment by trockefeller-pathway** [comment]
Just in case anyone else runs across this issue in the future like I did, PROJ_DATA is actually a thing starting with PROJ 9.1 and for a period of time PROJ_LIB and PROJ_DATA will both be valid environment variables https://proj.org/usage/environmentvars.html#envvar-PROJ_DATA
