### ISSUE TITLE
Reject NTV2 files where GS_TYPE != SECONDS

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#1294]
Following discussion of https://lists.osgeo.org/pipermail/proj/2019-February/008246.html , it could be appropriate to error out if reading a NTv2 file with GS_TYPE header field value is different from "SECONDS" to avoid misinterpreting it.
Adding proper support for GS_TYPE != SECONDS is probably not needed since nobody does it as underlined in https://github.com/Esri/ntv2-file-routines  (probably because PROJ doesn't handle it ! but that's nice to avoid too much creativity)

**Comment by kbevers** [comment]
Fixed in #1865
