### ISSUE TITLE
UTM conversion Issue

### ISSUE THREAD

**Issue by childsd3** [OSGeo/PROJ#1313]
I've been running into issues on a couple south american UTM projections using both the proj and cs2cs binaries.

Using both QGIS and epsg.io I get the following results for the PSAD56 21N grid (the correct results):
![qgisrsult](https://user-images.githubusercontent.com/4240758/53902900-80b3fb00-3fff-11e9-8b3c-13cf74ecd080.png)

Using the proj and cs2cs command line programs I get out the following:
```
proj +proj=utm +zone=21 +ellps=intl +towgs84=-288,175,-376,0,0,0,0 +units=m +no_defs
-59.74055 6.77685
197036.86       749944.31
```

**Comment by kbevers** [comment]
Here you go:

```
$ cs2cs +proj=latlon +datum=WGS84 +to +proj=utm +zone=21 +ellps=intl +towgs84=-288,175,-376,0,0,0,0 +units=m +no_defs
-59.74055 6.77685
197199.58	750303.41 88.86
```

The `proj` application doesn't take account for the datum shift you are expecting. `proj` is *only* for projecting coordinates on the sphere/ellipsoid to a flat surface, whereas `cs2cs` also does datum shifts (hente both the source CRS and destination CRS in my call).

**Comment by childsd3** [comment]
Right on, that's what I was looking for! Thanks @kbevers.
