### ISSUE TITLE
Undocumented change in Urmaev V projection

### ISSUE THREAD

**Issue by PositiveArrow** [OSGeo/PROJ#1317]
This commit introduced a breaking change with urm5 projection:
https://github.com/OSGeo/proj.4/commit/042074b2f1d8a52ffda4d7f61341627a01912765

In Proj.4 4.9.3:
echo 100 30 | ./bin/proj +proj=urm5 +a=1.000000 +b=1.000000
1.75 nan
In Proj.4 5.2.0:
echo 100 30 | ./src/.libs/proj +proj=urm5 +a=1.000000 +b=1.000000
Rel. 5.2.0, September 15th, 2018
<proj>:
projection initialization failure
cause: n <= 0, n > 1 or not specified
program abnormally terminated

The documentation states this is an optional parameter.
https://proj4.org/operations/projections/urm5.html

It's unclear what the right behavior is, but the documentation should match the implementation.

**Comment by kbevers** [comment]
The docs should be updated to state that `+n` is required. Not setting `+n` in your first example is what causes the `nan`. While the commit message of the changeset you refer to doesn't say so, it is really a bug fix.

**Comment by kbevers** [comment]
Fixed in c288deb
