### ISSUE TITLE
Molodensky transform issue

### ISSUE THREAD

**Issue by craigmox** [OSGeo/PROJ#1321]
I am moving software from a custom projection engine to Proj.  I'm comparing the results of sample coordinate projections between our software and Proj and found a discrepancy with how the Molodensky transform works.  Our code uses the first eccentricity value as part of calculating the "Radius of curvature in the prime vertical", whereas Proj appears to use the second eccentricity value.

In src/transformations/molodensky.cpp:
```
static PJ_LPZ calc_standard_params(PJ_LPZ lpz, PJ *P) {
    struct pj_opaque_molodensky *Q = (struct pj_opaque_molodensky *) P->opaque;
    double dphi, dlam, dh;

    /* sines and cosines */
    double slam = sin(lpz.lam);
    double clam = cos(lpz.lam);
    double sphi = sin(lpz.phi);
    double cphi = cos(lpz.phi);

    /* ellipsoid parameters and differences */
    double f = P->f, a = P->a;
    double dx = Q->dx, dy = Q->dy, dz = Q->dz;
    double da = Q->da, df = Q->df;

    /* ellipsoid radii of curvature */
    double rho = RM(a, P->es, lpz.phi);
    double nu  = RN(a, P->e2s, lpz.phi);  

// etc...
```

The last line above shows it passing in `P->e2s` to `RN()`.  Should it be `P->es`?

I am very new Proj, and math is not my strongest subject, so it's very possible I'm overlooking or misunderstanding something.  I just want to know which method is right and which is wrong.

**Comment by kbevers** [comment]
I believe you are correct. Just to be on the safe side, can you give a few examples of how your implementation differs from PROJ? As in, for a given set of input coordinates and transformation parameters what is the output from the two softwares?

**Comment by craigmox** [comment]
Sure.  We are only using Molendensky for shifting datum from WGS84 to NAD27.  This is the PROJ string I'm using for testing that matches the input parameters in our software.  Let me know if this looks wrong to you.

+proj=molodensky +ellps=WGS84 +da=69.4 +df=3.7264639341036679408489785714167e-5 +dx=8 +dy=-160 +dz=-176 

Couple examples:

Birmingham, Alabama, USA
Lon: -86.787794, Lat: 33.453588 (Radians: -1.51473275584258, 0.583875257205665)
Our software output: -1.51473293944666 0.583872645988011
PROJ: -1.5147329394454  0.583872646106133

Anchorage, Alaska, USA
Lon: -149.911413, Lat: 61.196847 (Radians: -2.61644774316703, 1.06808647198921)
Our software output: -2.6164015067902 1.06809465250532
PROJ: -2.61640150759525 1.06809465277931

For what it's worth, if I change our software to use the second eccentricity to match PROJ, the output of the examples above match PROJ exactly.

**Comment by rouault** [comment]
There's a second suspicious use of e2s in calc_abridged_params() line 196 as well. EPSG Guidance 7-2  only mentions the use of the squared first eccentricity in the rho and nu formulas for the 'abridged molodensky' (page 146-147). It has also a test point

**Comment by kbevers** [comment]
Thanks. The difference between the two results is less than a millimeter so in practice this doesn't matter. I will change the PROJ code though since it is clearly using the wrong eccentricity.
