### ISSUE TITLE
Geocentric to CompoundCRS with nadgrids+geoidgrids transformation lack grids

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#1323]
`src/projinfo -s '+proj=geocent +datum=WGS84 +units=m +type=crs' -t '+proj=longlat +ellps=GRS67 +nadgrids=@foo.gsb +geoidgrids=@foo.gtx +type=crs'` returns a transformation without grids

The variant using -s EPSG:4978 returns no tranformation at all

(extract from https://github.com/pyproj4/pyproj/issues/191)

**Comment by KAMI911** [comment]
Thank you for the quick fix.

**Comment by Zenopheus** [comment]
@rouault Thanks for fixing this. It was a major show stopper for me. I'm desperate to apply this to my latest GDAL/master snapshot. I was previously building proj.4 (branch 5.2) but I see branch 6 is quite different and I'm having problems. Are there instructions for building version 6 with GDAL for Windows/64bit? I don't need the newer Proj.4 6 functionality just your changes. Is it possible to apply your changes to the 5.2 branch?

**Comment by rouault** [comment]
> Are there instructions for building version 6 with GDAL for Windows/64bit?

https://github.com/OSGeo/gdal/blob/master/appveyor.yml can be used from inspiration

>  I don't need the newer Proj.4 6 functionality just your changes. Is it possible to apply your changes to the 5.2 branch?

No, because those changes are really specific of PROJ 6 ! PROJ < 6 should work fine regarding this.

**Comment by Zenopheus** [comment]
@rouault Thanks, I got it built but your changes didn't work for me. I'm using the latest GDAL and Proj.4 6 that I just built for C#/Windows:
```
from: +proj=longlat +ellps=WGS84 +datum=WGS84 +units=m +no_defs
to: +proj=geocent +ellps=WGS84 +datum=WGS84 +units=m +no_defs +geoidgrids=egm08_25.gtx
```
When I construct the CoordinateTransformation instance it throws an exception: 
**"No PROJ.4 translation for destination SRS, coordinate transformation initialization has failed."**

The Proj.4 log doesn't show much
```
[PROJ: pj_open_lib(proj.db): call fopen(proj-data\proj.db) - succeeded
[PROJ: pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
[PROJ: pj_ellipsoid - final:    ellps=WGS84
[PROJ: pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
[PROJ: pj_ellipsoid - final:    ellps=GRS80
[PROJ: pj_ellipsoid - final: a=6378137.000 f=1/298.257, errno=0
[PROJ: pj_ellipsoid - final: a=6378137 es=0.006694379990141316461  
```

cs2cs shows the same issue:
```
echo -157.790714 21.355942 0 | cs2cs -d 4 +proj=latlong +datum=WGS84 +to +proj=geocent +datum=WGS84
-5501925.4844   -2246334.4768 2308143.0072

echo -157.790714 21.355942 0 | cs2cs -d 4 +proj=latlong +datum=WGS84 +to +proj=geocent +datum=WGS84 +geoidgrids=egm08_25.gtx
Rel. 6.1.0, September 1st, 2019
<cs2cs>:
cannot initialize transformation
cause: (null)
program abnormally terminated

echo -157.790714 21.355942 0 | cs2cs -d 4 +proj=latlong +datum=WGS84 +to +proj=pipeline +step +proj=vgridshift +grids=egm08_25.gtx +step +proj=geocent +datum=WGS84
proj_create_operations: target_crs is not a CRS
Rel. 6.1.0, September 1st, 2019
<cs2cs>:
cannot initialize transformation
cause: (null)
program abnormally terminated
```

cct does not have this problem:
```
echo -157.790714 21.355942 0 | cct +proj=geocent +datum=WGS84
-5501925.4844  -2246334.4768  2308143.0072           inf

echo -157.790714 21.355942 0 | cct +proj=geocent +datum=WGS84 +geoidgrids=egm08_25.gtx
-5501911.4685  -2246328.7544  2308137.0877           inf

echo -157.790714 21.355942 0 | cct +proj=pipeline +step +proj=vgridshift +grids=egm08_25.gtx +step +proj=geocent +datum=WGS84
-5501911.4685  -2246328.7544  2308137.0877           inf

```

**Comment by rouault** [comment]
"+proj=geocent +ellps=WGS84 +datum=WGS84 +units=m +no_defs +geoidgrids=egm08_25.gtx" doesn't make sense to me. grids take as input long,lat coordinates, not geocentric ones.

**Comment by Zenopheus** [comment]
Oh, that makes sense.
How would I apply the grids to geocentric coordinates otherwise? That example was simplified. The real logic is more like this:
```
from: +proj=longlat +ellps=WGS84 +datum=WGS84 +units=m +no_defs +geoidgrids=egm08_25.gtx
to: +proj=geocent +ellps=WGS84 +datum=WGS84 +units=m +no_defs +geoidgrids=mydata.gtx
```
My goal is to remove the original geoid undulations from the original data and apply my own.
Where mydata.gtx includes the GEOID18 undulations combined with low tide offsets.

**Comment by rouault** [comment]
You may post this to proj mailing list in case someone has an idea. Communication in closed tickets is prone to be ignored
