### ISSUE TITLE
cs2cs fails to transform coordinates outside area of use

### ISSUE THREAD

**Issue by kbevers** [OSGeo/PROJ#1329]
Sorry for the bad title, I haven't been able to narrow the problem down to something more specific.

Let's have a look at transformations between EPSG:4275 and EPSG:4807:

```
$ ./projinfo -s EPSG:4275 -t EPSG:4807 -o PROJ
Candidate operations found: 2
-------------------------------------
Operation n°1:

INVERSE(EPSG):1763, Inverse of NTF (Paris) to NTF (1), 0 m, France - onshore - mainland and Corsica

PROJ string:
+proj=pipeline +step +proj=axisswap +order=2,1 +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=longlat +ellps=clrk80ign +pm=paris +step +proj=unitconvert +xy_in=rad +xy_out=grad +step +proj=axisswap +order=2,1

-------------------------------------
Operation n°2:

INVERSE(EPSG):1764, Inverse of NTF (Paris) to NTF (2), 0 m, France - onshore - mainland and Corsica

PROJ string:
+proj=pipeline +step +proj=axisswap +order=2,1 +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +inv +proj=longlat +ellps=clrk80ign +pm=-2.33720833333333 +step +proj=unitconvert +xy_in=rad +xy_out=grad +step +proj=axisswap +order=2,1
```

Two possible transformations, all good. Let's try:

```
$ echo 58 5 0 | cs2cs EPSG:4275 EPSG:4807
*	* inf
```

Whoops. But cct to the rescue:

```
$ echo 58 5 0 0 |../../../cmake/bin/cct +proj=pipeline +step +proj=axisswap +order=2,1 +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=longlat +ellps=clrk80ign +pm=paris +step +proj=unitconvert +xy_in=rad +xy_out=grad +step +proj=axisswap +order=2,1
      64.4444         2.9586        0.0000        0.0000
```

I don't really understand what is going on here. The accuracy of the transformation is "0", maybe that has something to do with this?

I see something similar with transformations between EPSG:4267 and EPSG:4269 but there's a lot more going on in that case so probably not the best to use for debugging.

**Comment by rouault** [comment]
The reason is that both possible operations have an area of use "France - onshore - mainland and Corsica" / BBOX[41.31,-4.87,51.14,9.63], and 58 5 doesn't fall into it. Perhaps proj_trans() should fail with a dedicated new errno ?

When using 51 5, this works... excepts that cs2cs doesn't realize that EPSG:4807 is supposed to be in gradians, so it outputs in degrees (but the value in degree is correct)

**Comment by kbevers** [comment]
> The reason is that both possible operations have an area of use "France - onshore - mainland and Corsica" / BBOX[41.31,-4.87,51.14,9.63], and 58 5 doesn't fall into it

Ah, thanks. I totally missed that.

> Perhaps proj_trans() should fail with a dedicated new errno ?

I think this is more of a warning situation but we don't really have a mechanism for that. Since this is a rather simple conversion and no accuracy is lost by going outside the bbox I think we should just do the conversion.

If we honour the area of use like this in all situations I think many people are going to be confused. Not sure how to best deal with that.

> excepts that cs2cs doesn't realize that EPSG:4807 is supposed to be in gradians, so it outputs in degrees (but the value in degree is correct)

So, a bug?

**Comment by rouault** [comment]
> I think this is more of a warning situation but we don't really have a mechanism for that. Since this is a rather simple conversion and no accuracy is lost by going outside the bbox I think we should just do the conversion.
> 
> If we honour the area of use like this in all situations I think many people are going to be confused. Not sure how to best deal with that.

For simplicity, in case where the point doesn't fall into any bbox, we could just take the first transform in the list in all cases, which is supposed to be the "best" one according to the sorting criterion, be it a coordinate operation with just conversions or a more complex one potentially involving Helmert or grid transformations (in which case it might fail). What do you think ?

> So, a bug? (regarding grad output)

Perhaps, but one I don't care much about... Nobody uses grad in real life nowadays (my "ancestors" from the end of 18th century will curse me for that lol)

**Comment by kbevers** [comment]
> What do you think ?

I think my answer is "it depends". If a area of use or bbox has been specified by a user I think that the current behaviour is correct. In cases where no bbox is specified it seems to me that selecting the first in the list is the right thing to do. I assume you mean using the first one while ignoring the bbox. You're right that grid transformations pose a bit of a problem, would it be possible to disregard those in a setup like this?

> Perhaps, but one I don't care much about... Nobody uses grad in real life nowadays (my "ancestors" from the end of 18th century will curse me for that lol)

Personally I don't care much about this either. The thing is, I am working on getting the GIGS tests working properly using the ISO19111 code. The 5208 test is the reason behind this issue. It exposes two problems. The first is what I've explained above which can both be regarded as a problem in PROJ and a problem with the test data (it shouldn't suggest coordinates outside the area of use). The other is that the test expects returned coordinates in gradians, although degrees are accepted if the software doesn't gradians. PROJ can do gradians so technically this is causing a failure in the test.

**Comment by kbevers** [comment]
I am confused now. Here's an example that *doesn't* return `HUGE_VAL` coordinates when outside the defined area:

```
$ echo 55 30 | cs2cs EPSG:4258 EPSG:25832
1832463.08	6298602.10 0.00

$ projinfo EPSG:25832
PROJ.4 string:
+proj=utm +zone=32 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs +type=crs

WKT2_2018 string:
PROJCRS["ETRS89 / UTM zone 32N",
    BASEGEOGCRS["ETRS89",
        DATUM["European Terrestrial Reference System 1989",
            ELLIPSOID["GRS 1980",6378137,298.257222101,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]]],
    CONVERSION["UTM zone 32N",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",9,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["unknown"],
        AREA["Europe - 6°E to 12°E and ETRS89 by country"],
        BBOX[38.76,6,83.92,12]],
    ID["EPSG",25832]]

$ projinfo -s EPSG:4258 -t EPSG:25832
Candidate operations found: 1
-------------------------------------
Operation n°1:

EPSG:16032, UTM zone 32N, 0 m, World - N hemisphere - 6°E to 12°E

PROJ string:
+proj=pipeline +step +proj=axisswap +order=2,1 +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=utm +zone=32 +ellps=GRS80

WKT2_2018 string:
CONVERSION["UTM zone 32N",
    METHOD["Transverse Mercator",
        ID["EPSG",9807]],
    PARAMETER["Latitude of natural origin",0,
        ANGLEUNIT["degree",0.0174532925199433],
        ID["EPSG",8801]],
    PARAMETER["Longitude of natural origin",9,
        ANGLEUNIT["degree",0.0174532925199433],
        ID["EPSG",8802]],
    PARAMETER["Scale factor at natural origin",0.9996,
        SCALEUNIT["unity",1],
        ID["EPSG",8805]],
    PARAMETER["False easting",500000,
        LENGTHUNIT["metre",1],
        ID["EPSG",8806]],
    PARAMETER["False northing",0,
        LENGTHUNIT["metre",1],
        ID["EPSG",8807]],
    ID["EPSG",16032]]
```

The input longitude of 30 is way out of the defined bounding box of EPSG:25832 - why does this transformation work but not the one above? Is it because there's no area of use attached to the operation?

**Comment by rouault** [comment]
> Is it because there's no area of use attached to the operation?

When there's a single operation returned by `proj_create_operations`, it is used without checking area of use : https://github.com/OSGeo/proj.4/blob/c5cc0f74fd912cef2872da227fa2bb2b47f116c6/src/4D_api.cpp#L1054

**Comment by kbevers** [comment]
Okay. My gut feeling is that the current behaviour is too complicated but I am having a hard time to come up with a suggestion for how to do things better. On one hand I would like transformations to "just work" but on the other I think that the area of use set by the local authority should be respected. The latter can be difficult to do since there exists valid reasons to go outside the defined area of use (e.g. using UTM zone 22 for all of Greenland, even though it spans ~10 zones).

I expect that once QGIS goes full PROJ 6 topics like this will generate a lot of discussion. It will likely reveal many use cases that doesn't fit into the current rules for choosing transformations and rejecting their output.
