### ISSUE TITLE
Can't project any data

### ISSUE THREAD

**Issue by StephPeriquet** [OSGeo/PROJ#1331]
Hi, 

I just tried to project my data from lat/long to UTM and project returns this error (all was working fine before): 
Error in project(data[, c(5, 6)], "-I +proj=utm +south +zone=33 +ellps=WGS84",  : 
  unused arguments (inverse = F, degrees = TRUE, silent = FALSE, ellps.default = "sphere").
data[, c(5, 6)] do contain the longitude and latitude as numeric.
When trying to run the example code in the help file I get this: 
s <- project(state.center, "+proj=merc")
Error in project(state.center, "+proj=merc") : xy not numeric.

I have tried updating rgdal package from source but it fails:
configure: R_HOME: /Library/Frameworks/R.framework/Resources
configure: CC: clang
configure: CXX: clang++
configure: C++11 support available
configure: rgdal: 1.4-3
checking for /usr/bin/svnversion... yes
configure: svn revision: 828
checking for gdal-config... /usr/local/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 1.11.5
checking GDAL version >= 1.11.4... yes
checking GDAL version <= 2.5.0... yes
checking gdal: linking with --libs only... yes
checking GDAL: gdal-config data directory readable... yes
checking GDAL: /usr/local/Cellar/gdal/1.11.5_1/share/gdal/pcs.csv readable... yes
./configure: line 2086: pkg-config: command not found
configure: pkg-config proj not available
  set PKG_CONFIG_PATH to the directory containing proj.pc
configure: PROJ version not determined using pkg-config proj
configure: proj CPP flags:  -I/usr/local/Cellar/gdal/1.11.5_1/include
checking PROJ header API:... proj_api.h
checking proj_api.h presence and usability... yes
checking PROJ version >= 4.8.0... yes
./configure: line 2325: test: =: unary operator expected
checking PROJ.4: proj.db found and readable... no
Error: proj/proj.db not found
Either install missing proj support files, set PROJ_LIB to the
correct path, and if need be use the --with-proj-share=
configure argument.
ERROR: configuration failed for package ‘rgdal’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rgdal’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rgdal’
Warning in install.packages :
  installation of package ‘rgdal’ had non-zero exit status

I'm running on MacOs Mojave, Rstudio 1.1.463 , R 3.5.2, proj4 1.0-8 & rgdal 1.4-2.

Any idea how I ca get my code to work again?

Thanks!
Stephanie

**Comment by kbevers** [comment]
>  (all was working fine before)

Before what?

You encounter this problem using rgdal, yes? It is hard to tell from your output if this is a problem in rgdal or in PROJ. The output does say `checking PROJ.4: proj.db found and readable... no` though, so there's a hint for you. It is possible that this is a problem with the rgdal installation.

Try running

```
echo 20 60 | proj +proj=utm +south +zone=33 +ellps=WGS84
```

from a command line to see if PROJ works by itself.

**Comment by StephPeriquet** [comment]
Thanks for the quick reply. The echo command line works fine indeed. I detached the rgdal package (didn't think about doing that before) and now it runs fine on R, so I assume the problem is coming from rgdal indeed....
By "before" I mean a few weeks ago... I'm pretty sure I updated packages version since then.

**Comment by busstoptaktik** [comment]
@StephPeriquet please discuss the problem on the PROJ mailing list (https://lists.osgeo.org/mailman/listinfo/proj and archive: https://lists.osgeo.org/pipermail/proj/) and/or whichever relevant R forum.

This place is for describing actual bugs in PROJ, not for getting help with PROJ usage. I believe a few rgdal people follow the PROJ mailing list, so you will have a much better chances for getting help there. Here, you will reach only PROJ developers, of whom approximately 0 are R users.

If, after discussing in relevant forums, you are convinced that you have actually found a PROJ bug, you are, obviously, very welcome to report your findings here - but just dumping a build log onto the development site is not really a productive way to seek help.
