### ISSUE TITLE
proj_create no longer returns a null pointer when passed a bad string

### ISSUE THREAD

**Issue by urschrei** [OSGeo/PROJ#1365]
In v5.x.x, passing a pointer to a "bad" proj string (such as `ugh`) to `proj_create` would return a null pointer. As of v6.0.0, this is longer the case, and no error is produced (i.e. `proj_errno` and `proj_context_errno` both return `0`), until conversion or projection are attempted. Is this intentional?

**Comment by rouault** [comment]
Ah this is interesting... If you try "projinfo ugh", you will understand what happens. In PROJ 6, proj_create() goes through the new createFromUserInput() function which accepts WKT string, PROJ string, EPSG:XXXX codes, ... and CRS names from the database, such as WGS84, NAD83, etc. It also implements a logic of approximate match, and 'ugh' matches with the GCS_Hough_1960 CRS...

**Comment by urschrei** [comment]
That's what I get for being insufficiently creative with my bad input. Seems like the sensible approach here is for me to note the new init logic, and caution that this might delay the appearance of an error.

**Comment by kbevers** [comment]
If you need, you can check that you get the output you expect with [`proj_get_type()`](https://proj4.org/development/reference/functions.html#_CPPv313proj_get_typePK2PJ) and check it against various [`PJ_TYPE`'s](https://proj4.org/development/reference/datatypes.html#_CPPv3N14iso19111_types7PJ_TYPEE).

If you expect a transformation and get something else you can raise a "user input error" in your application.
