### ISSUE TITLE
Performance regression from 5.2.0 to 6.0.0

### ISSUE THREAD

**Issue by mdiasribeiro** [OSGeo/PROJ#1367]
I'm currently looking into updating our usage of proj 5.2 to 6.0.
Testing shows over 10x slowdown of, as example, a 1k points sized array transformation using "proj_trans_generic" from EPSG:32631 to EPSG:4326 and back again.
On 5.2, 1M points in 1k batch arrays averages to about ~0.6 us per point, while
on 6.0, 1M points in 1k batch arrays averages to about ~7 us per point.

Anyone seeing this kind of performance degradation or if usage practices have changed in this version that would lead to this?

**Comment by rouault** [comment]
What if you try a batch of 10 million points ? To distinguish the initial cost of computing the transformation from the cost of transformation of each point

**Comment by snowman2** [comment]
https://pyproj4.github.io/pyproj/html/optimize_transformations.html

**Comment by snowman2** [comment]
Also, see: https://github.com/pyproj4/pyproj/issues/187

**Comment by mdiasribeiro** [comment]
Doing a 10 million point batch does indeed improve speeds to close to previous performance (~0.7 us per point). This does mean that creating these transformations has become various orders of magnitude slower compared to 5.2.0. This is not good, as for our use cases we perform multiple transformations of 1k to 10k points at a time. Even worse, we do require to occasionally transform a single point, and that performance has gone from ~30 us to ~23500us. Any way you can think of to cut these times? We are using a SWIG-wrapped C proj in Java (so no python).

**Comment by busstoptaktik** [comment]
> Any way you can think of to cut these times?

If your transformations are really from any random system to any random system there is probably not much you can do.

If you are actually transformaing between systems drawn from a limited set, just init the common use cases, and cache them. That's actually how PROJ is meant to be used

**Comment by snowman2** [comment]
The caching method is how pyproj does it with the Transformer class.

**Comment by mdiasribeiro** [comment]
I see. That means that we will have to expose the context as an internal api to allow for re-use. It's scary though, as our approach uses actor systems that access proj as a static lib, which means that handling that context inside actors is dangerous (since it isn't thread safe). I'll do some testing to check if the bulk of the slowdown is due to the creation of the transformation object or the context. If it is only the context, then it is annoying but workable.
Thanks for the info.

**Comment by kbevers** [comment]
I believe this issue has been dealt with.
