### ISSUE TITLE
ocea: division by zero if alpha is specified and alpha=0 or lat_0=0

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#1379]
Triggered by https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=13930

Can be be easily reproduced with: `proj +proj=ocea +alpha=0 +lat_0=1` or `proj +proj=ocea +alpha=1 +lat_0=0`
Both lead to finite results (since atan() has always finite output), but a division by zero still occurs at https://github.com/OSGeo/proj.4/blob/15a9adb5ff112184ea5abfe083ea280b7bef7dd4/src/projections/ocea.cpp#L69

The formulas come directly from Snyder but the later doesn't say anything about the validity range of the parameters.

So should alpha=0 and/or lat_0=0 be allowed ?

If we don't know and want to keep current behaviour unchanged, then a potential solution is to detect the div by zero before it occurs, and return the result of atan(+infinity)=pi/2 or atan(-infinity)=-pi/2 directly.

**Comment by busstoptaktik** [comment]
Wouldn't

    atan2 (-cos(alpha), -sin(phi_0) * sin(alpha)) + lon_z

do the job?

**Comment by rouault** [comment]
> atan2 (-cos(alpha), -sin(phi_0) * sin(alpha))

Not sure... atan2 can return values in the [-pi,pi] range, whereas atan is [-pi/2,pi/2]. In the 2-point case, Snyder explicitly asks to use atan2 for the lam_p computation, but regular atan for the phi_p one. For the 1-point case which is the case of interest here, he doesn't mention anything...

**Comment by busstoptaktik** [comment]
> Not sure... atan2 can return values in the [-pi,pi] range

Yes, this makes sense for a longitude (`lam_p`), whereas we would prefer to have the latitudes truncated at the poles - but I must admit, that I get lost in the potential sign combinations in this expression, so I'm not sure it will work correctly.

I just generally prefer atan2, to get the automatic quadrant correction (which of course does not make same sense for latitudes)

**Comment by rouault** [comment]
While testing closer, the issue is more profound than this ! The phi_0 variable is actually a constant value to 0, and not the value of lat_0 as one might expect. This error comes from the beginning of times (4.3.3!), and actually in ancient versions the variable wasn't initialized at all... So this case has always been completely broken

**Comment by kbevers** [comment]
> This error comes from the beginning of times (4.3.3!)

Good catch!

> So this case has always been completely broken

Perhaps that is the reason behind the upside-down map in the docs: https://proj4.org/operations/projections/ocea.html

**Comment by rouault** [comment]
> Perhaps that is the reason behind the upside-down map in the docs: https://proj4.org/operations/projections/ocea.html

Not directly, ocea without explicit alpha goes to the 2 points case, and thus with lat_1=lat_2=lon_1=lon_2=0, which is likely a undefined case to specify the projection
