### ISSUE TITLE
UTM performance regression from 4.9.2 to 4.9.3 and 6.0.0 (related to switching from tmerc to etmerc for UTM)

### ISSUE THREAD

**Issue by fvdbergh** [OSGeo/PROJ#1384]
I discovered issue [#316](https://github.com/OSGeo/proj.4/issues/316) after noticing a rather large performance regression while converting UTM to EPSG:4326, and tracking down the changes to the source.

I have attached a simple test program to illustrate.
[utm_proj_test.zip](https://github.com/OSGeo/proj.4/files/3017609/utm_proj_test.zip)
I just measured the execution time of the program linked to proj-4.9.2 versus proj-4.9.3 using the shell's 'time' command.

On my machine (Core i7-2720QM), with the proj libraries compiled with "-g -O2", I find that 4.9.3 runs about 2.7x slower than 4.9.2. This, in turn, makes reprojecting  images using the GDAL warp API (thus exact per-pixel transformations) slower by the same factor, which is rather a big deal when processing Sentinel 2 images on AWS.

I repeated the test with proj-6.0.0. If I use the "ACCEPT_DEPRECATED..." preprocessor definition, and run basically the same code, it runs about 3.0x times slower than proj-4.9.2. I tried using the new API, i.e., using proj_trans_array with PJ_COORD types, but that was even slower at 3.77x compared to proj-4.9.2. Not sure if my use of the new proj 6.0.0 API is correct, though.

I am not sure what I would like the proj team to do about this. One thing that would help is if the Changelog could mention the performance regression in UTM going from 4.9.2 to 4.9.3, and by extension, the suspected performance regression from 4.9.2 to 6.0.0. I notice that GDAL 2.4.0 still appears to use the 4.x API, but at some point GDAL might switch to the 6.0.0 API, which would make it difficult to regain the performance of GDAL + proj-4.9.2.

I know the suggestion that proj should provide an option to restore the UTM-via-tmerc behaviour was shot down in #316, but would that be feasible in the 6.0.0 code, especially in the light of the performance regression? Maybe something as crude as an environment variable?

Alternatively, it might be possible to improve the performance of the etmerc code? But it looks like the compiler is already trying pretty hard to use AVX intrinsics, so I am not sure if there is much room to improve performance without affecting accuracy.

-Frans

**Comment by rouault** [comment]
> This, in turn, makes reprojecting images using the GDAL warp API (thus exact per-pixel transformations) slower by the same factor, which is rather a big deal when processing Sentinel 2 images on AWS.

You can use an approximate linear transformer (what is used by default by gdalwarp or the GDALWarp() function, unless you specify -et) to save a lot of coordinate reprojections.

> I notice that GDAL 2.4.0 still appears to use the 4.x API

Depends on how you build it. But if you use --with-proj, GDAL 2.4 should already use proj.h (with PROJ >= 5). If you didn't build --with-proj, and it dlopen()'s libproj at runtime, then it will use the PROJ 4.x API indeed

GDAL has a OSR_USE_ETMERC=NO configuration option / environment variable.
With GDAL 2.5dev + PROJ 6, `OSR_USE_ETMERC=NO gdalsrsinfo EPSG:32631` returns '+proj=utm +approx +zone=31 +datum=WGS84 +units=m +no_defs' (note the +approx flag. see https://proj4.org/operations/projections/utm.html )
With GDAL 2.4 + PROJ 5 (or 4.9.x),  `OSR_USE_ETMERC=NO gdalsrsinfo EPSG:32631` returns '+proj=tmerc +lat_0=0 +lon_0=3 +k=0.9996 +x_0=500000 +y_0=0 +datum=WGS84 +units=m +no_defs`
Both will use the original faster tmerc implementation

**Comment by fvdbergh** [comment]
Hi Even,

Thanks for the quick reply.

Unfortunately I cannot use the approximate transformer. For the project I am working on at the moment, I have to reproduce exactly the output of a client-supplied Google Earth Engine script (but I have to do it on AWS). Since the GEE script uses nearest-neighbour resampling (of the Sentinel 2 L1C images!!), the approximate transformer occasionally gives me a few pixels that differ. By the time you turn the error threshold of the approximate transformer to a low enough value, there is not much of a performance difference between exact and almost-exact results. 

Thanks for the info on the GDAL flags; I'll hard-code that into my program, just in case :)


-Frans

**Comment by kbevers** [comment]
This issue seems to be dealt with. At least to the extend that it can. Closing the issue, but please re-open if it to soon.
