### ISSUE TITLE
Adapt code examples to PROJ 6 API

### ISSUE THREAD

**Issue by kbevers** [OSGeo/PROJ#1403]
The code example in https://github.com/OSGeo/proj.4/blob/master/examples/pj_obs_api_mini_demo.c was made as a demo of PROJ 5 capabilities. It should be updated to demonstrate best practice in PROJ 6. 

This issue was prompted by https://lists.osgeo.org/pipermail/proj/2019-April/008413.html

**Comment by rouault** [comment]
The https://proj4.org/development/quickstart.html which is derived from it should be updated too

**Comment by rouault** [comment]
Should mention proj_normalize_for_visualization() as most people will need it
