### ISSUE TITLE
`+proj=vgridshift` returns `inf` for valid lat/lon (EGM96)

### ISSUE THREAD

**Issue by andrew-hardin** [OSGeo/PROJ#1415]
I'm seeing a `+INF` vertical shift when I provide a valid lat/lon value (PROJ 6.0.0).
Minimal example is include below:

```c++
PJ* P = proj_create(PJ_DEFAULT_CTX, "+proj=vgridshift +grids=egm96_15.gtx");
if (!P) return 1;

PJ_COORD c;
c.lpz.lam = 3.1373020525119735;
c.lpz.phi = 0.17446020314726654;
c.lpz.z = 0;

c = proj_trans(P, PJ_FWD, c);
if(std::isinf(c.lpz.z)) {
  std::cerr << "Bug!";
}
```

I'm unfamiliar with the relevant source code, but I'll take a shot at resolving the issue this afternoon.

**Comment by andrew-hardin** [comment]
It looks like there's a boundary check that verifies the input coordinate falls within the grid. The example (above) fails that check. Assuming I understand the issue, I see two paths forward:

- A: if a grid spans from `-pi` to `pi` _and_ the input coordinate is < 1 pixel beyond the last column, then interpolate the x coordinate using the last and first column in the grid.
- B: add a new column to `egm96_15.gtx` by simply repeating the first column.

Both paths effectively wrap the global offset grid at `-pi` and `pi`.

**Comment by rouault** [comment]
Looks similar to issue #336
