### ISSUE TITLE
How to get size of array for proj_coordoperation_get_towgs84_values

### ISSUE THREAD

**Issue by snowman2** [OSGeo/PROJ#1430]
How do we know the size of the array (value_count) forproj_coordoperation_get_towgs84_values? Seems like it can be 3 or 7. How can we find out? Would a new function to get the size resolve this?

**Comment by kbevers** [comment]
You determine that yourself with `value_count`: https://proj4.org/development/reference/functions.html#_CPPv338proj_coordoperation_get_towgs84_valuesP10PJ_CONTEXTPK2PJPdii

IF you just ask for 7 I suspect you will get zeroes for the last four parameters in case of a simple 3-param Helmert.

**Comment by kbevers** [comment]
@rouault will the function return the time-dependent parameters as well if they are available? Or is this strictly 3/7-parameter Helmert?

**Comment by rouault** [comment]
> Or is this strictly 3/7-parameter Helmert?

Yes, only 3/7-parameter Helmert as indicated in the intent of the function: "WKT1 TOWGS84". And WKT1 only support those.
In the general case, you have to use proj_coordoperation_get_param_count() + proj_coordoperation_get_param()

**Comment by snowman2** [comment]
Thanks for the response! So, the extra zeros are expected if you originally input 3.
