### ISSUE TITLE
link to Dutch grid broken

### ISSUE THREAD

**Issue by markov2** [OSGeo/PROJ#1435]
Page https://proj4.org/resource_files.html refers to the Dutch grid at kadaster.nl  However, that link does not work anymore.  No idea where the info can be downloaded now.

**Comment by kbevers** [comment]
[This](https://zakelijk.kadaster.nl/transformatie-van-coordinaten) is likely the correct link. I don't understand a word of it though so confirmation from someone who speaks Dutch would be nice.

**Comment by markov2** [comment]
* Kristian Evers (notifications@github.com) [190420 13:31]:
> [This](https://zakelijk.kadaster.nl/transformatie-van-coordinaten)
> is likely the correct link. I don't understand a word of it though so
> confirmation from someone who speaks Dutch would be nice.

(Dutch is my first language)  Yes, that seems to refer to the same
page as was pointed to before.
-- 
               MarkOv

------------------------------------------------------------------------
       Mark Overmeer MSc                                MARKOV Solutions
       Mark@Overmeer.net                          solutions@overmeer.net
http://Mark.Overmeer.net                   http://solutions.overmeer.net
