### ISSUE TITLE
Support for the Ocean Oriented Interrupted Goode Homolosine

### ISSUE THREAD

**Issue by sridge** [OSGeo/PROJ#1442]
![GUID-F958670B-74CA-40B0-A4A2-26C6101F6C64-web](https://user-images.githubusercontent.com/11999411/56681706-f51e2880-6697-11e9-90b7-9de8462b3c35.gif)

Something similar to the above, from ArcGIS. It's commonly used by oceanographers but doesn't exist yet for PROJ.4. Those oceanographers that use python and Cartopy (and therefore PROJ.4), would appreciate this projection being added.

Some specifications:
- Northern Hemisphere interruptions at 100˚,-100˚
- Southern Hemisphere interruptions at  -67˚, 147˚ (corresponding with [ocean borders](https://en.wikipedia.org/wiki/Borders_of_the_oceans))
- Left and right bounds at 20˚, central longitude of -160˚

**Comment by kbevers** [comment]
There's a better chance to get your wish fulfilled if your provide some material that describes how to implement this projection. Ideally a paper describing the maths and some test coordinates that can be used to verify the implementation.

**Comment by sridge** [comment]
Thank you, I'll add some more background information. Not sure what test coordinates are, but assume they may already exist

https://github.com/OSGeo/proj.4/blob/master/src/projections/igh.cpp

The projection is already included in PROJ (igh), but with different interruptions. I was assuming it would be as simple as rearranging the "zones" from the code. 

From this:
```
 Land Zones:
    -180            -40                       180
      +--------------+-------------------------+    Zones 1,2,9,10,11 & 12:
      |1             |2                        |      Mollweide projection
      |              |                         |
      +--------------+-------------------------+    Zones 3,4,5,6,7 & 8:
      |3             |4                        |      Sinusoidal projection
      |              |                         |
    0 +-------+------+-+-----------+-----------+
      |5      |6       |7          |8          |
      |       |        |           |           |
      +-------+--------+-----------+-----------+
      |9      |10      |11         |12         |
      |       |        |           |           |
      +-------+--------+-----------+-----------+
    -180    -100      -20         80          180
*/
```
To this:
```
 Ocean Zones:
     20       100               -100          20
      +--------+------------------+------------+    Zones 1,2,3,10,11 & 12:
      |1       |2                 |3           |      Mollweide projection
      |        |                  |            |
      +--------+------------------+------------+    Zones 4,5,6,7, 8 & 9:
      |4       |5                 |6           |      Sinusoidal projection
      |        |                  |            |
    0 +------------+--------------+---+--------+
      |7           |8                 |9       |
      |            |                  |        |
      +------------+------------------+--------+
      |10          |11                |12      |
      |            |                  |        |
      +------------+------------------+--------+
     20           147                -67       20
*/
```

**Comment by kbevers** [comment]
> Thank you, I'll add some more background information. Not sure what test coordinates are, but assume they may already exist

Ideally they would be found in a publication that describes the projection. Alternatively I guess some coordinates can be produced using Esri software where the projection is already implemented.

> I was assuming it would be as simple as rearranging the "zones" from the code.

Probably, yes. If you want to give it a go I am happy to review your code and guide your through the process of getting it merged into PROJ.
