### ISSUE TITLE
Error no longer raised in proj_trans_generic for 6.1.0

### ISSUE THREAD

**Issue by snowman2** [OSGeo/PROJ#1449]
When throwing input into proj_trans_generic that is clearly out of range, an error is no longer raised in the 6.1.0 version that used to be raised in the 6.0.0 version. Just wanted to make sure this behavior is expected.

For projections used, see:
https://github.com/pyproj4/pyproj/pull/286/commits/0b92f70630a9b95d505dff97f0e98e4390ff3021

To reference tests passing in 6.0.0 and failing in 6.1.0:
https://travis-ci.org/pyproj4/pyproj/builds/525452457

**Comment by rouault** [comment]
The change of behaviour is linked to 1b8b720b , but that commit by itself is OK.
The fact that a errno is set or not when coordinate transformation fails is unfortunately somewhat "random" depending on where this occurs exactly in the library.
But in both PROJ 6.0 and master, the transformed coordinates will be set to INFINITY.

**Comment by snowman2** [comment]
Okay, thanks for the explanation. Feel free to close this issue if it is no longer relevant.
