### ISSUE TITLE
make install fails: [install-projHEADERS] Error 1

### ISSUE THREAD

**Issue by GabrieleMartini** [OSGeo/PROJ#1457]
https://askubuntu.com/questions/1141146/compiling-osgeo-proj-4-return-install-projheaders-error-1

**Comment by dchiu911** [comment]
Hi @GabrieleMartini how did you end up resolving the issue? Did you specify a different `--prefix`?

**Comment by GabrieleMartini** [comment]
Specifying different prefix solved the problem
