### ISSUE TITLE
OSGeo Community Project

### ISSUE THREAD

**Issue by jodygarnett** [OSGeo/PROJ#1468]
Looking at proj4.org:
- OSGeo asks that PROJ display the [OSGeo Community](https://github.com/OSGeo/osgeo/tree/master/incubation/community) logo somewhere
- The read the docs theme has some configuration options, and it is fairly easy to overriding sections of that theme like the header if you need a hand

**Comment by jodygarnett** [comment]
It would also be nice to fix up the [project page](https://www.osgeo.org/projects/proj4/) with links to the various communication channels and documentation.

**Comment by kbevers** [comment]
> It would also be nice to fix up the project page with links to the various communication channels and documentation.

How do I go about doing that? As far as I can tell I haven't got the right credentials to edit the site.

**Comment by kbevers** [comment]
Also, can we change the name? "Proj4" is wrong in several ways :)

**Comment by jodygarnett** [comment]
Sure, what is your OSGeo userid? Please login into the website once, and then I can give you permissions to edit that page (and also add events, announcements, etc...).

The goal with these pages is that they belong to the project, the PSC of each project should have access/credentials to edit.

**Comment by kbevers** [comment]
> Sure, what is your OSGeo userid? Please login into the website once, and then I can give you permissions to edit that page (and also add events, announcements, etc...). 

User ID is the same as here. Logged in at the moment.

> The goal with these pages is that they belong to the project, the PSC of each project should have access/credentials to edit.

Right. To be honest I am not very keen on maintaining several websites, so I'll just put something low maintenance on there and refer users to proj4.org if they need more information. It should be possible to cover the basics this way.

**Comment by jodygarnett** [comment]
I have added appropriate [roles](https://wiki.osgeo.org/wiki/Website#Roles), let me know if you have questions. I am also lurking on the project Gitter for more immediate chitchat.

**Comment by kbevers** [comment]
Closed with https://github.com/OSGeo/PROJ/pull/1568

Logo to be found here: https://proj.org/about.html
