### ISSUE TITLE
OSGeo Incubation Checklist

### ISSUE THREAD

**Issue by jodygarnett** [OSGeo/PROJ#1469]
Follow up to osgeo code sprint chat here are some links to get started on the graduation checklist.

Here is a markdown example to cut and paste into your wiki

* [graduation_checklist.md](https://github.com/OSGeo/osgeo/blob/master/incubation/documents/graduation_checklist.md)

And here are some examples:

* [GeoNode Checklist](https://wiki.osgeo.org/wiki/GeoNode_Incubation_Checklist)
* [GeoServer Incubation Checklist](https://github.com/geoserver/geoserver/wiki/GeoServer-Incubation-Checklist)
* [PyWPS Project Graduation Checklist](https://github.com/geopython/pywps/wiki/ProjectGraduationChecklist)
* [OSGeo Live](https://wiki.osgeo.org/wiki/Live_GIS_Incubation_Graduation_Checklist) - a bit verbose 

Please keep in mind that the OSGeo incubation program is intended as open source outreach, educating project teams on what is needed to both use an open source license and have some kind of public/welcoming development community.

Since the PROJ team is so experienced the checklist will mostly consist of document how the project operates and be very quick to fill out. Please document the state of play, rather than try to "fix things" (which delays incubation).

**Comment by kbevers** [comment]
Thanks, Jody. I'll get on this as soon as possible.

**Comment by kbevers** [comment]
I've added a wiki page with the checklist here: https://github.com/OSGeo/proj.4/wiki/Incubation-checklist

I have filled out the first couple of sections. I'll try to get it as up to date as I can within the next week or so. Others are of course welcome to pitch in as well!

**Comment by kbevers** [comment]
I have updated the checklist today. I believe the only two things that are missing now are the [provenance review](https://github.com/OSGeo/PROJ/wiki/PROJ-Provenance-Review) and a project logo. I'll start work on the provenance review now but don't expect to finish it anytime soon. There are many files to go through!

**Comment by jodygarnett** [comment]
That is great, we are working on incubation here at the community sprint for other project also.

You can do a lot by using grep to quickly check the files for headers which are unusual and make a shortlist for manual review. I also had some scripts that used git to figure out who created the file ... if you history goes back that far.

Some thoughts:

- May wish to consider CC0 for the documentation, right now it does not appear to be using a documentation license?
- PROJ includes a lot of data to check as part of a providence (may be clear as many datasets have a clear authority)

**Comment by kbevers** [comment]
@jodygarnett @msmitherdc,

The [Incubation checklist](https://github.com/OSGeo/PROJ/wiki/Incubation-checklist) is now finished and ready for review by the incubation committee.

**Comment by kbevers** [comment]
Closing as PROJ has successfully passed incubation.
