### ISSUE TITLE
OSX conda API version wrong?

### ISSUE THREAD

**Issue by abellgithub** [OSGeo/PROJ#1488]
Hi,

I've got a conda version of libproj.dylib and it shows the following version info:

```
           cmd LC_ID_DYLIB
       cmdsize 48
          name @rpath/libproj.15.dylib (offset 24)
    time stamp 1 Wed Dec 31 19:00:01 1969
       current version 17.0.0
 compatibility version 17.0.0
```

However, when I build from current source, I get:

```          cmd LC_ID_DYLIB
      cmdsize 48
         name @rpath/libproj.16.dylib (offset 24)
   time stamp 1 Wed Dec 31 19:00:01 1969
      current version 16.0.1
compatibility version 16.0.0
```

I'm not sure what's right here, but having version 16 with an internal version number lower than version 15 seems confusing if not wrong.

**Comment by kbevers** [comment]
I can't explain this. I've just checked the ABI information in both autoconf and CMake setups of the last couple of releases and they seem to be in order. I think the conda guys have a better chance of explaining this.
