### ISSUE TITLE
proj_normalize_for_visualization:  Cannot retrieve source or target CRS

### ISSUE THREAD

**Issue by nyalldawson** [OSGeo/PROJ#1492]
proj_normalize_for_visualization fails in the following context:

```
  PJ *o = proj_create( nullptr, "+proj=pipeline +step +proj=axisswap +order=2,1 +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=hgridshift +grids=GDA94_GDA2020_conformal_and_distortion.gsb +step +proj=unitconvert +xy_in=rad +xy_out=deg +step +proj=axisswap +order=2,1" );
  PJ *res = proj_normalize_for_visualization( nullptr, o );
```

With the error: Cannot retrieve source or target CRS (the grid IS available for use)

**Comment by rouault** [comment]
Yes, that's intended. As documented in https://proj4.org/development/reference/functions.html#c.proj_normalize_for_visualization, proj_normalize_for_visualization() can only work with a PJ* object returned by proj_create_crs_to_crs(). When instanciating with proj_create(), all CRS notions are lost, and thus axis order.

**Comment by nyalldawson** [comment]
So how can I determine whether in this case the axis need to be swapped or not?

**Comment by rouault** [comment]
Well, if the PROJ string was serialized by QGIS after doing proj_create_crs_to_crs() + proj_normalize_for_visualization(), then you're good. If it hasn't, then the PROJ string wouldn't probably work properly. So I'd say, just take it as it, and hope for the best.

**Comment by nyalldawson** [comment]
The code snippet was actually an adaption of what led to this. I'm actually creating the operation using proj_create_operations with a source and dest crs, and then proj_list_get to retrieve the operation. Does that change anything?

**Comment by rouault** [comment]
> I'm actually creating the operation using proj_create_operations with a source and dest crs, and then proj_list_get to retrieve the operation

Hum, I'd expect that to work. There's test for something similar using the C++ API : https://github.com/OSGeo/proj.4/blob/master/test/unit/test_operation.cpp#L8133. Can you share a reproducer of your issue ?

**Comment by nyalldawson** [comment]
Downstream issue, sorry!
