### ISSUE TITLE
No docs for proj_context_set_search_paths

### ISSUE THREAD

**Issue by nyalldawson** [OSGeo/PROJ#1493]
While the proj docs mention proj_context_set_search_paths on https://proj4.org/usage/environmentvars.html?highlight=proj_context_set_search_paths, there's no description elsewhere of how this function should be used and the consequences of calling it. 

E.g. does proj still fallback to the standard paths after a call to proj_context_set_search_paths? Is the PROJ_LIB environment variable respected?

**Comment by rouault** [comment]
> does proj still fallback to the standard paths after a call to proj_context_set_search_paths? Is the PROJ_LIB environment variable respected?

No, if it is set, PROJ_LIB is ignored : https://github.com/OSGeo/proj.4/blob/2eb2798b1ef31d04c717856d82acd4ccb7aac78a/src/open_lib.cpp#L204 . This is mostly a programmatic alternative to PROJ_LIB.

**Comment by nyalldawson** [comment]
Is there any way to add a search path to any existing ones, without affecting the others? E.g. for qgis I would like to offer the ability for users to manually place grid files in a user-writable .qgis/proj folder. But this would only be for additional grids, so it would need to be used in addition to other search paths. Would this require new api?

**Comment by rouault** [comment]
> Would this require new api?

not necessarily. proj_info().searchpath will contain the content of the PROJ_LIB env variable if set, the hard-coded path at compilation time, and search paths concatenated with ':' on non-Windows and ";" on Windows as separator.
So you could split that, add your new path, and call proj_context_set_search_paths() with the new array.

**Comment by nyalldawson** [comment]
Perfect! Last question: I'll add this to the doc, but I need a pointer on where it should sit so it will get included.

**Comment by rouault** [comment]
> but I need a pointer on where it should sit so it will get included.

In the doxygen comments, but that would probably need some changes in the doc building process to get that appear on the website. Presumably INPUT in Doxyfile, and perhaps something in docs/source/development/reference/functions.rst

**Comment by nyalldawson** [comment]
@rouault in https://github.com/OSGeo/proj.4/pull/1497 I've fixed ";" always being used as a delimator for searchpath, but in proj.h the dox for searchpath explicitly states "paths are separated by semi-colons" (i.e. current behavior). What's the desired behavior here? Do you want ":" used on non-Win platforms?

**Comment by kbevers** [comment]
What's the status on this issue? Is everything dealt with in #1497 or is there still more left to do regarding the docs?

**Comment by nyalldawson** [comment]
There's more for the docs - it's on my to-do list

**Comment by kbevers** [comment]
Duly noted - I'll refrain from closing the issue then :)

**Comment by nyalldawson** [comment]
Thanks! 

On a related topic: You should consider installing stale bot to handle this -- it's a great way to force contributions to keep moving forward and the issue tracker clean (without anyone personally having to be the "bad guy" and closing stuff/hassling manually)
