### ISSUE TITLE
redundant and incorrect CRS definitions getting into QGIS 3

### ISSUE THREAD

**Issue by gubuntu** [OSGeo/PROJ#1503]
I'm migrating this from https://issues.qgis.org/issues/20624. I hope this can (or has been) addressed in proj6. Otherwise please indicate if it needs to be taken upstream to EPSG.

---------------

New CRSs for South Africa appeared in QGIS 3.

So-called EPSG:120480-102489 and EPSG:102562-102568 are not even in the EPSG registry, so where did they come from and why are they assigned EPSG authority?

They are completely unnecessary and redundant as 120480-102489 are already covered by the official EPSG:2046-2055 CRSs and 102562-102568 are already covered by the QGIS 'ZANGI' CRSs.

If they were added to QGIS, please remove them. Else if they come from proj.4, please indicate that so we can raise an issue with proj.

**Comment by rouault** [comment]
Those are not EPSG codes, but ESRI codes. The PROJ database contains definitions from different authorities, and doesn't try to put one as more official as others. It might be needed to implement upper level logic in QGIS, if it is not a desirable behaviour to expose them to the user. Closing as not a PROJ bug. CC @nyalldawson

**Comment by gubuntu** [comment]
If they are ESRI codes why are they listed by proj as EPSG: and not ESRI: then?

**Comment by rouault** [comment]
> If they are ESRI codes why are they listed by proj as EPSG: and not ESRI: then?

QGIS issue I guess, unless this is demonstrated that PROJ mixes things somewhere. At least
`projinfo ESRI:102489` reports a CRS under ESRI authority, whereas `projinfo EPSG:102489` returns an error

**Comment by nyalldawson** [comment]
Right, this was an issue in qgis on older proj builds, where qgis had some odd logic to convert all authorities to epsg. It's fixed with the proj 6 builds, since that db is totally redundant.
