### ISSUE TITLE
List all projections in GUI

### ISSUE THREAD

**Issue by kiliandys** [OSGeo/PROJ#1515]
Hi !

Our team is currently upgrading from **proj4** to **proj6**.
In our software, we have GUI allowing the user to pick the projection he wants to use (accompanied with a search functionality).

Before, with **proj4**, we designed some reader to read the `epsg`, `IGNF`, `esri`, etc. files that were located in the `share/` folder.
If my understanding is correct, now that we are using **proj6**, all datas are gathered in `proj.db` and we can use the method `proj_get_crs_info_list_from_database`.

However, our GUI use the **proj-string** to create a **"category"** for each projection (for instance, `+proj=lcc` will be associated with `Lambert Conformal Conic`).

Hence my question:
- By using `proj_get_crs_info_list_from_database`, how can I generate the **proj-string** and/or get the associated **"category"** associated to the projection ?

**Comment by rouault** [comment]
PROJ_CRS_INFO contains the following field, that will contain strings like 'Lambert Conformal Conic':
```
    /** Name of the projection method for a projected CRS. Might be NULL even
     *for projected CRS in some cases. */
    char* projection_method_name;
```

**Comment by kiliandys** [comment]
Thank you, that's what I was looking for.
