### ISSUE TITLE
cs2cs gives a different z value for transformation in v6.0

### ISSUE THREAD

**Issue by matherno** [OSGeo/PROJ#1516]
In v5.2 the following...
`cs2cs +proj=longlat +ellps=aust_SA +towgs84=-116,-50.47,141.69,0.23,0.39,0.344,0.0983 +no_defs +to +proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs`
with the input coordinates...
`143d55'20.5501" -37d39'15.5647" 749.671`
outputs...
`143d55'25.378"E 37d39'10.188"S 737.171`

In v6.0 it outputs...
`143d55'25.378"E 37d39'10.188"S 749.671`

The height value passed in appears to not be changed after the update. Is there any new parameters that I'm missing here?

The coordinates are taken from the GDA94 technical manual. Page 32.
http://icsm.gov.au/sites/default/files/2017-09/gda-v_2.4_0.pdf

**Comment by rouault** [comment]
Yes, this is a bit tricky. In general those towgs84 transformations corresponds to transformation in the Geographical2D domain (using EPSG/IOGP terminology), that is the Z coordinate shouldn't be changed during the operation. So now in PROJ 6, there's an additional operator that is inserted to preserve the Z value, and only apply the delta long, delta lat values. 

See https://www.epsg-registry.org/export.htm?wkt=urn:ogc:def:coordinateOperation:EPSG::1280 that is the AGD84 -> GDA94 transformation from EPSG that uses "METHOD["Coordinate Frame rotation (geog2D domain)",ID["EPSG",9607]]"

You can get the same values as 5.2 by using an explicit pipeline that does geographic -> cartesian, then cartesian -> cartesian Helmert transformation, and finally cartesian -> geographic transformation
```
echo "143.92237502777778 -37.65432352777778  749.671" | \
  cct -d 8 +proj=pipeline +step +proj=unitconvert +xy_in=deg +xy_out=rad \
   +step +proj=cart +ellps=aust_SA \
   +step +proj=helmert +x=-116 +y=-50.47 +z=141.69 +rx=0.23 +ry=0.39 +rz=0.344 +s=0.0983 +convention=position_vector \
   +step +inv +proj=cart +ellps=GRS80 \
   +step +proj=unitconvert +xy_in=deg +xy_out=rad +inv

143.92371610   -37.65282994  737.17126422           inf
```

**Comment by matherno** [comment]
Thanks for the quick explanation.
I get what's going on now.
