### ISSUE TITLE
Expose a way to use CoordinateOperationContext::setDiscardSuperseded()

### ISSUE THREAD

**Issue by matherno** [OSGeo/PROJ#1519]
I'm trying to use proj_create_operations() to obtain a list of the coordinate operations between two CRSs. It was not returning all the coordinate operations for a given from/to pair, and after much investigation I found that there is a "discard superseded" parameter on the coordinate operation context that is true by default.

It looks there are some functions to set parameters on the coordinate operation context...
`proj_operation_factory_context_set_desired_accuracy`
`proj_operation_factory_context_set_area_of_interest`
but it doesn't look there is an equivalent for setting the "discard superseded" parameter.

Is this something that just hasn't been added, or am I perhaps looking at it wrong?

Also as a side note, is there a way to obtain the coordinate operation code, of a coordinate operation returned via proj_create_operations()? It seems you can get the name, and the coordinate operation method code. Note that I'm talking about the code in the `code` column in the `coordinate_operation_view` table in proj.db, which looks to be unique between all coordinate operations.

**Comment by rouault** [comment]
> Is this something that just hasn't been added

yes, this hasn't been mapped to the C API. The need for it was not obvious. What is your actual use case for being interested in a superseded operation ?

> is there a way to obtain the coordinate operation code, of a coordinate operation returned via proj_create_operations()

proj_get_id_code(), assuming that the coordinate operation is a "single operation" (typically the one you get for operations between 2 geographic CRSs), and not a compound operation.

**Comment by matherno** [comment]
In our product we need to support older coordinate operations, as our clients are often required to use old data/maps, so we need to list all the possible coordinate operations between two chosen CRSs. 
The idea would be that the best coordinate operation would be selected by default, but the user could choose another.

**Comment by rouault** [comment]
OK, I guess you can provide a pull request implementing that ? That shouldn't be hard if you take example on other proj_operation_factory_context_set_ functions.

**Comment by matherno** [comment]
I've added this function locally and built it, and I got it into our product, and setting discard superseded to false. The returned coordinate operation list is still being sorted. I've stepped through the code and it looks like `FilterResults::removeUninterestingOps()` in coordinateoperation.cpp is removing operations still. The CoordinateOperationContext parameter discardSuperseded_ is definitely being set to false.

The example I'm using is getting the coordinate operations between EPSG:4203 and EPSG:4326. There should be 5 coordinate operations between them (according to proj.db), and I'm only receiving two of them. The grid transformation and one of the 7 parameter ones.

**Comment by rouault** [comment]
> it looks like `FilterResults::removeUninterestingOps()` in coordinateoperation.cpp is removing operations still

yes, it will remove operations that have the same area of use as others, but which are less accurate. It should probably be enhanced to take into account discardSupersed and drop that behaviour.
