### ISSUE TITLE
Link failed when using -DPROJ_RENAME_SYMBOLS

### ISSUE THREAD

**Issue by salbert-pro** [OSGeo/PROJ#1520]
Hello,

I need to build PROJ v6 with -DPROJ_RENAME_SYMBOLS for GDAL master branch.

I git cloned the source code, switched to branch 6.1, and followed the GDAL wiki [1] in order to build PROJ on Ubuntu 18.04 LTS. Here's my configure line (which is called from a separate build directory):
```configure CXXFLAGS="-DPROJ_RENAME_SYMBOLS -O2" CFLAGS="${CXXFLAGS}" --prefix=/home/salbert/local```

Note : I also have the libproj-dev system package installed for other projects.

Unfortunately the link fails, here's the trace:
```
/bin/bash ../libtool  --tag=CXX   --mode=link g++ -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wlogical-op -Wshadow -Werror=vla -Wdate-time -Wnull-dereference -Wduplicated-cond -Wfloat-conversion -Wmissing-declarations -Wnon-virtual-dtor -Weffc++ -Woverloaded-virtual -Wdeprecated -fno-operator-names -Wzero-as-null-pointer-constant  -DPROJ_RENAME_SYMBOLS -O2 -fvisibility=hidden   -o proj apps/proj.o apps/emess.o apps/utils.o libproj.la -lpthread -lm 
libtool: link: g++ -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wlogical-op -Wshadow -Werror=vla -Wdate-time -Wnull-dereference -Wduplicated-cond -Wfloat-conversion -Wmissing-declarations -Wnon-virtual-dtor -Weffc++ -Woverloaded-virtual -Wdeprecated -fno-operator-names -Wzero-as-null-pointer-constant -DPROJ_RENAME_SYMBOLS -O2 -fvisibility=hidden -o .libs/proj apps/proj.o apps/emess.o apps/utils.o  ./.libs/libproj.so -lpthread -lm -Wl,-rpath -Wl,/home/salbert/local/lib
./.libs/libproj.so: undefined reference to `internal_geod_inverse'
./.libs/libproj.so: undefined reference to `internal_geod_init'
./.libs/libproj.so: undefined reference to `internal_geod_direct'
```
I tried to build using CMake and had the same problem. Here's the cmake command I used:
```
cmake -DPROJ_TESTS=OFF -DCMAKE_INSTALL_PREFIX=/home/salbert/local -DCMAKE_CXX_FLAGS="-DPROJ_RENAME_SYMBOLS" -DCMAKE_C_FLAGS="${CXXFLAGS}" ../../src/PROJ
```
[1] : https://trac.osgeo.org/gdal/wiki/BuildingOnUnixGDAL25dev

**Comment by rouault** [comment]
CFLAGS="${CXXFLAGS}" only works for a real environment variable, so before ./configure, not after it. Same for the CMake invokation. So either do it exactly like in the wiki page, or put in the CFLAGS parameter the same content as CXXFLAGS.
