### ISSUE TITLE
Use HTTPS download URLs

### ISSUE THREAD

**Issue by paulmenzel** [OSGeo/PROJ#1521]
https://proj.org/download.html includes links to the archives. Currently, they are HTTP URLs, but should be changed to HTTPS.

**Comment by kbevers** [comment]
Thanks for pointing it out. Please submit a pull request that changes it.

**Comment by paulmenzel** [comment]
On 06/21/19 13:15, Kristian Evers wrote:
> Thanks for pointing it out. Please submit a pull request that changes it.

Done. https://github.com/OSGeo/PROJ/pull/1522
