### ISSUE TITLE
Overzealous include order check

### ISSUE THREAD

**Issue by ojwb** [OSGeo/PROJ#1523]
Here's a reduced testcase (in the full example where I hit this the first two includes are in a local header and the third in the source file):

```
$ cat projreincludebug.c
#include <proj.h>
#include <proj_api.h>
#include <proj.h>
$ gcc -c projreincludebug.c
In file included from projreincludebug.c:3:
/usr/include/proj.h:123:2: error: #error proj.h must be included before proj_api.h
 #error proj.h must be included before proj_api.h
  ^~~~~
```

But I **am** including `proj.h` before `proj_api.h`!

I'm also including it after, but it has include guards so that really ought to be fine - I think the issue here is that the `#ifdef PROJ_API_H` check in `proj.h` is outside the include guarded part.

This is with proj 5.2.0.

**Comment by kbevers** [comment]
Try again with a recent PROJ version (6.1.0 or master). If the problem still exists we are happy to receive a pull request that fixes the problem.

**Comment by kbevers** [comment]
@ojwb Have you tried this with a more recent version of PROJ?

**Comment by ojwb** [comment]
Testing the above example with Debian package 6.3.0-1 it works:

```
$ gcc -DACCEPT_USE_OF_DEPRECATED_PROJ_API_H -c projreincludebug.c
$
```
