### ISSUE TITLE
projinfo --identify and EPSG:4326

### ISSUE THREAD

**Issue by jwilson8767** [OSGeo/PROJ#1530]
In testing the new `projinfo --indentify` functionality I've noticed that results from `projinfo` do not include an authority and therefore cannot be properly identified. 

Specifically, `projinfo 'epsg:4326'` gives the proj4 string '+proj=longlat +datum=WGS84 +no_defs +type=crs'. However, feeding that proj4 string that back into identify using `projinfo --identify '+proj=longlat +datum=WGS84 +no_defs +type=crs'` which gives this result:
```
PROJ.4 string:
+proj=longlat +datum=WGS84 +no_defs +type=crs

WKT2_2018 string:
GEOGCRS["unknown",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]],
        ID["EPSG",6326]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433],
        ID["EPSG",8901]],
    CS[ellipsoidal,2],
        AXIS["longitude",east,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]],
        AXIS["latitude",north,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]]]

Identification match count: 3
OGC:CRS84: 70 %
IGNF:WGS84GDD: 70 %
IGNF:WGS84G: 70 %
```

**No mention of EPSG:4326.**

I'm of the opinion that `projinfo epsg:4326` should return the epsg alias as part of the proj4 string (like `+init=ESPG:4326 +proj=longlat +datum=WGS84 +no_defs +type=crs
`. and that `projinfo --identify` should be capable of resolving less-descriptive CRSes like 4326, 3857, etc.

**Comment by rouault** [comment]
if you try latest PROJ master and 6.1 branch (so 6.1.1RC1), "EPSG:4326: 70%" is also added to the list. This was fixed since PROJ 6.1.0

> I'm of the opinion that projinfo epsg:4326 should return the epsg alias as part of the proj4 string

I'm leading a battle to kill the use PROJ.4 strings to convey CRS, as they are a poor way of expressing CRS, so I'm not eager to do this :-)

**Comment by jwilson8767** [comment]
> This was fixed since PROJ 6.1.0

Sweet, thanks!

What are you recommending for expressing CRS going into the future?

**Comment by kbevers** [comment]
> What are you recommending for expressing CRS going into the future?

EPSG codes (and similar) and WKT(2) representations of the CRS. PROJ.4 strings does not include enough information to properly represent a CRS.

**Comment by jwilson8767** [comment]
So if those are the preferred representations, why doesn't `projinfo --identify` return the EPSG code? Or am I missing something?

**Comment by rouault** [comment]
> why doesn't `projinfo --identify` return the EPSG code?

it does. But you need PROJ master or PROJ 6.1.1RC1 to get the fix that return it for geographic CRS

```
$ ~/proj/install-proj-6.1.1/bin/projinfo  --identify '+proj=longlat +datum=WGS84 +no_defs +type=crs'
PROJ.4 string:
+proj=longlat +datum=WGS84 +no_defs +type=crs

WKT2_2018 string:
GEOGCRS["unknown",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]],
        ID["EPSG",6326]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433],
        ID["EPSG",8901]],
    CS[ellipsoidal,2],
        AXIS["longitude",east,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]],
        AXIS["latitude",north,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]]]

Identification match count: 4
OGC:CRS84: 70 %
IGNF:WGS84GDD: 70 %
IGNF:WGS84G: 70 %
EPSG:4326: 70 %
```

**Comment by jwilson8767** [comment]
Ah, I get it now, thanks!
