### ISSUE TITLE
cgms_03_26.pdf link in geos.cpp out of date

### ISSUE THREAD

**Issue by schwehr** [OSGeo/PROJ#1532]
https://github.com/OSGeo/PROJ/blob/96af6dbf69dd38421916438702be80f73276d879/src/projections/geos.cpp#L8

http://www.eumetsat.int/en/area4/msg/news/us_doc/cgms_03_26.pdf does not work

A google search for `filetype:pdf cgms_03_26.pdf` gives:

https://www.cgms-info.org/documents/pdf_cgms_03.pdf

Coordination Group for Meteorological Satellites -  LRIT/HRIT Global Specification

Which does indeed seem to have relevant descriptions of projections.  So I think I can just send a pull request with the new link.

**Comment by kbevers** [comment]
> So I think I can just send a pull request with the new link.

Go ahead :)
