### ISSUE TITLE
Segmentation fault in SQLite during compilation

### ISSUE THREAD

**Issue by elpres** [OSGeo/PROJ#1536]
I'm trying to compile version 6.1.0, and once make gets to the `data` directory, it crashes with the following error:

```
Making all in data
make[1]: Entering directory '/usr/local/tmp/proj-6.1.0/data'
Make proj.db
rm -f proj.db
/bin/sh: line 30:  6929 Done                    cat ${SQL_EXPANDED_LIST}
      6930 Segmentation fault      (core dumped) | sqlite3 proj.db
Build of proj.db failed
make[1]: *** [Makefile:575: proj.db] Error 1
make[1]: Leaving directory '/usr/local/tmp/proj-6.1.0/data'
make: *** [Makefile:457: all-recursive] Error 1
```

The SQLite version I'm using is 3.28.0, and the compiler is gcc 7.3.1 (RedHat DevToolSet-7). I did download `proj-datumgrid-1.8.zip` and unzip it into `data` directory.

**Comment by rouault** [comment]
So this would crash in sqlite3 ? Are you sure your SQLite build is sane / functional ?

**Comment by elpres** [comment]
As far as I can tell from a short test (create a DB, create a table in it, insert a row, select it), it seems to work as expected.

Is there a simple way to isolate the command that is being executed in the Makefile, so that I could run it with by itself and maybe with a different SQLite build?

**Comment by rouault** [comment]
See https://github.com/OSGeo/PROJ/issues/1508#issuecomment-499811616 for a way of isolating the issue

**Comment by elpres** [comment]
Ok, I got it. I was building against the correct version of SQLite, but then the call to the `sqlite3` binary from the Makefile used an older version from `$PATH`. Adding the `bin` folder of the newer SQLite installation to the `$PATH` solved the problem.

Thanks for the help!
