### ISSUE TITLE
The install target does not install the .pdb file for Windows debug build

### ISSUE THREAD

**Issue by joa-quim** [OSGeo/PROJ#1538]
I also had problems to load .pdb file (VS complained about a missing symbol) that is created in the ``build/bin`` dir but that's probably a different issue.

**Comment by kbevers** [comment]
Please provide more info on this so it is possible to reproduce

**Comment by joa-quim** [comment]
Not much to add. I do ``-DCMAKE_BUILD_TYPE=Debug`` and the ``ninja install`` step (I'm using ninja) does not install the .pdb file

**Comment by joa-quim** [comment]
The full batch command, but it relies on my logic for names so it wont work as is for others. But the point is, the .pdb file is not installed in the install dir.

```
set BITS=32
set VC=14

md build
cd build

cmake -G "Ninja" .. ^
		-DCMAKE_BUILD_TYPE=Debug ^
		-DCMAKE_CXX_COMPILER=cl -DCMAKE_C_COMPILER=cl ^
		-DCMAKE_INSTALL_PREFIX=../compileds/VC%VC%_%BITS% ^
		-DBUILD_LIBPROJ_SHARED=on

ninja install

cd ..
rd /S /Q build
```
