### ISSUE TITLE
History of PROJ PDF

### ISSUE THREAD

**Issue by hobu** [OSGeo/PROJ#1539]
I had tracked down some information on Jerry for my FOSS4G 2017 talk, and I'm wondering if we should include it in the docs somewhere for posterity.  I have attached it to this ticket for us to decide either way.
[history-of-proj4-foss4g2017-howard-butler.pdf](https://github.com/OSGeo/PROJ/files/3342934/history-of-proj4-foss4g2017-howard-butler.pdf)

**Comment by rouault** [comment]
Sandro Furieri (Spatialite) also has written a nice summary page of PROJ history: https://www.gaia-gis.it/fossil/libspatialite/wiki?name=PROJ.6

**Comment by kbevers** [comment]
@hobu, I think a top level "history" section is warranted. It can include your report on the work done by Jerry and Frank as well as a timeline of major milestones of the project. As the de facto PROJ house historian I would suggest you write that chapter yourself.
