### ISSUE TITLE
Cmake fails when targeting visual studio generators

### ISSUE THREAD

**Issue by szekerest** [OSGeo/PROJ#1540]
This issue applies to 6.1 and master branches with the following output:

```
CMake Error at src/lib_proj.cmake:366 (target_compile_options):
  Error evaluating generator expression:

    $<COMPILE_LANGUAGE:C>

  $<COMPILE_LANGUAGE:...> may not be used with Visual Studio generators.
Call Stack (most recent call first):
  src/CMakeLists.txt:3 (include)


CMake Error at src/lib_proj.cmake:366 (target_compile_options):
  Error evaluating generator expression:

    $<COMPILE_LANGUAGE:CXX>

  $<COMPILE_LANGUAGE:...> may not be used with Visual Studio generators.
Call Stack (most recent call first):
  src/CMakeLists.txt:3 (include)
```

The referred code fragment in src/lib_proj.cmake:

```
target_compile_options(${PROJ_CORE_TARGET}
  PRIVATE $<$<COMPILE_LANGUAGE:C>:${PROJ_C_WARN_FLAGS}>
  PRIVATE $<$<COMPILE_LANGUAGE:CXX>:${PROJ_CXX_WARN_FLAGS}>
)
```

**Comment by kbevers** [comment]
Please explain what you have done to provoke those error messages

**Comment by szekerest** [comment]
@kbevers Used the following cmd:

`cmake ..\ -G "Visual Studio 15 2017" "-DCMAKE_PREFIX_PATH=E:\builds\release-1911" "-DCMAKE_INSTALL_PREFIX=E:\builds\release-1911" -DPROJ_TESTS=OFF -DCMAKE_BUILD_TYPE=Release -DBUILD_LIBPROJ_SHARED=ON`

**Comment by rouault** [comment]
This may have something to do with your cmake version. PROJ Appveyor builds do use Visual studio generators.

**Comment by szekerest** [comment]
yes, the latest cmake doesn't seem to produce this error.

**Comment by rouault** [comment]
@mwtoews We may need to adjust our cmake minimum version requirements ?

**Comment by mwtoews** [comment]
Hmm, testing with and old CMake 3.5.2 on Windows that has VS 2017, I can't seem to reproduce this error:
> CMake Error: Could not create named generator Visual Studio 15 2017

The highest-supported VS generator supported by this CMake version is Visual Studio 14 2015. @szekerest do you recall what version of CMake raised this error?
