### ISSUE TITLE
Format PROJ strings nicely

### ISSUE THREAD

**Issue by kbevers** [OSGeo/PROJ#1543]
Instead of this

```
> projinfo -s GDA94 -t GDA2020 -o PROJ
Candidate operations found: 1
Note: using '--spatial-test intersects' would bring more results (5)
-------------------------------------
Operation n┬░1:

EPSG:8048, GDA94 to GDA2020 (1), 0.01 m, Australia - GDA

PROJ string:
+proj=pipeline +step +proj=axisswap +order=2,1 +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=push +v_3 +step +proj=cart +ellps=GRS80 +step +proj=helmert +x=0.06155 +y=-0.01087 +z=-0.04019 +rx=-0.0394924 +ry=-0.0327221 +rz=-0.0328979 +s=-0.009994 +convention=coordinate_frame +step +inv +proj=cart +ellps=GRS80 +step +proj=pop +v_3 +step +proj=unitconvert +xy_in=rad +xy_out=deg +step +proj=axisswap +order=2,1
```

`projinfo` and the relevant API functions should return this
```
> projinfo -s GDA94 -t GDA2020 -o PROJ
Candidate operations found: 1
Note: using '--spatial-test intersects' would bring more results (5)
-------------------------------------
Operation n┬░1:

EPSG:8048, GDA94 to GDA2020 (1), 0.01 m, Australia - GDA

PROJ string:
+proj=pipeline 
  +step +proj=axisswap +order=2,1 
  +step +proj=unitconvert +xy_in=deg +xy_out=rad 
  +step +proj=push +v_3 +step +proj=cart +ellps=GRS80 
  +step +proj=helmert +x=0.06155 +y=-0.01087 +z=-0.04019 +rx=-0.0394924 
        +ry=-0.0327221 +rz=-0.0328979 +s=-0.009994 +convention=coordinate_frame
  +step +inv +proj=cart +ellps=GRS80 
  +step +proj=pop +v_3 
  +step +proj=unitconvert +xy_in=rad +xy_out=deg
  +step +proj=axisswap +order=2,1
```

or something to that effect. This makes it a lot easier to read long pipelines. It will also be beneficial to downstream projects that display the PROJ string of a transformation (e.g. QGIS).

**Comment by rouault** [comment]
@kbevers Wanna try implementing this ?  Should be around line https://github.com/OSGeo/PROJ/blob/3ae09c3ba164728e200a3b930b72ed5fc24ef6ee/src/iso19111/io.cpp#L5578
I'd suggest to not to this by default because it will break a lot of existing PROJ tests (and likely a few GDAL ones as well). So should probably controlled by a PRETTY_FORMATTING=YES option that projinfo would set. proj_as_proj_string() should be enhanced to recognize that option to.

**Comment by kbevers** [comment]
> Wanna try implementing this ?

That was my intention, yes. I don't think I'll find the time for it this week but Nyalls QGIS screenshots reminded me that this should be done. Thanks for the pointers.

> So should probably controlled by a PRETTY_FORMATTING=YES option that projinfo would set. proj_as_proj_string() should be enhanced to recognize that option to.

How about a `proj_string_pretty_print()` function that takes a PROJ string and return it nicely formatted?
