### ISSUE TITLE
JSON encoding of CRS

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#1545]
Seems that @hobu (per https://github.com/opengeospatial/ideas/issues/51) and me (per https://gist.github.com/rouault/6b5deff24999288955a50294e05365eb) got the same idea of having a JSON encoding for CRS WKT could be useful. It should be strongly inspired from WKT2:2018 (at the very least compatible), but there are some constructs of WKT that don't directly translate to JSON, so mechanical translation is not possible. Actually, more than WKT2:2018, it should be strongly derived from the ISO-19111:2019 UML diagrams (or the C++ implementation in PROJ). For example, where in WKT, we have `PROJCRS["foo",BASEGEOGCRS["bar",...`, it is more appropriate to use a generic "base_crs" key, and have the value dictionary have a "type":"GeographicCRS". That way the "base_crs" key can be also used for all Derived CRS.
Martin Daly indicated he owns http://crsjson.org/ for that purpose

**Comment by hobu** [comment]
It would seem completely reasonable to me to have a projson output that's as close to WKTv2 compatible as possible.

**Comment by rouault** [comment]
Cf https://github.com/OSGeo/PROJ/pull/1547

**Comment by snowman2** [comment]
Are there plans to adding support for creating a CRS from the WKT dict?

**Comment by snowman2** [comment]
Also, is this going to be available in the C-API via `proj.h`?

**Comment by snowman2** [comment]
Related to #1548, will there be support for creating from WKT dict/exporting to WKT dict for the PrimeMeridian, Ellipsoid, Datum, etc.?

**Comment by kbevers** [comment]
Closed with #1547
