### ISSUE TITLE
How to get list of all added projections from proj4

### ISSUE THREAD

**Issue by talhametin** [OSGeo/PROJ#1550]
I added some projections by using proj4 but i need to get list of all added projections. I look the openlayers proj api document and ı didn't find the appropriate functions for this operation. How i get the list of projections, There is any function on proj4 or openlayers proj library?

**Comment by kbevers** [comment]
The list of available projections is here in the documentation: https://proj.org/operations/projections/index.html

A similar list can be retrieved via the API: https://proj.org/development/reference/functions.html#c.proj_list_operations

You have to ask the openlayers project for specifics on that.
