### ISSUE TITLE
build failure on Solaris

### ISSUE THREAD

**Issue by edechaux** [OSGeo/PROJ#1553]
Hello,

File [src/apps/emess.h](https://github.com/OSGeo/PROJ/blob/master/src/apps/emess.h) has the following code that is triggered on Solaris platform :
```
#ifdef sun /* Archaic SunOs 4.1.1, etc. */
extern char *sys_errlist[];
#define strerror(n) (sys_errlist[n])
#endif
```
From [Solaris 8 documentation](https://docs.oracle.com/cd/E19455-01/817-5441/6mkt8ktja/index.html#Use%20of%20sys_errlist/sys_nerr) in 2000, sys_errlist is obsolete and has been removed. As [sterror](https://docs.oracle.com/cd/E19455-01/817-5438/6mkt5pcea/index.html) is available since, this define is not needed anymore for Solaris and should be removed.

**Comment by edechaux** [comment]
#1554

**Comment by rouault** [comment]
Fixed per https://github.com/OSGeo/PROJ/pull/1554
