### ISSUE TITLE
aclocal: command not found + cocoapods

### ISSUE THREAD

**Issue by livebird** [OSGeo/PROJ#1557]
Even if I have install all the required command, getting this error while building.

#######
Running aclocal

  Something went wrong, giving up!

./autogen.sh: line 29: aclocal: command not found

#######

I checked in the terminal and able to run "aclocal" from there.

 I am working on macOS Mojave. Using this repository with CocoaPods.

**Comment by rouault** [comment]
you need to install the autoconf package.
Or if you use an official tarball like https://github.com/OSGeo/PROJ/releases/download/6.1.1/proj-6.1.1.tar.gz, you just need to run ./configure

**Comment by livebird** [comment]
I already have autoconf and automake installed.
I am able to build it from terminal. But when I install it with CocoaPods I am getting this error.
