### ISSUE TITLE
Performing transformations using geographic 3D offsets

### ISSUE THREAD

**Issue by stefan-pdx** [OSGeo/PROJ#1564]
Hello,

First off, thank you for maintaining Proj!

I'm attempting to perform a vertical datum transformation from a subset of source SRS's to WGS84 at runtime in an application via GDAL/OGR/Proj. To do this, I'm building a compound CS where I use WGS84 (epsg:4326) as my horizontal datum along with a vertical datum that we can assume to be EGM96 (epsg:5773) for my use case. I'm wanting to project to a 3D coordinate system compatible with WGS84 (epsg:4979).

This is how I'm configuring my transformation:
```
horizontal_coordinate_system.importFromEPSG(4326);
vertical_coordinate_system.importFromEPSG(5773);

coordinate_system.SetCompoundCS(
    "WGS84 Horizontal + EGM96 Vertical",
    &horizontal_coordinate_system,
    &vertical_coordinate_system
);

destination_coordinate_system.importFromEPSG(4979);

OGRCoordinateTransformation* transformation = OGRCreateCoordinateTransformation(
    &coordinate_system,
    &destination_coordinate_system
);
```

I'm trying to use this transformation to project elevation data from the source reference frame to the destination:

```
transformation->Transform(
    elevations.size(),
    latitudes.data(),
    longitudes.data(),
    elevations.data()
);
```

When the transformation is created, I'm receiving an exception:

```
throw io::FormattingException(
        "Transformation cannot be formatted as WKT1 TOWGS84 parameters");
```

in `coordinateoperation.cpp`. After poking around the codepaths there, I've been able to piece together that my `methodEPSGCode` is `9660` and would take me down a [codepath that is removed via pre-processor flags](https://github.com/OSGeo/PROJ/blob/e52fc2aa58504e6f0658da821bdd543d7a39df34/src/iso19111/coordinateoperation.cpp#L6228):

```
#if 0
    if (methodEPSGCode == EPSG_CODE_METHOD_GEOGRAPHIC2D_OFFSETS ||
        methodEPSGCode == EPSG_CODE_METHOD_GEOGRAPHIC3D_OFFSETS) {
...
#endif
```
Is there a particular reason as to why there's a partial implementation in there? Is this type of transformation supported by Proj? Is there an easier way to perform this transformation?

Thanks for your support!

**Comment by rouault** [comment]
I can't reproduce your issue with GDAL and PROJ, by using the Python API to do something close to your C++ code
```
from osgeo import osr
sr_h = osr.SpatialReference()
sr_h.ImportFromEPSG(4326)
sr_v = osr.SpatialReference()
sr_v.ImportFromEPSG(5773)
sr_src = osr.SpatialReference()
sr_src.SetCompoundCS("WGS84 Horizontal + EGM96 Vertical", sr_h, sr_v)
sr_dst = osr.SpatialReference()
sr_dst.ImportFromEPSG(4979)
ct = osr.CoordinateTransformation(sr_src, sr_dst)
print(ct.TransformPoint(49,2,0))
```
displays `(49.0, 2.0, 44.64349365234375)`

Do you have the egm96_15.gtx grid available ?

**Comment by rouault** [comment]
Closing due to lack of feedback
