### ISSUE TITLE
PJ_CONTEXT not releasing file handle for sqlite until destroyed

### ISSUE THREAD

**Issue by snowman2** [OSGeo/PROJ#1565]
Related to:
- https://github.com/pyproj4/pyproj/issues/374

The solution for pyproj was to use a global context so only one file handle is added. This is more efficient as there is some overhead when creating a new PJ_CONTEXT. 

However, I have noticed this impacting the use of rasterio recently when upgrading to use PROJ 6 where I had too many open file handles. I expect that this may impact other applications.

Additionally. this could impact applications that are multithreaded with one PJ_CONTEXT per thread as well (https://github.com/pyproj4/pyproj/issues/386)

What are the reasonings behind the current implementation?
Are there alternative options? If so, what are the upside/downsides of switching to one of them?

**Comment by rouault** [comment]
> What are the reasonings behind the current implementation?

Keeping one file handle per PJ_CONTEXT avoid multithreading issues on PROJ side. And keeping it open all the time saves the time of reopening it + some potential caching effects in SQLite which has a page cache. That said I never tried closing & reopening it, but I would expect some cost

> Are there alternative options?

With current code, not that much. You could have just one PJ_CONTEXT but that would mean to make sure to put a lock around all PROJ operations and potential scalability issues if PROJ is eavily used.

**Comment by snowman2** [comment]
Thanks for the response. Sounds like designing around the current implementation is the best way to go.

**Comment by rouault** [comment]
I imagine we could provide a proj_context_close_database() or something like that if that would be useful, but would it ?

**Comment by snowman2** [comment]
Another idea would be to have the methods that use the context and need database access open the database connection at the start of the function and close it on completion of the function (or error).

You could also add an argument to pass into the function if you want to manage the connection yourself for optimization reasons (and then use the proj_context_open_database/proj_context_close_database in your process).

**Comment by rouault** [comment]
> Another idea would be to have the methods that use the context and need database access open the database connection at the start of the function and close it on completion of the function (or error).

Perhaps enabled conditionnaly with a proj_context_set_autoclose_database() that would enable that behaviour for a given context.

> You could also add an argument to pass into the function

Would clutter the API to do that for all functions

**Comment by snowman2** [comment]
> Perhaps enabled conditionnaly with a proj_context_set_autoclose_database() that would enable that behaviour for a given context.

I like that option much better :+1:

So if I understand correctly, the solution could entail adding:
```
proj_context_open_database
proj_context_close_database
proj_context_set_autoclose_database
```

**Comment by rouault** [comment]
Not sure we need proj_context_open_database as this would be done automatically in any case, or perhaps if we want an explicit error in case database opening by itself fails ?

**Comment by snowman2** [comment]
> Not sure we need proj_context_open_database as this would be done automatically in any case, or perhaps if we want an explicit error in case database opening by itself fails ?

I was thinking in the case where you closed the connection and want to re-open it again for another operation. But, if the connection is automatically opened if it is not already in the functions that need the database connection, then that's even better.

**Comment by snowman2** [comment]
But, it could potentially be confusing to read code without it :stuck_out_tongue:

**Comment by rouault** [comment]
Wouldn't just proj_context_set_autoclose_database do the job for now ?

**Comment by snowman2** [comment]
> Wouldn't just proj_context_set_autoclose_database do the job for now ?

Yes, that would work for now.

**Comment by rouault** [comment]
@snowman2 I have a candidate implementation in https://github.com/OSGeo/PROJ/pull/1566 . I cannot guarantee I've patched all the code paths to close the database as unfortunately this is a manual process to track them down.

**Comment by snowman2** [comment]
Thanks for working on this! 

> I cannot guarantee I've patched all the code paths to close the database as unfortunately this is a manual process to track them down.

Definitely understandable. I can test it out on an older version of `pyproj` later and see how it fares.
