### ISSUE TITLE
Opening sqlite database

### ISSUE THREAD

**Issue by gdbassett** [OSGeo/PROJ#1572]
I am attempting to update the proj4 R package (https://github.com/cran/proj4) to work with the new proj API.  When running I am getting the error
```
proj_create_operation_factory_context: Open of /opt/conda/share/proj failed
pj_obj_create: Open of /opt/conda/share/proj failed
```
Frankly it's been decades since I've written any C so I could easily be making a mistake, but is it possible https://github.com/OSGeo/PROJ/blob/master/src/iso19111/factory.cpp#L586 is attempting to open the directory rather than the file checked at line https://github.com/OSGeo/PROJ/blob/master/src/iso19111/factory.cpp#L575?

I am using 6.11 installed through conda (https://anaconda.org/conda-forge/proj4) in an ubuntu docker container.

**Comment by gdbassett** [comment]
Received roughly the same error with a pretty straight-forward install from conda: `RUN conda install -y -c proj4`
and then attempting to install R's 'sf' package: `Rscript -e "install.packages(c("sf", "rnaturalearrth"), dependencies=TRUE)`

```
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... ERROR 1: PROJ: proj_create_from_database: Open of /opt/conda/share/proj failed
ERROR 1: PROJ: proj_create_from_database: Open of /opt/conda/share/proj failed
ERROR 1: PROJ: proj_create: Open of /opt/conda/share/proj failed
ERROR 1: PROJ: proj_create: unrecognized format / unknown name
ERROR 1: Cannot instantiate source_crs
ERROR 6: Cannot find coordinate operations from `' to `'
no
configure: error: OGRCoordinateTransformation() does not return a coord.trans: PROJ not available?
```

**Comment by gdbassett** [comment]
By changing https://github.com/OSGeo/PROJ/blob/master/src/iso19111/factory.cpp#L586 from `sqlite3_open_v2(path.c_str(), &sqlite_handle_,` to `sqlite3_open_v2(path.c_str() + "/proj.db", &sqlite_handle_,` I was able to avoid the error.  I don't know if it's a good idea, but it worked.

**Comment by rouault** [comment]
As you don't show your code, it is difficult to figure out what you do. I suspect you might use proj_context_set_database_path() but provide a directory instead of the full filename to proj.db

You might perhaps consider using proj_context_set_search_paths() instead

**Comment by rouault** [comment]
Closing due to lack of feedback. Re-open if you've new elements to add

**Comment by gdbassett** [comment]
The code is console install commands.  You can see it in the 2nd post, however I will recreate it here:
```
conda install -y -c proj4
Rscript -e "install.packages(c("sf", "rnaturalearrth"), dependencies=TRUE)
```
(If r isn't installed, it can be installed with `conda install -c r r`

I'll cross-post this on the 'sf' package in case the bug is there.
