### ISSUE TITLE
pyproj2.2.2 can not link with geopandas0.4.1 or geopandas0.4.1.

### ISSUE THREAD

**Issue by pengguanjun** [OSGeo/PROJ#1576]
pyproj2.2.**0** can  link with geopandas0.4.1 or geopandas0.4.1.
pyproj2.2.**2** **can not** link with geopandas0.4.1 or geopandas0.4.1.

**Comment by pengguanjun** [comment]
boros.to_crs({"init": "epsg:4326"}).plot(ax=ax, color="white", edgecolor="black");
The result is wrong.
or
boros.to_crs(4326);
The result is wrong too.

No error, always stuck.
Or flashback.

**Comment by kbevers** [comment]
Please report this to the pyproj project: https://github.com/pyproj4/pyproj
