### ISSUE TITLE
PROPOSAL: add proj_set_context

### ISSUE THREAD

**Issue by snowman2** [OSGeo/PROJ#1591]
Would be nice to be able to change the context associated with a PJ*. This is useful when you create a new PJ* from a different context and then want the new PJ* to have it's own context that doesn't rely on the existence of the other context.

Plan to add specific examples later.

**Comment by snowman2** [comment]
Nevermind, Looks like `proj_clone` works.

**Comment by rouault** [comment]
Looks you were looking for `proj_assign_context()` in proj_experimental.h

**Comment by snowman2** [comment]
Yep, that's the one. I think that function is worthy of promotion to proj.h. Thoughts?

**Comment by kbevers** [comment]
> Yep, that's the one. I think that function is worthy of promotion to proj.h. Thoughts?

I would be willing to accept a PR that makes that change.

**Comment by snowman2** [comment]
Would it be better to copy it over or to move it over?

**Comment by kbevers** [comment]
Move it. We don't want it present in two header files at the same time.
