### ISSUE TITLE
proj utility in PROJ 6 does not support pipelines

### ISSUE THREAD

**Issue by mbudaj** [OSGeo/PROJ#1619]
The following used to work fine in Proj version 5, but causes an error in version 6:
```
$ proj +proj=pipeline +step +inv +init=epsg:31258 +step +init=epsg:31258
Rel. 6.2.0, September 1st, 2019
<proj>:
projection initialization failure
cause: no arguments in initialization list
program abnormally terminated
 ```

This particular epsg code is just an example, the error is caused also by other combinations. It seems as if epsg projections were not initialized from the proj.db database.

Interestingly, this works fine:
`$ cs2cs +init=epsg:31258 +to +init=epsg:31258`

Tested on the current Debian-testing distribution.

**Comment by rouault** [comment]
This is not related to +init=epsg: syntax, but in PROJ 6, the `proj` utility only supports forward projections and not pipelines. Pipelines are to be used with `cct` (the fact that `proj` in  PROJ 5 supported pipelines is more an accident I think)

Actually if you do
```
PROJ_USE_PROJ4_INIT_RULES=YES proj +proj=pipeline +step +inv +init=epsg:31258 +step +init=epsg:31258
```
you'll get the error `can't initialize operations that take non-angular input coordinates`
That you'd get also if you expand the +init=epsg: terms
```
$ $ proj +proj=pipeline +step +inv +proj=tmerc +lat_0=0 +lon_0=13.3333333333333 +k=1 +x_0=450000 +y_0=-5000000 +ellps=bessel  +units=m +no_defs  +step +proj=tmerc +lat_0=0 +lon_0=13.3333333333333 +k=1 +x_0=450000 +y_0=-5000000 +ellps=bessel  +units=m +no_defs 
Rel. 7.0.0, March 1st, 2020
<proj>: 
can't initialize operations that take non-angular input coordinates
program abnormally terminated
```

**Comment by kbevers** [comment]
> the fact that proj in PROJ 5 supported pipelines is more an accident I think

Yes, this was an unintended feature of PROJ 5. the `proj` utility has always been specifically for projecting geodetic coordinates to the plane or vice versa. `proj` has always ignored geodetic features such as `+towgs84` and `+nadgrids` and for the same reason pipelines are ignored. So, this was a bug in PROJ 5 which has been fixed in PROJ 6. 

Closing this since the behaviour is intended.

**Comment by mbudaj** [comment]
Thanks for the explanation, but I get the same error using the cct utility.

```
$ cct +proj=pipeline +step +inv +init=epsg:31258 +step +init=epsg:31258
proj_create: Error -1: no arguments in initialization listcct: Bad transformation arguments - (no arguments in initialization list)
    'cct -h' for help
```


I originally came upon this problem when using C API proj_create(0, "+proj=pipeline +step +inv +init=epsg:31258 +step +init=epsg:31258") in 6.2.0 which returned the same error.

**Comment by rouault** [comment]
yes +init=epsg:XXXX syntax is deprecated and must be explicitly enabled. See https://proj.org/development/migration.html#backward-incompatibilities for how to do that and the caveats
You'd better use proj_create_crs_to_crs(ctx, "EPSG:31258", "EPSG:31258", NULL)
