### ISSUE TITLE
Accidental autopromotion to 3D for vertical transforms

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#1623]
@kbevers Remember the discussion in #1587 about transformations between a 2D CRS and a 3D one not leading to a transformation term for the vertical part, which lead to the introduction of --3d / promoteTo3D() ?  It turns out that commit eed28e51 accidentally causes a kind of autopromotion (that is to say 'projinfo -s EPSG:4326 -t  EPSG:4326+3855' will propose the egm08_25.gtx grid). I didn't intend that side effect and I'm not sure what needs to be done.

Two possibilities:
- either keep that behaviour. In which case, projinfo should be modified to no longer suggest "Warning: mix of 2D and 3D CRS. Vertical transformations, if available, will not be applied. Consider using 3D version of the CRS, or the --3d switch"
- or amend eed28e51 to be more restrictive, and check that when considering a tuple (vertical CRS, Geographic CRS), the GeogCRS is a 3D one

In any case, the 2D to 3D case should be tested somewhere, so that any behaviour change doesn't get unnoticed :-)

**Comment by rouault** [comment]
@kbevers Small ping w.r.t above question

**Comment by kbevers** [comment]
Sorry, this was on my mental list of things to get to. Thanks for the reminder.

I don't think the autopromotion is a problem. At least in this case it seems to be doing the right thing. If we want to keep that behaviour we need to document the autopromotion process, especially regarding how heights from the input (2D) system is treated. I assume the added vertical component of a "2D coordinate" is relative to the ellipsoid. And that it is 0 when only the horisontal components are provided by the user.
