### ISSUE TITLE
EPSG 9.8.2 has concatenated operations with more than 3 steps, which cannot be imported currently

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#1632]
New to EPSG 9.8.2 is the introduction of concatenated operations with more than 3 steps: EPSG:9103 (NAD27 to ITRF2014 (1)) and 9104 (NAD27 to ITRF2014 (2)) which have respectively 4 and 7 steps.
For now we can't import those since the proj.db concatenated_operations table has a hard coded limit of 3 steps. If we wanted to import such concatenated operations, we might decide either to add extra columns up to 7 steps, or add an additional table as in the EPSG db model itself, with the steps.

**Comment by kbevers** [comment]
>  or add an additional table as in the EPSG db model itself, with the steps.

Probably the best solution since it allows for an arbitrary number of steps. Murphy's law dictactes that the minute after 7 steps is hard-coded someone adds a transformation with 8 steps :-)
