### ISSUE TITLE
Update Cppcheck to the latest version, which requires source code changes

### ISSUE THREAD

**Issue by mwtoews** [OSGeo/PROJ#1648]
The Travis CI upgrade from #1634 upgraded everything but cppcheck, as this would require source code changes to suite newer versions of cppcheck. A new version of this tool can be added to `.travis.yaml` using snaps addon, [like this](https://travis-ci.com/OSGeo/PROJ/jobs/238525924/config).

Here is the list of errors from Cppcheck 1.89 (note this shows "1.90 dev") that either need to be fixed or ignored:
- [ ] src/fileapi.cpp:94,error,memleak,Memory leak: pafile
- [ ] src/gauss.cpp:81,error,memleak,Memory leak: en
memleak check failed
- [ ] src/conversions/axisswap.cpp:106,performance,passedByValue,Function parameter 'lpz' should be passed by const reference.
- [ ] src/conversions/axisswap.cpp:120,performance,passedByValue,Function parameter 'xyz' should be passed by const reference.
- [ ] src/apps/gie.cpp:877,performance,passedByValue,Function parameter 'ci' should be passed by const reference.
- [ ] src/conversions/geoc.cpp:39,performance,passedByValue,Function parameter 'coo' should be passed by const reference.
- [ ] src/conversions/geoc.cpp:44,performance,passedByValue,Function parameter 'coo' should be passed by const reference.
- [ ] src/conversions/unitconvert.cpp:315,performance,passedByValue,Function parameter 'lpz' should be passed by const reference.
- [ ] src/conversions/unitconvert.cpp:332,performance,passedByValue,Function parameter 'xyz' should be passed by const reference.
- [ ] src/fwd.cpp:200,performance,passedByValue,Function parameter 'lpz' should be passed by const reference.
- [ ] src/inv.cpp:177,performance,passedByValue,Function parameter 'xyz' should be passed by const reference.
- [ ] src/pipeline.cpp:170,performance,passedByValue,Function parameter 'lpz' should be passed by const reference.
- [ ] src/pipeline.cpp:182,performance,passedByValue,Function parameter 'xyz' should be passed by const reference.
- [ ] src/transformations/affine.cpp:72,performance,passedByValue,Function parameter 'lpz' should be passed by const reference.
- [ ] src/transformations/affine.cpp:100,performance,passedByValue,Function parameter 'xyz' should be passed by const reference.
- [ ] src/transformations/deformation.cpp:74,performance,passedByValue,Function parameter 'cartesian' should be passed by const reference.
- [ ] src/transformations/deformation.cpp:165,performance,passedByValue,Function parameter 'lpz' should be passed by const reference.
- [ ] src/transformations/deformation.cpp:211,performance,passedByValue,Function parameter 'in' should be passed by const reference.
- [ ] src/transformations/hgridshift.cpp:19,performance,passedByValue,Function parameter 'lpz' should be passed by const reference.
- [ ] src/transformations/hgridshift.cpp:33,performance,passedByValue,Function parameter 'xyz' should be passed by const reference.
- [ ] src/transformations/molodensky.cpp:267,performance,passedByValue,Function parameter 'xyz' should be passed by const reference.
- [ ] src/transformations/vgridshift.cpp:20,performance,passedByValue,Function parameter 'lpz' should be passed by const reference.
- [ ] src/transformations/vgridshift.cpp:35,performance,passedByValue,Function parameter 'xyz' should be passed by const reference.
passedByValue check failed
- [ ] src/geodesic.c:549,style,knownConditionTrueFalse,Condition 'TRUE' is always true
- [ ] src/iso19111/coordinateoperation.cpp:11778,style,knownConditionTrueFalse,Condition '!allowEmptyIntersection' is always false
- [ ] src/iso19111/coordinateoperation.cpp:12046,style,knownConditionTrueFalse,Condition '!allowEmptyIntersection' is always false
- [ ] src/iso19111/coordinateoperation.cpp:12215,style,knownConditionTrueFalse,Condition '!allowEmptyIntersection' is always false
- [ ] src/iso19111/coordinateoperation.cpp:12602,style,knownConditionTrueFalse,Condition '!allowEmptyIntersection' is always false
- [ ] src/iso19111/coordinateoperation.cpp:12640,style,knownConditionTrueFalse,Condition '!allowEmptyIntersection' is always false
- [ ] src/iso19111/coordinateoperation.cpp:12678,style,knownConditionTrueFalse,Condition '!allowEmptyIntersection' is always false
- [ ] src/iso19111/coordinateoperation.cpp:12704,style,knownConditionTrueFalse,Condition '!allowEmptyIntersection' is always false
- [ ] src/iso19111/coordinateoperation.cpp:12757,style,knownConditionTrueFalse,Condition '!allowEmptyIntersection' is always false
- [ ] src/iso19111/coordinateoperation.cpp:12792,style,knownConditionTrueFalse,Condition '!allowEmptyIntersection' is always false
- [ ] src/iso19111/coordinateoperation.cpp:12827,style,knownConditionTrueFalse,Condition '!allowEmptyIntersection' is always false
- [ ] src/iso19111/coordinateoperation.cpp:13002,style,knownConditionTrueFalse,Condition '!allowEmptyIntersection' is always false
- [ ] src/iso19111/coordinateoperation.cpp:13030,style,knownConditionTrueFalse,Condition '!allowEmptyIntersection' is always false
- [ ] src/iso19111/coordinateoperation.cpp:13181,style,knownConditionTrueFalse,Condition '!allowEmptyIntersection' is always false
- [ ] src/iso19111/coordinateoperation.cpp:13222,style,knownConditionTrueFalse,Condition '!allowEmptyIntersection' is always false
- [ ] src/iso19111/coordinateoperation.cpp:13371,style,knownConditionTrueFalse,Condition '!allowEmptyIntersection' is always false
- [ ] src/iso19111/coordinateoperation.cpp:13378,style,knownConditionTrueFalse,Condition '!allowEmptyIntersection' is always false
knownConditionTrueFalse check failed
- [ ] src/conversions/axisswap.cpp:81,style,unreadVariable,Variable 'in.lp' is assigned a value that is never used.
- [ ] src/conversions/axisswap.cpp:96,style,unreadVariable,Variable 'in.xy' is assigned a value that is never used.
- [ ] src/conversions/axisswap.cpp:111,style,unreadVariable,Variable 'in.lpz' is assigned a value that is never used.
- [ ] src/conversions/axisswap.cpp:126,style,unreadVariable,Variable 'in.xyz' is assigned a value that is never used.
- [ ] src/transformations/deformation.cpp:90,style,unreadVariable,Variable 'geodetic.lpz' is assigned a value that is never used.
unreadVariable check failed
- [ ] src/geodesic.c:97,error,invalidFunctionArg,Invalid sqrt() argument nr 1. The value is -1 but the valid values are '0.0:'.
- [x] src/tests/geodtest.cpp:362,error,invalidFunctionArg,Invalid sqrt() argument nr 1. The value is -1 but the valid values are '0.0:'.
- [x] src/tests/geodtest.cpp:507,error,invalidFunctionArg,Invalid sqrt() argument nr 1. The value is -1 but the valid values are '0.0:'.
- [x] src/tests/geodtest.cpp:787,error,invalidFunctionArg,Invalid sqrt() argument nr 1. The value is -1 but the valid values are '0.0:'.

Furthermore, it should be noted that `scripts/cppcheck.sh` should be revised/upgraded to handle newer error codes that have been added to cppcheck.

**Comment by cffk** [comment]
I'll submit a pull request to address the issues with geodesic.c and geodtest.c.  (Now that we're guaranteed to be on a C99 compliant system, I can use nan("0") to return NAN.)
