### ISSUE TITLE
Q: migrating to libproj6

### ISSUE THREAD

**Issue by slazav** [OSGeo/PROJ#1662]
Hi,

I am trying to switch my project to libproj-6 api. There are a few questions.

**1**. Building crs-to-crs transformation. If I do something like this:
```
  const char *str1 = "+datum=WGS84 +proj=lonlat";
  const char *str2 = "+datum=WGS84 +proj=lonlat";
  PJ * pj = proj_create_crs_to_crs(0, str1,str2,0);
```
I have "proj_create_operations: source_crs is not a CRS" message. Putting +datum after +proj fixes it. Previously order of parameters was not important. Is it a documented change of  behavior? Are there any other restrictions in the order of parameters?

**2**. Error messages. In the example above the error message goes to stderr. If I try to use proj_errno_string(proj_errno(0)) it will be "generic error of unknown origin". How to switch off stderr output and handle this error message in the code?

**3**. Ok, I found out that +datum should go after +proj setting. I also found that I have to provide degrees instead of radians (it was not obvious from the documentation). Now I want to convert coordinates, but I have different results in old and new interface. The new one does not convert altitude.
```
  const char *str1 = "+proj=lonlat +datum=WGS84";
  const char *str2 = "+proj=lonlat +ellps=krass +towgs84=+28,-130,-95";
```
Old:
```
  PJ * pj1 = pj_init_plus(str1);
  PJ * pj2 = pj_init_plus(str2);
  pj_transform(pj1,pj2, 1,1, &x, &y, &z);
```
New:
```
  PJ * pj = proj_create_crs_to_crs(0, str1,str2,0);
  proj_trans_generic(pj, PJ_FWD, &x,0,1, &y,0,1, &z,0,1, 0,0,0);
```
What have changed?

**4**. How to replace old pj_is_latlong() function in my case?. Documentation says that I should use proj_get_type(), but I still do not understand how to use it. If I apply it directly to my PJ, I just learn that I have a
PJ_TYPE_CONCATENATED_OPERATION with 3 steps:
- PJ_TYPE_CONVERSION
- PJ_TYPE_TRANSFORMATION
- PJ_TYPE_TRANSFORMATION

**5**. I tried to replace proj_create_crs_to_crs with
proj_create_crs_to_crs_from_pj, and it did not work:

  const char *str1 = "+proj=lonlat +datum=WGS84";
  const char *str2 = "+proj=lonlat +ellps=krass +towgs84=+28,-130,-95";
  PJ * pj1 = proj_create(0, str1);
  PJ * pj2 = proj_create(0, str2);
  PJ * pj = proj_create_crs_to_crs_from_pj(0, pj1,pj2, 0,0);
  
again gives "proj_create_operations: source_crs is not a CRS". What is wrong here? Why it is different from using proj_create_crs_to_crs()?

**Comment by snowman2** [comment]
Hope this helps:

1/5. For your PROJ strings, you need to add `+type=crs` to it.
2. https://github.com/pyproj4/pyproj/blob/master/pyproj/_datadir.pyx
4. https://github.com/pyproj4/pyproj/blob/4fbbec45780e4a5b60377d9f91fc58024fc4dde8/pyproj/_crs.pyx#L2171-L2224
