### ISSUE TITLE
No latest version of docker image in docker hub (v6.2.0)

### ISSUE THREAD

**Issue by ghost** [OSGeo/PROJ#1672]
I can see PROJ is at version 6.2.0 but in the [docker hub ](https://hub.docker.com/r/osgeo/proj/tags) the latest version is 6.1.
Is automatic build broken or discontinued?

**Comment by senderle** [comment]
Not sure this is related, but I ran into some issues using 6.2.0 in an alpine container, described [here](https://github.com/alpinelinux/docker-alpine/issues/45). My fix was to recompile from source (result [here](https://cloud.docker.com/u/senderle/repository/docker/senderle/pystgis) in case it is useful).

**Comment by hobu** [comment]
The automated docker builds have been broken for a while when DockerHub + GitHub changed their application integration policies. I will get this fixed up.
