### ISSUE TITLE
cct outputs excessive whitespace comments are included in input data

### ISSUE THREAD

**Issue by kbevers** [OSGeo/PROJ#1677]
As the title says, `cct` prints too much whitespace when comments are included in input data. An empty line is printed whenever an input line contains a comment, or is perceived as including a comment (as the `-t2000` case below). A few examples to illustrate the point:

```
$ cat coords.txt
1 2 3  200
4 5 6  200

$ cct +proj=noop coords.txt
       1.0000         2.0000        3.0000      200.0000
       4.0000         5.0000        6.0000      200.0000

$ cct -t2000 +proj=noop coords.txt
       1.0000         2.0000        3.0000     2000.0000 200

       4.0000         5.0000        6.0000     2000.0000 200

$ cat coords_comment.txt
1 2 3  200 A
4 5 6  200 B

$ cct +proj=noop coords_comment.txt
       1.0000         2.0000        3.0000      200.0000 A

       4.0000         5.0000        6.0000      200.0000 B
```

**Comment by ghost** [comment]
The excessive white space you refer to, is the result of the CR in the input; the solution
is easy. Around line 380 of cct.cpp, you will find the following code:

        /* handle comment string */
        comment = column(buf, nfields+1);
        if (opt_given(o, "c")) {
            /* what number is the last coordinate column in the input data? */
            int colmax = 0;
            for (i=0; i<4; i++)
                colmax = MAX(colmax, columns_xyzt[i]);
            comment = column(buf, colmax+1);
        }
        comment_delimiter = (comment && *comment) ? whitespace : blank_comment;

Inserting the following above the last line above solves the problem:

        // Replace CR w/ '\0'
        size_t len = strlen(comment);
        if (len >= 1)
            comment[len - 1] = '\0';

Regards,
Henri

**Comment by kbevers** [comment]
@Houder Do you mind opening a pull request with your fix?

**Comment by ghost** [comment]
On 2020-11-17 10:49, Kristian Evers wrote:
> @Houder Do you mind opening a pull request with your fix?

Not in principle. But I only registered to Github this morning
in order to comment to your bug report.

In short, my knowledge of Github is nill; (yes, I do have some
knowledge of git).

So, first I have some study to do.

Regards,
Henri

**Comment by kbevers** [comment]
Sounds good. If you already are familiar with git it shouldn't be too difficult for you to figure the rest out. I'm happy to help you get started if there's something you get stuck on.
