### ISSUE TITLE
PROJ 6.2.0 Fails Tests Ubuntu 18.0.4

### ISSUE THREAD

**Issue by crabel99** [OSGeo/PROJ#1693]
Following the instructions from https://proj.org/install.html#compilation-and-installation-from-source-code has resulted in failure of `PROJ` to successfully pass testing. I am using the stock system python `/usr/bin/python` v2.7.15 for googletest. Note, this also fails for /usr/bin/python3 and for a custom build of python3.8.
```bash
# Install dependencies
apt install sqlite3 libsqlite3-dev libsqlite3-0
# Download latest proj-datumgrid packages
wget -P proj-datumgrid https://download.osgeo.org/proj/proj-datumgrid-1.8.zip
wget -P proj-datumgrid https://download.osgeo.org/proj/proj-datumgrid-world-1.0.zip
wget -P proj-datumgrid https://download.osgeo.org/proj/proj-datumgrid-oceania-1.0.zip
wget -P proj-datumgrid https://download.osgeo.org/proj/proj-datumgrid-north-america-1.2.zip
wget -P proj-datumgrid https://download.osgeo.org/proj/proj-datumgrid-europe-1.4.zip
# Clone and checkout PROJ
git clone https://github.com/OSGeo/PROJ.git
cd PROJ
git checkout 6.2.0
# Install proj-datumgrid packages
unzip -o ../proj-datumgrid/proj-datumgrid-1.8.zip -d data/
unzip -o ../proj-datumgrid/proj-datumgrid-world-1.0.zip -d data/
unzip -o ../proj-datumgrid/proj-datumgrid-oceania-1.0.zip -d data/
unzip -o ../proj-datumgrid/proj-datumgrid-north-america-1.2.zip -d data/
unzip -o ../proj-datumgrid/proj-datumgrid-europe-1.4.zip -d data/
mkdir build && cd build
cmake ..
cmake --build .
ctest
```
with the following `stdout`
```stdout
37% tests passed, 26 tests failed out of 40

Total Test time (real) =   3.12 sec

The following tests FAILED:
	  3 - Builtins2 (Failed)
	  8 - 4D-API-cs2cs-style (Failed)
	 11 - GIGS-5101.1-jhs (Failed)
	 12 - GIGS-5101.2-jhs (Failed)
	 13 - GIGS-5101.3-jhs (Failed)
	 14 - GIGS-5101.4-jhs-etmerc (Failed)
	 15 - GIGS-5102.1 (Failed)
	 16 - GIGS-5103.1 (Failed)
	 17 - GIGS-5103.2 (Failed)
	 18 - GIGS-5103.3 (Failed)
	 19 - GIGS-5105.2 (Failed)
	 20 - GIGS-5106 (Failed)
	 21 - GIGS-5107 (Failed)
	 22 - GIGS-5109 (Failed)
	 23 - GIGS-5111.1 (Failed)
	 24 - GIGS-5112 (Failed)
	 25 - GIGS-5113 (Failed)
	 26 - GIGS-5201 (Failed)
	 27 - GIGS-5208 (Failed)
	 30 - testvarious (Failed)
	 31 - testIGNF (Failed)
	 32 - testprojinfo (Failed)
	 33 - testprojinfo (Failed)
	 34 - proj_pj_transform_test (Failed)
	 39 - proj_test_cpp_api (SEGFAULT)
	 40 - gie_self_tests (Failed)
Errors while running CTest
```
Note: when only the base proj-datumgrid-1.8 is installed, one of the above failed tests passes, `33 - testprojinfo`. I thought that was odd and interesting. Not sure if it is germane to this issue...

I think there is an issue somewhere in the code because `gdal` isn't passing its tests due to failed projection transformations. Additionally, other applications which rely on `gdal` fail for the same reason (e.g. `sf`, `rgdal` and `postgis`). `gdal` does successfully build against `PROJ`

**Comment by rouault** [comment]
The tests should pass with no grid package or just with proj-datumgrid-1.8.zip. Additional packages will change the result of some coordinate operations, and cause failures in some tests. The segfault in proj_test_cpp_api is a bit unfortunate that said

**Comment by rouault** [comment]
hum just thinking, there was an issue with ctest not setting PROJ_LIB. This has been fixed in master, so this might be the cause of some failures you see.

**Comment by crabel99** [comment]
I get similar failures when I use the more traditional autogen as well. I'm runnign through various configurations. Using the kits in VS Code `cmake-tools` package I have 24 out of 41 tests failing.

**Comment by crabel99** [comment]
Using `cmake-tools` in VS Code, and only installing `proj-datumgrid-1.8.zip` I get the following:
```stdout
43% tests passed, 23 tests failed out of 40

Total Test time (real) =   6.96 sec

The following tests FAILED:
          3 - Builtins2 (Failed)
          8 - 4D-API-cs2cs-style (Failed)
         11 - GIGS-5101.1-jhs (Failed)
         12 - GIGS-5101.2-jhs (Failed)
         13 - GIGS-5101.3-jhs (Failed)
         14 - GIGS-5101.4-jhs-etmerc (Failed)
         15 - GIGS-5102.1 (Failed)
         16 - GIGS-5103.1 (Failed)
         17 - GIGS-5103.2 (Failed)
         18 - GIGS-5103.3 (Failed)
         19 - GIGS-5105.2 (Failed)
         20 - GIGS-5106 (Failed)
         21 - GIGS-5107 (Failed)
         22 - GIGS-5109 (Failed)
         23 - GIGS-5111.1 (Failed)
         24 - GIGS-5112 (Failed)
         25 - GIGS-5113 (Failed)
         26 - GIGS-5201 (Failed)
         27 - GIGS-5208 (Failed)
         30 - testvarious (Failed)
         31 - testIGNF (Failed)
         34 - proj_pj_transform_test (Failed)
         39 - proj_test_cpp_api (Failed)
Errors while running CTest
```

**Comment by rouault** [comment]
> Using `cmake-tools` in VS Code, and only installing `proj-datumgrid-1.8.zip` I get the following:

yes, as I said that's "expected" with 6.2 with ctest if you don't explicitly set PROJ_LIB to the installation path $(install_prefix)/share/proj. But `make check` with autoconf builds should work fine

**Comment by crabel99** [comment]
Sorry, make check deletes proj.db and I had to recompile... 
Here is the `configure` script output:
[proj_configure.txt](https://github.com/OSGeo/PROJ/files/3773165/proj_configure.txt)
Here is the `make check` output:
[proj_check.txt](https://github.com/OSGeo/PROJ/files/3773187/proj_check.txt)

**Comment by crabel99** [comment]
Looking through the file it looks like it passed all of the tests.

**Comment by crabel99** [comment]
Thanks for the help!!
