### ISSUE TITLE
mercator projection inverse `proj` command differs from `proj_create` + `proj_trans`

### ISSUE THREAD

**Issue by snowman2** [OSGeo/PROJ#1699]
Reference: https://github.com/pyproj4/pyproj/issues/470

Using the `proj` utility I get:
```
$ echo 3640945.346538976 -9059984.893837836 | proj -d 8 -I +proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +a=6378137 +b=6378137 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
32.70716853	-62.83532199
$ proj
Rel. 6.2.0, September 1st, 2019
usage: proj [-bdeEfiIlmorsStTvVwW [args]] [+opt[=arg] ...] [file ...]
```

Using `proj_create` and `proj_trans` with this code:
```python
def inverse(object projstr, float xx, float yy):
    cdef PJ* projobj = proj_create(NULL, cstrencode(projstr))
    cdef PJ_COORD projxyin
    cdef PJ_COORD projlonlatout
    projxyin.xy.x = xx
    projxyin.xy.y = yy
    projlonlatout = proj_trans(projobj, PJ_INV, projxyin)
    proj_destroy(projobj)
    return projlonlatout.uv.u, projlonlatout.uv.v

def inverse_arr(object projstr, double xx, double yy):
    cdef PJ* projobj = proj_create(NULL, cstrencode(projstr))
    proj_trans_generic(
        projobj,
        PJ_INV,
        &xx, _DOUBLESIZE, 1,
        &yy, _DOUBLESIZE, 1,
        NULL, _DOUBLESIZE, 0,
        NULL, _DOUBLESIZE, 0,
    )
    proj_destroy(projobj)
    return xx, yy
```

Then, executing it, I get:
```python
>>> from math import degrees
>>> EPSG_3857_PROJ4 = '+proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +a=6378137 +b=6378137 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs'
>>> ix, iy = inverse(EPSG_3857_PROJ4, 3640945.346538976, -9059984.893837836)
>>> degrees(ix), degrees(iy)
(32.707167667173714, -62.99092544578591)
>>> iax, iay = inverse_arr(EPSG_3857_PROJ4, 3640945.346538976, -9059984.893837836)
>>> degrees(iax), degrees(iay)
(32.70716853439809, -62.99092501209502)
>>> from pyproj import proj_version_str
>>> proj_version_str
'6.2.0'
```

I haven't dug in enough to be sure what is going on, but it seems to be this way since PROJ 6.0.0 and has the same issue with PROJ `master` from what I can tell by installing past pyproj versions. Any insight?

**Comment by rouault** [comment]
There's a confusion between PROJ CRS strings and PROJ pipeline in that use case. When you use '+proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +a=6378137 +b=6378137 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs', you kind of try to define a CRS, but

1) the proj utililty has always ignored any datum transformation terms lik +towgs84, so if you remove it for the proj invokation, you'll get the same results
```
$ echo 3640945.346538976 -9059984.893837836 | src/proj -d 8 -I +proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +a=6378137 +b=6378137 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
32.70716853	-62.83532199

$ echo 3640945.346538976 -9059984.893837836 | src/proj -d 8 -I +proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +a=6378137 +b=6378137 +units=m +no_defs
32.70716853	-62.83532199
```

2) your inverse_arr() use case is equivalent to the following cct invokation:
```
$ echo 3640945.346538976 -9059984.893837836 0 | src/cct -d 8 -I +proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +a=6378137 +b=6378137 +towgs84=0,0,0,0,0,0,0 +units=m +no_def
   32.70716853    -62.99092501  16944.99859326           inf
```
In a cct/proj_trans() context, +towgs84= is honoured and the above is internally translated as
```
$ echo 3640945.346538976 -9059984.893837836 0 | src/cct -d 8 +proj=pipeline +step +inv +proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +a=6378137 +b=6378137 +step +proj=cart  +a=6378137 +b=6378137 +step +proj=helmert +x=0 +y=0 +z=0 +step +inv +proj=cart +ellps=WGS84
   32.70716853    -62.99092501  16944.99859326           inf
```

3) This PROJ string meant to represent WebMercator is a incorrect one. GDAL/PROJ have always expected a nagrids=@null instead of towgs84=0,0,0 to avoid doing any geographic/geocentric conversion
So using `+proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +a=6378137 +b=6378137 +nadgrids=@null  +units=m +no_def` with cct/proj_trans() will lead to the expected result:
```
$ echo 3640945.346538976 -9059984.893837836 0 | src/cct -d 8 -I +proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +a=6378137 +b=6378137 +nadgrids=@null  +units=m +no_def
   32.70716853    -62.83532199    0.00000000           inf
```

All in all I believe PROJ behaves as intended

**Comment by snowman2** [comment]
Perfect, thanks for the explanation! That makes sense. I will pass along the explanation.

**Comment by snowman2** [comment]
One thing that I just thought about is that the `inverse` function should behave like `proj` correct? If that is true, then something is amiss here as it behaves like `cct`.

**Comment by rouault** [comment]
your inverse and inverse_arr functions should actually both behave like cct. But one thing that is wrong in inverse() is the use of the float type. It is definitely not wide enough for the accuracy you generally want.

**Comment by snowman2** [comment]
> your inverse and inverse_arr functions should actually both behave like cct

Okay, good to know.

> But one thing that is wrong in inverse() is the use of the float type. 

Good to know. It is `double` in the pyproj code, so we're good to go there.

Thanks for clearing that up for me 👍
