### ISSUE TITLE
Elevation don't change during pj_trans

### ISSUE THREAD

**Issue by ClementLeBihan** [OSGeo/PROJ#1707]
Hi,
I'm trying to transform WGS84 (RPSG:4326) to special ENU TF (+proj=tmerc +lat_0=48.8564814 +lon_0=2.352014 +x_0=0 +y_0=0 +ellps=WGS84 +units=m +no_defs), but altitude isn't transformed ! 

Here is the code I use :

```
int main()
{
	PJ_CONTEXT *C = proj_context_create();
	PJ *P = proj_create_crs_to_crs (C,"EPSG:4326","+proj=tmerc +lat_0=48.8564814 +lon_0=2.352014  +k_0=0.1 +x_0=0 +y_0=0 +ellps=WGS84 +units=m +no_defs", NULL);
	PJ_COORD a, b;

	a = proj_coord (43.6044715,1.4439527, 157.22, 0);
	b = proj_trans (P, PJ_FWD, a);

	std::cout << b.enu.e << " " << b.enu.n << " " << b.enu.u << std::endl;

	return 0;
}
```
The b.enu.u will still be 157.22, while it should be less (in the ENU Plane reference) because of the earth curvature. Which Option should I use ? 

Best,
Clément

**Comment by rouault** [comment]
There's a misunderstanding on what the .enu means. The .enu member of PROJ_COORD is for easting, northing, up of a projected CRS, not the local ENU Plane reference.  You're probably wanting this feature request : https://github.com/OSGeo/PROJ/issues/500

**Comment by ClementLeBihan** [comment]
Alright. So for now there is no such Matlab's geodetic2enu function in PROJ right ? 

Thank for your quick response !
Best,
Clément

**Comment by kbevers** [comment]
> Alright. So for now there is no such Matlab's geodetic2enu function in PROJ right ?

No, there isn't. But you are very welcome to provide such functionality :-)

**Comment by ClementLeBihan** [comment]
Unfortunately I've no knowledge about geospatial coordinates transform :/ 
Thank you for your help !
Clément
