### ISSUE TITLE
"constraints: - proj4 ==999999999999" in conda and incompatibility between proj 6.2.0 and basemap 1.2.1

### ISSUE THREAD

**Issue by Khris777** [OSGeo/PROJ#1714]
I had troubles installing `proj 6.2.0` with `basemap 1.2.1` as `proj 6.2.0` only worked with basemap `1.2.0` which didn't work at all because of a missing `espg` file.

During troubleshooting [I asked about the issue on stackoverflow](https://stackoverflow.com/questions/58622260/fail-to-install-basemap-1-2-1-with-conda-due-to-package-conflicts-how-to-resolv/58622552?noredirect=1#comment103574986_58622552) and [one user](https://stackoverflow.com/a/58622552/2756793) brought this issue to my attention:

Checking `proj 6.2.0` details with `conda search proj=6.2.0 --info -c conda-forge` returns:

```
proj 6.2.0 ha7a8c7b_1
---------------------
file name   : proj-6.2.0-ha7a8c7b_1.tar.bz2
name        : proj
version     : 6.2.0
build       : ha7a8c7b_1
build number: 1
size        : 8.5 MB
license     : MIT
subdir      : win-64
url         : https://conda.anaconda.org/conda-forge/win-64/proj-6.2.0-ha7a8c7b_1.tar.bz2
md5         : d112566d5617b2f13d7cdf2197a56465
timestamp   : 2019-09-24 13:47:02 UTC
constraints :
  - proj4 ==999999999999
dependencies:
  - sqlite >=3.29.0,<4.0a0
  - vc >=14.1,<15.0a0
```

The entry `- proj4 ==999999999999` looks weird, and it might be a reason for the package conflicts I have encountered. Can you check on this?

I was only able to install `basemap 1.2.1` together with `proj4 5.2.0`.

**Comment by kbevers** [comment]
Well, this is a problem in conda, not PROJ. This looks like the conda folks have applied measures that prevents the `proj` package from being installed simultaneously with the `proj4` package. This is a part of the migration to PROJ version 6.

I suggest you open an issue at https://github.com/conda-forge/proj.4-feedstock/ if you need a more thorough answer.
