### ISSUE TITLE
Where can I get proj.db?

### ISSUE THREAD

**Issue by SharpSnake** [OSGeo/PROJ#1716]
I use gdal with static-link to proj, and always get a message like "can't find proj.db".

**Comment by rouault** [comment]
set appropriately the PROJ_LIB environment variable to point to the directory where proj.db is installed

**Comment by SharpSnake** [comment]
> set appropriately the PROJ_LIB environment variable to point to the directory where proj.db is installed

Here comes the next question: how can I install the "proj.db". 
I tried to install OSGeo4W and other things, but still not work(can't find that db file).
