### ISSUE TITLE
cannot find the libproj.13

### ISSUE THREAD

**Issue by SuyueLiu** [OSGeo/PROJ#1717]
hello:
when I am working, there is an error as follow:
"dyld: Library not loaded: /usr/local/opt/proj/lib/libproj.13.dylib
  Referenced from: /Users/aaron/sumo/bin/sumo
  Reason: image not found
  Abort trap: 6"

I am using mac with the latest os, I searched online for a long time, but I still do not find a proper approach to solve this problem.
It seems something wrong with the path of my proj, I use the `which proj` to check the path( /usr/local/bin/proj ). Shall I link this two paths ?
I check the env variables of my laptop, I can't find the one for proj.
Would you pleasr give me some helps, thank you!

Suyue Liu

**Comment by rouault** [comment]
This is a general problem with linking to a native library. You'll find better resources on the general net for that.
