### ISSUE TITLE
proj 6.2.1 is very slow with sqlite 3.7.17-8 on RHEL 7 

### ISSUE THREAD

**Issue by akrherz** [OSGeo/PROJ#1718]
I've discovered that Proj 6.2.1 (packaged by yum.postgresql.org) runs very slow on Red Hat Enterprise 7.  For example:

```
echo "0 0" | time /usr/proj62/bin/cs2cs +proj=longlat +datum=WGS84 +to +init=epsg:2163
9473741.42	1181205.06 0.00
3.04user 0.11system 0:03.15elapsed 99%CPU (0avgtext+0avgdata 14744maxresident)k
0inputs+0outputs (0major+92566minor)pagefaults 0swaps
```

So 3.04 seconds!  On RHEL8, that command finishes in 0.06 seconds. 

RHEL7 ships with sqlite version 3.7.17. Is this version too old?

As a test, I built (./configure && make install) proj 6.2.1 manually myself on RHEL7 too and got a similar result
```
echo "0 0" | time /usr/local/bin/cs2cs +proj=longlat +datum=WGS84 +to +init=epsg:2163
9473741.42	1181205.06 0.00
2.92user 0.10system 0:03.03elapsed 99%CPU (0avgtext+0avgdata 14748maxresident)k
0inputs+0outputs (0major+92567minor)pagefaults 0swaps
```

Thank you

**Comment by rouault** [comment]
> Is this version too old?

Likely. Indeed I can reproduce slowness with old SQLite versions. This seems related to doing queries in the coordinate_operation_with_conversion_view view. I could reproduce also with 3.8.2. With 3.11.0 that comes with Ubuntu 16.04 the timings are OK. Looks like an optimization was added in SQLite for such queries between those two points.

**Comment by kbevers** [comment]
@rouault Is this grounds for changing the minimum requirements for SQLite? Or perhaps just state somewhere that we recommend using a newer version? Currently we require version 3.7.

**Comment by rouault** [comment]
> Is this grounds for changing the minimum requirements for SQLite?

yes: https://github.com/OSGeo/PROJ/pull/1721

**Comment by mwtoews** [comment]
For the record, I've [found](https://lists.osgeo.org/pipermail/proj/2019-November/008999.html) the exact minimum release of SQLite should be 3.8.11

**Comment by rouault** [comment]
Resolution is to require SQLite 3.11 at the minimum per #1721

**Comment by devrimgunduz** [comment]
Are you all aware that you'll kick out RHEL 7 users after this?

**Comment by rouault** [comment]
> Are you all aware that you'll kick out RHEL 7 users after this?

Yes, unfortunately, but there is no real alternative... Unfortunately the LTR character of RHEL with its dependencies that are aging isn't really compatible with the requirements of new PROJ versions.
