### ISSUE TITLE
Basic Vertical Transformation based on Australia grids issues

### ISSUE THREAD

**Issue by ClimateYukon** [OSGeo/PROJ#1724]
Hello,

I have been trying to get vertical transformation working for Australia, I installed the grid packs but I still seem to be missing a few important grids which keep me from doing any transformation.
Not sure if this is a PROJ issue but here is an example : 

`projinfo -s EPSG:4283 -t EPSG:4283+5711 --spatial-test intersects`
or
`projinfo -s EPSG:4283+7030 -t EPSG:4283+5711 --spatial-test intersects`

Returns a couple transformation but all of them are missing something : 

`Grid AUSGeoid09_GDA94_V1.01_DOV_windows.gsb needed but not found on the system.
Grid AUSGeoid2020_windows_binary.gsb needed but not found on the system.
`
Am I missing a package or are Australian vertical transformations not supported by PROJ out of the box?

Any hints on how I could solve this?

**Comment by rouault** [comment]
From http://www.ga.gov.au/ausgeoid/ , I've found https://s3-ap-southeast-2.amazonaws.com/geoid/AUSGeoid09_V1.01.gsb . The use of .gsb files from geoid models is highly unusual. It appears that the first channel of the .gsb file is the geoid undulation that is usually put in a .gtx file by PROJ (the second and third one would be the deflection of the vertical according https://www.ga.gov.au/scientific-topics/positioning-navigation/geodesy/ahdgm/ausgeoid2020, which we ignored). So technically we have everything needed to create a geoid file recognized by PROJ. The only thing I couldn't find is the license of the original .gsb file.
Anybody has connections with http://www.ga.gov.au to know if their geoid files are available under a open data/free software license ? ping @nyalldawson @camerons

**Comment by ClimateYukon** [comment]
@rouault thanks for answering,
I reached out to them and got an answer from Howard who also included proj mailing list in his answer so here is what he told me : 

> All,
> 
> Even has written a crowdfunding page on the CDN and grid files topic at https://www.spatialys.com/en/crowdfunding/ that I had discussed this earlier at https://lists.osgeo.org/pipermail/proj/2019-September/008858.html and its subsequent email thread. The page also provides a detailed proposal (though not in final RFC form) that outlines the technical development activities to achieve the effort. Sponsors have pledged half of the resources to complete this topic, but we still need more resources to bring it over the finish line (or starting line, depending on your perspective). If your organization is interested in helping, please contact me or Even directly.
> 
> Howard

From my little understanding it would take a considerable effort to bring those grids to proj but as a basic user I don't understand much more than that.

**Comment by rouault** [comment]
Nicholas Brown, Director of National Geodesy at Geoscience Australia, has confirmed by email to me (Even Rouault) on 2019-Nov-24 that AUSGeoid models all have the CCBY 4.0 <https://creativecommons.org/licenses/by/4.0/> licence.

**Comment by rouault** [comment]
The Australian AUSGeoid grids have now been included and referenced in the database. Closing
