### ISSUE TITLE
Request to add southern African north-oriented CRSs to proj6 db

### ISSUE THREAD

**Issue by gubuntu** [OSGeo/PROJ#1728]
Following on from https://github.com/OSGeo/PROJ/issues/1503

QGIS users in southern Africa have grown accustomed to the 'ZANGI' north-oriented versions of the official EPSG south-oriented CRSs for South Africa (where -axis=enu instead of wsu), or having to create custom north-oriented CRSs because there are no official EPSG ones. 

These will be lost to QGIS users as soon as Proj6 lands. 

So I'd like to request that they be added to the proj6 database so they become available to all platforms that use Proj6. 

In addition I'd like to request equivalent north-oriented ones for Namibia (Schwarzeck). 

The ESRI ones are incorrect (they switch -k instead of -axis, amongst other inconsistencies).

It would also be useful to add a few Albers and Lambert CRSs suitable for southern African countries and provinces since there are no standard EPSG ones. 

I don't know who the authority would be (Kartoza? QGIS-ZA?) but we'd like to get them in through a similar process that ESRI and other orgs besides the EPSG got theirs in.

**Comment by rouault** [comment]
Did you try to contact EPSG about that ? That would be the preferred path. A number of CRS in EPSG exist for example in Northing-Easting and Easting-Northing order.
