### ISSUE TITLE
Support EPSG:102100 (ESRI legacy) as alias for EPSG:3857

### ISSUE THREAD

**Issue by akrherz** [OSGeo/PROJ#1730]
Feel free to reject this RFE without hurting my feelings :)

Much like how `EPSG:900913` is aliased to `EPSG:3857`, it would be nice if `EPSG:102100` was aliased to `EPSG:3857` as well.  As I review my various WMS/TMS services using Proj, I still see a fair number of ESRI clients out in the wild still using that legacy code.

A couple years back, I attempted to remove `EPSG:102100` from my manually augmented Proj-epsg database and I got downstream users that had no available workaround from ESRI within their mapping apps.  Maybe I should try to pull the bandaid off again and see what breaks :)

At least this issue is documented (hopefully I did not miss this issue elsewhere) here now for reference and thanks for the consideration.

**Comment by rouault** [comment]
ESRI:102100 is recognized properly by PROJ, but not EPSG:102100. We indeed have a hardcoded EPSG:900913 in data/sql/customizations.sql. We could add an entry for EPSG:102100 having the same content as ESRI:102100, but we wouldn't probably want to do that for all ESRI:XXXX codes where XXXX >32767. Not completely opposed to your request, but not sure where we should draw the line (could be argued that upstream users of PROJ could ask PROJ to resolve ESRI:XXXX when they have EPSG:XXXX with XXXX > 32767)

**Comment by kbevers** [comment]
This is probably poking the hornets nest but... does the EPSG terms of use permit us putting an EPSG-identifier on an ESRI-curated CRS? Specifically I am thinking about §6.v11:

> No data that has been modified other than as permitted in these Terms of Use shall be attributed to the EPSG Dataset.

**Comment by rouault** [comment]
> No data that has been modified other than as permitted in these Terms of Use shall be attributed to the EPSG Dataset.

Well, I read this sentence as being about data originating from the EPSG dataset itself (they don't want that EPSG:4326 definition is changed to reflect something else), which is not the case here (there's no EPSG:102100 is EPSG)
