### ISSUE TITLE
Doc: try to clarify info about proj-datumgrid- packages

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#1751]
See https://lists.osgeo.org/pipermail/proj/2019-November/009045.html

**Comment by rouault** [comment]
CC @jmckenna

**Comment by kbevers** [comment]
Clarification on the datumgrid pacakages, for whoever want's to take this documentation task on.

### proj-datumgrid

This is the main grid package and the only one that is required. Includes various older grids that is mostly needed for legacy reasons. Without this grid the test suite fails miserably.

The most recent version is proj-datumgrid-1.8.

### Regional packages

Includes grids from various geodetic authorities within the region specific to the package. The grids mainly cover the geographical extent of the region but there are examples of overseas territories being included in these package, for example grids from IGN in France that both cover mainland France and overseas territories in the Pacific and other places.

Currently we have regional packages for Europe, North-America and Oceania. If someone supplies grids relevant for Africa, South-Americ, Asia or Antarctica we will create new regional packages.

### World package

The world package includes grids that have global extent, e.g. the global geoid model EGM08. 

### -latest packages

All packages above come in different versions, e.g `proj-datumgrid-1.8` or `proj-datumgrid-europe-1.4`. The `-latest` packages are symbolic links to the latest version of a given packages. That means that the link https://download.osgeo.org/proj/proj-datumgrid-north-america-latest.zip is equivalent to https://download.osgeo.org/proj/proj-datumgrid-north-america-1.2.zip (as of the time of writing this).

### What is included in each of the grid packages?

That informations is kept at the proj-datumgrid repositories: https://github.com/OSGeo/proj-datumgrid

For info on the contents of the regional packages the links at the bottom of that page can be followed. 

The packages themselves include README files that describe the contents as well.

**Comment by jmckenna** [comment]
PR #1760 created also related to this ticket.
