### ISSUE TITLE
configure: error: Please install sqlite3 binary.

### ISSUE THREAD

**Issue by powanjuanshu** [OSGeo/PROJ#1767]
my sqlite is static library
./configure ${HOSTCONF} SQLITE3_CFLAGS="-I${PREFIX_ARCH_PATH}/sqlite3/include" SQLITE3_LIBS="-L${PREFIX_ARCH_PATH}/sqlite3/lib -lsqlite3"

report error: 
checking for sqlite3... no
configure: error: Please install sqlite3 binary.

**### **Do you support sqlite3 static library?****

**Comment by rouault** [comment]
> Do you support sqlite3 static library?

yes. But we also need the sqlite3 binary/executable to be in the PATH to "compile" the proj.db database

**Comment by powanjuanshu** [comment]
Because I only want to compile the static library of proj, why do I have to rely on the dynamic library of SQLite？

**Comment by rouault** [comment]
Let me try to rephrase. PROJ needs both a SQLite3 static or dynamic *library* to link to. But for the "make" phase it also needs access to the SQLite3 *executable* to create the proj.db SQLite3 database from .sql text files. After build time, this SQLite3 executable will no longer be needed.

**Comment by powanjuanshu** [comment]
thank you

**Comment by phungxuanvuong** [comment]
> thank you

How can you fix it? 

@rouault  Pls reopen.

**Comment by kbevers** [comment]
There's no need to open a resolved issue

**Comment by Queetinliu** [comment]
please apt-get install libsqlite3-dev

**Comment by iulian0512** [comment]
> please apt-get install libsqlite3-dev

does not fix the issue, 
i have 
libsqlite3-dev is already the newest version (3.31.1-4ubuntu0.2).
when running 
./configure

**Comment by rouault** [comment]
you also need "apt-get install sqlite3"
