### ISSUE TITLE
ISEA inverse transformation 

### ISSUE THREAD

**Issue by am2222** [OSGeo/PROJ#1778]
Hi,
Does ISEA supports inverse transformation? e.g. from ISEA Sequence number to lat/long? 
For example something like this?
`
echo 2358806 | cs2cs +proj=isea +aperture=3 +resolution=12 +orientation=``isea`` +mode=``di`` +to +proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs -f "%.6f"
`

**Comment by kbevers** [comment]
No. Updated docs to be more clear about that in https://github.com/OSGeo/PROJ/commit/9750c044740692f757bfd7c6760f69a8683c330a

**Comment by am2222** [comment]
@kbevers sorry about commenting on a closed issue. Is there any sources to implement its reverse transformation based on that?

**Comment by kbevers** [comment]
> Is there any sources to implement its reverse transformation based on that?

Your best bet is probably to consult the original paper on the projection. My previous update to the docs included the wrong reference to the paper. That is now fixed and the website docs will be updated shortly https://proj.org/operations/projections/isea.html

**Comment by am2222** [comment]
@kbevers Actually I found that paper, seems it is quite straight forward for to inverse from snyder's projection to lat/long) but I am wondering about converting seqnum or q2di to snyder's projection, I could not find anything about that part

p.s: I guess I can not access to the new paper. My university does not cover access to it

**Comment by ppKrauss** [comment]
Hi @kbevers, can you check  this question? https://gis.stackexchange.com/q/418623/7505

... I don't understand how to use ISEA. I am expecting a good area calculations with it, but it does not work well.

**Comment by ppKrauss** [comment]
> Actually I found that paper

Hi @am2222,  can you show here the link or bibliographic record of the paper?
