### ISSUE TITLE
Inconsistent proj string definition for EPSG:4240 across PROJ5 <-> PROJ6

### ISSUE THREAD

**Issue by nirvn** [OSGeo/PROJ#1787]
The dissection of a reported QGIS issue (https://github.com/qgis/QGIS/issues/33121) led to the following finding:

- when QGIS is built against GDAL2/PROJ5, EPSG:4240's proj definition is as follow:
`+proj=longlat +a=6377276.345 +b=6356075.41314024 +towgs84=210,814,289,0,0,0,0 +no_defs`

- when QGIS is built against GDAL3/PROJ6, EPSG:4240's proj definition is as follow:
`+proj=longlat +ellps=evrst30 +towgs84=293,836,318,0.5,1.6,-2.8,2.1 +no_defs`

When reprojecting points from WGS84 to EPGS:4240, those two proj definitions result in different results.

Is there a reason why PROJ 6 is outputting a different proj description (and therefore different reprojection results) than its 5.X predecessor? The end result of this change is that datasets produced by GDAL2/PROJ5 are misprojected under GDAL3/PROJ6.

**Comment by kbevers** [comment]
A bit of `projinfo`'ing shows that PROJ5 is using an older set of transformation parameters than PROJ6 (note the helmert parameters in the last operation in the list):

```
 projinfo -s EPSG:4240 -t EPSG:4326 -o PROJ --show-superseded
Candidate operations found: 3
Note: using '--spatial-test intersects' would bring more results (4)
-------------------------------------
Operation n┬░1:

EPSG:1812, Indian 1975 to WGS 84 (4), 3.0 m, Thailand - onshore

PROJ string:
+proj=pipeline +step +proj=axisswap +order=2,1 +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=push +v_3 +step +proj=cart +ellps=evrst30 +step +proj=helmert +x=293 +y=836 +z=318 +rx=0.5 +ry=1.6 +rz=-2.8 +s=2.1 +convention=position_vector +step +inv +proj=cart +ellps=WGS84 +step +proj=pop +v_3 +step +proj=unitconvert +xy_in=rad +xy_out=deg +step +proj=axisswap +order=2,1

-------------------------------------
Operation n┬░2:

EPSG:1154, Indian 1975 to WGS 84 (1), 5.0 m, Thailand - onshore and Gulf of Thailand

PROJ string:
+proj=pipeline +step +proj=axisswap +order=2,1 +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=push +v_3 +step +proj=cart +ellps=evrst30 +step +proj=helmert +x=209 +y=818 +z=290 +step +inv +proj=cart +ellps=WGS84 +step +proj=pop +v_3 +step +proj=unitconvert +xy_in=rad +xy_out=deg +step +proj=axisswap +order=2,1

-------------------------------------
Operation n┬░3:

EPSG:1304, Indian 1975 to WGS 84 (2), 5.0 m, Thailand - onshore and Gulf of Thailand

PROJ string:
+proj=pipeline +step +proj=axisswap +order=2,1 +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=push +v_3 +step +proj=cart +ellps=evrst30 +step +proj=helmert +x=210 +y=814 +z=289 +step +inv +proj=cart +ellps=WGS84 +step +proj=pop +v_3 +step +proj=unitconvert +xy_in=rad +xy_out=deg +step +proj=axisswap +order=2,1
```

**Comment by nirvn** [comment]
@kbevers , meaning that reprojected data using PROJ < 6 were not as accurate as PROJ 6? In terms of end users, i.e. the average QGIS Joe opening his project file and going 'woaah, my data is misaligned', is there anything that should be done to alleviate this?

BTW, PROJ5 doesn't have a projinfo tool, correct?

**Comment by kbevers** [comment]
> meaning that reprojected data using PROJ < 6 were not as accurate as PROJ 6?

Yes. At least in some cases. And it looks like you've struck one of those. @rouault can maybe go into more detail with this than me.

> In terms of end users, i.e. the average QGIS Joe opening his project file and going 'woaah, my data is misaligned', is there anything that should be done to alleviate this?

They can always fall back on the old transformation. I can't advice on this is a good idea or not, as I am no expert in Indian geodesy. Depending on the use case this can be no big deal or a very big deal.

![epsg4240](https://user-images.githubusercontent.com/13132571/70605130-27b26c80-1bfa-11ea-868c-8639953444a0.PNG)

> BTW, PROJ5 doesn't have a projinfo tool, correct?

Nope. The database that `projinfo` uses was introduced with PROJ 6 as well as the tool.

If you are completely unaware about the changes from PROJ 5 to PROJ 6 I would encourage you to take a look at this great write-up from the Spatialite project: https://www.gaia-gis.it/fossil/libspatialite/wiki?name=PROJ.6

**Comment by nirvn** [comment]
@kbevers , OK. I've tried to select the superseded transform (identifier EPSG:1304), which would indeed be a good solution for our QGIS users, yet picking that transformation still doesn't result in properly aligned data:

![image](https://user-images.githubusercontent.com/1728657/70605833-ce643080-1c2d-11ea-9096-648644516023.png)

**Comment by kbevers** [comment]
I don't know what I am looking at. Please explain.

**Comment by nirvn** [comment]
@kbevers , sorry, I should have pointed at this comment here https://github.com/qgis/QGIS/issues/33121#issuecomment-559706637 to get background details.

Using this QGIS project ( https://github.com/qgis/QGIS/files/3904084/magnolias_waterfront_epsg4240.zip ) , you can see data projected (properly) in QGIS + GDAL2 + PROJ5:
![image](https://user-images.githubusercontent.com/1728657/70606431-07e96b80-1c2f-11ea-93c8-a838585dae60.png)

While under QGIS + GDAL3 + PROJ6, the same pink point appears misprojected:
![image](https://user-images.githubusercontent.com/1728657/70606477-22bbe000-1c2f-11ea-9e37-8046736fd20d.png)

I've tried to open the above-mentioned project and set the transformation to the superseded one you have highlighted in your screenshot, yet the resulting canvas still appears misprojected.

**Comment by kbevers** [comment]
Right... From `projinfo` we get

```
projinfo -s EPSG:4240 -t EPSG:4326 -o PROJ --show-superseded
Candidate operations found: 3
Note: using '--spatial-test intersects' would bring more results (4)
-------------------------------------
Operation n┬░1:

EPSG:1812, Indian 1975 to WGS 84 (4), 3.0 m, Thailand - onshore

PROJ string:
+proj=pipeline +step +proj=axisswap +order=2,1 +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=push +v_3 +step +proj=cart +ellps=evrst30 +step +proj=helmert +x=293 +y=836 +z=318 +rx=0.5 +ry=1.6 +rz=-2.8 +s=2.1 +convention=position_vector +step +inv +proj=cart +ellps=WGS84 +step +proj=pop +v_3 +step +proj=unitconvert +xy_in=rad +xy_out=deg +step +proj=axisswap +order=2,1

...

-------------------------------------
Operation n┬░3:

EPSG:1304, Indian 1975 to WGS 84 (2), 5.0 m, Thailand - onshore and Gulf of Thailand

PROJ string:
+proj=pipeline +step +proj=axisswap +order=2,1 +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=push +v_3 +step +proj=cart +ellps=evrst30 +step +proj=helmert +x=210 +y=814 +z=289 +step +inv +proj=cart +ellps=WGS84 +step +proj=pop +v_3 +step +proj=unitconvert +xy_in=rad +xy_out=deg +step +proj=axisswap +order=2,1
```

Running the same coordinate through both of the transformations shown above gives:

```
echo  13.727615  100.510492 0 0 | cct -d8 +proj=pipeline +step +proj=axisswap +order=2,1 +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=push +v_3 +step +proj=cart +ellps=evrst30 +step +proj=helmert +x=293 +y=836 +z=318 +rx=0.5 +ry=1.6 +rz=-2.8 +s=2.1 +convention=position_vector +step +inv +proj=cart +ellps=WGS84 +step +proj=pop +v_3 +step +proj=unitconvert +xy_in=rad +xy_out=deg +step +proj=axisswap +order=2,1
  13.72974092   100.50554095    0.00000000        0.0000

echo  13.727615  100.510492 0 0 | cct -d8 +proj=pipeline +step +proj=axisswap +order=2,1 +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=push +v_3 +step +proj=cart +ellps=evrst30 +step +proj=helmert +x=210 +y=814 +z=289 +step +inv +proj=cart +ellps=WGS84 +step +proj=pop +v_3 +step +proj=unitconvert +xy_in=rad +xy_out=deg +step +proj=axisswap +order=2,1
  13.72928153   100.50721013    0.00000000        0.0000
```

If we measure the distance between the two points we get
```
echo 13.72974092   100.50554095 13.72928153   100.50721013 | geod -I +ellps=WGS84
105d43'22.686"  -74d16'35.888"  187.555
```

187.555 meters. Which seems to match quite well with the distance from the star in the picture and the place where it ought to be. My guess is that QGIS is not using the deprecated transformation even though the user specified it. I think this points to a bug in QGIS and not PROJ.

**Comment by rouault** [comment]
@nirvn I'd suspect it is a QGIS issue. I do get the same results with PROJ 5 or PROJ 6 if using the superseded "EPSG:1304, Indian 1975 to WGS 84 (2)"

PROJ 6 (in lat lon order):
```
$ echo "7.5 102.5 0" | src/cct -d 10 +proj=pipeline +step +proj=axisswap +order=2,1 +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=push +v_3 +step +proj=cart +ellps=evrst30 +step +proj=helmert +x=210 +y=814 +z=289 +step +inv +proj=cart +ellps=WGS84 +step +proj=pop +v_3 +step +proj=unitconvert +xy_in=rad +xy_out=deg +step +proj=axisswap +order=2,1
 7.5021352004  102.4965461755  0.0000000000           inf
```

PROJ 5 (in lon lat order, ignore the Z value which should not be modified):
```
$ echo "102.5 7.5 0" | ~/proj/install-proj-5.2.0/bin/cs2cs -d 10 +proj=longlat +a=6377276.345 +b=6356075.41314024 +towgs84=210,814,289,0,0,0,0 +no_defs +to +proj=longlat +datum=WGS84
102.4965461755	7.5021352004 -76.9540318595
```

PROJ 6' choice of using by default "EPSG:1812, Indian 1975 to WGS 84 (4), 3.0 m, Thailand - onshore" is completely reasonable. It has the same area of use (in term of BBOX) as others and a highre accuracy. That said, one tricky point is that if you don't enable --show-superseded, "EPSG:1304, Indian 1975 to WGS 84 (2)" is not displayed, although it is not being superseded... The reason is that the filtering algorithm in the non-superseded case is quite aggressive and remove operations that have the same area of use as other operations but a lesser accuracy. In https://github.com/OSGeo/PROJ/blob/d1f432ea6e933cf06ce3ecaedf0e978ed30ec6f6/src/iso19111/coordinateoperation.cpp#L10942 . I've submitted https://github.com/OSGeo/PROJ/pull/1788 to fix that particular point

**Comment by denchat** [comment]
@rouault Would this change also make QGIS obey project's transform settings again?
Because the current behavior is that even though I add the old tranfrom `EPSG:1304` to the project file, there seems nothing happens.

**Comment by rouault** [comment]
> Would this change also make QGIS obey project's transform settings again?

I don't think so. It should just make avoid the user to have to check "Show superseded transformations" to make "EPSG:1304, Indian 1975 to WGS 84 (2)" appear.

**Comment by nirvn** [comment]
@rouault , right, if PROJ6 CLI gets to the same result using the older transformation string then it's indeed likely something needs to be fixed on the QGIS end of things.

**Comment by nirvn** [comment]
It does feel like something might be off with QGIS as whatever transformation is picked (in the full list that includes superseded ones), I get the exact same result on canvas.

**Comment by kbevers** [comment]
I think we can conclude that QGIS is the offender, not PROJ :-) The discussion can continue in https://github.com/qgis/QGIS/issues/33121.

**Comment by nirvn** [comment]
@rouault , are you in a position to confirm that picking the right transformation (which you've confirm leads to correct coordinates) in QGIS doesn't actually result in proper reproduction?

**Comment by rouault** [comment]
> are you in a position to confirm that picking the right transformation (which you've confirm leads to correct coordinates) in QGIS doesn't actually result in proper reproduction?

I let you guys investigate the QGIS side of things

**Comment by nirvn** [comment]
@rouault , for the record, I can see the issue on my machine.

Pinging @nyalldawson for him to read this back n forth. Conversation to continue over QGIS.

**Comment by nyalldawson** [comment]
Passing the ball back to proj with https://github.com/OSGeo/PROJ/issues/1794 :wink:

**Comment by nyalldawson** [comment]
...and accepting responsibility back at QGIS once again :stuck_out_tongue:
