### ISSUE TITLE
List of operations differs when using proj string vs auth:id code

### ISSUE THREAD

**Issue by nyalldawson** [OSGeo/PROJ#1792]
Coming from https://github.com/qgis/QGIS/issues/33323, and I suspect this is a "wontfix" / "cantfix", but:

`projinfo -s EPSG:3352 -t EPSG:32635 --spatial-test intersects` gives 6 candidates

Using the proj definition of EPSG:3352 instead gives only a single candidate:

`projinfo -s "+proj=tmerc +lat_0=0.1 +lon_0=27.95 +k=1 +x_0=2250000 +y_0=0 +ellps=krass +towgs84=23.57,-140.95,-79.8,0,0.35,0.79,-0.22 +units=m +no_defs +type=crs" -t EPSG:32635 `

Can you confirm that using proj strings in this manner makes it impossible to correctly determine the available operations?

**Comment by rouault** [comment]
I'd say that it is not even a bug. PROJ behaves at designed (to paraphrase recent Intel public relationship :-)). But I do mean it here :-)

When using the second invokation with the +towgs84, PROJ strictly honours it as the transformation to go to WGS84 and thus uses WGS84 as the pivot. This is to have backward compatibility for folks using PROJ.4 strings in their workflows.

If you wanted to have the same result as in the first invokation, you could call identify() on the PROJ string to go back to EPSG:3352.

Whether you want identify the PROJ string to EPSG:3352 (and thus not be constrained by its +towgs84 clause) or not will of course depend on the intended use...

**Comment by nyalldawson** [comment]
Perfect, thanks for the confirmation
