### ISSUE TITLE
Can't normalize "EPSG:1304, Indian 1975 to WGS 84 (2)" from proj string

### ISSUE THREAD

**Issue by nyalldawson** [OSGeo/PROJ#1794]
Refs https://github.com/qgis/QGIS/issues/33121

The following code demonstrates a failure to normalize a transform when using the proj string representation of that transform (specifically, "EPSG:1304, Indian 1975 to WGS 84 (2)")

```
  PJ_OPERATION_FACTORY_CONTEXT *operationContext = proj_create_operation_factory_context( nullptr, nullptr );
  proj_operation_factory_context_set_discard_superseded( nullptr, operationContext, false );

  PJ *src = proj_create_from_database( nullptr, "EPSG", "4240", PJ_CATEGORY_CRS, false, nullptr );
  PJ *dest = proj_create_from_database( nullptr, "EPSG", "4326", PJ_CATEGORY_CRS, false, nullptr );
  if ( PJ_OBJ_LIST *ops = proj_create_operations( nullptr, src, dest, operationContext ) )
  {
    int count = proj_list_get_count( ops );
    for ( int i = 0; i < count; ++i )
    {
      PJ *op = proj_list_get( nullptr, ops, i );
      if ( !op )
        continue;

      std::cout << proj_get_name( op );
      std::cout << proj_as_proj_string( nullptr, op, PJ_PROJ_5, nullptr );

      // creating a normalized op directly from the object returned by proj_create_operations works!
      PJ *normalized = proj_normalize_for_visualization( nullptr, op );
      assert( normalized );

      // but if we export the operation as a string, and then create a new operation from that string
      // the normalize call fails...
      PJ *transform2 = proj_create( nullptr, proj_as_proj_string( nullptr, op, PJ_PROJ_5, nullptr ) );
      PJ *normalized2 = proj_normalize_for_visualization( nullptr, transform2 );
      assert( normalized );
    }
    proj_list_destroy( ops );
  }
```

**Comment by rouault** [comment]
> and then create a new operation from that string the normalize call fails...

Yes, that's expected: https://github.com/OSGeo/PROJ/blob/42e981be8e89f7cfbd6f9cd3672c8e80560f61ad/src/iso19111/c_api.cpp#L7675
" coordinate operation, that has been created with  proj_create_crs_to_crs()", and not by proj_create(). The normalization needs to have access to the input and output CRS to have the concept of axis. An object returned by proj_create() is just an expression of a series of mathematic operations. PROJ has no longer any clue of the axis order.

**Comment by kbevers** [comment]
> Yes, that's expected:

Sooo.... passing the ball back to QGIS? :-)

**Comment by nirvn** [comment]
Q   🏀   Ø

**Comment by nyalldawson** [comment]
If that's the case, what API should be used to force proj to use a particular pipeline when converting between two crses?

**Comment by rouault** [comment]
> what API should be used to force proj to use a particular pipeline when converting between two crses?

Normalization should occur just after proj_create_operations(). If you store the PROJ pipeline string after doing normalization, then you don't need to do it again. (But why is QGIS not EPSG axis compliant by default ? just kidding...)

**Comment by nyalldawson** [comment]
> (But why is QGIS not EPSG axis compliant by default ?)

EVERYBODY-- you heard it HERE!! @rouault is volunteering to adapt QGIS to be EPSG axis compliant!! for FREE!!

(but seriously, I'd rather gouge my eyes out with a rusty nail then go down that path...)
