### ISSUE TITLE
Wrapping problem in AEQD ellipsoid code

### ISSUE THREAD

**Issue by pjsg** [OSGeo/PROJ#1798]
When using an ellipsoid, it appears that you can't get further away that 1/4 of the circumference of the earth. If using a sphere, then it works correctly:

```
$ proj +proj=aeqd +lat_0=0 +lon_0=0 +x_0=0 +y_0=0 +a=6371000 +b=6371000 +units=m +no_defs
91 0
10118738.32	0.00
$ proj +proj=aeqd +lat_0=0 +lon_0=0 +x_0=0 +y_0=0 +a=6371000.0001 +b=6371000 +units=m +no_defs
91 0
9896348.47	0.00
```
These two lines are operating on a trivial difference in shapes, and yet the output is extremely different -- because the input point is more than 90 degrees from the central point. 

For the point which is 89 degrees away, there is agreement in the converted locations:

```
$ proj +proj=aeqd +lat_0=0 +lon_0=0 +x_0=0 +y_0=0 +a=6371000 +b=6371000 +units=m +no_defs
89 0
9896348.47	0.00
$ proj +proj=aeqd +lat_0=0 +lon_0=0 +x_0=0 +y_0=0 +a=6371000.0001 +b=6371000 +units=m +no_defs
89 0
9896348.47	0.00
```
You will notice (in the ellipsoid case) that the 91, 0 point maps to the same location at the 89, 0 point.

I found this while exploring a similar set of issues in proj4js -- which also has this bug, and at least one other in aeqd. Related issue: https://github.com/proj4js/proj4js/issues/340

**Comment by QuLogic** [comment]
With what version?
```
$ proj
Rel. 5.2.0, September 15th, 2018
usage: proj [ -bdeEfiIlmorsStTvVwW [args] ] [ +opts[=arg] ] [ files ]
$ proj +proj=aeqd +lat_0=0 +lon_0=0 +x_0=0 +y_0=0 +a=6371000 +b=6371000 +units=m +no_defs
91 0
10118738.32	0.00
$ proj +proj=aeqd +lat_0=0 +lon_0=0 +x_0=0 +y_0=0 +a=6371000.0001 +b=6371000 +units=m +no_defs
91 0
10118738.32	0.00
```

**Comment by pjsg** [comment]
This is my bad -- I was using the version that came with my OS -- and they ship a way old version. I built master, and it works correctly. This is actually good news, as maybe I can port the fix forward to proj4js.
