### ISSUE TITLE
EPSG:3148 (Indian 1960, UTM Zone 48N) missing +towgs84 leading to wrong projection picked when loading shapefiles

### ISSUE THREAD

**Issue by nirvn** [OSGeo/PROJ#1799]
projinfo output for EPSG:3148

```
C:\>projinfo -o PROJ "EPSG:3148"
PROJ.4 string:
+proj=utm +zone=48 +ellps=evrst30 +units=m +no_defs +type=crs

C:\>projinfo -o WKT1_GDAL "EPSG:3148"
WKT1_GDAL:
PROJCS["Indian 1960 / UTM zone 48N",
    GEOGCS["Indian 1960",
        DATUM["Indian_1960",
            SPHEROID["Everest 1830 (1937 Adjustment)",6377276.345,300.8017,
                AUTHORITY["EPSG","7015"]],
            AUTHORITY["EPSG","6131"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4131"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",105],
    PARAMETER["scale_factor",0.9996],
    PARAMETER["false_easting",500000],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["Easting",EAST],
    AXIS["Northing",NORTH],
    AUTHORITY["EPSG","3148"]]
```

There's a `towgs84` parameter missing which was present under proj5 (see https://epsg.io/3148.proj4). 

As a result of the missing +towgs84 parameter, shapefiles using the projection EPSG:3148 are wrongly identified by gdal/QGIS as using the EPSG:24048 projection. The latter is problematic in this case as it won't reproject / transform properly onto WGS84 et cie for Indian 1960, UTM Zone 48N datasets.

Here's a shapefile saved in Indian 1960, UTM Zone 48N:
[ELCs2012.zip](https://github.com/OSGeo/PROJ/files/3966004/ELCs2012.zip)

The content of the .prj file is as follow:

`PROJCS["Indian_1960_UTM_zone_48N",GEOGCS["GCS_Indian 1960",DATUM["D_Indian_1960",SPHEROID["Everest_Adjustment_1937",6377276.345,300.8017]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",105],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["Meter",1]]`

**Comment by nirvn** [comment]
Note: I've used epsg.io to link to the 'proper' proj string as the official EPSG repository a/ doesn't feature a proj representation, and b/ doesn't show any TOWGS84 for neither the Indian 1960 nor the Indian 1975 projections:

- Indian 1960, UTM Zone 48N (http://www.epsg-registry.org/export.htm?wkt=urn:ogc:def:crs:EPSG::3148) 
- Indian 1975, UTM Zone 48N (http://www.epsg-registry.org/export.htm?wkt=urn:ogc:def:crs:EPSG::24048)

**Comment by nirvn** [comment]
For the sake of the discussion here, we might as well throw in Indian 1954 48N: http://www.epsg-registry.org/export.htm?wkt=urn:ogc:def:crs:EPSG::23948

All three projections have identical EPSG WKTs other than their PROJCRS and BASEGEODCRS names. PROJ (and/or GDAL?) should take those bits into account when reading shapefiles.

Additionally, each projection differs in how the coordinates are reprojected onto WGS84:
- Indian 1954: +towgs84=217,823,299,0,0,0,
- Indian 1960: +towgs84=198,881,317,0,0,0,0
- Indian 1975:  +towgs84=210,814,289,0,0,0,0

Under PROJ6, only Indian 1954 and Indian 1975 have TOWGS84 params attached, while Indian 1960 is missing the TOWGS84. All three should show this param.

**Comment by rouault** [comment]
TOWGS84 are not part of the CRS definition. This was an abuse of the 'early binding' definition, that we have kept in projinfo, in case where there was no ambiguity, when exporting to WKT1, but this is really an odd practice. TOWGS84 parameters were more or less randomly selected among one of the potential transformations to WGS84. You will never see TOWGS84 in epsg-registry.org exports.

With the PRJ you give, I get correct identification to EPSG:3148
```
$ projinfo --identify 'PROJCS["Indian_1960_UTM_zone_48N",GEOGCS["GCS_Indian 1960",DATUM["D_Indian_1960",SPHEROID["Everest_Adjustment_1937",6377276.345,300.8017]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",105],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["Meter",1]]' 
[...]
Identification match count: 1
EPSG:3148: 90 %
```
That said the OGR shapefile driver was perhaps too picky and only accepted 100% confidence. I've lowered this to 90%

**Comment by nirvn** [comment]
@rouault , OK, great to see the shapefile driver's been adjusted, good. 

This leaves #1801 to look into to figure out how to distinguish those projections via proj string.
