### ISSUE TITLE
Identification of EPSG from a proj string fails for Indian 1960, UTM Zone 48N

### ISSUE THREAD

**Issue by nirvn** [OSGeo/PROJ#1801]
When typing:

```
C:\>projinfo --identify "+proj=utm +zone=48 +a=6377276.345 +b=6356075.41314024 +towgs84=198,881,317,0,0,0,0 +units=m +no_defs +type=crs"
PROJ string:
+proj=utm +zone=48 +a=6377276.345 +b=6356075.41314024 +towgs84=210,814,289,0,0,0
,0 +units=m +no_defs
```

PROJ returns three matches, with the exact same match percentage:

```
Identification match count: 3
BoundCRS of EPSG:23948: 70 %
BoundCRS of EPSG:3148: 70 %
BoundCRS of EPSG:24048: 70 %
```

Those three EPSGs should *not* be equally matching, and the highest percentage should be EPSG:3148 (which is the code for the above-pasted proj string).

As mentioned in issue #1799 , those three EPSGs have identical parameters, other than their names (which isn't available in the proj string) and its +towgs84 parameter:

- Indian 1954: +towgs84=217,823,299,0,0,0,
- Indian 1960: +towgs84=198,881,317,0,0,0,0
- Indian 1975:  +towgs84=210,814,289,0,0,0,0

When identifying EPSG matches, PROJ should consider the towgs84 value and give EPSGs with matching transformations a greater weight / percentage.

**Comment by nirvn** [comment]
A bit more on this. 

PROJ "rightfully" adds the distinguishing TOWGS84 parameter to EPSG:23948 and EPSG:24048 but does not do so for EPSG:3418. Whatever is done for 23948 and 24048 should be applied / appended to 3148. See outputs below.

**EPSG:23948**
```
C:\>projinfo -o WKT1_GDAL "EPSG:23948"
WKT1_GDAL:
PROJCS["Indian 1954 / UTM zone 48N",
    GEOGCS["Indian 1954",
        DATUM["Indian_1954",
            SPHEROID["Everest 1830 (1937 Adjustment)",6377276.345,300.8017,
                AUTHORITY["EPSG","7015"]],
            TOWGS84[217,823,299,0,0,0,0],
            AUTHORITY["EPSG","6239"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4239"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",105],
    PARAMETER["scale_factor",0.9996],
    PARAMETER["false_easting",500000],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["Easting",EAST],
    AXIS["Northing",NORTH],
    AUTHORITY["EPSG","23948"]]
```

**EPSG:3148**
```
C:\>projinfo -o WKT1_GDAL "EPSG:3148"
WKT1_GDAL:
PROJCS["Indian 1960 / UTM zone 48N",
    GEOGCS["Indian 1960",
        DATUM["Indian_1960",
            SPHEROID["Everest 1830 (1937 Adjustment)",6377276.345,300.8017,
                AUTHORITY["EPSG","7015"]],
            AUTHORITY["EPSG","6131"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4131"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",105],
    PARAMETER["scale_factor",0.9996],
    PARAMETER["false_easting",500000],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["Easting",EAST],
    AXIS["Northing",NORTH],
    AUTHORITY["EPSG","3148"]]
```

**EPSG:24048**
```
C:\>projinfo -o WKT1_GDAL "EPSG:24048"
WKT1_GDAL:
PROJCS["Indian 1975 / UTM zone 48N",
    GEOGCS["Indian 1975",
        DATUM["Indian_1975",
            SPHEROID["Everest 1830 (1937 Adjustment)",6377276.345,300.8017,
                AUTHORITY["EPSG","7015"]],
            TOWGS84[293,836,318,0.5,1.6,-2.8,2.1],
            AUTHORITY["EPSG","6240"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4240"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",105],
    PARAMETER["scale_factor",0.9996],
    PARAMETER["false_easting",500000],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["Easting",EAST],
    AXIS["Northing",NORTH],
    AUTHORITY["EPSG","24048"]]
```

**Comment by nirvn** [comment]
To avoid coming up with the same match%, one could possibly look at the transformation to see matching WGS84 parameters.

For e.g., EPSG:3148's TOWGS84 values are `198,881,317,0,0,0,0` ; this happens to essentially match the default transformation suggested by PROJ6:

```
Inverse of Popular Visualisation Pseudo-Mercator + Inverse of Indian 1960 to WGS 84 (2) + UTM zone 48N
Scope: For military purposes. Accuracy 25m in each axis.
Remarks: Derived at 2 stations.
Area of use: World, Vietnam - 14°N to 18°N onshore, World - N hemisphere - 102°E to 108°E
Identifiers: INVERSE(EPSG):3856, INVERSE(EPSG):1542, EPSG:16048
+proj=pipeline +step +inv +proj=webmerc +lat_0=0 +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +step +proj=push +v_3 +step +proj=cart +ellps=WGS84 +step +proj=helmert +x=-198 +y=-881 +z=-317 +step +inv +proj=cart +ellps=evrst30 +step +proj=pop +v_3 +step +proj=utm +zone=48 +ellps=evrst30
```
_(i.e. the +proj=helmert +x=-198 +y=-881 +z=-317 bit)_

**Comment by rouault** [comment]
> Whatever is done for 23948 and 24048 should be applied / appended to 3148

No... For EPSG:23948 and EPSG:24048, there is at least one transformation to EPSG:4326 that is valid for their whole area of use, hence it is select. In the case of EPSG:3148, the potential transformations only intersect the area of use. Selecting 198,881,317,0,0,0,0 would be arbitrary

**Comment by nirvn** [comment]
@rouault , but these areas of use are "arbitrary" in nature right? The transformation I'm pointing out above matching the towgs84 values has a very small (and wrong) area of use defined, but in fact work (and has been used for decades) across the whole EPSG:3148 area.

**Comment by nirvn** [comment]
Actually just to make sure we're both on the same page, this issue is two fold.

The more serious issue is the equal match% (ie 70%) of three EPGSs against the above pasted proj string. There I think we should use the +towgs84 parameter to see if there's a matching transformation. If there is one, add 5% or so. It'd make matching of EPSG that much more accurate.

A secondary, cosmetic issue is the absence of the TOWGS84 parameter when exploring the WKT string. That's not a serious, and would merely (?) require the transformation area statement to be changed to reflect actual on the ground usage. Is the an authority responsible for setting these area extents that can make revisions?

**Comment by rouault** [comment]
> The more serious issue is the equal match% (ie 70%) of three EPGSs against the above pasted proj string

Almost fixed. When there are match(es) that have one of their transformation(s) to towgs84 that matches the input one, then only those ones will be returned. Pull request coming soon.

> would merely (?) require the transformation area statement to be changed to reflect actual on the ground usage. Is the an authority responsible for setting these area extents that can make revisions?

The thing is that EPSG:3148 area of use is [Asia - Cambodia and Vietnam - west of 108°E], but transformation EPSG:1542 using +towgs84=198,881,317,0,0,0,0 is only for [Vietnam - 14°N to 18°N onshore], so in theory it doesn't apply to Cambodia, hence PROJ doesn't automatically select it. The details on the operation are in https://www.epsg-registry.org/export.htm?gml=urn:ogc:def:coordinateOperation:EPSG::1542. Information source is "U.S. Defense Mapping Agency TR8350.2 revision of August 1993." You'd have to convince either them or EPSG that it applies to the whole are of use of EPSG:3148...
