### ISSUE TITLE
Incorrect identification of EPSG:4326 WKT with TOWGS84[0,0,0,0,0,0,0]

### ISSUE THREAD

**Issue by nyalldawson** [OSGeo/PROJ#1804]
Ok, it's rather a corner case, but identifying the WKT:

    GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],TOWGS84[0,0,0,0,0,0,0],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["DMSH",0.0174532925199433,AUTHORITY["EPSG","9108"]],AXIS["Lat",NORTH],AXIS["Long",EAST],AUTHORITY["EPSG","4326"]]

reports the match `BoundCRS of EPSG:4326: 100 %`

This really should be just direct match for EPSG:4326 and not a BoundCRS match, since the no-op transform "Transformation from WGS 84 to WGS84" doesn't actually have any meaning at all...

**Comment by rouault** [comment]
yeah, that's more an artefact of the interface. As a WKT1 GEOGCS[] with a TOWGS84[] is mapped to a  BoundCRS object, then identification of a BoundCRS result in one or more candidate BoundCRS. I don't think I want to change this at the PROJ level

**Comment by nyalldawson** [comment]
I'm taking a new zero-downstream-handling approach in QGIS :wink -- that means this WKT will be interpreted as a custom CRS and not as EPSG:4326. Do you foresee any issue there?

**Comment by rouault** [comment]
> Do you foresee any issue there?

Probably not... WGS84 with or without a null TOWGS84 is pretty much the same thing :-)
