### ISSUE TITLE
Add True View Projection

### ISSUE THREAD

**Issue by loixou** [OSGeo/PROJ#1806]
In some fields, it is important to see the earth from a satellite point of view, keeping the value of angles. This is called the True View Angle (theta x, theta y), and there is a link between these coordinates and ECEF coordinates. 

Would it be easy to implement this new projection if we get the mathematical projection from (theta xy to ECEF and the opposite) by a new guy like me (inspiration from the geos.cpp file ?)? By an experimented person ?

Note: in that type of coordinates, we can define something out of the field of view of the satellite.
PS: I can give the formulas if someone wants/can develop the cpp projection

**Comment by kbevers** [comment]
> Would it be easy to implement this new projection if we get the mathematical projection from (theta xy to ECEF and the opposite) by a new guy like me (inspiration from the geos.cpp file ?)?

Hard to tell without a reference for the projection in question. If your are fairly skilled in C\C++ it shouldn't be too hard I reckon. [Here](https://github.com/OSGeo/PROJ/pull/1391/) can get a feel for what sort of changes are necessary when adding a new projection.

> PS: I can give the formulas if someone wants/can develop the cpp projection

Just a word of caution, expect to put money on the table if you want someone else to do the work for you.
