### ISSUE TITLE
Support creating coordinate system from WKT string?

### ISSUE THREAD

**Issue by snowman2** [OSGeo/PROJ#1819]
Currently when attempting to create a coordinate system `PJ*` object from a WKT using `proj_create()`, I see this error:

Input string: 
```
CS[ellipsoidal,2],AXIS["geodetic latitude (Lat)",north,ORDER[1],ANGLEUNIT["degree",0.0174532925199433,ID["EPSG",9122]]],AXIS["geodetic longitude (Lon)",east,ORDER[2],ANGLEUNIT["degree",0.0174532925199433,ID["EPSG",9122]]]
```
Error:
```
proj_create: unhandled keyword: CS
```

Is there any desire to support creating a coordinate system `PJ*` using a WKT string in PROJ?

**Comment by rouault** [comment]
I don't think that's easily possible, nor there is a strong interest for that. For backward compatibility reasons, WKT2 has chosen a odd WKT construct for CS[] where the children of CS are at the same level of it, which would break assumptions in the main WKT parser

**Comment by snowman2** [comment]
That makes sense why it doesn't work currently. With PROJ JSON support it isn't entirely necessary to have it.
