### ISSUE TITLE
Creating datum using 'proj_create_from_name' strange behavior with 'WGS84' string. 

### ISSUE THREAD

**Issue by snowman2** [OSGeo/PROJ#1823]
Here is the pseudo code using the PROJ API used to create the datum from a name:
```
        PJ_OBJ_LIST *pj_list = proj_create_from_name(
            context,
            "EPSG",
            name_string,
            PJ_TYPE_GEODETIC_REFERENCE_FRAME
            1,
            1,
            1,
            NULL,
        )
        PJ* datum_pj = proj_list_get(context, pj_list, 0)
```

Here is the unexpected results:
```python
>>> from pyproj.crs import Datum
>>> dd = Datum.from_name("World Geodetic System 1984")
>>> dd
DATUM["World Geodetic System 1984",
    ELLIPSOID["WGS 84",6378137,298.257223563,
        LENGTHUNIT["metre",1]],
    ID["EPSG",6326]]
>>> dd = Datum.from_name("WGS84")
>>> dd
DATUM["Not specified (based on WGS 84 ellipsoid)",
    ELLIPSOID["WGS 84",6378137,298.257223563,
        LENGTHUNIT["metre",1]],
    ID["EPSG",6030]]
```

For some reason, `WGS84` and `World Geodetic System 1984` produce different results when creating a datum. I would expect both to produce the same results, however that is not the case. I tried listing all possible results with `WGS 84` when creating a datum, but this was the only one returned. Any ideas why this happens?

**Comment by snowman2** [comment]
Same for this one:
```python
>>> Datum.from_name("NAD83")
DATUM["NAD83 (Federal Base Network)",
    ELLIPSOID["GRS 1980",6378137,298.257222101,
        LENGTHUNIT["metre",1]],
    ID["EPSG",1211]]
>>> Datum.from_name("North American Datum 1983")
DATUM["North American Datum 1983",
    ELLIPSOID["GRS 1980",6378137,298.257222101,
        LENGTHUNIT["metre",1]],
    ID["EPSG",6269]]
>>> Datum.from_name("North American Datum of 1983")
DATUM["North American Datum of 1983 (CSRS96)",
    ELLIPSOID["GRS 1980",6378137,298.257222101,
        LENGTHUNIT["metre",1]],
    ID["EPSG",1192]]
```

**Comment by snowman2** [comment]
It would be nice if the `proj_create_from_name` defaulted to the ones used when creating a datum with the old PROJ string with `+datum=`.

For example:
```python
>>> cc = CRS("+proj=utm +zone=11N +datum=NAD83")
>>> cc.datum.name
'North American Datum 1983'
>>> cc = CRS("+proj=utm +zone=11N +datum=WGS84")
>>> cc.datum.name
'World Geodetic System 1984'
```
Thoughts?

**Comment by rouault** [comment]
> It would be nice if the `proj_create_from_name` defaulted to the ones used when creating a datum with the old PROJ string with `+datum=`.

No !!! :-) Those are PROJ.4 specific, whereas the ones passed to and returned by proj_create_from_name() are the ones official for the authority (here EPSG)

That said EPSG has a alias table, where for example "WGS 84" is registered as an official alias for datum EPSG:6326 "World Geodetic System 1984". We should probably try to query in it too. Currently when looking only in the datum table, there's no way that looking for "WGS84" can identify a row that contains  "World Geodetic System 1984" (at least not without a 10-layer neural network :-))

**Comment by snowman2** [comment]
Okay, the alias table sounds useful 👍. My thinking for adding this would be to help the PROJ users migrate away from PROJ strings and still have a way to build a custom CRS with a simple/familiar interface. I added an alias map to pyproj for backwards compatibility. https://github.com/pyproj4/pyproj/commit/25a894008e4e1bc4785b4f4f67d89f79391fe04b

**Comment by snowman2** [comment]
Thoughts on adding the aliases to the `+datum=` options to the PROJ authority?

**Comment by rouault** [comment]
> Thoughts on adding the aliases to the `+datum=` options to the PROJ authority?

Done per https://github.com/OSGeo/PROJ/pull/1827/commits/206a45de20b4936efa0e216fce6addd768881508

**Comment by snowman2** [comment]
Perfect, thanks!
