### ISSUE TITLE
DEGREE SIGN character in projinfo output is incorrectly displayed on MS Windows console

### ISSUE THREAD

**Issue by agiudiceandrea** [OSGeo/PROJ#1828]
On MS Windows 7 64 bit localized in Italian, the output of **projinfo** (6.2.1) tool can contain the **DEGREE SIGN** character (`U+00B0 | ° | \xc2\xb0`) that is incorrectly displayed in the command prompt console, e.g. the OSGeo4W Shell:

![image](https://user-images.githubusercontent.com/16253859/71884440-a8e91a80-3138-11ea-96a8-88947c10cae8.png)

The default console codepage is 850 | ibm850 | OEM Multilingual Latin 1; Western European (DOS)

Is it possible to properly encode/decode the DEGREE SIGN character in the string "Operation n°" or to  avoid the use of such character (e.g. using "Operation n.")?
I would also add a space at the end of the string to separate it from the number that follows.

The problem also occurs changing the codepage to 65001 | utf-8 | Unicode (UTF-8) when the font used in the shell is non TrueType (the default font is Raster type).

https://github.com/OSGeo/PROJ/blob/529eb50f5d7e817dd27674984050a9bf1a6dce55/src/apps/projinfo.cpp#L689-L692

**Comment by mwtoews** [comment]
There are many ways to represent this symbol, see https://en.wikipedia.org/wiki/Numero_sign

Normally in English, it's just the two ASCII characters, with an optional fullstop: No.

**Comment by kbevers** [comment]
Going with a plain ASCII representation like "No." would be the simplest fix to this. I have been annoyed by this as well when using projinfo on Windows.
