### ISSUE TITLE
Could PROJ add a new map projection  "Hao vertical projection"?

### ISSUE THREAD

**Issue by yangleir** [OSGeo/PROJ#1845]
**Description of proposed changes**
An Chinese scientist  invented a interesting map projection named vertical map projection which give us a new view of the world. See his [sites](http://www.hxgmap.com/),but in Chinese.  The author's last name is Hao, so I call it "Hao vertical projection" temporary.

For vertical projection the earth surface is slit on the E-W direction and projected to flat surface. Here is figure to show the different between traditional map projection and the vertical one.
![切](https://user-images.githubusercontent.com/9152905/71878805-89b5b180-3167-11ea-908a-54d95a315d70.jpg)

In addition to the fun perspective, the vertical map could be used in polar science because its deformation at polar area is small. It can put the arctic and antarctic into one map with small deformation over polar area. So I think this map projection is both interesting and useful for science. 

Could the PROJ add this kind of map projection? 

Here is the map.
![1106south](https://user-images.githubusercontent.com/9152905/71878367-6f2f0880-3166-11ea-87db-bc5e87dc282b.jpg)

**Comment by kbevers** [comment]
> Could the PROJ add this kind of map projection?

If the projection is well-documented in a scientific paper (or similar) and has suitable test material to confirm the implementation against, sure it could be interesting. Please note though, this isn't happening by itself, you will ned to do the implementatoin yourself or hire someone who can do it on your behalf.

Please update the title of this issue to something less generic than "add a map projection". I suggest putting in the name of the projection as a good starting point :-)

**Comment by yangleir** [comment]
Hi @kbevers , I will writing to the inventor of the map projection for scientific paper and related material. Thanks for your advise.

**Comment by yangleir** [comment]
I temporary close this issue. It will be open again until I get sufficient information of the projection or there is someone who is willing to do the job with his own knowledge.
