### ISSUE TITLE
Set fixed value for (height) coordinate

### ISSUE THREAD

**Issue by Jochem-L** [OSGeo/PROJ#1846]
The official transformation between ETRS89 and Dutch national RD coordinates with NAP height requires a fixed height in the Helmert transformation step for the horizontal RD coordinates and the real height for the vertical NAP coordinates (see official RDNAPTRANS™2018 documentation at [https://www.nsgi.nl/](https://www.nsgi.nl/)). This is not possible with the available options in cct like `-z 43` or `+proj=push` and `+proj=pop`. Currently, a workaround is used that misuses the time to store a second height value (see code below). However, to transform between ITRS and RD&NAP, also a value for the time will be needed and the workaround can't be used. 

Therefore a new feature is requested to set a fixed height. This could be something like:
`+proj=pop +v_3=43`
or
`+proj=set +v_3=43`

__
Current workaround command:
```
cct -t 0 -d 4 +proj=pipeline
+step +proj=unitconvert +xy_in=deg +xy_out=rad
+step +proj=axisswap +order=2,1,3,4
+step +proj=vgridshift +grids=nlgeo2018.gtx
+step +proj=push +v_3 +v_4
+step +proj=axisswap +order=1,2,4,-3
+step +proj=geogoffset +dh=43
+step +proj=cart +ellps=GRS80
+step +proj=helmert +x=-565.7346 +y=-50.4058 +z=-465.2895 +rx=-0.395023 +ry=0.330776 +rz=-1.876073 +s=-4.07242 +convention=coordinate_frame +exact
+step +proj=cart +inv +ellps=bessel
+step +proj=hgridshift +inv +grids=rdcorr2018.gsb,null
+step +proj=sterea +lat_0=52.156160556 +lon_0=5.387638889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel
+step +proj=pop +v_3 +v_4
```
__
Command with preferred new feature:
```
cct -t 0 -d 4 +proj=pipeline
+step +proj=unitconvert +xy_in=deg +xy_out=rad
+step +proj=axisswap +order=2,1,3,4
+step +proj=vgridshift +grids=nlgeo2018.gtx
+step +proj=push +v_3
+step +proj=set v_3=43
+step +proj=cart +ellps=GRS80
+step +proj=helmert +x=-565.7346 +y=-50.4058 +z=-465.2895 +rx=-0.395023 +ry=0.330776 +rz=-1.876073 +s=-4.07242 +convention=coordinate_frame +exact
+step +proj=cart +inv +ellps=bessel
+step +proj=hgridshift +inv +grids=rdcorr2018.gsb,null
+step +proj=sterea +lat_0=52.156160556 +lon_0=5.387638889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel
+step +proj=pop +v_3
```

**Comment by kbevers** [comment]
This is indeed a good suggestion. I think the `set` moniker is fine - it says what it does!

I will happily accept a pull request that implements this. https://github.com/OSGeo/PROJ/pull/1250/files is a good starting point if a template is needed.

Kudos on the work-around. I like the ingenuity involved to make that happen :)

**Comment by Jochem-L** [comment]
Thanks for de kudos. It took us quite some time. In the previous publication it was even more complicated, as I didn't use `push` and `pop`, nor `geogoffset` and I had to misuse also `unitconvert ` and the EGM geoid: 

Previous workaround command:
```
cct -t 0 -d 4 +proj=pipeline 
+step +proj=axisswap +order=2,1,3,4 
+step +proj=vgridshift +grids=nlgeo2018.gtx 
+step +proj=axisswap +order=1,2,4,-3 
+step +proj=vgridshift +inv +grids=egm96_15.gtx 
+step +proj=cart +ellps=GRS80 
+step +proj=helmert +x=-565.7346 +y=-50.4058 +z=-465.2895 +rx=-0.395023 +ry=0.330776 +rz=-1.876073 +s=-4.07242 +convention=coordinate_frame +exact 
+step +proj=cart +inv +ellps=bessel 
+step +proj=hgridshift +inv +grids=rdcorr2018.gsb,null 
+step +proj=sterea +lat_0=52.156160556 +lon_0=5.387638889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel 
+step +proj=unitconvert +z_in=m +z_out=1e32 
+step +proj=axisswap +order=1,2,-4,-3
```

**Comment by rouault** [comment]
I would imagine that the semantics of +proj=set would be by default to be applied in both forward and reverse cases ? (unless a +omit_fwd / +omit_inv is added)
Mostly for my education: is your pipeline supposed to be used also in the reverse case ? If so, that would mean that the helmet transformation in the reverse case would be taken with a  Z value being a NAP height

**Comment by Jochem-L** [comment]
**On feature request**
If an inverse of `+proj=set` is to be defined, the only option I see is to set the coordinate to the same value as in the forward case. For a case like the Dutch transformation, the reverse transformation can't be obtained by simply inverting the individual steps. So, no inverse of `+proj=set` is needed in this case. Instead a different pipeline is used for the reverse (from RD with NAP height to ETRS89) transformation (see code below). 

**On Dutch transformation**
From RD with NAP height to ETRS89, the used ellipsoidal height for the Helmert transformation is not the NAP height, but the height is set to 0 m. This is an unconventional trick to get the same results as when the effect of the Helmert transformation is included in the horizontal NTv2 grid. For the forward transformation from ETRS89 to RD with NAP height, we need to set the ellipsoidal ETRS89 height for the Helmert transformation to the equivalent of 0 m NAP. This is 43 m for the centre of the Netherlands and this value can be used as an approximation elsewhere (the effect of this approximation is below 1 mm for the horizontal coordinates, in an area up to hundreds of km outside the Netherlands).

Thanks for pointing to `+omit_fwd` and `+omit_inv`. We will look if this can be used to define a single pipeline that can be used in both transformation directions.

__
Current workaround inverse command:
```
cct -t 0 -d 9 +proj=pipeline
+step +proj=sterea +inv +lat_0=52.156160556 +lon_0=5.387638889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel
+step +proj=push +v_3 +v_4
+step +proj=axisswap +order=1,2,4,3
+step +proj=hgridshift +grids=rdcorr2018.gsb,null
+step +proj=cart +ellps=bessel
+step +proj=helmert +inv +x=-565.7346 +y=-50.4058 +z=-465.2895 +rx=-0.395023 +ry=0.330776 +rz=-1.876073 +s=-4.07242 +convention=coordinate_frame +exact
+step +proj=cart +inv +ellps=GRS80
+step +proj=pop +v_3 +v_4
+step +proj=vgridshift +inv +grids=nlgeo2018.gtx
+step +proj=axisswap +order=2,1,3,4
+step +proj=unitconvert +xy_in=rad +xy_out=deg
```

__
Inverse command with preferred new feature:
```
cct -t 0 -d 9 +proj=pipeline
+step +proj=sterea +inv +lat_0=52.156160556 +lon_0=5.387638889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel
+step +proj=push +v_3
+step +proj=set +v_3=0
+step +proj=hgridshift +grids=rdcorr2018.gsb,null
+step +proj=cart +ellps=bessel
+step +proj=helmert +inv +x=-565.7346 +y=-50.4058 +z=-465.2895 +rx=-0.395023 +ry=0.330776 +rz=-1.876073 +s=-4.07242 +convention=coordinate_frame +exact
+step +proj=cart +inv +ellps=GRS80
+step +proj=pop +v_3
+step +proj=vgridshift +inv +grids=nlgeo2018.gtx
+step +proj=axisswap +order=2,1,3,4
+step +proj=unitconvert +xy_in=rad +xy_out=deg
```

**Comment by rouault** [comment]
It looks to me that the following pipeline, which is the preferred one of your initial comment https://github.com/OSGeo/PROJ/issues/1846#issue-549573538, with an added +step +proj=set +v_3=0 could be used for the reverse path:
```
cct -t 0 -d 4 +proj=pipeline
+step +proj=unitconvert +xy_in=deg +xy_out=rad
+step +proj=axisswap +order=2,1,3,4
+step +proj=vgridshift +grids=nlgeo2018.gtx
+step +proj=push +v_3
+step +proj=set v_3=43
+step +proj=cart +ellps=GRS80
+step +proj=helmert +x=-565.7346 +y=-50.4058 +z=-465.2895 +rx=-0.395023 +ry=0.330776 +rz=-1.876073 +s=-4.07242 +convention=coordinate_frame +exact
+step +proj=cart +inv +ellps=bessel
+step +proj=hgridshift +inv +grids=rdcorr2018.gsb,null
+step +proj=sterea +lat_0=52.156160556 +lon_0=5.387638889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel
+step +proj=set +v_3=0
+step +proj=pop +v_3
```

**Comment by hdeligt** [comment]
It looks like that should indeed work; very nice! It will allow us (I'm Jochem's colleague) to use t for what it is intended.

For 6.3.0 the following adaptation of the workaround from the original post works in both directions using omit_inv/omit_fwd. Depending on your requirements, you need to use a different value for d when using -I.

```
cct -t 0 -d 4 +proj=pipeline
+step +proj=unitconvert +xy_in=deg +xy_out=rad
+step +proj=axisswap +order=2,1,3,4
+step +proj=vgridshift +grids=nlgeo2018.gtx
+step +proj=push +v_3 +v_4
+step +proj=axisswap +order=1,2,4,-3 +omit_inv
+step +proj=geogoffset +dh=43 +omit_inv
+step +proj=cart +ellps=GRS80
+step +proj=helmert +x=-565.7346 +y=-50.4058 +z=-465.2895 +rx=-0.395023 +ry=0.330776 +rz=-1.876073 +s=-4.07242 +convention=coordinate_frame +exact
+step +proj=cart +inv +ellps=bessel
+step +proj=hgridshift +inv +grids=rdcorr2018.gsb,null
+step +proj=sterea +lat_0=52.156160556 +lon_0=5.387638889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel
+step +proj=axisswap +order=1,2,4,-3 +omit_fwd
+step +proj=pop +v_3 +v_4
```
