### ISSUE TITLE
Can't install from source proj4 6.3.0

### ISSUE THREAD

**Issue by cmodomingo** [OSGeo/PROJ#1847]
I'm having this bellow error while doing Make.

iso19111/internal.cpp:48:21: fatal error: sqlite3.h: No such file or directory
 #include "sqlite3.h"

Steps that I took before I came accross the error above:

export SQLITE3_LIBS=/pgsql/g01/software/rdbms/10.11.0/lib
export SQLITE3_CFLAGS=/pgsql/g01/software/rdbms/10.11.0/include
./configure --prefix=/pgsql/g01/software/rdbms/10.11.0

SQLITE3 exists:
ls -laht /pgsql/g01/software/rdbms/10.11.0/include/sqlite3*
-rw-r--r--. 1 pgsql dba  34K Jan 13 23:45 /pgsql/g01/software/rdbms/10.11.0/include/sqlite3ext.h
-rw-r--r--. 1 pgsql dba 552K Jan 13 23:45 /pgsql/g01/software/rdbms/10.11.0/include/sqlite3.h

My Environment Variable:
SHELL=/bin/bash
TERM=xterm
HISTSIZE=1000
OLDPWD=/pgsql/g01/software/stage
USER=pgsql
SQLITE3_CFLAGS=/pgsql/g01/software/rdbms/10.11.0/include
LD_LIBRARY_PATH=/pgsql/g01/software/rdbms/10.11.0/lib:/oracle/g01/software/client/11.2.0.4/lib:/usr/lib:/lib:/lib64:/usr/lib64
PGPORT=5432
MAIL=/var/spool/mail/pgsql
PATH=/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/pgsql/.local/bin:/home/pgsql/bin:/sbin:/home/pgsql/bin:/pgsql/g01/software/rdbms/10.11.0/bin
PWD=/pgsql/g01/software/stage/proj-6.3.0
LANG=en_US.UTF-8
PGSID=pg10.11
SQLITE3_LIBS=/pgsql/g01/software/rdbms/10.11.0/lib
PGHOME=/pgsql/g01/software/rdbms/10.11.0
SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass
HISTCONTROL=ignoredups
BACKUP_PATH=/pgsql/g01/bkup01/physical
SHLVL=1
HOME=/home/pgsql
LOGNAME=pgsql
CVS_RSH=ssh
PGDATA=/pgsql/g01/db01/pg10.11
LESSOPEN=||/usr/bin/lesspipe.sh %s
ORACLE_HOME=/oracle/g01/software/client/11.2.0.4
_=/bin/printenv

Thank you in advance

**Comment by rouault** [comment]
> export SQLITE3_CFLAGS=/pgsql/g01/software/rdbms/10.11.0/include

You should add `-I` just after the equal sign

**Comment by cmodomingo** [comment]
Hi Rouault,

Thank you for your quick response. After adding -I right after the equal sign it looks like it passed the error that I previously encounter but now i'm presented with this error during make.


/bin/sh ../libtool  --tag=CXX   --mode=link g++ -std=c++11 -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wlogical-op -Wshadow -Werror=vla -Wmissing-declarations -Wnon-virtual-dtor  -Woverloaded-virtual -Wdeprecated -Wzero-as-null-pointer-constant  -g -O2 -fvisibility=hidden   -o proj apps/proj.o apps/emess.o apps/utils.o libproj.la -lpthread -lm
libtool: link: g++ -std=c++11 -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wlogical-op -Wshadow -Werror=vla -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -Wdeprecated -Wzero-as-null-pointer-constant -g -O2 -fvisibility=hidden -o .libs/proj apps/proj.o apps/emess.o apps/utils.o  ./.libs/libproj.so -lpthread -lm -Wl,-rpath -Wl,/pgsql/g01/software/rdbms/10.11.0/lib
./.libs/libproj.so: undefined reference to `sqlite3_column_text'
./.libs/libproj.so: undefined reference to `sqlite3_close'
./.libs/libproj.so: undefined reference to `sqlite3_reset'
./.libs/libproj.so: undefined reference to `sqlite3_result_double'
./.libs/libproj.so: undefined reference to `sqlite3_open_v2'
./.libs/libproj.so: undefined reference to `sqlite3_vfs_register'
./.libs/libproj.so: undefined reference to `sqlite3_result_int'
./.libs/libproj.so: undefined reference to `sqlite3_value_double'
./.libs/libproj.so: undefined reference to `sqlite3_result_null'
./.libs/libproj.so: undefined reference to `sqlite3_bind_double'
./.libs/libproj.so: undefined reference to `sqlite3_create_function'
./.libs/libproj.so: undefined reference to `sqlite3_finalize'
./.libs/libproj.so: undefined reference to `sqlite3_bind_text'
./.libs/libproj.so: undefined reference to `sqlite3_vfs_find'
./.libs/libproj.so: undefined reference to `sqlite3_step'
./.libs/libproj.so: undefined reference to `sqlite3_vfs_unregister'
./.libs/libproj.so: undefined reference to `sqlite3_column_count'
./.libs/libproj.so: undefined reference to `sqlite3_errmsg'
./.libs/libproj.so: undefined reference to `sqlite3_value_type'
./.libs/libproj.so: undefined reference to `sqlite3_snprintf'
./.libs/libproj.so: undefined reference to `sqlite3_value_int64'
./.libs/libproj.so: undefined reference to `sqlite3_prepare_v2'
./.libs/libproj.so: undefined reference to `sqlite3_vsnprintf'
collect2: error: ld returned 1 exit status
make[2]: *** [proj] Error 1
make[2]: Leaving directory `/pgsql/g01/software/stage/proj-6.3.0/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/pgsql/g01/software/stage/proj-6.3.0/src'
make: *** [all-recursive] Error 1

**Comment by rouault** [comment]
> export SQLITE3_LIBS=/pgsql/g01/software/rdbms/10.11.0/lib

Ah, and that should likely be 
```
export SQLITE3_LIBS="-L/pgsql/g01/software/rdbms/10.11.0/lib -lsqlite3"
```

**Comment by rouault** [comment]
Closing due to lack of feedback

**Comment by yulisar** [comment]
> > export SQLITE3_LIBS=/pgsql/g01/software/rdbms/10.11.0/lib
> 
> Ah, and that should likely be
> 
> ```
> export SQLITE3_LIBS="-L/pgsql/g01/software/rdbms/10.11.0/lib -lsqlite3"
> ```

Thanks, this is solving my issue. the same problem.

**Comment by joaocarr** [comment]
I have similar issues with both SQLITE3 and LIBTIFF.

$echo $SQLITE3_LIBS
-L/home/sm1jc/sqlite/sqlite-3.32.3/lib -lsqlite3

I run $./configure  --prefix=blablabla (with no error)

But I get these errors after $make

e.g.
./.libs/libproj.so: undefined reference to `sqlite3_column_blob'
./.libs/libproj.so: undefined reference to `sqlite3_column_int64'
./.libs/libproj.so: undefined reference to `sqlite3_bind_double'
./.libs/libproj.so: undefined reference to `sqlite3_bind_blob'
./.libs/libproj.so: undefined reference to `sqlite3_column_type'
./.libs/libproj.so: undefined reference to `sqlite3_reset'
./.libs/libproj.so: undefined reference to `sqlite3_bind_null'
./.libs/libproj.so: undefined reference to `TIFFClose'
./.libs/libproj.so: undefined reference to `sqlite3_result_double'
./.libs/libproj.so: undefined reference to `TIFFGetField'
./.libs/libproj.so: undefined reference to `TIFFSetTagExtender'
./.libs/libproj.so: undefined reference to `TIFFIsCODECConfigured'

**Comment by lisisili** [comment]
> I have similar issues with both SQLITE3 and LIBTIFF.
> 
> $echo $SQLITE3_LIBS
> -L/home/sm1jc/sqlite/sqlite-3.32.3/lib -lsqlite3
> 
> I run $./configure --prefix=blablabla (with no error)
> 
> But I get these errors after $make
> 
> e.g.
> ./.libs/libproj.so: undefined reference to `sqlite3_column_blob' ./.libs/libproj.so: undefined reference to `sqlite3_column_int64'
> ./.libs/libproj.so: undefined reference to `sqlite3_bind_double' ./.libs/libproj.so: undefined reference to `sqlite3_bind_blob'
> ./.libs/libproj.so: undefined reference to `sqlite3_column_type' ./.libs/libproj.so: undefined reference to `sqlite3_reset'
> ./.libs/libproj.so: undefined reference to `sqlite3_bind_null' ./.libs/libproj.so: undefined reference to `TIFFClose'
> ./.libs/libproj.so: undefined reference to `sqlite3_result_double' ./.libs/libproj.so: undefined reference to `TIFFGetField'
> ./.libs/libproj.so: undefined reference to `TIFFSetTagExtender' ./.libs/libproj.so: undefined reference to `TIFFIsCODECConfigured'

hello, i have the same problem, can you give me some adviece to solve this problem?

**Comment by headtr1ck** [comment]
> > I have similar issues with both SQLITE3 and LIBTIFF.
> > $echo $SQLITE3_LIBS
> > -L/home/sm1jc/sqlite/sqlite-3.32.3/lib -lsqlite3
> > I run $./configure --prefix=blablabla (with no error)
> > But I get these errors after $make
> > e.g.
> > ./.libs/libproj.so: undefined reference to `sqlite3_column_blob' ./.libs/libproj.so: undefined reference to `sqlite3_column_int64'
> > ./.libs/libproj.so: undefined reference to `sqlite3_bind_double' ./.libs/libproj.so: undefined reference to `sqlite3_bind_blob'
> > ./.libs/libproj.so: undefined reference to `sqlite3_column_type' ./.libs/libproj.so: undefined reference to `sqlite3_reset'
> > ./.libs/libproj.so: undefined reference to `sqlite3_bind_null' ./.libs/libproj.so: undefined reference to `TIFFClose'
> > ./.libs/libproj.so: undefined reference to `sqlite3_result_double' ./.libs/libproj.so: undefined reference to `TIFFGetField'
> > ./.libs/libproj.so: undefined reference to `TIFFSetTagExtender' ./.libs/libproj.so: undefined reference to `TIFFIsCODECConfigured'
> 
> hello, i have the same problem, can you give me some adviece to solve this problem?

for me it helped to add both, libtiff and libtiffxx:

export $TIFF_LIBS="-L/path/to/prefix/lib -ltiff -ltiffxx"

**Comment by songololo** [comment]
I am encountering the same issue and can't seem to get things working.

I've been trying both via `./configure` and `cmake3`.

e.g.
```
export SQLITE3_CFLAGS="-I/usr/local/include"
export SQLITE3_LIBS="-L/usr/local/lib -llibsqlite3.so"
export TIFF_CFLAGS="-I/usr/local/include"
export TIFF_LIBS="-L/usr/local/lib -llibtiff.so"
sudo ./configure --prefix=/usr/local --without-curl
```

Which fails to find the custom `sqlite3` path and gives me this form of error:
```
checking for SQLITE3... configure: error: Package requirements (sqlite3 >= 3.11) were not met:

Requested 'sqlite3 >= 3.11' but version of SQLite is 3.7.17

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables SQLITE3_CFLAGS
and SQLITE3_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

I've tried:
```
sudo ./configure --prefix=/usr/local --without-curl \
    SQLITE3_CFLAGS=-I/usr/local/include \
    SQLITE3_LIBS=-L/usr/local/lib \
    TIFF_CFLAGS=-I/usr/local/include \
    TIFF_LIBS=-L/usr/local/lib
sudo make
```

Which runs for a while but then gives me this style of error:
```
./.libs/libproj.so: undefined reference to `sqlite3_bind_int'
./.libs/libproj.so: undefined reference to `sqlite3_column_blob'
./.libs/libproj.so: undefined reference to `sqlite3_column_int64'
./.libs/libproj.so: undefined reference to `sqlite3_bind_double'
./.libs/libproj.so: undefined reference to `sqlite3_bind_blob'
./.libs/libproj.so: undefined reference to `sqlite3_column_type'
./.libs/libproj.so: undefined reference to `sqlite3_reset'
./.libs/libproj.so: undefined reference to `sqlite3_bind_null'
./.libs/libproj.so: undefined reference to `TIFFClose'
./.libs/libproj.so: undefined reference to `sqlite3_result_double'
./.libs/libproj.so: undefined reference to `TIFFGetField'
./.libs/libproj.so: undefined reference to `TIFFSetTagExtender'
./.libs/libproj.so: undefined reference to `TIFFIsCODECConfigured'
./.libs/libproj.so: undefined reference to `sqlite3_close'
./.libs/libproj.so: undefined reference to `sqlite3_create_function'
./.libs/libproj.so: undefined reference to `sqlite3_vfs_register'
./.libs/libproj.so: undefined reference to `sqlite3_last_insert_rowid'
./.libs/libproj.so: undefined reference to `sqlite3_snprintf'
./.libs/libproj.so: undefined reference to `sqlite3_vsnprintf'
./.libs/libproj.so: undefined reference to `sqlite3_libversion_number'
./.libs/libproj.so: undefined reference to `TIFFReadEncodedTile'
./.libs/libproj.so: undefined reference to `sqlite3_column_double'
./.libs/libproj.so: undefined reference to `sqlite3_value_double'
./.libs/libproj.so: undefined reference to `TIFFReadDirectory'
./.libs/libproj.so: undefined reference to `sqlite3_libversion'
./.libs/libproj.so: undefined reference to `TIFFReadEncodedStrip'
./.libs/libproj.so: undefined reference to `sqlite3_column_text'
./.libs/libproj.so: undefined reference to `sqlite3_bind_text'
./.libs/libproj.so: undefined reference to `sqlite3_prepare_v2'
./.libs/libproj.so: undefined reference to `sqlite3_errmsg'
./.libs/libproj.so: undefined reference to `sqlite3_bind_int64'
./.libs/libproj.so: undefined reference to `TIFFIsTiled'
./.libs/libproj.so: undefined reference to `sqlite3_result_int'
./.libs/libproj.so: undefined reference to `TIFFStripSize64'
./.libs/libproj.so: undefined reference to `sqlite3_column_bytes'
./.libs/libproj.so: undefined reference to `sqlite3_value_type'
./.libs/libproj.so: undefined reference to `sqlite3_free_table'
./.libs/libproj.so: undefined reference to `sqlite3_open_v2'
./.libs/libproj.so: undefined reference to `TIFFClientOpen'
./.libs/libproj.so: undefined reference to `sqlite3_free'
./.libs/libproj.so: undefined reference to `TIFFMergeFieldInfo'
./.libs/libproj.so: undefined reference to `sqlite3_exec'
./.libs/libproj.so: undefined reference to `sqlite3_step'
./.libs/libproj.so: undefined reference to `sqlite3_value_int64'
./.libs/libproj.so: undefined reference to `TIFFCurrentDirOffset'
./.libs/libproj.so: undefined reference to `TIFFSetSubDirectory'
./.libs/libproj.so: undefined reference to `sqlite3_vfs_unregister'
./.libs/libproj.so: undefined reference to `TIFFTileSize64'
./.libs/libproj.so: undefined reference to `sqlite3_finalize'
./.libs/libproj.so: undefined reference to `sqlite3_result_null'
./.libs/libproj.so: undefined reference to `sqlite3_vfs_find'
./.libs/libproj.so: undefined reference to `sqlite3_config'
./.libs/libproj.so: undefined reference to `sqlite3_column_count'
./.libs/libproj.so: undefined reference to `sqlite3_initialize'
./.libs/libproj.so: undefined reference to `sqlite3_get_table'
```

And I've tried:
```
sudo cmake3 \
    -DSQLITE3_LIBRARY=/usr/local/lib/libsqlite3.so \
    -DTIFF_INCLUDE_DIR=/usr/local/include \
    -DTIFF_LIBRARY_RELEASE=/usr/local/lib/libtiff.so \
    -DENABLE_CURL=OFF \
    -DBUILD_TESTING=OFF \
    -DBUILD_PROJSYNC=OFF ..
sudo cmake3 --build .
```

Which gives this form of error:
```
...
Error: near line 72252: no such table: main.object_view
Error: near line 72253: no such table: main.object_view
Error: near line 72254: no such table: main.object_view
Error: near line 72255: no such table: main.object_view
Error: near line 72256: no such table: main.object_view
Error: near line 72257: no such table: main.object_view
Error: near line 72258: no such table: main.object_view
Error: near line 72259: no such table: main.object_view
Error: near line 72260: no such table: main.object_view
Error: near line 72264: no such table: main.object_view
Error: near line 72269: no such table: unit_of_measure
Error: near line 72270: no such table: unit_of_measure
Error: near line 72271: no such table: unit_of_measure
Error: near line 72272: no such table: unit_of_measure
Error: near line 72273: no such table: unit_of_measure
Error: near line 72274: no such table: unit_of_measure
Error: near line 72275: no such table: unit_of_measure
Error: near line 72276: no such table: unit_of_measure
...
```

I don't normally work with compiling from source, so I may be missing something (building from source is unavoidable in my current situation).

Versions
======
- SQLITE v3.37
- TIFF v4.3.0
- PROJ v8.2.0

**Comment by rouault** [comment]
@songololo you may need to add /usr/local/bin to your PATH to make sure the right version of the sqlite3 binary is executed, which may solve the errors like "Error: near line 72252".
And for autoconf builds, you should rather use SQLITE3_LIBS="-L/usr/local/lib -lsqlite3" and TIFF_LIBS="-L/usr/local/lib -ltiff"

**Comment by songololo** [comment]
@rouault thanks for your feedback.

Here is my environment:
```
echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
which sqlite3
/usr/local/bin/sqlite3
sqlite3 --version
3.37.2 
```

My latest attempt is:
```
sudo ./configure --prefix=/usr/local --without-curl SQLITE3_CFLAGS=-I/usr/local/include SQLITE3_LIBS="-L/usr/local/lib -lsqlite3" TIFF_CFLAGS=-I/usr/local/include TIFF_LIBS="-L/usr/local/lib -ltiff"
```
Which finds sqlite3: `checking for sqlite3... yes`

```
sudo make
```
Though I'm still running into the `Error: near line 72664: no such table: main.coordinate_operation_view` style errors.

**Comment by songololo** [comment]
This seems to have worked:
```
sudo cmake3 -DCMAKE_BUILD_TYPE=Release -DSQLITE3_INCLUDE_DIR=/usr/local/include -DSQLITE3_LIBRARY=/usr/local/lib/libsqlite3.so -DTIFF_INCLUDE_DIR=/usr/local/include -DTIFF_LIBRARY_RELEASE=/usr/local/lib/libtiff.so -DENABLE_CURL=OFF -DBUILD_TESTING=OFF -DBUILD_PROJSYNC=OFF ..
sudo cmake3 --build .
sudo cmake3 --build . --target install
```

**Comment by alsaleem00** [comment]
The cflags/libs should be specified before ./configure (not as switches.) like this:
SQLITE3_CFLAGS=... SQLITE3_LIBS=... TIFF_CFLAGS=... TIFF_LIBS=... ./configure ....

**Comment by dg0yt** [comment]
> The cflags/libs should be specified before ./configure (not as switches.) like this: SQLITE3_CFLAGS=... SQLITE3_LIBS=... TIFF_CFLAGS=... TIFF_LIBS=... ./configure ....

No.

**Comment by z-han** [comment]
with the error :  undefined reference to `sqlite3_bind_int'
try to reinstall sqlite3.

add "#define SQLITE_ENABLE_COLUMN_METADATA 1"   in the sqlite3.c, then ./configure


**#define SQLITE_CORE 1
#define SQLITE_AMALGAMATION 1
#ifndef SQLITE_PRIVATE
    define SQLITE_PRIVATE static
#endif
#define SQLITE_ENABLE_COLUMN_METADATA 1

/************** Begin file ctime.c *******************************************/
/***



When this C-preprocessor macro is defined, SQLite includes some additional APIs that provide convenient access to meta-data about tables and queries. The APIs that are enabled by this option are:

sqlite3_column_database_name() .....
