### ISSUE TITLE
PROJ 6.3.0: 2d transformation: UOM transformation is lacked for height coordinate

### ISSUE THREAD

**Issue by and-marsh** [OSGeo/PROJ#1860]
#### Example of problem
After update to `proj 6.3.0` i found changing in 2d transformation between systems with different units of measure.

 For example i have transformation between `WGS84` and `NAD83(HARN) / Arizona East (ft)`, i expect that UOM for height in source CRS is `meter`  and UOM in target CRS is `foot`. And it was true for `proj < 6.3.0`. Due to it hight was transformed in target UOM.
Now this transformation doesn't take changing UOM into account for height coordinate:
```c
./cs2cs  EPSG:4979  EPSG:2867 <<EOF
35 -110 10
EOF
749912.01       1455337.62 10.00
```

I'm not sure it is correct, so I found it necessary to notify you of such behavior

#### Environment Information
 - PROJ version (`proj 6.3.0`)
 - `macOS Catalina 10.15.2`

#### Installation method
 - from source

**Comment by rouault** [comment]
Yes this is indeed a change of behaviour. This wasn't really "designed" for that use case and is a side effect of a bug fix to address issues with compound CRS. That said the vertical unit for a 2D CRS is unspecified, by definition, so you cannot rely on this value. The new behaviour is to consider that for a 2D CRS the vertical unit is metre.

**Comment by and-marsh** [comment]
Ok, thank you for your response, i guess the issue can be closed

**Comment by egorf** [comment]
> Yes this is indeed a change of behaviour. This wasn't really "designed" for that use case and is a side effect of a bug fix to address issues with compound CRS. That said the vertical unit for a 2D CRS is unspecified, by definition, so you cannot rely on this value. The new behaviour is to consider that for a 2D CRS the vertical unit is metre.

Hi! What would be the "correct" way to get the old behavior now? I know this might be outside proj scope, but I can't see a situation where the data would be required in ft for horizontal coordinates and in meters for the vertical part.
