### ISSUE TITLE
No `./configure` file?

### ISSUE THREAD

**Issue by swiss-knight** [OSGeo/PROJ#1871]
I'm trying to build `proj` on Ubuntu 16.04 64bits (`4.15.0-74-generic x86_64 GNU/Linux`).    
I cloned the repository and checked out to branch `6.3`.    

Then, as stated in the documentation here: https://proj.org/install.html , I ran `./configure` prior to `make && make install` but apparently, the file doesn't exist:

```
/opt/PROJ$ ./configure
-bash: ./configure: No such file or directory
```

Did I miss a step in the build process?    

I guess `automake` should be run first?    
But I didn't found this step in the installation guide.

**Comment by kbevers** [comment]
You need to run `autogen.sh` first when building from a clone of the repository. This used to be in the README but apparently was removed recently. I'll update the install instructions to include a note on it.

**Comment by kbevers** [comment]
Added in ef20438
