### ISSUE TITLE
Different results of new and old implementation

### ISSUE THREAD

**Issue by dbsint** [OSGeo/PROJ#1876]
#### Problem description

Hello. I have try to convert coordinates from meters to degree. In compare old and new implementation of proj lib I got different results.

#### Source code

```c++

#include <proj.h>
#include "proj_internal.h"
#include <iostream>

void test(){
	const char* prj_str = "+proj=robin +lon_0=0 +x_0=0 +y_0=0 +ellps=clrk66 +towgs84=-8,160,176,0,0,0,0 +units=m +no_defs";
	std::cout.precision(20);

// new implementation (wrong results)
	auto proj_new = proj_create( PJ_DEFAULT_CTX, prj_str);
	PJ_COORD pt_xy_new = proj_coord ( 0, 0, 0, 0);
	PJ_COORD pt_degr_new = proj_trans(proj_new, PJ_INV, pt_xy_new);
	std::cout << "new: (" << std::fixed << pt_degr_new.lp.lam << " "<< pt_degr_new.lp.phi << ")" << std::endl;
	proj_destroy(proj_new);

// old implementation (valid results)
	auto proj_old = pj_init_plus( prj_str);
	projXY pt_xy_old = {0,0};
	auto pt_degr_old = pj_inv(pt_xy_old, proj_old);
	std::cout << "old: (" << std::fixed << pt_degr_old.lam << " "<< pt_degr_old.phi << ")" << std::endl;
	pj_free(proj_old);
}

```

output:
new: (0.00002508545359241857 0.00002777996680520826)
old: (0.00000000000000000000 0.00000000000000000732)

 If remove +towgs84 from input string then results is identical. (i.e. "+proj=robin +lon_0=0 +x_0=0 +y_0=0 +ellps=clrk66 +units=m +no_defs";)
 output:
new: (0.00000000000000000000 0.00000000000000000732)
old: (0.00000000000000000000 0.00000000000000000732)

#### Environment Information
 - PROJ version (Rel. 6.2.1, November 1st, 2019)
 - archlinux

#### Installation method
 - from archlinux repos

**Comment by rouault** [comment]
Works as expected. proj_create() honours +towgs84, whereas pj_inv() didn't.
