### ISSUE TITLE
Coordinate operation PROJ->WKT support

### ISSUE THREAD

**Issue by snowman2** [OSGeo/PROJ#1890]
Currently when doing `projinfo` on a PROJ string to create a coordinate operation you get a `CONVERSION` WKT string that is a `PROJ-based coordinate operation`:
```
projinfo '+proj=aea +lat_1=1'
PROJ string:
+proj=aea +lat_1=1

WKT2:2019 string:
CONVERSION["PROJ-based coordinate operation",
    METHOD["PROJ-based operation method: +proj=aea +lat_1=1"]]
```

However, when using the `type=crs` with it, the `CONVERSION` WKT parameter is fully filled out:
```
projinfo '+proj=aea +lat_1=1 +type=crs'
PROJ.4 string:
+proj=aea +lat_0=0 +lon_0=0 +lat_1=1 +lat_2=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs +type=crs

WKT2:2019 string:
PROJCRS["unknown",
    BASEGEOGCRS["unknown",
        DATUM["World Geodetic System 1984",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]],
            ID["EPSG",6326]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8901]]],
    CONVERSION["unknown",
        METHOD["Albers Equal Area",
            ID["EPSG",9822]],
        PARAMETER["Latitude of false origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8821]],
        PARAMETER["Longitude of false origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8822]],
        PARAMETER["Latitude of 1st standard parallel",1,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8823]],
        PARAMETER["Latitude of 2nd standard parallel",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8824]],
        PARAMETER["Easting at false origin",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8826]],
        PARAMETER["Northing at false origin",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8827]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]]
```

Thoughts on having the WKT string for the `CONVERSION` also fully filled out like the `type=crs` version? This would be useful like in the case in #1881 where the coordinate operation can only be created with a PROJ string as there is no WKT equivalent for the scaling factor for creation due to the official EPSG definition. However, the fix in #1884 makes it so that there is a WKT equivalent on export.

**Comment by rouault** [comment]
This would not be immediately trivial to do so, but I'm not really following you on the motivation. The current implementation in the non type=crs scenario will preserve fully the PROJ string provided
```
$ src/projinfo '+proj=cea +k_0=2 +foo=bar'
PROJ string:
+proj=cea +k_0=2 +foo=bar

WKT2:2019 string:
CONVERSION["PROJ-based coordinate operation",
    METHOD["PROJ-based operation method: +proj=cea +k_0=2 +foo=bar"]]
```

**Comment by kbevers** [comment]
I reckon that what @snowman2 ask for is output similar to:

```
projinfo '+proj=aea +lat_1=1'
PROJ string:
+proj=aea +lat_1=1

WKT2:2019 string:
CONVERSION["PROJ-based coordinate operation",
        METHOD["Albers Equal Area",
            ID["EPSG",9822]],
        PARAMETER["Latitude of false origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8821]],
        PARAMETER["Longitude of false origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8822]],
        PARAMETER["Latitude of 1st standard parallel",1,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8823]],
        PARAMETER["Latitude of 2nd standard parallel",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8824]],
        PARAMETER["Easting at false origin",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8826]],
        PARAMETER["Northing at false origin",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8827]]]]
```

Basically an elaborated WKT description of the operation

**Comment by rouault** [comment]
> Basically an elaborated WKT description of the operation

Yes, but for which purpose ? The current behaviour has at least the advantage of being guaranteed to be loss-less

**Comment by snowman2** [comment]
> This would not be immediately trivial to do so, but I'm not really following you on the motivation.

It is nice to have consistency on output between the non-crs and CRS version of the coordinate operation. Also, it makes the parameters easier to parse through when exporting to PROJ JSON.

> The current behaviour has at least the advantage of being guaranteed to be loss-less

I think only doing so when there is a lossless conversion in WKT form makes sense.

**Comment by rouault** [comment]
If someone wants to have a crack at this, the starting place would be around https://github.com/OSGeo/PROJ/blob/a4c5cc1e42559f1d92c6b7655680d11f1eead703/src/iso19111/io.cpp#L9368

unexpectedStructure would have been set to false at https://github.com/OSGeo/PROJ/blob/a4c5cc1e42559f1d92c6b7655680d11f1eead703/src/iso19111/io.cpp#L9230 , so you'd have to change things a bit around there

**Comment by snowman2** [comment]
It seems that the input is tied quite a bit to building a CRS. For example, it needs the Ellipsoid to determine the method.
https://github.com/OSGeo/PROJ/blob/a4c5cc1e42559f1d92c6b7655680d11f1eead703/src/iso19111/io.cpp#L8652-L8661

It seems impossible to do without the `+type=crs` unless I am missing something.

With that, my next question is if someone were to build a CRS like so:
```
PROJCRS["unknown",
    BASEGEOGCRS["unknown",
        DATUM["World Geodetic System 1984",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]],
            ID["EPSG",6326]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8901]]],
    CONVERSION["PROJ-based coordinate operation",
        METHOD["PROJ-based operation method: +proj=aea +lat_1=1"]]
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]]
```

How difficult would it be to attempt to output it like this? And where in the code would you look to attempt to change that?
```
PROJCRS["unknown",
    BASEGEOGCRS["unknown",
        DATUM["World Geodetic System 1984",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]],
            ID["EPSG",6326]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8901]]],
    CONVERSION["unknown",
        METHOD["Albers Equal Area",
            ID["EPSG",9822]],
        PARAMETER["Latitude of false origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8821]],
        PARAMETER["Longitude of false origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8822]],
        PARAMETER["Latitude of 1st standard parallel",1,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8823]],
        PARAMETER["Latitude of 2nd standard parallel",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8824]],
        PARAMETER["Easting at false origin",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8826]],
        PARAMETER["Northing at false origin",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8827]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]]

```

**Comment by rouault** [comment]
> It seems impossible to do without the `+type=crs` unless I am missing something.

The logic in +type=crs assumes WGS84 for the geographic CRS if no specific ellipsoid is specified in the PROJ string. The same could be just re-used.

> How difficult would it be to attempt to output it like this?

In WKTParser::Private::buildConversion(), you'd basically have to use PROJStringParser::createFromPROJString() with the PROJ string in the METHOD[] node and get the Conversion object from the returned ProjectedCRS.

**Comment by snowman2** [comment]
> The logic in +type=crs assumes WGS84 for the geographic CRS if no specific ellipsoid is specified in the PROJ string. The same could be just re-used.

That could be problematic to assume if it was used to build a CRS with a different ellipsoid. I think I will go with the full WKT string version to be safe.

> In WKTParser::Private::buildConversion(), you'd basically have to use PROJStringParser::createFromPROJString() with the PROJ string in the METHOD[] node and get the Conversion object from the returned ProjectedCRS.

Sounds like a good idea. :+1:

**Comment by snowman2** [comment]
After giving it a go, I better understand what @rouault was saying about the current behavior being loss-less and will table this idea for now. I definitely don't want to introduce lossy behavior :). Thanks for all the tips along the way @rouault!
