### ISSUE TITLE
Confusing output from `cs2cs`

### ISSUE THREAD

**Issue by artemp** [OSGeo/PROJ#1894]
#### Example of problem

```
cs2cs -Ef %.10f +init=EPSG:2193 +to +init=EPSG:4326  <<END 
274000 3087000
276000 3087000
276000 7173000
274000 7173000
END
274000 3087000	148.7639922894	-60.1157610321 0.0000000000
276000 3087000	148.7968095108	-60.1221489798 0.0000000000
276000 7173000	159.9548476477	-24.9788425008 0.0000000000
274000 7173000	159.9355459783	-24.9771194497 0.0000000000
```

```
cs2cs -Esf %.10f EPSG:2193 +to EPSG:4326  <<END 
274000 3087000
276000 3087000
276000 7173000
274000 7173000
END
274000 3087000	-107.2707818506	-76.5784585357 0.0000000000
276000 3087000	-107.3446420266	-76.5752515226 0.0000000000
276000 7173000	-99.4882522415	-45.2788173624 0.0000000000
274000 7173000	-99.4701210457	-45.2795948561 0.0000000000

```

#### Problem description
Not getting expected results

#### Expected Output
I'm expecting output to match 

#### Environment Information
 - 6.3.0 (`proj`)
 - Ubuntu 19.10

#### Installation method
 - from source
`CC=/usr/bin/clang CXX=/usr/bin/clang++ CXXFLAGS="-std=c++14 -stdlib=libc++" LDFLAGS="-stdlib=libc++" ./configure --prefix=/opt/mapnik_deps --enable-lto`

**Comment by rouault** [comment]
Those results are expected.
+init=EPSG:XXXX corresponds to the deprecated syntax where EPSG CRS axis order is ignored. Thus projected CRS are assumed to be easting, northing and geographic CRS are assumed to be longitude, latitude
EPSG:XXXX syntax new to PROJ6 is EPSG CRS axis order compliant. In that case, EPSG:2193 is defined as having northing, easting axis order. And EPSG:4326 latitude, longitude

Partly mentionned in https://proj.org/apps/cs2cs.html and https://proj.org/faq.html#why-is-the-axis-ordering-in-proj-not-consistent

**Comment by rouault** [comment]
You would need to also add a -r switch to reverse the input order (for that particular case using EPSG:2193):
```
$ echo "274000 3087000" | src/cs2cs -Ersf %.10f EPSG:2193 +to EPSG:4326 
274000 3087000	148.7639922894	-60.1157610321 0.0000000000
```

**Comment by artemp** [comment]
:+1:
