### ISSUE TITLE
PROPOSAL: Add `+type=conversion`

### ISSUE THREAD

**Issue by snowman2** [OSGeo/PROJ#1900]
Related to #1890 

In order to implement something related to https://github.com/OSGeo/PROJ/issues/1890#issuecomment-578786844, I am wondering if it would be useful to add  `+type=conversion` or something similar.

The reasoning would be that the axis order and ellipsoid parameters are needed for the correct conversion to be added and it would differentiate it from other types.

**Comment by rouault** [comment]
I'm not sure to understand the need. +type=conversion (more generally an "operation" that can be a conversion or a transformation) is implied by the absence of +type=crs

**Comment by snowman2** [comment]
It is to allow the user to opt-in to tell PROJ to make the conversion to WKT from PROJ-Based-Operation. This way, it can also remain a PROJ-based-operation if the user so desires.

**Comment by rouault** [comment]
Hum, I'm a bit confused. Could you give examples of the input & output for the various cases you have in mind ?

**Comment by snowman2** [comment]
Maybe another parameter name might be more clear?
```
projinfo '+proj=aea +lat_1=1'
PROJ string:
+proj=aea +lat_1=1

WKT2:2019 string:
CONVERSION["PROJ-based coordinate operation",
    METHOD["PROJ-based operation method: +proj=aea +lat_1=1"]]
```
Versus:
```
projinfo '+proj=aea +lat_1=1 +type=conversion'
PROJ string:
+proj=aea +lat_1=1

WKT2:2019 string:
CONVERSION["undefined",
        METHOD["Albers Equal Area",
            ID["EPSG",9822]],
        PARAMETER["Latitude of false origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8821]],
        PARAMETER["Longitude of false origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8822]],
        PARAMETER["Latitude of 1st standard parallel",1,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8823]],
        PARAMETER["Latitude of 2nd standard parallel",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8824]],
        PARAMETER["Easting at false origin",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8826]],
        PARAMETER["Northing at false origin",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8827]]]]
```

**Comment by rouault** [comment]
I believe the +type=conversion would be the desired behaviour by default, if when converting back from the expended WKT representation to PROJ string is lossless.
And if it was to be explicit like you suggest, what would we do in the situation where +type=conversion is specified and the PROJ string -> WKT -> PROJ string isn't lossless ?
Admitedly in the +type=crs, we don't do that check, but perhaps we should, and if the roundtrip doesn't work, we should perhaps fallback to METHOD["PROJ-based operation method: ...."]

**Comment by snowman2** [comment]
> Admitedly in the +type=crs, we don't do that check, but perhaps we should, and if the roundtrip doesn't work, we should perhaps fallback to METHOD["PROJ-based operation method: ...."]

Is this a check you would be willing to add in?

**Comment by rouault** [comment]
> Is this a check you would be willing to add in?

Added somewhere in the todo list :-)

**Comment by snowman2** [comment]
> Added somewhere in the todo list :-)

Much appreciated :+1:

**Comment by rouault** [comment]
> Added somewhere in the todo list :-)

Actually I'm lucky as I think this is already implemented :-)
PROJStringParser::Private::buildProjectedCRS() has this
```
    if (hasUnusedParameters(step)) {
        props.set("EXTENSION_PROJ4", projString_);
    }
```
This will store in the CRS object the original PROJ string if there's a PROJ recognized parameter that the PROJstring->ISO19111 ingester didn't recognize.

So for your use case, you'd just need to call getExtensionProj4() on the projectedCRS. If it is non empty, then just keep the current ```CONVERSION["PROJ-based coordinate operation",
    METHOD["PROJ-based operation method: ....]]``` representation

**Comment by snowman2** [comment]
Perfect - I just added that to #1899

**Comment by snowman2** [comment]
Thanks!
