### ISSUE TITLE
Tutorial QGIS

### ISSUE THREAD

**Issue by SebastianKasan** [OSGeo/PROJ#1909]
Hi there, 

would it be possible for you to make a tutorial on how to transform between current epoch WGS84 and other CRSs (for dummies)? I need to convert ETRS89 to current epoch WGS84 (what my emlid gnss receiver spills out). I think this is a very relevant issue for many surveyors and unfortunately until now, only elaborate survey programs offer these sorts of transformation...

I read through the HTDP docs on the proj page, but it is still unclear to me, how to transform whole layers in QGIS with this approach...

Thank you

**Comment by kbevers** [comment]
That would be a great tutorial to have. Obviously we are not going to add a QGIS tutorial to the PROJ docs but this can be framed in terms of PROJ utilities. I have made a tutorial that is a bit more generic than what you are asking but it might be a good starting place: https://github.com/kbevers/PROJTutorial/ Especially the exercises on the Helmert transform should point you in the right direction. At some point I am going to add that tutorial to the PROJ docs, I just need to find the time to do so. We still need a tutorial that is minded more at day-to-day use and your example here would fit that nicely. In the end it is up to the community to provide such a tutorial.

And now back to your problem. Which realization of ETRS89 and which realization of WGS84 do you want to transform betweeen?

**Comment by SebastianKasan** [comment]
Thank you Kristian for your kind answer.
Because I am not 100% sure of my understanding, I give you some background:

I need to transform coordinates (in shapefile or csv) that I get from my Emlid RS2, corrected by NTRIP (SAPOS here in Germany). My NTRIP provider tells me that corrections come in "ETRS89". 

From what I have gathered, we talk about EPSG:4258. I would assume that the corrections come in the latest realization. Format is LLH.

And the same goes for WGS84- EPSG:4326. I would assume that current satellite signals from GPS and GLONASS send in the latest realization. Unfortunately I have found nobody that is knowledgable to confirm these intricacies.

With regards to WGS84, I found that the latest realizations come in XYZ only... but I need again, LLH...

**Comment by kbevers** [comment]
> I need to transform coordinates (in shapefile or csv)

You'll need GDAL for the shapefile. You can use the `ogr2ogr` utility with the [`-ct`](https://gdal.org/programs/ogr2ogr.html#cmdoption-ogr2ogr-ct) switch applied. I'll explain the transformation I think you need below. You'll have to piece it together yourself.

> From what I have gathered, we talk about EPSG:4258. I would assume that the corrections come in the latest realization. Format is LLH.

EPSG:4258 just means ETRS89 - it doesn't specify which national realization of ETRS89 it is. Since you are in Germany I believe it is ETRF200. 

> And the same goes for WGS84- EPSG:4326. I would assume that current satellite signals from GPS and GLONASS send in the latest realization. Unfortunately I have found nobody that is knowledgable to confirm these intricacies.

Correct, a GNSS measurement from today will give you data in the latest WGS84 realization (WGS84 (G1762)). It is equivalent to ITRF2008. More on WGS84 here https://confluence.qps.nl/qinsy/8.0/en/world-geodetic-system-1984-wgs84-182618392.html

With the knowledge that you really want to transform between ETRF2000 and ITRF2008 we can ask `projinfo` how to do that:

```
projinfo -s ETRF2000 -t ITRF2008 -o PROJ
Candidate operations found: 1
-------------------------------------
Operation n┬░1:

unknown id, Conversion from ETRF2000 (geog2D) to ETRF2000 (geocentric) + Inverse of ITRF2008 to ETRF2000 (1) + Conversion from ITRF2008 (geocentric) to ITRF2008 (geog2D), 0 m, Europe - ETRS89

PROJ string:
+proj=pipeline +step +proj=axisswap +order=2,1 +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=cart +ellps=GRS80 +step +inv +proj=helmert +x=0.0521 +y=0.0493 +z=-0.0585 +rx=0.000891 +ry=0.00539 +rz=-0.008712 +s=0.00134 +dx=0.0001 +dy=0.0001 +dz=-0.0018 +drx=8.1e-05 +dry=0.00049 +drz=-0.000792 +ds=8e-05 +t_epoch=2000 +convention=position_vector +step +inv +proj=cart +ellps=GRS80 +step +proj=unitconvert +xy_in=rad +xy_out=deg +step +proj=axisswap +order=2,1
```

Note that the above transformation requires geodetic coordinates as input and will return geodetic coordinates as well. But as this seems to be what you need everything is fine. Here's an example transformation:

```
echo 52.0 13.0 0.0 2020.1 | cct -d 8 +proj=pipeline \
+step +proj=axisswap +order=2,1 \
+step +proj=unitconvert +xy_in=deg +xy_out=rad \
+step +proj=cart +ellps=GRS80 \
+step +inv +proj=helmert +x=0.0521 +y=0.0493 +z=-0.0585 +rx=0.000891 +ry=0.00539 \
  +rz=-0.008712 +s=0.00134 +dx=0.0001 +dy=0.0001 +dz=-0.0018 +drx=8.1e-05 +dry=0.00049 \
  +drz=-0.000792 +ds=8e-05 +t_epoch=2000 +convention=position_vector \
+step +inv +proj=cart +ellps=GRS80 \
+step +proj=unitconvert +xy_in=rad +xy_out=deg +step +proj=axisswap +order=2,1
  52.00000494    13.00000837    0.01771682     2020.1000
```

where 2020.1 is roughly todays date in decimalyears. 

> With regards to WGS84, I found that the latest realizations come in XYZ only... but I need again, LLH...

That is just a simple conversion. See the `cart` operation: https://proj.org/operations/conversions/cart.html

**Comment by SebastianKasan** [comment]
Ok, great. I will try to apply this in GDAL tonight... If I manage, I can write the tutorial hopefully...

Thank you

**Comment by kbevers** [comment]
> If I manage, I can write the tutorial hopefully...

That would be a very welcome addition to the docs!

**Comment by SebastianKasan** [comment]
So I tried it and the process works but to my surprise, the difference XY is only 30 cm. It should be around 70 cm.

I tried it with two different files, the distance stays the same...

I will try to get some info on the realization of ETRS89 that my NTRIP corrections come in... we are getting closer however...

**Comment by SebastianKasan** [comment]
Information from SAPOS says that corrections come in: ETRS89/DREF91( Realisierung 2016)

**Comment by SebastianKasan** [comment]
From the written documents supplied by SAPOS : 
![grafik](https://user-images.githubusercontent.com/39992733/73921160-24202680-48c7-11ea-8908-fe9fef7c8879.png)

So it seems to be realization 1989...
