### ISSUE TITLE
CMake's set(CMAKE_CXX_STANDARD 11) does not work

### ISSUE THREAD

**Issue by mwtoews** [OSGeo/PROJ#1924]
It seems that CMake's `set(CMAKE_CXX_STANDARD 11)` approach does not work, since a configure can succeed, but the build fail.

#### Example of problem

Try to configure a CMake build with an older compiler before C++11 support, e.g., GCC 4.4 or MSVC++ 9.0, and the configure messages may look like:

```
...
-- Requiring C++11
-- Requiring C++11 - done
-- Requiring C99
-- Requiring C99 - done
...
```
no problems? I'm actually having a hard time finding an old compiler that fails during CMake's configuration stage.

However when building with MSVC++ 9.0:
```
...
[  2%] Building CXX object src/CMakeFiles/proj.dir/4D_api.cpp.obj
D:\src\PROJ\PROJ\include\proj/util.hpp(33) : fatal error C1189: #error :  Must have C++11 or newer.
NMAKE : fatal error U1077: 'C:\Users\user\AppData\Local\Programs\Common\MICROS~1\VISUAL~1\9.0\VC\bin\amd64\cl.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Users\user\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Users\user\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\nmake.exe"' : return code '0x2'
Stop.
```
or with GCC 4.4
```
...
[  1%] Building CXX object src/CMakeFiles/proj.dir/4D_api.cpp.o
cd /home/user/src/PROJ/build/src && /usr/bin/c++  -DCURL_ENABLED -DMUTEX_pthread -DPROJ_LIB=\"/usr/local/share/proj\" -DTIFF_ENABLED -Dproj_EXPORTS -I/home/user/src/PROJ/src -I/home/user/src/PROJ/include -I/home/user/src/PROJ/build/src -I/amp/gw/sw/anaconda3/include  -O3 -DNDEBUG -fPIC -fvisibility=hidden   -Wall -Wextra -Wswitch -Wshadow -Wunused-parameter -Wmissing-declarations -Wformat -Wformat-security -std=c++0x -o CMakeFiles/proj.dir/4D_api.cpp.o -c /home/user/src/PROJ/src/4D_api.cpp
In file included from /home/user/src/PROJ/src/proj_json_streaming_writer.hpp:39,
                 from /home/user/src/PROJ/include/proj/io.hpp:41,
                 from /home/user/src/PROJ/include/proj/common.hpp:36,
                 from /home/user/src/PROJ/src/proj_internal.h:61,
                 from /home/user/src/PROJ/src/4D_api.cpp:47:
/home/user/src/PROJ/include/proj/util.hpp:33:2: error: #error Must have C++11 or newer.
In file included from /home/user/src/PROJ/src/4D_api.cpp:55:
/home/user/src/PROJ/include/proj/internal/internal.hpp:37:2: error: #error Must have C++11 or newer.
```

#### Problem description
Setting C++11 support for CMake was previously discussed in #1118

The approach taken was to set a global:
```
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
```
which is [the recommend approach](https://cliutils.gitlab.io/modern-cmake/chapters/features/cpp11.html), however this doesn't seem to work as expected since a configuration with a non-C++11 compliant compiler can succeed, but then quickly fail when building. Doing some tests with `src/lib_proj.cmake`, this also does not work:
```
set_target_properties(proj PROPERTIES
    CXX_STANDARD 11
    CXX_STANDARD_REQUIRED YES
    CXX_EXTENSIONS NO
)
```

#### Possible solutions?

It seems that [`target_compile_features`](https://cmake.org/cmake/help/v3.9/command/target_compile_features.html) may offer a slightly more robust solution:
```
target_compile_features(proj INTERFACE cxx_std_11)
set_target_properties(proj PROPERTIES CXX_EXTENSIONS OFF)
```
this sort-of works, however GCC 4.8 seems to slip thru with partial C++11 support. Probably a more solution is to harvest a few specific C++ features from [a list of C++ features](https://cmake.org/cmake/help/v3.9/prop_gbl/CMAKE_CXX_KNOWN_FEATURES.html):
```
target_compile_features(proj
    INTERFACE
        cxx_constexpr
        cxx_nullptr
        cxx_variadic_templates
)
```
this will at least fail a configure with (e.g.):
```
CMake Error at src/lib_proj.cmake:354 (target_compile_features):
  target_compile_features The compiler feature "cxx_constexpr" is not known
  to CXX compiler

  "GNU"

  version 4.4.7.
Call Stack (most recent call first):
  src/CMakeLists.txt:3 (include)
```
or
```
CMake Error at src/lib_proj.cmake:350 (target_compile_features):
  target_compile_features no known features for CXX compiler

  "MSVC"

  version 15.0.30729.1.
```
these fails are the expected outcomes of attempting to use old compilers.

---

Any thoughts? With a `target_compile_features` solution, am I picking the correct [C++ features](https://cmake.org/cmake/help/v3.9/prop_gbl/CMAKE_CXX_KNOWN_FEATURES.html) currently in-use? Too many/few? Are these all `PUBLIC`? An article that demonstrates this feature use is show [here](https://crascit.com/2015/03/28/enabling-cxx11-in-cmake/).

**Comment by busstoptaktik** [comment]
@mwtoews to me, this looks mostly like a bug in CMake. Obviously one that maybe should be worked around, but probably also be mentioned to Kitware?

**Comment by melroy89** [comment]
Is this still an issue in CMake!?

**Comment by mwtoews** [comment]
Looking at this issue a bit further, it seems that we might need to wait a couple years until CMake 3.22, when `target_compile_features` will ignore valid compile features for un-enabled languages, described in [this proposal](https://gitlab.kitware.com/cmake/cmake/-/issues/22326) (and [fix](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/6255)). The former behaviour of `target_compile_features` would require all projects that link to `PROJ::proj` to have CXX enabled, which is non-sense. The `CMAKE_CXX_STANDARD` variable trick will need to the way for a while longer, as it does not impose that requirement.

As for finding C++ compilers that _don't_ support  C++11, this is increasingly rare to find, so the motivation for this issue is fading into obscurity.

**Comment by craigscott-crascit** [comment]
CMake 3.22 should come out towards the end of this year, based on its usual release cadence.

**Comment by craigscott-crascit** [comment]
For completeness, CMake 3.22 has now been released.
