### ISSUE TITLE
6.3.1-rc1: `make distclean` deletes `README` which is not regenerated

### ISSUE THREAD

**Issue by sebastic** [OSGeo/PROJ#1927]
As reported by Andreas Beckmann in [Debian Bug #951187](https://bugs.debian.org/951187):
> proj/experimental FTBFS twice in a row. 'debian/rules clean' after the
> first build removes 'README' via 'make distclean', but that file
> is not regenerated during the second build causing the install target to
> fail. I did not check whether the package in sid has the same problem.
> ```
> [...]
> dh_auto_clean
>         make -j3 distclean
> [...]
> make[3]: Entering directory '/build/proj-6.3.1~rc1'
> rm -rf .libs _libs
> rm -f README
> rm -f *.lo
> test -z "proj.pc" || rm -f proj.pc
> rm -f libtool config.lt
> rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
> test . = "." || test -z "" || rm -f
> rm -f cscope.out cscope.in.out cscope.po.out cscope.files
> make[3]: Leaving directory '/build/proj-6.3.1~rc1'
> [...]
>    debian/rules override_dh_installdocs
> make[1]: Entering directory '/build/proj-6.3.1~rc1'
> dh_installdocs -A AUTHORS NEWS README
> cp: cannot stat 'README': No such file or directory
> dh_installdocs: error: cp --reflink=auto -a README debian/proj-data/usr/share/doc/proj-data returned exit code 1
> make[1]: *** [debian/rules:57: override_dh_installdocs] Error 25
> make[1]: Leaving directory '/build/proj-6.3.1~rc1'
> make: *** [debian/rules:28: binary] Error 2
> [...]
> ```

[proj_6.3.1~rc1-1~exp1_twice.log.gz](https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=951187;filename=proj_6.3.1~rc1-1~exp1_twice.log.gz;msg=5)

**Comment by rouault** [comment]
It isn't something new to 6.3.1, right ?

**Comment by sebastic** [comment]
Probably not, it was likely broken since 9ae0e5e8a515d4e225a895809de32ed83fc413da but not noticed before.

The change is trivial though, so could be included in 6.3.1 if you don't just rename the rc1 tarballs.

**Comment by rouault** [comment]
Answering myself, closer inspection of "diff -Nur proj-6.3.0/ proj-6.3.1/" shows no related change, so must be an older issue

> The change is trivial though, so could be included in 6.3.1 if you don't just rename the rc1 tarballs.

I want 6.3.1 to be out as soon as possible to correct the crashing issue in MapServer (and other inconvenience in R spatial) and I'm little available next week so I think I'll stick with 6.3.1rc1.

**Comment by kbevers** [comment]
Yes, 6.3.1RC1 should be fine. We'll include the fix in 7.0.0 and any potential other 6.3.x releases.
