### ISSUE TITLE
proj_grid_get_info_from_database v7 regression/API break

### ISSUE THREAD

**Issue by nyalldawson** [OSGeo/PROJ#1942]
In proj 6, using proj_grid_get_info_from_database with the proj operation string

    +proj=pipeline +step +proj=axisswap +order=2,1 +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +inv +proj=hgridshift +grids=GDA94_GDA2020_conformal_and_distortion.gsb +step +proj=unitconvert +xy_in=rad +xy_out=deg +step +proj=axisswap +order=2,1

correctly populates the url/directDownload arguments.

Under proj 7, calling proj_grid_get_info_from_database with the exact same operation string results in empty/false results for the url/directDownload... arguments.

For proj 7, it's necessary to change "GDA94_GDA2020_conformal_and_distortion.gsb" to "au_icsm_GDA94_GDA2020_conformal_and_distortion.tiff" in the operation string in order to get the correct results from proj_grid_get_info_from_database. But this breaks existing code, e.g. a QGIS project will store the user-selected operation strings inside that project, and then present user visible warnings and advice if another user loads that same project and the required grids aren't available. If a user loads a project created in a proj 6 based version, then the required grid details cannot be retrieved under a proj 7 build.

**Comment by kbevers** [comment]
I believe this has to be sorted out before we can make a final release of 7.0.0. 

@rouault I am not entirely sure if this is the expected behaviour or not. My impression was that the renamed grid files from PROJ-data should be transparent to the users. Is that correct?
