### ISSUE TITLE
PROJ 7.0.0 static library

### ISSUE THREAD

**Issue by spatialite** [OSGeo/PROJ#1957]
7.0.0 now depends on libcurl, and thus requires explicitly passing a -DCURL_STATICLIB directive 
to ./configure in order to build an usable PROJ static library (due to name mangling issues of
link symbols).

tested on Windows/MinGW, but the same will probably happen on Linux too.

**Comment by weagle08** [comment]
You need to set ENABLE_CURL=OFF as well as BUILD_PROJSYNC=OFF since it depends on the CURL library and you should be good to go.

SEE [BUILD OPTIONS](https://proj.org/install.html#cmake-configure-options)
