### ISSUE TITLE
Axis swap produces different results

### ISSUE THREAD

**Issue by snowman2** [OSGeo/PROJ#1961]
From: https://github.com/pyproj4/pyproj/issues/537

#### Example of problem

```
$ echo '-35000 -7000 0 0' | cct +proj=pipeline +step +inv +proj=tmerc +lat_0=36 +lon_0=139.833333333333 +k=0.9999 +x_0=0 +y_0=0 +ellps=GRS80 +step +proj=unitconvert +xy_in=rad +xy_out=deg
     139.4454        35.9363        0.0000        0.0000
$ echo '-35000 -7000 0 0' | cct +proj=pipeline +step +proj=axisswap +order=2,1 +step +inv +proj=tmerc +lat_0=36 +lon_0=139.833333333333 +k=0.9999 +x_0=0 +y_0=0 +ellps=GRS80 +step +proj=unitconvert +xy_in=rad +xy_out=deg +step +proj=axisswap +order=2,1
      35.6845       139.7560        0.0000        0.0000
```
#### Problem description

With the above example, the axis swap produces a different result in the output.
 
#### Expected Output
The output should be the same regardless of axis swapping.

#### Environment Information
 - PROJ version 6.3.1
 - Ubuntu 18

#### Installation method
 - conda & from source with an older version of master

**Comment by rouault** [comment]
The results seem correct to me. There's no reason that the axisswap applied to input cancels itself with the axisswap of the output. Most projections are not linear transforms :-)

**Comment by snowman2** [comment]
I am not concerned about the order, but the actual values:

- 35.9363 versus 35.6845
- 139.4454 versus 139.7560

This is concerning that they are different.

**Comment by rouault** [comment]
> This is concerning that they are different.

No, this is a relief :-) If you provide the same input, it is expected that you get different output if one pipeline has axis swap and another one, not. The fact that the values are close but different is due to them being close to the false origin of the projection (at ~40 km), so the resulting longitude, latitude are also close of one another. Not sure how to explain this. But this is definitely not a bug.

**Comment by snowman2** [comment]
So, forcing the input/output to be the x,y order can produce different results? Are there more cases where this can happen? If so, mind adding it to the FAQ?

**Comment by snowman2** [comment]
In this case, is it recommended to not do the axis swap?

**Comment by rouault** [comment]
I'm afraid I don't really follow you. PROJ tmerc in inverse direction expect parameters to be in easting, northing order. Either you provide them as such without axis inversion, or you provide them as northing, easting and add axis inversion.

**Comment by snowman2** [comment]
Ohhh, I get it now. 🤦‍♂ Thanks!
