### ISSUE TITLE
cs2cs: +to needed as separator between CRS's when transforming data from a text file

### ISSUE THREAD

**Issue by kbevers** [OSGeo/PROJ#2012]
See output below. The first `cs2cs` call fails, the second works. This should work in both cases. Using `cs2cs` in interactive mode (not supplying the file in the call) works both with and without the `+to`.

```
$ cs2cs EPSG:4908 EPSG:3182 GR96_fiducial_stations_1996.txt
proj_create: unrecognized format / unknown name
Rel. 6.3.1, February 10th, 2020
<cs2cs>:
cannot instantiate source coordinate system
program abnormally terminated

$ cs2cs EPSG:4908 +to EPSG:3182 GR96_fiducial_stations_1996.txt
1603824.25      9428698.27 78.44  NYAL
4122420.81      7431549.82 96.85  KOSG
2666768.82      9189321.17 132.44  TROM
3840319.23      8187884.33 45.55  ONSA
44337.19        8564551.30 54.98  THU1
1874618.79      7435512.89 93.04  REYK
373873.36       5272678.04 152.83  STJO
-2310909.00     8537110.13 180.85  YELL
502406.59       7429978.51 229.85  KELY
-1866998.59     7332959.93 -19.45  CHUR
43406.76        8564807.96 36.03  THU2
770064.59       6741261.69 110.39  QAQ1

$ cat GR96_fiducial_stations_1996.txt
1202430.6554    252626.6607   6237767.5158  NYAL
3899225.2628    396731.8177   5015078.3367  KOSG
2102940.3525    721569.3978   5958192.0896  TROM
3370658.6751    711877.0424   5349786.8520  ONSA
 538981.4378  -1388714.7772   6181005.1119  THU1
2587384.5090  -1043033.4888   5716563.9614  REYK
2612631.2495  -3426807.0112   4686757.7889  STJO
-1224452.4927 -2689216.1022   5633638.2786  YELL
1575559.2989  -1941827.9162   5848076.4816  KELY
-236438.6866  -3307616.7782   5430049.1616  CHUR
 538093.7369  -1389087.9912   6180979.1444  THU2
2170942.2836  -2251829.9231   5539988.2636  QAQ1
```

**Comment by rouault** [comment]
This rings a bell. From my memories, the cs2cs argument parser is quite tricky, and when I allowed the capability to use EPSG codes, while "cs2cs EPSG:XXXX EPSG:YYYY" could be unambiguously parsed, I think it was more tricky to have it accept the coordinate file.

**Comment by kbevers** [comment]
I am sure it is. I bet the optional `+to` separator complicates things a lot. We should consider getting rid of it for 8.0.0.

**Comment by rouault** [comment]
> We should consider getting rid of it for 8.0.0.

Hum, and what about "cs2cs +proj=.... +to +proj=...." use cases ? We want that to still work.

A prelimiiary step would be to list to all existing possibilities offer by cs2cs. And there are quite a lot, including omitting things before the +to or after it, as I discovered, where the missing CRS specification is the geographic CRS corresponding to the one specified, like
```
even@even-i700:~/proj/proj.4/build_autoconf$ src/cs2cs +to +proj=utm +zone=31 +datum=WGS84
3 50
500000.00	5538630.70 0.00

even@even-i700:~/proj/proj.4/build_autoconf$ src/cs2cs +proj=utm +zone=31 +datum=WGS84
500000.00	5538630.70 0.00
3dE	50dN 0.000

even@even-i700:~/proj/proj.4/build_autoconf$ src/cs2cs +proj=utm +zone=31 +datum=WGS84 +to
500000.00	5538630.70 0.00
3dE	50dN 0.000
```

**Comment by kbevers** [comment]
> Hum, and what about "cs2cs +proj=.... +to +proj=...." use cases ? We want that to still work.

Do we really? We should kill those at some point. I'll admit I don't know when that it is, but use of PROJ.4 strings won't go away unless we push people away from it. A soft push could be to start by removing support in cs2cs but still allow PROJ.4 CRS definitions in `proj_create_crs_to_crs`. Just thinking out loud here.

> where the missing CRS specification is the geographic CRS corresponding to the one specified, like

Yeah, I think it would be perfectly fine to remove that behaviour. Explicit is better than implicit, as the Zen of Python says. That is a good dogma to follow in my opinion. I'm willing to break backwards compatibility of sketchy behavior in favour of simplicity. Simplicity both in usage and maintenance.
