### ISSUE TITLE
Documentation: removal of examples having +no_defs

### ISSUE THREAD

**Issue by johanley** [OSGeo/PROJ#2017]
This refers to this doc:
 _PROJ coordinate transformation software library_, Release 7.0.0, Mar 03, 2020

**If** I understand the proj docs correctly, the _+no_defs_ option has been obsolete since v6.0.0. 
But the doc references this non-existent option in 14 examples. 
The first example is at the bottom of page 58:

`PROJ.4 string: +proj=longlat +datum=WGS84 +no_defs +type=crs
`
Should all uses of +no_defs be removed from this doc? 
Or has _+no_defs_ been retained in the examples, to make sure new examples are well-behaved when run against older versions of _proj_? If so, is that explained anywhere in the doc?

**Comment by kbevers** [comment]
`projinfo` will produce PROJ.4 strings that includes `+no_defs`:

```
projinfo EPSG:25832 -o PROJ
PROJ.4 string:
+proj=utm +zone=32 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs +type=crs
```

It does so for legacy reasons. You may get a CRS-type PROJ.4 string from a modern version of PROJ and use it with an older GDAL version (<=2.x). So for those cases the docs are okay, but if `+no_defs` is used in other circumstances it probably should be left out. This will have to be a case-by-case judgment I think.

**Comment by rouault** [comment]
Yes +no_defs is kept on purpose when generating PROJ *4* strings

**Comment by kbevers** [comment]
I've had a quick look around and there are cases of +no_defs are used where it shouldn't be. 

A few examples:

https://proj.org/operations/projections/cass.html
https://proj.org/operations/projections/ccon.html

`git grep +no_defs` reveals a few other similar cases. These should be fixed.
