### ISSUE TITLE
Download grids by bounding box or region name

### ISSUE THREAD

**Issue by snowman2** [OSGeo/PROJ#2028]
I remember seeing something about adding functionality to pre-fetch grids. Potentially by region name or bounding box. Currently I see this for manually downloading files: https://github.com/OSGeo/PROJ/blob/38ec5e662a74d40e02e38dc5dca553c3ecb04356/src/proj.h#L510

Are there plans to add functionality to download grids by a bounding box or by region name?
Also, what about a download all grids method?

**Comment by rouault** [comment]
>  to download grids by a bounding box

Exists as a utility : https://proj.org/apps/projsync.html#cmdoption-projsync-bbox

> by region name

By area of use name: https://proj.org/apps/projsync.html#cmdoption-projsync-area-of-use

No plan from me for now to provide that in the API.

**Comment by snowman2** [comment]
Thanks for the pointers! It looks like I have some reading to do.

> No plan from me for now to provide that in the API.

I hope it will make it there eventually. `pyproj` does not include any of the PROJ command line executables in the wheels. So, this functionality would be entirely missing for users who install `pyproj` that way (I think that is the majority of the users).

**Comment by snowman2** [comment]
Thoughts on surfacing these methods in `proj.h`?
```
// For use by projinfo
std::string PROJ_DLL pj_context_get_url_endpoint(PJ_CONTEXT* ctx);
// For use by projsync
std::string PROJ_DLL pj_context_get_user_writable_directory(PJ_CONTEXT *ctx, bool create);
void PROJ_DLL pj_context_set_user_writable_directory(PJ_CONTEXT* ctx, const std::string& path);
std::string PROJ_DLL pj_get_relative_share_proj(PJ_CONTEXT *ctx);
```
I think with those methods, the `projsync` functionality could be replicated in `pyproj` following the logic in `projsync.cpp`.

**Comment by rouault** [comment]
You'd probably only need pj_context_get_url_endpoint() and pj_context_get_user_writable_directory() if you restrict yourself to downloading to the default user-writable directory

pj_get_relative_share_proj() + pj_context_set_user_writable_directory() are only needed for downloading in system /share/proj.

**Comment by snowman2** [comment]
I am currently planning on replicating all of projsync, but I may be able to get by without these methods. I was thinking keeping them the same would be easier on users. But, I will try it out and implementation and think on it later.
