### ISSUE TITLE
Deb package in Ubuntu 16.04 does not allow installation in foreign architecture

### ISSUE THREAD

**Issue by jonnius** [OSGeo/PROJ#2038]
#### Example of problem
In Ubuntu 16.04 (and probably other Debian-based distros) run:
```
sudo dpkg --add-architecture armhf
sudo apt update
sudo apt install libproj9:armhf
```
**Or** in a more realistic scenario when doing cross-compiling in a docker container through Clickable. Install [Clickable](http://clickable.bhdouglass.com/en/latest/install.html) and then try this little example project:
```
git clone https://gitlab.com/jonnius/proj-demo.git 
cd proj-demo
clickable build -a armhf
```
#### Problem description
`apt-get` fails to install `libproj9:armhf` with the following error message:
```
The following packages have unmet dependencies:
 libproj9:armhf : Depends: proj-data:armhf but it is not installable
```
The package `proj-data` is architecture independent. `libproj9` should not claim that it depends on `proj-data:armhf` but rather `proj-data:all` or simply `proj-data` so it could be installed. Seems like a packaging issue to me.

#### Expected Output
The libproj9 gets installed.

#### Environment Information
 - PROJ version 4.9.2
 - Ubuntu 16.04

#### Installation method
 - apt-get

**Comment by rouault** [comment]
This is (was?) a Ubuntu (Debian?) packaging bug, not a PROJ upstream bug. Closing as invalid here

**Comment by jonnius** [comment]
Could you please point me to the bug tracker where I could report this issue then?

**Comment by rouault** [comment]
https://launchpad.net/ubuntu/+source/gdal

**Comment by jonnius** [comment]
Thanks. I filed the [bug on launchpad](https://bugs.launchpad.net/ubuntu/+source/proj/+bug/1866985).
