### ISSUE TITLE
Running pkg-config --list-all with PROJ installed causes segfault

### ISSUE THREAD

**Issue by volleio** [OSGeo/PROJ#2064]
#### Example of problem
Found this issue [debugging the install of RMagick](https://github.com/rmagick/rmagick/issues/1153#issuecomment-598203790).

Installing PROJ and then running
```c
pkg-config --debug --list-all
```
causes a segfault while `Parsing package file '/usr/local/lib/pkgconfig/proj.pc'`. 
Running
```c
pkg-config --exists --print-errors "proj"
```
results in `Variable 'datarootdir' not defined in '/usr/local/lib/pkgconfig/proj.pc'`. Removing /usr/local/lib/pkgconfig/proj.pc (renaming it to proj.pc.backup) and re-running the `pkg-config --list-all` command succeeds without segfault.

#### Problem description
PROJ shouldn't affect `pkg-config`'s ability to list all packages. 

#### Expected Output
`pkg-config --list-all` should output all of the installed packages in the `pkg-config` pc paths. 

#### Environment Information
 - PROJ version 7.0.0
 - MacOS Catalina 10.15.3 (19D76)
 - pkg-config version 0.29.2

#### Installation method
 - brew install proj

**Comment by hobu** [comment]
> PROJ shouldn't affect `pkg-config`'s ability to list all packages.

Can you past the proj.pc file here too?

`pkg-config` also shouldn't segfault ever 😄, but that's `pkg-config`'s issue

**Comment by volleio** [comment]
Yep, here is my proj.pc contents! 
```c
prefix=/usr/local/Cellar/proj/7.0.0
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include
datadir=${datarootdir}/proj

Name: PROJ
Description: Coordinate transformation software library
Requires:
Version: 7.0.0
Libs: -L${libdir} -lproj
Libs.private: -lsqlite3 -lstdc++
Cflags: -I${includedir}
```

**Comment by hobu** [comment]
hmph, that doesn't look that interesting.

**Comment by mwtoews** [comment]
@volleio I'm unable to recreate the segfault under Ubuntu 18.04, but let's see if #2067 can resolve this issue. Could you try this `proj.pc` file content (the new added line is `datarootdir=${prefix}/share`):
```
prefix=/usr/local/Cellar/proj/7.0.0
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include
datarootdir=${prefix}/share
datadir=${datarootdir}/proj

Name: PROJ
Description: Coordinate transformation software library
Requires:
Version: 7.0.0
Libs: -L${libdir} -lproj
Libs.private: -lsqlite3 -lstdc++
Cflags: -I${includedir}
```

**Comment by volleio** [comment]
@mwtoews that resolved it, thank you!
