### ISSUE TITLE
proj.pc change between 6.3.1 and 7.0.0 breaks packaging

### ISSUE THREAD

**Issue by devrimgunduz** [OSGeo/PROJ#2070]
Hi,

In Proj 6.3,1, the proj.pc includes this line:

`datadir=${prefix}/share/proj`

However, in 7.0.0, it has:

`datadir=${datarootdir}/proj`

...and this breaks SLES-12 builds, because datarootdir is not defined in .pc file.

Any chance we can revert to 6.3.1 version, please?

Thanks!

**Comment by mwtoews** [comment]
Does #2067 resolve the issue?

**Comment by devrimgunduz** [comment]
In theory, yes -- but on SLES-12, when I apply the patch I get this, because automake is 1.13 (or 1.15) there

> + /usr/bin/make -j3
/pghome/pgsql/rpm12testing/BUILD/proj-7.0.0/missing: line 81: automake-1.16: command not found
WARNING: 'automake-1.16' is missing on your system.
         You should only need it if you modified 'Makefile.am' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'automake' program is part of the GNU Automake package:
         <https://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <https://www.gnu.org/software/autoconf>
         <https://www.gnu.org/software/m4/>
         <https://www.perl.org/>

Any ideas how can I skip this?

Regards, Devrim

**Comment by mwtoews** [comment]
With a pristine proj-7.0.0 source with [this patch](https://patch-diff.githubusercontent.com/raw/OSGeo/PROJ/pull/2067.diff), I get this error too on Ubuntu 16.04.

Essentially, you'd need to re-run `./autogen.sh`, which is only part of the repo and not source distribution. And to get a minimal patch, the same versions of various autotools need to be paired (e.g. I see automake 1.16.1 was used). I don't have these tool versions, so can't make a clean looking patch for the source distribution.

**Comment by devrimgunduz** [comment]
Thanks @mwtoews . I'm closing this bug  (found a way to update automake to 1.6 on SLES 12..

**Comment by devrimgunduz** [comment]
Hi,

What is the timeline for 7.0.1? I cannot build 7.0.0 on RHEL  7 (which majority of users run) after applying this patch (automake 1.13 is available there. Need 7.0.1 so that I can push it to the community RPM repositories.

Thanks!

Regards, Devrim

**Comment by mwtoews** [comment]
Currently, the [milestone for 7.0.1](https://github.com/OSGeo/PROJ/milestone/21) is 1 May 2020, set three months after the initial release. Currently there are 19 closed tickets for this milestone. It could be worth discussing on the mail list, as it's a PSC decision to set a release.

**Comment by rouault** [comment]
Closing after the mailing list discussion of thread https://lists.osgeo.org/pipermail/proj/2020-March/009486.html
