### ISSUE TITLE
Update docs - installation still references PROJ4 5.0.1

### ISSUE THREAD

**Issue by serbinsh** [OSGeo/PROJ#2072]
The source code installation instructions here: https://proj.org/install.html still reference an older version of PROJ4, 5.0.1.  This is fine and I would advocate for maintaining install instructions for v5+, v6+, and the newer v7+ versions.  That is because the older v5 don't require certain libs like sqlite, the older datum data, and with 7 now require a new set of *tiff data.  However, because of the mismatch it can be confusing to determine which steps are relevant for which version.

In addition, at least I found it a bit unclear what you are supposed to do with the proj-data-1.0.tar.gz file.  I surmised that I should unpack that in the /data folder based on the approach in v5 and v6 but that wasnt clear.

[now that I submitted I realized this may not be a FR, maybe more a bug?  Wasnt sure since you dont have a docs request]

**Comment by kbevers** [comment]
Right, yes that should be updated. Don't worry about the labels, we'll update them if them don't match.

I wonder if we can do this dynamically with Sphinx? We put the version number in the config, there may be a way to access that from within the text. That would ensure that the most recent versions is mentioned.
