### ISSUE TITLE
libproj not found in standard or give locations

### ISSUE THREAD

**Issue by vwtlin** [OSGeo/PROJ#2093]
Hi 

Thank you all in developing and maintaining PROJ. 

I installed PROJ 7.0.0 via homebrew in macOS Catalina. Then I tried to install package 'sf' but it comes up with this error. I will be grateful if you could provide any advice to solve this problem. 

![libproj](https://user-images.githubusercontent.com/44833405/77605532-28280680-6f50-11ea-8a2a-7d859d383dd6.jpg)

**Comment by rouault** [comment]
This should be reported to homebrew and/or sf. This is not a PROJ issue
