### ISSUE TITLE
Use PROJ_SOURCE_DIR instead of CMAKE_SOURCE_DIR in CMake files

### ISSUE THREAD

**Issue by SpaceIm** [OSGeo/PROJ#2094]
#### Problem description

If wrapped into another CMakeLists, CMAKE_SOURCE_DIR does not point to what PROJ expect.
For example `include_directories(${CMAKE_SOURCE_DIR}/include)` in lib_proj.cmake would be incorrect in this case.

**Comment by mwtoews** [comment]
Thanks, further docs on  [`PROJ_SOURCE_DIR` are here](https://cmake.org/cmake/help/v3.9/variable/PROJECT-NAME_SOURCE_DIR.html), I'll take a look.
