### ISSUE TITLE
Wrong grids file name in esri.sql

### ISSUE THREAD

**Issue by PedroVenancio** [OSGeo/PROJ#2096]
esri.sql (https://raw.githubusercontent.com/OSGeo/PROJ/master/data/sql/esri.sql) file makes reference of Portuguese grid files with wrong names.

```
INSERT INTO "grid_transformation" VALUES('ESRI','108023','Datum_Lisboa_Hayford_To_WGS_1984_NTv2',NULL,NULL,'EPSG','9615','NTv2','ESRI','104106','EPSG','4326','EPSG','1294',0.1,'EPSG','8656','Latitude and longitude difference file','portugal/DLX_ETRS89_geo',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
INSERT INTO "grid_transformation" VALUES('ESRI','108024','Datum_Lisboa_Hayford_To_ETRS_1989_NTv2',NULL,NULL,'EPSG','9615','NTv2','ESRI','104106','EPSG','4258','EPSG','1294',0.1,'EPSG','8656','Latitude and longitude difference file','portugal/DLX_ETRS89_geo',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
INSERT INTO "grid_transformation" VALUES('ESRI','108025','Datum_73_To_WGS_1984_NTv2',NULL,NULL,'EPSG','9615','NTv2','EPSG','4274','EPSG','4326','EPSG','1294',0.1,'EPSG','8656','Latitude and longitude difference file','portugal/D73_ETRS89_geo',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
```
**portugal/DLX_ETRS89_geo** and **portugal/D73_ETRS89_geo**

instead of 

**DLx_ETRS89_geo.gsb** and **D73_ETRS89_geo.gsb**

So, when using some layers in ESRI:102165, ESRI:102164 or ESRI:102161, for instance, in QGIS, it always show a message saying that the .gsb or .tif (PROJ 6 or PROJ 7) grid files are not present.

Updating the proj.db with

```
update grid_transformation
set grid_name = 'DLx_ETRS89_geo.gsb'
where grid_name = 'portugal/DLX_ETRS89_geo'

update grid_transformation
set grid_name = 'D73_ETRS89_geo.gsb'
where grid_name = 'portugal/D73_ETRS89_geo'
```
solves the problem locally, and I would like to update https://raw.githubusercontent.com/OSGeo/PROJ/master/data/sql/esri.sql accordingly, but the header of this file says:

`--- This file has been generated by scripts/build_db_from_esri.py. DO NOT EDIT !`

Is there a way to solve this issue in PROJ, without changing esri.sql?

A related issue is that these grid files were created to reproject from DLx and D73 to ETRS89, not WGS84. Anyway, it's a fair aproximation. But it lacks the correct transformation from D73 to ETRS89. Can I create a new entry like:
```
INSERT INTO "grid_transformation" VALUES('ESRI','108473','Datum_73_To_ETRS_1989_NTv2',NULL,NULL,'EPSG','9615','NTv2','EPSG','4274','EPSG','4258','EPSG','1294',0.1,'EPSG','8656','Latitude and longitude difference file','D73_ETRS89_geo.gsb',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
```
?

Thank you very much!

**Comment by rouault** [comment]
You may need to add an entry in data/sql/grid_alternatives.sql to map the ESRI grid name to the PROJ one

**Comment by PedroVenancio** [comment]
Hi @rouault 

Something like

```
INSERT INTO grid_alternatives(original_grid_name,
                              proj_grid_name,
                              proj_grid_format,
                              proj_method,
                              inverse_direction,
                              package_name,
                              url, direct_download, open_license, directory)
                      VALUES ('portugal/DLX_ETRS89_geo',
                              'DLx_ETRS89_geo.gsb',
                              'NTv2',
                              'hgridshift',
                              0,
                              'proj-datumgrid-europe',
                              NULL, NULL, NULL, NULL);
```

```
INSERT INTO grid_alternatives(original_grid_name,
                              proj_grid_name,
                              proj_grid_format,
                              proj_method,
                              inverse_direction,
                              package_name,
                              url, direct_download, open_license, directory)
                      VALUES ('portugal/D73_ETRS89_geo',
                              'D73_ETRS89_geo.gsb',
                              'NTv2',
                              'hgridshift',
                              0,
                              'proj-datumgrid-europe',
                              NULL, NULL, NULL, NULL);
```
in 6.3 branch, and

```
-- Portugal
('portugal/DLX_ETRS89_geo','pt_dgt_DLx_ETRS89_geo.tif','portugal/DLX_ETRS89_geo','GTiff','hgridshift',0,NULL,'https://cdn.proj.org/pt_dgt_DLx_ETRS89_geo.tif',1,1,NULL),
('portugal/D73_ETRS89_geo','pt_dgt_D73_ETRS89_geo.tif','portugal/D73_ETRS89_geo','GTiff','hgridshift',0,NULL,'https://cdn.proj.org/pt_dgt_D73_ETRS89_geo.tif',1,1,NULL),
```
in master branch?

**Comment by rouault** [comment]
For master, should likely be the following (I changed the values in the 3rd column to be the .gsb filenames)
```
-- Portugal
('portugal/DLX_ETRS89_geo','pt_dgt_DLx_ETRS89_geo.tif','DLx_ETRS89_geo.gsb','GTiff','hgridshift',0,NULL,'https://cdn.proj.org/pt_dgt_DLx_ETRS89_geo.tif',1,1,NULL),
('portugal/D73_ETRS89_geo','pt_dgt_D73_ETRS89_geo.tif','D73_ETRS89_geo.gsb','GTiff','hgridshift',0,NULL,'https://cdn.proj.org/pt_dgt_D73_ETRS89_geo.tif',1,1,NULL),
```

**Comment by PedroVenancio** [comment]
Thank you very much @rouault !

About the possible new entry

```
INSERT INTO "grid_transformation" VALUES('ESRI','108473','Datum_73_To_ETRS_1989_NTv2',NULL,NULL,'EPSG','9615','NTv2','EPSG','4274','EPSG','4258','EPSG','1294',0.1,'EPSG','8656','Latitude and longitude difference file','D73_ETRS89_geo.gsb',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
```

where should be inserted? data/sql/grid_transformation_custom.sql maybe?

**Comment by rouault** [comment]
> INSERT INTO "grid_transformation" VALUES('ESRI','108473','Datum_73_To_ETRS_1989_NTv2',NULL,NULL,'EPSG','9615','NTv2','EPSG','4274','EPSG','4258','EPSG','1294',0.1,'EPSG','8656','Latitude and longitude difference file','D73_ETRS89_geo.gsb',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);

Why ESRI:108473 ? It doesn't come from ESRI, and this entry doesn't seem needed at all as EPSG:4274 and EPSG:4258 are already linked together by tranformation EPSG:6189 "Datum 73 to ETRS89 (6)"

**Comment by PedroVenancio** [comment]
> 
> 
> > INSERT INTO "grid_transformation" VALUES('ESRI','108473','Datum_73_To_ETRS_1989_NTv2',NULL,NULL,'EPSG','9615','NTv2','EPSG','4274','EPSG','4258','EPSG','1294',0.1,'EPSG','8656','Latitude and longitude difference file','D73_ETRS89_geo.gsb',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0);
> 
> Why ESRI:108473 ? It doesn't come from ESRI, and this entry doesn't seem needed at all as EPSG:4274 and EPSG:4258 are already linked together by tranformation EPSG:6189 "Datum 73 to ETRS89 (6)"

You're completely right @rouault thank you very much!
