### ISSUE TITLE
Difference between two geoids not computed if they don't refer to the same GeographicCRS

### ISSUE THREAD

**Issue by jjimenezshaw** [OSGeo/PROJ#2115]
#### Example of problem
If I run this transformation between geoids 5773 and 5732 (Belfast height), the z value does not change
`echo 54 -7 0 | ./cs2cs EPSG:4326+5773 EPSG:4258+5732 -f "%.3f"` ==> `54.000	-7.000 0.000`

However those geoids are not exactly the same. (you can check easily in https://cdn.proj.org/ clicking in the area. the "geoid undulation" is not the same)

If I use an intermediate step, `EPSG:4979` for instance, I get a small change in `z`:
`echo 54 -7 0 | ./cs2cs EPSG:4326+5773 EPSG:4979 -f "%.3f" | ./cs2cs EPSG:4979 EPSG:4258+5732 -f "%.3f"` ==> `54.000	-7.000 -0.148`

The same is noticeable with NAVD88
`echo 40 -80 0 | ./cs2cs EPSG:4326+3855 EPSG:4269+5703 -f "%.3f"` ==> `40.000	-80.000 0.000`
while using EPSG:4269 as intermediate step we get a difference:
`echo 40 -80 0 | ./cs2cs EPSG:4326+3855 EPSG:4269 -f "%.3f" | ./cs2cs EPSG:4269 EPSG:4269+5703 -f "%.3f"` ==> `40.000	-80.000 -0.794`

What is wrong here? Why is not computing the direct transformation, but it does with an intermediate step?

I've notice that between 5773 and 3855 it does it directly
`echo 54 -7 0 | ./cs2cs EPSG:4326+5773 EPSG:4258+3855 -f "%.3f"` ==> `54.000	-7.000 -0.365`

#### Problem description
I don't know why there is a different output using that simple intermediate step. And why in other cases it does work.

#### Expected Output
Different `z` value due to different geoids. See above

#### Environment Information
 - PROJ version (`proj`): 7.0.0 
 - Operation System Information: Ubunut 18.04

#### Installation method
Compiled from source (tag 7.0.0 patched with 64946ab) with CMake. curl was disabled. Datumgrids cloned from github (PROJ-data)

**Comment by rouault** [comment]
> Why is not computing the direct transformation, but it does with an intermediate step?

I believe it is a limitation of the createOperations() logic. If the 2 vertical CRS that have geoid models do not refer to the same geographic CRS, createOperations() is lost. For 5773 (EGM96) <--> 3855 (EGM2008), they both have geoid models that refer to EPSG:4326.
Whereas the geoid model for EPSG:5732 (Belfast height) refer to ETRS89

**Comment by jjimenezshaw** [comment]
If I use the `proj4` notation to define the CS, then it works.
`echo -7 54 0 | ./cs2cs "+proj=longlat +datum=WGS84 +no_defs +geoidgrids=egm96_15.gtx" "+proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs  +geoidgrids=OSGM15_Belfast.gtx" -f "%.3f"` ==> `-7.000 54.000 -0.148`
(copied from https://github.com/OSGeo/gdal/issues/1836#issuecomment-531154187)

I don't want to use `proj4` notation. I just want to understand how it behaves.
