### ISSUE TITLE
proj.4 and proj.7: EPGS:2169 (LUREF) projection is off by some 150 meters

### ISSUE THREAD

**Issue by AlainKnaff** [OSGeo/PROJ#2120]
Having to bulk-convert a lot of geographic coordinates from latitude/longitude into LUREF (EPGS:2169), I first tried proj4 (Debian 10 package) and used the following invocation:

proj +init=epsg:2169 <<EOF
5.980380 50.155478
EOF

... and got 66686.53 135849.72

However, the correct answer would be 66582 135730 (as returned by https://geoportail.lu and https://epsg.io). The answer given by proj is some 150m off!

Then I tried proj7 (downloaded from your site and compiled), and it has the same issue.

**Comment by kbevers** [comment]
You are using old deprecated PROJ.4 syntax which is inaccurate and bound to go wrong. Get up to speed with PROJ >6 idioms and you'll be fine:

```
echo 50.155478 5.980380 | cs2cs EPSG:4326 EPSG:2169
135730.12       66582.28 0.00
```

Note the swapped order of the input coordinate. PROJ now respects the axis order for CRS's as defined   in the EPSG registry.

**Comment by AlainKnaff** [comment]
This works, thanks for your quick answer :-)

Any idea why the old syntax is still available without warning?
