### ISSUE TITLE
Proj 7 doesn't look for tiff grids in proj_context_set_search_paths

### ISSUE THREAD

**Issue by nyalldawson** [OSGeo/PROJ#2121]
Steps to reproduce:

1. Move or rename the pt_dgt_DLx_ETRS89_geo.tif from all proj system paths
2. Create an empty folder, put the pt_dgt_DLx_ETRS89_geo.tif file within it
3. Use proj_context_set_search_paths to set a search path to the new folder with the .tif file
4. Try to use proj_create to create the operation which requires the tif grid, e.g. `+proj=pipeline +step +inv +proj=tmerc +lat_0=39.6666666666667 +lon_0=1 +k=1 +x_0=0 +y_0=0 +ellps=intl +pm=lisbon +step +proj=hgridshift +grids=pt_dgt_DLx_ETRS89_geo.tif +step +proj=tmerc +lat_0=39.6682583333333 +lon_0=-8.13310833333333 +k=1 +x_0=0 +y_0=0 +ellps=GRS80`

The result is null, vs a valid transform when the tif file is present in the proj default search paths

**Comment by rouault** [comment]
I do *NOT* reproduce with the following executable, run from the build dir of PROJ, and with the grid installed in /tmp
```
#include <stdio.h>
#include "proj.h"

int main()
{
    const char* const paths [] = { "/tmp", "data" };
    PJ_CONTEXT* ctx = proj_context_create();
    proj_context_set_search_paths(ctx, 2, paths);
    PJ* pj = proj_create(ctx, "+proj=pipeline +step +inv +proj=tmerc +lat_0=39.6666666666667 +lon_0=1 +k=1 +x_0=0 +y_0=0 +ellps=intl +pm=lisbon +step +proj=hgridshift +grids=pt_dgt_DLx_ETRS89_geo.tif +step +proj=tmerc +lat_0=39.6682583333333 +lon_0=-8.13310833333333 +k=1 +x_0=0 +y_0=0 +ellps=GRS80");
    PJ_COORD c;
    c.xy.x = 1000;
    c.xy.y = 1000;
    c = proj_trans(pj, PJ_FWD, c);
    printf("%f %f\n", c.xy.x, c.xy.y);
    return 0;
}
```
```
$ LD_LIBRARY_PATH=src/.libs ./mytest 
1000.993133 1001.535009
```

(This even works with the search paths containing only /tmp, but with a warning about proj.db not being found)

**Comment by nyalldawson** [comment]
Hmmmm, I'll give that script a test tomorrow and see what happens locally ...

**Comment by nyalldawson** [comment]
Confirmed not an proj issue
