### ISSUE TITLE
EPSG_CODE_METHOD_MERCATOR_VARIANT_C (2SP)

### ISSUE THREAD

**Issue by Vasshus** [OSGeo/PROJ#2137]
Porposing to have Mercator variant C method included in Proj
This is IOGP method "[urn:ogc:def:method:EPSG::1044](https://epsg.io/1044-method.gml)"

[IOGP Publication 373-7-2](http://www.epsg.org/Portals/0/373-07-2.pdf)

**Comment by rouault** [comment]
Why ? This method isn't used in practice in the EPSG dataset.

**Comment by Vasshus** [comment]
The reason is that we have data defined with this CRS that need to be projected to other CRS using Mercator Variant C.
E.G:
PROJCRS["WGS84_Mercator_Trinidad",
  BASEGEODCRS["WGS 84",
    DATUM["World Geodetic System 1984",
      ELLIPSOID["WGS 84",6378137,298.257223563,LENGTHUNIT["metre",1.0]]]],
  CONVERSION["Mercator_variantC_CM58W_11N",
    METHOD["Mercator (variant C)",ID["EPSG",1044]],
    PARAMETER["Latitude of 1st standard parallel",6.64456744726493,ANGLEUNIT["degree",0.01745329252]],
    PARAMETER["Longitude of natural origin",-58,ANGLEUNIT["degree",0.01745329252]],
    PARAMETER["Latitude of false origin",11,ANGLEUNIT["degree",0.01745329252]],
    PARAMETER["Easting at false origin",0,LENGTHUNIT["metre",1.0]],
    PARAMETER["Northing at false origin",0,LENGTHUNIT["metre",1.0]]],
  CS[cartesian,2],
    AXIS["easting (E)",east,ORDER[1]],
    AXIS["northing (N)",north,ORDER[2]],
    LENGTHUNIT["metre",1.0],
  ID["COMPANY",200000]]

**Comment by rouault** [comment]
Interesting. If you're interested in contracting someone to implement this, see my contact at http://www.spatialys.com/en/contact/

**Comment by Vasshus** [comment]
Blue Marble - Geographic Calculator and ArcMap handles this for us currently, I was just hoping this to be available in PROJ as well :) Time will show what we will do.

**Comment by rouault** [comment]
> Wasn't this fixed by [b8db250#diff-9ffc43dcef9e80862f62f4a9637c9d96](https://github.com/OSGeo/PROJ/commit/b8db2500285e3d4feaa5778ec7fa888bd6c6a479#diff-9ffc43dcef9e80862f62f4a9637c9d96)?

No, this commit does the mapping between OGC names and ESRI names, but the main item for practical use is missing: mapping from the OGC WKT to a PROJ string. It isn't completely trivial since it would require either morphing parameters of variant C to variant A/B or implementing a +variant=C in +proj=merc
