### ISSUE TITLE
Building problem of Proj7 in Visual Studio 2017 Pro

### ISSUE THREAD

**Issue by himsve** [OSGeo/PROJ#2140]
I'm using Visual Studio 2017 Pro for compiling and building Proj. But the cmake building in Visual Studio fails due to missing TIFF and Curl linking (library and include).

Output from VS:
 
`Call Stack (most recent call first):
  CMakeLists.txt:120 (include)
CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find TIFF (missing: TIFF_LIBRARY TIFF_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.12/Modules/FindTIFF.cmake:69 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:151 (find_package)`

TIFF and CURL are failing in calls find_package(TIFF REQUIRED) and find_package(CURL REQUIRED).

For me it seems that TIFF and CURL libraries are not included in ordinary VS installations. 

It is possible to include TIFF and CURL libraries the same way as Sqlite3 (FindSqlite3.cmake)?

By the way: proj7 building works fine with vcpkg in Windows. 👍

**Comment by rouault** [comment]
https://proj.org/install.html#compilation-and-installation-from-source-code gives build instructions for windows
