### ISSUE TITLE
CRS PROJ string and WKT form based on PROJ string not equivalent for bound CRS

### ISSUE THREAD

**Issue by snowman2** [OSGeo/PROJ#2149]
#### Example of problem
Related: https://github.com/pyproj4/pyproj/issues/598

When comparing a PJ* based on the PROJ string with it's equivalent PJ* based on the WKT form are not seen as equivalent. 

Pseduo code:
```c
crs = proj_create(NULL, "+proj=lcc +lat_1=51.16666723333333 +lat_2=49.8333339 +lat_0=90 +lon_0=4.367486666666666 +x_0=150000.013 +y_0=5400088.438 +ellps=intl +towgs84=106.869,-52.2978,103.724,-0.33657,0.456955,-1.84218,1 +units=m +no_defs");
wkt = proj_as_wkt(NULL, crs, PJ_WKT2_2018, NULL);
crs_wkt = proj_create(NULL, wkt);
equivalent = proj_is_equivalent_to(crs, crs_wkt, PJ_COMP_EQUIVALENT);
```
The result says the CRS are not equivalent. However, the `source_crs`, `target_crs`, and `coordinate_operation` are seen as equivalent (ref: https://github.com/pyproj4/pyproj/issues/598#issuecomment-613156636).

#### Environment Information
 - PROJ version 6.3.1 + 7.0.0
 - macOS-10.15.3-x86_64-i386-64bit & Linux-4.15.0-96-generic-x86_64-with-glibc2.10

#### Installation method
 - conda & python wheel

**Comment by rouault** [comment]
@snowman2 I can't reproduce with master or latest state of 6.3 and 7.0 branches:

Given eq.c
```
#include <stdio.h>
#include "proj.h"

int main()
{
    PJ* crs = proj_create(NULL, "+proj=lcc +lat_1=51.16666723333333 +lat_2=49.8333339 +lat_0=90 +lon_0=4.367486666666666 +x_0=150000.013 +y_0=5400088.438 +ellps=intl +towgs84=106.869,-52.2978,103.724,-0.33657,0.456955,-1.84218,1 +units=m +no_defs");
    const char* wkt = proj_as_wkt(NULL, crs, PJ_WKT2_2018, NULL);
    PJ* crs_wkt = proj_create(NULL, wkt);
    int equivalent = proj_is_equivalent_to(crs, crs_wkt, PJ_COMP_EQUIVALENT);
    printf("%d\n", equivalent);
    return 0;
}
```
`gcc eq.c -o eq -I../src -Lsrc/.libs -lproj && LD_LIBRARY_PATH=src/.libs ./eq` outputs 1

**Comment by snowman2** [comment]
Thanks for trying this out. I will try it out with the latest version and see if I can match what you find.

**Comment by snowman2** [comment]
Whoops, I forgot to add `+type=crs`. With that added, it returns False:

```c
#include <stdio.h>
#include "proj.h"

int main()
{
    PJ* crs = proj_create(NULL, "+proj=lcc +lat_1=51.16666723333333 +lat_2=49.8333339 +lat_0=90 +lon_0=4.367486666666666 +x_0=150000.013 +y_0=5400088.438 +ellps=intl +towgs84=106.869,-52.2978,103.724,-0.33657,0.456955,-1.84218,1 +units=m +no_defs +type=crs");
    const char* wkt = proj_as_wkt(NULL, crs, PJ_WKT2_2018, NULL);
    PJ* crs_wkt = proj_create(NULL, wkt);
    int equivalent = proj_is_equivalent_to(crs, crs_wkt, PJ_COMP_EQUIVALENT);
    printf("%d\n", equivalent);
    return 0;
}
```

**Comment by rouault** [comment]
OK, this has nothing to do with BoundCRS. Can be reproduced too by removing the +towgs84 with a plain ProjectedCRS.
The reason is due to ambiguous axis order for the GeographicCRS base of the ProjectedCRS. When instanciating a CRS from a PROJ string, the GeographicCRS is created with lon, lat order, but when instanciating from WKT when the AXIS are not mentionned, lat, lon order is assumed.

Instead of PJ_COMP_EQUIVALENT, you can use PJ_COMP_EQUIVALENT_EXCEPT_AXIS_ORDER_GEOGCRS if you don't care about that difference.

**Comment by snowman2** [comment]
> The reason is due to ambiguous axis order for the GeographicCRS base of the ProjectedCRS. When instanciating a CRS from a PROJ string, the GeographicCRS is created with lon, lat order, but when instanciating from WKT when the AXIS are not mentionned, lat, lon order is assumed.

Does it make sense to add the axis information when exporting to a WKT for consistency?

**Comment by rouault** [comment]
> Does it make sense to add the axis information when exporting to a WKT for consistency?

This isn't allowed by the WKT grammar: http://docs.opengeospatial.org/is/18-010r7/18-010r7.html#71

**Comment by rouault** [comment]
An alternative when you compare 2 CRS would be to export them to WKT, instanciate 2 new CRS from that, and use proj_is_equivalent_to() on them.

**Comment by snowman2** [comment]
@rouault thanks for the info on this. Sounds like this is a `gotcha` that would be useful to have documented so others are aware of the behavior and that is expected.

Essentially what you said translated to `pyproj`:
```python
>>> from pyproj import CRS
>>> crs = CRS("+proj=lcc +lat_1=51.16666723333333 +lat_2=49.8333339 +lat_0=90 +lon_0=4.367486666666666 +x_0=150000.013 +y_0=5400088.438 +ellps=intl +towgs84=106.869,-52.2978,103.724,-0.33657,0.456955,-1.84218,1 +units=m +no_defs")
>>> crs_wkt = CRS(crs.to_wkt())
>>> crs == crs_wkt
False
>>> crs.equals(crs_wkt, ignore_axis_order=True)
True
>>> crs_wkt == CRS(crs_wkt.to_wkt())
True
```
