### ISSUE TITLE
Invalid values in inverse projections for Eckert IV

### ISSUE THREAD

**Issue by pnuu** [OSGeo/PROJ#2152]
#### Example of problem
```bash
$ invproj +proj=eck4 +a=6371000
-16921202.922943164 -8313010.558165222
54d35'17.571"E	81d47'15.153"S
```
```bash
$ proj +proj=eck4 +a=6371000
54d35'17.571"E	81d47'15.153"S
3024435.50	-8313010.56
```
#### Problem description
The first pair of x/y coordinates above are the bottom-left (South-Western) extent limits for the Eckert IV projection, and these values should be invalid. As seen from the second (forward) projection, the results from the inverse projection map to different (correct) location.

These PRs seem to be related, as the projections are of similar type with invalid regions in the corners:
https://github.com/OSGeo/PROJ/pull/304
https://github.com/OSGeo/PROJ/pull/2151

And this issues visualizes what happens when remapping to Eckert IV:
https://github.com/pytroll/pyresample/issues/266

Pyresample uses `pyproj` which in turn calls `PROJ`.

#### Expected Output
The expected result from the call to `invproj` should give an invalid result.

#### Environment Information
 - PROJ versions tested: 4.9.3 (from Ubuntu) and 7.0.0 (from conda-forge and compiled from source)
 - Linux (Ubuntu 18.04 LTS)

#### Installation method
 - Installation tested from conda, apt-get and by compiling the source code from GitHub.

**Comment by imshuv** [comment]
I want to work on this issue and part of this organization can someone please suggest me how should I get started?
