### ISSUE TITLE
gie accepts invalid keywords without noticing

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#2158]
I just accidentally noticed that I mispelled "roundtrip" as "roundrip" and gie didn't warn me... Similarly I frequently mispell "expect" as "except".

I think gie should error out when it encounters a keyword it doesn't understand. This would imply to revise existing gie files to properly add comment markers in front of some comment text that isn't marked as such currently

**Comment by busstoptaktik** [comment]
As `gie` is a generic fault entirely attributable to me, I think it is relevant to note that this is actually by design: I wanted it to be insanely easy to document what you wanted to achieve with a given test, and hence making anything not explicitly a keyword a comment.

I do, however, feel your pain (especially since I have numerous times misspelled your family name as either Ruoault, Ruoualt, or any other remotely imaginable permutation, for which I hope for forgiveness), and agree that perhaps the bright idea of making comments the primary data type was probably not as bright as it seemed a few years back...

**Comment by kbevers** [comment]
RTFM :-)
![image](https://user-images.githubusercontent.com/13132571/79542398-daed0f80-808b-11ea-8452-cfd32d6e9067.png)

For some strange reason I like the loose format of the gie file, so I would not be super happy about changing behaviour. But we could raise some warnings when a line starts with common misspellings of keywords, for instance "except" and "roundrip".

**Comment by busstoptaktik** [comment]
@kbevers said:
> For some strange reason I like the loose format of the gie file

@rouault,  one of the "strange" reasons for liking the loose format is that it makes `gie` a quite capable teaching tool for PROJ syntax - cf. e.g. [this](https://github.com/kbevers/PROJTutorial/blob/master/exercises/conversions.gie) example from a PROJ workshop arranged by @kbevers about a year ago.

**Comment by rouault** [comment]
Relying on common misspelling is not going to be very useful. I'm pretty sure the creativity in this domain is unbounded.
I was thinking that an optional @strict keyword around the top of the file (or perhaps a -strict switch on the command line?) could offer the best (or worse) of both worlds. For PROJ test .gie files we could use that for example.

**Comment by kbevers** [comment]
> Relying on common misspelling is not going to be very useful. I'm pretty sure the creativity in this domain is unbounded.

I would try to identify misspellings by looking at the Levenshtein distance between the first word of each line and the list of keywords. If the distance is close to a match I would print a warning.

A strict switch could work as well. In that case we need a way to add comments, like prefixing with # or whatever. There's a lot of freestyle text in the existing gie files that would fail with a strict setting turned on.

**Comment by busstoptaktik** [comment]
> I was thinking that an optional @strict keyword around the top of the file

Since `<gie>` identifies the start of the test material, we could simply have a `<gie-strict>` token instead. This would ensure that a non-strict-enabled version of GIE would entirely ignore the material.

**Comment by busstoptaktik** [comment]
> In that case we need a way to add comments

IIRC, '#' style comments are already ignored, as GIE calls `pj_chomp()` on the input
