### ISSUE TITLE
Crash during sqlite.exe call from PROJ

### ISSUE THREAD

**Issue by portos53** [OSGeo/PROJ#2169]
Hello !

I create this issue here because I think the origin of the crash can come from an issue in PROJ. 

I'm currently using:
- GDAL 3.0.4
- PROJ 7.0.0
- SQLite 3.31.1
- under Windows 10 x64.

I build myself all this libraries and their dependencies from the sources with Visual Studio 12 2017.

I tried to use in GDAL in my software which used previously:
- GDAL 2.2.2
- PROJ 4.9.3
- SQLite 3.7.9

When I called OGRSpatialReference::importFromEPSG: I've got an lru11::KeyNotFound then access violation.

The call stack give that: 
> 000000000026a130()
> sqlite3.exe!00007ff7c71ccb99()
> sqlite3.exe!00007ff7c72c36ce()
> sqlite3.exe!00007ff7c71d89fe()
> proj_7_0.dll!00007ffdd1d8b63d()
> proj_7_0.dll!00007ffdd1ece76e()
> proj_7_0.dll!00007ffdd1eab0e4()
> proj_7_0.dll!00007ffdd1ed2933()
> proj_7_0.dll!00007ffdd1ed2825()
> proj_7_0.dll!00007ffdd1ee2148()
> gdal300.dll!00007ffddaf6f99d()

I decided also to test directly PROJ from the executables. All my tests of the command line samples of PROJ executables return without rpint anything in the command prompt, even with the PROJ_DEBUG at 3.

I know this is very few informations to diagnostic but I can't get more things than that. 

Can you help me to understand this crash, please ? Or perhaps I missed something for the compilation options.

I saw this post : https://github.com/OSGeo/PROJ/issues/1932#issuecomment-592495456 but it didn't solve the issue.

Any help would be greatly appreciated !

**Comment by rouault** [comment]
I'd suggest you try with a pre-built sqlite3 dll, such as coming with vcpkg or conda

**Comment by portos53** [comment]
Good suggestion ! Thank you ! I still don't know what was missing in my SQLite3 build options but the conda package will be good for our usage.
