### ISSUE TITLE
Integration of NADCON5 grids & transformation methods

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#2194]
https://www.ngs.noaa.gov/NADCON5/index.shtml supersedes NADCON4 grid currently handled. One particularity of NADCON5 grids is that some of them combine lon, lat shift + ellipsoidal height shift

**Comment by ValZapod** [comment]
https://community.esri.com/t5/coordinate-reference-systems-questions/ncat-vs-arcmap-coordinate-conversions/m-p/799628

**Comment by kbevers** [comment]
@rouault is this still relevant?

**Comment by rouault** [comment]
> is this still relevant?

I guess it could, but nobody seems to have a pressing need for that up to now

**Comment by kbevers** [comment]
Let's close it until someone actually needs it. I'd say that the grid format is irrelevant to PROJ as we can just convert to GTG or a defmodel configuration. The transformation methods will probably be described in EPSG eventually at which point we can implement them if needed

**Comment by rouault** [comment]
Re-opening as I've got funding to work on this.

@kbevers A number of the NADCON5 grids contain shifts in longitude, latitude and ellipsoidal height. For performance reasons, we want to be able to apply the horizontal & vertical shifts within the same PROJ operation. I was wondering if I should add a "hvgridshift" operation that would be hgridshift + vgridshift, or extend the existing "hgridshift" to be able to apply the vertical shift as well. For the later option, there are 2 alternatives: either automatically apply the vertical shift when there's a vertical shift component in the grid, or require an explicit +vshift boolean switch to enable it.
Any preference ? I'm slightly leaning towards on a new "hvgridshift" operation, as being the most consistent with how we have dealt with things up to now. My only concern is the proliferation of similar looking operations.

**Comment by kbevers** [comment]
>  I'm slightly leaning towards on a new "hvgridshift" operation, as being the most consistent with how we have dealt with things up to now. My only concern is the proliferation of similar looking operations.

Yeah, I think a new operation is the best option. It could also just be called `gridshift`. Depending on the  implementation it might even be possible to have it be able to do the jobs of `hgridshift` and `vgridshift`, so that they can be thin wrappers for `gridshift`. Idea here of course being to share as much code as possible between the three operations. If that's possible. Not should exactly what's required for NADCON5.

**Comment by ValZapod** [comment]
>Re-opening as I've got funding to work on this.

This is great. Meanwhile WGS84 moved to G2238 on 27 November, BTW full support of its IGS20 requires ANTEX (.atx) files parsing, including new for ITRF2020 post-seismic deformations. See https://igs.org/news/igs20/ 

https://files.igs.org/pub/station/general/igs20.atx
https://lists.igs.org/pipermail/igsmail/2022/008234.html
