### ISSUE TITLE
Height not converted fom EPSG:4979 to EPSG:4150 when target promoted to 3D and bound to WGS84

### ISSUE THREAD

**Issue by hernando** [OSGeo/PROJ#2202]
#### Example of problem

When using cs2cs to convert from a EPSG:4979 to EPSG:4150 (which have a different ellipsoid) after it has been promoted to 3D, heights are not converted if the target CRS is bound to WGS84.
```
p="46.5173732 6.561943 400"
echo $p | cs2cs EPSG:4979 "$(projinfo -o WKT2:2019 -q --3d EPSG:4150)"
46d31'7.143"N   6d33'45.909"E 348.578
echo $p | cs2cs EPSG:4979 "$(projinfo -o WKT2:2019 -q --3d EPSG:4150 --boundcrs-to-wgs84)"
46d31'7.143"N   6d33'45.909"E 400.000
```
The same thing happens if I take a WKT1 string and edit it manually to add the third axis and then test with/without TOWGS84.

Interestingly, this problem doesn't show up with OSGB36 (EPSG:4277), which is also based on a different ellipsoid. **But**, only if the path to the horizontal grid file is not given:
```
p="49.96006137820 -5.20304609998 124.269"
echo $p | cs2cs EPSG:4979 "$(projinfo -o WKT2:2019 -q --3d EPSG:4277 --boundcrs-to-wgs84)"
49d57'33.983"N  5d12'7.435"W 74.217
echo $p | cs2cs EPSG:4979 "$(projinfo -o WKT2:2019 -q --3d EPSG:4277)"
49d57'33.983"N  5d12'7.435"W 74.217
```
When the path to the horizontal grid file is given, the height is not transformed:
```
export PROJ_LIB=paths to proj.db and uk_os grid files
echo $p | cs2cs EPSG:4979 "$(projinfo -o WKT2:2019 -q --3d EPSG:4277 --boundcrs-to-wgs84)"
49d57'34.032"N  5d12'7.243"W 124.269
echo $p | cs2cs EPSG:4979 "$(projinfo -o WKT2:2019 -q --3d EPSG:4277)"
49d57'34.032"N  5d12'7.243"W 124.269
```
I've just discovered this one while making tests comparing OSGB36 and CH1903+ for the sake of this ticket (maybe I should change the title...)

#### Problem description

When working with 3D CRS, the height should always be transformed regardless of:
* The presence of TOWGS84 in WKT1 or the usage of BOUNDCRS in WKT2.
* The usage of grid files in the horizontal transformation.

#### Expected Output
For CH1903+ the output height should always be 348.578.
For OSGB36 the output height should always be 74.217.

#### Environment Information
 - PROJ origin/master
 - Ubuntu 18.04 64bit

#### Installation method
 - Compiled from source

**Comment by rouault** [comment]
More details in https://github.com/OSGeo/gdal/issues/2454

**Comment by rouault** [comment]
> When working with 3D CRS, the height should always be transformed regardless of:
>     * The usage of grid files in the horizontal transformation.

I don't see how that could be done. If using a horizontal grid transformation, there's no conversion in geocentric/cartesian state, so there's no way elevations can be transformed (contrary when a Helmert transformation is done)

**Comment by hernando** [comment]
Hmmm, I see what you mean, I didn't think about that. The only way would be to apply another path for the height. In any case, the right thing to do for OSGB36 in 3D is to use EPSG:7405, which is the official compound CRS with the national height system for UK. I'm planning to make the PRs to include the OSGM15 geoid in PROJ-data and proj.db, so don't worry about it.
