### ISSUE TITLE
I don't know if this is a bug or feature or what I may even be asking

### ISSUE THREAD

**Issue by OldSubSailor** [OSGeo/PROJ#2211]
I tried searching for this but did not get a return.

#### Example of problem
I get a full terminal window of these comments when I start Ortho4XP.

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyproj/crs/crs.py:294: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  projstring = _prepare_from_string(" ".join((projstring, projkwargs)))

```
#### Problem description
This has been going on for a long time now.   I had expected it to be fixed(?)  How long does one have to be subjected to Future Warnings?

if in_crs_string.startswith(("+init", "init")):
            warnings.warn(
                "'+init=<authority>:<code>' syntax is deprecated. "
                "'<authority>:<code>' is the preferred initialization method. "
                "When making the change, be mindful of axis order changes: "
                "https://pyproj4.github.io/pyproj/stable/gotchas.html"
                "#axis-order-changes-in-proj-6",
                FutureWarning,
                stacklevel=2,

#### Expected Output
No warnings


#### Environment Information
 - pyproj     2.6.1
- proj Rel. 7.0.0, March 1st, 2020
 - macOS Catalina 10.15.4

#### Installation method
 - I think that proj was installed when using the ruby based homebrew master install(?)

Thank you

**Comment by rouault** [comment]
This is a question for pyproj: https://github.com/pyproj4/pyproj

**Comment by OldSubSailor** [comment]
I suppose that you did not forward it to them?
A C program is like a fast dance on a newly waxed dance floor by people carrying razors.  -W.R.

And now for something completely different. -M.P

**Comment by rouault** [comment]
> I suppose that you did not forward it to them?

No

**Comment by OldSubSailor** [comment]
Thank you for your support.
