### ISSUE TITLE
Changed result of `proj_create("WGS84")`

### ISSUE THREAD

**Issue by dg0yt** [OSGeo/PROJ#2216]
#### Example of problem

In PROJ 7.0.0 and 7.0.1, "WGS84" defines a `PJ_TYPE_GEODETIC_REFERENCE_FRAME`:
~~~
$projinfo WGS84
WKT2:2019 string:
DATUM["World Geodetic System 1984",
    ELLIPSOID["WGS 84",6378137,298.257223563,
        LENGTHUNIT["metre",1]],
    ID["EPSG",6326]]
~~~

Before PROJ 7.0.0,  "WGS84" defines a `PJ_TYPE_GEOGRAPHIC_2D_CRS`:
~~~
$projinfo WGS84
PROJ.4 string:
+proj=longlat +datum=WGS84 +no_defs +type=crs

WKT2:2019 string:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    USAGE[
        SCOPE["unknown"],
        AREA["World"],
        BBOX[-90,-180,90,180]],
    ID["EPSG",4326]]
~~~

Changed type:

```c++
#include <cstdio>
#include <proj.h>
int main()
{
    auto* pj = proj_create(PJ_DEFAULT_CTX, "WGS84");
    printf("type: %d\n", proj_get_type(pj));
    return 0;
}
```

#### Problem description

I do not find more information on this change (issue, commit, release notes).
Is this intentional?

#### Installation method
 - from source

**Comment by dg0yt** [comment]
Bonus: The output for "WGS 84" is unchanged, i.e. "WGS84" and "WGS 84" differ, since 7.0.0.

**Comment by rouault** [comment]
Yes, this is related to 206a45de20b4936efa0e216fce6addd768881508 and #1823 where WGS84 (PROJ.4 string name) was added as an alias for the datum  "World Geodetic System 1984".

As the search order from name is:
1. exact name (or official alias) on CRS object
2. exact name (or official alias) on other type of objects
3. approximate name matching on CRS object
4. approximate name matching on other type of objects

the WGS84 datum is now matched at step 2, whereas previously the "WGS 84" name (which is the official name for the CRS) was matched at step 3. Hard to please everybody...

**Comment by dg0yt** [comment]
It may be a good change, indeed. However, I'm surprised to find this by accident (still on the way to switch from `+init...` to IDs), having added `proj_get_type` only recently, but with GDAL 6. "WGS84" seems to be quite prominent, so a silent change comes unexepected. I'm using GDAL, too, which accepts calls like [`oSRS.SetWellKnownGeogCS( "WGS84" );`](https://gdal.org/tutorials/warp_tut.html?highlight=wgs84), according to tutorials.

**Comment by rouault** [comment]
> I'm using GDAL, too, which accepts calls like [`oSRS.SetWellKnownGeogCS( "WGS84" )`](https://gdal.org/tutorials/warp_tut.html?highlight=wgs84)

yes, completely a GDAL thing. Predates PROJ modernization.

What I can do on PROJ side is to add an alias WGS84 to the EPSG:4326 CRS. This will still solve @snowman2 use case who explicitly used proj_create_from_name() with PJ_TYPE_GEODETIC_REFERENCE_FRAME
