### ISSUE TITLE
Implemtation of WKT

### ISSUE THREAD

**Issue by needhelp-proj** [OSGeo/PROJ#2219]
I'm trying to use a WKT string to transform between two CSs but I haven found any examples on how to do this. I'm using the OSGeo4W Shell and all attempts so far didn't work. I'm using the following code: `cs2cs +init=epsg:4326 +to +proj_create_from_wkt(0,"GEODCRS[„WGS 84“,DATUM[„World Geodetic System 1984“,ELLIPSOID[“WGS 84”,6378137,298.257223563,LENGTHUNIT[“metre”,1.0]]]CS[ellipsoidal,2],AXIS[“latitude”,north,ORDER[1]],AXIS[“longitude”,east,ORDER[2]],ANGLEUNIT[“degree”,0.0174532952]]")` . I tried using `+proj_create()` as well but I get each time the error:
> proj_create: unrecognized format / unknown name

**Comment by rouault** [comment]
For help requests, use communication channels indicated at https://proj.org/community/channels.html
