### ISSUE TITLE
SQLite3 warnings triggered (and not detected)

### ISSUE THREAD

**Issue by jjimenezshaw** [OSGeo/PROJ#2221]
#### Example of problem
When I enable SQLite3 error logging with the call to `sqlite3_config(SQLITE_CONFIG_LOG, errorLogCallback, pData);` it detects some error/warnings. These messages may saturate the log, and they show a posible lack of performance.

Enabling sqlite3 log (see below how) this command produces this output:
```
echo  48 -110 0 | cs2cs EPSG:4326 EPSG:32001
setting SQLITE_CONFIG_LOG
(code 284) automatic index on alias_name(code)
(code 284) automatic index on alias_name(code)
(code 284) automatic index on alias_name(code)
(code 284) automatic index on alias_name(code)
(code 284) automatic index on alias_name(code)
(code 284) automatic index on alias_name(code)
(code 284) automatic index on alias_name(code)
(code 284) automatic index on alias_name(code)
1877763.91	365187.80 0.00
```

This naïve patch enables the sqlite3 log in `cs2cs`, and dumps every message to `stderr`
```
diff --git a/src/apps/cs2cs.cpp b/src/apps/cs2cs.cpp
index 4ada83b5..567cb740 100644
--- a/src/apps/cs2cs.cpp
+++ b/src/apps/cs2cs.cpp
@@ -319,7 +319,17 @@ static std::string get_geog_crs_proj_string_from_proj_crs(PJ *src,
 /*                                main()                                */
 /************************************************************************/
 
+#include "sqlite3.h"
+static void errorLogCallback(void*, int iErrCode, const char* zMsg)
+{
+    fprintf(stderr, "(code %d) %s\n", iErrCode, zMsg);
+}
+
 int main(int argc, char **argv) {
+
+    fprintf(stderr, "setting SQLITE_CONFIG_LOG\n"); // to test stderr
+    sqlite3_config(SQLITE_CONFIG_LOG, errorLogCallback, nullptr);
+
     char *arg;
     char **eargv = argv;
     std::string fromStr;
```

#### Problem description
When the final application uses SQLite3 for other purposes, it may want to detect errors with the log callback. However in this case, the log can be flooded by messages from `PROJ`, depending on the transformations and CRS used.
The error is suggesting that the index should be pre-created, to avoid creating it automatically every single time.

More info in 
- https://www.sqlite.org/optoverview.html#autoindex
- https://www.sqlite.org/errlog.html 
- https://www.sqlite.org/c3ref/c_config_covering_index_scan.html#sqliteconfiglog

This problem is detected also calling the method `GetProjectionRef` reading a GeoTIFF with `GDAL`. Every time I open a GeoTIFF (and read the projection ref), the message is logged.

Side note: creating a "non-Universal" Transverse Mercator projection (with scale_factor=1, false_easting=0, central_meridian=0) in `GDAL` with `SetTM` generates the log `(284) automatic index on object_view(table_name)`

#### Expected Output
No messages due to missing indices on SQLite3 log when it is enabled in a final application.

#### Environment Information
 - PROJ version (`proj`) 7.0.1
 - Operation System Information: Ubuntu 18.04

#### Installation method
 - compiled from source tag 7.0.1

**Comment by rouault** [comment]
I'm not sure that we can address this, at least fully. For example "automatic index on object_view(table_name)" cannot be solved by creating an index on a table, since this isn't possible here, object_view being a view. So this might imply to rewrite some requests, and could also be dependent on the SQLite3 version and how its query planner work.
I'd suggest that you ignore those warnings for now.

**Comment by jjimenezshaw** [comment]
Thanks for the quick answer.
The message about "object_view(table_name)" was just to give more information.

What about creating an index on alias_name(code)? It seems to be the most common message. In particular opening GeoTIFFs in GDAL with a normal UTM wkt (nothing fancy).

**Comment by jjimenezshaw** [comment]
Checking the backtrace of the call to `GDALDataset::GetProjectionRef()`, the error message is created inside the call to `const char* pszWKT = proj_as_wkt(...)` in 
`OGRSpatialReference::Private::refreshRootFromProjObj()`
Unfortunately I don't have useful symbols for `PROJ` in this environment.

**Comment by jjimenezshaw** [comment]
That was fast! Thank you!
