### ISSUE TITLE
Linker error when attempting to building libproj with PIC

### ISSUE THREAD

**Issue by urschrei** [OSGeo/PROJ#2231]
#### Example of problem
I'm building `proj` 7.0.1 from source, in order to statically link to it. The library I'm linking it to requires PIC, and I'm configuring CMake as follows:

    cmake proj-7.0.1
    -DBUILD_SHARED_LIBS=ON
    -DBUILD_TESTING=OFF
    -DCMAKE_BUILD_TYPE=Release
    -DCMAKE_CXX_FLAGS="-std=c++11 -fPIC"
    -DCMAKE_INSTALL_PREFIX=[path snipped]/out
    -DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64
    -DCMAKE_C_COMPILER=/usr/bin/gcc-9
    -DCMAKE_CXX_COMPILER=/usr/bin/g++-9
    -DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64
    -DCMAKE_ASM_COMPILER=/usr/bin/gcc-9

`libproj` [builds and installs to the specified directory](https://travis-ci.org/github/georust/proj-sys/jobs/688453592#L2413) (dynamically linking `libcurl`, `libtiff`, and `sqlite 3`), but the link step fails:

    note: /usr/bin/ld: [path snipped]/out/lib/libproj.a(4D_api.cpp.o): relocation
    R_X86_64_32 against `.rodata.str1.8' can not be used when making a
    shared object; recompile with -fPIC`

    [path snipped]/out/lib/libproj.a(4D_api.cpp.o): error adding symbols: Bad value
    collect2: error: ld returned 1 exit status

To be clear, I strongly suspect that this is an error on my part, **not** a bug, but I'm wondering whether a linker error of this kind has been seen before.

#### Environment Information
 - PROJ version (`proj 7.0.1`)
 - Linux (Xenial, Travis, gcc-9 / g++-9)

#### Installation method
from source

**Comment by mwtoews** [comment]
Run `VERBOSE=1 make -j2` to see the full commands used to create objects, and you should see that CMake already adds `-std=c++11 -fPIC`, so it should not be necessary to specify these to `CMAKE_CXX_FLAGS`.

Are you able to successfully build the library with fewer options? This might help narrow down the issue.
