### ISSUE TITLE
Consider including remarks, scope and source for conversions

### ISSUE THREAD

**Issue by nyalldawson** [OSGeo/PROJ#2237]
Currently the conversions table does not include the scope, remarks or source information which is available from the EPSG registry. It would be valuable for this information to be included in the proj database so that it can be exposed to users to aid them to make correct operation choices when multiple operations are possible.

**Comment by rouault** [comment]
> so that it can be exposed to users to aid them to make correct operation choices when multiple operations are possible.

not sure to understand the rationale: conversions are mostly a map projection with its parameter instantiated. When transforming between a projected CRS and something else, all the potential coordinate operations will use the same conversion(s). Only the transformations between datums might change.

**Comment by nyalldawson** [comment]
I was looking at a transform which used the epsg:17355 conversion. Proj doesn't expose any textual metadata about this, but the epsg registry has content:

"Remarks: Grid convergence uses opposite sign convention to UTM.
Scope: Large and medium scale topographic mapping and engineering survey.
Information Source: Australian Surveying and Land "

**Comment by kbevers** [comment]
I can see exposing stuff like this being useful in QGIS when defining custom CRS/projections.

**Comment by nyalldawson** [comment]
Thank you!!
