### ISSUE TITLE
Spurious warning `proj_context_get_database_path: Cannot find proj.db`

### ISSUE THREAD

**Issue by hernando** [OSGeo/PROJ#2242]
#### Example of problem

GDAL's `GetProjTLSContextHolder`, which is called from `OSRSetPROJSearchPaths` executes this sequence:
```
        proj_context_set_autoclose_database(l_projContext.context, true);
        // dummy call to cause the database to be closed
        proj_context_get_database_path(l_projContext.context);
        proj_context_set_autoclose_database(l_projContext.context, false);
```
When proj.db is not located in any of the default search paths and PROJ_LIB is not present, the call to `proj_context_get_database_path` prints a warning about `proj.db` not found.

#### Problem description

`OSRSetPROJSearchPaths` prints a warning to proj.db not found in the very attempt to set the location to it.

#### Expected Output

No warning is printed, `proj_context_get_database_path` returns `nullptr` instead.

But the actual solution should be having a function to close the database instead of the 3 function call sequence workaround used in GDAL.

#### Environment Information
 - PROJ version 7.0.1
 - Ubuntu 18.04

#### Installation method
 - Compiled from source

**Comment by rouault** [comment]
This is rather a GDAL issue
