### ISSUE TITLE
Make projection definitions for Belge Lambert 1972 equivalent

### ISSUE THREAD

**Issue by karinpraet** [OSGeo/PROJ#2249]
I'm refering to the closed issue: [https://github.com/OSGeo/PROJ/issues/1781](https://github.com/OSGeo/PROJ/issues/1781)
ESRI changed the definition for EPSG:31370 and classified the old definition as ESRI:102499.

In the new release of ArcGIS Pro, Esri makes both definitions equivalent. See [https://pro.arcgis.com/en/pro-app/get-started/release-notes.htm](https://pro.arcgis.com/en/pro-app/get-started/release-notes.htm) BUG-000130113. 

#### Expected Output
Make the project definition for ESRI:102499 Belge_Lambert_1972_bad_FE_FN equivalent to EPSG:31370 Belge_lambert_1972

**Comment by rouault** [comment]
So it looks like ESRI:102499 uses a precision of 0.1 mm for false easting/northing values, whereas EPSG:31370 rounds them to a precision of 1 mm, right ?

What do you mean exactly by "making projection equivalent": that someone referencing ESRI:102499 would actually use the projection parameters of EPSG:31370 ? We don't have such mechanism. The closest we have would be to mark ESRI:102499 as being deprecated by EPSG:31370 but that wouldn't make use it automatically use its parameters

**Comment by karinpraet** [comment]
I'm not sure this will have the desired effect. I would have to check the consequences together with some collegues. This will take some time. So I will close this issue for now. Thanks for your response.
