### ISSUE TITLE
Incorrect Projection Parameters for RSRGD2000 / RSPS2000

### ISSUE THREAD

**Issue by palmerj** [OSGeo/PROJ#2254]
#### Example of problem
I think projection EPSG:5482 has an issue with the application of projection parameters in PROJ 7.1.0 (master). 

Using projinfo it seems the first standard parallel parameter is not defining lat true scale parameter for the sterographic projection method. See:

```
$ projinfo EPSG:5482 -o WKT1:GDAL
WKT1:GDAL string:
PROJCS["RSRGD2000 / RSPS2000",
    GEOGCS["RSRGD2000",
        DATUM["Ross_Sea_Region_Geodetic_Datum_2000",
            SPHEROID["GRS 1980",6378137,298.257222101,
                AUTHORITY["EPSG","7019"]],
            AUTHORITY["EPSG","6764"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4764"]],
    PROJECTION["Polar_Stereographic"],
    PARAMETER["latitude_of_origin",-90],
    PARAMETER["central_meridian",180],
    PARAMETER["scale_factor",0.994],
    PARAMETER["false_easting",5000000],
    PARAMETER["false_northing",1000000],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AUTHORITY["EPSG","5482"]]
```

I would expect to see PARAMETER["standard_parallel_1",-90] in the WKT definition, so PROJ includes the +lat_ts=-90 proj parameter (rather than the default of +lat_ts=0) .

```
projinfo 'PROJCS["RSRGD2000_RSPS2000", GEOGCS["GCS_RSRGD2000", DATUM["D_Ross_Sea_Region_Geodetic_Datum_2000", SPHEROID["GRS_1980",6378137,298.257222101]], PRIMEM["Greenwich",0], UNIT["Degree",0.017453292519943295]], PROJECTION["Stereographic_South_Pole"], PARAMETER["standard_parallel_1",-90], PARAMETER["central_meridian",180], PARAMETER["false_easting",5000000], PARAMETER["false_northing",1000000], UNIT["Meter",1]]' -o PROJ
PROJ.4 string:
+proj=stere +lat_0=-90 +lat_ts=-90 +lon_0=180 +x_0=5000000 +y_0=1000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs +type=crs
```

I checked with GDAL 2.4.2/PROJ 5.2.0 and it does output the correct PROJ projection parameters, even though the WKT is the same. So it looks like some change in the conversion and mapping of projection parameters between PROJ versions 5.2.0 and 7.10-master...

```
>>> import gdal
>>> gdal.VersionInfo()
'2040200'
>>> import osr
>>> proj = osr.SpatialReference()
>>> proj.ImportFromEPSG(5482)
0
>>> proj.ExportToPrettyWkt()
'PROJCS["RSRGD2000 / RSPS2000",\n    GEOGCS["RSRGD2000",\n        DATUM["Ross_Sea_Region_Geodetic_Datum_2000",\n            SPHEROID["GRS 1980",6378137,298.257222101,\n                AUTHORITY["EPSG","7019"]],\n            TOWGS84[0,0,0,0,0,0,0],\n            AUTHORITY["EPSG","6764"]],\n        PRIMEM["Greenwich",0,\n            AUTHORITY["EPSG","8901"]],\n        UNIT["degree",0.0174532925199433,\n            AUTHORITY["EPSG","9122"]],\n        AUTHORITY["EPSG","4764"]],\n    PROJECTION["Polar_Stereographic"],\n    PARAMETER["latitude_of_origin",-90],\n    PARAMETER["central_meridian",180],\n    PARAMETER["scale_factor",0.994],\n    PARAMETER["false_easting",5000000],\n    PARAMETER["false_northing",1000000],\n    UNIT["metre",1,\n        AUTHORITY["EPSG","9001"]],\n    AUTHORITY["EPSG","5482"]]'
>>> proj.ExportToProj4()
'+proj=stere +lat_0=-90 +lat_ts=-90 +lon_0=180 +k=0.994 +x_0=5000000 +y_0=1000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs '
```

#### Environment Information
 - PROJ master/5.2.0
 - MacOS/Windows

#### Installation method
 - from source, shipped with QGIS MacOS

**Comment by rouault** [comment]
OK, this is a bit of a confusing area, but I don't think there's a bug.
The EPSG projection method used for EPSG:5482 is "Polar Stereographic (variant A)" that accepts only a "Latitude of natural origin" (lat_0) and "Scale factor at natural origin" (k_0)
GDAL 2.4 in its PROJ.4 export used to add a lat_ts parameter equal to lat_0, but this is not necessary as the default for stere is to have abs(lat_ts) =90. (I see the doc of +proj=stere is wrong there, referencing to the generic behaviour of lat_ts which isn't the one actually implemented for +proj=stere. Will followup with fix)

```
$ echo "45 -85" | proj +proj=stere +lat_0=-90 +lat_ts=-90 +lon_0=180 +k=0.994 +x_0=5000000 +y_0=1000000 +ellps=GRS80
4607232.31	607232.31
$ echo "45 -85" | proj +proj=stere +lat_0=-90 +lon_0=180 +k=0.994 +x_0=5000000 +y_0=1000000 +ellps=GRS80
4607232.31	607232.31
```

**Comment by palmerj** [comment]
But I think ( need to confirm with users in the morning) we are getting things rotated 90 degrees with 5482 now. This layer is in 3031, and setting the project projection to 5482.. (In QGIS v3.12):

![image](https://user-images.githubusercontent.com/580022/83630611-72c49f80-a5df-11ea-8567-a103a2d047bb.png)

When add the +lat_ts=-90 parameter it's fixed!

Also this projection from a .prj shapefile also works ok in QGIS:

```
PROJCS["RSRGD2000_RSPS2000",
    GEOGCS["GCS_RSRGD2000",
        DATUM["D_Ross_Sea_Region_Geodetic_Datum_2000",
            SPHEROID["GRS_1980",6378137,298.257222101]],
        PRIMEM["Greenwich",0],
        UNIT["Degree",0.017453292519943295]],
    PROJECTION["Stereographic_South_Pole"],
    PARAMETER["standard_parallel_1",-90],
    PARAMETER["central_meridian",180],
    PARAMETER["false_easting",5000000],
    PARAMETER["false_northing",1000000],
    UNIT["Meter",1]]
```

**Comment by rouault** [comment]
Ah, that's a completely different issue then.
I strongly suspect this is due to the unusual axis order from the EPSG definition
```
    CS[Cartesian,2],
        AXIS["northing (N)",north,
            MERIDIAN[180,
                ANGLEUNIT["degree",0.0174532925199433]],
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["easting (E)",north,
            MERIDIAN[-90,
                ANGLEUNIT["degree",0.0174532925199433]],
            ORDER[2],
            LENGTHUNIT["metre",1]],
```
and it not being taken into account by normalizeForVisualization() method of PROJ, that is used by QGIS for "GIS friendly" visualization.
I can fix that, but the meridian values here are really surprising: normally they would imply that for eastings, positive values are towards the west, and for northings, positive to the south. So even the "EPSG axis definition compliant" mode of PROJ is probably currently confused by that.

EPSG:32761 uses a more usual unusual (if I might say) axis definition for Polar stereographic that is taken into account by the normalizeForVisualization() method:
```
    CS[Cartesian,2],
        AXIS["northing (N)",north,
            MERIDIAN[0,
                ANGLEUNIT["degree",0.0174532925199433]],
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["easting (E)",north,
            MERIDIAN[90,
                ANGLEUNIT["degree",0.0174532925199433]],
            ORDER[2],
            LENGTHUNIT["metre",1]],
```

**Comment by rouault** [comment]
Ok, should be fixed by https://github.com/OSGeo/PROJ/pull/2256 . I've tried it in QGIS with 2 rasters, one in EPSG:3031 and one in EPSG:5482 generated with gdalwarp from the same input raster. With the fix, they overlap when using either EPSG:3031 or EPSG:5482 in QGIS as the current CRS.

**Comment by palmerj** [comment]
Thank so much @rouault for the fix.

Can't you please clearly explain why it was working in 5.2 and not now? Is normalizeForVisualization a new feature of PROJ?

> but the meridian values here are really surprising: normally they would imply that for eastings, positive values are towards the west, and for northings, positive to the south

Positive to the north, and positive to the west I think. Note the RSPS2000 projection is centred on 180°E/W to provide a 'New Zealand up' projection.

Note the projection definition is here: https://www.linz.govt.nz/data/geodetic-system/datums-projections-and-heights/projections/ross-sea-region-projections#rsps2000.

**Comment by palmerj** [comment]
Note given this fix, do you think we need to change something in the EPSG registry to make this easier to deal with?

**Comment by rouault** [comment]
> Can't you please clearly explain why it was working in 5.2 and not now? Is normalizeForVisualization a new feature of PROJ?

Past GDAL and PROJ where (mostly) EPSG axis order unaware. PROJ >= 6 is now (mostly) EPSG axis order aware, which is both a feature and a bug depending on point of view and use cases. normalizeForVisualization() is a method used for GIS-friendly usage, that is where the horizontal axis is along longitudes/eastings and the vertical axis along latitudes/northings, while the EPSG definition might use the "geodesist order". Not sure that makes sense.

> Note given this fix, do you think we need to change something in the EPSG registry to make this easier to deal with?

Not really. Changing it would bring even more confusion now.

**Comment by palmerj** [comment]
Thanks Even. Personally I see per SRS axis order definition for anything other than a hard set default of GIS-friendly/computer science friendly as a bug and a huge pain to all. I'm not really sure many geodesist even want this. Standard's writers/modellers on the other hand...
```
     CS[Cartesian,2],
        AXIS["northing (N)",north,
            MERIDIAN[180,
                ANGLEUNIT["degree",0.0174532925199433]],
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["easting (E)",north,
            MERIDIAN[-90,
                ANGLEUNIT["degree",0.0174532925199433]],
            ORDER[2],
            LENGTHUNIT["metre",1]],
```

I'm still really confused how `"easting (E)",north,` got defined in EPSG. Is this not a data entry issue? I think LINZ needs to audit its EPSG records.

**Comment by kbevers** [comment]
>  Personally I see per SRS axis order definition for anything other than a hard set default of GIS-friendly/computer science friendly as a bug and a huge pain to all. I'm not really sure many geodesist even want this. Standard's writers/modellers on the other hand...

This is all based on standards mostly designed by geodesist, so I'm not sure your statement holds. On the surface it seems ridicoulus that axis ordering is even an issue but there are many cases where you can't assume that the first number in a coordinate is the direction towards east and the second towards north. Polar stereographic projections is a good example of that.

> I'm still really confused how "easting (E)",north, got defined in EPSG. Is this not a straight out data entry issue? I think LINZ needs to audit its EPSG records.

Yes, that looks like a blunder in data entry (copy/paste gone wrong?)

**Comment by rouault** [comment]
> Yes, that looks like a blunder in data entry (copy/paste gone wrong?)

no, it's not a blunder: ``"easting (E)",north,`` means that this is an axis meant at representing easting values of the projection, but as you are centered at the south pole, all directions starting from it go to the ``north``.

See 7.5.4 c) of http://docs.opengeospatial.org/is/18-010r7/18-010r7.html:
```For coordinate systems centred on a pole the direction for both axes will be ‘south’ (for the north pole case) or ‘north’ (for the south pole case); the axes direction shall be supplemented with a <meridian> description. This is the value of the meridian that the axis follows from the pole.```

**Comment by palmerj** [comment]
> no, it's not a blunder: "easting (E)",north, means that this is an axis meant at representing easting values of the projection, but as you are centered at the south pole, all directions starting from it go to the north.

Aha. Yes that make sense now you point it out. Very confusing on the surface. X and Y system would just be easier in this case!

> This is all based on standards mostly designed by geodesist, so I'm not sure your statement holds

@kbevers Maybe not, and I guess we will never know. My guess is the committee only had a few actual member (IAG or national agency reps) involved in the standard and most others wouldn't have been aware of the details at the time of publishing. Anyway we have this additional complex now in our system, so we can't go back on that.
