### ISSUE TITLE
Does proj_info return updated search paths if they've been set using proj_context_set_search_paths?

### ISSUE THREAD

**Issue by urschrei** [OSGeo/PROJ#2266]
Using 7.0.1, with `api.h`, I can pass an updated list of search paths using `proj_context_set_search_paths`, but a subsequent call to `proj_info` doesn't reflect the update. Since `proj_info` doesn't take a `PJ_CONTEXT*`, I'm just double-checking whether I've done something wrong when setting the new paths, or whether `proj_info` isn't supposed to show the update.

**Comment by rouault** [comment]
> Since `proj_info` doesn't take a `PJ_CONTEXT*`

Yes, that's exactly the reason. proj_info() can only return the search paths modified on the default context, but not a custom context.

**Comment by urschrei** [comment]
Ah, thanks for clarifying. If I set the new search path on the default context, do custom contexts (existing or subsequently-created) use the updated paths?

**Comment by rouault** [comment]
>  If I set the new search path on the default context, do custom contexts (existing or subsequently-created) use the updated paths?

I think so
