### ISSUE TITLE
Basic Temporal Datum Support (c-api)

### ISSUE THREAD

**Issue by snowman2** [OSGeo/PROJ#2273]
Highest priority:
- Add `PJ_TYPE_TEMPORAL_DATUM` (identified with proj_get_type) - or something like it. The PJ_TYPE is currently set to unknown. Would be nice to be able to identify it. (Side note: `PJ_TYPE_ENGINEERING_DATUM` and `PJ_TYPE_PARAMETRIC_DATUM` would be nice to have as well.)

Would be nice, but currently can access with PROJ JSON, so not entirely necessary:

- `proj_temporal_datum_get_calendar()`
- `proj_temporal_datum_get_time_origin()`

```
    "TIMECRS[\"Decimal Years CE\",\n"
    "    TDATUM[\"Common Era\",\n"
    "        CALENDAR[\"proleptic Gregorian\"],\n"
    "        TIMEORIGIN[0000]],\n"
    "    CS[TemporalMeasure,1],\n"
    "        AXIS[\"decimal years (a)\",future,\n"
    "            TIMEUNIT[\"year\"]]]"
```

```python
>>> print(crs.datum.to_json(pretty=True))
{
  "$schema": "https://proj.org/schemas/v0.2/projjson.schema.json",
  "type": "TemporalDatum",
  "name": "Common Era",
  "calendar": "proleptic Gregorian",
  "time_origin": "0000"
}
```

What are the current thoughts/plans for this?

**Comment by rouault** [comment]
> What are the current thoughts/plans for this?

Your suggestions sound good. Feel free to submit a PR for them
