### ISSUE TITLE
projsync fails, cdn.proj.org link broken?

### ISSUE THREAD

**Issue by perrygeo** [OSGeo/PROJ#2285]
#### Example of problem
The projsync utility isn't working out of the box

```bash
$ projsync --system-directory --all
Downloading from https://cdn.proj.org into /usr/local/share/proj
Cannot download files.geojson
```
#### Environment Information
 - PROJ version 7.1.0
 - Debian buster

#### Installation method
 - Source, `--prefix=/usr/local`

**Comment by rouault** [comment]
you likely need to run as sudo if your system directory is  /usr/local/share/proj

**Comment by perrygeo** [comment]
This is running as root in a Docker build. I can confirm that I have network connectivity and write access to `/usr/local/share/proj`. 

EDIT: The problem was `libcurl` which was compiled without ssl support. Installing `libssl-dev` and recompiling curl `--with-ssl` fixed the problem. Sorry for the noise!
