### ISSUE TITLE
Inaccuracy after back and forth helmert transformation

### ISSUE THREAD

**Issue by and-marsh** [OSGeo/PROJ#2302]
#### Example of problem

Hi,
I have found that some slight error appears after back and forth helmert transformation. I wonder if it's some logic error or just error due to floating point numbers?

 
For example i used `gdaltransform` but i think it's PROJ business anyway:
```c
echo '5 115 0' | ./gdaltransform -ct 'urn:ogc:def:coordinateOperation:EPSG::6902'
4.99914346212806 115.003007192241 0

echo '4.99914346212806 115.003007192241 0' | ./gdaltransform -ct 'urn:ogc:def:coordinateOperation:EPSG::6902' -i
5.00000000632161 114.999999977952 0
```
The difference is something about 2.5mm. It can increase with repeated transformation back and forth.

Thank you in advance!

#### Environment Information
 - PROJ version (`7.0.1`)
 

#### Installation method
 - from source

**Comment by kbevers** [comment]
I can't reproduce. With `projinfo` I get the following pipeline:

```
projinfo urn:ogc:def:coordinateOperation:EPSG::6902 -o PROJ
PROJ string:
+proj=pipeline +step +proj=axisswap +order=2,1 +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=push +v_3 +step +proj=cart +ellps=evrstSS +step +proj=helmert +x=-679 +y=667 +z=-49 +step +inv +proj=cart +ellps=WGS84 +step +proj=pop +v_3 +step +proj=unitconvert +xy_in=rad +xy_out=deg +step +proj=axisswap +order=2,1
```

which I then use to create a gie file with, that tests if the roundtrip accuracy is below 1 mm after 10000 iterations:

```
<gie>

operation +proj=pipeline
          +step +proj=axisswap +order=2,1
          +step +proj=unitconvert +xy_in=deg +xy_out=rad
          +step +proj=push +v_3
          +step +proj=cart +ellps=evrstSS
          +step +proj=helmert +x=-679 +y=667 +z=-49
          +step +inv +proj=cart +ellps=WGS84
          +step +proj=pop +v_3
          +step +proj=unitconvert +xy_in=rad +xy_out=deg
          +step +proj=axisswap +order=2,1

accept    5 115 0
roundtrip 10000  1 mm

</gie>
```

It is:

```
 gie epsg_6902.gie
-------------------------------------------------------------------------------
Reading file 'epsg_6902.gie'
-------------------------------------------------------------------------------
total:  1 tests succeeded,  0 tests skipped,  0 tests failed.
-------------------------------------------------------------------------------
```

If I increase the number of iterations to 50000 I start to get into trouble:

```
 gie epsg_6902.gie
-------------------------------------------------------------------------------
Reading file 'epsg_6902.gie'
-------------------------------------------------------------------------------
proj=pipeline step proj=axisswap order=2,1 step proj=unitconvert xy_in...
-------------------------------------------------------------------------------
     FAILURE in epsg_6902.gie(15):
     roundtrip deviation: 1.146778 mm, expected: 1.000000 mm
-------------------------------------------------------------------------------
total:  0 tests succeeded,  0 tests skipped,  1 tests FAILED!
-------------------------------------------------------------------------------
```

So in conclusion, the transformation seems to perform just fine. It is likely that your problem is related to passing coordinates on the command line or maybe GDAL is doing something extra to the coordinates.

**Comment by and-marsh** [comment]
Thanks for the quick answer!

I will do some extra tests and and try to find out what exactly causes the problem.

**Comment by rouault** [comment]
@kristian I think gie / proj_roundtrip is confused  by the unitconvert regarding geographic vs projected coordinates. If one removes them and modify input values accordingly

```
<gie-strict>
operation +proj=pipeline \
          +step +proj=push +v_3 \
          +step +proj=cart +ellps=evrstSS \
          +step +proj=helmert +x=-679 +y=667 +z=-49 \
          +step +inv +proj=cart +ellps=WGS84 \
          +step +proj=pop +v_3

tolerance 1 mm
accept    115 5 0
roundtrip 1

</gie-strict>
```
it fails with
```
-------------------------------------------------------------------------------
     FAILURE in test.gie(11):
     roundtrip deviation: 2.542775 mm, expected: 1.000000 mm
```

**Comment by rouault** [comment]
The round-tripping issue comes from the +step +proj=push +v_3  / +step +proj=pop +v_3 . I guess this is expected

**Comment by kristian** [comment]
@rouault wrong @kristian 👍

**Comment by kbevers** [comment]
>  I guess this is expected

Yes, that will of course cause some inaccuracy when roundtripping. We can't fix that. Fortunately the (single) roundtrip error is well within the advertized accuracy of the transformation.

**Comment by and-marsh** [comment]
Thanks a lot for the clarifying!
Since it's expected and can't be fixed the issue can be closed. Sorry for disturbing.

Have a nice weekend!
