### ISSUE TITLE
PROJ 7.1.0 make error

### ISSUE THREAD

**Issue by joaocarr** [OSGeo/PROJ#2306]
Hi,
I'm getting the following error after make:
---------------------------------------------------------------------------
./.libs/libproj.so: undefined reference to `sqlite3_column_blob'
./.libs/libproj.so: undefined reference to `sqlite3_column_int64'
./.libs/libproj.so: undefined reference to `sqlite3_bind_double'
./.libs/libproj.so: undefined reference to `sqlite3_bind_blob'
./.libs/libproj.so: undefined reference to `sqlite3_column_type'
./.libs/libproj.so: undefined reference to `sqlite3_reset'
./.libs/libproj.so: undefined reference to `sqlite3_bind_null'
./.libs/libproj.so: undefined reference to `TIFFClose'
./.libs/libproj.so: undefined reference to `sqlite3_result_double'
./.libs/libproj.so: undefined reference to `TIFFGetField'
./.libs/libproj.so: undefined reference to `TIFFSetTagExtender'
./.libs/libproj.so: undefined reference to `TIFFIsCODECConfigured'
./.libs/libproj.so: undefined reference to `sqlite3_close'
./.libs/libproj.so: undefined reference to `sqlite3_create_function'
./.libs/libproj.so: undefined reference to `sqlite3_vfs_register'
./.libs/libproj.so: undefined reference to `sqlite3_last_insert_rowid'
./.libs/libproj.so: undefined reference to `sqlite3_snprintf'
./.libs/libproj.so: undefined reference to `sqlite3_vsnprintf'
./.libs/libproj.so: undefined reference to `sqlite3_libversion_number'
./.libs/libproj.so: undefined reference to `TIFFReadEncodedTile'
./.libs/libproj.so: undefined reference to `sqlite3_column_double'
./.libs/libproj.so: undefined reference to `sqlite3_value_double'
./.libs/libproj.so: undefined reference to `TIFFReadDirectory'
./.libs/libproj.so: undefined reference to `sqlite3_libversion'
./.libs/libproj.so: undefined reference to `TIFFReadEncodedStrip'
./.libs/libproj.so: undefined reference to `sqlite3_column_text'
./.libs/libproj.so: undefined reference to `sqlite3_bind_text'
./.libs/libproj.so: undefined reference to `sqlite3_prepare_v2'
./.libs/libproj.so: undefined reference to `sqlite3_errmsg'
./.libs/libproj.so: undefined reference to `sqlite3_bind_int64'
./.libs/libproj.so: undefined reference to `TIFFIsTiled'
./.libs/libproj.so: undefined reference to `sqlite3_result_int'
./.libs/libproj.so: undefined reference to `TIFFStripSize64'
./.libs/libproj.so: undefined reference to `sqlite3_column_bytes'
./.libs/libproj.so: undefined reference to `sqlite3_value_type'
./.libs/libproj.so: undefined reference to `sqlite3_free_table'
./.libs/libproj.so: undefined reference to `sqlite3_open_v2'
./.libs/libproj.so: undefined reference to `TIFFClientOpen'
./.libs/libproj.so: undefined reference to `TIFFMergeFieldInfo'
./.libs/libproj.so: undefined reference to `sqlite3_exec'
./.libs/libproj.so: undefined reference to `sqlite3_step'
./.libs/libproj.so: undefined reference to `sqlite3_value_int64'
./.libs/libproj.so: undefined reference to `TIFFCurrentDirOffset'
./.libs/libproj.so: undefined reference to `TIFFSetSubDirectory'
./.libs/libproj.so: undefined reference to `sqlite3_vfs_unregister'
./.libs/libproj.so: undefined reference to `TIFFTileSize64'
./.libs/libproj.so: undefined reference to `sqlite3_finalize'
./.libs/libproj.so: undefined reference to `sqlite3_result_null'
./.libs/libproj.so: undefined reference to `sqlite3_vfs_find'
./.libs/libproj.so: undefined reference to `sqlite3_config'
./.libs/libproj.so: undefined reference to `sqlite3_column_count'
./.libs/libproj.so: undefined reference to `sqlite3_initialize'
./.libs/libproj.so: undefined reference to `sqlite3_get_table'
collect2: error: ld returned 1 exit status
make[2]: *** [proj] Error 1
make[2]: Leaving directory `/home/sm1jc/build_proj/proj-7.1.0/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/sm1jc/build_proj/proj-7.1.0/src'
make: *** [all-recursive] Error 1
---------------------------------------------------------------------------------
I have successfully installed sqlite and libtiff and updated the paths in .bashrc.
export CPATH=/home/sm1jc/sqlite/sqlite-3.32.3/include/:/home/sm1jc/libtiff/libtiff-4.1.0/include/:$CPATH
export LIBRARY_PATH=/home/sm1jc/sqlite/sqlite-3.32.3/lib/:/home/sm1jc/libtiff/libtiff-4.1.0/lib/:$LIBRARY_PATH
export LD_LIBRARY_PATH=/home/sm1jc/sqlite/sqlite-3.32.3/lib/:/home/sm1jc/libtiff/libtiff-4.1.0/lib/:$LD_LIBRARY_PATH
export PATH=/home/sm1jc/sqlite/sqlite-3.32.3/bin/:/home/sm1jc/libtiff/libtiff-4.1.0/bin/:$PATH
export SQLITE3_LIBS=/home/sm1jc/sqlite/sqlite-3.32.3/lib/
export TIFF_LIBS=/home/sm1jc/libtiff/libtiff-4.1.0/lib/
export TIFF_CFLAGS=home/sm1jc/libtiff/libtiff-4.1.0/include/
 

#### Environment Information
 - PROJ version (`proj-7.1.0`)
 - CentOS Linux 7 (Core)

#### Installation method
 - from source

**Comment by rouault** [comment]
Look at closed issues . There's at least one with a similar issue, and the solution
