### ISSUE TITLE
Use of "inf"

### ISSUE THREAD

**Issue by BrannonKing** [OSGeo/PROJ#2317]
I have an issue using existing images that contain `inf` for their flattening values. For whatever reason it seems that earlier versions of PROJ and GDAL supported using infinite floating point values, but that current versions don't support it.

Here's an example of an image: https://drive.google.com/file/d/1-kY3_ZDP-yu1mE3ahxHa8GMJGe_vz6Uk/view?usp=sharing . Attempts to manipulate this image give the error "non double value". I recognize that the documentation says to use "zero" to mean infinite flattening. I was unaware of that years ago, whenever I first began using GDAL/PROJ. I'm fairly sure I'm not the only one doing this, though.

My guess is that this is just a string parsing issue, and that the underlying mathematical functionality can handle the infinite floating value.

The ostringstream utilized to write the values (in internal.cpp) will happily write out "inf" for infinite doubles. It's the istringstream where things become problematic. See the note here: http://cplusplus.github.io/LWG/lwg-active.html#2381 . 

Some possible options:
1. Special case `+/-inf` in the c_locale_stod method.
2. Utilize `<charconv>` on Windows with C++17 or newer.
3. Force the locale for the entire process to be ol' C and use `std::stod` et al.

It seems that `<charconv>` never did get a floating point implementation done on GCC, which is unfortunate. I don't know all the ramifications of defaulting to C++17 on Windows, either. So what would you think about special-casing the `inf` support? It would be fine for NaN to continue to break things.

**Comment by rouault** [comment]
The issue was more in the GeoTIFF file than in the software, anyway I've pushed a fix in GDAL GeoTIFF reader to interpret the infinite value as 0.

**Comment by BrannonKing** [comment]
Your fix is sufficient for my present use case. Thanks for being so prompt on it.
