### ISSUE TITLE
Always add user writable directory?

### ISSUE THREAD

**Issue by snowman2** [OSGeo/PROJ#2330]
In the [docs](https://proj.org/resource_files.html#where-are-proj-resource-files-looked-for) it says that if you set `proj_context_set_search_paths` that the user writable directory will not be searched through. Since this directory only contains transformation grids, would there be a reason not to always search through it even if search paths are set?

**Comment by rouault** [comment]
The user-writable directory will in most cases contain only the cache.db file (that will contain chunks of transformation grids). cache.db in the user-writable directory will be accessed whatever the logic to find regular resource files is. That is if proj_context_set_search_paths doesn't include the user writable directory, it will still be accessed to find cache.db if PROJ_NETWORK=ON

I don't see a particular reason why the current logic (which is partly historic / arbitrary) of proj_context_set_search_paths() with respect to the user writable directory should be changed. Which use case do you have in mind ? Can't it be covered with existing logic and API ?

**Comment by snowman2** [comment]
> That is if proj_context_set_search_paths doesn't include the user writable directory, it will still be accessed to find cache.db if PROJ_NETWORK=ON

This is the part that confused me. It is a directory that is always used by PROJ when PROJ_NETWORK=ON, but when I downloaded grids with `projsync`, it couldn't find them. I guess my brain assumed that if PROJ was already using it for `cache.db` it would also use it to look for grids.

> Can't it be covered with existing logic and API?

Yes, it can be. You can add the directory that is set by `proj_context_set_search_paths`. So, not entirely a change that is required. It just seemed more of a gotcha. But, the behavior is documented, so it would be fine to leave as is if you prefer.
