### ISSUE TITLE
proj_create_from_name & lowercase UTM zone letter errors

### ISSUE THREAD

**Issue by snowman2** [OSGeo/PROJ#2332]
From `pyproj` build: https://travis-ci.com/github/pyproj4/pyproj/jobs/375162263#L3540

#### Example of problem

pseudo code of what is being run:
```c
const PJ_TYPE types[] = {PJ_TYPE_CONVERSION};
proj_create_from_name(
            nullptr,
            nullptr,
            "UTM zone 2s",
            &types,
            1,
            false,
            1,
            nullptr,
)

```
#### Problem description

Unable to find the coordinate operation.

#### Expected Output

Success

#### Environment Information
 - PROJ version: 7.2 (latest)
 - Operation System Information: Ubuntu 18.04

#### Installation method
 - from source

Is this change expected? It works in the 7.1 release.

**Comment by rouault** [comment]
> Is this change expected?

yes, more or less. I changed something recently so that exact name matching is exact (the use of LIKE caused issues). You should probably be able to workaround that by specifying approximateMatch = true

**Comment by snowman2** [comment]
Thanks for verifying 👍

**Comment by rouault** [comment]
Actually, there is an easy fix to get the previous behaviour. Fix underway too

**Comment by snowman2** [comment]
Thanks 👍
