### ISSUE TITLE
Results changes with cct and +init=ITRF2008:ITRF2000

### ISSUE THREAD

**Issue by snowman2** [OSGeo/PROJ#2333]
#### Example of problem

PROJ 7.1:
```bash
echo 3513638.19380 778956.45250 5248216.46900 2008.75 | cct +init=ITRF2008:ITRF2000
 3513638.1999    778956.4533  5248216.4535     2008.7500
```
PROJ 7.2 (latest)
```bash
echo 3513638.19380 778956.45250 5248216.46900 2008.75 | ./cct +init=ITRF2008:ITRF2000
 3513638.1928    778956.4517  5248216.4427     2008.7500
```
#### Problem description

Difference of ~0.01. Not sure if it matters or not. Just noticed it and wanted to make sure it is expected.

**Comment by rouault** [comment]
Indeed a bug. Side-effect of 3dc92ad7014e1cf20a3bc95c8c21a34a371fcb78 . Fix under way

**Comment by rouault** [comment]
Thanks for raising!
