### ISSUE TITLE
"swung to plane" cartographic projection

### ISSUE THREAD

**Issue by emhere** [OSGeo/PROJ#2338]
as seen in these papers:
["Rectangling Stereographic Projection for Wide-Angle Image Visualization"](https://openaccess.thecvf.com/content_iccv_2013/papers/Chang_Rectangling_Stereographic_Projection_2013_ICCV_paper.pdf)

["Generating a Perspective Image from a Panoramic Image by the Swung-to-Cylinder Projection"](https://www.semanticscholar.org/paper/Generating-a-Perspective-Image-from-a-Panoramic-by-Chang-Lai/4f46c3445bf3948cd04e7d2443ad1c58d0e61e1a)
(this paper provides an example of what a 360deg swung to plane projection would look like and adds a variation on it)

I'm very curious how this would look on a map, it seems promising :)

**Comment by Motet666** [comment]
Hello, sorry to disturb you, have you solved it?

**Comment by Motet666** [comment]
When I wrote the code, I found that the image that should have been a rectangle turned into a triangle. How can I solve this problem?：）
