### ISSUE TITLE
`ENU` not mentioned in `PROJ_COORD` datatype documentation

### ISSUE THREAD

**Issue by megies** [OSGeo/PROJ#2343]
Documentation for `PROJ_COORD` is not mentioning `.enu` usage. It is shown in the [development mini example](https://github.com/OSGeo/PROJ/blob/f6a9bbbc584c6a3633bde04f151be930957c384f/examples/pj_obs_api_mini_demo.c#L80) but `.enu` is not listed in the [access options](https://github.com/OSGeo/PROJ/blob/8aba4d24b72631007c1c33b70bc1a908fa5d8319/docs/source/development/reference/datatypes.rst#complex-coordinate-types), in contrast to `.uvw`, `.xyz` etc.

**Comment by kbevers** [comment]
Fixed in 310fa2ce67113bc883a
