### ISSUE TITLE
Add option to ignore deprecated flag of operations in proj_create_operations

### ISSUE THREAD

**Issue by matherno** [OSGeo/PROJ#2349]
When obtaining a list of coordinate operations in proj_create_operations, there doesn't seem to be the option to allow deprecated operations.
We require the ability to see all coordinate operations, regardless of whether they are deprecated or not.

**Comment by rouault** [comment]
Use ``proj_operation_factory_context_set_discard_superseded(ctx, factory_ctx, FALSE)``

**Comment by matherno** [comment]
Already using that option, and that allows superseded coordinate operations, but not deprecated coordinate operations.

**Comment by rouault** [comment]
> and that allows superseded coordinate operations, but not deprecated coordinate operations.

ah sorry, indeed. Why would you need deprecated coordinate operations ? Can you give an example of what your are attempting and would like to see as a result ?

**Comment by matherno** [comment]
In our application we list the possible coordinate operations between any two coordinate systems. The user can select from that list to choose which coordinate operation to use. We need to do this because users could have legacy data that they need to transform, and the "best coordinate operation" isn't always the one they would want to use. We need to also include deprecated coordinate operations in this list, in the case that users will want to use them.

**Comment by rouault** [comment]
In EPSG, 'deprecated' tends to mean broken, at least for CRS definitions. Not completely sure for coordinate operations themselves
