### ISSUE TITLE
ProjJson 0.2 Schema Incorrect for Prime Meridian?

### ISSUE THREAD

**Issue by mlptownsend** [OSGeo/PROJ#2354]
#### Problem description
Love the projjson schema and output, but I may have found a problem with the prime_meridian definition. If you output EPSG:22300 and EPSG:31293, you'll see the difference.

EPSG:22300:
```
"prime_meridian": {
"name": "Paris",
"longitude": {
  "value": 2.5969213,
  "unit": {
	"type": "AngularUnit",
	"name": "grad",
	"conversion_factor": 0.0157079632679489
  }
}
}
```

EPSG:31293:
```
"prime_meridian": {
"name": "Ferro",
"longitude": -17.6666666666667
}
```

The 0.2 schema defines the prime_meridian as seen in 22300 with longitude as value and unit, but it doesn't seem to account for the version seen in 31293 which has longitude as a number only.

Or maybe it's a problem with how projinfo is spitting out EPSG:31293 as projjson?

#### Environment Information
PROJ 7, Windows 10 x64.

#### Installation method
Built from source.

Full outputs of "projinfo -o projjson EPSG:22300 -q" and "projinfo -o projjson EPSG:31293 -q" attached.
[22300.txt](https://github.com/OSGeo/PROJ/files/5234979/22300.txt)
[31293.txt](https://github.com/OSGeo/PROJ/files/5234980/31293.txt)

**Comment by rouault** [comment]
Was indeed a bug of the schema

**Comment by kbevers** [comment]
@rouault should the schema version be bumped to 0.2.1 after this fix?

**Comment by rouault** [comment]
> should the schema version be bumped to 0.2.1 after this fix?

I considered that a bit, but here it is a bug of the schema. I believe that issuing a new schema version should be done only if PROJ emits something different from before. But perhaps I can change the "description": "Schema for PROJJSON" to "description": "Schema for PROJJSON (v0.2.1)" inside the schema ?

**Comment by kbevers** [comment]
> But perhaps I can change the "description": "Schema for PROJJSON" to "description": "Schema for PROJJSON (v0.2.1)" inside the schema ?

Yes, I think that's a good compromise.
