### ISSUE TITLE
cs2cs EPSG:4978  EPSG:26910 produces the same results for all inputs

### ISSUE THREAD

**Issue by glirellus** [OSGeo/PROJ#2367]
>cs2cs EPSG:4978  EPSG:26910
-122.07673673964236 37.414399665701325
500000.00       9997964.94 -6356752.31
-121.96378874329872 37.771039372647678
500000.00       9997964.94 -6356752.31
-122.14050065828438 47.660245267458592
500000.00       9997964.94 -6356752.31

>projinfo -s EPSG:4978 -t EPSG:26910
Candidate operations found: 1
Note: using '--spatial-test intersects' would bring more results (6)
-------------------------------------
Operation No. 1:

unknown id, Conversion from WGS 84 (geocentric) to WGS 84 (geog2D) + Inverse of NAD83 to WGS 84 (1) + UTM zone 10N, 4 m, North America - Canada and USA (CONUS, Alaska mainland)

PROJ string:
+proj=pipeline +step +inv +proj=cart +ellps=WGS84 +step +proj=utm +zone=10 +ellps=GRS80

WKT2:2019 string:
CONCATENATEDOPERATION["Conversion from WGS 84 (geocentric) to WGS 84 (geog2D) + Inverse of NAD83 to WGS 84 (1) + UTM zone 10N",
    SOURCECRS[
        GEODCRS["WGS 84",
            DATUM["World Geodetic System 1984",
                ELLIPSOID["WGS 84",6378137,298.257223563,
                    LENGTHUNIT["metre",1]]],
            PRIMEM["Greenwich",0,
                ANGLEUNIT["degree",0.0174532925199433]],
            CS[Cartesian,3],
                AXIS["(X)",geocentricX,
                    ORDER[1],
                    LENGTHUNIT["metre",1]],
                AXIS["(Y)",geocentricY,
                    ORDER[2],
                    LENGTHUNIT["metre",1]],
                AXIS["(Z)",geocentricZ,
                    ORDER[3],
                    LENGTHUNIT["metre",1]],
            ID["EPSG",4978]]],
    TARGETCRS[
        PROJCRS["NAD83 / UTM zone 10N",
            BASEGEOGCRS["NAD83",
                DATUM["North American Datum 1983",
                    ELLIPSOID["GRS 1980",6378137,298.257222101,
                        LENGTHUNIT["metre",1]]],
                PRIMEM["Greenwich",0,
                    ANGLEUNIT["degree",0.0174532925199433]],
                ID["EPSG",4269]],
            CONVERSION["UTM zone 10N",
                METHOD["Transverse Mercator",
                    ID["EPSG",9807]],
                PARAMETER["Latitude of natural origin",0,
                    ANGLEUNIT["degree",0.0174532925199433],
                    ID["EPSG",8801]],
                PARAMETER["Longitude of natural origin",-123,
                    ANGLEUNIT["degree",0.0174532925199433],
                    ID["EPSG",8802]],
                PARAMETER["Scale factor at natural origin",0.9996,
                    SCALEUNIT["unity",1],
                    ID["EPSG",8805]],
                PARAMETER["False easting",500000,
                    LENGTHUNIT["metre",1],
                    ID["EPSG",8806]],
                PARAMETER["False northing",0,
                    LENGTHUNIT["metre",1],
                    ID["EPSG",8807]]],
            CS[Cartesian,2],
                AXIS["(E)",east,
                    ORDER[1],
                    LENGTHUNIT["metre",1]],
                AXIS["(N)",north,
                    ORDER[2],
                    LENGTHUNIT["metre",1]],
            ID["EPSG",26910]]],
    STEP[
        CONVERSION["Conversion from WGS 84 (geocentric) to WGS 84 (geog2D)",
            METHOD["Geographic/geocentric conversions",
                ID["EPSG",9602]]]],
    STEP[
        COORDINATEOPERATION["Inverse of NAD83 to WGS 84 (1)",
            SOURCECRS[
                GEOGCRS["WGS 84",
                    DATUM["World Geodetic System 1984",
                        ELLIPSOID["WGS 84",6378137,298.257223563,
                            LENGTHUNIT["metre",1]]],
                    PRIMEM["Greenwich",0,
                        ANGLEUNIT["degree",0.0174532925199433]],
                    CS[ellipsoidal,2],
                        AXIS["geodetic latitude (Lat)",north,
                            ORDER[1],
                            ANGLEUNIT["degree",0.0174532925199433]],
                        AXIS["geodetic longitude (Lon)",east,
                            ORDER[2],
                            ANGLEUNIT["degree",0.0174532925199433]],
                    ID["EPSG",4326]]],
            TARGETCRS[
                GEOGCRS["NAD83",
                    DATUM["North American Datum 1983",
                        ELLIPSOID["GRS 1980",6378137,298.257222101,
                            LENGTHUNIT["metre",1]]],
                    PRIMEM["Greenwich",0,
                        ANGLEUNIT["degree",0.0174532925199433]],
                    CS[ellipsoidal,2],
                        AXIS["geodetic latitude (Lat)",north,
                            ORDER[1],
                            ANGLEUNIT["degree",0.0174532925199433]],
                        AXIS["geodetic longitude (Lon)",east,
                            ORDER[2],
                            ANGLEUNIT["degree",0.0174532925199433]],
                    ID["EPSG",4269]]],
            METHOD["Geocentric translations (geog2D domain)",
                ID["EPSG",9603]],
            PARAMETER["X-axis translation",0,
                LENGTHUNIT["metre",1],
                ID["EPSG",8605]],
            PARAMETER["Y-axis translation",0,
                LENGTHUNIT["metre",1],
                ID["EPSG",8606]],
            PARAMETER["Z-axis translation",0,
                LENGTHUNIT["metre",1],
                ID["EPSG",8607]],
            OPERATIONACCURACY[4.0],
            ID["INVERSE(DERIVED_FROM(EPSG))",1188],
            REMARK["Derived at 354 stations."]]],
    STEP[
        CONVERSION["UTM zone 10N",
            METHOD["Transverse Mercator",
                ID["EPSG",9807]],
            PARAMETER["Latitude of natural origin",0,
                ANGLEUNIT["degree",0.0174532925199433],
                ID["EPSG",8801]],
            PARAMETER["Longitude of natural origin",-123,
                ANGLEUNIT["degree",0.0174532925199433],
                ID["EPSG",8802]],
            PARAMETER["Scale factor at natural origin",0.9996,
                SCALEUNIT["unity",1],
                ID["EPSG",8805]],
            PARAMETER["False easting",500000,
                LENGTHUNIT["metre",1],
                ID["EPSG",8806]],
            PARAMETER["False northing",0,
                LENGTHUNIT["metre",1],
                ID["EPSG",8807]],
            ID["EPSG",16010]]],
    USAGE[
        SCOPE["unknown"],
        AREA["North America - Canada and USA (CONUS, Alaska mainland)"],
        BBOX[23.81,-172.54,86.46,-47.74]]]

```
for the pairing of EPSG:4978  EPSG:26910  (as well as some other pairings involving EPSG:4978), the output coordinates are always the same two numbers no matter what the input coordinates are. If there were an error or invalid inputs I would expect there to be an error message (for example, when I put in deliberately bad information I get "*" or "Inf" instead of numbers).  ProjInfo indicates that the input coordinates are well within the allowed range of coordinates for this projection. 

#### Expected Output
>cs2cs EPSG:4978  EPSG:26910
-122.07673673964236 37.414399665701325
581701.31  4141244.65
-121.96378874329872 37.771039372647678
591259.96  4180917.35
-122.14050065828438 47.660245267458592
564534.40  5278896.82


#### Environment Information
 - PROJ version 7.1.1
 - Operation System Windows 10

#### Installation method
 Building on Windows with vcpkg and Visual Studio 2019

**Comment by rouault** [comment]
EPSG:4978 is a geocentric CRS. Your input coordinates are geographic coordinates here, so when interpretated as geocentric coordinates, quite close to the center of Earth, hence the same output if you move from the center of earth within one meter :-)

You probably rather want to use EPSG:4326, and when doing so, you must provide the coordinates in latitude, longitude order rather than longitude, latitude

```
echo 37.414399665701325 -122.07673673964236 | cs2cs EPSG:4326 EPSG:26910
581701.31	4141244.65 0.00
```

So not a bug.

**Comment by glirellus** [comment]
Thanks!
