### ISSUE TITLE
Incorrect transform on IGNF:NTFP crs

### ISSUE THREAD

**Issue by NicoIGN** [OSGeo/PROJ#2374]
**With Proj7.1.0 (tested with 7.1.1 as well):**
./cs2cs +init=IGNF:LAMB93 +to +init=IGNF:NTFP  -v -f %.15f << EOF
> 652760.737 7033791.243 0
> EOF

>  From Coordinate System
> +init=IGNF:LAMB93
> To Coordinate System
> +init=IGNF:NTFP
0.000024264131890	50.400011551482990 0.000000000000000

 **--> this is not correct (Greenwich meridian?)**

**With PROJ4, it is correct**
../../proj-4.8.0/bin/cs2cs +init=IGNF:LAMB93 +to +init=IGNF:NTFP  -v -f %.15f << EOF
> 652760.737 7033791.243 0
> EOF

>  From Coordinate System
> Lambert Conformal Conic
> 	Conic, Sph&Ell
> 	lat_1= and lat_2= or lat_0
>  +init=IGNF:LAMB93 +proj=lcc +towgs84=0.0000,0.0000,0.0000 +a=6378137.0000
>  +rf=298.2572221010000 +lat_0=46.500000000 +lon_0=3.000000000
>  +lat_1=44.000000000 +lat_2=49.000000000 +x_0=700000.000 +y_0=6600000.000
>  +geoidgrids=RAF09.gtx,RAC09.gtx,geoidnull.gtx +units=m +no_defs
> following specified but NOT used
>  +title=Lambert +93
>  To Coordinate System
> Lat/long (Geodetic alias)
> 	
>  +init=IGNF:NTFP +proj=longlat +nadgrids=ntf_r93.gsb,null +a=6378249.2000
>  +rf=293.4660210000000 +pm=2.337229167
>  +geoidgrids=RAF09.gtx,RAC09.gtx,geoidnull.gtx +units=m +no_defs
> following specified but NOT used
>  +title=Nouvelle +Triangulation +Francaise +Paris +grades
>  +towgs84=-168.0000,-60.0000,320.0000

0.000000002611831	50.399999995332799 -0.000063250378489

#### Installation method
MacOSX 10.12.6 / user-compilation

**Comment by rouault** [comment]
> **--> this is not correct (Greenwich meridian?)**

no, that's not the issue.
Did you make sure that you have the PROJ-data grids installed (https://download.osgeo.org/proj/proj-data-1.2.zip) in the PROJ data directory (/usr/share/proj typically) or at the very least the ntf_r93.gsb grid (or its geotiff version: https://cdn.proj.org/fr_ign_ntf_r93.tif)
With that grid installed, I get: ``0.000000002945194	50.399999996259041 0.000000000000000`` as a result. The different with the PROJ 4.8 result is ~ 0.1 mm.

The result ``0.000024264131890 50.400011551482990 0.000000000000000`` is when using only the Helmert transformation

**Comment by rouault** [comment]
I should also note that you use the deprecated +init=IGNF: syntax. One key difference is that in this mode  +init=IGNF:NTFP is interpreted as being in geographic coordinates in degrees (for compat with PROJ.4), whereas if you use IGNF:NTFP it will return grads which is correct with respect to the definition of the CRS.

**Comment by NicoIGN** [comment]
Ok, thank you for this precision, I hadn't noticed that one. I'm actually migrating softwares from PROJ4 to PROJ7 so I prefer being as close as the old lib as possible for now.

**Comment by rouault** [comment]
I should amend a bit what I mentionned before: if you use cs2cs, then it will output (input) degrees where grad would normally been expected. But if you use the newer projinfo and cct utilities, they will use grads as "expected"

And if you use the corresponding EPSG codes, and you've the fr_ign_gr3df97a.tif grid installed, then it will use the geocentric adjustment method, which should give results identical or very close to Circe (result is in lat, lon order, as mandated by the axis order of EPSG:4807)
```
echo "652760.738 7033791.243 0" | cs2cs -f "%.10f" EPSG:2154 EPSG:4807
50.3999999966	0.0000000235 0.0000000000
```
