### ISSUE TITLE
TM documentation is out of date

### ISSUE THREAD

**Issue by cffk** [OSGeo/PROJ#2375]
#### The documentation of the transverse Mercator projection needs to be updated
Current figure + documentation reflects the Snyder/Evenden method.  This should be supplemented (replaced?) by a figure and documentation for the Poder/Engsager method.

I will take a crack at adding the formulas.  Maybe @hobu for the figure?

**Comment by hobu** [comment]
> Maybe @hobu for the figure?

I think it is time to build the images for every documentation build as part of CI. I will implement it with Github Actions.

**Comment by hobu** [comment]
Builder implemented in #2377 2377

**Comment by rouault** [comment]
We'll still need to manually run plot.sh to refresh docs/plot/images, which is used to build the live documentation (or off-line one if you do 'make html' locally), right ?

**Comment by hobu** [comment]
My hope is documentation build and push will also push latest images as well instead of stale ones in the git repository. Some more discussion is maybe needed in regard to that however.

**Comment by cffk** [comment]
This is closest by #2379
