### ISSUE TITLE
Bumping vcpkg version to 7.1.1

### ISSUE THREAD

**Issue by Matioupi** [OSGeo/PROJ#2391]
Hello,

while trying to bump the vcpkg port version of proj to 7.1.1 withing this PR : https://github.com/microsoft/vcpkg/pull/14143

I faced some errors with the uwp triplet builds. I'm not using them myself, but they were building properly with version 6.x

So far, errors look like :

     6>C:\src\vcpkg\buildtrees\proj4\src\7.1.1-094056a32a.clean\src\filemanager.cpp(695,24): error C3861: 'CreateFileW': identifier not found [C:\src\vcpkg\buildtrees\proj4\x64-uwp-dbg\src\proj.vcxproj]
     6>C:\src\vcpkg\buildtrees\proj4\src\7.1.1-094056a32a.clean\src\filemanager.cpp(1215,34): error C2065: 'FOLDERID_LocalAppData': undeclared identifier [C:\src\vcpkg\buildtrees\proj4\x64-uwp-dbg\src\proj.vcxproj]
     6>C:\src\vcpkg\buildtrees\proj4\src\7.1.1-094056a32a.clean\src\filemanager.cpp(1215,13): error C3861: 'SHGetKnownFolderPath': identifier not found [C:\src\vcpkg\buildtrees\proj4\x64-uwp-dbg\src\proj.vcxproj]
     6>C:\src\vcpkg\buildtrees\proj4\src\7.1.1-094056a32a.clean\src\filemanager.cpp(1314,27): error C2065: 'GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS': undeclared identifier [C:\src\vcpkg\buildtrees\proj4\x64-uwp-dbg\src\proj.vcxproj]
     6>C:\src\vcpkg\buildtrees\proj4\src\7.1.1-094056a32a.clean\src\filemanager.cpp(1315,31): error C2065: 'GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT': undeclared identifier [C:\src\vcpkg\buildtrees\proj4\x64-uwp-dbg\src\proj.vcxproj]
     6>C:\src\vcpkg\buildtrees\proj4\src\7.1.1-094056a32a.clean\src\filemanager.cpp(1314,9): error C3861: 'GetModuleHandleEx': identifier not found [C:\src\vcpkg\buildtrees\proj4\x64-uwp-dbg\src\proj.vcxproj]

and all seems to fall within the filemanager.cpp file which was not there in 6.x. One of those error is related to the fact that CreateFileW (or CreateFile) do not exist for uwp :

https://github.com/OSGeo/PROJ/blob/e6a992b59985e51e2d205fe56c1abecc4a10ffd0/src/filemanager.cpp#L695

what are the maintenainers thoughts about this ? do you consider helping in handling new proj version from within vcpkg (which in my opinion is a nice package handling system) ?

Regards

Mathieu

**Comment by kbevers** [comment]
> what are the maintenainers thoughts about this ?

If you, or someone else, can provide a patch that fixes this it is quite likely we will merge it.

> do you consider helping in handling new proj version from within vcpkg (which in my opinion is a nice package handling system) ?

I can't speak for the rest of the team but personally I am no interested in that. In my opinion it's better to leave that to the wider community in the hands of someone more familiar with vcpg than I am (and I suspect the rest of the PROJ team). With that said, feedback from packagers is greatly valued and have over the years led to many improvements to PROJ.

**Comment by Matioupi** [comment]
Thanks for your answer. I doubt I will either put much energy in patching for uwp that I will not use...
I've been looking to the CreateFile API and the CreateFile2 API is available for uwp with minor signature changes, but the other issues remain and I have not found straightforward ways to patch them

I don't know if missing the uwp ports in vcpkg would prevent bumping the PROJ version on the main repo... If it does, I will probably consider going with my own fork where I don't care uwp and maintenance / upgrade of versions is easier !
