### ISSUE TITLE
Rationale for having the PROJ_LIB compile time string tested last

### ISSUE THREAD

**Issue by Matioupi** [OSGeo/PROJ#2399]
Hello,
I've seen a few issues about the PROJ lib environment variable / compilte time variable, I hope it's not a duplicate.

is there a rationale (that I missed) for having the PROJ_LIB compile time preprocessor variable tested at the very end of the sequence of default path search ?

https://github.com/OSGeo/PROJ/blob/64d46a6b2939272a0590d3e149ffec5b9ec0336f/src/filemanager.cpp#L1608

I would personnaly prefer to give priority to the library hard-coded value if there is one defined at compile time.
If I understand current implementation (and observed behaviour), it's the opposite : the hardcoded internal path is tested in very last position and actually skipped if a PROJ_LIB environment variable is present.

What about adding a compile time switch to either build a proj lib with priority to compile time hard-coded value, or use the current implementation ?

**Comment by rouault** [comment]
I'm afraid people will never agree on the order into which things are tested. A rationale for PROJ_LIB env var having precedence on the compile time hardcoded value is that sometimes installation is moved away from its installation prefix (like Conda-based installs I believe)

**Comment by Matioupi** [comment]
I agree this will probably never reach a consensus. That's why I was proposing (and can do a PR for this) a compile time switch to propose both behaviour :

When building the lib targetting a system wide installation (usually unix environment philosphy) , then I agree that the PROJ_LIB env var priority is better, but when building the lib in order to integrate it as a part of a specific piece of software (as many MS Windows software do), I would prefer that a later install of another software using PROJ do not interfer with my software (e.g. when installing OSGEO4W the variable get set and this can mess up other instances of the dll) And this is a real world scenario that I actually faced.

**Comment by jmckenna** [comment]
Agreed @Matioupi in fact I recently mentioned a similar issue on the gdal-dev list when testing GDAL 3.1.4 release candidate (with PROJ-master) on Windows.  +1

**Comment by rouault** [comment]
https://github.com/OSGeo/PROJ/pull/2476 is an attempt at addressing this issue. Please check that it works as intended

**Comment by Matioupi** [comment]
I will test that, thanks !

**Comment by rouault** [comment]
@Matioupi  any feedback on PR #2476 ?
