### ISSUE TITLE
Failure to transform/apply a vertical shift grid on lon/lat/elevation coordinates

### ISSUE THREAD

**Issue by nirvn** [OSGeo/PROJ#2414]
#### Example of problem

The following code attempting to apply a vertical shift grid fails, returning inf values.

```
    std::vector< double > xVector = { 14.4072 };
    std::vector< double > yVector = { 47.6275 };
    std::vector< double > zVector = { 10.0 };
    PJ *P = proj_create( PJ_DEFAULT_CTX, QStringLiteral( "+proj=vgridshift +grids=at_bev_GV_Hoehengrid_V1.tif" ).toUtf8().constData() );
    proj_trans_generic( P, PJ_FWD,
                        xVector.data(), sizeof( double ), 1,
                        yVector.data(), sizeof( double ), 1,
                        zVector.data(), sizeof( double ), 1,
                        nullptr, sizeof( double ), 0);
    int err = proj_errno( P );
    qDebug() << QString( "Output %1 %2 %3 (%4)" ).arg( xVector[0] ).arg( yVector[0] ).arg( zVector[0] ).arg( QString::fromUtf8( proj_errno_string( err ) ) );
    proj_destroy( P );
```

The debug output printed in the console is `Output inf inf inf (latitude or longitude exceeded limits)`.

I'm perplexed as if I check this operation via cct, it works. E.g. the following command:

`echo 14.4072 47.6275 100.0 | cct +proj=vgridshift +grids=at_bev_GV_Hoehengrid_V1.tif`

returns

` 14.4072000000   47.6275000000      100.1976           inf`

**Comment by rouault** [comment]
cct has some extra intelligence and does a degree -> radian conversion for you when it sees that the projection expects values to be provided as angular/geographic coordinates (using proj_angular_input() and proj_torad())

If you don't want to do the conversion of the values, you can modify your pipeline to be "+proj=pipeline +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=vgridshift +grids=at_bev_GV_Hoehengrid_V1.tif +step +proj=unitconvert +xy_in=rad +xy_out=deg"

**Comment by nirvn** [comment]
@rouault , fantastic, thanks for the explanation.

If you could help clarifying one more detail, I'd appreciate it. When you use the command I pasted above (ie `echo 14.4072 47.6275 100.0 | cct +proj=vgridshift +grids=at_bev_GV_Hoehengrid_V1.tif`), is proj expecting WGS84 longitude latitude coordinates as input?

**Comment by rouault** [comment]
> is proj expecting WGS84 longitude latitude coordinates as input?

it is expected longitude, latitude yes. But not necessarily WGS84. That depends on the grid.  For that one, that should be in MGI / EPSG:4312

**Comment by nirvn** [comment]
@rouault , ah good. So, if the starting point is WGS84 lon,lat, that should be re-projected to EPSG:4312 first, then the vgridshift applied afterward?

**Comment by rouault** [comment]
>  So, if the starting point is WGS84 lon,lat, that should be re-projected to EPSG:4312 first, then the vgridshift applied afterward?

yes, also make sure to apply the grid in the right direction. Due to historical reason, PROJ substracts the value in the grid. If you want to go from GHA height to EVRF2000 Austria height, you need to add +multiplier=1
