### ISSUE TITLE
License only covering Proj.4?

### ISSUE THREAD

**Issue by danme74** [OSGeo/PROJ#2415]
The file COPYING contains information about licenses. As stated in master right now (2020-11-05) it only applies to Proj.4.

I assume license applies to the current code base and should be updated to reflect that.

I also suggest renaming COPYING to something more obvious such as LICENSE or LICENSE.TXT, but that's up to you. ("License" feels like a broader and more correct term than "copying".)

I would also prefer if the license information was part of the installation, similar to how GDAL (and other libraries) handle it:
/usr/share/doc/gdal-libs-1.11.4/LICENSE.TXT

**Comment by rouault** [comment]
> I also suggest renaming COPYING to something more obvious such as LICENSE or LICENSE.TXT

COPYING is a standard filename for a autoconf/automake project. See https://www.gnu.org/software/automake/manual/automake.html#Gnits

**Comment by hobu** [comment]
> I also suggest renaming COPYING to something more obvious such as LICENSE or LICENSE.TXT,

I disagree that COPYING is any more obvious than LICENSE. It's just the GNU way.
