### ISSUE TITLE
proj_factors

### ISSUE THREAD

**Issue by NicoIGN** [OSGeo/PROJ#2416]
Hi,

I'm struggling to compute the scale factor and the meridian convergence from a PJ object. I'm working with the C++ API, but even with the executable proj, it doesn't seem to work properly:

echo 600000 2200000 | proj +init=IGNF:LAMBE -SV

sends back 

> Lambert Conformal Conic
>  Conic, Sph&Ell
>  lat_1= and lat_2= or lat_0, k_0=
>  +init=IGNF:LAMBE +proj=lcc +lat_1=46.8 +lat_0=46.8 +lon_0=0 +k_0=0.99987742
>  +x_0=600000 +y_0=2200000 +ellps=clrk80ign +pm=paris +units=m +no_defs
> --- following specified but NOT used
>  +type=crs
> Final Earth figure: ellipsoid
>   Major axis (a): 6378249.200
>   1/flattening: 293.466021
>   squared eccentricity: 0.006803487646
> Rel. 7.0.0, March 1st, 2020
> <proj>: while processing file: <stdin>, line 1
>  
> latitude or longitude exceeded limits

C++ try (and fail):

```

> PJ* my_proj = proj_create(nullptr, "+init=IGNF:LAMBE");
> 
> //is it right? :
> my_proj->fwd = pj_fwd; 
> 
> PJ_COORD coord;
> //some code that convert the cartographic coordinates (600000, 2200000) in geographic coordinates in radian (that work properly)
> ...
> ...
> ...
> 
> PJ_FACTORS facs = proj_factors(my_proj, coord);
> 
> return facs.meridian_convergence;

```

What's wrong? Bug in the code or misunderstanding from me.

Thanks a lot,

**Comment by kbevers** [comment]
You haven't got much patience, eh?

Your problem is that you are feeding projected coordinates into `proj` when it expects geodetic coordinates. If you do the inverse transformation you get what you want:

```
$ echo 600000 2200000 | proj -I +init=IGNF:LAMBE -SV
#Lambert Conformal Conic
#       Conic, Sph&Ell
#       lat_1= and lat_2= or lat_0, k_0=
# +init=IGNF:LAMBE +proj=lcc +lat_1=46.8 +lat_0=46.8 +lon_0=0 +k_0=0.99987742
# +x_0=600000 +y_0=2200000 +ellps=clrk80ign +pm=paris +units=m +no_defs
#--- following specified but NOT used
# +type=crs
#Final Earth figure: ellipsoid
#  Major axis (a): 6378249.200
#  1/flattening: 293.466021
#  squared eccentricity: 0.006803487646
Longitude: 2d20'14.025"E [ 2.3372291667 ]
Latitude:  46d48'N [ 46.8 ]
Easting (x):   600000.000
Northing (y):  2200000.000
Meridian scale (h) : 0.99987742  ( -0.01226 % error )
Parallel scale (k) : 0.99987742  ( -0.01226 % error )
Areal scale (s):     0.99975485  ( -0.02451 % error )
Angular distortion (w): 0.000
Meridian/Parallel angle: 90.00000
Convergence : 1d42'13.56" [ 1.70376674 ]
Max-min (Tissot axis a-b) scale error: 0.99988 0.99988
```

**Comment by NicoIGN** [comment]
Ok thank you for the swift answer.

That means we should change the sign of the result if we make the reverse transfo, right? I don't really understand why it's not possible to compute the meridian convergence this way but at least i could move forward with my work, thanks again!

Nicolas


________________________________
De : Kristian Evers [notifications@github.com]
Envoyé : jeudi 5 novembre 2020 17:21
À : OSGeo/PROJ
Cc : Nicolas Bellaiche; Author
Objet : Re: [OSGeo/PROJ] proj_factors (#2416)


You haven't got much patience, eh?

Your problem is that you are feeding projected coordinates into proj when it expects geodetic coordinates. If you do the inverse transformation you get what you want:

$ echo 600000 2200000 | proj -I +init=IGNF:LAMBE -SV
#Lambert Conformal Conic
#       Conic, Sph&Ell
#       lat_1= and lat_2= or lat_0, k_0=
# +init=IGNF:LAMBE +proj=lcc +lat_1=46.8 +lat_0=46.8 +lon_0=0 +k_0=0.99987742
# +x_0=600000 +y_0=2200000 +ellps=clrk80ign +pm=paris +units=m +no_defs
#--- following specified but NOT used
# +type=crs
#Final Earth figure: ellipsoid
#  Major axis (a): 6378249.200
#  1/flattening: 293.466021
#  squared eccentricity: 0.006803487646
Longitude: 2d20'14.025"E [ 2.3372291667 ]
Latitude:  46d48'N [ 46.8 ]
Easting (x):   600000.000
Northing (y):  2200000.000
Meridian scale (h) : 0.99987742  ( -0.01226 % error )
Parallel scale (k) : 0.99987742  ( -0.01226 % error )
Areal scale (s):     0.99975485  ( -0.02451 % error )
Angular distortion (w): 0.000
Meridian/Parallel angle: 90.00000
Convergence : 1d42'13.56" [ 1.70376674 ]
Max-min (Tissot axis a-b) scale error: 0.99988 0.99988

**Comment by busstoptaktik** [comment]
> That means we should change the sign of the result if we make the reverse transfo, right?

Wrong. The meridian convergence is a property of the lines of *constant longitude* in the projected plane. Hence, you should obviously specify *at which longitude* (and latitude) you want your result.

Also, please raise (and keep) this kind of questions on the PROJ mailing list, where they belong.
