### ISSUE TITLE
Geocentric translation grid interpolation with cartesian source and target crs

### ISSUE THREAD

**Issue by himsve** [OSGeo/PROJ#2433]
Geocentric translation with grid Interpolation works with geographic source and target crs's, but have an issue where it would be useful with cartesian (geocentic) source and target crs'es. 

We have a residual model in GeoTiff referred in a geocentric crs, whereas is used in a long chain with several transformation steps. The chain was original written as proj string pipeline, and we are porting the transformation steps to db records (sql inserts). The original proj string pipeline worked perfectly. 

I know, Proj is able to transform between geographic and geocentric crs'es, but in this case all transformation steps are performed geocentrical. In some cases Proj is not able to discover all geocentric from/to geographic transformations.

Here is a sample with inputs to db:

- Step 1: 
`INSERT INTO other_transformation VALUES('PROJ','CRS1_CRS2','From CRS1 to CRS2','','PROJ','PROJString','+proj=pipeline +ellps=GRS80 +step +proj=deformation +dt=14.58 +xy_grids=@deformation.ct2 +z_grids=@deformation.gtx +inv','PROJ','CRS1_geocentric','PROJ','CRS2_geocentric',................);`

- Step 2:
`INSERT INTO "helmert_transformation" VALUES('PROJ','CRS2_CRS3','From CRS2 to CRS3','','EPSG','1032','Coordinate Frame rotation (geocentric domain)','PROJ','CRS2_geocentric','PROJ','CRS3_geocentric',................);`
 
Coordinate operation CRS3_geocentric > CRS3_geographic3D is not discovered by proj.
 
- Step 3:
`INSERT INTO "grid_transformation" VALUES('PROJ','CRS3_CRS4','PGS_EUREF89 to ITRF2014','May be emulated using NTv2 method.','EPSG','1087','Geocentric translation by Grid Interpolation','PROJ','CRS3_geographic3D','PROJ','CRS4_geographic3D',................);`

Alternative, if we use "CRS2_geographic3D" and "CRS3_geographic3D" as source and target crs'es in step 2, proj did not discover the "CRS2_geocentric > CRS2_geographic3D" transformation between step 1 and 2.

(All CRSX_geocentric and CRSX_geographic3D are pointing back to the same geodetic_datum) 

By the way, time depended geodetic grid interpolation (deformation application) in "grid_transformation" would also solve this issue, instead of using "other_transformation" as we need (according to Step 1). I guess this enhaucement is planned in the future.

**Comment by rouault** [comment]
> Coordinate operation CRS3_geocentric > CRS3_geographic3D is not discovered by proj.

Your report isn't entirely clear to me. It would be better if you'd include the full SQL statements you add to the database (or at least the ones relevant for this report), and a "projinfo -s X -t Y" invokation that shows the issue

> By the way, time depended geodetic grid interpolation (deformation application) in "grid_transformation" would also solve this issue, instead of using "other_transformation" as we need (according to Step 1).

So transforming a coordinate from CRS_A@epoch1 to CRS_B@epoch2 using the time difference epoch2-epoch1 as the multiplier of grid coefficients ? I'm not sure there's a method in EPSG for that yet. The closest would be the operation method for the Canadian velocity grids that are point motion operation in the same CRS.

> I guess this enhencement is planned in the future.

There are certainly improvements possible regarding time-dependent transformations. In additions to PROJ enhancements (that would have to be funded), they might also require EPSG enhancements so we can rely on something "standard"

**Comment by kbevers** [comment]
> GeoTiff referred in a geocentric crs

I am curious, how does this work?

**Comment by himsve** [comment]
> > GeoTiff referred in a geocentric crs
> 
> I am curious, how does this work?

It works perfect as proj string. 

This is the original proj string: 
`+proj=pipeline
    +step +proj=cart
    +ellps=GRS80
    +step +proj=xyzgridshift +grids=TestGrid.tif`

We chose to work geocentrical instead of horisontally and vertically. Then we did not had to define any new vertical datums and crs'es. The geotiff is just a residual model with tiny corrections. The correction should fit the ITRF2014>ETRS89 tranformation into the fixed ETRS89 PGS stations.

**Comment by kbevers** [comment]
> We chose to work geocentrical instead of horisontally and vertically

But the grid is still indexed in lat/long coordinates, yes?

**Comment by himsve** [comment]
> > We chose to work geocentrical instead of horisontally and vertically
> 
> But the grid is still indexed in lat/long coordinates, yes?

Yes they did. Heights did not change, because pushpop->v3=true as default.

**Comment by himsve** [comment]
> > Coordinate operation CRS3_geocentric > CRS3_geographic3D is not discovered by proj.
> 
> Your report isn't entirely clear to me. It would be better if you'd include the full SQL statements you add to the database (or at least the ones relevant for this report), and a "projinfo -s X -t Y" invokation that shows the issue
  
> > By the way, time depended geodetic grid interpolation (deformation application) in "grid_transformation" would also solve this issue, instead of using "other_transformation" as we need (according to Step 1).
> 
> So transforming a coordinate from CRS_A@epoch1 to CRS_B@epoch2 using the time difference epoch2-epoch1 as the multiplier of grid coefficients ? I'm not sure there's a method in EPSG for that yet. The closest would be the operation method for the Canadian velocity grids that are point motion operation in the same CRS.
> 
> > I guess this enhencement is planned in the future.
> 
> There are certainly improvements possible regarding time-dependent transformations. In additions to PROJ enhancements (that would have to be funded), they might also require EPSG enhancements so we can rely on something "standard"

Hi.

It seems that I'm confusing you more than necessary.

Kartverket (KV) is realizing a transformations from ITRF2014 to the norwegian native EUREF89. The original transformation chain had like 10 steps, but we have simplify it. Hopefully 3-4 steps would be sufficient for the implementation.

Here is a part of original chain described as proj string:

`+proj=pipeline +ellps=GRS80
+step +proj=deformation +dt=14.58 +xy_grids=@Milne.ct2+z_grids=@RH2000LU_absup.gtx +inv"
+step +proj=helmert +convention=coordinate_frame +x=-0.0950 +y=0.0139 +z=-0.0748 +s=0.01424 +rx=-0.001044 +ry=-0.0141853 +rz=0.0155201 +exact
+step +proj=xyzgridshift +grids=PGS0817_NKGRF17_20200508.tif`

PGS0817_NKGRF17_20200508.tif is a residual model with X, Y and Z translations.

This proj string works perfectly. But, when we are implementing the steps in proj.db, we prefer to use either geocentric or 3D geographic source and target crs's. The coordinate operations "deformation",  "helmert" and "xyzgridshift" are not able to mix between geocentric and 3D geographic source and target crs's.

- "deformation" accepts only geocentric crs
- "helmert" accepts both
- "xyzgridshift" accepts only geographic crs

**Comment by kbevers** [comment]
> Kartverket (KV) is realizing a transformations from ITRF2014 to the norwegian native EUREF89

Just an FYI, the new NKG transformations are on their way to PROJ (hopefully the next version). Current state of the implementation [here](https://github.com/OSGeo/PROJ/compare/master...kbevers:nkg_transformations). Not sure if what you are doing is the same thing or not, just wanted to give you a heads up in case it is.

**Comment by himsve** [comment]
> > Kartverket (KV) is realizing a transformations from ITRF2014 to the norwegian native EUREF89
> 
> Just an FYI, the new NKG transformations are on their way to PROJ (hopefully the next version). Current state of the implementation [here](https://github.com/OSGeo/PROJ/compare/master...kbevers:nkg_transformations). Not sure if what you are doing is the same thing or not, just wanted to give you a heads up in case it is.

Yes, we fill mainly follow the NKG transformations.

**Comment by kbevers** [comment]
> Yes, we fill mainly follow the NKG transformations.

Mainly? Does that mean what you are doing now is different to the NKG transformations or the exact same? I am probably sidetracking the discussion but since I am working on implementing the NKG 2020 transformations I think it is quite important to understand what's going on here. There's no reason to have two versions of the same thing.

**Comment by himsve** [comment]
> > Yes, we fill mainly follow the NKG transformations.
> 
> Mainly? Does that mean what you are doing now is different to the NKG transformations or the exact same? I am probably sidetracking the discussion but since I am working on implementing the NKG 2020 transformations I think it is quite important to understand what's going on here. There's no reason to have two versions of the same thing.

We are planning to use the NKG transformation. But, since the native norwegian EUREF89 realization is a bit noisy we may have to use a correction grid between "NKG EUREF89" and "native EUREF89". First of all, we need to test how well the NKG transformation fits. I agree it could be confusing with two different versions, but since the native EUREF89 was re-realized back in 2010, it was made a transformation between ITRF2005 and native EUREF89 for norwegian applications. Therefore we need test the NKG transformation and maybe add a final correction grid to meet the demanded accuracy.

**Comment by kbevers** [comment]
> Therefore we need test the NKG transformation and maybe add a final correction grid to meet the demanded accuracy.

Right, that makes sense. If you build my `nkg_transformations` branch you can test out the NKG 2020 transformations and see how well they match your "native EUREF89". You should get an email with a bit more details soon, just need to make a few finishing touches.
