### ISSUE TITLE
Make Install Error: Permission denied

### ISSUE THREAD

**Issue by kenpryor67** [OSGeo/PROJ#2439]
#### Example of problem
I receive the following errors upon executing the "make install" command in the source directory:
20:47 ~/proj-4.9.3 $ make install
Making install in src
make[1]: Entering directory `/home/KenPryor67/proj-4.9.3/src'
make[2]: Entering directory `/home/KenPryor67/proj-4.9.3/src'
 /bin/mkdir -p '/usr/local/lib'
 /bin/bash ../libtool   --mode=install /usr/bin/install -c   libproj.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libproj.so.12.0.0 /usr/local/lib/libproj.so.12.0.0
/usr/bin/install: cannot create regular file '/usr/local/lib/libproj.so.12.0.0': Permission denied
make[2]: *** [install-libLTLIBRARIES] Error 1
make[2]: Leaving directory `/home/KenPryor67/proj-4.9.3/src'
make[1]: *** [install-am] Error 2
make[1]: Leaving directory `/home/KenPryor67/proj-4.9.3/src'
make: *** [install-recursive] Error 1

#### Environment Information
 - PROJ version (`proj`): 4.9.3
 - Operation System Information:
20:53 ~/proj-4.9.3 $ cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

#### Installation method
 - Installing from source

**Comment by kbevers** [comment]
This is not a PROJ problem. You problably just need to install as root or using `sudo`.

Also, please use a more recent version of PROJ. The current version is 7.2.0. 4.9.3 several years old and in no way lives up to modern standards.
