### ISSUE TITLE
WGS84 axis order affects choice of transformation to EPSG:6342

### ISSUE THREAD

**Issue by dg0yt** [OSGeo/PROJ#2442]
#### Example of problem
In dealing with GPX tracks from another continent, I spent some time analysing inconsistencies in transformations of WGS84 input coordinates to UTM13/NAD83 coordinates, depending on whether I used my own GPX code (using PROJ directly), or GDAL (using `OCTNewTransformation` etc.). I think that I was now able to isolate the root cause in PROJ. With these variables:

```sh
WGS84_LAT_LONG_GDAL="GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AXIS[\"Latitude\",NORTH],AXIS[\"Longitude\",EAST],AUTHORITY[\"EPSG\",\"4326\"]]"
WGS84_LONG_LAT_MINE="GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AXIS[\"Longitude\",EAST],AXIS[\"Latitude\",NORTH]]"

LON=-105.0084468
LAT=40.0149205
```
the output for WGS84_LAT_LONG_GDAL (i.e. EPSG:4326) to EPSG:6342 is: 
```sh
$ echo $LAT $LON 0 2019 | cs2cs -E "$WGS84_LAT_LONG_GDAL" "EPSG:6342"
40.0149205 -105.0084468 0	499279.14	4429413.28 0.00 2019
$ projinfo -s "$WGS84_LAT_LONG_GDAL" -t "EPSG:6342"
Candidate operations found: 1
-------------------------------------
Operation No. 1:

unknown id, Ballpark geographic offset from WGS 84 to NAD83(2011) + UTM zone 13N, unknown accuracy, World, has ballpark transformation

PROJ string:
+proj=pipeline +step +proj=axisswap +order=2,1 +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=utm +zone=13 +ellps=GRS80
[...]
```

However, for mine LONG_LAT definition (no authorative code) to EPSG:6342, the output is:
```sh
$ echo $LON $LAT 0 2019 | cs2cs -E "$WGS84_LONG_LAT_MINE" "EPSG:6342"
-105.0084468 40.0149205 0	499280.00	4429412.56 0.00 2019
$ projinfo -s "$WGS84_LONG_LAT_MINE" -t "EPSG:6342"
Candidate operations found: 1
-------------------------------------
Operation No. 1:

unknown id, axis order change (2D) + WGS_1984_(ITRF08)_To_NAD_1983_2011 + UTM zone 13N, 0.03 m, USA - CONUS and Alaska; PRVI

PROJ string:
+proj=pipeline +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=push +v_3 +step +proj=cart +ellps=WGS84 +step +proj=helmert +x=0.99343 +y=-1.90331 +z=-0.52655 +rx=0.02591467 +ry=0.00942645 +rz=0.01159935 +s=0.00171504 +convention=coordinate_frame +step +inv +proj=cart +ellps=GRS80 +step +proj=pop +v_3 +step +proj=utm +zone=13 +ellps=GRS80
[...]
```

#### Problem description

- Equivalent input coordinates give significantly different output.
- For the source coordinate system without authorative code, a more specific transformation pipeline is chosen.

#### Expected Output

- EPSG:6342 output coordinates should be identical.
- Transformations should differ only by an axis swap step.

#### Environment Information
 - PROJ version (`proj`): 7.1.1, compiled from source.
 - Operation System Information: Linux

#### Installation method
 - Build from source, PATH and LD_LIBRARY_PATH point to the install dir.

**Comment by rouault** [comment]
Interesting... To paraphrase Intel, PROJ behaves here as designed, even if the outcome is a bit unexpected. When using the EPSG:4326 definition, PROJ detects that it is a transformation between 2 CRS from the same authority, in particular EPSG here, and so it only looks for transformations available under the EPSG authority (or the PROJ one for overrides / customizations).

That behaviour is defined in the authority_to_authority_preference table of proj.db
```
$ echo "select source_auth_name,target_auth_name,allowed_authorities from authority_to_authority_preference;" | sqlite3 data/proj.db
any|EPSG|PROJ,EPSG,any
EPSG|EPSG|PROJ,EPSG
PROJ|EPSG|PROJ,EPSG
IGNF|EPSG|PROJ,IGNF,EPSG
ESRI|EPSG|PROJ,ESRI,EPSG
```

With the custom WGS84 with long, lat axis order, the CRS is no longer affiliated to EPSG, and thus PROJ looks for transformations declarated by any authority, and here it finds WGS_1984_(ITRF08)_To_NAD_1983_2011 (,ESRI:108363) which comes from ESRI. If you add a restriction to EPSG, with ``projinfo -s "$WGS84_LONG_LAT_MINE" -t EPSG:6342 --authority EPSG``, it will only looks for transformation available in EPSG

**Comment by dg0yt** [comment]
I would need to tell `--authority EPSG` and similar through the API. The CLI tools were just used for analysis.

In my application, which is still running with PROJ 4.9 on some Linux platforms, it is more complicated, with the outdated `+init=epsg:4326` on the output side, and `+proj=latlong +datum=WGS84 +no_defs` on the input side, at least for "my" GPX code.

For the historical record, PROJ 4.9 gives:
```
$ echo -105.0084468 40.0149205 0 | cs2cs -E +proj=latlong +datum=WGS84 +no_defs +to +init=epsg:6342
-105.0084468 40.0149205 0	499279.14	4429413.28 0.00
```
i.e. the same as the authority-based code path does now. From this POV, the new "ESRI" transformation is the change in behaviour.

**Comment by rouault** [comment]
> I would need to tell `--authority EPSG` and similar through the API

projinfo --authority basically calls the C++ method wrapped by proj_create_operation_factory_context() :
https://proj.org/development/reference/functions.html#_CPPv437proj_create_operation_factory_contextP10PJ_CONTEXTPKc
