### ISSUE TITLE
Outdated docs

### ISSUE THREAD

**Issue by joto** [OSGeo/PROJ#2451]
https://proj.org/development/threads.html says it documents version 7.2.0., but it contains a lot about version 4 and functions like `pj_ctx_alloc()` which seem to be older functions. On the [Quickstart](https://proj.org/development/quickstart.html) the function `proj_context_create()` is mentioned. So there are some discrepancies here.

**Comment by kbevers** [comment]
It is still valid if you are using the `proj_api.h` but an update is definitely needed. Basically just waiting for someone to put in the work. Contributions are welcome!

**Comment by direvus** [comment]
The "Threads" page certainly didn't age well.  It's really describing internal concerns at a point in time, which would have made sense in a wiki or blog post, but not really suitable for long-lived project documentation IMO.

My proposal is to update the Quickstart page to demonstrate how to write thread-safe code (currently the text mentions this, but the code samples don't show it) and just delete the Threads page entirely.  I'll start work on a PR.
