### ISSUE TITLE
How to setup this project and How to start contributing to this project ?

### ISSUE THREAD

**Issue by AdityaTeltia** [OSGeo/PROJ#2475]
Hello everyone !
I am an open source enthusiast , trying to contribute but don't know how to setup the project . I know c++ , anyone who can help me setup the project .
Thank You

**Comment by rouault** [comment]
Hi, such question / introduction isn't very fit for an issue tracker. Maybe try on the mailing list : https://proj.org/community/channels.html

**Comment by AdityaTeltia** [comment]
Ok Thankyou !
