### ISSUE TITLE
Exposing PJD_ERR codes to the public API ?

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#2482]
I'm aware of users who would be interested in having access to PROJ error codes in a more "predictible" / "computer friendly" way than relying of the string returned by proj_errno_string() (one caveat of proj_errno_string() I just discovered is that it uses a static char[] array, and is thus not thread-safe), because currently PJD_ERR_ constants are in proj_internal.h

In particular they would be interested in errors regarding grid handling, such as PJD_ERR_GRID_AREA, and also potentially 2 new error codes:
- PJD_ERR_NODATA_HIT  : when evaluation of a grid at a point is not possible due to nodata value found (currently we don't set a errno for this, and just return HUGE_VAL)
- PJD_ERR_NO_OPERATION : would be emitted by proj_trans() when no coordinate operation is available to transform the given point (currently it returns a arguable EINVAL)

Should we go to exposing in proj.h all the existing error codes, or a minimum subset depending on this immediate needs ? @kbevers opinions ?

**Comment by kbevers** [comment]
There's no doubt we can do error handling much better than now. The only two downsides to exposing the `PJD_ERR_*` constants are

1. Bigger API surface -> less room to play in the future
2. The current error codes and their strings are not very good in my opinion. Some are overly generic, others are way too specific.

But this may be a good time to completely revamp error handling? Something like

- Remove `proj_errno_string()`
- reduce the number of error codes to ~10, expose them in the API
- make a clear distinction between operation initialization errors and single coordinate transformation errors
- move away from generic error messages to actual purpose-build messages localized in the code where an error might happen (print them with a `proj_log_*` function).
- possibly a lot more ...

**Comment by rouault** [comment]
Thanks for your throughts. They make sense and I'll have some (limited) funding to work on that topic

> Remove proj_errno_string()

Rather than pure removal, I'd probably deprecate it in favor of a thread-safe alternative that will take a PROJ_CONTEXT* that can store the error string. It could output a message with the generic error code, and potentially retrieve the last logged error string to concatenate it (I haven't looked at the details if that's possible. Just a thought)

> reduce the number of error codes to ~10, expose them in the API
> make a clear distinction between operation initialization errors and single coordinate transformation errors

My initial proposal (will probably be adjusted during implementation):
```
/** Error codes related to coordinate operation initalization
 * Note: some of them can also be emitted during coordinate transformation,
 * like PROJ_ERR_INVALID_OP_FILE_NOT_FOUND in case the resource loading
 * is differed until it is really needed.
 */
PROJ_ERR_INVALID_OP_WRONG_SYNTAX          = -1000     /* invalid pipeline structure, missing +proj argument, etc */
PROJ_ERR_INVALID_OP_MISSING_ARG           = -1001     /* missing required operation parameter */
PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE     = -1002     /* one of the operation parameter has an illegal value */
PROJ_ERR_INVALID_OP_MUTUALLY_EXCLUSIVE_ARG= -1003     /* mutually exclusive arguments */
PROJ_ERR_INVALID_OP_FILE_NOT_FOUND        = -1004     /* file not found (particular case of PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE) */
PROJ_ERR_INVALID_OP_NETWORK_ERROR         = -1005     /* failure when accessing a network resource during coordinate operation initialization */
PROJ_ERR_INVALID_OP_OTHER                 = -1999     /* other error related to coordinate operation initialization */

/** Error codes related to transformation on a specific coordinate */
PROJ_ERR_COORD_TRANSFM_INVALID_COORD             = -2000     /* for e.g lat > 90deg */
PROJ_ERR_COORD_TRANSFM_OUTSIDE_PROJECTION_DOMAIN = -2001     /* coordinate is outside of the projection domain. e.g approximate mercator with |longitude - lon_0| > 90deg, or iterative convergence method failed */
PROJ_ERR_COORD_TRANSFM_NO_OPERATION              = -2002     /* no operation found, e.g if no match the required accuracy, or if ballpark transformations were asked to not be used and they would be only such candidate */
PROJ_ERR_COORD_TRANSFM_OUTSIDE_GRID              = -2003     /* point to transform falls outside grid or subgrid */
PROJ_ERR_COORD_TRANSFM_GRID_AT_NODATA            = -2004     /* point to transform falls in a grid cell that evaluates to nodata */
PROJ_ERR_COORD_TRANSFM_NETWORK_ERROR             = -2005     /* failure when accessing a network resource during coordiante transformation */
PROJ_ERR_COORD_TRANSFM_OTHER                     = -2999     /* other error related to coordinate transformation */
```

I've chosen new numeric values in case people would use in their own code the old codes (by cheating and looking at proj_internal.h). That way they will never receive an error code that was valid before, which will avoid mis-interpretation and will allow them to more quickly find they have to adapt their code.

A potential mapping of old to new error codes could be
```
#define PJD_ERR_NO_ARGS                  -1     --> PROJ_ERR_INVALID_OP_WRONG_SYNTAX or PROJ_ERR_INVALID_OP_MISSING_ARG (as it was misused)
#define PJD_ERR_NO_OPTION_IN_INIT_FILE   -2     --> PROJ_ERR_INVALID_OP_WRONG_SYNTAX
#define PJD_ERR_NO_COLON_IN_INIT_STRING  -3     --> PROJ_ERR_INVALID_OP_WRONG_SYNTAX
#define PJD_ERR_PROJ_NOT_NAMED           -4     --> PROJ_ERR_INVALID_OP_WRONG_SYNTAX
#define PJD_ERR_UNKNOWN_PROJECTION_ID    -5     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_INVALID_ECCENTRICITY     -6     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_UNKNOWN_UNIT_ID          -7     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_INVALID_BOOLEAN_PARAM    -8     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_UNKNOWN_ELLP_PARAM       -9     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_REV_FLATTENING_IS_ZERO  -10     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_REF_RAD_LARGER_THAN_90  -11     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_ES_LESS_THAN_ZERO       -12     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_MAJOR_AXIS_NOT_GIVEN    -13     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_LAT_OR_LON_EXCEED_LIMIT -14     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_INVALID_X_OR_Y          -15     --> PROJ_ERR_COORD_TRANSFM_INVALID_COORD or PROJ_ERR_COORD_TRANSFM_OUTSIDE_PROJECTION_DOMAIN depending on cases
#define PJD_ERR_WRONG_FORMAT_DMS_VALUE  -16     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_NON_CONV_INV_MERI_DIST  -17     --> PROJ_ERR_COORD_TRANSFM_OUTSIDE_PROJECTION_DOMAIN
#define PJD_ERR_NON_CONV_SINHPSI2TANPHI -18     --> PROJ_ERR_COORD_TRANSFM_OUTSIDE_PROJECTION_DOMAIN
#define PJD_ERR_ACOS_ASIN_ARG_TOO_LARGE -19     --> PROJ_ERR_COORD_TRANSFM_OUTSIDE_PROJECTION_DOMAIN
#define PJD_ERR_TOLERANCE_CONDITION     -20     --> PROJ_ERR_COORD_TRANSFM_OUTSIDE_PROJECTION_DOMAIN
#define PJD_ERR_CONIC_LAT_EQUAL         -21     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_LAT_LARGER_THAN_90      -22     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_LAT1_IS_ZERO            -23     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_LAT_TS_LARGER_THAN_90   -24     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_CONTROL_POINT_NO_DIST   -25     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_NO_ROTATION_PROJ        -26     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_W_OR_M_ZERO_OR_LESS     -27     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_LSAT_NOT_IN_RANGE       -28     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_PATH_NOT_IN_RANGE       -29     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_INVALID_H               -30     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_K_LESS_THAN_ZERO        -31     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_LAT_1_OR_2_ZERO_OR_90   -32     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_LAT_0_OR_ALPHA_EQ_90    -33     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_ELLIPSOID_USE_REQUIRED  -34     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_INVALID_UTM_ZONE        -35     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
/* -36 no longer used */
#define PJD_ERR_FAILED_TO_FIND_PROJ     -37     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE / PROJ_ERR_INVALID_OP_MISSING_ARG
#define PJD_ERR_FAILED_TO_LOAD_GRID     -38     --> PROJ_ERR_INVALID_OP_FILE_NOT_FOUND / PROJ_ERR_COORD_TRANSFM_FILE_NOT_FOUND
#define PJD_ERR_INVALID_M_OR_N          -39     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_N_OUT_OF_RANGE          -40     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_LAT_1_2_UNSPECIFIED     -41     --> PROJ_ERR_INVALID_OP_MISSING_ARG
#define PJD_ERR_ABS_LAT1_EQ_ABS_LAT2    -42     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_LAT_0_HALF_PI_FROM_MEAN -43     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_UNPARSEABLE_CS_DEF      -44     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_GEOCENTRIC              -45     /* no longer used */
#define PJD_ERR_UNKNOWN_PRIME_MERIDIAN  -46     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_AXIS                    -47     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_GRID_AREA               -48     --> PROJ_ERR_COORD_TRANSFM_OUTSIDE_GRID
#define PJD_ERR_INVALID_SWEEP_AXIS      -49     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_MALFORMED_PIPELINE      -50     --> PROJ_ERR_INVALID_OP_WRONG_SYNTAX
#define PJD_ERR_UNIT_FACTOR_LESS_THAN_0 -51     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_INVALID_SCALE           -52     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_NON_CONVERGENT          -53     --> PROJ_ERR_COORD_TRANSFM_OUTSIDE_PROJECTION_DOMAIN
#define PJD_ERR_MISSING_ARGS            -54     --> PROJ_ERR_INVALID_OP_MISSING_ARG
#define PJD_ERR_LAT_0_IS_ZERO           -55     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_ELLIPSOIDAL_UNSUPPORTED -56     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_TOO_MANY_INITS          -57     --> PROJ_ERR_INVALID_OP_WRONG_SYNTAX
#define PJD_ERR_INVALID_ARG             -58     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_INCONSISTENT_UNIT       -59     --> PROJ_ERR_INVALID_OP_ILLEGAL_ARG_VALUE
#define PJD_ERR_MUTUALLY_EXCLUSIVE_ARGS -60     --> PROJ_ERR_INVALID_OP_MUTUALLY_EXCLUSIVE_ARG
#define PJD_ERR_GENERIC_ERROR           -61     --> PROJ_ERR_INVALID_OP_OTHER / PROJ_ERR_COORD_TRANSFM_OTHER
#define PJD_ERR_NETWORK_ERROR           -62     --> PROJ_ERR_INVALID_OP_NETWORK_ERROR / PROJ_ERR_COORD_TRANSFM_NETWORK_ERROR
```

> move away from generic error messages to actual purpose-build messages localized in the code where an error might happen (print them with a proj_log_* function).

Agreed. When doing so, I will probably use the  gettext _("bla") convention (with a dummy definition for the _(x) macro. See https://www.gnu.org/software/gettext/manual/html_node/Mark-Keywords.html) , so that we could possibly use some day gettext to have translatable strings. Real gettext support is not in the scope of my work, but would make it easier.


Another thought I had was regarding the ``proj_trans_array()`` and ``proj_trans_generic()`` method and error handling. I had considered having an extended version where you would have the error code for each point, but that seems a bit overkill. People can just use proj_trans() on each point and test the error code. Given that proj_trans_array / proj_trans_generic just calls proj_trans, there's no real benefit to have an extended array method for now. Could potentially make sense some day if we have more efficient way of transforming coordinates in batch. One thing to do for PROJ 8 though is to make sure that proj_trans_array() / proj_trans_generic() do not stop at the first coordinate transformation failure (proj_trans_array currently stops at the first failure, whereas proj_trans_generic continues), and make sure that the error code they set after transformation is one of the above given values if all failed points fail for that reason or PROJ_ERR_COORD_TRANSFM_OTHER if they fail for different reasons.

**Comment by kbevers** [comment]
> Rather than pure removal, I'd probably deprecate it in favor of a thread-safe alternative that will take a PROJ_CONTEXT* that can store the error string

Yeah, that's a better way to do it. 

> My initial proposal

Looks quite good to me. As you say, it is likely that a more fine-grained set of error codes is needed but it seems like a good start. It's a good idea to distinquish the two error classes into 1nnn and 2nnn but I wonder if we can be a bit more clever with that, so that bit operations can be used to test which type of error it is. Basically checking if a given bit is on or off. Something like:

```
#define PROJ_ERR_INVALID_OP                               64
#define PROJ_ERR_INVALID_OP_WRONG_SYNTAX                  PROJ_ERR_INVALID_OP+1

#define PROJ_ERR_COORD                                    128
#define PROJ_ERR_COORD_TRANSFM_INVALID_COORD              PROJ_ERR_COORD+1


if (err & PROJ_ERR_INVALID_OP) {
    // operation initialization failed for some reason
}

if (err & PROJ_ERR_COORD) {
    // transient error during coordinate transformation
}
```

Better values than 64 and 128 should be used but they should demonstrate the point for now. The bitwise operations could also be replaced by dedicated API functions, bit operator mastery is probably not as strong in the average programmer as it used to be! I don't know how often this would be useful but I think it is a nicer approach than having testing if an error code is in the 1000 or 2000 range and we have a bit more freedom to mix things up if we stick with macros all the way. I rembember seeing a similar approach used somewhere ages ago and figured it might be usefull here. Thoughts?

> Another thought I had was regarding the proj_trans_array() and proj_trans_generic() method and error handling

I think as long as we set the output coordinate to `HUGE_VAL` on all four components when errors occur I think we are good. For the array function we can set the error code to something generic if one or more coordinates fail and let the calling code look into the log to figure out what happened. Which points failed would be obvious from the `HUGE_VAL` coordinates. At the moment I don't think we are properly consistent in the way erroneous coordinates are flagged so that would be another thing to look into.

**Comment by busstoptaktik** [comment]
IMHO, during transformation, the only error type that should be relevant is domain errors, i.e. attempting to use an operation outside of its (geophysically or mathematically) valid area (such as the coverage of a transformation grid, or the set of points not leading to a mathematical singularity). Calling the inverse of a non-invertible operation is also a special case of calling an operation with a vanishing area of definition.

Not being able to access a grid due to lack of connectivity may be a relevant additional case, but essentially it falls back to a domain issue - we do not have the relevant part of the grid, and telling the user why makes a lot of sense.

During instantiation a much larger number of relevant errors are possible (calling for an undefined ellipsoid, a semimajor axis of zero, unknown operations, missing parameters, speeling missteaks, etc.), and we can relevantly help the user by giving a helpful descriptive message. But I think the number of relevant messages during run time i extremely small.

**Comment by rouault** [comment]
> Basically checking if a given bit is on or off.

I've no idea if that would be helpful (I'd suspect more that people would test actual error codes for which they want to react in a special way), but that doesn't hurt to make a provision for such use. Using 1024 and 2048 as bases should give more than enough room for any foreseable future, and avoid any collision with Unix errno numbers
