### ISSUE TITLE
Installed resources for Windows and Linux differs

### ISSUE THREAD

**Issue by danme74** [OSGeo/PROJ#2485]
When building and installing Proj 7.2.0 on Windows and Linux, the following installed resources differs:

`proj.db` _(differs)_
`deformation_model.schema.json` _(missing on Windows)_
`projjson.schema.json` _(missing on Windows)_
`triangulation.schema.json` _(missing on Windows)_

Is this an issue?

The build and installation was not made the same day on Windows and Linux, so if any modification is made to the proj.db before installing it could certainly differ (e.g. update date/time).

In both cases, proj was built as a shared library.

On Windows, cmake was used and the "projsync", "curl" and "testing" features was disabled when building. On Linux, autogen, configure, make was used (built without curl).

**Comment by rouault** [comment]
The missing installed files was an error, now fixed.
Regarding the difference in proj.db, it might come perhaps from different SQLite versions used to generate it, or perhaps different lien endings between Linux and Windows that could affect multi-line content (like CREATE TABLE statements) in the DB. They shouldn't be significant.

**Comment by danme74** [comment]
Thanks!

FYI:
For both linux and windows I used the same sqlite, version 3.31.1 and it was built-in statically.
I got 159 binary differences in between the windows proj.db and the linux proj.db. Both files has the same size.

I looked into the first two, and attached some dumps with context here. Maybe it can give you some more information about the cause?
[proj-db-diff.txt](https://github.com/OSGeo/PROJ/files/5685693/proj-db-diff.txt)

**Comment by rouault** [comment]
> I looked into the first two, and attached some dumps with context here. Maybe it can give you some more information about the cause?

Looks like subtle differences (on the least significant bit) in how the floating point numbers in data/sql/unit.sql end up being encoded in IEEE-754 64bit numbers.
