### ISSUE TITLE
Better examples for the API

### ISSUE THREAD

**Issue by dfileccia** [OSGeo/PROJ#2492]
I have been struggling using the +proj=hgridshift for a while. My transform is accepted and created but it just doesn't seem to work. I am using a similar one for vgridshift that works every time. I cannot find really, any good examples to explain what happens or what the results shoulf be from the transformation as they all seem to be part of a larger transformation. My application needs just the shift values from the hgrid and vgrid.

I am using:
I am testing PROJ 7.2.0

proj string = "+proj=hgridshift +grids=uk_os_OSTN15_NTv2_OSGBtoETRS.tif +multiplier=1 +inv" - Wrong answers and I have no clue what it is really yielding.
proj string = "+proj=vgridshift +grids=uk_os_OSGM15_GB.tif +multiplier=1 +inv" - Yields proper geoid separation and orthometric height

I can get the PJ_GRID_INFO and it all checks out fine.

I know the file takes lat/lon in radians for the transform. I get shift values out (they are added to the src lat/lon). But I know since this is an OSTN02 grid shift file that the output should come out in meters.
It would be nice to have some very simple examples and explanations for users that are not surveyors that need to understand beyond syntax when is happening for the specific examples.

**Comment by kbevers** [comment]
I don't know how to change the docs so you understand them. It's quite clear to me but I also happened to have written most of it...

The general advice for user who are insecure in building their own transformation pipelines is to just let PROJ do the work for them. E.g. by leveraging the EPSG database as in the example below.

```
$ PROJ_LIB=./data src/projinfo -s EPSG:4277 -t EPSG:4258 -o PROJ
Candidate operations found: 2
-------------------------------------
Operation No. 1:

DERIVED_FROM(EPSG):7709, OSGB 1936 to ETRS89 (2), 0.03 m, United Kingdom (UK) - offshore to boundary of UKCS within 49°45'N to 61°N and 9°W to 2°E; onshore Great Britain (England, Wales and Scotland). Isle of Man onshore.

PROJ string:
+proj=pipeline
  +step +proj=axisswap +order=2,1
  +step +proj=unitconvert +xy_in=deg +xy_out=rad
  +step +proj=hgridshift +grids=uk_os_OSTN15_NTv2_OSGBtoETRS.tif
  +step +proj=unitconvert +xy_in=rad +xy_out=deg
  +step +proj=axisswap +order=2,1
```

If that's not useful for what you are trying to do I reckon you can get a bit of inspiration for how to use `hgridshift` in combination with the grid you are looking at.

**Comment by dfileccia** [comment]
I will try this but I do not think it will prevail! I have tried that too.

David Fileccia

I have been all things unholy. If God can work through

me, he can work through anyone. -- Francis of Assisi

________________________________

**Comment by dfileccia** [comment]
Hi Kristian,

Here is what I changed my PROJ string to:
const QString p = "+proj=pipeline "

        "+step +proj=axisswap +order=2,1 "

        "+step +proj=unitconvert +xy_in=deg +xy_out=rad "

        "+step +proj=hgridshift +grids=%1 "

        "+step +proj=unitconvert +xy_in=rad +xy_out=deg "

        "+step +proj=axisswap +order=2,1";

Input to proj_trans (in degrees):
   PJ_COORD src;


   src.lp.phi = lat;

   src.lp.lam = lon;

proj_create is happy with this.
proj_trans responds: "point not within available datum shift grids"

If I remove the "+proj=axisswap" lines, proj_trans is happy and returns the same result as I was getting before!

As I said, I need to get the shift values. The file is boundaries are in lat/lon according to the proj_grid_info function. I assume that means I give it latitude and longitude for input.

Again, I cannot figure why and setting debug level doesn't help either with this.

David Fileccia

I have been all things unholy. If God can work through

me, he can work through anyone. -- Francis of Assisi

________________________________

**Comment by busstoptaktik** [comment]
David,

Could you provide the exact string you pass to proj_create()? You have
placeholder "%1" in the string you show. Is that passed literally?

Den ons. 16. dec. 2020 kl. 21.10 skrev David FIleccia <
notifications@github.com>:

**Comment by dfileccia** [comment]
Here is the exact string that is passed into proj_create. The %1 is the QString 'arg' placeholder for the file path.

DGF: PROJ str= "+proj=pipeline +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=hgridshift +grids=D:/MSys64/home/DFileccia/Workspace/Geoids/proj/uk_os_OSTN15_NTv2_OSGBtoETRS.tif +inv +step +proj=unitconvert +xy_in=rad +xy_out=deg "

This is the latitude and longitude I have been testing (decimal degrees).

hs.query (57.15709900, -2.11771100, xs, ys);


Code used to create the transform:


   m_C = proj_context_create ();



   if (proj_context_errno (m_C) == 0) {

      const QString p = "+proj=pipeline "

            "+step +proj=unitconvert +xy_in=deg +xy_out=rad "

            "+step +proj=hgridshift +grids=%1 +inv "

            "+step +proj=unitconvert +xy_in=rad +xy_out=deg ";


      m_P = proj_create (m_C, p.arg (filepath).toUtf8 ().constData ());


      if (proj_errno (m_P) != 0) {

         proj_context_destroy (m_C);

         m_C = nullptr;

      }
   }




Using the above transform, I pass in latitude and longitude and pack into a PJ_COORD as follows:


   PJ_COORD src;
   src.lp.phi = lat;

   src.lp.lam = lon;


   PJ_COORD dst = proj_trans (m_P, PJ_FWD, src);

   if (proj_errno (m_P) == 0) {
-- This doesn't seem to yield shifts but a L/L pair that has been shifted.

   }

   else {

      proj_errno_reset (m_P);

      xs = 999;

      ys = 999;

   }


This is much appreciated to help me understand what is going on.


David Fileccia

I have been all things unholy. If God can work through

me, he can work through anyone. -- Francis of Assisi

________________________________

**Comment by rouault** [comment]
> This doesn't seem to yield shifts but a L/L pair that has been shifted.

yes, the output of hgridshift is shifted coordinates, not the shift value. You can obviously compute it easily from the output and the input

**Comment by dfileccia** [comment]
I didn't put in what I currently do because I was more concerned about your opinions. What I currently do is...

xs = dst.lp.lam - src.lp.lam;
ys = dst.lp.phi - src.lp.phi;

This gives me residual values for sure but I am not sure what the units are. Looks like probably degrees since that is what the transform returns. Now, how to get that to meters... IDK.

David Fileccia

I have been all things unholy. If God can work through

me, he can work through anyone. -- Francis of Assisi

________________________________

**Comment by rouault** [comment]
> Now, how to get that to meters

Use https://github.com/OSGeo/PROJ/blob/2414eb2bb655588b4b7e9fe86bba70592bd7f911/src/geodesic.h#L367

**Comment by dfileccia** [comment]
Thanks. I was unsure if the value from the file was added to the source lat/long or not. If the geoid_* functions are not exported, I can just use geographiclib.

David Fileccia

I have been all things unholy. If God can work through

me, he can work through anyone. -- Francis of Assisi

________________________________
