### ISSUE TITLE
EPSG:4326 to EPSG:32749

### ISSUE THREAD

**Issue by snowman2** [OSGeo/PROJ#2497]
From: https://github.com/geopandas/geopandas/issues/1761

#### Example of problem
```
echo -6.155403427850139 106.48395538330078 | ./cs2cs epsg:4326 epsg:32749
-154.37	9317499.91 0.00
```
#### Expected Output

The x coordinate should be closer to `46618`

#### Environment Information
 - PROJ version: 6.1.1, 7,0.1 and 8.0.0
 - Operation System Information: Ubuntu 20 

#### Installation method
 - pyproj wheel, from source

**Comment by rouault** [comment]
Precision of input coordinates is crucial :-) If you try "https://epsg.io/transform#s_srs=4326&t_srs=32749&x=106.4839553&y=-6.1554033" you get a consistent result with PROJ

**Comment by snowman2** [comment]
Thanks 👍
