### ISSUE TITLE
certificate just expired on cdn.proj.org

### ISSUE THREAD

**Issue by michaelkirk** [OSGeo/PROJ#2504]
Please let me know if this isn't the proper place to report this.

#### Example of problem

When using the network grid, my client started failing. This may be because the cdn.proj.org cert just expired, since, my understanding is that's proj's download source.

<img width="458" alt="Screen Shot 2021-01-16 at 10 01 54 PM" src="https://user-images.githubusercontent.com/217057/104830732-18fba780-5847-11eb-920e-22d2db6ed225.png">

```
$ openssl s_client -servername cdn.proj.org -connect "cdn.proj.org:443" |  openssl x509 -noout -dates
depth=4 C = US, O = "Starfield Technologies, Inc.", OU = Starfield Class 2 Certification Authority
verify return:1
depth=3 C = US, ST = Arizona, L = Scottsdale, O = "Starfield Technologies, Inc.", CN = Starfield Services Root Certificate Authority - G2
verify return:1
depth=2 C = US, O = Amazon, CN = Amazon Root CA 1
verify return:1
depth=1 C = US, O = Amazon, OU = Server CA 1B, CN = Amazon
verify return:1
depth=0 CN = cdn.proj.org
verify error:num=10:certificate has expired
notAfter=Jan 16 12:00:00 2021 GMT
verify return:1
depth=0 CN = cdn.proj.org
notAfter=Jan 16 12:00:00 2021 GMT
verify return:1
notBefore=Dec 16 00:00:00 2019 GMT
notAfter=Jan 16 12:00:00 2021 GMT
```

#### Expected Output

Expected the network enabled projection to complete.

#### Environment Information
 - PROJ version (`proj`): 1.7.1
 - Operation System Information: macos

#### Installation method
 - from source, via the [rust proj wrapper crate](http://github.com/georust/proj).

**Comment by hobu** [comment]
Yes, this is the right spot to make this ticket. 

Working a renewal now.

**Comment by hobu** [comment]
New cert should be propagating through CDN now.

```
openssl s_client -servername cdn.proj.org -connect "cdn.proj.org:443" |  openssl x509 -noout -dates
depth=2 C = US, O = Amazon, CN = Amazon Root CA 1
verify return:1
depth=1 C = US, O = Amazon, OU = Server CA 1B, CN = Amazon
verify return:1
depth=0 CN = cdn.proj.org
verify return:1
notBefore=Jan 17 00:00:00 2021 GMT
notAfter=Feb 15 23:59:59 2022 GMT
```

**Comment by michaelkirk** [comment]
Looks good - and my clients working now. Thank you!
