### ISSUE TITLE
Using +over with EPSG codes and WKT CRS Input/Output?

### ISSUE THREAD

**Issue by mlptownsend** [OSGeo/PROJ#2512]
Is it possible to provide the +over flag when using an EPSG code or a WKT string as the CRS input when calling the utility methods like cs2cs? It doesn't seem like it's able to recognize it as-is. I've tried various combinations of attaching the +over to no avail.

I can kind of hack around it by customizing the library, but it would be nice to be able to have this out of the box. Or, if it's actually possible...?

**Comment by mlptownsend** [comment]
So here's what I did to pull it off in my customized version. If you're interested I might be able to submit a PR (I'll have to run it by the proper channels locally first o'course). Also would like to know if it was ultimately a good idea too.

1. Add a new flag on the PJ_CONTEXT called forceOver, default value 0.
2. New api method 'void PROJ_DLL proj_context_set_force_over(PJ_CONTEXT* ctx, int enable);' Its sole purpose is to set said flag on the provided context object (or on the default if nullptr provided, just like how proj_context_use_proj4_init_rules works).
3. Inside of pj_init_ctx_with_allow_init_epsg, right after the 'PIN->over = pj_param(ctx, start, "bover").i' line, check the context for the forceOver flag. If non-zero, turn on PIN->over.

With this, it's just a matter of adding a new command line switch to the utilities that calls proj_context_set_force_over. Not a whole lot of code change ultimately.

**Comment by rouault** [comment]
> If you're interested I might be able to submit a PR

I can't really think of a better way. The +over concept is really super specific and doesn't fit nicely into ISO 19111 concepts. So your PR is welcome

**Comment by mlptownsend** [comment]
Yeah, my problem is really super specific with the dateline/antimeridian. It may take me a little while to circle back around to this, but I'll see what I can do. Thanks!

**Comment by kbevers** [comment]
@mlptownsend Not to put pressure on you, but in case it's valuable to you to have this in the main distribution. There's about 10 days until the next release (8.0.0) will be prepared. After that it will be 4 or 5 months before the next release where this can be added.
