### ISSUE TITLE
Prefer keyword signature of CMake command target_link_libraries

### ISSUE THREAD

**Issue by mloskot** [OSGeo/PROJ#2515]
This task is about a slight modernisation of the CMake configuration to use the keyword-based signatures.
The keyword signatures also make it explicit if a dependency is a [build requirement and/or usage requirement](https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html).

The plain and keyword calls to `target_link_libraries` (and possibly other `target_*` commands) can not be mixed as per https://cmake.org/cmake/help/latest/policy/CMP0023.html
Otherwise, CMake issues errors

```
The plain signature for `target_link_libraries` has already been used with the target "xxx". 
All uses of `target_link_libraries with` a target must be either all-keyword or all-plain.
```

### References

- Blocking #2514

**Comment by kbevers** [comment]
@mloskot Is this something you want to take a stab at? If so, it would be good get that done in time for 8.0.0RC1 which will be prepared around February 20th.

**Comment by mloskot** [comment]
@kbevers Yes, I'm going to work on it this week

**Comment by kbevers** [comment]
Awesome!

**Comment by mloskot** [comment]
@kbevers I covered this in PR #2533
