### ISSUE TITLE
Improved error when proj_create doesn't recognize definition

### ISSUE THREAD

**Issue by frewsxcv** [OSGeo/PROJ#2529]
```c
#include <proj.h>
#include <stdio.h>

int main() {
    PJ* pj_point = proj_create(0, "a b c d e f g h i j");
    if (pj_point) {
        printf("proj_create succeeded\n");
    } else {
        int errno = proj_context_errno(0);
        const char* error_string = proj_errno_string(errno);
        printf("%s\n", error_string);
    }
    return 0;
}
```

If PROJ doesn't recognize the definition provided to `proj_create`, the error that gets returned is `generic error of unknown origin` which makes it hard for users finding out what went wrong

**Comment by frewsxcv** [comment]
One other thing to add is [the `proj_create` documentation](https://proj.org/development/reference/functions.html#c.proj_create) recommends retrieving the errno if the call fails:

> If creation of the transformation object fails, the function returns 0 and the PROJ error number is updated. The error number can be read with `proj_errno()` or `proj_context_errno()`.

**Comment by frewsxcv** [comment]
Does anyone know where the relevant code is? I might have capacity to make this change

**Comment by direvus** [comment]
Hi @frewsxcv, running your sample code I get:

```
proj_create: unrecognized format / unknown name
Unknown error (code 4096)
```

Maybe this has been improved since you raised the issue?

I think "proj_create: unrecognized format" is clear enough to point users in the right direction.  Is there anything about it you'd want to change?

**Comment by frewsxcv** [comment]
Thanks for the update!

**Comment by frewsxcv** [comment]
> Hi @frewsxcv, running your sample code I get:
> 
> ```
> proj_create: unrecognized format / unknown name
> Unknown error (code 4096)
> ```
> 
> Maybe this has been improved since you raised the issue?
> 
> I think "proj_create: unrecognized format" is clear enough to point users in the right direction. Is there anything about it you'd want to change?

The `proj_create: unrecognized format` is getting logged by the logger, from what I understand. `Unknown error (code 4096)` is the actual string that gets returned, which is what would get displayed to the user, which isn't so helpful.

**Comment by direvus** [comment]
OK @frewsxcv, thanks, I think I understand the problem better now.

I think this works better if we have proj_create set the error code to INVALID_OP_WRONG_SYNTAX ("Invalid PROJ string syntax") when the underlying function throws a ParsingException.  Does that work for you?

With this change, running your test program outputs as follows:

```
proj_create: unrecognized format / unknown name
Invalid PROJ string syntax
```

**Comment by frewsxcv** [comment]
@direvus Yep, that's perfect. Thanks!
