### ISSUE TITLE
Proj-7.2.1 build fails on debian platforms 

### ISSUE THREAD

**Issue by pullag** [OSGeo/PROJ#2530]
.....
.......
Make proj.db
rm -f proj.db
free(): invalid pointer
/bin/bash: line 30:   377 Done                    cat ${SQL_EXPANDED_LIST}
       378 Aborted                 | sqlite3 proj.db
Build of proj.db failed
make[1]: *** [Makefile:666: proj.db] Error 1

I'm using this steps
./configure --prefix=/usr/local SQLITE3_CFLAGS='-I$/usr/local/sqlite-3/include' SQLITE3_LIBS='-L/usr/local/sqlite-3/lib -lsqlite3' --enable-lto --disable-tiff
make 
make install

**Comment by rouault** [comment]
Looks quite similar to https://github.com/OSGeo/PROJ/issues/1536 . Might be an issue on how you've built sqlite3 or a mismatch of sqlite3 library/binary

**Comment by pullag** [comment]
Thanks for your reply, 
I took a prestine ubuntu20.04 and installed system sqlite3(headers, libs, exec)
and the default version is sqlite-3.31.1. and the proj-7.2.1 build went fine.

So compiled the sqlite-3.31.1 again on my platform and ran the proj-7.2.1 build with the same options mentioned above.
The build got passed.
So, I suspect some issue with sqlite-3.32.3
