### ISSUE TITLE
proj -le still enlists 'International 1909 (Hayford)' instead of 'International 1924'

### ISSUE THREAD

**Issue by florisvdh** [OSGeo/PROJ#2534]
#### Example of problem

```bash
$ dpkg -l | grep libproj
ii  libproj-dev:amd64                             7.2.1-1~focal0                          amd64        Cartographic projection library (development files)
ii  libproj19:amd64                               7.2.1-1~focal0                          amd64        Cartographic projection library

$ proj -le | grep -E '\sintl'
     intl a=6378388.0      rf=297.          International 1909 (Hayford)

$ projinfo -k ellipsoid -o proj,wkt_all EPSG:7022
PROJ string:
+ellps=intl

WKT2:2015 string:
ELLIPSOID["International 1924",6378388,297,
    LENGTHUNIT["metre",1],
    ID["EPSG",7022]]

WKT2:2019 string:
ELLIPSOID["International 1924",6378388,297,
    LENGTHUNIT["metre",1],
    ID["EPSG",7022]]

WKT1:GDAL string:
SPHEROID["International 1924",6378388,297,
    AUTHORITY["EPSG","7022"]]
```
#### Problem description

In the list of ellipsoids of `proj -le`, an older name is still used for the international ellipsoid. I'd expect it should be changed to 'International 1924' (EPSG:7022), cf. the output of `projinfo`. In both cases, reference is made to the PROJ name `intl`.

Maybe there are other such non-conforming cases in the output of `proj -le`, I think this should be checked.

#### Expected Output

```bash
$ proj -le | grep -E '\sintl'
     intl a=6378388.0      rf=297.          International 1924
```

#### Environment Information
 - PROJ 7.2.1
 - Linux Mint 20

#### Installation method
apt-get, with ubuntugis-unstable PPA 

```
$ apt policy libproj19
libproj19:
  Installed: 7.2.1-1~focal0
  Candidate: 7.2.1-1~focal0
  Version table:
 *** 7.2.1-1~focal0 500
        500 http://ppa.launchpad.net/ubuntugis/ubuntugis-unstable/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by busstoptaktik** [comment]
@florisvdh yes - it would indeed make sense to change the `proj -le` designation:

The Hayford ellipsoid was based on investigations in 1909, published in 1910 as J.F. Hayford: *Supplementary Investigation in 1909 of the Figure of the Earth and Isostasy*, Coast and Geodetic Survey, 80pp. (freely accessible through Google Books).

In 1924 Hayford's ellipsoid was adopted by the IUGG as "the International Ellipsoid".

Hence either of 

- Hayford, 1909 (for the year the work was done),
- Hayford, 1910 (for the year of publication), or
- International, 1924

would be reasonable names, but the "International, 1909" really is a peculiar mix of concepts.

**Comment by florisvdh** [comment]
Thank you for providing this interesting background @busstoptaktik! I understand the alternatives you enlist would all be equivalent. I think the advantage of changing to 'International 1924' would be syntactical consistency with EPSG:7022 and the WKT strings in which it is used, in order to avoid confusion.

**Comment by kbevers** [comment]
Ellipsoid names are defined here: https://github.com/OSGeo/PROJ/blob/master/src/ellps.cpp Feel free to open a pull request that fixes this.

**Comment by florisvdh** [comment]
The `ellipsoid` table in `proj.db` has:

|auth_name |code |name               |description |
|:---------|:----|:------------------|:-----------|
|EPSG      |7022 |International 1924 |NA          |

(`NA` meaning missing value; have generated this in R)

Not clear to me is if it is a goal to keep both data sources connected: `ellps.cpp` on the one hand and the 'PROJ' records of `ellipsoid` inside `proj.db` on the other hand. I think that further consistency would provide most clarity.

Here maybe the broader description `International 1924 (Hayford 1909, 1910)` could be added to the description field of `ellipsoid` (above). On the other hand, if name matching is desired, then perhaps one or the other should change names.

See #2537 for general issue on this.

**Comment by kbevers** [comment]
> Not clear to me is if it is a goal to keep both data sources connected

@florisvdh ideally all ellipsoid information is read from the database, similar to `proj_get_units_from_database()` but at the moment we haven't got such a function. Someone just needs to step up and do it.
