### ISSUE TITLE
Relationship between ellipsoid table in proj.db and the ellipsoids enlisted in ellps.cpp

### ISSUE THREAD

**Issue by florisvdh** [OSGeo/PROJ#2537]
As I understand, `ellps.cpp` is used in `proj -le` while `proj.db` is used by `projinfo`. Their outputs (ellipsoid names and such) show different strings, cf. the 'International 1924' discussed in #2534.

Not clear to me is if it is a goal to keep both data sources connected: `ellps.cpp` on the one hand and the 'PROJ' records of `ellipsoid` inside `proj.db` on the other hand. I think that further consistency would provide most clarity.

Should names and descriptions match? And ellipsoids from one table be present in the other? Some exploration:
 - in `ellipsoid` actually only 10 records are present where `auth_name` equals `PROJ` - with `code` set as uppercase form of `name` in `ellps.cpp`, so not all 46 from `ellps.cpp` are present.
- from the 10 PROJ ellipsoids in `ellipsoid`, 2 do not occur in `ellps.cpp`:
    
    |auth_name |code      |name                                           |description |
    |:---------|:---------|:----------------------------------------------|:-----------|
    |PROJ      |CPM       |Comité international des poids et mesures 1799 |NA          |
    |PROJ      |EARTH2000 |Earth2000                                      |NA          |

- identical strings between `name` in `ellipsoid` and `description` in `ellps.cpp` occur in 17 cases (8 EPSG, 1 ESRI, 8 PROJ)
- identical strings between `description` in `ellipsoid` and `description` in `ellps.cpp` occur in 2 cases (2 times ESRI)

**Comment by kbevers** [comment]
Ideally the ellipsoid data shown with `proj -le` should be retrieved from `proj.db`. We do this for the units. Any ellipsoids missing in `proj.db` should be added.

**Comment by busstoptaktik** [comment]
> Any ellipsoids missing in `proj.db` should be added.

So for clarity we should perhaps expand the "International 1924 (Hayford 1909/1910)" aliases into separate entries for each alternative name?

If I interpret [the `proj.db` setup](https://github.com/OSGeo/PROJ/blob/e8a535ee02e7170bf9f16ff0570c07ee0a3b7ec0/scripts/build_db.py#L88-L91) correctly, `proj.db` supports ellipsoids defined as either the combination of  `(a, b)` or of `(a, 1/f)` only. PROJ, on the other hand, attempts to allow using whichever parameter set was used in the original publication (with `GRS80` as a notable exception: The *dynamic form factor* `J2` is not supported, so we use a derived value for `1/f`).

Fortunately, in the list of built in ellipsoids, only the two combinations allowed in `proj.db` are used, so this is unlikely to cause any kind of trouble (although one may still define *ad hoc* ellipsoids using `f`, `rf`, `e`, `es`, `ep`, or `eps` as shape parameter using `PROJ` command line syntax).

I believe it would be academically controversial, and geodetically confusing, to entirely remove John Fillmore Hayford's name from the ellipsoid he derived. But I could, as a stop-gap, amend #2536, introducing separate (but numerically identical) entries for

- `intl` International 1924
- `hayf09` Hayford 1909
- `hayf10` Hayford 1910

to ensure we actually have a baseline for what should be considered "missing in `proj.db`" as per @kbevers' comment.

**Comment by florisvdh** [comment]
@busstoptaktik  `proj.db` seems to document synonymy in the `alias_name` table, so IMHO your suggestion of splitting could be supported there. Ellipsoid aliases visualized in R:

``` r
suppressPackageStartupMessages(library(dplyr))
proj <- DBI::dbConnect(RSQLite::SQLite(), dbname = "/usr/share/proj/proj.db")
tbl(proj, "alias_name") %>%
    filter(table_name == "ellipsoid") %>%
    collect
#> # A tibble: 50 x 5
#>    table_name auth_name code  alt_name             source
#>    <chr>      <chr>     <chr> <chr>                <chr> 
#>  1 ellipsoid  EPSG      1026  Zach_1812            ESRI  
#>  2 ellipsoid  EPSG      7001  Airy_1830            ESRI  
#>  3 ellipsoid  EPSG      7002  Airy_Modified        ESRI  
#>  4 ellipsoid  EPSG      7003  Australian           ESRI  
#>  5 ellipsoid  EPSG      7004  Bessel_1841          ESRI  
#>  6 ellipsoid  EPSG      7005  Bessel_Modified      ESRI  
#>  7 ellipsoid  EPSG      7006  Bessel_Namibia       ESRI  
#>  8 ellipsoid  EPSG      7007  Clarke_1858          ESRI  
#>  9 ellipsoid  EPSG      7008  Clarke_1866          ESRI  
#> 10 ellipsoid  EPSG      7009  Clarke_1866_Michigan ESRI  
#> # … with 40 more rows
```

<sup>Created on 2021-02-16 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>


Upon inspecting, currently all the ellipsoid aliases are between EPSG and ESRI codes. In this case, it would be between PROJ code `intl` and PROJ code `hayf09` etc.

I don't know how this table is actually used by the `projinfo` application (and others), though. E.g. in printing a CRS as WKT it seems sensible that it would then always translate to one favoured synonym, again to avoid confusion and unnecessary differences between WKT strings.

**Comment by florisvdh** [comment]
> In this case, it would be between PROJ code `intl` and PROJ code `hayf09` etc.

After looking better (apologies) it seems that `alias_name` actually does not show two codes, but just one. So remains unclear to me how synonymy would be / is handled.

**Comment by busstoptaktik** [comment]
> So remains unclear to me how synonymy would be / is handled

Probably by not requiring the `(auth_name, code)` pair to be unique?
