### ISSUE TITLE
CMake files not installed when autotools is used. pkg-config file not installed when using CMake

### ISSUE THREAD

**Issue by sebastic** [OSGeo/PROJ#2546]
#### Example of problem
When using autotools to build PROJ like the Debian package does the `.cmake` files are not installed as they are when using CMake like the Fedora package does.

Likewise the pkg-config file is not installed when using CMake, the Fedora package had to [patch](https://src.fedoraproject.org/rpms/proj/blob/rawhide/f/proj_pkgconfig.patch) PROJ to install it.

#### Problem description

The developers of QMapShack [[1](https://sourceforge.net/p/qlandkartegt/mailman/message/36634734/)] and OpenOrienteering Mapper [[2](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=983254#34)] have complained that the Debian package does not install the CMake files forcing them to maintain a `FindProj.cmake` in their source tree.

#### Expected Output

Ideally the CMake files are installed as part of the Autotools build, and the pkg-config bits as part of the CMake build.

The result of either build should be nearly identical. And have both the pkg-config and CMake bits installed for the benefit of downstream projects.

#### Environment Information
 - Rel. 7.2.1, January 1st, 2021
 - Debian GNU/Linux unstable (amd64)

#### Installation method
 - Debian package (`libproj-dev`)

**Comment by dg0yt** [comment]
For more context, as the developer of OpenOrienteering Mapper:

Debian claims that our software fails to build from source with PROJ 8.0.0, due to usage of `proj_api.h`. Now we are using CMake, and we have been adopting modern PROJ and CMake early. With the Debian PROJ package being build with autotools, it doesn't provide the CMake config files. This makes our package fall back to a legacy `FindPROJ4.cmake` which looks for `proj_api.h`. This header file was removed in PROJ 8.0.0, uncovering the unbalanced feature set of the PROJ build systems. 

> The developers of QMapShack [1] and OpenOrienteering Mapper [2] have complained that the Debian package does not install the CMake files forcing them to maintain a FindProj.cmake in their source tree.

The CMake find module is not "maintained" for Debian testing / PROJ 8.0. It is kept for Debian stable, Ubuntu 18.04 and alikes, with PROJ version down to 4.9 where there are no CMake options. For this purpose, it works as intended.

My point of view is that:
- the CMake build needs to create the missing pkgconfig files
- the CMake build shall be adjusted to support Debian's multiarch builds of PROJ
- autotools should eventually be dropped.

I don't dispute that autotools works great for Debian packaging. But I think that
- the CMake build can work equally well,
- reimplementing CMake config file generation in autotools is going to be a fruitless, volatile maintenance burden. (Maybe less in the PROJ case, but definitely in the general case.)

**Comment by kbevers** [comment]
I am not the best to deal with this issue so I'm hoping to get input from @mwtoews, @hobu, @cffk and @mloskot as well. So for now just a few comments and clarifying questions from me.

> forcing them to maintain a FindProj.cmake in their source tree.

This is annoying, for sure, but it seem to me that it is a common issue. We keep a `FindSqlite3.cmake` file around for the same reason.

I generally agree with @dg0yt's points, especially the point about dropping autotools but that is my personal opinion and a change like that needs a well thought out strategi and PSC approval. Maybe now is the time to start thinking about that.

> reimplementing CMake config file generation in autotools is going to be a fruitless, volatile maintenance burden. (Maybe less in the PROJ case, but definitely in the general case.)

Also resonates with me. The burden of maintaining to build systems is already too much in my opinion so I would rather not complicate things more than necessary.


What is the absolute minimum we can do to get around this problem? My goal here is to find an immediate fix we can put into 8.0.0RC2 and hopefully smooth the transition to a `proj_api.h`-less PROJ.

**Comment by sebastic** [comment]
> What is the absolute minimum we can do to get around this problem? My goal here is to find an immediate fix we can put into 8.0.0RC2 and hopefully smooth the transition to a proj_api.h-less PROJ.

I don't think there is a quick fix that can be included in 8.0.0RC2.

I have already provided patches for QGIS en OpenOrienteering Mapper adding support for PROJ 8 to their cmake modules. Such fixes are the way to go for PROJ 8 support in downstream projects for the time being in my opinion.

If Autotools is removed in PROJ 9, then we'll switch the Debian package to use cmake when autotools is no longer available.

I'd rather not see that happen, as autotools is a better build system from a packaging POV, but I also agree that maintaining multiple buildsystems is problematic.

MapServer switched to cmake some time ago ([MS RFC 92](https://mapserver.org/development/rfc/ms-rfc-92.html)), and GEOS did that recently ([RFC7](https://trac.osgeo.org/geos/wiki/RFC7)) although they haven't removed the autotools bits in 3.9.x (yet).

**Comment by kbevers** [comment]
> I don't think there is a quick fix that can be included in 8.0.0RC2.

Alright, good to know. 

> I have already provided patches for QGIS en OpenOrienteering Mapper adding support for PROJ 8 to their cmake modules. Such fixes are the way to go for PROJ 8 support in downstream projects for the time being in my opinion.

Thanks.

> If Autotools is removed in PROJ 9, then we'll switch the Debian package to use cmake when autotools is no longer available.
>
> I'd rather not see that happen, as autotools is a better build system from a packaging POV, but I also agree that maintaining multiple buildsystems is problematic.

There's not really a perfect solution, I agree. If autotools was a reliable option on Windows I would be happy to keep that around as the only build tool for PROJ.

**Comment by cffk** [comment]
I don't see any good solution here as long as autotools is being used.
I believe that the continued use of autotools by Debian is mostly a
result of inertia.  Perhaps the maintainer of PROJ on the Debian side
can be presuaded to switch to cmake?

**Comment by mwtoews** [comment]
The pkg-config issue should be simple, see #2547 for a candidate.

Getting autotools to generate CMake files sounds like a mess. I would rather support dropping autotools, similar to GEOS (see [RFC7](https://trac.osgeo.org/geos/wiki/RFC7)) and libspatialindex.

**Comment by kbevers** [comment]
> Perhaps the maintainer of PROJ on the Debian side can be presuaded to switch to cmake?

@cffk we already have confirmation from @sebastic above that he will do that if we drop autotools. 

> The pkg-config issue should be simple, see #2547 for a candidate.

Great!

**Comment by sebastic** [comment]
> I believe that the continued use of autotools by Debian is mostly a
result of inertia. Perhaps the maintainer of PROJ on the Debian side
can be presuaded to switch to cmake?

It's not inertia, it's a conscious decision. Autotools is the best choice for the proj Debian package because it supports things like multiarch and reproducible builds better than CMake. See some of the issues related to GEOS: 

 https://lists.osgeo.org/pipermail/geos-devel/2021-January/010078.html

As long as Autotools is available for PROJ, it's the best choice from a packaging POV. Switching to CMake is a regression which I can't justify just to make life easier for some CMake based downstream projects. Every time a package was switched to CMake it introduced issues that were not present with the prior Autotools build. Only when CMake is the only build system will we accept those.

**Comment by kbevers** [comment]
> Every time a package was switched to CMake it introduced issues that were not present with the prior Autotools build.

Are those issues possible to resolve by configuring CMake in a certain way? Multiarch has been mentioned a few times and that seems to be possible to handle but maybe there are other things we should be aware of?

**Comment by sebastic** [comment]
Multiarch is already supported in PROJ because it uses `CMAKE_INSTALL_LIB`.

Reproducible builds are more difficult because of the absolute path issue. Switching to cmake will result in file-references-package-build-path issues.

Autotools generates gcc commands like:
```
gcc -c foo.c -o foo.o
```
Whereas CMake generates commands like:
```
gcc -o CMakeFiles/foo.dir/foo.c.o -c /build/foo-0.1/src/foo.c
```

This causes the absolute path to be embedded in the binaries via `__FILE__` in `assert()`.

I'm not aware of a fix other than using `-DNDEBUG` to strip out `assert()`.

**Comment by mloskot** [comment]
Generally, every project that aims to be built and consumed with CMake should provide the Config-file, and not the Find-module guesser. Maintenance of the legacy guessers is cumbersome indeed.

@sebastic 
> CMake files not installed when autotools is used.

Looks like the PROJ autotools configuration needs a fix.

@mwtoews 
>  I would rather support dropping autotools

Generally, I'd do it too.
Specifically, it should be call of @kbevers as the active maintainer should pick what works best for him.

**Comment by mloskot** [comment]
@sebastic 
> I'm not aware of a fix other than using -DNDEBUG to strip out assert().

```
cmake -S <path-to-source> -B <path-to-build> -DCMAKE_BUILD_TYPE=Release
cmake --build <path-to-build> --config Release
```

**Comment by sebastic** [comment]
`CMAKE_BUILD_TYPE=Release` is not appropriate for Debian package because there will be no debug symbols then.

The Debian package build for CMake uses `CMAKE_BUILD_TYPE=None` by default for this reason. `RelWithDeInfo` is also common when packages diverge from the default.

**Comment by dg0yt** [comment]
`RelWithDebInfo` is standard. `None` is not (or no more). However, the value can be empty.

**Comment by mloskot** [comment]
@sebastic None is wrong. See @dg0yt suggestion.

**Comment by sebastic** [comment]
Not according to the discussion linked from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=701233

**Comment by dg0yt** [comment]
> Not according to the discussion linked from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=701233

This is from 2013. This is far from the "Modern CMake" we talk about, and explains why the benefits of config files are not understood.

**Comment by mloskot** [comment]
@sebastic From that discussion
> we should be promoting the use of -DCMAKE_BUILD_TYPE=RelWithDebInfo (-g -O2), and here's a patch that does that.

Yes, indeed.
Then, counter-suggestion says

> It is required by policy that CFLAGS and CXXFLAGS (solely) are used when building.

Which simply stands against CMake recommendation of "Do not fiddle with flags, unless you really have to"

Then, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=711515#10 says

> Previously, it was inconsistent in that some platforms/compilers had this flag for the RelWithDebInfo configuration and some didn't.

There is a history of inconsistent behaviours and it *used to* be necessary to handle that, but I doubt that still is the case (as @dg0yt  suggested in https://github.com/OSGeo/PROJ/issues/2546#issuecomment-785135001). I assume nobody reviewed that.

Finally, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=701233#27 says

> Strictly speaking build system (eg. cmake) should not try to set any compilation flags themselves. 

Well, as Debian does not trust any build system, then there is nothing to discuss really.
Certainly, Debian is free to do its _own_ things its own way.

**Comment by dg0yt** [comment]
For the record, unlike the documentation of `CMAKE_BUILD_TYPE`, CMake's `Modules/CMakeInitializeConfigs.cmake` lists `None` in the doc string of `CMAKE_BUILD_TYPE`. It is treated different from an empty string. (You might provide evil `CMAKE_C_FLAGS_NONE_INIT`...)

Debian's cmake package has a `debtoolchainfilegen` script "to generate toolchain files based on Ubuntu/Debian's Multi-Arch". Perhaps this helps to reduce pain with handling multi-arch.

**Comment by mloskot** [comment]
@dg0yt Yes, good point. The CMake toolchain file is a tool for unified builds across many projects with custom requirements like the Debian's. If I need to force certain flag across multiple projects, I do use toolchain to pre-configure CMake overriding its defaults.

The CMake toolchain files are usually minimal as they do just few things, after the excellent https://crascit.com/professional-cmake/ book:

> - Describe basic details of the target system.
> - Provide paths to tools (typically just to the compilers).
> - Set the **default flags** for tools (usually just for compilers and perhaps linkers).
> - Set the location of a target platform’s root file system in the case of cross-compilation.

By the way, this is also important:

> Toolchain files should ideally be completely decoupled from the project and should even be reusable across different projects, since they should only be describing the toolchain, not how they interact with a particular project.

**Comment by mwtoews** [comment]
I might be wrong (and please correct me if I am), but one of the advantages of autotools (from a binary packager's perspective) is that it builds both static and dynamic libraries. The CMake set-up builds either static or dynamic via [BUILD_SHARED_LIBS](https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html). To get both libraries, it would need to be compiled twice, and then somehow "merged" to a binary package. Is this true?

**Comment by mloskot** [comment]
Correct. That is canonical CMake way. It can be configured to build both at the same time, using object libraries, and link objects generating both, but that is discouraged - shared and static libraries are often linked from objects compiled with different flags.

There had been discussions about it, e.g. [[CMake] Approach to both shared and static lib](https://cmake.org/pipermail/cmake/2018-May/thread.html)

**Comment by dg0yt** [comment]
@sebastic wrote:
> `CMAKE_BUILD_TYPE=Release` is not appropriate for Debian package because there will be no debug symbols then.
> 
> The Debian package build for CMake uses `CMAKE_BUILD_TYPE=None` by default for this reason. `RelWithDeInfo` is also common when packages diverge from the default.

@dg0yt wrote:
> For the record, unlike the documentation of `CMAKE_BUILD_TYPE`, CMake's `Modules/CMakeInitializeConfigs.cmake` lists `None` in the doc string of `CMAKE_BUILD_TYPE`. It is treated different from an empty string. (You might provide evil `CMAKE_C_FLAGS_NONE_INIT`...)

Like other projects, `proj` sets `CMAKE_BUILD_TYPE` to release when it evaluates to false:
https://github.com/OSGeo/PROJ/blob/9e2eb067585b9a61b2b5e636547ac80dd4d01d06/CMakeLists.txt#L219-L223

The empty value evaluates to false, so it is unsuitable for telling CMake to not apply additional flags. In contrast, "None" is able to achieve that goal. I think this should be adressed by CMake documentation, either by discouraging interference with an unconfigured/empty build type value, or by actively documenting `None`.

**Comment by dg0yt** [comment]
> The CMake set-up builds either static or dynamic via [BUILD_SHARED_LIBS](https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html). To get both libraries, it would need to be compiled twice, and then somehow "merged" to a binary package.

CMake doesn't seem to change this. They offer ["multi configuration" builds](https://discourse.cmake.org/t/cpack-distributing-both-shared-and-static-libraries/1225) now, but this means to build and install *all* artifacts twice.

For the particular situation of PROJ and debian packaging, I [successfully experimented](https://build.opensuse.org/package/show/home:dg0yt:branches:home:dg0yt:staging/proj) with extending a shared CMake build with a static build in a subdir with each program target explicitly disabled (*configure*), build only the "proj" target in this subdir (*build*), and finally run cmake -P cmake_install in the `src` subdir (*install*).

Excerpt from debian rules:
~~~
override_dh_auto_configure:
	dh_auto_configure --buildsystem=cmake -- \
	  -DUSE_EXTERNAL_GTEST:BOOL=ON
	mkdir $(CURDIR)/DebianStatic
	dh_auto_configure --buildsystem=cmake --builddirectory=$(CURDIR)/DebianStatic -- \
	  -DCMAKE_BUILD_TYPE=DebianStatic \
	  -DBUILD_SHARED_LIBS=0 \
	  -DBUILD_CCT:BOOL=OFF \
	  -DBUILD_CS2CS:BOOL=OFF \
	  -DBUILD_GEOD:BOOL=OFF \
	  -DBUILD_GIE:BOOL=OFF \
	  -DBUILD_PROJ:BOOL=OFF \
	  -DBUILD_PROJINFO:BOOL=OFF \
	  -DBUILD_PROJSYNC:BOOL=OFF \
	  -DBUILD_TESTING:BOOL=OFF

override_dh_auto_build:
	dh_auto_build
	cmake --build $(CURDIR)/DebianStatic --target proj

override_dh_auto_install:
	dh_auto_install
	DESTDIR=$(CURDIR)/debian/tmp cmake -P $(CURDIR)/DebianStatic/src/cmake_install.cmake
~~~
(This uses `CMAKE_BUILD_TYPE=DebianStatic` because it works like `None`, but is printed during the install step.)

Downsides of this approach:
- It doesn't apply equally well to other CMake-based projects. (No mitigation unless standardized by CMake.)
- For the install step, it uses the generated script directly. [Since CMake 3.18](https://cmake.org/cmake/help/v3.18/command/install.html#generated-installation-script), "Use of this feature is not recommended." (Possible mitigation: component-based install.)
- It still requires a long tail of options to avoid the installation of the programs. (Possible mitigation: a single option controlling the (default for) all programs, or a component-based install.)

---

FTR, In a similar way of secondary build, it might be possible to generate CMake config files in addition to an autotools build, assuming that the configuration (flags, dependencies etc.) is not too different.

**Comment by sebastic** [comment]
FWIW the loss of the static library when switching to CMake is generally not an issue.

**Comment by dg0yt** [comment]
> FWIW the loss of the static library when switching to CMake is generally not an issue.

Multi-arch seems to work, too. So I conclude that there are no blockers for removing autotools from the debian packaging POV, apart from the preference for autotools.

**Comment by dg0yt** [comment]
FTR Ubuntu has two tickets related to missing CMake files, and Fedora uses cmake but has a patch generating `proj.pc`. It is a pity that the issue was not discussed here earlier. There seems to be an interpretation that CMake is used only "internally" or "for Windows" when there is an autotools option.

**Comment by yobeonline** [comment]
In the meantime, maybe it would be good to modify https://proj.org/development/cmake.html to indicate that users may need to provide their own findPROJ.cmake file to make it work.

**Comment by yobeonline** [comment]
In case of autotools builds, how about deploying a cmake config script that uses pkg-config to provide the imported targets?
```cmake
find_package(PkgConfig REQUIRED)
pkg_check_modules(PROJ4 REQUIRED IMPORTED_TARGET proj)
	
add_library(PROJ4::proj ALIAS PkgConfig::PROJ4)
…
```

**Comment by ibaris** [comment]
> In the meantime, maybe it would be good to modify https://proj.org/development/cmake.html to indicate that users may need to provide their own findPROJ.cmake file to make it work.

And how to I build my own `findPROJ.cmake` file in order to use *PROJ*?????

**Comment by rouault** [comment]
The issue "CMake files not installed when autotools is used. pkg-config file not installed when using CMake" can now be closed: 
- we no longer have autotools,
- pkg-config files, as well as CMake config files, are now installed with cmake builds.

To find PROJ versions that don't ship with CMake config files, https://github.com/OSGeo/gdal/blob/master/cmake/modules/packages/FindPROJ.cmake can be used as an example

**Comment by ibaris** [comment]
Thank you very much for the hint. But are there no more documentation how to build and include this project in another CMake projects? I mean I followed the documentation [here](https://proj.org/install.html) (*Building on Windows with vcpkg and Visual Studio 2017 or 2019[¶](https://proj.org/install.html#building-on-windows-with-vcpkg-and-visual-studio-2017-or-2019)*) and [here](https://proj.org/development/cmake.html) and I tried to adapt the `FindPROJ.cmake` as you said. But I do not even to what path `PROJ_DIR`, `PROJ_INCLUDE_DIRS`, and `PROJ4_LIBRARIES` should point to.  `FindPROJ.cmake` tries to find the file `proj.h` in `PROJ_INCLUDE_DIRS`, but the file is present in `PROJ\build_vs2019\src`.

**Comment by dg0yt** [comment]
Paths need to point to where you *installed* the package. 

The linked documentation seems to target developing PROJ. If you want to use PROJ (and more) with vcpkg, the preferred form is vcpkg's manifest mode, and the alternative (classic mode) is a plain `vcpkg install proj4`. Modern versions of PROJ come with CMake config files, so you don't deal with `FindPROJ.cmake` and variables. The CMake usage instructions by vcpkg:
~~~
    find_package(PROJ CONFIG REQUIRED)
    target_link_libraries(main PRIVATE PROJ::proj)
~~~

If you don't use vcpkg, you will just have a few more steps to arrange on your own. But it is standard CMake.

**Comment by ibaris** [comment]
> dg0yt

Thank you very much! Now it works :heart_eyes:.
