### ISSUE TITLE
EPSG:28356 -> EPSG:3395 PROJ vs GDAL(?) conversion mismatch

### ISSUE THREAD

**Issue by ngodber** [OSGeo/PROJ#2563]
I've found a conversion mismatch between PROJ and that performed by QGIS (perhaps using GDAL in the back end, not sure) when transforming between EPSG 28356 and 3395. 

cs2cs EPSG:28356 EPSG:3395 
323816.3 6991035.5

![image](https://user-images.githubusercontent.com/11834846/110227256-2cbbb400-7f42-11eb-9d26-76b29e433268.png)

#### Problem description 
QGIS converts the same coordinates to 

16833884.92 | -3127974.262

So interestingly why I load the PROJ converted points they are offset by ~1.5 meters compared to the original and QGIS converted data set. I'm far from a GIS guru so it may well be that this is just the expected result of different transform definitions with one being no more 'right' than the other but I thought it would be worth at least getting the confirmation from those more knowledgeable in these matters than me. 

I've only limited options to confirm transforms but for what its worth I found that the EPSG.io transform matched QGIS https://epsg.io/transform#s_srs=28356&t_srs=3395&x=323816.3000000&y=6991035.5000000 though of course this could also be powered by GDAL in the backend. 

#### Expected Output
I expected that the transforms between GDAL and PROJ would be closer (eg decimeter?) if not exactly matching.

#### Environment Information
 - PROJ version (`proj`) 8.0.0
 - Operation System Information Win 10

#### Installation method
 - conda, apt-get, from source, etc...
conda from conda-forge

**Comment by kbevers** [comment]
What PROJ version is your QGIS install using?

**Comment by ngodber** [comment]
![image](https://user-images.githubusercontent.com/11834846/110233754-ef6f1a80-7f71-11eb-8804-4597c655401d.png)
Look like 6.3.2

**Comment by kbevers** [comment]
Without having looked further into this I would say that it is quite likely that is the explanation. The EPSG database gets updated all the time and so do PROJ itself. If you want to investigate this further you can install PROJ 6.3.2 and check the results of `projinfo -s EPSG:28356 -t EPSG:3395` from both versions and see if there are any differences.

**Comment by ngodber** [comment]
Hi, 

Thanks for the confirmation. Doing as you suggested there is indeed a new transformation in PROJ 8 that is absent in 6. That clears up what is going on. Thanks for the assistance.

Cheers,
Neil
