### ISSUE TITLE
Unify the proj and cs2cs input formats (allow EPSG shorcuts with proj)

### ISSUE THREAD

**Issue by jidanni** [OSGeo/PROJ#2564]
The proj man page should have examples of using EPSG codes, just
like the cs2cs man page has.

Or mention there on the proj man page why one cannot use them, (as
shortcut aliases.)

**Comment by kbevers** [comment]
> The proj man page should have examples of using EPSG codes, just like the cs2cs man page has.

You can't do that which is why such examples doesn't exist. You are welcome to suggest a text that explains that.

**Comment by jidanni** [comment]
I have a better idea.
Unify the proj and cs2cs input formats!
E.g.,
```
$ proj EPSG:3826
```
should also be an alias for the tedious error prone manual entry of
```
$ proj +proj=tmerc +lon_0=121 +k=0.9999 +x_0=250000 +ellps=GRS80
```

This would allow the unification of most of the entry formats on the
SYNOPSIS section of the cs2cs man page with proj!

OR, there on the proj man page, say:
"Some of you have so fallen in love with the succinct EPSG aliases, that
you can no longer bear to only be allowed to use their expanded forms,
as that is all that proj accepts.

No worry, just use cs2cs! Anything that proj can do, cs2cs can also do. Here's how..." (as per #2565!)

**Comment by jidanni** [comment]
Wait, proj CAN use EPSG codes,
```
proj -I +init=epsg:3828
```
it's just that there are no mention or examples on the proj man page
(compared with the cs2cs man page.)

So maybe some note of it should be made on the proj man page.
