### ISSUE TITLE
options for ios and android compilation

### ISSUE THREAD

**Issue by guiguite** [OSGeo/PROJ#2568]
Feature Request    
I understand Proj is currently designed for Desktop. Although version 4 was easy to compile for mobile (iOS and Android), versions 6 and above add many dependencies that make it hard to compile for those platforms.
It would be nice to have some options in the build scripts to cross-compile for those popular platforms, as location-aware applications are numerous and would greatly benefit from Proj.

**Comment by alionteo** [comment]
> Android builds aren't particularly difficult apparently. See https://github.com/opengisch/OSGeo4A/blob/master/recipes/proj/recipe.sh

Would it be possible to share some steps to integrate for mobile platforms like flutter? I am at very beginner level in proj. Thanks
