### ISSUE TITLE
Problem with tessellation st_make_grid() of library(sf) in R Studio

### ISSUE THREAD

**Issue by SnBuenafe** [OSGeo/PROJ#2579]
I'm trying to create a grid using `st_make_grid()` in RStudio 1.4.1103 using the `library(sf)`. I use macOS Big Sur Version 11.2.2. However, the tessellation of the area is not correct. In fact, it is not creating a grid using the area I set (`pacific_polygon` in the code shown below). A colleague who uses PROJ 7 but on windows platform was able to successfully recreate the grid (see plots below). 

```R
> library(sf)
Linking to GEOS 3.9.1, GDAL 3.2.1, PROJ 7.2.1
> pacific_pus <- st_make_grid(pacific_polygon, square = F, cellsize = c(53730, 53730)) %>% 
  st_sf()
> ggplot() +
  geom_sf(data = pacific_pus) +
  geom_sf(data = pacific_land, size = 0.05, fill = "grey20")
```
Here is the plot I'm getting:
![image](https://user-images.githubusercontent.com/78692266/111198156-8ca7ff80-85bf-11eb-8371-dcaf03d82a68.png)

Here is the expected output:
<img width="990" alt="Screen Shot 2021-03-15 at 7 00 27 PM" src="https://user-images.githubusercontent.com/78692266/111199245-b6155b00-85c0-11eb-977c-f75b68a89a4f.png">

#### Environment Information
 - PROJ version 7.2.1 (`proj 7.2.1`)
 - macOS Big Sur 11.2.2
 - RStudio 1.4.1103

#### Installation method
 - Homebrew

**Comment by hobu** [comment]
Please reopen this bug once it is clear what the issue is between PROJ 7 and PROJ 7.2.0 that is causing your issue.
