### ISSUE TITLE
Any update on IAU2000/2015 CRS support?

### ISSUE THREAD

**Issue by BerginJay** [OSGeo/PROJ#2601]
I noticed that there are already some discussions about IAU2000 CRS in QGIS, GDAL and here. Is there any update on these CRSs?
http://osgeo-org.1560.x6.nabble.com/Missing-lunar-CRS-td5444768.html
http://osgeo-org.1560.x6.nabble.com/PROJ-IAU2000-CRS-definitions-td5405737.html

**I find that there are already some repositories of IAU2000 CRSs in WKT format**:
https://github.com/USGS-Astrogeology/GDAL_scripts/tree/master/OGC_IAU2000_WKT_v2
https://svn.osgeo.org/metacrs/sr.org/srsbrowser/data/IAU2000.wkt

So can we migrate these wkt data into Proj directly？And what else need to be done?

I am not familiar with this projection thing. Please forgive me if there is anything wrong.

**Comment by kbevers** [comment]
> So can we migrate these wkt data into Proj directly？

I don't know about "we" but certainly "someone" can. That someone could be you. I think this would be a great addition to the PROJ CRS database but seing as it hasn't happened yet I don't think any of the regular contributors has much motivation to do the work. A motivated contributor can seek inspiration in the `build_db*` python scripts in https://github.com/OSGeo/PROJ/tree/master/scripts. It is likely that the new `--dump-db-structure` feature of `projinfo` added in #2577 could be helpful in this regard.

If you haven't got the skills to do it yourself and it is sufficiently important to your work, there's a good chance that you can hire one of previous contributors to this part of the PROJ codebase to do it on your behalf.

**Comment by rouault** [comment]
Hopefully I should have the contracting vehicle to do that in the coming months. It should have happened originally last year, but for some reasons was delayed. The source would likely be https://github.com/USGS-Astrogeology/GDAL_scripts/tree/master/OGC_IAU2000_WKT_v2

**Comment by BerginJay** [comment]
>  A motivated contributor can seek inspiration in the build_db* python scripts in https://github.com/OSGeo/PROJ/tree/master/scripts. It is likely that the new --dump-db-structure feature of projinfo added in #2577 could be helpful in this regard.

Thanks! I'd love to contribute. It seems a little difficult to me now, but I will keep studying and trying at my spare time.

And thank you @rouault! That would be the best.

**Comment by rouault** [comment]
update: I'll work at integrating https://github.com/thareUSGS/csvForWKT in coming weeks

**Comment by rouault** [comment]
Implemented in https://github.com/OSGeo/PROJ/pull/2876

**Comment by BerginJay** [comment]
Thank you very much! This is an very important work for the planetary community.

**Comment by MetroPietro** [comment]
Roualt, thank you for the CRS definitions! Unfortunately the implementation seems incomplete, or QGIS for some other reason is having difficulty parsing them. 
(1) I start a new blank session in QGIS 3.24.1 running GDAL/OGR version 3.4.2; PROJ version 9.0.0; EPSG Registry database version v10.054 (2022-02-13) on Windows 11. 
(2) I set the CRS to 49900 (LongLat); and create a multipolygon layer in a new Geopackage. I create a polygon in that layer, save edits, and save the QGIS session. 
(3) I change the CRS to 49950 (Robinson projection). QGIS throws errors about "No transform available" between 49950, custom CRS, and EPSG:4326. However on-the-fly reprojection seems to work.
(4) I create a Print Layout and add a Map with the 49950/Robinson projection. 
(5) When I add a scalebar, it refuses to draw, as if QGIS is unable to identify the scale.
Is there any way I can help get this to work?
