### ISSUE TITLE
no_kv_NKGETRF14_EPSG7922_2000.tif referenced in database but missing in PROJ-data

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#2602]
CC @himsve 
Issue raised in https://github.com/OSGeo/PROJ/pull/2598#issuecomment-804989891 :  no_kv_NKGETRF14_EPSG7922_2000.tif is not included in PROJ-data, but it is referenced by the NKG:NKG_ETRF14_ETRF93_2000 operation (itself used as a step of the NKG::ITRF2014_TO_NO concatenated operation), and there is an entry in the grid_alternatives table pointing to a non-existing file on PROJ CDN.
So either PROJ-data should be updated to have this file, or the entry in grid_alternatives should be removed/amended.

**Comment by himsve** [comment]
There was a conflict at the pull request [https://github.com/OSGeo/PROJ-data/pull/58](url). The conflict is solved. (https://github.com/OSGeo/PROJ/issues/2602 is depended on https://github.com/OSGeo/PROJ-data/pull/58).

**Comment by rouault** [comment]
Ah, I had forgotten that there was a related pending PR in PROJ-data.
