### ISSUE TITLE
Document how to use grid shifts

### ISSUE THREAD

**Issue by jidanni** [OSGeo/PROJ#2607]
```
$ proj -lp|grep grid.*shift
deformation : Kinematic grid shift
hgridshift : Horizontal grid shift
vgridshift : Vertical grid shift
xyzgridshift : Geocentric grid shift
```
look interesting.  Perhaps add some examples somewhere on how to use
them.

**Comment by kbevers** [comment]
All described here: https://proj.org/operations/transformations/index.html

**Comment by jidanni** [comment]
I see. Debian [was not _playing with a full deck_](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=985978).
