### ISSUE TITLE
Document simple decimal degrees / DMS conversion method

### ISSUE THREAD

**Issue by jidanni** [OSGeo/PROJ#2608]
Let's say the user simply has a file full of longitude-latitude pairs
that he wishes to convert between decimal degrees / DMS.

He thinks proj/cs2cs's output format looks great and doesn't want to
bother using a more efficient program or write his own.

So please document (somewhere) the most efficient way of doing it with proj/cs2cs
is.

Perhaps:

```
$ echo 120.67943615257 24.1429030776298 | cs2cs +proj=longlat +to +proj=longlat
120d40'45.97"E	24d8'34.451"N 0.000
```

Also when writing the example, mention reasons for loss of precision in e.g.,
```
$ echo 120.67943615257 24.1429030776298 |
  cs2cs +proj=longlat +to +proj=longlat |
  cs2cs -f %.13f +proj=longlat +to +proj=longlat
120.6794361111111 24.1429030555556 0.0000000000000
```

**Comment by jidanni** [comment]
Hmmm, maybe on https://proj.org/operations/conversions/noop.html

**Comment by kbevers** [comment]
This belong on the cs2cs doc pages, seing as it is functionality provided by those two applications. I don't like the cs2cs example since it is using projstrings. 

```
$ echo 120.67943615257 24.1429030776298 | cs2cs EPSG:4326 EPSG:4326
120d40'45.97"N	24d8'34.451"E 0.000
```

would be a more modern approach.

proj can't be used for this, as it won't let you set up operations that return angular coordinates:

```
$ echo 120.67943615257 24.1429030776298 | proj +proj=latlon
Rel. 7.1.1, September 1st, 2020
<proj>:
can't initialize operations that produce angular output coordinates
program abnormally terminated
```

**Comment by jidanni** [comment]
> $ echo 120.67943615257 24.1429030776298 | cs2cs EPSG:4326 EPSG:4326

But please remove any reference to any certain 4326, 4327 etc. as we don't want the reader to think the answer is related to any parameters contained with those definitions.

Anyway, perhaps cs2cs could allow a noop parameter...

**Comment by kbevers** [comment]
> But please remove any reference to any certain 4326, 4327 etc. as we don't want the reader to think the answer is related to any parameters contained with those definitions.

You seem to think that I am going to make these changes. This is a community effort. If you think something is wrong, fix it :-)

**Comment by jidanni** [comment]
Yes, but I don't know what to write, nor where to write it.

**Comment by jidanni** [comment]
Maybe this, seen in the PDF manual,

> 7.2.10  Unit conversionNew in version 5.0.0.Convert between various
> distance, angular and time units.

can somehow be used.

**Comment by kbevers** [comment]
No, that's for converting between units, not how units are represented on screen. `unitconvert` can't give you angular output expressed as DMS.
