### ISSUE TITLE
Question: vertical transformation difference (PROJ 5.2 versus PROJ 8)

### ISSUE THREAD

**Issue by snowman2** [OSGeo/PROJ#2609]
Forwarded from: https://gis.stackexchange.com/questions/391224/postgis-st-transform-seems-to-treat-the-vertical-datum-but-not-the-equivalent-py/ (more details there. summary added here.)

### PROJ 8:
```
echo 47.01987 8.37909 1000 | cs2cs -d 8 'epsg:4326' 'epsg:2056'
2671499.89130806	1208075.11357823 1000.00000000
$ cs2cs
Rel. 8.0.0, March 1st, 2021
```
This is the same with pyproj using PROJ 8.

### PROJ 5:
In PostGIS:
```
SELECT 
  ST_AsText(
    ST_Transform(
      ST_SetSRID(
        ST_MakePoint(8.37909, 47.01987, 1000),
      4326),
    2056)
  ) AS geom;

```
Output:
```
"POINT Z (2671499.8913080636 1208075.1135782269 951.4265527641401)"
```
This result the same using pyproj with PROJ 5.2.

```
SELECT PostGIS_Full_Version();

"POSTGIS=""3.1.0 5e2af69"" [EXTENSION]     
  PGSQL=""130""    
  GEOS=""3.7.1-CAPI-1.11.1 27a5e771""
  PROJ=""Rel. 5.2.0, September 15th, 2018""
  LIBXML=""2.9.4""
  LIBJSON=""0.12.1""
  LIBPROTOBUF=""1.3.1""
  WAGYU=""0.5.0 (Internal)""    
TOPOLOGY"
```

I have seen some issues related to force it to be 3D or something around that, but am not sure what is relevant. Do you have any ideas/suggestions/recommendations?

**Comment by rouault** [comment]
With PROJ 8 and explicit use of 3D CRs (with ellipsoidal height):
```
$ echo 47.01987 8.37909 1000 | cs2cs -d 8 EPSG:4979 "$(projinfo EPSG:2056 --3d --single-line -q -o WKT2:2019)"
2671499.89130806	1208075.11357823 951.42655277
```
At the C API level you can use proj_crs_promote_to_3D() from proj_experimental.h

**Comment by snowman2** [comment]
Thanks @rouault, that was very helpful. Thoughts about promoting `proj_crs_promote_to_3D` to `proj.h`?

**Comment by rouault** [comment]
> Thoughts about promoting `proj_crs_promote_to_3D` to `proj.h`?

I guess we could move most/all functions from proj_experimental.h to proj.h. Most of them have been used and required by GDAL since a long time. You can just safely include proj_experimental.h

**Comment by snowman2** [comment]
Thanks @rouault :+1: I will open a new issue to discuss moving functions from `proj_experimental.h` to `proj.h`.
