### ISSUE TITLE
Equal Earth - can't create WKT1 string

### ISSUE THREAD

**Issue by kyngchaos** [OSGeo/PROJ#2610]
#### Problem description

PROJ can't create a WKT1 (GDAL or Esri) string for the Equal Earth projection.  An error occurs:

`Error when exporting to WKT1:GDAL: Unsupported conversion method: Equal Earth`

or 

`Error when exporting to WKT1:ESRI: Unsupported conversion method: Equal Earth`

from PROJ:

`projinfo -o WKT1:GDAL EPSG:8857`
`projinfo -o WKT1:ESRI EPSG:8857`

This affects GDAL when using ogr2ogr to convert or warp vectors to shapefile format.  Internally it works, and the coordinates are correctly projected and written to the shapefile, but ogr2ogr can't create the PRJ:

`ERROR 1: PROJ: proj_as_wkt: Unsupported conversion method: Equal Earth`

#### Environment Information
 - PROJ version 7 and 8, compiled from source
 - macOS 10.14

**Comment by rouault** [comment]
That WKT1:GDAL doesn't support it is expected since WKT1:GDAL is the subset of WKT understood by GDAL <= 2.4 and PROJ = <= 5.2
Mapping to WKT1:ESRI that is used for shapefile .prj added in https://github.com/OSGeo/PROJ/pull/2611

**Comment by kyngchaos** [comment]
Can this be backported to PROJ 7.2?  or is that dead now with v8 release?  I'm waiting on v8 while QGIS works out kinks (I've seen some commits there for v8 support, so I assume it's not fully supported yet).

**Comment by rouault** [comment]
the 7.2 branch isn't anymore maintained by the project. QGIS should just work fine with PROJ 8. There were just a few issues with things trying to include proj_api.h that was removed and a few typedefs changes, but that's about all.

**Comment by kyngchaos** [comment]
I've already started packaging 3.16 LTR (Mac) with PROJ 7.2.  I'll try a manual backport for my proj 7 build.

**Comment by rouault** [comment]
you only need to backport the changes in esriparammappings.cpp ( https://github.com/OSGeo/PROJ/commit/752cb2a162e74235d7fac534aeec37894e024de0#diff-6ed8130500cd65dfda26c799767ce976058510ff16d6fdb763f6ff148a3bbb7a  )
