### ISSUE TITLE
Promoting functions from proj_experimental.h to proj.h

### ISSUE THREAD

**Issue by snowman2** [OSGeo/PROJ#2614]
> I guess we could move most/all functions from proj_experimental.h to proj.h. Most of them have been used and required by GDAL since a long time.

_Originally posted by @rouault in https://github.com/OSGeo/PROJ/issues/2609#issuecomment-808737977_

I think moving methods to `proj.h` would be good to plan on doing for clarity for developers to know that these methods are stable and ready for use.

Having a specific version when this transition will be beneficial for `pyproj` to increase the likelihood that the upcoming releases will be compatible with future releases of PROJ.

For example, knowing the version when the switch will occur enables this:
```python
IF (CTE_PROJ_VERSION_MAJOR, CTE_PROJ_VERSION_MINOR) >= (8, 1):
    cdef extern from "proj.h":
        PJ *proj_crs_promote_to_3D(PJ_CONTEXT *ctx,
                                    const char* crs_3D_name,
                                    const PJ* crs_2D);
ELSE:
    cdef extern from "proj_experimental.h":
        PJ *proj_crs_promote_to_3D(PJ_CONTEXT *ctx,
                                    const char* crs_3D_name,
                                    const PJ* crs_2D);
```
Any thoughts on when this would be good to do?

**Comment by rouault** [comment]
I don't know how tpyrex works, but as proj_experimental.h includes proj.h, you could potentially just use the ELSE branch, even if the function is moved to proj.h some day. This is assuming pyrex can follow #include.

**Comment by snowman2** [comment]
> I don't know how tpyrex works, but as proj_experimental.h includes proj.h, you could potentially just use the ELSE branch, even if the function is moved to proj.h some day. This is assuming pyrex can follow #include.

I tried it out with another function inside `proj.h` and it seems to work. Thanks, that was very helpful :+1:
