### ISSUE TITLE
The extent of EPSG extent 3593 'New Zealand - offshore' appears to be backwards across the date line. (Maybe EPSG bug?)

### ISSUE THREAD

**Issue by rhuijben** [OSGeo/PROJ#2615]
* Example of problem

If my demo application (part of SharpProj. A new wrapping around PROJ for C#/.Net users) displays EPSG 3851
![image](https://user-images.githubusercontent.com/2271549/112746654-8bf46d80-8fb0-11eb-87e0-88781f4eb42b.png)

It shows the entire world, it finds the bounds East-West of 160.6 - -171.2, while EPSG.org shows the region as

![image](https://user-images.githubusercontent.com/2271549/112746695-e7bef680-8fb0-11eb-9905-bdb7826f04fd.png)

* Problem description

As the region is wrapped around, the bounding box excludes what actually should be included.

* Expected Output

The region should be ok, so tools relying on the output should work correctly.

The information is in extend.sql, and appears auto generated. So I expect a bug somewhere in the conversion chain.
```
a9b6f3949 (** 2020-09-24 22:41:59 +0200 2572) INSERT INTO "extent" VALUES('EPSG','3593','New Zealand - offshore','New Zealand - offshore.',-55.95,-25.88,160.6,-171.2,0);
```

*  Environment Information
PROJ 8.0.0
Windows

**Comment by rhuijben** [comment]
Looks like a different issue

**Comment by rouault** [comment]
> The information is in extend.sql, and appears auto generated. So I expect a bug somewhere in the conversion chain.

It is expected, by convention, for extents crossing the antimerdian to have west_lon (close but a bit below to +180) and east_lon (close but a bit above to -180)
