### ISSUE TITLE
Add comma in +ellps +R

### ISSUE THREAD

**Issue by jidanni** [OSGeo/PROJ#2645]
Many places in the manual, one sees
> If used in conjunction with +ellps +R takes precedence.
> If used in conjunction with +ellps, +R takes precedence.

I.e., adding a comma, would be clearer.

**Comment by kbevers** [comment]
This is a trivial change, please just open a pull request for those. Relevant file here https://github.com/OSGeo/PROJ/blob/master/docs/source/operations/options/R.rst

**Comment by jidanni** [comment]
OK, ah, so that was the file where it lives.
