### ISSUE TITLE
false easting/northing override for utm proj-string

### ISSUE THREAD

**Issue by namdre** [OSGeo/PROJ#2651]
Hello,
i'm not sure if this is a feature or a bug (i'd label it a question if i could):

 I've received geo-referenced data from another program with the proj-string

`+proj=utm +zone=31 +ellps=WGS84 +datum=WGS84 +x_0=613156.00 +y_0=5639788.95 +units=m +no_defs`

When creating a projection from this string (using the libproj 6.3.1-1 package on ubuntu) it appears that the `x_0` and `y_0` parameters are ignored. 

According to [old information from gis.stackexchange.com](https://gis.stackexchange.com/questions/21827/can-we-use-proj-to-offset-coordinates) this is to be expected because UTM uses it's own implicit easting/northing values. 

1) is the behavior described above still expected?
2) what is the recommended proj-string to represent UTM coordinates with a custom offset?

**Comment by rouault** [comment]
you're fortunate that PROJ is open source so the answer is at https://github.com/OSGeo/PROJ/blob/master/src/projections/tmerc.cpp#L728
I guess you want to use "+proj=tmerc +lon_0=3 +k_0=0.9996 +datum=WGS84 +x_0=613156.00 +y_0=5639788.95 +units=m +no_defs"

**Comment by namdre** [comment]
Thank you very much! Does that mean the answer to 1) is "Yes"?

**Comment by rouault** [comment]
> Does that mean the answer to 1) is "Yes"?

I'd say yes : https://proj.org/operations/projections/utm.html doesn't mention x_0 / y_0. UTM is a "profile" of Transverse Mercator where there is only 2 parameters : zone and south/north indicator that define togerther x_0, y_0, lat_0, lon_0 and k_0 of tmerc. So if you override them, you're in a unspecified land . @kbevers  thoughts ?

**Comment by kbevers** [comment]
Setting `+x_0` and `+y_0` on the UTM projection should not change the behaviour of the UTM projection since it will no longer be a UTM projection. The current behaviour is the way it is by design and the docs reflect that as well. If you want to offset UTM coordinates using `tmerc` as described by @rouault is the way to go.

**Comment by namdre** [comment]
Thanks again!

**Comment by busstoptaktik** [comment]
> i'm not sure if this is a feature or a bug (i'd label it a question if i could)

@namdre: In general, the proper place for questions is the PROJ mailing list (cf. https://proj.org/community/channels.html), where you'll find a community of helpful, skillful and friendly people.
