### ISSUE TITLE
Inconsistent chaining of CRS in operations

### ISSUE THREAD

**Issue by d3netxer** [OSGeo/PROJ#2658]
First tried using Geopandas and then pyproj, but running into the same problem. Using example below using pyproj to document the issue, this command:

```
projinfo -s EPSG:32640 -t ESRI:54009 -o PROJ
```

results in this error:

```
createOperations() failed with: Inconsistent chaining of CRS in operations
```

curiously, doing it in reverse does not produce an error:

```
projinfo -s ESRI:54009 -t  EPSG:32640 -o PROJ
```

#### Environment Information
 - PROJ version: 6.2.1
 - Operation System Information: Anaconda environment on Windows

#### Installation method
 - conda

**Comment by rouault** [comment]
This works in PROJ 8.0 branch and master:
```
$ projinfo -s EPSG:32640 -t ESRI:54009 -o PROJ
Candidate operations found: 1
-------------------------------------
Operation No. 1:

unknown id, Inverse of UTM zone 40N + axis order change (2D) + World_Mollweide, 0 m, World

PROJ string:
+proj=pipeline
  +step +inv +proj=utm +zone=40 +ellps=WGS84
  +step +proj=moll +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84
```
You need to upgrade your PROJ version. I remember having fixed such issues a number of time in past months.
