### ISSUE TITLE
cmake build: automate .so versionning from autoconf

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#2675]
I see libtiff has automated logic to automatically set the same .so.x.y.z scheme as autoconf.
See https://gitlab.com/libtiff/libtiff/-/blob/master/cmake/AutotoolsVersion.cmake
and its used in https://gitlab.com/libtiff/libtiff/-/blob/master/libtiff/CMakeLists.txt#L139

Could be a good idea to adopt this in PROJ too. At least while we have dual autoconf & cmake support

**Comment by kbevers** [comment]
> At least while we have dual autoconf & cmake support

Would this also be your preferred option if we only had CMake? From recent discussions I feel a slight consensus emerging regarding ditching autoconf and only supporting CMake in the (near?) future. Should that happen, would we then have to return to the current cmake .so version naming scheme? In other words, if we are going to drop autoconf I'd rather not end up in a situation where the CMake .so's changes naming scheme twice in a short period of time.

**Comment by rouault** [comment]
> In other words, if we are going to drop autoconf I'd rather not end up in a situation where the CMake .so's changes naming scheme twice in a short period of time.

ah ah yes when writing that ticket, I realized that just dropping autoconf support might be a way to resolve it. I don't have personaly a strong opinion regarding that but would be supportive of keeping only cmake support. I know GEOS recently dropped autoconf support. The only point that is probably missing to switch fully to cmake is a "make dist" target to it to create the release tarball.

**Comment by kbevers** [comment]
> ah ah yes when writing that ticket, I realized that just dropping autoconf support might be a way to resolve it.

A CMake only PROJ would indeed be a lot simpler. I think it is time to start drafting a RFC on the topic. Of course that should include a transition plan. 

@mwtoews @mloskot in https://github.com/OSGeo/PROJ/issues/2546 the two of you both seem to be in favour of dropping autoconf. Would you be willing to draft an RFC on that? I'm happy to help but I'm afraid I don't have the necessary CMake expertise to do it justice.

**Comment by mloskot** [comment]
> you both seem to be in favour of dropping autoconf. 

@kbevers I'm inherently in favour of avoiding the autotools, but I'm not having any expectations from PROJ specifically. 

> Would you be willing to draft an RFC on that?

Despite that I'm not quite able to allocate time for that right now, I prefer not to be linked as author of the autotools drop motion - I'd rather avoid a clash (again) with the autotools supporters :)

**Comment by kbevers** [comment]
>  I'd rather avoid a clash (again) with the autotools supporters :)

Sure, I understand that :-)

**Comment by mwtoews** [comment]
Sure, I can draft up a RFC. It would more-or-less look like [GEOS' RFC7](https://trac.osgeo.org/geos/wiki/RFC7). Several objectives would need to be in place before implementation, such as "make dist".

Looking at the [milestones](https://github.com/OSGeo/PROJ/milestones?direction=asc&sort=title&state=open), is there an ideal target release when this would be considered for implementation? 8.2 in Nov 2021? Or later?

**Comment by kbevers** [comment]
> Sure, I can draft up a RFC.

Awesome, thanks!

> Looking at the milestones, is there an ideal target release when this would be considered for implementation? 8.2 in Nov 2021? Or later?

Good question. Not sure if a change like this would need a bump in major version number? In that case it could be 9.0 March 1st 2022 (continuing the tradition of major version release in march). If not, 8.2 could be a possibility. It would give roughly six month notice - is that enough? Ideally we would have the new CMake setup ready well before that so packagers can test it beforehand.

**Comment by mwtoews** [comment]
I would prefer to aim for a major version bump for this type of change. A relaxed timeline should suit everyone. Some of the objectives required for CMake can be prepared before. It could be interesting to see how GEOS progresses for their next CMake-only release.

**Comment by kbevers** [comment]
I would too. Having another major release gives us a chance to clean up minor things in the API as well (I believe we have a few deprecated functions already). 

It would be good to get an RFC confirmed as quickly as possible so we can communicate the upcoming changes as soon as possible. Ideally it would also be good to be able to put out a test release using only cmake in paralllel with the regular release. The 8.2 release should be suitable for that.
