### ISSUE TITLE
[Security] Potential Secret Leak

### ISSUE THREAD

**Issue by raima-zachariah** [OSGeo/PROJ#2694]
It has been noticed that while using Gaurav0/backport@v1.0.26 your bot_token c1c49a5799d0a3a3885db8a4792880cbe509c1d6 is present in plaintext. Please ensure that secrets are encrypted or not passed as plain text in github workflows.

**Comment by jmckenna** [comment]
This is a similar report for MapServer.  I had to setup a BOT_TOKEN_KEY secret in the GitHub project settings, and then replace the bot_token_key in backport.yml with ${{ secrets.BOT_TOKEN_KEY }}.

**Comment by kbevers** [comment]
As far as I can tell you are referring to a previous version of https://github.com/OSGeo/PROJ/blob/master/.github/workflows/backport.yml. The token isn't exposed in the curren incarnation and I am quite sure that the exposed token ins't valid anymore.
