### ISSUE TITLE
Doc: dead link to schema of the triangulation format

### ISSUE THREAD

**Issue by jratike80** [OSGeo/PROJ#2699]
The manual page https://proj.org/operations/transformations/tinshift.html? has a dead link to the json schema 
https://proj.org/schemas/triangulation.schema.json

I can find the file from GitHub https://github.com/OSGeo/PROJ/blob/master/data/triangulation.schema.json but I do not know if that is a correct link to use in the document.

**Comment by rouault** [comment]
@kbevers This should be cherry-picked to 8.0 branch for website refresh. Should I wait to do that while 8.0.1 hasn't been released ?

**Comment by kbevers** [comment]
@rouault just do it now. It won't affect the final 8.0.1 release archives, so we might as well get the docs updatede straight away.

**Comment by rouault** [comment]
done
