### ISSUE TITLE
PROPOSAL: mode where the SQLite3  db handle would be shared amongst several contexts

### ISSUE THREAD

**Issue by snowman2** [OSGeo/PROJ#2700]
From: https://lists.osgeo.org/pipermail/gdal-dev/2021-April/054022.html

> In theory that could 
be possible as you can invoke sqlite3_open_v2() with 
SQLITE_OPEN_FULLMUTEX. But would require non completely trivial changes
> @rouault 

Sounds like something worth having it's own issue.

**Comment by snowman2** [comment]
Closing for #2728

**Comment by rouault** [comment]
ah sorry, didn't realize there was an existing one

**Comment by snowman2** [comment]
No worries - just glad to see that it is something you are thinking about.
