### ISSUE TITLE
Stereographics vs. Stererographics: typo?

### ISSUE THREAD

**Issue by mwtoews** [OSGeo/PROJ#2701]
Compare the two words:

1. `Stereographics`
2. `Stererographics`

Only 2 is currently used throughout PROJ for these:

1. [Modified Stererographics of Alaska](https://proj.org/operations/projections/alsk.html)
2. [Mod. Stererographics of 48 U.S.](https://proj.org/operations/projections/gs48.html)
2. [Mod. Stererographics of 50 U.S.](https://proj.org/operations/projections/gs50.html)

The singular version of 1 (stereographic) is used extensively i.e. [stereographic projection](https://en.wikipedia.org/wiki/Stereographic_projection).

Is 2 a typo? Should these be "Stereographics"? Or the singular "Stereographic"? I'm 99% certain this is a typo, but it's been there for a few decades, embedded in `PROJ_HEAD` and all. Page 18 of [proj_4_3.pdf](https://github.com/OSGeo/PROJ/blob/master/docs/old/proj_4_3.pdf) uses the singular Stereographic (1), suggesting that 2 is a typo.

**Comment by rouault** [comment]
Most certainly a typo. Snyder, "Map Projections - a working manual" (https://pubs.usgs.gov/pp/1395/report.pdf) mentions at page 9:
```
44. Modified-Stereographic Conformal projection of Alaska -----------------------------------------------------------------------------------205 
45. Modified-Stereographic Conformal projection of 48 United States, bounded by a  near-rectangle of constant scale ---------------206 
```
