### ISSUE TITLE
QST: Different order of operations returned with `--bbox`

### ISSUE THREAD

**Issue by snowman2** [OSGeo/PROJ#2703]
I couldn't find the relevant change in the history, but seem to remember something was changed related to the order of the operations. This is what I am seeing currently with the difference:

### Command:
```bash
projinfo -s "EPSG:4326" -t "EPSG:2964"  --bbox -136.46,49.0,-60.72,83.17 --spatial-test intersects
```

### Output
PROJ 8.0.0:
```
Candidate operations found: 7
-------------------------------------
Operation No. 1:

unknown id, Inverse of NAD27 to WGS 84 (33) + Alaska Albers, 1 m, Canada - onshore - Alberta; British Columbia; Manitoba; New Brunswick; Newfoundland and Labrador; Northwest Territories; Nova Scotia; Nunavut; Ontario; Prince Edward Island; Quebec; Saskatchewan; Yukon; offshore east coast., at least one grid missing

...
Grid ca_nrc_ntv2_0.tif needed but not found on the system. Can be obtained at https://cdn.proj.org/ca_nrc_ntv2_0.tif

-------------------------------------
Operation No. 2:

unknown id, Inverse of NAD27 to WGS 84 (13) + Alaska Albers, 8 m, Canada - Northwest Territories; Nunavut; Saskatchewan.

...
...
```

8.0.1 & Current master:
```
Candidate operations found: 7
-------------------------------------
Operation No. 1:

unknown id, Inverse of NAD27 to WGS 84 (13) + Alaska Albers, 8 m, Canada - Northwest Territories; Nunavut; Saskatchewan.

...

-------------------------------------
Operation No. 2:

unknown id, Inverse of NAD27 to WGS 84 (33) + Alaska Albers, 1 m, Canada - onshore - Alberta; British Columbia; Manitoba; New Brunswick; Newfoundland and Labrador; Northwest Territories; Nova Scotia; Nunavut; Ontario; Prince Edward Island; Quebec; Saskatchewan; Yukon; offshore east coast west of 44°W and north of 40°N., at least one grid missing
...

Grid ca_nrc_ntv2_0.tif needed but not found on the system. Can be obtained at https://cdn.proj.org/ca_nrc_ntv2_0.tif

```

Are you able to point me to the relevant change?

**Comment by rouault** [comment]
I don't get the same results as you. This might depend on the grids you've available in your PROJ data directory. I also tried to play with the --grid-check flag to abstract that away, but still doesn't get the same results as you. Anyway, I strongly suspect this might be linked to https://github.com/OSGeo/PROJ/pull/2679 . I let you do a git bisect if you really want to spot the commit that changes the behaviour for you.

**Comment by snowman2** [comment]
> I don't get the same results as you. 

What results do you get?

> This might depend on the grids you've available in your PROJ data directory. 

I thought that might be it as well, but it happens even when PROJ_NETWORK=ON/OFF.

> I let you do a git bisect if you really want to spot the commit that changes the behaviour for you.

Sounds like that might have to be what I will have to do.

**Comment by snowman2** [comment]
Related: https://github.com/pyproj4/pyproj/issues/833

**Comment by rouault** [comment]
with an additional "--grid-check known_available", with PROJ master:
unknown id, Inverse of NAD27 to WGS 84 (13) + Alaska Albers, 8 m, Canada - Northwest Territories; Nunavut; Saskatchewan.
unknown id, Inverse of NAD27 to WGS 84 (33) + Alaska Albers, 1 m, Canada - onshore - Alberta; British Columbia; Manitoba; New Brunswick; Newfoundland and Labrador; Northwest Territories; Nova Scotia; Nunavut; Ontario; Prince Edward Island; Quebec; Saskatchewan; Yukon; offshore east coast west of 44°W and north of 40°N., at least one grid missing
[...]

with an additional "--grid-check known_available", with 8.0.1 and 8.0.0:
unknown id, Inverse of NAD27 to WGS 84 (33) + Alaska Albers, 1 m, Canada - onshore - Alberta; British Columbia; Manitoba; New Brunswick; Newfoundland and Labrador; Northwest Territories; Nova Scotia; Nunavut; Ontario; Prince Edward Island; Quebec; Saskatchewan; Yukon; offshore east coast., at least one grid missing
unknown id, Inverse of NAD27 to WGS 84 (13) + Alaska Albers, 8 m, Canada - Northwest Territories; Nunavut; Saskatchewan.
[...]

and with the 3 of them, without --grid-check and on a proj data directory without any grid:
unknown id, Inverse of NAD27 to WGS 84 (13) + Alaska Albers, 8 m, Canada - Northwest Territories; Nunavut; Saskatchewan.
unknown id, Inverse of NAD27 to WGS 84 (3) + Alaska Albers, 20 m, Canada - onshore - Alberta; British Columbia; Manitoba; New Brunswick; Newfoundland and Labrador; Northwest Territories; Nova Scotia; Nunavut; Ontario; Prince Edward Island; Quebec; Saskatchewan; Yukon; offshore east coast west of 44°W and north of 40°N.
unknown id, Inverse of NAD27 to WGS 84 (10) + Alaska Albers, 13 m, Canada - Alberta; British Columbia.
unknown id, Inverse of NAD27 to WGS 84 (14) + Alaska Albers, 10 m, Canada - Yukon.
unknown id, Inverse of NAD27 to WGS 84 (7) + Alaska Albers, 12 m, United States (USA) - Alaska mainland.
unknown id, Inverse of NAD27 to WGS 84 (33) + Alaska Albers, 1 m, Canada - onshore - Alberta; British Columbia; Manitoba; New Brunswick; Newfoundland and Labrador; Northwest Territories; Nova Scotia; Nunavut; Ontario; Prince Edward Island; Quebec; Saskatchewan; Yukon; offshore east coast west of 44°W and north of 40°N., at least one grid missing
unknown id, Inverse of NAD27 to WGS 84 (85) + Alaska Albers, 5 m, United States (USA) - Alaska including EEZ., at least one grid missing

**Comment by snowman2** [comment]
Well, at least it shows up in PROJ master on your end. I am assuming that this behavior change is expected, correct?

**Comment by rouault** [comment]
>  I am assuming that this behavior change is expected, correct?

I actually see this is related to EPSG v10.019 update in master. If I run master against proj.db with EPSG 10.018, I get the same results as with the 8.0 branch. This is related to some changes in extents in the v10.019. See changes in data/sql/extent.sql in f6abb7d75c647013dd83a82361b96c202e615d90

**Comment by snowman2** [comment]
That makes sense. Thanks 👍
