### ISSUE TITLE
Foucault vs. Foucaut: typo?

### ISSUE THREAD

**Issue by mwtoews** [OSGeo/PROJ#2704]
Compare the two:

1. `Foucault`
2. `Foucaut`

Only 2 is used in PROJ (e.g. [`fouc`](https://proj.org/operations/projections/fouc.html)), and I'm 99.5% certain it is a typo that should be spelled as 1. I suppose this is named after [Léon Foucault](https://en.wikipedia.org/wiki/L%C3%A9on_Foucault)?

Similar to #2701, this is a decades old typo embedded in `PROJ_HEAD`, etc.

(Yes, I'm working on a general spelling PR, but am individually creating issues for prominent typos that may require cross-referencing, and yes I intend to fix these too.)

**Comment by rouault** [comment]
Yeah, a treasure hunt ! I think that Foucaut, without l, is the correct spelling in that instance. There are indeed quite a few known French men with Foucault name, with l, including the one of the pendulum experiment you quoted (Léon Foucault) or more recently the philosopher Michel Foucault (https://en.wikipedia.org/wiki/Michel_Foucault). Although if you ask to the random French guy about Foucault, they will think to https://en.wikipedia.org/wiki/Jean-Pierre_Foucault :-)

But here, it seems this is "Henri Casimir Auguste De Prépetit Foucaut"

First hint I found was on https://bl.ocks.org/Fil/4db96f1250ad6118290e24d62e67187d which has a references to "Capitaine De Prépetit Foucaut, Notice sur la construction de nouvelles mappemondes et de nouveaux atlas, pp. 5-10, Arras, France, 1862."
But googling for that name doesn't lead to interesting results. But the second reference to "Coup d'oeil historique sur la projection des cartes de géographie, M. d'Avezac - 1863." leads to its digital version at Bibliothèque Nationale de France:  http://gallica.bnf.fr/ark:/12148/bpt6k6574475p and at page 11 of that document they mention:
"Le capitaine du génie Henri-Casimir-Auguste DE PRÉPETIT FOUCAUT, dans une Notice sur la construction de nouvelles mappemondes et de nouveaux atlas de géographie, lithographiée à Arras en 1862, s'est occupé spécialement de la projection de la mappemonde entière dans ce dernier système"

**Comment by mwtoews** [comment]
Perfect, thanks! This all makes sense. Added to (to be committed) `spelling_wordlist.txt`.
