### ISSUE TITLE
Adding new projection: Cupola

### ISSUE THREAD

**Issue by dkapitan** [OSGeo/PROJ#2706]
Recently Weia Reinboud defined a new asymmetric equal area worldmap projection, named Cupola, see [this journal paper here](https://www.tandfonline.com/eprint/EE7Y8RK4GXA4ITWUTQPY/full?target=10.1080/23729333.2020.1862962).

She has actually written the code herself and I offered to help contribute the Cupola projection to the open source community. Now I am quite proficient with Python, but not that experienced with geodata processing nor C.

I thought that I could implement a projection directly in WKT, but apparently that's not the case? Basically the Python pseudo-code below is what I want to implement.

```python
# parameters for Cupola
c1 = 0.5253 # part of the equator on intermediate sphere, default = 1
c2 = 0.7264 # sin of angle of polarline; default = 1
c3 = 0.4188 # height of the equator, can be negative, default = 0
c4 = 22.00 # phi of centre projection in degrees, default = 0
c5 = 0.9701 # strech in plane, default = 1

# constants
c6 = 11.023  # central meridian 11.023 degrees, also defines border of the map
c7 = 180.00 # degrees to the right of c6, default = 180
grid = 30 # grid distance in degrees
r2 = 1.61885660611815
w123 = 0.258701109423297
c4r = 0.383972435438752
pc = 0.559562341761853


def cupola_projection(u , v, c1, c2, c5, r2, w123, spc, cpc, qc):
    """
    (phi, lambda) as (lat, lon) in degrees --> (u, v) in radians --> (p, q) in radians on intermediate sphere --> (x, y) cartographic projection.
    """
    spc = sin(pc)
    cpc = cos(pc)
    c6 = c6+(180-c7)
    c6r = pi * c6/180  # c6 in [rad], v of center of projection
    qc = c1*c6r

    # calculate (p, q)
    p = asin(c2*sin(u)+w123)
    sp = sin(p)
    cp = cos(p)
    q = c1*v

    qqc = q-qc
    sqqc = sin(qqc)
    cqqc = cos(qqc)
    
    # k is Snyder's constant, taken as product with r2:
    r2k = r2 * sqrt(2/(1+spc*sp+cpc*cp*cqqc));
 
    return (r2k*cp*sqqc*c5, r2k*(cpc*sp-spc*cp*cqqc)/c5)
```

Can anyone point me in the right direction what the best way is to implement this for the C/Python geostack? Would it be possible to add this to PROJ, so that many downstream projects can benefit from it.

My main aim is to be able to use this projection for drawing choropleth maps.

**Comment by WeiaR** [comment]
Maybe its easier to just use one formula for x and one for y? They look awkward but work:
u and v are geographical width and length in radians. Then:
x=1.6188566*sqrt(2/(1+0.530815*sin(asin(0.7264*sin(u)+0.2587011))+0.8474875* cos(asin(0.7264*sin(u)+0.2587011))*cos(0.5253*v-0.1010612291)))* cos(asin(0.7264*sin(u)+0.2587011))*sin(0.5253*v-0.1010612291)*0.9701

y=1.6188566*sqrt(2/(1+0.530815*sin(asin(0.7264*sin(u)+0.2587011))+0.8474875* cos(asin(0.7264*sin(u)+0.2587011))*cos(0.5253*v-0.1010612291)))*(0.8474875* sin(asin(0.7264*sin(u)+0.2587011))-0.530815* cos(asin(0.7264*sin(u)+0.2587011))*cos(0.5253*v-0.1010612291))/0.9701

**Comment by rouault** [comment]
If you want to integrate it, have a look at the changes that were required to add another projection method, like https://github.com/OSGeo/PROJ/commit/4559a3f702f3f2e2d796d46458a61f38595d6e08  (you wouldn't need to do changes in coordinateoperation_constants.hpp and proj_constants.h, as they are related to binding the projection method to a EPSG one, but this isn't the case here)

**Comment by mbloch** [comment]
@WeiaR   Cupola is a lovely projection! I especially like your your variation with separate polar maps. I've added the above code to my JavaScript port of PROJ.4, which uses the same open source license as PROJ. Please let me know if you require any changes. https://github.com/mbloch/mapshaper-proj/blob/master/src/projections/cupola.js

**Comment by WeiaR** [comment]
Hi Matthew, Thanks! 
Can you explain what you have done, the code looks OK to me. I am just a few hours on github, so I do not understand what to do with it ;-) Is it a library, can everyone use it??
The version with separate polar maps has different code of course.

**Comment by mbloch** [comment]
Weia,
Yes, I've added your projection to a JavaScript projections library that anyone can use. The library is mostly used by the open source "mapshaper" tool ([link](https://github.com/mbloch/mapshaper)). To see your projection in mapshaper, you can click [this link](https://mapshaper.org/?q&files=https://int.nyt.com/newsgraphics/vmap/examples/world_land_polygon.json), then click the "Console" button and run the command `proj cupola`.

**Comment by WeiaR** [comment]
Hi Matthew, Nice to see it programmed by someone else! It looks a bit 'naked' without a graticule. For the article in IJC I made a coastal line set myself, to prevent cluttering small islands etcetera. Yours can be enlarged a bit more than mine, although it has issues on the South polar line. Thanks!

**Comment by mbloch** [comment]
I'm happy to continue discussing how mapshaper can best implement the Cupola projection. Maybe we should move this discussion over to the mapshaper's issue tracker (link: https://github.com/mbloch/mapshaper/issues/479)
