### ISSUE TITLE
Be ready for U+00B0 DEGREE SIGN "°" on input

### ISSUE THREAD

**Issue by jidanni** [OSGeo/PROJ#2712]
Sooner or later, please recognize "°" on input,
```
$ cs2cs +proj=latlon +to +proj=latlon <<< "22°56'52.2\"N 121°14'09.3\"E"
22dE    0dN 0.000°56'52.2"N 121°14'09.3"E
$ echo  "22°56'52.2\"N 121°14'09.3\"E" | sed s/°/d/g | cs2cs -f %.6f +proj=latlon +to +proj=latlon
22.947833       121.235917 0.000000

**Comment by direvus** [comment]
If we only care about UTF-8, that's a pretty simple change, we could just treat the byte sequence `\xc2\xb0` as equivalent to `d` for the purposes of parsing a DMS string.  If that's all we want to worry about then I'd be happy to raise a PR for it.

If we want to respect other encodings as well, then it's more of a heavy lift, and more than I'd be comfortable biting off at this stage.
