### ISSUE TITLE
Be ready for U+00B0 DEGREE SIGN "°" on output

### ISSUE THREAD

**Issue by jidanni** [OSGeo/PROJ#2713]
Just like #2712, some folks would like "°" on output,
without needing `sed s/d/°/g`.

And indeed, you don't say d m s, except for the d. So now that Unicode
has been invented, even the d can, optionally, go.

**Comment by kbevers** [comment]
This has been tried in the [past](https://github.com/OSGeo/PROJ/issues/1828) without much success. There is no point in doing this before Windows gets it's act together. Also, breaking an output format that has existed for ~40 years is maybe not the best idea.

**Comment by jidanni** [comment]
I'm just saying "show that proj is aware that there are newer ways to write "d" these days, perhaps by acknowledgement of that fact on the man page, and maybe even offering a way to let the user avoid sed(1)." No, no need to change defaults.
