### ISSUE TITLE
creating a projection by WKT that contain 'metre' instead of 'meter' ,is failed

### ISSUE THREAD

**Issue by aharondavid** [OSGeo/PROJ#2718]
# Your code here

WKT = "
COMPD_CS["ENU (34.7820335833334:31.8878662083333) + EGM96 geoid height",PROJCS["ENU (34.7820335833334:31.8878662083333)",GEOGCS["GCS_WGS_1984",DATUM["D_unknown",SPHEROID["WGS84",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]],PROJECTION["Orthographic"],PARAMETER["Latitude_Of_Center",31.8878662083333],PARAMETER["Longitude_Of_Center",34.7820335833334],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["Meter",1]],VERT_CS["EGM96 geoid height",VERT_DATUM["EGM96 geoid",2005,EXTENSION["PROJ4_GRIDS","egm96_15.gtx"],AUTHORITY["EPSG","5171"]],UNIT["**metre**",1,AUTHORITY["EPSG","9001"]],AXIS["Up",UP],AUTHORITY["EPSG","5773"]]]
";

OGRSpatialReference SR;
OGRErr error = SR.importFromWkt(WKT);
#### Problem description

creating  OGRSpatialReference by WKT that contain 'metre' instead of 'meter' is failed.
the above WKT is one sample

#### Expected Output
Succeeded result like GDAL < 3

#### Environment Information
 - PROJ version 7.1
 - GDAL-3.1.2
 - Windows 10

**Comment by rouault** [comment]
The above snippet is incorrect due to the lack of escaping of the " character.

From PROJ command line, things work fine with PROJ 8.0.1 and 7.2.1:
```
$ projinfo 'COMPD_CS["ENU (34.7820335833334:31.8878662083333) + EGM96 geoid height",PROJCS["ENU (34.7820335833334:31.8878662083333)",GEOGCS["GCS_WGS_1984",DATUM["D_unknown",SPHEROID["WGS84",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]],PROJECTION["Orthographic"],PARAMETER["Latitude_Of_Center",31.8878662083333],PARAMETER["Longitude_Of_Center",34.7820335833334],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["Meter",1]],VERT_CS["EGM96 geoid height",VERT_DATUM["EGM96 geoid",2005,EXTENSION["PROJ4_GRIDS","egm96_15.gtx"],AUTHORITY["EPSG","5171"]],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Up",UP],AUTHORITY["EPSG","5773"]]]' -o PROJ -q
+proj=ortho +f=0 +lat_0=31.8878662083333 +lon_0=34.7820335833334 +x_0=0 +y_0=0 +ellps=WGS84 +units=m +geoidgrids=egm96_15.gtx +vunits=m +no_defs +type=crs
```
