### ISSUE TITLE
Replace nlohmann_json with a faster Json parser.

### ISSUE THREAD

**Issue by himsve** [OSGeo/PROJ#2727]
The JSON-parser process in TINSHIFT transformation may take several seconds for huge json tinshift models. nlohmann_json is not the fastest open source library.

nlohmann_json might be replace with for example Simdsjon, one of the fastest open source json parsers:

- https://simdjson.org
- https://github.com/simdjson/simdjson

I have tested and compared nlohmann_json and Simdjson for the TINSHIFT-application. In my case the json parser in  Simdsjon was **~12.5x faster** than nlohmann_json.

**Comment by rouault** [comment]
Is the JSON parsing the main bottleneck that shows up when using such huge json tinshift models ? How large is your JSON file ?

**Comment by himsve** [comment]
Yes, absolute. My file is 2.4 MB and it took ~8 second to parse the json file in runtime. The same parsing method (TINShiftFile::parse()) with Simdjson took ~0.63 seconds.

**Comment by rouault** [comment]
> it took ~8 second to parse the json file in runtime

with an optimized build ?

**Comment by rouault** [comment]
I've just tested with a 6.7 MB file with 71429 vertices and 115859 triangles and ``time sh -c 'echo "27.209636004 70.499319535 0" | src/cct +proj=tinshift +file=/tmp/triangulation_kkj_geog.json'`` runs in 487 ms here with nlohmann_json with a -O2 build

**Comment by himsve** [comment]
OK. I did new optimized builds in Vcpkg and have better results now:

- niemann: 0.125 s
- simdjson: 0.023 s

**Comment by rouault** [comment]
cf https://github.com/OSGeo/PROJ/pull/4603 "tinshift: support TIN GeoPackage files"
