### ISSUE TITLE
ETRS89 to Chart datum transformation in Norway

### ISSUE THREAD

**Issue by himsve** [OSGeo/PROJ#2739]
## ETRS89 to Chart datum transformation in Norway

The Norwegian Mapping Authority has defined the vertical transformation between ETRS89 and chart datum with vertical correction grid (GeoTiff). The transformation involves to steps:

1) Vertical shifts from correction grid (ETRS89 ell. height>Chart datum height)
2) Height Depth Reversal of Chart datum height. (Chart datum height>Chart datum depth)

The Norwegian chart datum has already EPSG code 9672 (https://epsg.org/home.html)  

The transformation is prototyped in branches:
[CD Norway branch - Proj](https://github.com/himsve/PROJ/tree/typo_cdnorway)
[CD Norway branch - Proj-data](https://github.com/himsve/PROJ-data/tree/type_cdnorway)

### Figure vertical datums, example

![CDNORWAY](https://user-images.githubusercontent.com/56073535/120648512-02fc2580-c47c-11eb-9a1f-0f73f7e6255e.png)

### Coverage vertical correction grid

![CDNORWAY_coverage](https://user-images.githubusercontent.com/56073535/120648597-1b6c4000-c47c-11eb-80fc-1c1e0fa73b54.jpeg)

### Discussions

- So far, neither the national transformation from ETRS89 ell. to Chart datum, or intermediate vertical datum are defined in the EPSG registry. Do we need the register all datums and transformation steps?
- The vertical correction grid does not cover the entire extent of Chart datum (EPSG:4615). Do the vertical correction grid and the vertical datum need to cover the same extent?   
- What other changes do we have to do at the above branches before pull requests?

**Comment by rouault** [comment]
>     * So far, neither the national transformation from ETRS89 ell. to Chart datum, or intermediate vertical datum are defined in the EPSG registry. Do we need the register all datums and transformation steps?

Yes, please. That makes their use and maintenance by PROJ much easier

> The vertical correction grid does not cover the entire extent of Chart datum (EPSG:4615). Do the vertical correction grid and the vertical datum need to cover the same extent?

Not necessarily. Each transformation/grid has its own extent, which can be a subset of the source & target CRS

> What other changes do we have to do at the above branches before pull requests?

For PROJ-data, probably none. For PROJ, once the CRS & transformations are registered in EPSG, all changes but the ones in grid_alternatives.sql are no longer needed once we've imported the new version of the EPSG database
