### ISSUE TITLE
Describing CRS using EPSG codes doesn't work

### ISSUE THREAD

**Issue by jvkvijay** [OSGeo/PROJ#2742]
Hello All, 

I am new to PROJ.  I am trying out the code in the Proj quick start guide.  (https://proj.org/development/quickstart.html). If I describe a CRS as a proj string, things work fine. But if I describe a CRS as an EPSG code (eg: EPSG:4326), things don't work. For example, the code 

P = proj_create_crs_to_crs (C,
                            "EPSG:4326",
                            "+proj=utm +zone=32 +datum=WGS84", /* or EPSG:32632 */
                            NULL);

in the quick start guide doesn't work. I get a NULL back.

I installed proj using VCPKG. (proj4) . The version I am using seems to be 7.2.1

What am I doing wrong ?  Any help would be appreciated. 

thank you
Vijay

**Comment by rouault** [comment]
It is likely that PROJ doesn't find the ``proj.db`` file. Set the PROJ_LIB environment variable to point to the directory where this file is installed

**Comment by jvkvijay** [comment]
Hi Rouault,

Setting the PROJ_LIB environment variable solved the issue. 

Many thanks
Vijay
