### ISSUE TITLE
No proj_api.h in src/ folder

### ISSUE THREAD

**Issue by mbelotti99** [OSGeo/PROJ#2746]
Hi,

I'm sorry if this is not the correct forum to post this. Please let me know if this is inappropriate and I'll delete this. 

I was trying to install Cartopy on a Mojave MacOS. In order to do that, I tried all three approaches to installing proj: Homebrew, Macports and manual compilation. All three approaches did not create a file called `proj_api.h`, which Cartopy seems to look for during its installation. 

I looked at the current master branch of the proj project, and there is no `proj_api.h` file in it, even though it seems to be there in older releases. Has this file been removed from newer versions of proj?

**Comment by rouault** [comment]
>  Has this file been removed from newer versions of proj?

yes, was removed in PROJ 8 as announced many years ago :  https://proj.org/development/index.html .  You're probably using a too old version of cartopy. It looks like 0.17 should support newer PROJ versions: https://scitools.org.uk/cartopy/docs/latest/whats_new.html#what-s-new-in-cartopy-0-17 . Anyway, this it to see with the cartopy team

**Comment by mbelotti99** [comment]
Thank you for your answer! Sorry for the redundancy there, I had not thought to look at the development page.  

I'll look into the Cartopy issues to see what's up. =]

**Comment by jmckenna** [comment]
@mbelotti99 here is a page of adoption status for that, which does also list the Cartopy status: https://github.com/OSGeo/PROJ/wiki/proj.h-adoption-status  @mbelotti99 maybe when you contact Cartopy you can ask them to make sure that their entry on that page is uptodate.

**Comment by snowman2** [comment]
https://github.com/SciTools/cartopy/issues/1140

**Comment by mbelotti99** [comment]
Hello everyone! 

Just in case someone runs into this in the future, I'm posting this here (again, if this is not the appropriate place to do this, I can remove my post).

I asked the Cartopy team, and they confirmed that Cartopy cannot be compiled on PROJ >= 8. I manually compiled release 7.2.1 and it worked perfectly. The manual compilation was totally seamless. Not hassle at all. 

Here is the link to my question on Cartopy's github: https://github.com/SciTools/cartopy/issues/1802

@jmckenna It seams like this page is updated, right? Cartopy apparently still depends on proj_api.h. Am I interpreting it wrong? I can send it to them either way, if you think it helps! haha

**Comment by jmckenna** [comment]
@mbelotti99 repeating my words exactly: "@mbelotti99 maybe when you contact Cartopy you can ask them to make sure that their entry on that page is uptodate"

**Comment by jmckenna** [comment]
@mbelotti99 I never checked the status, but if you did check with them excellent!  I was only asking for them to verify.   Cheers and have a nice weekend!
