### ISSUE TITLE
proj 8.0.0 installation error database is locked

### ISSUE THREAD

**Issue by Gopal-Murali** [OSGeo/PROJ#2748]
Hello,

I am trying to install PROJ 8.0.0 on a server that runs on Ubuntu 18.04.5 LTS.

I have already compiled and installed sqlite3 locally and added it to the PATH/LD_LIBRARY_PATH/PKG_CONFIG_PATH. However, when I tried to install proj-8.0.0 (using the ./configure and install commands) following instructions [here](https://proj.org/install.html#compilation-and-installation-from-source-code), I am getting the following error. 

```c
Make proj.db
rm -f proj.db
Error: near line 7: database is locked
Error: near line 12: database is locked
Error: near line 23: database is locked
Error: near line 31: database is locked
Error: near line 33: database is locked
Error: near line 52: database is locked
Error: near line 59: database is locked
Error: near line 73: database is locked
Error: near line 81: database is locked
Error: near line 100: database is locked
Error: near line 102: database is locked

```
#### Environment Information
 - PROJ version: 8.0.0

#### Installation method
 -from source

**Comment by rouault** [comment]
> I have already compiled and installed sqlite3 locally

why don't you use the sqlite3 version of the distribution ?

**Comment by Gopal-Murali** [comment]
Sorry for the missing details. I have installed sqlite3 from [here](https://www.sqlite.org/download.html) (amalgamation) because I get the below error if I don't do this. 

I am trying to install PROJ on a university cluster and don't have root access / don't know the location of sqlite3. 

```c
checking for pthread_mutexattr_settype in -lpthread... yes
checking whether PTHREAD_MUTEX_RECURSIVE is declared... yes
enabled, pthread
checking for SQLITE3... configure: error: Package requirements (sqlite3 >= 3.11) were not met:

No package 'sqlite3' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables SQLITE3_CFLAGS
and SQLITE3_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

```

**Comment by rouault** [comment]
You should just use "apt install sqlite3 libsqlite3-dev" to get both the sqlite3 binary and dev package

**Comment by rouault** [comment]
Ah sorry, missed your comment about having not root access.

**Comment by Gopal-Murali** [comment]
> You should just use "apt install sqlite3 libsqlite3-dev" to get both the sqlite3 binary and dev package

Sorry. As I mentioned before, I don't have root access and I get the below error when I try "apt install sqlite3 libsqlite3-dev"

```c
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?

```

**Comment by rouault** [comment]
For what is worth, the following works:
```
docker pull ubuntu:18.04
docker run --rm -it ubuntu:18.04
# inside Docker
apt update
apt install g++ make wget libtiff-dev libcurl4-gnutls-dev
wget https://sqlite.org/2021/sqlite-autoconf-3350500.tar.gz
tar xvzf sqlite-autoconf-3350500.tar.gz
cd sqlite-autoconf-3350500
./configure --prefix=/tmp/install
make -j$(nproc) && make install
cd ..
wget http://download.osgeo.org/proj/proj-8.0.0.tar.gz
tar xvzf proj-8.0.0.tar.gz
cd proj-8.0.0
PATH=/tmp/install/bin:$PATH PKG_CONFIG_PATH=/tmp/install/lib/pkgconfig ./configure
PATH=/tmp/install/bin:$PATH make -j$(nproc)
```

**Comment by Gopal-Murali** [comment]
Thanks for the help. I did manage to install it.

**Comment by rouault** [comment]
Did you identify what caused the "database locked" error ?
