### ISSUE TITLE
Fedora RPM build via cmake has no static libraries

### ISSUE THREAD

**Issue by rsbivand** [OSGeo/PROJ#2753]
Dwnstream problems in R package **sf** https://github.com/r-spatial/sf/issues/1696 (at foot) and a bugzilla issue for RPM packaging https://bugzilla.redhat.com/show_bug.cgi?id=1958191 indicate that cmake builds of PROJ (possibly from 7.2.0) do not build static libraries. This has led to slightly spurious `proj.pc` files being generated, and failures for R package **sf** to install from source when the static library was absent (it was checked in configure). I cannot see a direct link to https://github.com/OSGeo/PROJ/issues/2688, and myself know nothing of `cmake` internals, so I cannot try to fix this. Feedback downstream to the RPM issue and the R **sf** issue would be valued, especially because if I understand correctly, the RPM community will need a fresh 7.2.* release when the cmake problem is resolved and the static library generated correctly because a fixed 8.0.* will not help those stuck on `proj_api.h`. Below my output from a cmake build from 8.0.1 source build:
```
[rsb@localhost build]$ pwd
/home/rsb/topics/proj/proj-8.0.1/build
[rsb@localhost build]$ ls bin
cct       gie_self_tests        proj_errno_string_test  test_misc
cs2cs     pj_phi2_test          projinfo                test_network
geod      proj                  projsync                test_tinshift
geodtest  proj_angular_io_test  proj_test_cpp_api
gie       proj_context_test     test_defmodel
[rsb@localhost build]$ ls lib
libgtest.so  libproj.so  libproj.so.22  libproj.so.22.1.0
[rsb@localhost build]$ ls include
CMakeFiles  cmake_install.cmake  CTestTestfile.cmake  Makefile  proj
[rsb@localhost build]$ 
```

**Comment by rsbivand** [comment]
I understand from https://github.com/r-spatial/sf/issues/1696#issuecomment-866858310 that `cmake` unlike `autotools` does not build dynamic and static libraries in one run, and that the behaviour from the packager switching to `cmake` is expected, but not by downstream software. If RPM packagers have changed policy to avoid shipping both dynamic and static, downstream will have to work around that.

**Comment by mwtoews** [comment]
@rsbivand you are correct about the static/dynamic build behavior difference, see https://github.com/OSGeo/PROJ/issues/2546#issuecomment-785389755 and discussion further down in the thread.

**Comment by rsbivand** [comment]
@mwtoews thanks for the link - I'll add it to the R **sf** package issue.
