### ISSUE TITLE
AttributeError: partially initialized module 'pyproj' has no attribute 'network' (most likely due to a circular import)

### ISSUE THREAD

**Issue by Gujsingh** [OSGeo/PROJ#2754]
Hi I am trying to download geopandas and am getting the following error
AttributeError: partially initialized module 'pyproj' has no attribute 'network' (most likely due to a circular import)
HERE IS THE FULL TRACE BACK  on Jupyter
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-33-c0f9d033d4f7> in <module>
      2 import os
      3 from shapely import geometry
----> 4 from geopandas import GeoDataFrame
      5 import plotly.express as px
      6 import plotly.graph_objects as go

~/miniconda3/lib/python3.9/site-packages/geopandas/__init__.py in <module>
----> 1 from geopandas._config import options  # noqa
      2 
      3 from geopandas.geoseries import GeoSeries  # noqa
      4 from geopandas.geodataframe import GeoDataFrame  # noqa
      5 from geopandas.array import points_from_xy  # noqa

~/miniconda3/lib/python3.9/site-packages/geopandas/_config.py in <module>
    124 use_pygeos = Option(
    125     key="use_pygeos",
--> 126     default_value=_default_use_pygeos(),
    127     doc=(
    128         "Whether to use PyGEOS to speed up spatial operations. The default is True "

~/miniconda3/lib/python3.9/site-packages/geopandas/_config.py in _default_use_pygeos()
    110 
    111 def _default_use_pygeos():
--> 112     import geopandas._compat as compat
    113 
    114     return compat.USE_PYGEOS

~/miniconda3/lib/python3.9/site-packages/geopandas/_compat.py in <module>
      6 
      7 import pandas as pd
----> 8 import pyproj
      9 import shapely
     10 import shapely.geos

~/miniconda3/lib/python3.9/site-packages/pyproj/__init__.py in <module>
     78     warnings.warn(str(err))
     79 
---> 80 pyproj.network.set_ca_bundle_path()

AttributeError: partially initialized module 'pyproj' has no attribute 'network' (most likely due to a circular import)

Here is what I import:
import argparse
import os
from shapely import geometry
from geopandas import GeoDataFrame
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
import pandas as pd
from ipdb import set_trace
from math import sin, cos, sqrt, atan2, radians
from pyod.models.lscp import LSCP
from pyod.models.lof import LOF
from pyod.utils.utility import standardizer
from pyod.utils.data import generate_data
from pyod.utils.data import evaluate_print
from pyod.utils.example import visualize
from scipy.stats import zscore
from sklearn.neighbors import BallTree, KDTree
from sklearn.cluster import DBSCAN
from sklearn.ensemble import IsolationForest
from sklearn.neighbors import LocalOutlierFactor

Here is what I install:
%conda install numpy
%conda install pandas
%conda install -c plotly plotly
%conda install -c conda-forge pyarrow
%conda install scikit-learn
%pip install ipdb
%pip install --upgrade certifi
%pip install geopandas
%conda install -c conda-forge pyproj
%pip install Shapely

**Comment by rouault** [comment]
the issue should be reported to geopandas or pyproj projects. This is not a PROJ issue by itself.
