### ISSUE TITLE
expose PROJ_USER_WRITABLE_DIRECTORY env variable

### ISSUE THREAD

**Issue by jmckenna** [OSGeo/PROJ#2755]
- default location of grids and cache.db on Windows (when using the `projsync` utility) is "C:/Users/xxxxx/AppData/Local/proj"
- the env variable `PROJ_USER_WRITABLE_DIRECTORY` can be used to set a more friendly path, but is currently for testing purposes only
- this feature request is to expose/publish the `PROJ_USER_WRITABLE_DIRECTORY` env variable, in the next release of PROJ

(I volunteer to test and document this)

**Comment by hobu** [comment]
> default location of grids and cache.db on Windows (when using the projsync utility) is "C:/Users/xxxxx/AppData/Local/proj"

Is this a bad default? I thought AppData was supposed to be the user-space data directory, which is exactly what we're doing here.

**Comment by jmckenna** [comment]
Windows users do not access the ""C:/Users/xxxxx/AppData/Local/" path (in fact by default it is invisible, those folders).

**Comment by kbevers** [comment]
> Windows users do not access the ""C:/Users/xxxxx/AppData/Local/" path (in fact by default it is invisible, those folders).

Isn't that the whole point? Why would a casual PROJ/GDAL/QGIS user need to access the grid files directly?

**Comment by jmckenna** [comment]
I anticipated this pushback.  It's unfortunate.  Closing.

**Comment by kbevers** [comment]
> I anticipated this pushback. It's unfortunate. Closing.

This isn't pushback. We should be able to get clarified why this is a useful change. If there's a good argument for it we should change it.

**Comment by hobu** [comment]
> I anticipated this pushback.

We're only asking if what's there now is a good default on windows. I can understand why you would want to change it, although I would hope it would be a rare thing to change.
