### ISSUE TITLE
Warn proj_as_proj_string for CRS can lose information

### ISSUE THREAD

**Issue by snowman2** [OSGeo/PROJ#2758]
https://github.com/OSGeo/PROJ/blob/d41c10c9e1e787a521a3841605a2e6024649eb3f/src/proj.h#L1170

https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems

Since PROJ strings aren't great for representing CRS, thoughts about deprecating support to export to that format for CRS?

**Comment by busstoptaktik** [comment]
I'm all for this - PROJ strings are for describing transformations, not for defining CRS.

Actually, the notion of "a definition of a CRS" is somewhat of a misnomer: Fundamentally, a CRS is just a label. It gains a lot of practical usefulness through its "relations" to other CRS, expressed as transformations - for which PROJ strings are probably the most human readable tool.

**Comment by rouault** [comment]
What do you mean about deprecating exactly ? I'd expect this functionality to remain forever, despite its limitations. There are a number of geospatial formats whose CRS storage is PROJ.4 CRS strings.

**Comment by snowman2** [comment]
> What do you mean about deprecating exactly ? 

- Add documentation that it is deprecated and won't get any more features/fixes and reference that it is a lossy format for CRS.
- Add warning messages when using it that it is deprecated and is not a good format for storing CRS information.

> There are a number of geospatial formats whose CRS storage is PROJ.4 CRS strings.

Which ones? How feasible for them to update to use WKT?

That is a really unfortunate situation for a geospatial format to use PROJ strings. As a user, I would want to know which ones do that and get annoying warning messages so I can avoid them if possible.

**Comment by rouault** [comment]
> Which ones?

From a cursory grep in GDAL source:
- The "ODIM" products using HDF5:  https://www.eumetnet.eu/wp-content/uploads/2019/05/OPERA-ODIM_H5-v2.1.pdf
- the RRASTER format: https://gdal.org/drivers/raster/rraster.html
- the WASP format: https://gdal.org/drivers/vector/wasp.html
- the WALK format: https://gdal.org/drivers/vector/walk.html
- the GMT ASCII vector format: https://gdal.org/drivers/vector/gmt.html
- a few SQL based databases have a spatial_ref_sys table with a column that can contain a proj4 string: PostGIS, Spatialite  . Often as a complement to WKT. The PROJ.4 string might be useful to express very custom things that can't be expressed in WKT

**Comment by snowman2** [comment]
> The PROJ.4 string might be useful to express very custom things that can't be expressed in WKT

There are CRS represented as PROJ strings that can't be represented as a WKT string :thinking:.  I guess that is reason enough to not deprecate.

**Comment by rouault** [comment]
> There are CRS represented as PROJ strings that can't be represented as a WKT string

Mostly odd things where you mess with +over, +lon_wrap= etc.

**Comment by busstoptaktik** [comment]
> What do you mean about deprecating exactly ?

I mean strongly suggesting not using this for defining CRS in any new work; not removing the feature.

But as per my previous comment, the entire notion of "defining" a CRS is dubious: Transformations between CRS are much more important than CRS definitions, so proj strings per se remain extremely useful for (informally) defining transformations.

**Comment by snowman2** [comment]
@rouault I updated the title to something I think would be a useful change. Thoughts?

**Comment by rouault** [comment]
> Thoughts?

as a warning in the documentation ?
I'd be -0 regarding a runtime warning
