### ISSUE TITLE
CMake targets broken in 8.1.0 when using external nlohmann_json

### ISSUE THREAD

**Issue by dirkvdb** [OSGeo/PROJ#2762]
When cmake configure finds an external nlohmann_json it will use that.

In that case a nlohmann_json::nlohmann_json dependency is set on the cmake targets. But no `find_dependency(nlohmann_json REQUIRED)` is added to the proj-config.cmake.

Adding the proj target as a dependency now causes a cmake error:
```
Target "yourtarget" links to target "nlohmann_json::nlohmann_json" but the target was not found
```

#### Environment Information
 - PROJ version 8.1.0

#### Installation method
 - from source

**Comment by rouault** [comment]
@mwtoews opinions / guidance welcome how to fix that. I'd say that  external nlohmann_json should not be exported by PROJ cmake files, as it is only an implementation detail that users of the PROJ API don't have direct access to

**Comment by mwtoews** [comment]
@dirkvdb could you provide a few more details, such as the command or options you used to configure cmake? An os and compiler would be handy too. I'm unable to trigger this error, so any guidance will help me find a resolution.

**Comment by dirkvdb** [comment]
This happens when configuring proj with -DNLOHMANN_JSON_ORIGIN="external" on any platform.
The proj build will work fine, but external projects that do a
```
find_package(PROJ CONFIG REQUIRED)
target_link_libraries(mytarget PRIVATE PROJ::proj)
```
will get the error.

I made a pull request #2763 with a possible fix.

**Comment by mwtoews** [comment]
I'm still unable to trigger this error. Here is my method, first starting up docker in the git repo:
```
docker run -t -i --rm -v `pwd`:/io ubuntu:20.04 bash
```
then within the VM:
```
apt update
apt install cmake nlohmann-json3-dev sqlite3 libsqlite3-dev libtiff-dev libcurl4-openssl-dev g++
cd /io/
mkdir build && cd build
cmake ..
make -j7
make install
apt remove nlohmann-json3-dev
cd ../test
./postinstall/test_cmake.sh /usr/local
```
and I've modified line 7 on `test/postinstall/testappprojinfo/CMakeLists.txt` to try and break it.

Ideally dependant projects won't need `nlohmann/json`, as it's a header-only library only required to build PROJ.

**Comment by dirkvdb** [comment]
In the testappprojinfo project you link against proj using the `${${USE_PROJ_NAME}_LIBRARIES}` define.
Since the problem is in the cmake target, this will work.
I think it will break if you modify the test project to link against the cmake proj target: `PROJ::proj`

The cmake targets system is superior to using the _LIBRARIES and _INCLUDES variables because it contains more information than just include paths and libraries (linker flags, transitive dependencies, ...) It does require the targets to be found in the cmake config file even when it is a private dependency. This is crucial for static builds that require the transitive dependencies for linking.

**Comment by mwtoews** [comment]
Ah right, it's a static build. I now see the error with `-DBUILD_SHARED_LIBS=OFF`. Thanks for the PR, I'll investigate further. I've been meaning to get the postinstall suite to also check static builds, so this seems to be a good time to get that going.
