### ISSUE TITLE
Wrong horizontal shift when reprojecting from GDA2020 zone 55 +ahd to gda94 zone 55+ahd or to epsg:4326

### ISSUE THREAD

**Issue by yanivday** [OSGeo/PROJ#2778]
## Expected behavior and actual behavior.

Hello, 

With Gdal 3.1.2 proj v8.0 library:
Reprojecting from GDA2020 zone 55 +ahd to gda94 zone 55+ahd, the horizontal movement is incorrect (see test no.2 in the attached document)
Projecting from GDA 2020 + ahd height to WGS84 (or wgs84+egm96)> back to GDA +ahd, you get an increasing shift (an additional shift for every interaction back and forth) (test no.3 in the attached document)

Thank you very much for your help!
Kind regards,
Yaniv

## Steps to reproduce the problem.

See the attached .prj files and the Gdaltransform_for Gdal.docx for more information and command lines.
You have to copy AUSGeoid09_V1.01.gtx, AUSGeoid2020_20180201.gtx and egm96_15.gtx to your ./proj folder.

## Operating system

Windows 10 64bit

## GDAL version and provenance

using Gdal 3.1.2 proj v8.0 library
[gdaltransform.zip](https://github.com/OSGeo/gdal/files/6805488/gdaltransform.zip)

**Comment by rouault** [comment]
Preliminary analysis with playing with projinfo on PROJ master:

```
$ src/projinfo -s @GDA94_MGA_zone55_ahd_height.prj -t @GDA2020_MGA_zone55_ahd_height.prj --spatial-test intersects -o PROJ --grid-check none
Candidate operations found: 4
-------------------------------------
Operation No. 1:

unknown id, Inverse of UTM zone 55S + AHD height to WGS84 ellipsoidal height + Inverse of AHD height to WGS84 ellipsoidal height + GDA94 to GDA2020 (1) + UTM zone 55S, unknown accuracy, Australia including Lord Howe Island, Macquarie Islands, Ashmore and Cartier Islands, Christmas Island, Cocos (Keeling) Islands, Norfolk Island. All onshore and offshore., at least one grid missing

PROJ string:
+proj=pipeline
  +step +inv +proj=utm +zone=55 +south +ellps=GRS80
  +step +proj=vgridshift +grids=AUSGeoid09_V1.01.gtx +multiplier=1
  +step +inv +proj=vgridshift +grids=AUSGeoid2020_20180201.gtx +multiplier=1
  +step +proj=push +v_3
  +step +proj=cart +ellps=GRS80
  +step +proj=helmert +x=0.06155 +y=-0.01087 +z=-0.04019 +rx=-0.0394924
        +ry=-0.0327221 +rz=-0.0328979 +s=-0.009994 +convention=coordinate_frame
  +step +inv +proj=cart +ellps=GRS80
  +step +proj=pop +v_3
  +step +proj=utm +zone=55 +south +ellps=GRS80

-------------------------------------
Operation No. 2:

unknown id, Inverse of UTM zone 55S + AHD height to WGS84 ellipsoidal height + Inverse of AHD height to WGS84 ellipsoidal height + GDA94 to GDA2020 (3) + UTM zone 55S, unknown accuracy, Australia - Australian Capital Territory; New South Wales; Northern Territory; Queensland; South Australia; Tasmania; Western Australia; Victoria., at least one grid missing

PROJ string:
+proj=pipeline
  +step +inv +proj=utm +zone=55 +south +ellps=GRS80
  +step +proj=vgridshift +grids=AUSGeoid09_V1.01.gtx +multiplier=1
  +step +inv +proj=vgridshift +grids=AUSGeoid2020_20180201.gtx +multiplier=1
  +step +proj=hgridshift +grids=au_icsm_GDA94_GDA2020_conformal.tif
  +step +proj=utm +zone=55 +south +ellps=GRS80

-------------------------------------
Operation No. 3:

unknown id, Inverse of UTM zone 55S + AHD height to WGS84 ellipsoidal height + Inverse of AHD height to WGS84 ellipsoidal height + GDA94 to GDA2020 (2) + UTM zone 55S, unknown accuracy, Australia - Australian Capital Territory; New South Wales; Northern Territory; Queensland; South Australia; Tasmania; Western Australia; Victoria., at least one grid missing

PROJ string:
+proj=pipeline
  +step +inv +proj=utm +zone=55 +south +ellps=GRS80
  +step +proj=vgridshift +grids=AUSGeoid09_V1.01.gtx +multiplier=1
  +step +inv +proj=vgridshift +grids=AUSGeoid2020_20180201.gtx +multiplier=1
  +step +proj=hgridshift
        +grids=au_icsm_GDA94_GDA2020_conformal_and_distortion.tif
  +step +proj=utm +zone=55 +south +ellps=GRS80

-------------------------------------
Operation No. 4:

unknown id, Inverse of UTM zone 55S + AHD height to WGS84 ellipsoidal height + Inverse of AHD height to WGS84 ellipsoidal height + Ballpark geographic offset from GDA94 to GDA2020 + UTM zone 55S, unknown accuracy, World, has ballpark transformation, at least one grid missing

PROJ string:
+proj=pipeline
  +step +inv +proj=utm +zone=55 +south +ellps=GRS80
  +step +proj=vgridshift +grids=AUSGeoid09_V1.01.gtx +multiplier=1
  +step +inv +proj=vgridshift +grids=AUSGeoid2020_20180201.gtx +multiplier=1
  +step +proj=utm +zone=55 +south +ellps=GRS80

```
and
```
$ src/projinfo -s @GDA2020_MGA_zone55_ahd_height.prj -t @GDA94_MGA_zone55_ahd_height.prj  --spatial-test intersects -o PROJ --grid-check none
Candidate operations found: 4
-------------------------------------
Operation No. 1:

unknown id, Inverse of UTM zone 55S + AHD height to WGS84 ellipsoidal height + Inverse of AHD height to WGS84 ellipsoidal height + GDA2020 to WGS 84 (2) + Inverse of Transformation from GDA94 to WGS84 + UTM zone 55S, unknown accuracy, Australia including Lord Howe Island, Macquarie Islands, Ashmore and Cartier Islands, Christmas Island, Cocos (Keeling) Islands, Norfolk Island. All onshore and offshore., at least one grid missing

PROJ string:
+proj=pipeline
  +step +inv +proj=utm +zone=55 +south +ellps=GRS80
  +step +proj=vgridshift +grids=AUSGeoid2020_20180201.gtx +multiplier=1
  +step +inv +proj=vgridshift +grids=AUSGeoid09_V1.01.gtx +multiplier=1
  +step +proj=utm +zone=55 +south +ellps=GRS80

-------------------------------------
Operation No. 2:

unknown id, Inverse of UTM zone 55S + AHD height to WGS84 ellipsoidal height + Inverse of AHD height to WGS84 ellipsoidal height + Inverse of WGS 84 to GDA2020 (3) + Inverse of Transformation from GDA94 to WGS84 + UTM zone 55S, unknown accuracy, Australia including Lord Howe Island, Macquarie Islands, Ashmore and Cartier Islands, Christmas Island, Cocos (Keeling) Islands, Norfolk Island. All onshore and offshore., at least one grid missing

PROJ string:
+proj=pipeline
  +step +inv +proj=utm +zone=55 +south +ellps=GRS80
  +step +proj=vgridshift +grids=AUSGeoid2020_20180201.gtx +multiplier=1
  +step +inv +proj=vgridshift +grids=AUSGeoid09_V1.01.gtx +multiplier=1
  +step +proj=push +v_3
  +step +proj=cart +ellps=GRS80
  +step +inv +proj=helmert +x=0.06155 +y=-0.01087 +z=-0.04019 +rx=-0.0394924
        +ry=-0.0327221 +rz=-0.0328979 +s=-0.009994 +convention=coordinate_frame
  +step +inv +proj=cart +ellps=GRS80
  +step +proj=pop +v_3
  +step +proj=utm +zone=55 +south +ellps=GRS80

-------------------------------------
Operation No. 3:

unknown id, Inverse of UTM zone 55S + AHD height to WGS84 ellipsoidal height + Inverse of AHD height to WGS84 ellipsoidal height + Inverse of WGS 84 to GDA2020 (4) + Inverse of Transformation from GDA94 to WGS84 + UTM zone 55S, unknown accuracy, Australia - Australian Capital Territory; New South Wales; Northern Territory; Queensland; South Australia; Tasmania; Western Australia; Victoria., at least one grid missing

PROJ string:
+proj=pipeline
  +step +inv +proj=utm +zone=55 +south +ellps=GRS80
  +step +proj=vgridshift +grids=AUSGeoid2020_20180201.gtx +multiplier=1
  +step +inv +proj=vgridshift +grids=AUSGeoid09_V1.01.gtx +multiplier=1
  +step +inv +proj=hgridshift
        +grids=au_icsm_GDA94_GDA2020_conformal_and_distortion.tif
  +step +proj=utm +zone=55 +south +ellps=GRS80

-------------------------------------
Operation No. 4:

unknown id, Inverse of UTM zone 55S + AHD height to WGS84 ellipsoidal height + Inverse of AHD height to WGS84 ellipsoidal height + Ballpark geographic offset from GDA2020 to WGS 84 + Inverse of Transformation from GDA94 to WGS84 + UTM zone 55S, unknown accuracy, World, has ballpark transformation, at least one grid missing

PROJ string:
+proj=pipeline
  +step +inv +proj=utm +zone=55 +south +ellps=GRS80
  +step +proj=vgridshift +grids=AUSGeoid2020_20180201.gtx +multiplier=1
  +step +inv +proj=vgridshift +grids=AUSGeoid09_V1.01.gtx +multiplier=1
  +step +proj=utm +zone=55 +south +ellps=GRS80

```

So for the GDA94+AHD to GDA2020+AHD the pipeline we get is not so bad except the horizontal shift grid should likely be done between the 2 vertical shift grids, and in 3D, so "+proj=pipeline  +step +inv +proj=utm +zone=55 +south +ellps=GRS80  +step +proj=vgridshift +grids=AUSGeoid09_V1.01.gtx +multiplier=1 +step +proj=cart +ellps=GRS80  +step +proj=helmert +x=0.06155 +y=-0.01087 +z=-0.04019 +rx=-0.0394924  +ry=-0.0327221 +rz=-0.0328979 +s=-0.009994 +convention=coordinate_frame  +step +inv +proj=cart +ellps=GRS80 +step +inv +proj=vgridshift +grids=AUSGeoid2020_20180201.gtx +multiplier=1  +step +proj=utm +zone=55 +south +ellps=GRS80"
For the GDA2020+AHD  to GDA94+AHD, the pipeline we get is confused by a horizontal shift between GDA94 and WGS84 and GDA2020 and WGS84, which is due to the fact that the PROJ4_GRID syntax in the .prj has traditionnaly implied to go through WGS84 (not sure why this confusion isn't hit in the GDA94+AHD to GDA2020+AHD direction)
Note to the reporter: you cannot compare the Z value you get with GDAL/PROJ and the one with the online service, as the online service expect ellipsoidal heights as input whereas your WKT are in AHD elevation

**Comment by rouault** [comment]
Part of the confusion also comes from the fact that GDA94_MGA_zone55_ahd_height.prj has an explicit TOWGS84[0,0,0,0,0,0,0] in its horizontal CRS defintion, which makes WGS84 a very tempting pivot datum for PROJ. Removing that node makes PROJ to propose a more reasonable pipeline that includes the correct GDA2020 to GDA94 horizontal shift

**Comment by rouault** [comment]
Upon reflection, I believe PROJ behaves as best as it can given the input WKT. To get the results you'd expect the best is to remove the TOWGS84[0,0,0,0,0,0] node from GDA94_MGA_zone55_ahd_height.prj and the EXTENSION["PROJ4_GRIDS", ...@ from GDA94_MGA_zone55_ahd_height.prj  and GDA2020_MGA_zone55_ahd_height.prj, since they all make PROJ consider WGS 84 as an intermediate datum, but transformations between WGS 84 and GDA94/GDA2020 are ill-defined

**Comment by yanivday** [comment]
Hi Even,

Thanks for the quick answer.
(1)
You are right! Once I removed the TOWGS84 from the GDA94_MGA_zone55_ahd_height.prj I got a good result converting from GDA2020 to GDA94 (the GDA2020_MGA_zone55_ahd_height.prj that I sent you had no TOWGS84, only the GDA94):

With ToWGS84[0,0,0,0,0,0,0] (wrong):
gdaltransform.exe -s_srs "D:\DWork Projects\Ddelete\taylorsds\1267\gdaltransform\GDA2020_MGA_zone55_ahd_height.prj " -t_srs  "D:\DWork Projects\Ddelete\taylorsds\1267\gdaltransform\GDA94_MGA_zone55_ahd_height.prj"
Enter X Y [Z [T]] values separated by space, and press Return.
320700.490773555 5812901.47199924 100.062210225218
320700.490773555 5812901.47199924 100.000000867204

WIthout ToWGS84[0,0,0,0,0,0,0] (correct):
gdaltransform.exe -s_srs "D:\DWork Projects\Ddelete\taylorsds\1267\gdaltransform\GDA2020_MGA_zone55_ahd_height.prj " -t_srs  "D:\DWork Projects\Ddelete\taylorsds\1267\gdaltransform\GDA94_MGA_zone55_ahd_height.prj"
Enter X Y [Z [T]] values separated by space, and press Return.
320700.490773555 5812901.47199924 100.062210225218
320699.99999977 5812900.00000007 100.000000867204

(2)
I found that when reprojecting from epsg:4326 to GDA 2020 + ahd height you **MUST** use the ToWGS84, otherwise, you get a wrong shift (as said above, the GDA2020_MGA_zone55_ahd_height.prj that I sent you had no TOWGS84)

Without Towgs84[0,0,0,0,0,0,0] (wrong):

gdaltransform.exe -s_srs EPSG:4326 -t_srs "D:\DWork Projects\Ddelete\taylorsds\1267\gdaltransform\GDA2020_MGA_zone55_ahd_height.prj"
Enter X Y [Z [T]] values separated by space, and press Return.
144.963046619994 -37.8137045108536 104.748687983519
320700.490775746 5812901.47189781 100.000000000001

With towgs84[0,0,0,0,0,0,0] (correct):
gdaltransform.exe -s_srs EPSG:4326 -t_srs "D:\DWork Projects\Ddelete\taylorsds\1267\gdaltransform\GDA2020_MGA_zone55_ahd_height_towgs.prj"
Enter X Y [Z [T]] values separated by space, and press Return.
144.963046619994 -37.8137045108536 104.748687983519
320699.99999998 5812900 100.000000000001

Conclusions:
Without removing the EXTENSION["PROJ4_GRIDS", ...@:
1. When reprojecting between GDA94 <> GDA2020, no need to use the TOWGS84[0,0,0,0,0,0,0]
2. When projecting between WGS84 to GDA2020 or to GDA94, you need to use the TOWGS84[0,0,0,0,0,0,0]

Can you confirm this from your side as well?

(p.s, no worries about the ellipsoid/geoid height differences (as long as the height value is correct), this is why I circled and marked the ellipsoid).

Thanks,
Yaniv

**Comment by rouault** [comment]
Closing as it seems no action is needed
