### ISSUE TITLE
[cmake] Error using find_package(proj)

### ISSUE THREAD

**Issue by JackBoosY** [OSGeo/PROJ#2792]
In the downstream, I wan't to fix some issues in https://github.com/microsoft/vcpkg/pull/19298.
After test the expoted cmake files, I got some errors:
```
1> CMake Error at F:/vcpkg/scripts/buildsystems/vcpkg.cmake:782 (_find_package):
1>   Could not find a configuration file for package "proj" that is compatible
1>   with requested version "".
1> 
1>   The following configuration files were considered but not accepted:
1> 
1>     F:/vcpkg/installed/x86-windows/share/proj/proj-config.cmake, version: 7.2.0 (package = PROJ, NOT proj)
```

So I checked the proj-config-version.cmake:
```cmake
...
if (NOT PACKAGE_FIND_NAME STREQUAL "PROJ")
  # Check package name (in particular, because of the way cmake finds
  # package config files, the capitalization could easily be "wrong").
  # This is necessary to ensure that the automatically generated
  # variables, e.g., <package>_FOUND, are consistently spelled.
  set (REASON "package = PROJ, NOT ${PACKAGE_FIND_NAME}")
  set (PACKAGE_VERSION_UNSUITABLE TRUE)
...
```

Then, I checked the source files:
https://github.com/OSGeo/PROJ/blob/2656c2980fbe6fd4775797f7ff7226cc320f6f59/cmake/CMakeLists.txt#L105-L116

https://github.com/OSGeo/PROJ/blob/2656c2980fbe6fd4775797f7ff7226cc320f6f59/cmake/project-config-version.cmake.in#L25-L31

https://github.com/OSGeo/PROJ/blob/e3d7e18f988230973ced5163fa2581b6671c8755/cmake/CMakeLists.txt#L96-L97

Obviously, the project name checked in `version.cmake` is unprocessed, and the exported cmake file name is lowercase, which causes this issue.

**Comment by dg0yt** [comment]
The canonical form is:
~~~
find_package(PROJ)
~~~
cf. https://proj.org/development/cmake.html

For cmake config files, the lower case file name is okay. `find_package` "searches for a file called `<PackageName>Config.cmake` or `<lower-case-package-name>-config.cmake` for each name specified." Cf. https://cmake.org/cmake/help/v3.21/command/find_package.html#full-signature-and-config-mode

**Comment by JackBoosY** [comment]
@dg0yt Yes, but it would be great if the two names are the same (strict).

**Comment by JackBoosY** [comment]
And I've made a patch to fix this, see https://github.com/microsoft/vcpkg/pull/19298/commits/864a20b07ffb49c84b7df680cfac958c913d2819.

**Comment by JackBoosY** [comment]
After some discussion, I think now is reasonable.
