### ISSUE TITLE
Update proj to newest version on Ubuntu 20.04

### ISSUE THREAD

**Issue by ratnanil** [OSGeo/PROJ#2794]
#### Example of problem

I would like to install the newest version of proj, which [currently is 8.1.0](https://proj.org/news.html). However, when I follow [the installation instructions](https://proj.org/install.html#debian), I get version 6.3.1. 
   
```
$ sudo apt-get install proj-bin
Reading package lists... Done
Building dependency tree       
Reading state information... Done
proj-bin is already the newest version (6.3.1-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

#### Problem description

Since quite a lot has happened since 6.3.1, I would like to update proj to a newer version

#### Expected Output

I expect there is add a repository to get the newest version of proj. How would I do this?

#### Environment Information
 - PROJ version (`proj`)
```
$ proj
Rel. 6.3.1, February 10th, 2020
```

 - Operation System Information

Ubuntu 20.04

#### Installation method

apt-get

**Comment by rouault** [comment]
This is not something PROJ upstream has influence upon. Ubuntu is a snapshot based distribution. For a given version of Ubuntu, you'll always get the version of PROJ that was packaged at that time. You must either upgrade your Ubuntu version, or build your own PROJ or use alternative distribution channels like Conda Forge.
