### ISSUE TITLE
Questions about accuracy about proj_create_crs_to_crs()

### ISSUE THREAD

**Issue by CrisFLZs** [OSGeo/PROJ#2799]
Sorry to bother you.
I use proj_create_crs_to_crs() function to transform the longitude and latitude to the XY coordinate.But the accuracy can only get to meter like X:111002 Y:5563311 .I want to use the proj_create_crs_to_crs_from_pj() function to improve the accuracy.But I don't know how to fit the parameters in it.
ACCURACY = value;
Could please tell me how to use this function by giving an example.

**Comment by CrisFLZs** [comment]
proj_create_crs_to_crs_from_pj(PJ_DEFAULT_CTX,wgs84,city,NULL,"ACCURACY=0.01")
I use this code.However it can't work.

**Comment by CrisFLZs** [comment]
proj_create_crs_to_crs_from_pj(PJ_DEFAULT_CTX,wgs84,city,NULL,"ACCURACY=0.01")
I use this code.However it can't work.

**Comment by rouault** [comment]
Questions about usage aren't appropriate for the bug tracker. See https://proj.org/community/channels.html for other communication channels
