### ISSUE TITLE
ok_proj6() always return FALSE. why to design it ?

### ISSUE THREAD

**Issue by bigdataman2015** [OSGeo/PROJ#2816]
ok_proj6() always return FALSE. why to design it ?

**Comment by bigdataman2015** [comment]
> PROJ::ok_proj6
function () 
{
    FALSE
}
<bytecode: 0x00000197f0ec1cf8>
<environment: namespace:PROJ>

**Comment by rouault** [comment]
I assume this issue is about another project. ok_proj6() is not a function present in PROJ code base. Closing as not a PROJ bug
