### ISSUE TITLE
 PROJ: proj_create: Error 1027 (Invalid value for an argument)

### ISSUE THREAD

**Issue by bowenbelongstonature** [OSGeo/PROJ#2821]
I'm doing gdalwarp on Cygwin platform with PROJ 8.0.0. 

_-s_srs +proj=lcc +lat_1=30.0 +lat_2=35.0 +lat_0=30.0 +lon_0=87.0 +x_0=0.0 +y_0=0.0 +a=6370000.0 +b=6370000.0 +units=m +no_defs +datum=WGS84_

Code above gave this error: _lcc: Invalid value for lat_1 and lat_2: |lat_1 + lat_2| should be > 0_

Please tell me why and how to fix it.

**Comment by busstoptaktik** [comment]
This site is for PROJ development. For usage questions, please refer to the communication channels (mailing list, etc.) listed [here](https://proj.org/community/channels.html)
