### ISSUE TITLE
EPSG:8353 does not get identified from ESRI WKT

### ISSUE THREAD

**Issue by wonder-sk** [OSGeo/PROJ#2822]
#### Example of problem

ESRI WKT for EPSG:8353 used in a shapefile is not correctly identified as EPSG:8353 by PROJ:

```
projinfo --identify "PROJCS[\"S-JTSK_[JTSK03]_Krovak_East_North\",
    GEOGCS[\"S-JTSK_[JTSK03]\",
        DATUM[\"S-JTSK_[JTSK03]\",
            SPHEROID[\"Bessel_1841\",6377397.155,299.1528128]],
        PRIMEM[\"Greenwich\",0.0],
        UNIT[\"Degree\",0.0174532925199433]],
    PROJECTION[\"Krovak\"],
    PARAMETER[\"False_Easting\",0.0],
    PARAMETER[\"False_Northing\",0.0],
    PARAMETER[\"Pseudo_Standard_Parallel_1\",78.5],
    PARAMETER[\"Scale_Factor\",0.9999],
    PARAMETER[\"Azimuth\",30.2881397527778],
    PARAMETER[\"Longitude_Of_Center\",24.8333333333333],
    PARAMETER[\"Latitude_Of_Center\",49.5],
    PARAMETER[\"X_Scale\",-1.0],
    PARAMETER[\"Y_Scale\",1.0],
    PARAMETER[\"XY_Plane_Rotation\",90.0],
    UNIT[\"Meter\",1.0]]"
```
That returns:
```
Identification match count: 1
EPSG:8353: 25 %
```
Nyall has pointed out this is a very low confidence match and QGIS uses 70% cutoff, so the match is not considered.

Surprisingly to me, EPSG:5514 which is an "older" CRS used in Slovakia and very similar to EPSG:8353 - in fact, in WKT2:2019 definition the only difference between those two CRS is that their `BASEGEOGCRS` is different (EPSG:8351 for EPSG:8353 vs EPSG:4156 for EPSG:5514). Yet EPSG:5514 is detected correctly from its ESRI WKT:

```
projinfo --identify "PROJCS[\"S-JTSK_Krovak_East_North\",
     GEOGCS[\"GCS_S_JTSK\",
         DATUM[\"D_S_JTSK\",
             SPHEROID[\"Bessel_1841\",6377397.155,299.1528128]],
         PRIMEM[\"Greenwich\",0.0],
         UNIT[\"Degree\",0.0174532925199433]],
     PROJECTION[\"Krovak\"],
     PARAMETER[\"False_Easting\",0.0],
     PARAMETER[\"False_Northing\",0.0],
     PARAMETER[\"Pseudo_Standard_Parallel_1\",78.5],
     PARAMETER[\"Scale_Factor\",0.9999],
     PARAMETER[\"Azimuth\",30.2881397527778],
     PARAMETER[\"Longitude_Of_Center\",24.8333333333333],
     PARAMETER[\"Latitude_Of_Center\",49.5],
     PARAMETER[\"X_Scale\",-1.0],
     PARAMETER[\"Y_Scale\",1.0],
     PARAMETER[\"XY_Plane_Rotation\",90.0],
     UNIT[\"Meter\",1.0]]"
```
That returns
```
Identification match count: 1
EPSG:5514: 100 %
```

#### Problem description

If the auth ID EPSG:8353 does not get identified, some CRS-related functionalities are not working correctly and causing confusion to users (see the original QGIS bug report https://github.com/qgis/QGIS/issues/44845)

#### Expected Output

EPSG:8353 should be identified from ESRI WKT.

#### Environment Information
 - PROJ version (`proj`): 6.3.1, 7.2.0
 - Operation System Information: linux (ubuntu 20.04)

#### Installation method
 - 6.3.1 from system packages, 7.2.0 self-compiled

**Comment by wonder-sk** [comment]
Thanks a lot Even on behalf of the Slovak QGIS community :slightly_smiling_face:

**Comment by rouault** [comment]
> on behalf of the Slovak QGIS community slightly_smiling_face

you mean on behalf of all people whose favorite CRS' datum name doesn't start with D_ in Esri world :rofl:
