### ISSUE TITLE
proj.db is no longer found under ../share/proj (on Windows at least)

### ISSUE THREAD

**Issue by joa-quim** [OSGeo/PROJ#2830]
I just built ``proj`` from master and now I get the known 
```
echo 55.2 12.2 | C:\programs\compa_libs\proj5_GIT\compileds\VC14_64\bin\proj +proj=merc +lat_ts=56.5 +ellps=GRS80
pj_obj_create: Cannot find proj.db
3399483.80      752085.60
```
Setting ``PROJ_LIB`` or going back to proj7, works.

**Comment by rouault** [comment]
can you give the file hiearchy that show the relative positions of the proj binary, the proj dll and proj.db ?

**Comment by joa-quim** [comment]
Things may look a bit confusing in my system that relies a lot on symlinks
```
C:\programs\compa_libs\proj5_GIT\compileds\VC14_64\bin\proj.exe
C:\programs\compa_libs\proj5_GIT\compileds\VC14_64\share\proj\proj.db
The dll is at
C:\programs\compa_libs\proj5_GIT\compileds\VC14_64\lib\proj_w64.dll
but referenced from a symlink in a dir that is in the path
```
I have used this structure for many years and if you remember I was the guy who first implemented the looking at  ``../share/proj/proj.db`` (on Windows).

And it's the first time that I'm using proj8 so this may come from already some time.

**Comment by rouault** [comment]
I don't recall this code to have changed or significantly changed since it was implemented. It is still in https://github.com/OSGeo/PROJ/blob/master/src/filemanager.cpp#L1235 . I guess it wil lbe easier for you to step through this and see what's going on

**Comment by joa-quim** [comment]
Ok, started to try but found one thing. It all works if the DLL is _physically_ at

```
C:\programs\compa_libs\proj5_GIT\compileds\VC14_64\lib\proj_w64.dll
C:\programs\compa_libs\proj5_GIT\compileds\VC14_64\bin\proj.exe
C:\programs\compa_libs\proj5_GIT\compileds\VC14_64\share\proj\proj.db
```
but not if it is at (symlinked and in the path)
```
C:\programs\compa_libs\DLLs_VC14_64\proj_w64.dll
```
This however, has worked up until proj7

Given the peculiarity of my environment I guess I'll have to swallow the pill and not using symlinks here.

**Comment by rouault** [comment]
> This however, has worked up until proj7

I believe this might be due to https://github.com/OSGeo/PROJ/commit/29583196dfae2565a35c7a8759cc8a5640d6a2b1 what must have been pushed after the previous version you tested. Initially we used GetModuleFileNameW() with a nullptr argument which caused the path of the current binary to be retrieved (but whose location might be unrelated to PROJ) and that change modified it to be queried on a function of proj dll itself, and this must be the physical location, not the symlink.

> Given the peculiarity of my environment I guess I'll have to swallow the pill and not using symlinks here.

Agreed

**Comment by joa-quim** [comment]
Yes, very likely the reason.

Made a symlink of ``share\proj`` in ``C:\programs\compa_libs`` and now the dll symlink 
``C:\programs\compa_libs\DLLs_VC14_64\proj_w64.dll``
is able to find ``proj.db`` again
