### ISSUE TITLE
EPGS codes of orthographic and topocentric implementations

### ISSUE THREAD

**Issue by stefangachter** [OSGeo/PROJ#2832]
Dear all, I am little bit confused about the EPGS codes and the corresponding implementations in Proj.
If I understand it correctly, 
https://proj.org/operations/conversions/topocentric.html?highlight=topocentric
then the `topocentric` conversion or maybe more precisely, `+proj=cart +ellps=WGS84 +step +proj=topocentric` , corresponds to EPSG  9836. Is my understanding correct?
I cannot find a reference for the orthographic projection `ortho`
https://proj.org/operations/projections/ortho.html?highlight=orthographic
I had a look at the implementation https://github.com/OSGeo/PROJ/blob/master/src/projections/ortho.cpp without digging too much into the details. If I understand it correctly, then orthographic projection is either "spherical" or "ellipsoidal".  Is it then EPSG 9839 or  EPSG 9840, respectively? And does the implementation follow the reference https://proj.org/zreferences.html#id17 as well (IOGP. Geomatics Guidance Note 7, Part 2)?
Thanks for the clarification.

**Comment by rouault** [comment]
+proj=topocentric alone is EPSG:9836
+proj=cart followed by +proj=topocentric is EPSG:9837
+proj=ortho is EPSG:9840 (ellipsoidal case implemented since PROJ 7.2, following IOGP guidance 7.2)
