### ISSUE TITLE
missing unit type - degree

### ISSUE THREAD

**Issue by wiktorn** [OSGeo/PROJ#284]
As far as I checked contents of the file [nad/epsg](https://github.com/OSGeo/proj.4/blob/master/nad/epsg) it looks, that there is a lot of units=m, although meters are default (as it was written on wiki page. I've corrected it already).

I've changed the wiki so it says now, that default is degrees, as it is for example for WGS84 and possibly other longlat projections. But there is no such unit reported by cs2cs -lu. Maybe degree unit should be added to the list of units in cs2cs.

**Comment by hobu** [comment]
Which wiki page are you referring to?

**Comment by wiktorn** [comment]
https://github.com/OSGeo/proj.4/wiki/GenParms

**Comment by kbevers** [comment]
I would say this is incorrect. Units of projected coordinates do not default to degrees. latlong "projections" are a special case. I've removed the statement from the wiki-page.

**Comment by wiktorn** [comment]
But if it is left like that, it is difficult to understand how missing unit= param is treated, and as I understand - it is somehow handled.

Is it the case, that default depends on proj= parameter?

**Comment by kbevers** [comment]
Per design proj outputs projected coordinates in meters. There is possibly a few projections that overrides or ignores this behaviour, in which case you can't rely on the +parameter. The latlong "projection" completely ignores +units.

If you leave out the +unit parameter units of the coordinates you get are the default for that particular projection. This will almost always be meters.

**Comment by wiktorn** [comment]
Then maybe it's worth documenting, that:
- default is dependant on projection, for merc, tmerc and utm projection it's meters, for latlon - degrees

Then for most EPSG projections - units=m is surplus and can be removed, because anyway meters is the default value.

**Comment by kbevers** [comment]
The default unit is now mentioned on http://proj4.org/parameters.html#units:  https://github.com/OSGeo/proj.4/commit/f253355bc22b118049c0f205bdd47e7fee6afe23

That is correct, though it doesn't hurt to be explicit with these things.

**Comment by maikefischer** [comment]
Any idea how I can output km instead of meters?

**Comment by kbevers** [comment]
Yes: https://proj4.org/usage/projections.html#units

And for the record, [questions about the use of PROJ should be directed to the mailing list, not the issue tracker](https://proj4.org/community/channels.html).
