### ISSUE TITLE
Language bindings : fProj4 : Link broken

### ISSUE THREAD

**Issue by jbelien** [OSGeo/PROJ#288]
Hi,
Just a quick note to warn you that the "fProj4 - bindings for proj.4 in MySQL" link in "Language bindings" is broken (http://wiki.ferhatbingol.com/index.php/MySQL/Scientific:Packages:fPROJ4).

I'll try to contact Ferhat Bingöl to know if the library is still available somewhere.

**Comment by jbelien** [comment]
Unfortunately, no answer from Ferhat Bingöl.

**Comment by rouault** [comment]
Fixed the wiki with a link that seems to work : https://github.com/OSGeo/proj.4/wiki/Home/_compare/6716b93c3c0cfc43c26582f6fc23e8e1b6f21789...808fa906906139c507a1e09afae775f08e323cbd
