### ISSUE TITLE
[8.1.0] [5.0.1]Behaviour change when transform coordinates 

### ISSUE THREAD

**Issue by qd1308504206** [OSGeo/PROJ#2894]
Behavior changes in versions 8.1.0 and 5.0.1

```cpp
# code test version 8.1.0
PJ_CONTEXT* context = proj_context_create();

//set search_paths  The code for setting the path is not the key point, which is omitted here

    auto srcCRS = proj_create(context, "EPSG:4490");
    auto targetCRS = proj_create(context, "EPSG:4547");
    
    auto pj = proj_create_crs_to_crs_from_pj(context, srcCRS, targetCRS, nullptr, nullptr);
    
    proj_destroy(srcCRS);
    proj_destroy(targetCRS);
    //PJ_COORD coord = { -78271.516964022070, 313086.06785608182, 0, 0 };
    PJ_COORD coord = { 313086.06785608182,-78271.516964022070, 0, 0 };
    PJ_COORD coord2 = proj_trans(m_pj, PJ_DIRECTION::PJ_FWD, coord);
   //output  coord2 is  inf inf inf inf
```
*******************************************************************************************************
but the Code in version 5.0.1
can get result : -1366.095681552781   5464.3827262110126

and the website http://epsg.io/transform#s_srs=4490&t_srs=4547&x=-78271.5169639&y=313086.0678561
also get result: -1366.10 5464.38  

-------------------------------------------------------------------------------------------------------
I am very clear about the following points.
1: I know the coordinates  are beyond the boundary of 4490 CRS
2: I Know the new feature in version 8.1.0 of proj coordinate's order need to swap. that is not the key point
3: I Know I should to do transform from 4547 to 4490.
4: I know that converting out of range coordinates has no practical significance
-------------------------------------------------------------------------------------------------------
now I have a question
#### Problem description
when input the coordinates out of boundary,
output is inf inf ...  is that Intentional change？or a bug? or is that some way to avoid this?

yes , I want to get same result with version 5.0.1

please help me,  actually， the code I learned from gdal 3.3.1 source code.
someone tell me what can I do someting in gdal is also ok.

**Comment by rouault** [comment]
> when input the coordinates out of boundary, output is inf inf ... is that Intentional change？

Yes, a latitude outside of [-90,90] degree is non-sense, and we now reject it.
You could likely get the same results as before by removing the following lines in src/fwd.cpp
```
        /* check for latitude or longitude over-range */
        t = (coo.lp.phi < 0  ?  -coo.lp.phi  :  coo.lp.phi) - M_HALFPI;
        if (t > PJ_EPS_LAT)
        {
            proj_log_error(P, _("Invalid latitude"));
            proj_errno_set (P, PROJ_ERR_COORD_TRANSFM_INVALID_COORD);
            coo = proj_coord_error ();
            return;
        }
        if (coo.lp.lam > 10  ||  coo.lp.lam < -10)
        {
            proj_log_error(P, _("Invalid longitude"));
            proj_errno_set (P, PROJ_ERR_COORD_TRANSFM_INVALID_COORD);
            coo = proj_coord_error ();
            return;
        }


        /* Clamp latitude to -90..90 degree range */
        if (coo.lp.phi > M_HALFPI)
            coo.lp.phi = M_HALFPI;
        if (coo.lp.phi < -M_HALFPI)
            coo.lp.phi = -M_HALFPI;
```

**Comment by qd1308504206** [comment]
@rouault 
Hello,  I do as you say , and test it again after remove the code.
my test code is not changed.

but I get the result is unexpected.
after remove code the result is : coord2 = {-9780199.9085544478, -2243223.3572037192, 0,0}

is there any other code need to modify or remove?

**Comment by qd1308504206** [comment]
there I do some changes, can get expected results
result is : coord2 = {-1366.1,5464.38, 0,0}

from following lines in src/fwd.cpp
```
PJ_COORD pj_fwd4d (PJ_COORD coo, PJ *P) {
    int last_errno = proj_errno_reset(P);

    if (!P->skip_fwd_prepare)
        coo = fwd_prepare (P, coo);
    if (HUGE_VAL==coo.v[0])
        return proj_coord_error ();
```

to
```
PJ_COORD pj_fwd4d (PJ_COORD coo, PJ *P) {
    int last_errno = proj_errno_reset(P);

    if (!P->skip_fwd_prepare)
    {
        auto coo2 = fwd_prepare(P, coo);
        if (HUGE_VAL == coo2.v[0])
        {
            proj_errno_reset(P);
            return error_or_coord(P, coo, last_errno);
        }
        
        coo = coo2;
    }
    if (HUGE_VAL==coo.v[0])
        return proj_coord_error ();
```

And I made a same modification in the function `PJ_COORD pj_fwd4d (PJ_COORD coo, PJ *P) `
`PJ_XYZ pj_fwd3d(PJ_LPZ lpz, PJ *P) `
`PJ_XY pj_fwd(PJ_LP lp, PJ *P)`
