### ISSUE TITLE
document geodesic issues in proj 4.9.1

### ISSUE THREAD

**Issue by cffk** [OSGeo/PROJ#291]
Here are the issues with the geod utility and geodesic library in proj
4.9.1.  This is mainly to serve as documentation for pull request #290.

(A) The library requires that latitudes be in the range [-90,90] and
longitudes in the range [-540,540); however this is not checked for or
enforced in the geod utility and as a consequence bogus results are
returned.

(B) dmstor uses an inaccurate value for pi/180 which leads to some odd
results in some cases.

Pull request #290 fixes these problems as follows:

(A) The library converts latitudes outside the range [-90,90] to NaN
causing NaNs to be returned.  It also accepts any values for longitude
and azimuth.  Exact range reduction is done on these quantities (however
this is of marginal utility in the context of geod which first converts
the arguments to radians).

(B) geod now uses dmstor's inaccurate value for pi/180 to convert the
arguments back to degrees.

Examples: invoke geod with arguments

  -I +ellps=WGS84 -f %.14f -F %.9f

Illegal latitude
  20 30 100 0
  => 0.0 180.0 8906425.332516942 (before)
  => nan nan nan (after)

Previously illegal (and now legal) longitude
  20 30 30 1000
  => 0.0 0.0 14471451.806513431 (before)
  => -54.91770376976906 62.56591359249907 10709578.386826832 (after)

Fix inaccurate treatment of the pole
  20 30 90 50
  => -0.0 -180.0 7789599.475141093 (before)
  => 0.0 -160.0 7789599.475141088 (after)

Fix inaccurate treatment of antipodal points
  0 0 0 180
  => -0.00000000000483 0.00000000000483 20003931.458625447 (before)
  => 0.0 0.0 20003931.458625447 (after)

**Comment by rouault** [comment]
Now that #290 is merged, is there any point keeping this ticket still opened ?

**Comment by cffk** [comment]
Closed!
