### ISSUE TITLE
Where is TRAC bug tracker?

### ISSUE THREAD

**Issue by rsbivand** [OSGeo/PROJ#293]
Why had the content of the TRAC bug tracker not been copied across?

**Comment by rouault** [comment]
Not sure to understand your question. Look at https://github.com/OSGeo/proj.4/issues/ . It is there

**Comment by rsbivand** [comment]
Yes, but that isn't easy to find and is hard to search. I've found:

https://github.com/OSGeo/proj.4/issues/274

which was what I wanted. I'm going to repeat it, because I keep being bugged by people falling over the omitted proj_def.dat file in 4.9.1.

**Comment by rsbivand** [comment]
Issues do not get pushed to the proj mailing list - why not? Without their being circulated there, none of "us" see the issues, and I'm not going to bother to run RSS on them, life is too short. Scanning a list digest is possible, but github is and will continue to be a big mess.

**Comment by rouault** [comment]
@rsbivand  You can subscribe to github notifications with https://github.com/OSGeo/proj.4/subscription

**Comment by rsbivand** [comment]
Exactly. If I am obliged to track multiple projects both on list and in notifications, I will drop doing both - the list will largely not contain significant information, and the notifications will be more noise than signal - scanning topics on a single list daily digest arriving in my inbox when something was going on gave me what I needed to pre-empt downstream problems. Github doesn't and never will, because it is not about information flow. Can notifications be posted to the list, technically?
