### ISSUE TITLE
When 4.9.2??

### ISSUE THREAD

**Issue by rsbivand** [OSGeo/PROJ#294]
In:

https://github.com/OSGeo/proj.4/issues/274

it was indicated that a snafu of the order of omitting proj_def.dat in the 4.9.1 release tarball would cause a speedy release of 4.9.2. Nothing has happened, and user problems accumulate despite providing guidance and coding round the "infelicity". When 4.9.2 - just this problem should have led to a release?

**Comment by rouault** [comment]
Roger,

"When 4.9.2" isn't appropriate for a bug tracker, but rather for the proj mailing list
