### ISSUE TITLE
Issue when trying to convert to lat/long system from gauss-kruger.

### ISSUE THREAD

**Issue by ealione** [OSGeo/PROJ#295]
I have some variables that look like this

`x1 = 4566236.297;
y1 = 5827396.697;`

that use the gauss-kruger zone 4, system. When trying to convert these to a latitude longitute value by trying

```
if (!(pj_merc = pj_init_plus("+proj=tmerc +lat_0=0 +lon_0=12 +k=1 +x_0=4500000 +y_0=0 +ellps=bessel +datum=potsdam +units=m +no_defs"))) {
        exit(1);
    }
if (!(pj_latlong = pj_init_plus("+proj=latlong +datum=WGS84"))) {
        exit(1);
}

x1 *= DEG_TO_RAD;
y1 *= DEG_TO_RAD;

pj_transform(pj_merc, pj_latlong, 1, 1, &x1, &y1, NULL );
```

I get back `-0.433622 0.0128923`.

Am I doing something wrong?

**Comment by rouault** [comment]
Questions are not for github tickets. Use the proj mailing list : http://lists.maptools.org/mailman/listinfo/proj
