### ISSUE TITLE
Omitted nad/proj_def.dat in 4.9.1

### ISSUE THREAD

**Issue by rsbivand** [OSGeo/PROJ#298]
Is anyone paying attention to:

http://lists.maptools.org/pipermail/proj/2015-September/007209.html

and 

http://lists.maptools.org/pipermail/proj/2015-May/007125.html

This blunder always merited a 4.9.2 release which should have been made in May. If you see the full current thread, you'll see requests for admission of serious bug fixes for the release process (that made in May turns out not to have been sufficient).

Not posting issues on the mailing list, and people here not reading (or reading and ignoring) the mailing list is a very serious weakening of the development process (IMO typical of github). This software is vital, and shouldn't be subject to rushed releases (4.9.1 wasn't properly checked).

**Comment by hobu** [comment]
> shouldn't be subject to rushed releases (4.9.1 wasn't properly checked).

There were _5_ release candidates. I don't think you can say it wasn't properly checked.

**Comment by rsbivand** [comment]
Yes, I can. The omission of a crucial file of defaults, leading to error in:

$ echo "0 0" | proj +proj=utm +zone=32

which didn't happen before is a showstopper. Having many RCs doesn't help if the problems are not set up for testing, or are hard to debug (this was so obvious once I realised that the problem was the missing defaults file, but before that I'd been all over pj_init_plus and friends, assuming that it was a library issue.

The underlying question is why the test suit didn't test something as simple as this; your answer would be more helpful if you showed that simple things like this are now tested. Years ago there was another foobar with a release without the version number properly set. Not complicated, but problematic for downstream applications.

**Comment by rouault** [comment]
For what is worth I wasn't even aware that not specifying a datum was valid, or what that proj_def.dat file was supposed to do. Perhaps one should revoke my commit rights for ignorance ;-) ?

**Comment by rsbivand** [comment]
What I initially though was that someone - arguably wisely - had tightened something in pj_init\* and friends with regard to not having at least something like +ellps=, but couldn't see where it had happened. The file culprit seems to be dated 1994, possibly untouched since then. However, when checking R packages depending on rgdal, it turned out that many relied on +ellps=WGS84, simply setting "+proj=longlat" as the coordinate reference system. I've tried to convince people to set the ellipsoid themselves based on actually knowing (or via EPSG), but in userland there are lots of production scripts, teaching materials, etc., without. Since I'd only worked around the missing ellps when +no_defs wasn't set, I missed +datum being set, and worse +init being set, resulting in the injection of the wrong +ellps in some cases. That was blocked three days ago, but there are repercussions in other software dependencies in the R environment.

Yes, we could move to dropping defaults, but they've been there since 4.3. I think that would be hard to do twenty years after they were introduced. I didn't know they were there either, until they went away and the consequences became apparent.
