### ISSUE TITLE
Problems building on FreeBSD 10, PTHREAD_MUTEX_RECURSIVE

### ISSUE THREAD

**Issue by turepalsson** [OSGeo/PROJ#302]
I'm having problems building on FreeBSD 10. In `src/pj_mutex.c`, the following lines

```
#ifndef PTHREAD_MUTEX_RECURSIVE
        pthread_mutexattr_settype(&mutex_attr, PTHREAD_MUTEX_RECURSIVE_NP);
#else
        pthread_mutexattr_settype(&mutex_attr, PTHREAD_MUTEX_RECURSIVE);  
#endif
```

blow up, because `PTHREAD_MUTEX_RECURSIVE` is an `enum` constant, not a `#define`:d value (and `PTHREAD_MUTEX_RECURSIVE_NP` is not defined at all).

**Comment by rouault** [comment]
Fixed per https://github.com/OSGeo/proj.4/pull/303
