### ISSUE TITLE
Question: is float GeoTIFF and GPG lossless compared to .gsb?

### ISSUE THREAD

**Issue by ValZapod** [OSGeo/PROJ#3032]
FFmpeg that I usually use does not really have precision for float --> int stuff, so cannot verify.

If the anwser is yes, please update https://proj.org/specifications/geodetictiffgrids.html where you start talking about GDA2020 here 

>The file size is 4.8 MB using DEFLATE compression and floating-point predictor. To be compared with the 83 MB of the original .gsb file.

**Comment by ValZapod** [comment]
I also find it insane that float values are not done in GeographicLib! Just nuts, they do not even support TIFF even NOT IN FLOAT (from docs here https://geographiclib.sourceforge.io/html/geoid.html)

Also can you please verify this for me, 1'x1' EGM2008 GPG file? https://www.agisoft.com/downloads/geoids/

**Comment by rouault** [comment]
github issues are not for questions.
