### ISSUE TITLE
Build error on Windows when using CMake

### ISSUE THREAD

**Issue by iraytrace** [OSGeo/PROJ#308]
When using cmake to build on Windows, Visual Studio 2013 fails to build complaining: 
error MSB6006: "cmd.exe" exited with code 9009.

You can reproduce the problem with:

<pre>git clone https://github.com/OSGeo/proj.4.git
mkdir proj.4\build
cd proj.4\build
cmake -G "Visual Studio 12 2013 Win64" -Wno-dev -DCMAKE_INSTALL_PREFIX=C:\installed ..
cmake --build . --target install --config Release
</pre>

By comparison, the following nmake succeeds:

<pre>git clone https://github.com/OSGeo/proj.4.git
cd proj.4
nmake /f makefile.vc INSTDIR=C:\installed install-all</pre>

**Comment by hobu** [comment]
According to AppVeyor, it does build cleanly on x64 on Visual Studio 12

https://ci.appveyor.com/project/OSGeo/proj-4/build/1.0.75
