### ISSUE TITLE
How to reference the proj.4 library

### ISSUE THREAD

**Issue by DamienIrving** [OSGeo/PROJ#309]
I'm writing a scientific journal paper at the moment in which I use [Iris](http://scitools.org.uk/iris/) to re-calculate atmospheric wind data in a rotated coordinate system (i.e. one where the north pole has been moved). In the methods section of the paper I list the major software packages I used for the research, including any references to academic papers written about that software (e.g. many authors of scientific software are publishing with journals like the _Journal of Open Research Software_ so they can get academic credit for their work). Since Iris uses proj.4 for grid rotation, I'd like to reference proj.4 if possible. Is there an appropriate reference that I could cite?

**Comment by rouault** [comment]
For a next time, github ticket are not the best place for questions. The medium for that is rather the proj mailing list :  http://lists.maptools.org/mailman/listinfo/proj
Speaking just on my behalf, I don't think there's a recommandation to reference proj.4. "The Proj.4 library : https://github.com/OSGeo/proj.4" would be fine I think. If you want to reference a particular algorithm in proj, then you'd have to dig up in the history to find the original author(s), but I don't think they care that much. Oh well, I'm just not in acadamics and don't pretend to understand the subtelties of that aspect of the academic work ;-) The only obligations related to proj.4 are the ones linked to the software license : https://github.com/OSGeo/proj.4/blob/master/COPYING. Much of the original work was done by Gerald Evenden, probably largely based on Snyder's works, but there have been a lot of other contributions.

**Comment by hobu** [comment]
> "The Proj.4 library : https://github.com/OSGeo/proj.4" would be fine I think.

Yep. Maybe specifically call out Gerald too, but since proj.4 is a fork of Gerald's work, maybe this would be confusing.

**Comment by katrinleinweber** [comment]
Have you considered applying [GH's "Citable Code" guide](https://guides.github.com/activities/citable-code/) and/or [including a `CITATION` file](https://www.software.ac.uk/blog/2016-10-06-encouraging-citation-software-introducing-citation-files) in this repo?
