### ISSUE TITLE
./configure missing

### ISSUE THREAD

**Issue by edzer** [OSGeo/PROJ#310]
`./configure` is currently missing; if I run `autoconf` on a stale Ubuntu 14.04 (v 2.69) I get warnings and a non-working ./configure, giving me:

./configure: line 2157: AM_INIT_AUTOMAKE: command not found
./configure: line 2158: syntax error near unexpected token `src/proj_config.h'
./configure: line 2158:`AM_CONFIG_HEADER(src/proj_config.h)'

**Comment by QuLogic** [comment]
`./configure` is not supposed to be in git. If you want to run from git, you need to run `./autogen.sh` _or_ `autoreconf` to recreate all autotools files.

**Comment by edzer** [comment]
Fair point, but then please add these instructions to the README, which now tells you to start with ./configure. https://trac.osgeo.org/proj/ points to the github repo, and the README suggests we have a released version, here.

**Comment by QuLogic** [comment]
You can get a release from the section [here](https://github.com/OSGeo/proj.4/releases). It does contain `./configure` and should not require autotools. Someone from the project will have to update the links on trac if desired.
