### ISSUE TITLE
Error on NTF_France_II_degree projection system

### ISSUE THREAD

**Issue by bsaglio** [OSGeo/PROJ#312]
It appears that there is a unexpected shift when reprojecting (with proj.4) shapefiles associated with a "NTF_France_II_degree" PRJ file produced by ArcGIS.
This PRJ file is slightly different from the official one used by Q-GIS for instance and that is avalaible at the following URL ;
http://spatialreference.org/ref/esri/102582/prj/

Please find attached an illustration of this difference that caused mismatch in proj.4 library.
![difference](https://cloud.githubusercontent.com/assets/11537300/10220158/5f240a9c-6845-11e5-87a2-d00cf8cb3e1a.PNG)

**Comment by rouault** [comment]
I'm sorry, but as such, this report is far from being characterized enough to be identified as a proj.4 issue. Could be a ArcMap, a QGIS one, etc... If you think it is a proj.4 issue, then try to demonstrate it only with proj.4 tools.

**Comment by bsaglio** [comment]
The reprojection to WebMercator is made using proj.4.
The data source comes either from ArcGis or Q.GIS, so the PRJ file is slightly different, as described below.
The data itself is no matter.

**Comment by bsaglio** [comment]
If you want to make a local test

Example of data produced with the official ESRI:102582 projection system : http://wgs3.s3.amazonaws.com/perso/bsaglio/proj4/QGIS-102582.zip

Example of data produced by ArcGIS (PRJ slightly diffrent) 
http://wgs3.s3.amazonaws.com/perso/bsaglio/proj4/ArcMap-102582.zip

**Comment by rouault** [comment]
Sorry to be a pain. But provide cs2cs comand line and input value. Output values you got. Output values you expected. Maintainers are lazy ! (I am!)
