### ISSUE TITLE
Using cmake specifying -DBUILD_LIBPROJ_SHARED=off from a fresh "git clone" breaks compilation

### ISSUE THREAD

**Issue by oelbox** [OSGeo/PROJ#325]
Sorry if this has been reported previously, but a quick search in issues, came up empty.

When using cmake from a fresh git clone (important) and doing:

```
mkdir build && cd build
cmake -DBUILD_LIBPROJ_SHARED=off ..
make
```

Compiling the code results gcc for most, if not all, executables report undefined references.

When using cmake and doing:

```
cmake -DBUILD_LIBPROJ_SHARED=off -DBUILD_CS2CS=off -DBUILD_PROJ=off -DBUILD_GEOD=off -DBUILD_NAD2BIN=off ..
```

libproj.a is built, but make still reports

```
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

If you do

```
mkdir build && cd build
cmake ..
make
cd ..
rm -rf build && mkdir build && cd build
cmake -DBUILD_LIBPROJ_SHARED=off -DBUILD_CS2CS=off -DBUILD_PROJ=off -DBUILD_GEOD=off -DBUILD_NAD2BIN=off ..
make
```

It compiles without error. So building it first as a shared library, removing the build directory, then making the build directory once again and building as static library works fine.

**Comment by cffk** [comment]
The first error you describe arises because the executables are only
linked with the system libraries (e.g., -lm) if the libproj is built as
a shared library.  Please try the following patch

```
diff --git a/src/lib_proj.cmake b/src/lib_proj.cmake
index b7b497c..47cd807 100644
--- a/src/lib_proj.cmake
+++ b/src/lib_proj.cmake
@@ -294,15 +294,15 @@ set_target_properties(${PROJ_CORE_TARGET}
 # Link properties
 ##############################################
 set(PROJ_LIBRARIES ${PROJ_CORE_TARGET} )
-if(UNIX AND BUILD_LIBPROJ_SHARED)
+if(UNIX)
     find_library(M_LIB m)
     if(M_LIB)
       TARGET_LINK_LIBRARIES(${PROJ_CORE_TARGET} -lm)
     endif()
-endif(UNIX AND BUILD_LIBPROJ_SHARED)
-if(USE_THREAD AND Threads_FOUND AND CMAKE_USE_PTHREADS_INIT AND BUILD_LIBPROJ_SHARED)
+endif(UNIX)
+if(USE_THREAD AND Threads_FOUND AND CMAKE_USE_PTHREADS_INIT)
    TARGET_LINK_LIBRARIES(${PROJ_CORE_TARGET} ${CMAKE_THREAD_LIBS_INIT})
-endif(USE_THREAD AND Threads_FOUND AND CMAKE_USE_PTHREADS_INIT AND BUILD_LIBPROJ_SHARED)
+endif(USE_THREAD AND Threads_FOUND AND CMAKE_USE_PTHREADS_INIT)


 ##############################################
```

Before this patch is adopted, someone probably should figure out the
motivation behind the original logic.

**Comment by oelbox** [comment]
Yepp, patch worked nicely! Thank you for posting it.

**Comment by hobu** [comment]
> Before this patch is adopted, someone probably should figure out the motivation behind the original logic.

I suspect it was copied from somewhere and the motivation wasn't intentional.
