### ISSUE TITLE
cant find sqlite3

### ISSUE THREAD

**Issue by mrx23dot** [OSGeo/PROJ#3277]
cloning head.
cmake ..

CMake Error at CMakeLists.txt:187 (message):
  sqlite3 >= 3.11 required!

 sqlite3 --version
3.34.1 2021-01-20 14:10:07 10e20c0b43500cfb9bbc0eaa061c57514f715d87238f4d835880cd846b9ealt1

**Comment by dg0yt** [comment]
> CMake Error at CMakeLists.txt:187 (message):
> sqlite3 >= 3.11 required!

This is refering to development stuff (headers, libs).

> sqlite3 --version
> 3.34.1 2021-01-20 14:10:07 10e20c0b43500cfb9bbc0eaa061c57514f715d87238f4d835880cd846b9ealt1

This is the tool. 

Now there is a huge gap from having the tool to having CMake find the development stuff.
