### ISSUE TITLE
FL not generated from FL.lla on windows

### ISSUE THREAD

**Issue by bartoli** [OSGeo/PROJ#330]
On Windows, nad/makefile.vc doesn't have FL in OLD_GRIDS. this causes $prefix/share/FL to be absent on a windows install, while a linux install uses *.lla, so FL is installed
Is there a particular reason, or was it simply forgotten?

**Comment by hobu** [comment]
Simply forgotten. Please make a pull request tweaking this and we'll merge it.

**Comment by bartoli** [comment]
There seeems to be the same issue for CH. But scripts changed in 6.x, so the error must be only in 4.9.x, which i suppose you won't do any more release?

**Comment by kbevers** [comment]
> which i suppose you won't do any more release

Correct.
