### ISSUE TITLE
Next minor version 4.10.0 will break PJ_VERSION

### ISSUE THREAD

**Issue by micahcochran** [OSGeo/PROJ#333]
I saw a tag for 4.10.0 and have been working on getting proj4 version info for matplotlib's basemap.  In the minor version if it is 4.10.0, PJ_VERSION will break.

Currently for 4.9.2 it is defined this way:

``` C
#define PJ_VERSION 492
```

At some point this will need to be fixed, not necessarily for 4.9.3.

GDAL handles versions in this manner [gdal_version.h](https://github.com/OSGeo/gdal/blob/trunk/gdal/gcore/gdal_version.h).

**Comment by cffk** [comment]
How about the following (to go into proj_api.h):

``` C
#define PROJ_VERSION_MAJOR 4
#define PROJ_VERSION_MINOR 9
#define PROJ_VERSION_PATCH 3

#define PROJ_VERSION_NUM(a,b,c) ((((a) * 10000 + (b)) * 100) + (c))

/* PROJ_VERSION = 4000903 */
#define PROJ_VERSION \
 PROJ_VERSION_NUM(PROJ_VERSION_MAJOR, PROJ_VERSION_MINOR, PROJ_VERSION_PATCH)

/* For backward compatibility, use only if PROJ_VERSION is undefined */
#define PJ_VERSION 493
```

The exact definiton of PROJ_VERSION_NUM doesn't matter as long as users perform tests like this

``` C
#if defined(PROJ_VERSION) && PROJ_VERSION >= PROJ_VERSION_NUM(4,9,3)
...
#endif
```

**Comment by micahcochran** [comment]
I think I'd prefer (a,b,c) to be replaced with more descriptive (major,minor,patch) like this:

``` C
#define PROJ_VERSION_NUM(major,minor,patch) ((((major) * 10000 + (minor)) * 100) + (patch))
```

A small point is that this doesn't follow the PJ_ naming convention.

PJ_VERSION should be deprecated, but it should still be updated until it no longer works.   Changing it in the 4.9.3 release would give other projects time to update to the new version scheme.  It looks good to me @cffk !

**Comment by rouault** [comment]
Note: there's just an inconsistency in the value of the /\* PROJ_VERSION = 4000903 */  comment and the one coming from the formula. Should be 40903.

**Comment by cffk** [comment]
The multiplications are nested in this formula, so there really are 4 digits allocated to the minor version number.

**Comment by rouault** [comment]
> The multiplications are nested in this formula, so there really are 4 digits allocated to the minor version number.
> Oh I didn't see it. Anticipating proj 4.666.0 ;-) ?

**Comment by hobu** [comment]
Note that I propose the next release version be 4.9.3, and I am hoping to produce a release candidate as part of the Paris Code Sprint.  I also plan to spend a few hours doing website cleanup and organization.

**Comment by micahcochran** [comment]
[I think that 4.9.3 is release version has already been shown in actions](https://github.com/OSGeo/proj.4/issues?utf8=%E2%9C%93&q=milestone%3A4.9.3).

**Comment by QuLogic** [comment]
A milestone does not equal a release; it's just a target.

**Comment by cffk** [comment]
Let me offer a counterproposal...

Stick with PJ_VERSION and just define (and document) its format for
version 4.10.0 and later (see below).  This has the benefits that
existing version tests continue to work, nothing gets deprecated, and
everything will work seamlessly until version 999.999.99.

``` patch
diff --git a/src/proj_api.h b/src/proj_api.h
index db833b1..b482c0f 100644
--- a/src/proj_api.h
+++ b/src/proj_api.h
@@ -37,7 +37,18 @@
 extern "C" {
 #endif

-/* Try to update this every version! */
+/*
+ * This version number should be updated with every release!  The format of
+ * PJ_VERSION is
+ *
+ * * Before version 4.10.0: PJ_VERSION=MNP where M, N, and P are the major,
+ *   minor, and patch numbers; e.g., PJ_VERSION=493 for version 4.9.3.
+ *
+ * * Version 4.10.0 and later: PJ_VERSION=MMMNNNPP later where MMM, NNN, PP
+ *   are the major, minor, and patch numbers (the minor and patch numbers
+ *   are padded with leading zeros if necessary); e.g., PJ_VERSION=401000
+ *   for version 4.10.0.
+ */
 #define PJ_VERSION 493

 /* pj_init() and similar functions can be used with a non-C locale */
```

**Comment by micahcochran** [comment]
The benefit of the counter-proposal is that, if you need a feature that is in 4.9.2.  
`#if PJ_VERSION > 492` is true if PJ_VERSION=493 or PJ_VERSION=401000.

I think this is slightly less complicated than the first proposal.  I am in slightly favoring of this policy change for version numbering over the first proposal.

**Comment by micahcochran** [comment]
@cffk I've warmed up to your counter-proposal.  Would you mind submitting a pull request for it?

I've worked on some code for making this work in pyproj, the Python library using PROJ.4, in its Cython code:

``` Python
if PJ_VERSION > 499:
    proj_version_str = "{0}.{1}.{2}".format(PJ_VERSION // 10**5 % 1000, PJ_VERSION // 10**2 % 1000, PJ_VERSION % 100)
else:
    proj_version_str = "{0}.{1}.{2}".format(PJ_VERSION // 100 % 10, PJ_VERSION // 10 % 10, PJ_VERSION % 10)
```

// is the floor division operator in Python.

Thank you!

**Comment by cffk** [comment]
OK, I'll do so this weekend.

**Comment by micahcochran** [comment]
@cffk Thank you!
