### ISSUE TITLE
Disparity between cs2cs and pj_init_plus

### ISSUE THREAD

**Issue by kodonnell** [OSGeo/PROJ#334]
I'm testing using proj4 in some MySQL UDFs, and all was working fine on the previous server I was testing on. However, on trying it on another, I've discovered an odd bug (or I've misunderstood something):

Previously, this worked:

```
input = "+proj=nzmg +nadgrids=nzgd2kgrid0005.gsb"; 
pj_in = pj_init_plus(input)
```

However, on the new server, I've had to change to:

```
input = "+proj=nzmg +datum=nzgd49 +nadgrids=nzgd2kgrid0005.gsb"; 
```

otherwise `pj_init_plus` fails. Oddly though, the prior `input` still works with cs2cs, e.g.

```
echo -e "2494214\t6744354" | cs2cs +proj=nzmg +nadgrids=nzgd2kgrid0005.gsb +to +proj=tmerc +lat_0=0 +lon_0=173 +k=0.9996 +x_0=1600000 +y_0=10000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
```

Adding in the `+datum=nzgd49` doesn't appear to affect the output, so I can probably continue to use it. However, thought it might be a useful "bug" to know about ...

Ah, almost forgot - running `proj` gives `Rel. 4.9.2, 08 September 2015`, on both the old and new servers. The old server is centos (7?), and the new is Arch Linux.

**Comment by mwtoews** [comment]
Is `nzgd2kgrid0005.gsb` loaded in the correct directory of the new server? You didn't show the output, which correctly is:

```
$ echo -e "2494214\t6744354" | cs2cs +proj=nzmg +datum=nzgd49 +nadgrids=nzgd2kgrid0005.gsb +to +proj=tmerc +lat_0=0 +lon_0=173 +k=0.9996 +x_0=1600000 +y_0=10000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
1583188.01      6182105.87 0.00
```

And yes, `+datum=nzgd49` is a required parameter, but perhaps it was not in (e.g.) version 4.8.0. I suppose it was implied from definitions (somewhere), since if you use `+no_defs` on the left side it will raise the error with any version of proj, e.g.

```
$ cs2cs +proj=nzmg +nadgrids=nzgd2kgrid0005.gsb +no_defs +to +proj=tmerc +lat_0=0 +lon_0=173 +k=0.9996 +x_0=1600000 +y_0=10000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs                                                                   Using from definition: proj=nzmg no_defs
Rel. 4.8.0, 6 March 2012
<cs2cs>:
projection initialization failure
cause: major axis or radius = 0 or not given
program abnormally terminated
```

**Comment by kodonnell** [comment]
Yes, the datum file is loaded into the correct directory, and the output is as you have above.

My point is that it does _not_ seem to be a required parameter for cs2cs - I get the same answer below with and without `datum=nzgd49`:

```
# no datum
$ echo -e "2494214\t6744354" | cs2cs +proj=nzmg +nadgrids=nzgd2kgrid0005.gsb +to +proj=tmerc +lat_0=0 +lon_0=173 +k=0.9996 +x_0=1600000 +y_0=10000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
1583188.01      6182105.87 0.00
# with datum
$ echo -e "2494214\t6744354" | cs2cs +proj=nzmg +datum=nzgd49 +nadgrids=nzgd2kgrid0005.gsb +to +proj=tmerc +lat_0=0 +lon_0=173 +k=0.9996 +x_0=1600000 +y_0=10000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
1583188.01      6182105.87 0.00
```

However, as pointed out above, it is required for `pj_init_plus` etc.

**Comment by kbevers** [comment]
Just tried to recreate this issue with no luck. Closing since is most likely was a issue with the specific system setup.
