### ISSUE TITLE
Failed to load NULL datum file

### ISSUE THREAD

**Issue by Fuzl** [OSGeo/PROJ#335]
Hello to all,
On a x86 OSGEO4W setup, I have datum grid problems in QGIS and it seems to come from proj :
When I try : 

> ogr2ogr -f "ESRI Shapefile" -s_srs IGNF:LAMBE -t_srs EPSG:2154 test.shp mylayer.shp

I get :

> pj_open_lib(IGNF): call fopen(C:\OSGeo4W\share\proj\IGNF) - succeeded
> pj_open_lib(ntf_r93.gsb): call fopen(C:\OSGeo4W\share\proj\ntf_r93.gsb) - succeeded
> NTv2 FRANCE   156x111: LL=(-5.5,41) UR=(10,52)
> pj_open_lib(null): call fopen(C:\OSGeo4W\share\proj\null) - failed
> ERROR 1: failed to load datum shift file
> Failed to reproject feature 0 (geometry probably out of source or destination SRS).
> ERROR 1: Terminating translation prematurely after failed translation of layer mylayer (use -skipfailures to skip errors)

The IGNF:LAMBE definition is :

> +proj=lcc +nadgrids=ntf_r93.gsb,null +a=6378249.2000 +rf=293.4660210000000 +pm=2.337229167 +lat_0=46.800000000 +lon_0=0.000000000 +k_0=0.99987742 +lat_1=46.800000000 +x_0=600000.000 +y_0=2200000.000 +units=m +no_defs

Additionnally, when I change the definition with the following (removing null datum grid file), it works (no errors) :

> +proj=lcc +nadgrids=ntf_r93.gsb +a=6378249.2000 +rf=293.4660210000000 +pm=2.337229167 +lat_0=46.800000000 +lon_0=0.000000000 +k_0=0.99987742 +lat_1=46.800000000 +x_0=600000.000 +y_0=2200000.000 +units=m +no_defs

It seems weird to me that proj cannot open the null datum shift file... Any ideas ?
PROJ4 version is 492.
Thanks,
Cev.

**Comment by volvo850fahre** [comment]
Hello,
I think this might be windows specific problem. Do you have a file named null in the C:\OSGeo4W\share\proj\ folder? I have version 4.9.3 installed and have that file in the folder. 
I tried
`ogr2ogr -f "ESRI Shapefile" -s_srs IGNF:LAMBE -t_srs EPSG:2154 test.shp ~/gis.osm_water_a_free_1.shp` 
(with a sample .shp file) and got no errors. 

Greetigs, 
Jonas.

**Comment by Fuzl** [comment]
Thanks for your answer Jonas, indeed the null file was missing and adding it solved the problem.
