### ISSUE TITLE
static builds allowed on windows for export, but for import needs to not have __declspec(dllimport) defined

### ISSUE THREAD

**Issue by vautieri** [OSGeo/PROJ#3353]
The code here below would allow one to import a static build on windows by having __declspec(dllimport) commented out.  I believe you need another flag to have an empty define PROJ_DLL.  I'm assuming you want to support import and export of both a shared and static lib being you can create both, not import because no way exists to not import (__declspec(dllimport))

```
#ifndef PROJ_DLL
#  if defined(_MSC_VER)
#    ifdef PROJ_MSVC_DLL_EXPORT
#      define PROJ_DLL __declspec(dllexport)
#    else
#      define PROJ_DLL /*__declspec(dllimport)*/
#    endif
#  elif defined(__GNUC__)
#    define PROJ_DLL __attribute__ ((visibility("default")))
#  else
#    define PROJ_DLL
#  endif
#endif
```

**Comment by rouault** [comment]
The commit message of 6e9b324ab7bf5909df7e68409e060282db14fa54 should answer your question
