### ISSUE TITLE
Deal with datum files spanning dateline

### ISSUE THREAD

**Issue by hobu** [OSGeo/PROJ#336]
The case where datum files that span the dateline is not handled. I think the most reasonable solution might be to simply make sure that gtx files that are provided by the project (in the proj-datum packages or whatever) are split. Otherwise, we're kind of stuck.

```
GTX 4201x2041: LL=(-130,24) UR=(-59.9999999,58)
pj_open_lib(g2003alaska.gtx): call fopen(/usr/local/Cellar/proj/4.9.2/share/proj/g2003alaska.gtx) - succeeded

This GTX spans the dateline!  This will cause problems.
GTX 3721x1381: LL=(172,49) UR=(234,72)

```

**Comment by rouault** [comment]
Splitting grids is a solution, but I think support for grids spanning dateline could be added. This would require changes in the following places:
https://github.com/OSGeo/proj.4/blob/master/src/pj_apply_gridshift.c#L149
https://github.com/OSGeo/proj.4/blob/master/src/pj_apply_gridshift.c#L168
https://github.com/OSGeo/proj.4/blob/master/src/pj_apply_gridshift.c#L196
https://github.com/OSGeo/proj.4/blob/master/src/nad_cvt.c#L15
https://github.com/OSGeo/proj.4/blob/master/src/nad_cvt.c#L57
