### ISSUE TITLE
cs2cs man page should be maintained in its original nroff format

### ISSUE THREAD

**Issue by jidanni** [OSGeo/PROJ#337]
https://github.com/OSGeo/proj.4/wiki/Mancs2cs should be maintained in its original nroff format. It should say CS2CS(1) on its corners. And should have an updated URL at bottom, and have a BUGS section.

**Comment by micahcochran** [comment]
I've done all of those changes with the exception of adding a BUGS section.  I have submitted a pull request.

**Comment by micahcochran** [comment]
PR #382 has been merged.  Closes this issue.
