### ISSUE TITLE
-v, -V should delve deeper into "utm"

### ISSUE THREAD

**Issue by jidanni** [OSGeo/PROJ#339]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=809628
-v, and -V go into a lot of detail. But they should also at the same time mention that e.g.,
+proj=utm   +lon_0=123
is equivalent to
+proj=tmerc +lon_0=123 +x_0=500000 +k=0.9996
else even looking at the documents,
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=809630
one would never know!

**Comment by kbevers** [comment]
That would be very cool, but would be quite difficult, if not impossible, to facilitate with the current infrastructure in proj.4.
