### ISSUE TITLE
 mention if any two runs of cs2cs can always be rewritten into one run or not

### ISSUE THREAD

**Issue by jidanni** [OSGeo/PROJ#340]
On the cs2cs man page, please mention if any two runs of cs2cs
$ cs2cs ... +to ...|cs2cs ... +to ...
can always be rewritten into one run, or if instead that is sometimes
not possible.

**Comment by micahcochran** [comment]
This appears to be entirely possible:

```
$ echo -e "-87\t35" | cs2cs +init=epsg:4326 +to +init=epsg:3309 | cs2cs +init=epsg:3309 +to +init=epsg:4326
87dW    35dN 0.000
```

I can see perhaps using this for testing.  Are there other applications?
