### ISSUE TITLE
Overlapping strcpy in rtodms.c

### ISSUE THREAD

**Issue by hannob** [OSGeo/PROJ#350]
In rtodms.c there is a strcpy call that can affect overlapping memory areas. This is not allowed by C and can lead to undefined behavior.

To test this one can compile with address sanitizer and run make check (add "-fsanitize=address" to CFLAGS/LDFLAGS).

Alternatively you can use memmove, which allows overlapping memory areas.

Patch:

```
--- a/src/rtodms.c  2015-09-11 01:19:07.000000000 +0200
+++ b/src/rtodms.c  2016-02-08 12:04:10.187056504 +0100
@@ -63,7 +63,7 @@
        if (*p != '.')
            ++p;
        if (++q != p)
-           (void)strcpy(p, q);
+           (void)memmove(p, q, strlen(p));
    } else if (min)
        (void)sprintf(ss,"%dd%d'%c",deg,min,sign);
    else
```

**Comment by rouault** [comment]
Has already been fixed in master by 90e393396d0aad7f504b21bc25f87326d044da63
