### ISSUE TITLE
Cannot install, configure script is missing.

### ISSUE THREAD

**Issue by statguy** [OSGeo/PROJ#352]

**Comment by rouault** [comment]
You have to run the ./autogen.sh script to generate configure and makefiles.

**Comment by statguy** [comment]
Ok thanks, there is no mention in README or in INSTALL however.

**Comment by rouault** [comment]
Indeed . I've opened #353 for that. Contributions welcome

**Comment by dwschulze** [comment]
Running ./autogen.sh gives this error:

$ ./autogen.sh 
Running aclocal
./autogen.sh: 29: ./autogen.sh: aclocal: not found

  Something went wrong, giving up!

**Comment by hobu** [comment]
As the error message notes, you don't have aclocal installed.
