### ISSUE TITLE
Update documentation to reflect removal of configure / cmake

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#353]
The doc is out-dated regarding the build.

**Comment by QuLogic** [comment]
As another note; `configure` _should_ exist in the distribution tarballs (e.g., if built with `make dist`.) It just won't exist in the git repository.

**Comment by micahcochran** [comment]
Here's the equivalents.
Autoconf version:
`./configure --prefix=/my/path`
CMake's equivalent:
`cmake -DCMAKE_INSTALL_PREFIX=/my/path .`

It might not be bad to mention `./autogen.sh` for people downloading the github development version.

**Comment by dwschulze** [comment]
What are the new instructions for building the jni layer?

**Comment by kbevers** [comment]
This is reflected in the README now.
