### ISSUE TITLE
updates to the geodesic(3)

### ISSUE THREAD

**Issue by cffk** [OSGeo/PROJ#354]
proj version 4.9.2 incorporates the geodesic library from GeographicLib
1.44.  I'd like to upgrade it to the latest GeographicLib version, 1.46.
Here are the changes:

Version 1.45 http://geographiclib.sourceforge.net/1.45/C
- This fixes the bug where the solution of the inverse problem with nan
  and a point on equator did not return all nans.  This is illustrated
  by the following call to geod (version 4.9.2)
  
  ``` bash
  $ echo 91 0 0 90 | geod +ellps=WGS84 -I -f %.5f
  90.00000 -90.00000 10018754.171
  ```
  
  This should return "nan nan nan", since latitude 91&deg; is treated as a
  nan.
- A test suite is included.
- Add geod_polygon_clear().

Version 1.46 http://geographiclib.sourceforge.net/1.46/C
- More accurate inverse solution when longitude difference is close to
  180&deg;.
- Add s13 and a13 to the geod_geodesicline struct.
- Add geod_directline, geod_gendirectline, and geod_inverseline.

The last two changes in 1.46 simplify the process of generating
waypoints on a geodesic specified by its endpoints.

The changes in 1.45 and and 1.46 are both source-code compatible with
1.44.  However, version 1.46 requires an increment to the proj library
version, since the geod_geodesicline struct has increased in size.

So the question is: should I upgrade just to 1.45 (no change in library
version) or should I go all the way to 1.46 (which will require a change
in library version)?

My recommendation would be to opt for the full upgrade unless a release
is anticipated in the next month or so.

**Comment by hobu** [comment]
I am planning to issue a 4.9.3 release candidate during the [OSGeo Paris Code Sprint](https://wiki.osgeo.org/wiki/Paris_Code_Sprint_2016) next week. I don't know if any one else was going to tackle proj.4 issues next week. I see no reason why you can't go to 1.46 and increment the soversion'ing as necessary in support of it.

**Comment by cffk** [comment]
Done!  See pull request #355
