### ISSUE TITLE
Possible bug in RGDAL implementation of Proj.4 for azimuthal equidistant projections?

### ISSUE THREAD

**Issue by geotheory** [OSGeo/PROJ#357]
Possibly not a Proj.4 issue, but it may be I'm not sure.  Projections with "+proj=aeqd" all come out skewed, and wrap around when they should project outwards from azimuth.  Full details here on [StackOverflow](https://stackoverflow.com/questions/35565796/equidistant-azimuthal-projection-anomalies).

**Comment by QuLogic** [comment]
With what version of Proj.4? I'm pretty sure this is related to #246, which is fixed in 4.9.2.

**Comment by geotheory** [comment]
Thanks @QuLogic, I'm on 4.9.1, which looks like is the most recent version available using rgdal.
