### ISSUE TITLE
Old TRAC Wiki pages

### ISSUE THREAD

**Issue by micahcochran** [OSGeo/PROJ#367]
So the old wiki (TRAC) is  https://trac.osgeo.org/proj/wiki    and its landing page points to the wiki here on github... https://github.com/OSGeo/proj.4/wiki

However, all the pages within TRAC do not have similar messages pointing to the new content.  You can search for something PROJ.4 related and a TRAC wiki  page will come up as one of the results.  Also, there are old hyperlinks everywhere pointing to the TRAC wiki.  At this point the Github wiki really doesn't have that much new content, but over time there could be some updates.

I think that it would be best if the pages on TRAC would have a link to the appropriate github wiki pages.  Perhaps a message near the top in bold that says:  "This content has been moved to Proj.4's Github wiki." with a link to that page on GH.

Any thoughts or problems?

**Comment by hobu** [comment]
I'd like to see us moving all content to the http://proj4.org website, and updating all the pointers on the trac and github wikis to point at those docs. 

When we are confident all of the content is moved from the trac wiki into the docs, I will update an HTTP redirect to point the trac website to proj4.org.

I'd like all of the wiki pages to go away and have the content be in the Sphinx documentation set. We can then generate PDF and other output types easily from that.

Make sense?

**Comment by micahcochran** [comment]
@hobu  that sounds like a great idea.  Thanks for explaining.
