### ISSUE TITLE
Add the Natural Earth II projection

### ISSUE THREAD

**Issue by beuan** [OSGeo/PROJ#369]
It would be nice to get support for [the Natural Earth II projection](http://www.shadedrelief.com/NE2_proj/).

The [reference implementation](https://github.com/OSUCartography/JMapProjLib/blob/master/src/com/jhlabs/map/proj/NaturalEarth2Projection.java) can be found in the [Java Map Projection Library's GitHub repository](https://github.com/OSUCartography/JMapProjLib).

The forward projection is

x = lon \* (0.84719 - 0.13063 \* lat^2 + lat^12 \* (-0.04515 + 0.05494 \* lat^2 - 0.02326 \* lat^4 + 0.00331 \* lat^6))

y = lat\* (1.01183 + lat^8 \* (-0.02625 + 0.01926 \* lat^2 - 0.00396 \* lat^4))

Research paper about the projection is available [here](http://cartography.oregonstate.edu/pdf/2016_Savric_etal_NaturalEarthII.pdf).

**Comment by beuan** [comment]
Attached is code for the Natural Earth II projection for addition to PROJ.4 by @berniejenny
[PJ_natearth2.zip](https://github.com/OSGeo/proj.4/files/192665/PJ_natearth2.zip)

**Comment by QuLogic** [comment]
Why not make a Pull Request?
