### ISSUE TITLE
Add the Compact Miller projection

### ISSUE THREAD

**Issue by beuan** [OSGeo/PROJ#370]
It would be nice to get support for the Compact Miller projection.

The [reference implementation](https://github.com/OSUCartography/JMapProjLib/blob/master/src/com/jhlabs/map/proj/CompactMillerProjection.java) can be found in the [Java Map Projection Library's GitHub repository](https://github.com/OSUCartography/JMapProjLib).

The Compact Miller is cylindrical projection described in this paper: http://cartography.oregonstate.edu/pdf/2015_Jenny_etal_ACompromiseAspect-adaptiveCylindricalProjectionForWorldMaps.pdf

Attached is code for addition to PROJ.4 by @berniejenny

Below are a few test points for both projections.

(From the Proj.4 mailing list post: http://lists.maptools.org/pipermail/proj/2015-February/007031.html)

[PJ_comill.zip](https://github.com/OSGeo/proj.4/files/192674/PJ_comill.zip)

Compact Miller (lon, lat, 0, X, Y):

0 0.0 0 0.0 0.0
0 22.5 0 0.0 2537439.6610749415
0 45.0 0 0.0 5391682.432264133
0 67.5 0 0.0 8661480.510260897
0 90.0 0 0.0 1.2009484264916677E7
45 0.0 0 5003778.588046594 0.0
45 22.5 0 5003778.588046594 2537439.6610749415
45 45.0 0 5003778.588046594 5391682.432264133
45 67.5 0 5003778.588046594 8661480.510260897
45 90.0 0 5003778.588046594 1.2009484264916677E7
90 0.0 0 1.0007557176093187E7 0.0
90 22.5 0 1.0007557176093187E7 2537439.6610749415
90 45.0 0 1.0007557176093187E7 5391682.432264133
90 67.5 0 1.0007557176093187E7 8661480.510260897
90 90.0 0 1.0007557176093187E7 1.2009484264916677E7
135 0.0 0 1.501133576413978E7 0.0
135 22.5 0 1.501133576413978E7 2537439.6610749415
135 45.0 0 1.501133576413978E7 5391682.432264133
135 67.5 0 1.501133576413978E7 8661480.510260897
135 90.0 0 1.501133576413978E7 1.2009484264916677E7
180 0.0 0 2.0015114352186374E7 0.0
180 22.5 0 2.0015114352186374E7 2537439.6610749415
180 45.0 0 2.0015114352186374E7 5391682.432264133
180 67.5 0 2.0015114352186374E7 8661480.510260897
180 90.0 0 2.0015114352186374E7 1.2009484264916677E7

**Comment by micahcochran** [comment]
I'm just repeating what @QuLogic  said about NaturalEarth2.   Why not fork the code and submit a Pull Request?
