### ISSUE TITLE
GIGS testing

### ISSUE THREAD

**Issue by micahcochran** [OSGeo/PROJ#374]
I got a few of the [Geospatial Integrity of Geoscience Software GIGS testing](http://www.iogp.org/Geomatics#2521115-gigs) 51xx series working this weekend using pyproj.  The results were pretty promising.  Most all of the tests passed.  These could be used for coverage tests.  A few failed, but it might be a good opportunity look at what is going wrong.  (It might even be pyproj or Python related.)

These will be a little bit harder to get working in only Proj.4.  Some Python code should be able to be leveraged in some manner.

The 51xx series of is basically tables of points in lat/long (in many various definitions with WGS 84 only being used once) and projected northings/eastings (or southings/westings).  The results are  compare the results that within an error range of at most 50 mm or 0.002 seconds. The first test is a single conversion.  The other does 1000 roundtrips.

Projections that are tested by 51xx series tests:  aea, cass, laea, lcc, merc, omerc, somerc, sterea, tmerc, and utm.

**Comment by micahcochran** [comment]
GIGS testing is more extensive testing than is in the current Proj.4 test suite for these few projections that are tested.

I converted the Excel spreadsheets into csv.   Then, I used python code to convert the extend the testing for GIGS. 

The only test fails is test 5102 part 2.  This is a Lambert Conic Conformal (1SP) projection.  This is converting between EPSG:4807 and EPSG:27572. Both projections set the prime meridian to paris.  I haven't done much investigation to try to understand why it fails.

Everything else looks like rounding errors.  I did try to change to floor rounding, but that didn't quite work either.

The test suite in PR #373 will work better for this type of testing because it uses a numeric tolerance instead of using rounding.  There is also a 1,000 round trip test that is prescribed by GIGS 51xx, which could be added in the future.  My initial pyproj tests showed fairly good results.

I've added [gigs branch](https://github.com/micahcochran/proj.4/tree/gigs) with the files [nad/testgigs](https://github.com/micahcochran/proj.4/blob/gigs/nad/testgigs) and [nad/tg_out.dist](https://github.com/micahcochran/proj.4/blob/gigs/nad/tg_out.dist)

If you run it, I suggest using a tool like [Meld](http://meldmerge.org/) or [icdiff](https://github.com/jeffkaufman/icdiff) that provides a side-by-side comparison with coloration to highlight the difference between the files.

I want to get this done so that there might be an option for me to clean this up for merging before PR #373, if desired.  Or it might be better to commit this after using the new test suite.

**Comment by busstoptaktik** [comment]
I may be missing something here, but I do not see any evident reason to merge this before #373: The internal self test in #373 is included as a safety measure due to some really intrusive code surgery with a high risk of swapping or misplacing arguments (although the infrastructure can also be used for more extensive testing).

Having GIGS supported is of value by itself: It ensures that proj passes a standardized test, which is a good thing.

So I think merging one or the other first doesn't matter - I believe both efforts add to the confidence in libproj.

On a related note, I would find it awesome to define a test file format for proj, including both forward and inverse point expectations, such that one could extend the internal self test with a syntax something like  proj -VC testfile.1 testfile.2 etc.

Anyways - I think that your work om GIGS and my work on refactoring are related in their goal of making libproj a better libproj, but otherwise orthogonal, and can be merged in any order (as you also hint at in the last sentence above)

**Comment by micahcochran** [comment]
> On a related note, I would find it awesome to define a test file format for proj, including both forward and inverse point expectations, such that one could extend the internal self test with a syntax something like proj -VC testfile.1 testfile.2 etc.

I converted the GIGS Excel files to a CSV format, but I think that would be a nightmare to actually maintain it in that format.  I'm a little partial to a JSON format because it should be easy to make it work in other software, but still be fairly easy to edit.  There are [lots of choices](http://www.json.org/) of external JSON parsing libraries, but that would add an additional dependency.

> Anyways - I think that your work om GIGS and my work on refactoring are related in their goal of making libproj a better libproj, but otherwise orthogonal, and can be merged in any order (as you also hint at in the last sentence above)

I agree.  Do not hold up merging the refactoring that @busstoptaktik is doing for this.  The refactoring is necessary work.

**Comment by hobu** [comment]
If the GIGS Excel files are maintained in .xlsx format, We can easily consume them with Python without having to do a format change. I don't know that this matters, but I thought I'd throw that out there...

**Comment by micahcochran** [comment]
They are actually .xls files.  When I first started on this I tried using them directly.  The files are not that uniform.  The Excel files do no contain the amount of error tolerance.  I've written (hackish) code for parsing for the CSV files and exporting to a JSON file.

Here is an example JSON test:

``` json
{
"description": "Test 5113, Transverse Mercator (South Oriented), v2-0_2011-06-28.", 
"projections": ["+init=epsg:4148", "+init=epsg:2049"], 
"coordinates": [ [[22.5, 0.0], [-166998.44, 0.0]], 
                 [[21.5, -25.0], [-50475.46, 2766147.25]], 
                 [[20.5, -30.0], [48243.45, 3320218.65]], 
                 [[19.5, -35.0], [136937.65, 3875621.18]], 
                 [[19.5, -35.0], [136937.65, 3875621.18]]
               ], 
"tests": [{"tolerances": [2.7777777777777776e-07, 0.03], "type": "conversion"}, 
          {"times": 1000, "tolerances": [5.555555555555556e-08, 0.006], "type": "roundtrip"}]
}
```

Just to quickly explain the elements of the test.  There is a `description` of the test.  There are two proj4 style `projections` strings.  There are two types of `tests`: a simple conversion within a specified tolerance, and a number of roundtrips.  The `coordinates` pairs with the left ones goes with the left projection.  The right ones goes with the right projection.  For example the [22.5, 0.0] coordinate is related to projection "+init=epsg:4148".

I chose to use Decimal Degrees (DD), but the tests do contain Degree Minute Second (Sexagesimal degrees) format, which is GIGS seems to prefer DMS for the human interface. (See [Geospatial Integrity of Geoscience Software Part 3 - User guide for GIGS Test Dataset](http://www.iogp.org/pubs/430-3.pdf).  Appendix 5 - Precision and presentation. Electronic page 79, paper page 71.)  There are a few places mentions of where it has to be noted if DD is used over DMS.

Many languages make parsing and accessing JSON data really easy, including Python and Javascript.

I'm using python and using pyproj with good results.  Currently, about 90% of the tests pass (this is up from 60% before I got the tolerances correct.).  The failures could be that the numbers do not contain enough precision since I'm using Decimal Degrees.  I've thought about calling `cs2cs` from Python, but I haven't got a good handle on using subprocess.

The current tests that do not match, I am reporting the farthest outlier, NOT the average:
- 5101 part 1, Transverse Mercator  there are two different formulas JHS (recommended) and USGS.  both has discrepancies of about 36 meters with 100 round trips, part 4 I tested JHS and had a discrepency of 17 meters with 1000 round trips.
- the above mentioned 5102 part 2 (which some results are off up to 5 km), which the conversion and the roundtrip had failures.
- Test 5108 Cassini-Solder is up to 56 meters off with the 1000 round trips.
- Test 5110, Lambert Azimuthal Equal Area is up to 0.4 meters off with 1000 round trips.

There are a few more tests that should be converted that need a little bit of manual conversion.

I need to clean up my code to get it ready for review.

**Comment by busstoptaktik** [comment]
Regarding Transverse Mercator: are you using the high precision etmerc implementation, or the slightly faster, but less precise, original tmerc version?

**Comment by cffk** [comment]
etmerc will be used in the next release (and this is the checked in version).

**Comment by busstoptaktik** [comment]
I am aware of that, but I am not sure whether Micah is running the tests on the latest release or the development version

**Comment by micahcochran** [comment]
I was using tmerc for GIGS test 5101 part 1.  I switched the projection from tmerc to etmerc and the test passed.    The 5101 part 2 test is EPSG CRS code 32631, which is a UTM projection.   I must have updated to the pyproj repository (which is about 5 months ago) because now it completely matches.   Good detective work guys!

Another of the 5101 tests, part 4 use EPSG CRS code 22175 has 65 matches and 27 non-matches.  So I used `+init=espg:22175` as the proj4 string.
from nad/epsg:

```
# POSGAR 98 / Argentina 5
<22175> +proj=tmerc +lat_0=-90 +lon_0=-60 +k=1 +x_0=5500000 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs  <>
```

However if I use the EPSG 22175 proj4 parameter and replace it with etmerc, and the tests passed (92 matches). 

This is probably a complicated question: Should the epsg definitions default to using etmerc?

I can see the need to release something sooner for everyone interested to take a look at.

**Comment by busstoptaktik** [comment]
> This is probably a complicated question: Should the epsg definitions default to using etmerc?

Strictly speaking, I believe the proper solution will be to rename what is now known as tmerc, to stmerc (indicating its John Snyder heritage), and renaming etmerc to tmerc

This will give the best available algorithm the most obvious name, and provide the stmerc loophole for people needing the Snyder version for backwards "less precision compatibility".

I am, however, sure that there are mixed opinions about this

**Comment by hobu** [comment]
> Strictly speaking, I believe the proper solution will be to rename what is now known as tmerc, to stmerc (indicating its John Snyder heritage), and renaming etmerc to tmerc

👍

**Comment by rouault** [comment]
For backward compatibility, I'd suggest not to remove etmerc, but make etmerc and tmerc aliases.

**Comment by busstoptaktik** [comment]
@rouault: yes - that is really a much better solution (and requires only a few additional lines of code).

**Comment by micahcochran** [comment]
Here's what work I've done so far.  All of what I have is in my [py-gigs branch under the folder test/gigs](https://github.com/micahcochran/proj.4/tree/py-gigs/test/gigs).

It is a python file, which is called `proj_test.py`.  This could use a better name since this implies that it might use the `proj` command, which it does not.  The python file contains installation instructions that are fairly complete, but could use some improvement.

I'm leaning towards completely refactoring the code so that it does not require pyproj.  I think I have an approach to use Python `suprocess` that should work.

There is a list of tests that do not work in [KNOWNISSUES.txt](https://github.com/micahcochran/proj.4/blob/py-gigs/test/gigs/KNOWNISSUES.txt).  I suspect the roundtrip conversion needs to be examined a little closer.

Please refer back to to the GIG [tesing material](http://www.iogp.org/Geomatics#2521115-gigs) if you suspect that there are any mistakes in the testing.  These tests are specifically dealt with in 5100 and 5200 series tests.

I need to point out in documentation that these test are based on material provided by IOGP.  They have a disclaimer message which should be included.

**EDIT**: The roundtrip test is currently incorrect. "Round trip calculations from the converted coordinates back to the original should also be tested for the point or points indicated in the input file, with final coordinates compared to the starting values. "  That last part is not currently being done.

**Comment by micahcochran** [comment]
I've updated the testing framework so it now can call cs2cs and pyproj.  Roundtrip tests now work properly.

Documentation is now in [TESTNOTES.md](https://github.com/micahcochran/proj.4/blob/py-gigs/test/gigs/TESTNOTES.md).  (I need to put the IOGP disclaimer message in the documentation.)

I'm am toying with applying this to proj4js.  Is this a testing framework that should be a part of the PROJ.4 or should this be an entirely separate project?
