### ISSUE TITLE
Load time non-computable initializers in PJ_healpix

### ISSUE THREAD

**Issue by busstoptaktik** [OSGeo/PROJ#376]
PJ_healpix.c uses a large number of non-computable initializers. Works OK with gcc, but non-portable.

Compiling with `gcc -W -Wall -Wextra -pedantic -I. -c PJ_healpix.c`
reveals 20 cases of 

"warning: initializer element is not computable at load time"

@Conzar: This code appears to be written by you. Do you mind if I clear up these warnings?

**Comment by Conzar** [comment]
@busstoptaktik please do!  What is an initializer element?
