### ISSUE TITLE
USK2000

### ISSUE THREAD

**Issue by ghost** [OSGeo/PROJ#389]
USK2000 - is national geodetic reference coordinate system of Ukraine.

Parametres:
ETRS89/ETRF2000 to USK2000

Tx=-24.376 m 
Ty=121.321 m 
Tz=75.895 m 
Rx=0.001296" 
Ry=0.007840" 
Rz=-0.012672" 
D=0

References:
- http://www.ukrinform.net/rubric-ukrnews/425420-on_january_1_2007_ukraine_is_transferring_to_a_new_geodesy_coordinate_system_usk_2000_modeled_on_the_basis_of_observations_of_the_global_positioning_system_90693.html
- http://www.kmu.gov.ua/control/en/publish/article?art_id=60680054&cat_id=244315200
- http://www.euref.eu/symposia/2008brussels/06-28-ukraineslides.pdf
- http://gki.com.ua/files/uploads/documents/Norms/Ukrgeodesykart_norms/Nakaz_23_zastosuvannia_USK_2000.pdf
- http://science.lp.edu.ua/uk/node/1695
- http://science.lp.edu.ua/uk/node/1569
- http://buksis.nethouse.ua/posts/210112
- http://www.nbuv.gov.ua/old_jrn/natural/Geodez/2013_77/20.pdf
- http://agrosoil.yolasite.com/resources/2015-AiG-84-abstr-ref-en-Cherlinka.pdf
- http://www.unoosa.org/documents/pdf/psa/activities/2010/moldova/presentations/3-4.pdf

**Comment by micahcochran** [comment]
It is a little unclear (to me at least) what you want someone to do with this information.

**Comment by kbevers** [comment]
It's not just you, Micah. I am also a little puzzled and the links doesn't help me either. The links that seem to contain some actual useful information are in a language I don't understand.

**Comment by busstoptaktik** [comment]
@Symbian9:  is this thesystem with EPSG code 1077?

**Comment by ghost** [comment]
No. As I understand, for connecting USK2000 with WGS84 need use EPSG:5822
- http://vinmap.net/book/ch09s03s02.html

Also, try look inside this
- http://gis-lab.info/forum/viewtopic.php?f=34&t=15940
- http://www.vingeo.com/update/rus/Datums.ini

**Comment by kbevers** [comment]
@Symbian9 can you link us to sources in english? Most of us won't be able to understand those texts in Ukrainian(?). Also, do you mind explaining what your motivation is for sharing all this information?

**Comment by ghost** [comment]
I want use USK2000 reference coordinate system by Proj.4 library.
Here is its description of CRS in English
- http://dgm.gki.com.ua/files/image/3261067/Description_of_CRS_UA_UCS_2000_UA_TM.pdf

So, what string for proj.4 needed? Or maybe its possible implement this in Proj.4 specification?

**Comment by kbevers** [comment]
Well, it says in your document that the projection is covered by EPSG codes 5570 to 5583. So for 5570 it is as simple as

```
proj +init=epsg:5570
```

which expand to

```
proj +proj=tmerc +lat_0=0 +lon_0=21 +k=1 +x_0=7500000 +y_0=0 +ellps=krass +towgs84=25,-141,-78.5,0,0.35,0.736,0 +units=m +no_defs
```

**Comment by ghost** [comment]
Ok, but i found something like this
<code>+towgs84=+24,-123,-94,-9.69E-7,1.212E-6,+6.3E-7,+1.1E-6</code>
Taked it from here.
- http://zemres.com/forum/viewtopic.php?f=13&t=24&start=100

And here is map with USK2000 (check box with "УСК2000")
- http://dgm.gki.com.ua/map

**Comment by busstoptaktik** [comment]
You could start by checking whether it makes any difference at the
precision level you need, by running a number of relevant test coordinates
through both sets of towgs parameters.

You have not given any details about your needs, which makes it very hard
to help you.

Please provide all relevant details, including preferably a test point
coordinate, when asking for help. It will significantly increase the chance
that anyone will be able to help you
Den 13/06/2016 00.30 skrev "Symbian9" notifications@github.com:

**Comment by ghost** [comment]
http://gis.stackexchange.com/questions/171507/ukrainian-topographic-map-projection-and-coordinates
