### ISSUE TITLE
Set failure limits for coveralls

### ISSUE THREAD

**Issue by kbevers** [OSGeo/PROJ#393]
At the moment even the slightest negative change in test coverage makes coveralls fail. Most pull request seem to be failing even though travis/appveyor is fine. Almost always because test coverage decreased by 0.001% (or even less). I suggest that we set the coverage decrease failure threshold on coveralls to 0.5 %. This way coveralls won't fail when making small changes to existing code, but should still reveal missing tests for new code.

It might also be preferable to turn of coveralls comments as they create a lot of noise i long running pull requests. Test coverage is still summed up in the check overview.

@hobu can you make this change?

**Comment by rouault** [comment]
@kbevers I've modified the settings to implement your 2 suggestions. Hope that will work

**Comment by kbevers** [comment]
Thanks, Even.
