### ISSUE TITLE
Add ellipsoidal orthographic projection

### ISSUE THREAD

**Issue by kbevers** [OSGeo/PROJ#397]
As mentioned by Noel Zinn on the mailing list, the orthographic projection is only implemented in the spherical case. In the pdf below Noel describes the ellipsoidal orthographic projection.
[
http://www.hydrometronics.com/downloads/Ellipsoidal%20Orthographic%20Projection.pdf](http://www.hydrometronics.com/downloads/Ellipsoidal%20Orthographic%20Projection.pdf)

PJ_ortho.c should be updated accordingly.

**Comment by Felix-neko** [comment]
Still nobody implemented it? It would be an extreamely great and useful feature, especially in radar modeling software... And for calculating ballistic and space trajectories too...

**Comment by kbevers** [comment]
> Still nobody implemented it? It would be an extreamely great and useful feature, especially in radar modeling software... And for calculating ballistic and space trajectories too...

No. If this is important to you, you can always do it yourself. I am happy to help you with that. If that is not an option to you, I am sure we can find a developer who would do the work for if you are willing to pay for the hours put into this.

**Comment by carbonox-infernox** [comment]
Seems like the gnomonic projection is also spherical based on my tests here:
[https://github.com/pyproj4/pyproj/issues/388](url)
