### ISSUE TITLE
"Major axis or radius=0 or not given"

### ISSUE THREAD

**Issue by ghost** [OSGeo/PROJ#398]
I now try use <code>+proj=tpers</code> in OpenOrienteering Mapper
- https://github.com/OpenOrienteering/mapper/issues/722

But when try input it in "Custom PROJ.4" field it give me a message:
<code>Major axis or radius=0 or not given</code>

I use Trusty i386 build of Proj.4 from launchpad, so where and how problem can be fixed?

References:
- https://github.com/Homebrew/legacy-homebrew/issues/439
- https://launchpad.net/ubuntu/trusty/i386/libproj0

**Comment by kbevers** [comment]
You need to at least set the height parameter (+h) for proj to be able to output anything. See this for more info: https://trac.osgeo.org/proj/wiki/proj%3Dtpers

**Comment by ghost** [comment]
Think problem was in not included <code>+ellps=WGS84</code>
