### ISSUE TITLE
VB Wrappers from Eric G. Miller

### ISSUE THREAD

**Issue by yportier** [OSGeo/PROJ#414]
The link to the [PROJ.4 VB Wrappers](http://ftp.dfg.ca.gov/Public/BDB/Tools/proj4/proj_api.zip) from Eric G. Miller in the [Home Page](https://github.com/OSGeo/proj.4/wiki) of the wiki is broken.

**Comment by kbevers** [comment]
Any idea what the proper link is? Is it even maintained anymore? I suspect not many are using VB these days...

**Comment by micahcochran** [comment]
The link seems to be working for me.

**Comment by yportier** [comment]
Not sure if it is useful to many people but I was looking to use proj4 from Excel (I know that probably sounds dirty) and I thought that maybe a good starting point. Anyway, the link is still broken to me :-(

**Comment by kbevers** [comment]
@yportier Have a look at [proj.xll](https://github.com/jbuonagurio/proj.xll) that was just announced by @jbuonagurio
