### ISSUE TITLE
Link to download for release

### ISSUE THREAD

**Issue by matzeri** [OSGeo/PROJ#416]
GitHub is allowing the download of releases at 
https://github.com/OSGeo/proj.4/releases

however these files are much larger, and with different structure, than those available at 
http://download.osgeo.org/proj/

To avoid confusion it will be proper to show an advise on
https://github.com/OSGeo/proj.4/releases
that forwards to
http://download.osgeo.org/proj/

Something like 
https://github.com/FFTW/fftw3/releases

**Comment by kbevers** [comment]
Thanks for your suggestion @matzeri. Since no one has shown their support for this I take it that this is not really something the users of proj.4 needs. Personally I prefer to keep the thing we need to update at new releases to a minimum.
