### ISSUE TITLE
Configuration errors on CENTOS Knights Landing system

### ISSUE THREAD

**Issue by dbh441** [OSGeo/PROJ#424]
The proj.4 distribution that I downloaded has a configure.ac file, but no configure file.  So I installed autoconf 2.69 and ran it to get a configure file, with the following messages:

configure.ac:9: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.

Not surprisingly, the configure file it produced terminated with errors:

[dbh@localhost proj.4-master]$ ./configure --prefix=${SW4ROOT}
./configure: line 2186: AM_INIT_AUTOMAKE: command not found
./configure: line 2187: syntax error near unexpected token `src/proj_config.h'
./configure: line 2187:`AM_CONFIG_HEADER(src/proj_config.h)'

Now I am trying to figure out m4_pattern_allow, but would appreciate guidance if this is a trivial issue.

**Comment by kbevers** [comment]
The canonical way of building proj.4 is:

```
./autogen.sh
./configure
make
make install
```

I am not entirely sure if you did the first step. If you did run `autogen.sh` we'll have to look into this. 

Either way the build process should be documented more clearly!

**Comment by dbh441** [comment]
Kristin:

  Thanks for your response.

  I downloaded the development version of proj.4 instead of the
distribution.  My mistake.  I have since downloaded the distribution and am
working to build it, with more success (I am a newbie and still learning to
set up the compilation and linking environment correctly on this new
machine).

Dave Harris
