### ISSUE TITLE
src/PJ_healpix.c calls fabsl() but doesn't include <math.h> / fabsl() is non-portable

### ISSUE THREAD

**Issue by rklrkl** [OSGeo/PROJ#426]
There are several calls to the maths routine fabsl() in src/PJ_healpix.c, but the <math.h> include file isn't included to define it.

Also note that alhough fabsl() is in the maths library on Linux systems, it isn't present in math libraries on some other non-Linux sytems (e.g. PA-RISC HP-UX).

A workaround for PA-RISC HP-UX (which does have fabs() at least) for example might be:
# ifdef __hpux
# include <math.h>
# ifndef __ia64
# define fabsl(x) (long double)fabs((long double)(x))
# endif
# endif

Ideally, though, fabsl() should be tested for existence via the configure script and the fallback I've mentioned used based on, say, HAVE_FABSL not being defined as 1.

**Comment by rouault** [comment]
A simpler fix would probably to just use fabs() instead of fabsl() since we don't use the double long type in the code but just plain double. Want to submit a PR for this ?
