### ISSUE TITLE
Copyright tag is deprecated

### ISSUE THREAD

**Issue by volvo850fahre** [OSGeo/PROJ#429]
Hello, 

The Copyright tag is deprecated. Use the License tag instead, as detailed in https://en.opensuse.org/openSUSE:Packaging_guidelines#Licensing 

So the copyright tag should be replaced with:
License:  MIT, Copyright (c) 2000, Frank Warmerdam

Thank you very much!

**Comment by kbevers** [comment]
Thank you for taking care of this.
