### ISSUE TITLE
Improve comments in projects.h

### ISSUE THREAD

**Issue by busstoptaktik** [OSGeo/PROJ#433]
Pull request #431 introduces a large number of descriptive comments in projects.h. A number of potential improvements do, however, remain. They are marked up with "TODO: Description needed", but are related to some rather convoluted parts of the code base, so explaining them compactly is a nasty task.

I _do_ volunteer to do this, but probably need some help from e.g. @warmerdam

**Comment by kbevers** [comment]
`projects.h` is no more. Partly replace by `proj_internal.h`. There's not much left to track in this issue, so I am closing it. Feel free to reopen if I am in the wrong here.
