### ISSUE TITLE
geogrids functionality not documented

### ISSUE THREAD

**Issue by czka** [OSGeo/PROJ#441]
I learnt from PROJ.4 ML archives that PROJ.4 has supported vertical datum transformation grids via +geogrids for several years now. PROJ.4 wiki pages (https://github.com/OSGeo/proj.4/wiki/GenParms, https://trac.osgeo.org/proj/wiki/GenParms) don't mention this. Probably the `GTX -raster- (rw+v): NOAA Vertical Datum .GTX` GDAL format is involved, as per https://trac.osgeo.org/proj/wiki/VerticalDatums.

**Comment by kbevers** [comment]
This is mentioned in the docs for the next release.
