### ISSUE TITLE
Improve const-ness of pointers to PJ objects

### ISSUE THREAD

**Issue by busstoptaktik** [OSGeo/PROJ#446]
Many functions taking a pointer to a PJ as argument do not use const PJ * (or const projPJ) in the function header even though they do not modify the object pointed to (cf. e.g. the majority of functions in pj_ctx.c).

Since const-ness is a contract that can be verified by the compiler, we may get some improved long term safety by being more explicit about when const-ness could be assumed by the caller.

Can anyone see any downsides to adding this, where applicable?

**Comment by busstoptaktik** [comment]
@kbevers, you have introduced some `const` improvements recently, and charted some reasons why `const`-accountability is hard to obtain. Please close this issue, if you believe it to be "as done as cen reasonably be expected"

**Comment by kbevers** [comment]
It's hard to really have ``const PJ*`` because of ``PJ->last_errno``. There's also the ``PJ_CONTEXT->last_errno``, but I am not sure if that can be changed or not when accessing it through a ``const PJ*``. If that is allowed we might be able to work around the error numbers and make the `PJ*`'s more constant. Otherwise I'd say it's about as good as it gets now.

**Comment by busstoptaktik** [comment]
@kbevers, iirc, I introduced the last_errno field in PJ quite recently, but after the discussion with you and @rouault about the OBS_API, where we ended up giving contexts a more prominent role in the API, I think it is by and large superfluous.

Personally, I would, as you know, prefer to do all error messaging through the thread local errno, but as the context->last_errno, for mostly historical reasons, is there, and since it has been used for years, perhaps we should revert to using only that, and remove PJ->last_errno, which has never been alive in a released version.

So perhaps, we really should eliminate PJ->last_errno and, while at it, simplify error messaging/handling by changing the function type of the PJ->pfree function pointer to fit with the error-message supporting function `static void *pj_freeup_msg_plain (PJ *P, int errlev)` from `pj_malloc.c`.

This would improve error messaging, and allow us to drop most of the deallocation code in the PJ_*.c files (a significant simplfication).

But it comes at the cost of having to visit every single PJ_xxx.c file, for a few patches. Probably a day's utterly boring work for one of us, or an afternoon's if we collaborate.

Any opinion about this?

**Comment by kbevers** [comment]
Lead the way and I'll gladly spend an afternoon ini boredom on this :-)

**Comment by kbevers** [comment]
@busstoptaktik 
So... where are we on this? The boring deallocation changes has been made, so it should be easier to drop `P->last_errno`, yes?

**Comment by busstoptaktik** [comment]
Agreed, but I have no immediate plans to go further... too many other things shouting louder :-)

**Comment by busstoptaktik** [comment]
... and to elaborate a bit more: it takes some time to get through this, since it must be done bottom-up, so chasing const-dependencies from the top, by setting const-ness, thereby finding the non-const dependencies, trying one by one to const them, to find their non-const dependencies.

Of course it is not turtles all the way down: after a handful of steps, you finally arrive at a function that can be const'ed by virtue of not calling other non-const functions, and probably static analyzers (splint, cppcheck, and friends - perhaps even the right combination of gcc compiler flags?), can help quite a bit finding the right place to start... I have just not started yet.

**Comment by busstoptaktik** [comment]
... after some const-chasing, I think the place to start is these lines in `projects.h`:

    XY  (*fwd)(LP,    PJ *);
    LP  (*inv)(XY,    PJ *);
    XYZ (*fwd3d)(LPZ, PJ *);
    LPZ (*inv3d)(XYZ, PJ *);
    PJ_COORD (*fwd4d)(PJ_COORD, PJ *);
    PJ_COORD (*inv4d)(PJ_COORD, PJ *);

to

    XY  (*fwd)(LP,    const PJ *);
    LP  (*inv)(XY,    const PJ *);
    XYZ (*fwd3d)(LPZ, const PJ *);
    LPZ (*inv3d)(XYZ, const PJ *);
    PJ_COORD (*fwd4d)(PJ_COORD, const PJ *);
    PJ_COORD (*inv4d)(PJ_COORD, const PJ *);
