### ISSUE TITLE
Polar reprojection: pj_transform drops points

### ISSUE THREAD

**Issue by dshorthouse** [OSGeo/PROJ#449]
I submitted [an issue](https://github.com/mapserver/mapserver/issues/5348) on MapServer's GitHub repository whose root cause is apparently in pj_transform. If you follow the comments, @jmckenna will point you to the bottom of http://osgeo-org.1560.x6.nabble.com/Polar-reprojection-again-td4288764.html#a4288776 where Frank Warmerdam discussed a fix. Unfortunately, his modified pj_transform.c returns a 404. I hope there's enough information here to get to the bottom of the issue.

**Comment by kbevers** [comment]
Can you provide me with the projection string you are using and a set of coordinates that are transformed incorrectly? Preferaby with the expected results as well, if that is possible. That will make it a lot easier to debug and fix this problem.

**Comment by dshorthouse** [comment]
I have no idea what MapServer is doing internally when making calls to proj, which apparently is where the issue resides - an interaction between its EXTENT and calls made. Since @warmerdam was the one to originally respond and even suggested a fix to pj_transform(), I assume he'll recall what was going on. The fix he made may not have ever been incorporated even though it was apparently committed to an old CVS repo.

This is what he wrote in that URL I provided earlier:

```
The raster resampler calls PROJ.4's pj_transform() function for one 
whole row of points to transform at once.  The idea is that pj_transform() 
returns a success flag for each point.  But some kinds of errors are 
considered to be "non-transient", and it is assumed if they are encountered 
for one point they will apply to all points. 

It turns out that getting errno=33 (EDOM) or errno=34 (ERANGE) from 
math library functions (like atan) were considered "non-transient" by 
pj_transform(), even though they are likely to only apply to some points 
in a group.  Because your initial range +-10000000 was invalid to reproject, 
and because the error was improperly considered non-transient the code 
was assuming all the points would fail and giving up. 

Using a smaller initial EXTENT (ie +-5000000) was enough to get a reason 
result.  But better than that, I was able to correct the PROJ.4 
pj_transform() function. 

The upshot is that if you can grab the latest PROJ.4 source from CVS and 
build it, you can get correct behavior.  Since I wouldn't be surprised 
if that is messy for you, I have also put the modified pj_transform.c 
on my web site at: 

   http://www.gdal.org/tmp/pj_transform.c

If you grab that and dump over the PROJ 4.4.9 src/pj_transform.c file, 
build and install it, you should be ok.
```

FWIW, my PROJ is Rel. 4.9.3, 15 August 2016 and here's the relevant bits from my mapfile in MapServer:

```
EXTENT -148121.186365755 365450.649229487 3912759.02991964 2393632.20330306
PROJECTION
    "proj=laea"
    "lat_0=90"
    "lon_0=0"
    "x_0=0"
    "y_0=0"
    "ellps=WGS84"
    "datum=WGS84"
    "units=m"
    "over"
    "no_defs"
  END
POINTS
      141.2602778 75.39833333
END
```

That point is expressed as long lat.

From the above PROJECTION, I'd assume the proj string is:
`+proj=laea +lat_0=90 +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +over +no_defs`

But, that's my limit here.

**Comment by kbevers** [comment]
> The upshot is that if you can grab the latest PROJ.4 source from CVS and 
> build it, you can get correct behavior.

Frank committed his fix back in 2006. See  https://github.com/OSGeo/proj.4/commit/9990608a8f73ad884aa1b21bc76a3c6fb44d3382

It might be that Frank's fix was not good enough, it could also be a completely different problem. I have no insight in mapserver or it's config files, so it is hard for me to say if this indeed is a bug in PROJ.4. With @jmckenna's report of the transformation working in QGIS I doubt it though. 

I am happy to look closer into this if the problem can be narrowed down to a basic example using `proj` or `cs2cs`.

**Comment by busstoptaktik** [comment]
No news in 11 months, and seems to be an issue elsewhere than in PROJ.4. Closing.
