### ISSUE TITLE
Documentation for pipelines

### ISSUE THREAD

**Issue by busstoptaktik** [OSGeo/PROJ#454]
The pipeline functionality is currently documented by comments in PJ_pipeline.c and PJ_obs_api.c, and by the demo code in examles/pj_obs_api_test.c

That is somewhat limited.

@kbevers suggests in a review of PR #453 that:

> The pipeline concept is very powerful, but also rather complicated compared to what has been possible in PROJ.4 up until now. This needs to be documented thoroughly. I suggest a new section on the webpage, "Coordinate transformation" where the concept of pipelines can be introduced. It will also be a nice place to document the geodetic transformations that are coming from you soon. Additionally the new proj.h/pj_obs_api.c API should be documented in the "Development" section. This doesn't have to be a part of this PR, but should be written at least before the next release and preferably a lot sooner so first-movers has a chance to try things out.

Which is clearly the way to go.

**Comment by kbevers** [comment]
I'd say this has been taken care of in https://github.com/OSGeo/proj.4/pull/577. Agree @busstoptaktik ?

Both the concept and the new API has been documented in the docs-release-4.1.0 branch.

**Comment by busstoptaktik** [comment]
Agree - you've done some amazing work on the documentation!

**Comment by kbevers** [comment]
Thanks. I've made sure that this will close when the doc PR is merged.
