### ISSUE TITLE
Broken links on the Home page

### ISSUE THREAD

**Issue by Andre-J** [OSGeo/PROJ#455]
Since recently, the content from ftp://ftp.remotesensing.org/ has been removed. These are the first links on the main wiki page https://github.com/OSGeo/proj.4/wiki, Documentation section.

The content of "Gerald Evenden's libproj" has also been gone.

I suggest to link to saved copies from waybackmachine, as mentioned on https://madfileformatscience.garymcgath.com/2016/09/08/libtiff-offline/

Or use https://github.com/OSGeo/proj.4/tree/master/docs/old

**Comment by kbevers** [comment]
I have removed the broken link to remotesensing.org and added a note about the proces of moving stuff to proj4.org.
