### ISSUE TITLE
CALCOFI projection: Fwd code appears to stomp on inv code's setup

### ISSUE THREAD

**Issue by busstoptaktik** [OSGeo/PROJ#458]
CALCOFI roundtrips nicely with nanometer accuracy if you allocate new PJ objects between invocation of forward and backward projection code (as will happen from the command line, when running echo 12 55 | proj +proj=calcofi +ellps=GRS80 | proj -I +proj=calcofi +ellps=GRS80 )

When using the library functions, however, it becomes clear that the forward function stomps on the setup of the inverse function.

Hence, you need to allocate a new instance of the PJ object between backward and forward invocations.

I am not volunteering to repair this (UPDATE: well, apparently I did anyway - cf. comments below), but I attach a minimum working example for reference for anyone inclined to do so.

```
#define PJ_LIB__
#include <projects.h>

#define TODEG(rad)  ((rad)*180.0/M_PI)
#define TORAD(deg)  ((deg)*M_PI/180.0)


int main (void) {
    XY xy = {272.822333088673,   -1567.43423323066};
    LP lp = {TORAD(12), TORAD(55)};
    PJ *P;

    /* First do a roundtrip without using both pj_fwd and pj_inv from the same PJ object */

    P = pj_init_plus ("+proj=calcofi +ellps=GRS80 +no_defs");
    if (0==P)
        return puts ("oops!");
    xy = pj_fwd (lp, P);
    printf ("Ini 1: %.15g   %.15g\n", TODEG(lp.lam), TODEG(lp.phi));
    printf ("Fwd 1: %.15g   %.15g\n", xy.x, xy.y);
    pj_free (P);

    /* allocate a fresh PJ for the inverse call */
    P = pj_init_plus ("+proj=calcofi +ellps=GRS80 +no_defs");
    if (0==P)
        return puts ("oops!");
    lp = pj_inv (xy, P);
    printf ("Inv 1: %.15g   %.15g\n", TODEG(lp.lam), TODEG(lp.phi));
    pj_free (P);


    /* Then do a roundtrip using the same PJ for both pj_fwd and pj_inv */

    P = pj_init_plus ("+proj=calcofi +ellps=GRS80 +no_defs");
    if (0==P)
        return puts ("oops!");
    xy = pj_fwd (lp, P);
    printf ("Ini 2: %.15g   %.15g\n", TODEG(lp.lam), TODEG(lp.phi));
    printf ("Fwd 2: %.15g   %.15g\n", xy.x, xy.y);
    if (0==P)
        return puts ("oops!");
    lp = pj_inv (xy, P);
    printf ("Inv 2: %.15g   %.15g\n", TODEG(lp.lam), TODEG(lp.phi));
    pj_free (P);

    return 0;
}
```

Which, when invoked, replies with:
```
$ calcofi_problem

Ini 1: 12   55
Fwd 1: 272.822333088673   -1567.43423323066
Inv 1: 12.0000000000232   55
Ini 2: 12.0000000000232   55
Fwd 2: 272.822333088732   -1567.43423323096
Inv 2: -180.754568896108   31849873.7233269
```

**Comment by kbevers** [comment]
I think these [two](https://github.com/OSGeo/proj.4/blob/master/src/PJ_calcofi.c#L116) [lines](https://github.com/OSGeo/proj.4/blob/master/src/PJ_calcofi.c#L140) are the culprits. If so the fix is straight forward.

**Comment by busstoptaktik** [comment]
Thanks @kbevers , your hint pointed me in the right direction:

Actually, the problem is [here](https://github.com/OSGeo/proj.4/blob/master/src/PJ_calcofi.c#L89-L91), and materializes because of changes introduced in my own PR #456 in order to support transformations with identical units for input and output (e.g. the Helmert transformation which expects linear units for input and writes linear units on output.

It appears that I mistakenly linked twice to the library version with PR #456 when trying to validate that the bug was not introduced by that PR - actually it is NOT present in master.

The CALCOFI code by (which was introduced by @warmerdam ) stomps on setup data to introduce a workaround implementing something closely related to the functionality PR #456 introduces in the pj_fwd/pj_inv functions. Hence, I think it may now be possible to get the same effect without stomping on the setup data.

But for now, I have changed the code in pj_inv in PR #456 to stay compatible with the existing CALCOFI code.
