### ISSUE TITLE
Is Proj.4 thread-safe as far as pj_errorno ignored?

### ISSUE THREAD

**Issue by bylee20** [OSGeo/PROJ#473]
I found from wiki:

> Key Thread Safety Issues
> ---
> *   the global pj_errno variable is shared between threads and makes it essentially impossible to handle errors safely. Being addressed with the introduction of the projCtx execution context.
>   * the datum shift using grid files uses globally shared lists of loaded grid information. Access to this has been made safe in 4.7.0 with the introduction of a proj.4 mutex used to protect access to these memory structures (see pj_mutex.c).

From this description, may I assume that I don't have to use per-thread context unless I use error handling?

**Comment by rouault** [comment]
I think the answer is yes, but questions are not for github issues
