### ISSUE TITLE
Update links on github and trac to proj4.org

### ISSUE THREAD

**Issue by kbevers** [OSGeo/PROJ#474]
With #466 the last remaining pages from the old trac website has been migrated to proj4.org. Links on github and trac should be changed to proj4.org.

Additionally the github wiki and information on trac.osgeo.org/proj should be removed or hidden.

**Comment by hobu** [comment]
Front page modified. 
Full redirection requested. https://lists.osgeo.org/pipermail/sac/2016-December/007800.html

**Comment by kbevers** [comment]
Thanks, Howard. I'll close this and https://github.com/OSGeo/proj.4/issues/450 when the link in the repo description is updated and the wiki is taken care. 

Regarding the wiki, remove it from the repo or use it for something else related to proj-development?

**Comment by hobu** [comment]
done.

**Comment by kbevers** [comment]
> done.

At least the stuff regarding trac :-)

Something still needs to be done here:

![image](https://cloud.githubusercontent.com/assets/13132571/21569971/fa79992e-cec1-11e6-8f11-688ef3030143.png)

**Comment by mwtoews** [comment]
The old hompage is still broadcasted at https://api.github.com/repos/OSGeo/proj.4

This should be really simple to fix (to those with the correct privileges): just click the <kbd>Edit</kbd> button beside the URL at https://github.com/OSGeo/proj.4

**Comment by hobu** [comment]
done.
