### ISSUE TITLE
Can old trac database be removed ?

### ISSUE THREAD

**Issue by strk** [OSGeo/PROJ#485]
See https://trac.osgeo.org/osgeo/ticket/1846
If you need a database dump please speak up now or it'll be gone shortly.

**Comment by kbevers** [comment]
No objections from me. A database dump would be handy, I guess.

**Comment by hobu** [comment]
Yes a dump for posterity would be good to have around, but otherwise the old trac instance can be shut down.

**Comment by strk** [comment]
Please drop a note in the trac ticket to request a dump. Will send a link to download the dump, so we don't have to keep it on the OSGeo machines.

**Comment by hobu** [comment]
> don't have to keep it on the OSGeo machines.

How big is it? If it is not in some kind of archive at OSGeo, it will likely be lost forever.

**Comment by strk** [comment]
I think backup are cycled on OSGeo, so unless it's intentionally retained (but I don't know why would we do so) it'll be lost. the custom format dump is 2.6M
