### ISSUE TITLE
No reference to source code repository from proj4.org

### ISSUE THREAD

**Issue by strk** [OSGeo/PROJ#486]
I had to guess you were meeting here, as http://proj4.org/ does not contain the info (or hides it very well)

**Comment by hobu** [comment]
We're not intending to be opaque here on purpose. I will add a link to the development source on the website.

**Comment by kbevers** [comment]
Okay, I'll back off then. Just started editing the frontpage of proj4.org :)

**Comment by hobu** [comment]
> Just started editing the frontpage of proj4.org :)

Ok, you can take it :)

**Comment by strk** [comment]
Thanks !
I never thought you were being opaque on purpose :)

**Comment by kbevers** [comment]
Fixed in https://github.com/OSGeo/proj.4/commit/090a259958cc5316ecdba37f2f99ab87a8affe4b
