### ISSUE TITLE
What does no_defs mean?

### ISSUE THREAD

**Issue by jany-tenaj** [OSGeo/PROJ#494]
[esri.txt](https://github.com/OSGeo/proj.4/blob/master/nad/esri#L18) contains lines like the following with +no_defs no_defs or simply no_defs without +.
```
# NAD27(CGQ77) / SCoPQ zone 2
<2008> +proj=tmerc +lat_0=0 +lon_0=-55.5 +k=0.999900 +x_0=304800 +y_0=0 +ellps=clrk66 +units=m +no_defs no_defs <>
```
Am I correct to assume that no_defs means the same as +no_defs and therefore is redundant in the line above or does it have another meaning that was described nowhere?

**Comment by kbevers** [comment]
It doesn't do anything. I don't no why it is there in the first place and it hasn't been updated in 14 years, so  it's not likely anyone can remember the reason :)
