### ISSUE TITLE
Add transformation to ENU coordinate system

### ISSUE THREAD

**Issue by andrewyushkevich** [OSGeo/PROJ#500]

**Comment by kbevers** [comment]
You have to explain in more details what this is all about.

**Comment by andrewyushkevich** [comment]
I mean something like ecef2enu/geodetic2enu/_uvw2enu in [pymap3d](https://github.com/scivision/pymap3d/blob/feb4c0fd7c790bc2d757353f2e24693691414db3/pymap3d/__init__.py).

If I understand right, there's no +proj parameter or transformation function for ENU in proj4.

**Comment by kbevers** [comment]
Maybe [this](https://github.com/OSGeo/proj.4/blob/44c611c574f001267cd39c904c081e8f1f0d8c96/src/PJ_cart.c ) is what you are looking for?

**Comment by andrewyushkevich** [comment]
I don't think so...

Here's a good example:
![multi_coords](https://cloud.githubusercontent.com/assets/23178688/24102641/b297da2a-0d8d-11e7-8be7-48796f9dd306.png)

1. I have geodetic coordinates of the tree (ex. 43.21009, 78.120123).
2. I want to know scene ENU coordinates, knowing the origin of coordiantes system (ex.43.21,78.12)

**Comment by micahcochran** [comment]
This appears to be the [documentation that goes along with that graphic](http://www.dirsig.org/docs/new/coordinates.html).  (That documentation is from [DIRSIG](http://www.dirsig.org/), which looks like remote sensing software only available to the US Government and its contractors and university partners.)

Most CAD software works in a Cartesian plane (like Scene ENU), but surveyors can typically use GPS points to tie it in by a local coordinate system  that has very little distortion (UTM coordinates are closer what I'd call a local coordinate system).  They take a few points on the drawing and it georectifies those points.  Thereby, causing the rest of the points to also have coordinates on the local coordinate system.  Yea, there is a bit of distortion in that process, too.

**Comment by busstoptaktik** [comment]
@micahcochran, @andrewyushkevich: so a potential solution appears to be something like (untested):
`+proj=etmerc +ellps=GRS80 +lon_0=43.21 +lat_0=78.12 +x_0=0 +y_0=0 +k_0=1`

(I see now, that we should also introduce a `+z_0` in `pj_init.c`, as a local geoid approximation, transforming ellipsoidal heights into orthometric).

**Comment by busstoptaktik** [comment]
No response from original poster for more than two weeks. to my attempt at clarifying. This is probably not an issue anymore. Closing.

@andrewyushkevich you can reopen if you disagree, but you will have to offer more details about what you try to accomplish if you want help to solve the problem.

**Comment by absudabsu** [comment]
I can attest that this would be an immensely useful feature. 

@busstoptaktik, Can you please explain how you came up with
`+proj=etmerc +ellps=GRS80 +lon_0=43.21 +lat_0=78.12 +x_0=0 +y_0=0 +k_0=1`
?

**Comment by kbevers** [comment]
> @busstoptaktik, Can you please explain how you came up with
+proj=etmerc +ellps=GRS80 +lon_0=43.21 +lat_0=78.12 +x_0=0 +y_0=0 +k_0=1
?

Thomas is just using the fact that the Transverse Mercator (etmerc) locally is a very good approximation of a right handed coordinate system with minimal distortion of scale, area and angles. By setting the projection center at the scene origin for small areas you get a close enough approximation to a ENU coordinate system. Since this issue originally was created the `+z_0` parameter has been introduced, so the original projection setup should now be defined as:

```
+proj=etmerc +ellps=GRS80 +lon_0=43.21 +lat_0=78.12 +x_0=0 +y_0=0 +z_0=120 +k_0=1
```

**Comment by micahcochran** [comment]
The [Transverse Mercator documentation](https://proj4.org/operations/projections/tmerc.html) gives a brief explanation of the parameters.

**Comment by ralphtee** [comment]
* I have provided some inputs here (https://github.com/jswhit/pyproj/issues/129#issuecomment-439601138).

* IMHO, tweaking `+proj=etmerc` (with or without the suggested extra options) to *emulate* ENU results (or specifically, EPSG Operation Method 9836 "EOM 9836") would introduce other problems down the road. E.g., results from the *tweaked* `+proj=etmerc` would approximate those from actual EOM 9836 implementation but never "equal" - causing other questions. ENU coordinates are frequently used in accuracy/quality calculations of positioning and traverse/network adjustment.
 
* Also, the suggested extra options may cause unintended confusion especially for Users who are not trained in map projections (which are pretty much most of the Users out there).

**Comment by kbevers** [comment]
Thanks @ralphtee. It's quite clear now how this should be implemented.

@rouault Would this be a good operation to use as an example of how to add a new operation after RFC2? I believe there's a bunch of extra things that is needed now compared to before the RFC2-merge, yes?

**Comment by rouault** [comment]
Yes, now for better integration of a new operation, several extra things have to be done if there's a way to represent it as a WKT CONVERSION or COORDINATEOPERATION (that is a Transformation). First is to look in EPSG guidance 7-2, or in the EPSG database itself, if it is something known. Here it looks like this ENU system is what is describe in "§ 2.2.2 Geocentric/topocentric conversions " of EPSG guidance 7-2. Then if you go to https://www.epsg-registry.org/export.htm?gml=urn:ogc:def:method:EPSG::9836 , you'll get the official name of the operation, and name and code of its parameters. Those have to be added to src/proj_constants.h. Then, for that case, you have to edit the SingleOperation::exportToPROJStringGeneric() method in src/coordinateoperation.cpp to add the mapping from the EPSG parameters to the PROJ string mapping. And add in test/unit/test_operation.cpp a test to check that this mapping from WKT to PROJString works. This is the minimum integration.

In Conversion::inverse(), if the method has a natural inverse (sometimes it is just a matter of negating signs, or reversing some parameters, or just switching the source and target CRS), you may add a dedicated case, or let the generic InverseConversion code handle it.

You may also wish to add a C++ create method in the Conversion class to instanciate the new conversion.
If this method is actually used by a transformation registered in the EPSG database, then you'd have to edit scripts/build_db.py to refresh the .sql script with the new data (here the EPSG:9836 method is only referenced by a dummy transformation 'EPSG topocentric example B', so nothing to do). Possibly, if one want to build a WKT representation from the PROJString, one add to edit PROJStringParser::createFromPROJString() in src/io.cpp, but this is not strictly needed (this method is far from being able to convert all potential PROJ string formulations to ISO-19111 model. It only handles a subset centered around CRS formulations)

**Comment by kbevers** [comment]
@rouault All right, that's what I figured. If you are willing to guide me along in the process I'd like to give this a go to get more familiar with the new code. I am a bit low on time at the moment but I will try to get started during this week.

**Comment by caprieldeluca** [comment]
Just to mention that I would be very grateful that the _Geographic/topocentric conversions_ methods could be implemented.  

````
C:\>projinfo -s EPSG:4979 -t EPSG:5819
Candidate operations found: 1
-------------------------------------
Operation n┬░1:

EPSG:15594, EPSG topocentric example A, 0 m, Not specified

PROJ string:
Error when exporting to PROJ string: Unsupported conversion method: Geographic/topocentric conversions

WKT2:2019 string:
CONVERSION["EPSG topocentric example A",
    METHOD["Geographic/topocentric conversions",
        ID["EPSG",9837]],
    PARAMETER["Latitude of topocentric origin",55,
        ANGLEUNIT["degree",0.0174532925199433],
        ID["EPSG",8834]],
    PARAMETER["Longitude of topocentric origin",5,
        ANGLEUNIT["degree",0.0174532925199433],
        ID["EPSG",8835]],
    PARAMETER["Ellipsoidal height of topocentric origin",0,
        LENGTHUNIT["metre",1],
        ID["EPSG",8836]],
    ID["EPSG",15594]]
````

**Comment by Jochem-L** [comment]
Instead of approximating a local coordinate frame with a projection, it is possible to use a PROJ command to do the transformation, including a cartesian Up component. 

Transformation from geographic coordinates to ENU coordinates:
``cct -I +proj=pipeline +step +proj=axisswap +order=3,1,2,4 +step +proj=helmert +ry=%latitude% +rz=-%longitude% +x=%XYZ[1]% +y=%XYZ[2]% +z=%XYZ[3]% +convention=coordinate_frame +exact +step +proj=cart +inv +ellps=GRS80``
with:
`%latitude%` and `%longitude%` coordinates of central point in arcseconds
`%XYZ[1]%`, `%XYZ[2]%` and `%XYZ[3]%` geocentric coordinates of central point

The transformation in opposite direction from ENU coordinates to geographic coordinates can be done by just removing the `-I` parameter. Azimuth, scale and false easting and northing can be added as extra steps in the pipeline (see last line of scripts below). Additionally, the conversion to arcseconds and the computation of the geocentric coordinates can be put in a script.

Transformation from ENU coordinates to geographic coordinates in a Windows batch program:

&nbsp; &nbsp; **enu2geo.bat**
```
@REM MSDOS batch program to transform local E,N,U to lat,lon,h coordinates
@echo off

REM Enable some functionality
setlocal enabledelayedexpansion

REM Show welcome message
echo Transform coordinates in local CRS (E,N,U) to geographic coordinates (lat,lon,h)
echo.
echo Enter coordinates of central point (CP) and additional parameters of local CRS:

REM Ask user for coordinates of central point (CP) and additional parameters of local CRS
set /p latitude= "Latitude of CP         [deg] = "
set /p longitude="Longitude of CP        [deg] = "
set /p height=   "Ellipsoidal height of CP [m] = "
set /p East=     "East-coordinate of CP    [m] = "
set /p North=    "North-coordinate of CP   [m] = "
set /p Up=       "Up-coordinate of CP      [m] = "
set /p azimuth=  "Azimuth of local CRS   [deg] = "
set /p scale=    "Scale of local CRS     [ppm] = "

REM Determine geocentric coordinates of CP
for /f "tokens=*" %%f in ('echo %%longitude%% %%latitude%% %%height%% ^| cct -d 5 +proj^=cart +ellps^=GRS80') do (set coords=%%f)

REM Store geocentric coordinates of CP in array
set i=1
for %%f in (%coords%) do (
 set XYZ[!i!]=%%f
 set /a i=!i!+1
)

REM Invert parameters and convert to arcseconds
set /a latitude=(%latitude%)*3600
set /a nlongitude=%longitude%*-3600
set /a nEast=%East%*-1
set /a nNorth=%North%*-1
set /a nUp=%Up%*-1
set /a azimuth=(%azimuth%)*3600

REM Ask user for input coordinates
echo.
echo Enter coordinates in local CRS (E,N,U) to transform to geographic coordinates (lat,lon,h): 

REM Transform input coordinates
cct -t 0 -d 9 +proj=pipeline +step +proj=helmert +x=%nEast% +y=%nNorth% +z=%nUp% +convention=coordinate_frame +exact +step +proj=helmert +rz=%azimuth% +s=%scale% +convention=coordinate_frame +exact +step +proj=axisswap +order=3,1,2,4 +step +proj=helmert +ry=%latitude% +rz=%nlongitude% +x=%XYZ[1]% +y=%XYZ[2]% +z=%XYZ[3]% +convention=coordinate_frame +exact +step +proj=cart +inv +ellps=GRS80 +step +proj=axisswap +order=2,1,3,4
```
&nbsp;

Transformation from geographic coordinates to ENU coordinates in a Windows batch program:

&nbsp; &nbsp; **geo2enu.bat**

```
@REM MSDOS batch program to transform lat,lon,h to local E,N,U coordinates
@echo off

REM Enable some functionality
setlocal enabledelayedexpansion

REM Show welcome message
echo Transform coordinates in geographic coordinates (lat,lon,h) to local CRS (E,N,U)
echo.
echo Enter coordinates of central point (CP) and additional parameters of local CRS:

REM Ask user for coordinates of central point (CP) and additional parameters of local CRS
set /p latitude= "Latitude of CP         [deg] = "
set /p longitude="Longitude of CP        [deg] = "
set /p height=   "Ellipsoidal height of CP [m] = "
set /p East=     "East-coordinate of CP    [m] = "
set /p North=    "North-coordinate of CP   [m] = "
set /p Up=       "Up-coordinate of CP      [m] = "
set /p azimuth=  "Azimuth of local CRS   [deg] = "
set /p scale=    "Scale of local CRS     [ppm] = "

REM Determine geocentric coordinates of CP
for /f "tokens=*" %%f in ('echo %%longitude%% %%latitude%% %%height%% ^| cct -d 5 +proj^=cart +ellps^=GRS80') do (set coords=%%f)

REM Store geocentric coordinates of CP in array
set i=1
for %%f in (%coords%) do (
 set XYZ[!i!]=%%f
 set /a i=!i!+1
)

REM Invert parameters and convert to arcseconds
set /a latitude=(%latitude%)*3600
set /a nlongitude=%longitude%*-3600
set /a nEast=%East%*-1
set /a nNorth=%North%*-1
set /a nUp=%Up%*-1
set /a azimuth=(%azimuth%)*3600

REM Ask user for input coordinates
echo.
echo Enter geographic coordinates (lat,lon,h) to transform to coordinates in local CRS (E,N,U):

REM Transform input coordinates
cct -t 0 -d 4 -I +proj=pipeline +step +proj=helmert +x=%nEast% +y=%nNorth% +z=%nUp% +convention=coordinate_frame +exact +step +proj=helmert +rz=%azimuth% +s=%scale% +convention=coordinate_frame +exact +step +proj=axisswap +order=3,1,2,4 +step +proj=helmert +ry=%latitude% +rz=%nlongitude% +x=%XYZ[1]% +y=%XYZ[2]% +z=%XYZ[3]% +convention=coordinate_frame +exact +step +proj=cart +inv +ellps=GRS80 +step +proj=axisswap +order=2,1,3,4
```

**Comment by Jochem-L** [comment]
I found a bug in the code of the Windows batch programs above (--number in a PROJ string is not interpreted as +number). I fixed it by editing the code in my comment above. The code should work for negative ENU coordinates and on the eastern hemisphere now too.
