### ISSUE TITLE
Tectonic shifts in NZ and around the world

### ISSUE THREAD

**Issue by surf9** [OSGeo/PROJ#505]
Hi there

I am just wondering how often does Proj4 get updated and released to factor in changes in the land caused by tectonic shifts?

Thanks,

**Comment by busstoptaktik** [comment]
Hello surf9,

The "Issues" section on a Github page is for bug reports and/or feature requests. Please direct your questions to the mailing list (see http://lists.maptools.org/mailman/listinfo/proj )
