### ISSUE TITLE
Accuracy after coordinate transformation

### ISSUE THREAD

**Issue by surf9** [OSGeo/PROJ#506]
Hi there

I would like to carry out transformation from many different coordinate systems.

E.g. 

1. CITM2000 to WGS84
2. NZTM to WGS84
3. NZMG to WGS84

I am just wondering how accurate are the transformation results that Proj4 provides?

E.g. are the results off by a maximum 2m or are they very accurate such as a difference in only mm?

Thanks,

**Comment by busstoptaktik** [comment]
Hello surf9,

The "Issues" section on a Github page is for bug reports and/or feature requests. Please direct your questions to the mailing list (see http://lists.maptools.org/mailman/listinfo/proj )
