### ISSUE TITLE
utm projection incorrect results

### ISSUE THREAD

**Issue by cj-mcdonald** [OSGeo/PROJ#511]
Hello,

I've just built proj 4.9.3 on both Centos 7.3 and Windows Server 2012,
and I'm seeing some differences in results on both platforms compared to
proj 4.8.0.

Doing an inverse UTM to WGS84 projection in zone 41, 60E to 66E.
With 4.8.0 (and previous versions):

`proj -I -f %.6f +proj=utm +lon_0=60e +ellps=WGS84 +datum=WGS84 +units=m +no_defs`
Input: 654321 1234567
Output: 64.413286 11.164772

These results appear correct.

But with the same command and inputs in proj 4.9.3 I get output:
58.413286 11.164772

The longitude is 6 degrees adrift, outside of the UTM zone.

If I explicitly specify the UTM zone then I get the expected results with
proj 4.9.3:

`proj -I -f %.6f +proj=utm +zone=41 +ellps=WGS84 +datum=WGS84 +units=m +no_defs`
Output: 64.413286 11.164772

Also if I specify a fractionally different +lon_0 value with proj 4.9.3, then
I get the expected results:

`proj -I -f %.6f +proj=utm +lon_0=60.00001e +ellps=WGS84 +datum=WGS84 +units=m +no_defs`
Output: 64.413286 11.164772

The behaviour is the same on Centos 7.3 and Windows.  I'm doing a default
build from source, eg on Centos:
```
./configure --prefix /home/my-programs
make
make install
```
The proj 4.8.0 & 4.9.3 installations which I'm comparing were built
on the same systems with the same compilers.

**Comment by cffk** [comment]
Surely zone 41 corresponds to lon_0 = 63?  The formula is lon_0 = 6 * zone - 183.

**Comment by cj-mcdonald** [comment]
Ah, my lack of knowledge.  I was running through some test examples which had been set up years ago, and found the difference in behaviour.  Buts its obviously an incorrect test case.  If I set lon_0 to 63 then it gives the expected results.

I'll close this issue.
