### ISSUE TITLE
Geocentric XYZ to Geodetic λϕH (Rel 4.9.3, 15 Aug 2016)

### ISSUE THREAD

**Issue by ralphtee** [OSGeo/PROJ#512]
I was trying to convert a Geocentric XYZ coordinate (X=-2476833.539  Y=5873855.500 Z=211343.144) to Geodetic coordinate on an evrstSS ellipsoid. The answer should be 112° 51' 49.442" E  1° 54' 41.512" N 933.735 m.

The command I used was
```
cs2cs +proj=geocent +to +proj=longlat +ellps=evrstSS
```
I figured that I need not specify an ellipsoid on the *"from"* side because the input coordinate would be in ECEF. However, cs2cs totally ignored *ellps=evrstSS* (on the *"to"* side) and converted the given XYZ to WGS84 geodetic coordinate. (Please see screen capture below.)

![scn1](https://cloud.githubusercontent.com/assets/22031088/26005443/99b688be-376b-11e7-878e-113da8e08b35.png)

Retyping the command as follow gave the expected result.

```
cs2cs +proj=geocent +ellps=evrstSS +to +proj=longlat
```

![scn2](https://cloud.githubusercontent.com/assets/22031088/26005724/7d5e36f2-376c-11e7-8bde-8cf05f9ffc51.png)

Although the second command gave the expected result, it appeared "weird" as it does not follow the "from"/"to" semantics (i.e., "weird" to specify the target ellipsoid on the *"from"* side). Did I miss something somewhere, or might this be a bug ?

**Comment by busstoptaktik** [comment]
While perhaps confusing, this is how it is meant to work: latlong is a kind of "pass through" indicator that instructs cs2cs (through the underlying `pj_transform()` call) to do nothing on the "to" side of the transformation.

When you have a `geocent` on the "from" side, it means to convert *from* geocentric cartesian *to* geographic (that is how `pj_transform` works in general). On the "to" side you have a passthrough, and on the from side the inverse part of a *conversion to geocentric cartesian*, i.e. a conversion *from* geocentric cartesian. And to carry out that transformation, you need to know which ellipsoid you are working with.
