### ISSUE TITLE
Please add mailing list URL to http://proj4.org/ and https://github.com/OSGeo/proj.4/

### ISSUE THREAD

**Issue by neteler** [OSGeo/PROJ#531]
In the migration off https://trac.osgeo.org/proj/ the link to
http://lists.maptools.org/mailman/listinfo/proj
got lost.

Please add it both to http://proj4.org/ and this github repo landing page to not disconnect it for prospective (new) contributors. Thanks!

**Comment by hobu** [comment]
Fixed in #532
