### ISSUE TITLE
inconsistency among repeated calls of pj_transform

### ISSUE THREAD

**Issue by larivera** [OSGeo/PROJ#540]
Hi,

The short code hereafter is the same as the example in https://github.com/OSGeo/proj.4/wiki/ProjAPI
but  with 'wgs84' and 'geocent' projections instead of 'merc' and 'latlong'.

Running it once and feeding it successively with the same input produces 
different results. The original version doesn't seem to present this problem.

eg:
> ~/taller/PROJ 10174 :./example2_proj
> 45. 45. 
> 3194419.15	3194419.15 	4487348.41
> 45. 45.
> 5438093.35	5438093.35 	7660382.90
> 45. 45.
> 7024610.59	7024610.59 	9904057.10

Luis
--------------------------------------
######
# Slightly modified from:  https://github.com/OSGeo/proj.4/wiki/ProjAPI
# By changing   'merc' and 'latlong' into   'wgs84' and 'geocent' respectively.

#include <stdio.h>
#include <stdlib.h>
#include <proj_api.h>

main(int argc, char **argv) {
     projPJ pj_wgs84, pj_geocent;
     double x, y, z;
     int p;

     if (!(pj_wgs84   = pj_init_plus("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")) )
        exit(1);
     if (!(pj_geocent = pj_init_plus("+proj=geocent +datum=WGS84 +units=m +no_defs")) )
        exit(1);
     while (scanf("%lf %lf", &x, &y) == 2) {
        x *= DEG_TO_RAD;
        y *= DEG_TO_RAD;
        p = pj_transform(pj_wgs84, pj_geocent, 1, 1, &x, &y, &z );
        printf("%.2f\t%.2f \t%.2f\n", x, y, z);
     }
     exit(0);
}
########

**Comment by rouault** [comment]
You don't seem to initialize z. That's the likely explanation

**Comment by larivera** [comment]
Yes, thanks; this solves the issue.
