### ISSUE TITLE
Decision: Version number of the next release?

### ISSUE THREAD

**Issue by kbevers** [OSGeo/PROJ#542]
As discussed recently on the mailing list, now might be a good time to adjust the version numbers of PROJ.4. The following options have been discussed:

1. PROJ.4 v. 4.9.4
2. PROJ.4 v. 4.10.0
3. PROJ.4 v. 10.0.0
4. PROJ.4 v.  5.0.0

Personally I am much in favour of option 3. It frees up the major version number, and the version number is no longer tightly coupled to the name of the library. It will also signal that significant changes and improvements have been made to the library (mostly materialized in the new API).

@hobu, I guess you have the final word here (which is why I have assigned it to you). Others should feel free to chime in with their opinion as well.

**Comment by QuLogic** [comment]
Speaking from a semver perspective, bumping major means API broke, so if #543 were applied right now, it would make sense. Simply adding new API should not necessitate a major bump. That being said, one might want to change major versions for reasons other than API compatibility...

**Comment by busstoptaktik** [comment]
Wouldn't changes in the internals of PJ be considered an ABI break? It certainly would necessitate a recompile, as dynamic linking to a version with updated PJ structure would be catastrophic?

**Comment by busstoptaktik** [comment]
But +1 for 10.0.0 from here. It really would make communication about the version number Vs the project name much easier.

**Comment by hobu** [comment]
Option 4 is PROJ.4 v. 5.0.0

What was the rationale for 10? The 4 vs. 5 thing is only dissonant to us pedants who discriminate between PROJ and PROJ.4 😄 

> Wouldn't changes in the internals of PJ be considered an ABI break? It certainly would necessitate a recompile, as dynamic linking to a version with updated PJ structure would be catastrophic?

I think we are bumping all of the SOVERSION for whatever the next release is called.

**Comment by kbevers** [comment]
@hobu, I wrote the following on the mailing list:

> Regarding the version number of the next release, my suggestion of jumping to version 10.0.0 should mostly be seen as a communication aid. I'll try to explain why. 
> 
> Today we have PROJ.4 version 4.9.3. The next version introduces radically improved geodetic capabilities and a new and more coherent API.  Using 4.10.0 as the next version number would be just fine, and I wouldn't object to that. BUT, to me there's more at play here. The PROJ.4 library existed on life-support for a number of years with very little activity and years between releases. That is all changed now, especially thanks to Howard stepping up and taking on the role of maintainer a few years back. Since then a lot has happened and I think it would be great to show that to the world by "rebranding" the library with a change in version number. A simple change to 4.10.0 would probably be "just another version" to most users of the library, whereas a release of PROJ.4 version 10.0.0 should get the attention of the developers that rely on PROJ.4. Once we have their attention we can explain to them that the library is very much alive, that we've have made a bunch of cool stuff over the past year and let them know what is on schedule for the next couple of years. 
> 
> So yes, we could just continue on the path we are already on but why not use this opportunity to highlight that the project has been revitalized after a long period of stagnation?
> 
> Regarding calling the next major release PROJ.5. I don't like the idea of changing the name of the project when what should be changed is the version number. The problem is that today the project name and version number is tightly coupled. That's not ideal. My suggestion of going to version 10.0.0 fixes that, although at the cost of a very large jump in version numbers. It has worked for another rather big and important piece of software, so surely it can work for PROJ.4 as well! An added benefit is that we get the full use of all three levels in the version number in the future which I think will make it easier to release smaller changes like bug fixes.
> 

I've added "PROJ.4 v. 5.0.0" to the list above.

**Comment by kbevers** [comment]
[Recent discussion on the mailing list](http://lists.maptools.org/pipermail/proj/2017-November/007878.html) decided that the next version is "PROJ v. 5.0.0".
