### ISSUE TITLE
msan issue with pj_init.c:get_init()

### ISSUE THREAD

**Issue by schwehr** [OSGeo/PROJ#550]
In fuzzing, we've found that fname can have an llvm msan violation.  From another Google engineer:

The name string is larger than MAX_PATH_FILENAME + ID_TAG_MAX + 1:
Breakpoint 1, get_init 
    name=0x719000005f0e "epsg:f_uoo_uoff+no_uoo", '\002' <repeats 119 times>, ":no_uoff =epsg:no_uoff no\377\377\377\377\377\377\377\37
7\377proj=", '\377' <repeats 20 times>...) at third_party/proj4/proj/src/pj_init.c:264
264         if ((opt = strrchr(fname, ':')) != NULL)
(gdb) p strlen(name)
$2 = 1250

The strncpy at pj_init.c line 246 will not null terminate the string and initialize the last 2 bytes, leading to the OOB read in strrchr/uninitialized read.

Fully 0 initializing fname or null terminating the string solves the issue.

**Comment by rouault** [comment]
Don't be shy and submit a PR ;-)

**Comment by markus-kusano** [comment]
This appears to have been fixed in 21d16428760469717fd25ebf9d03c286db935c66
