### ISSUE TITLE
CMake files should be installed to lib, not share

### ISSUE THREAD

**Issue by mwoehlke-kitware** [OSGeo/PROJ#560]
It is preferred to install CMake package configuration files (e.g. `proj-targets.cmake` in particular) to `lib` (or arch-specific flavor thereof) rather than `share`, in order to support co-installation of different arch packages (e.g. i686 and x86_64). Specifically, it would be nice to see these installed to `${LIBDIR}/cmake/PROJ4`.

(Also, has anyone considered using `GNUInstallDirs`? Right now it appears that installing to the correct arch-dependent libdir requires setting `PROJ_LIB_SUBDIR`, which does not conform to any convention for such things...)

**Comment by busstoptaktik** [comment]
@cffk, @hobu, you seem to be fluent in cmake. Does the fix by @ndavid (3f42cb4) appear OK to you?

**Comment by hobu** [comment]
Yep, this is the way CMake does it now. The original Proj.4 CMake files originated quite a while ago. This can be merged immediately.
