### ISSUE TITLE
Always true tests in PJ_cart.c

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#568]
```
PJ_cart.c:489:14: warning: address of array 'info.version' will always evaluate to 'true' [-Wpointer-bool-conversion]
    if (info.version) {
    ~~  ~~~~~^~~~~~~
PJ_cart.c:494:15: warning: address of array 'info.release' will always evaluate to 'true' [-Wpointer-bool-conversion]
    if (!info.release)    return 56;
        ~~~~~~^~~~~~~
PJ_cart.c:495:15: warning: address of array 'info.searchpath' will always evaluate to 'true' [-Wpointer-bool-conversion]
    if (!info.searchpath) return 57;
        ~~~~~~^~~~~~~~~~
```

**Comment by kbevers** [comment]
Yeah, I have noticed those. If I remeber correctly I struggled a bit with finding a way to check if these fields are set or not. I recall getting some warning for doing ```if (info.version[0] != \0)``` or something similar. What's the correct way of doing this?

**Comment by rouault** [comment]
```if( info.version[0] != '\0' )``` should be fine

**Comment by kbevers** [comment]
I would think so too. Can't remember the specifics of why I ended up not doing it that way. I'll make the change some time later today. Thanks for reminding of this problem.
