### ISSUE TITLE
Need a projection like Azimuthal Equidistant (AEQD), but with polar coordinates. Do you have one?

### ISSUE THREAD

**Issue by Felix-neko** [OSGeo/PROJ#572]
I have a geotiff in a simple `latlon ` projection. I want to reproject its data on a plane tangential to Earth ellipsoid to make some further calculations.

Just now I'm using `aeqd` projection for it, but I'm looking for some similar projection that would give me not cartesian, but **polar** coordinates.

To reproject my geotiff raster I'm using `rasterio.reproject(...)` to convert my geotiff data (it's a good analog of `cs2cs` utility from `PROJ.4`):

    dst_crs = CRS({"proj": "aeqd", "lat_0": lat_center, "lon_0": lon_center, "datum": "WGS84"})
`lat_center` and `lon_center` were the center of my geotiff.

`aeqd` projection gives me some raster in cartesian grid (`x_j` and `y_i` on the tangential plane):

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/1cPVU.png

But for my purposes it needs some extra interpolation to get the values in my polar mesh (by distance and azimuth on the tangent plane). Can you advice me some other projection?

**Comment by busstoptaktik** [comment]
@Felix-neko - the "issues" section is not for usage discussions, but for reporting actual shortcommings in the PROJ.4 code. Please raise this discussion over at the PROJ.4 mailing list, http://osgeo-org.1560.x6.nabble.com/PROJ-4-f3840930.html, where you are much more likely to get informed opinions on the subject.

Once you have a potential solution described, you are welcome to open an enhancement proposal here.

I'm closing this issue now, but please note that it will remain accessible through direct URL, so when raising the discussion on the mailing list, please don't supply figures - just give a reference to this page.
