### ISSUE TITLE
Remove Windows CE cruft (wince/msvc80)

### ISSUE THREAD

**Issue by mloskot** [OSGeo/PROJ#582]
As original maintainer of the Windows CE port, I can confirm I no longer use it.
Even if there are users, they should survive using CMake.

Can I remove the wince/msvc80 folder and any mentions of Windows CE, if found anywhere?

**Comment by kbevers** [comment]
+1 from me, but I'd suggest you check with the mailing list if someone is still using it.

**Comment by mloskot** [comment]
@kbevers 
> I'd suggest you check with the mailing list if someone is still using it.

Good idea, http://lists.maptools.org/pipermail/proj/2017-September/007792.html
