### ISSUE TITLE
Add Tobler-Mercator projection

### ISSUE THREAD

**Issue by micahcochran** [OSGeo/PROJ#584]
Dr. Waldo Tobler mentioned in the mailing list that someone should add this projection.

Here is a link to the paper "A new companion for Mercator". Published 31 Mar 2017.  It is behind a paywall.
http://dx.doi.org/10.1080/15230406.2017.1308837

Mike Bostock appears to have created an [example of this projection](https://bl.ocks.org/mbostock/f3db9ee8f3d22558c2ad745c88507ce8).

**Comment by tobwen** [comment]
I will never understand why access to science costs a fee.
