### ISSUE TITLE
proj_destroy should take an errlev argument

### ISSUE THREAD

**Issue by busstoptaktik** [OSGeo/PROJ#585]
`proj_destroy (PJ *P)` should be `proj_destroy (PJ *P, int errlev)`, so it matches the `pj_default_destructor ()` and the `destructor` entry in the `PJ` type.

Functionality should be similar to that of the `pj_default_destructor ()`: Setting the error level on the associated context if `errlev != 0`, then cleaning up after `PJ *P`.

All in all, this would make proj_destroy a simple wrapper call for `P->destructor`, and make chained destruction, as in `PJ_ob_tran.c` a bit easier to read.

It would also enforce an overall culture of stating whether all is well, improving handshake with application level code.

As there has still not been any released versions of PROJ.4 supporting the proj_destroy functionality, all relevant uses are found within the PROJ.4 code base.

Hence, I intend to implement this ASAP (but please feel free to comment - I may have missed something)

**Comment by rouault** [comment]
I'd find it odd that proj_destroy has a errlevel argument for external users of proj. Perhaps that makes sense internally, but externally I fail to see one. If errors occur it is up to proj to raise them. Users just want to destroy an object that proj returned to them previously

**Comment by busstoptaktik** [comment]
@rouault  you are (not surprisingly :-) ) totally right. Thanks for an educational comment - I rest my case here, and consider whether we need a `pj_destroy_with_errlev` for library internal use. It may not be worth the effort in general, but it may make it easier to introduce the structure of a PJ_xxx file for new developers.
