### ISSUE TITLE
There's no obvious way to do an inverse transformation with cct

### ISSUE THREAD

**Issue by kbevers** [OSGeo/PROJ#607]
With `proj` and `cs2cs` the `-I` flag can be used to do the inverse transformation of the given proj-string. With `cct` this is not possible. It is possible by using the pipeline framework, e.g.

```
cct +proj=pipeline +step +proj=merc +inv
```
but that shouldn't be necessary for simple transformations that consists of only one step. This can be solved in several ways, either by simply adding an `-I` flag to `cct` or perhaps by allowing the `+inv` parameter to be used in transformations that are not using the pipeline framework.

So possible solutions are either
A) `cct -I +proj=merc` or 
B) `cct +proj=merc +inv`

**Comment by busstoptaktik** [comment]
`cct` should support the `-I` flag. Line 168 says:
```
    direction = opt_given (o, "I")? -1: 1;
```
 If it doesn't, it is an error.  But not having an `-I` example, and documentation in the help text is certainly an error.

So perhaps the thing is really not so much that `cct` lacks an obvious way to do inverse transforms, but rather that it lacks in making it obvious how to do them?

**Comment by kbevers** [comment]
I get this with `cct` compiled from master:
```
> cct.exe -I +proj=merc
Invalid option "I"
```

**Comment by kbevers** [comment]
The fix is easy, btw. `I` is missing in the following statement (line 158, cct.c):
```
  o = opt_parse (argc, argv, "hv", "cozt", longflags, longkeys);
```

**Comment by busstoptaktik** [comment]
Gracias - will update

**Comment by busstoptaktik** [comment]
Oops - I'm working on this too (in connection with repairing #608), so expect a hand held merge soon :-)

**Comment by busstoptaktik** [comment]
... actually, our changes were so close to being identical, that I am just discarding my changes in cct.c, and keep only the ones in proj_strtod.c
