### ISSUE TITLE
cct has trouble reading zeros

### ISSUE THREAD

**Issue by kbevers** [OSGeo/PROJ#608]
The below copypasta explains the problem. It should be possible to just enter "0" as a coordinate.

```
> cct.exe +proj=merc
55 12 0 0
# UNREADABLE: 55 12 0 0
55 12 0. 0.
6122571.993630046000000  1336830.206625790100000     0.000000000000000     0.000000000000000
55 12 0.0 0.0
6122571.993630046000000  1336830.206625790100000     0.000000000000000     0.000000000000000
```

**Comment by kbevers** [comment]
Followup. This only happens in some cases. I suspect that the problem arises when the underlying projection is only is defined in the 2D case.

```
> cct.exe +proj=cart +ellps=GRS80
12 55 0 0
3586469.656816008000000  762327.658786674850000  5201383.523088155300000     0.000000000000000
```

**Comment by busstoptaktik** [comment]
That's a regression in proj_strtod. Apparently I fatfingered a commit recently. Will check.
