### ISSUE TITLE
Convert GIGS to gie

### ISSUE THREAD

**Issue by kbevers** [OSGeo/PROJ#621]
We might as well use `gie` for the GIGS tests. It should cut down the test-execution time significantly, reduce the code base some amount as well and the overall test setup will be a lot simpler.

It is not possible with the current incarnation of `gie` but it should be possible to add the needed functionality to the test program. As far as I can understand the GIGS tests are not using the euclidean distance between the two coordinates to test how well the calculated coordinate matches the expected. Instead each element in a coordinate is checked against it's expected counterpart, i.e.
```
abs(x_calc - x_exp) < TOL && abs(y_calc - y_exp) < TOL && abs(z_calc - z_exp) < TOL
```

 `gie` should be able to handle that before the GIGS tests can be converted.

Perhaps a `DIRECTTOL` operation should be added, that tests the individual numbers in a coordinate against the expected result.

**Comment by busstoptaktik** [comment]
> Perhaps a DIRECTTOL operation should be added, that tests the individual numbers in a coordinate against the expected result.

In the full design, I intend to include a "NORM" directive, setting the method of measurement. Mathematically speaking, GIGS seems to check the *infinity norm* (a.k.a. the *maximum norm*).

I would still want to have the geodesic distance as the default norm in the angular case, though, as this is as close we get to an "Euclidean norm on an ellipsoidal surface".

As-is, the roundtrip directive is a direct call to `proj_roundtrip()`, which measures geodesics for angular coordinates, Euclidean for linear.

Note that the Euclidean norm will always be at least as large as the infinity norm:

> max (abs dx, abs dy, abs dz) <= sqrt (dxdx+dydy+dzdz).
>
> > *Where the equals part applies only when at least two of (x, y, z) are 0.*

That is, the Euclidean norm claims the discrepancy is **worse** than the infinity norm does.

Hence, if the GIGS criteria are met under the Euclidean norm, they will also be met under the infinity norm. So if complying with "GIGS under Euclidean norm" we certainly comply with GIGS, while we *may* still comply, even if failing slightly.

**Comment by kbevers** [comment]
This is the crucial part with regards to the tolerance check of the current Python GIGS test:
```python
coord_diff = abs(cor[0] - exc[0]), abs(cor[1] - exc[1]), abs(cor[2] - exc[2])
if isinstance(tolerance, float):
    matching = coord_diff < (tolerance, tolerance, tolerance)
elif isinstance(tolerance, (list, tuple)):
    matching = coord_diff < tuple(tolerance)
```

I'll admit that I haven't looked through all the GIGS documents (there's a LOT of them), but from our current GIGS setup it seems that some of the tests have different tolerance values for the x, y and z components of a coordinate. In reality I reckon that it is probably only differentiated in the horizontal and vertical parts, but nonetheless, it's not always just the same number for all three components. I don't know how that fits the concept of the inifity norm. But in the cases where it is the same tolerance for all components, yes, it do look like the infinity norm is used.

> So if complying with "GIGS under Euclidean norm" we certainly comply with GIGS

My limited testing so far suggest that in many cases we are at least an order of magnitude on the wrong side with the Euclidean norm. Hence the wish for more tools in the box.

Here's a little sample from the 5101.2 test:
```
     FAILURE in 5101.2-jhs.gie(65):
     expected: 611544.042 6653097.435
     got:      611544.041976836   6653097.435294963
     deviation:  0.296 mm,  expected:  0.030 mm
     -----
     FAILURE in 5101.2-jhs.gie(68):
     expected: 667294.821 6655205.484
     got:      667294.821124452   6655205.483634564
     deviation:  0.386 mm,  expected:  0.030 mm
     -----
     FAILURE in 5101.2-jhs.gie(71):
     expected: 723020.074 6658157.202
     got:      723020.073598994   6658157.202407250
     deviation:  0.572 mm,  expected:  0.030 mm
     -----
     FAILURE in 5101.2-jhs.gie(74):
     expected: 778711.23 6661953.041
     got:      778711.229752370   6661953.040544908
     deviation:  0.518 mm,  expected:  0.030 mm
```

Round trip test seem to perform very well though!

**Comment by busstoptaktik** [comment]
Apparently, the expected coordinates are given in mm or cm, while the expected deviation is given as submillimetric. Something's wrong with that - I would expect at least an extra digit in the "expected" data. Or perhaps the expected deviation is given in cm, dm or even m?

**Comment by kbevers** [comment]
From the test description: "Results for the forward and reverse calculations should agree to within 0.03m ". So 3cm is the expected accuracy. I set the tolerance in the gie-file with `TOLERANCE 0.03`. Does gie not work in meters for the tolerance setting?

**Comment by busstoptaktik** [comment]
> Does gie not work in meters for the tolerance setting?

You can specify the unit as *km, m, dm, cm, mm, um, nm*:

    tolerance 42 km
    tolerance 4 dm
    tolerance 1 nm
    tolerance 314 um

If no unit is given *mm* is assumed, since this is the approximate accuracy level expected for geodetic transformations.

*um* is micrometer, with *u* playing the role of greek mu. And yes - I left out *hm* and *dam*.

Perhaps *Mm* could be useful, for giving points for at least hitting the right quadrant :-)

**Comment by kbevers** [comment]
Alright, that was not clear to me. I definitely expected meter to be the unit of choice, it is after all the standard everywhere else in PROJ.4.

We probably need some sort of documentation.

**Comment by kbevers** [comment]
The 5101.2 test passes with flying colors now:

```
$ ./bin/gie ../../proj4/test/gigs/5101.2-jhs.gie
-------------------------------------------------------------------------------
Reading file '../../proj4/test/gigs/5101.2-jhs.gie'
-------------------------------------------------------------------------------
total: 46 tests succeeded,   0 tests failed.
-------------------------------------------------------------------------------
```

**Comment by busstoptaktik** [comment]
> We probably need some sort of documentation.

Certainly - and perhaps either changing the default to *m* or requiring explicit statement of unit.

**Comment by kbevers** [comment]
I prefer meter as the default unit, but explicitly stating the unit is obviously more transparent.

**Comment by kbevers** [comment]
All GIGS tests have been translated to the format used in gie. All passing tests are added to the CMake test suite, although not run on the CI targets just yet.
