### ISSUE TITLE
proj.h: missing equivalent of int pj_find_file(projCtx ctx, const char *short_filename,   char* out_full_filename, size_t out_full_filename_size); in proj.h

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#654]
This function is used by GDAL to be able to retrieve the full file name for a proj.4 grid file. It would be necessary to have someting equivalent in proj.h

**Comment by kbevers** [comment]
This can be achieved with the `proj_info_grid` function. It call's `pj_find_file` and saves the path, if found, in the returned `PJ_GRID_INFO` struct. `proj_info_init` can be used to locate an init-file.

**Comment by rouault** [comment]
Ah I've overlooked this... Thanks
