### ISSUE TITLE
More almost-for-free OGC/ISO-19100 alignment improvement

### ISSUE THREAD

**Issue by busstoptaktik** [OSGeo/PROJ#663]
As a new PROJ.4 version is getting closer, I think we need to do some more things fast in order to have a reasonable terminology alignment with the OGC/ISO-19100 geospatial standards series.

In PR #639, I introduced the macro synonyms `OPERATION`, `TRANSFORMATION` and `CONVERSION`, and their specialization `PROJECTION`. They frame most of what I propose to do now.

The first steps are probably uncontroversial: They consist of introducing similar synonyms in the projection (or rather: operation) definition language (if I may be so far-fetching as to call a set of key/value-pair definitions a language):

Let’s introduce the `proj=` synonyms `oper=`, `tran=`, and `conv=`, maintaining the PROJ.4 tradition for short, readable forms, while adding a bit of *informal* semantics.

I do **not** propose, for now, to put any *formal* semantical meaning into the keys, other than the one already borne by proj=, but down the line, obviously it will be possible to let the individual operations check that they are not being called with a misleading key tag.

Also, what’s called a “pipeline” in PROJ.4 is called a concatenation in ISO-19100, so we should have a reasonable synonym - e.g. “concatenate”, “concat”, “cat” or somesuch (a synonym requires only a two line addition in PJ_pipeline.c + the related X-macro magic in pj_list.c).

I suppose all of this is largely uncontroversial, since it requires minimal coding, only adds synonyms, and does so for the greater good of being more aligned with current geospatial standards.

More controversially, I suggest to rename the `proj_trans` family to something that does not suggest “transformation”, but the most general of the terms: “operation”, e.g.
`proj_oper()`, `proj_oper_array()`, and `proj_oper_generic()`.

Here, I do not suggest any synonyms (in the name of avoiding API clutter). Other possibilities: proj_op, proj_operate, proj_operation, or (and this is actually my current favorite, closely folloed by proj_op): just proj.

By calling it proj, and nothing else, we do not get the “operation” flavor into the name, but by letting it be “just the namespace, and nothing else”, we stress that THIS is the entrance to the main functionality of the library. So:

proj is nice and very short

proj_op is nice, short, and hints at "operation"

proj_oper is aligned with the oper= keyword proposed

proj_operate says what it *does*, but is too long for my taste

proj_operation says what it *is*, but is even longer

Unless we go with the bare “proj”, I think we should select something that directly aims at the ISO-19100 overarching concept of “operation” - proj_trans will have to go (although I really *like* that name)

@kbevers  and @rouault, you were quite active when we selected the `proj_` namespace for the 4D API, so I think you may have meanings about this as well?

**Comment by kbevers** [comment]
No objections to the first part.

The second part, on the other hand, I am not so sure about. Although it aligns perfectly with the standard, using "operation" in favour of "transformation" is taking it a little to far for my taste. To me it makes sense to talk about "projecting", "converting" and "transforming" coordinates.  The list doesn't really extend to "operating". My feeling is that "transformation" is the most intuitively understood word, although it is not 100% correct according to the standards.

Which of the current functions are you proposing to rename to "proj"?

**Comment by busstoptaktik** [comment]
"Operation" is the superclass for "transformation", "conversion" and "projection". A transformation is *not* a conversion, a conversion *may* be a projection, and a projection *is* a conversion.

And *all transformations, conversions and projections* are ***operations***. And if "transformation" is perceived as the most intuitively understood word, it's probably because it is so easily intuitively *mis*understood, and hence should be left out of contexts where it is bound to confuse.

Mathematically, a `PJ` is an *operator*. It *operates* on `PJ_COORD`. It should do so through the facilitating plumbing delivered by `proj_op`, `proj_operation` or somesuch function.

If going for the ultrashort option, `proj_trans`  would become `proj`,  `proj_trans_array` would become `proj_array`, and `proj_trans_generic` would become `proj_generic`

**Comment by kbevers** [comment]
Yes, I understand the definitions in the standard. I am just saying that they are easily understood as nouns, but not necesarily in their verb counterparts. To me anyway...

With that said, the problem doesn't exist if we use your suggested ultrashort option. The `proj_array` and `proj_generic` become slightly less self-describing but I think we can live with that.

**Comment by c0nk** [comment]
I also don't like the `proj_op*` suggestion. They mostly sound like nouns. The ultra short options are too short. I prefer the current names to both of those. But what about names like `proj_apply` and `proj_apply_array`?

**Comment by kbevers** [comment]
We are too far into the release process to make those changes. The first part of this issue is stil valid and should go into 5.1.0, but the boat has sailed on the second part.

**Comment by busstoptaktik** [comment]
> but the boat has sailed on the second part

Well, actually it's the train that has flown, but there's no reason to row it back to the shore, anyway: The API stuff we have works, it's just the colour that has another sound, so no reason to change that - rather, let's take the bull by the hand and avoid mixing metaphors :-)

I agree that the first part is still legit, but I think it needs another iteration, so I'll close this for now, and probably open another issue or PR after the next ISO TC-211 meeting in Copenhagen in May/June.

Reopen if you disagree.
