### ISSUE TITLE
Incorrect declaration of hypot using Visual Studio 2017 

### ISSUE THREAD

**Issue by pstieber** [OSGeo/PROJ#695]
I'm attempting to build the master branch (86b96ccb8c926f831451c3e6d364319a0d833522) using the 64-bit version of Visual Studio 2017 version 15.5.0.  The default cmake setup indicates `Performing Test C99_MATH - Failed`. This leads to a declaration of `hypot` via https://github.com/OSGeo/proj.4/blob/master/src/projects.h#L97, but this declaration causes the following compiler warning:

```
2>C:\OutsideSource\proj.4\src\projects.h(97): error C2220: warning treated as error - no 'object' file generated
2>C:\OutsideSource\proj.4\src\projects.h(97): warning C4273: 'hypot': inconsistent dll linkage
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\ucrt\corecrt_math.h(509): note: see previous definition of 'hypot'
```

This indicates `hypot` is declared in `corecrt_math.h`, which is included via `math.h`.

The preprocessor test to include `hypot` was changed by @kbevers 29 days ago.

https://github.com/OSGeo/proj.4/commit/e09999127da8dea56d9af52bc346cf7cc6613547

Is the `C99_MATH` test is flawed?

**Comment by cffk** [comment]
Bletch -- this looks like a mistake I made.  Please replace "copysigna"
by "copysign" on line 41 for CMakeLists.txt and try again.  Let me know
if this fixes the problem.

   --Charles

**Comment by pstieber** [comment]
@cffk Your suggested fix of `copysigna` -> `copysign` worked.  The C99_MATH test is working and the declaration is no longer included.  Thanks!  Will let someone else with merge privileges close this issue.

**Comment by cffk** [comment]
Done...

**Comment by pstieber** [comment]
@cffk That was fast!  Thank you!

**Comment by kbevers** [comment]
Is this also a problem with 5.0.1?

We've not been very good at taking care of the nmake builds, so this is likely to have been overlooked while making changes to this in the autoconf/cmake setups. Do you get the same errors if you build via  cmake-generated nmake files?

Please also note that [nmake support will be removed in version 6](https://github.com/OSGeo/proj.4/issues/838).

**Comment by cffk** [comment]
My guess is that HAVE_C99_MATH needs to be defined for recent versions Visual Studio.  This is taken care of (I believe) by cmake.  Perhaps there's some way that nmake can figure out how to set this macro based on the version of Visual Studio.

**Comment by kbevers** [comment]
>  This is taken care of (I believe) by cmake.

That was my hope too. And why I prompted for a test with CMake generated nmake files. Actually in general I am just interested to see if that even works. I haven't done the test myself.

> Perhaps there's some way that nmake can figure out how to set this macro based on the version of Visual Studio.

We shouldn't waste too much time on maintaining nmake though. But if someone has a quick solution we should of course include that.

**Comment by zedxxx** [comment]
I try to build version 5.0.1 with Visual Studio 2008 using CMake and got the same error:

```
proj_etmerc.c
d:\proj\src\projects.h(97): error C2220: warning treated as error - no 'object' file generated
d:\proj\src\projects.h(97): warning C4273: 'hypot' : inconsistent dll linkage
  C:\Program Files (x86)\Microsoft Visual Studio 9.0\vc\include\math.h(455) : see previous definition of 'hypot'
```
Configuration info:
```
+ cmake . '-GVisual Studio 9 2008' '-DBUILD_LIBPROJ_SHARED=1' '-DCMAKE_INSTALL_PREFIX=d:/.build'
-- The C compiler identification is MSVC 15.0.30729.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 9.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 9.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
--
-- Configuring PROJ:
--
-- PROJ_VERSION                             = 5.0.0
-- PROJ_ABI_VERSION                         = 5_0
-- Looking for include file dlfcn.h
-- Looking for include file dlfcn.h - not found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - not found
-- Looking for include file jni.h
-- Looking for include file jni.h - not found
-- Looking for include file memory.h
-- Looking for include file memory.h - found
-- Looking for include file stdint.h
-- Looking for include file stdint.h - not found
-- Looking for include file stdlib.h
-- Looking for include file stdlib.h - found
-- Looking for include file string.h
-- Looking for include file string.h - found
-- Looking for include file sys/stat.h
-- Looking for include file sys/stat.h - found
-- Looking for include file sys/types.h
-- Looking for include file sys/types.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - not found
-- Looking for 4 include files stdlib.h, ..., float.h
-- Looking for 4 include files stdlib.h, ..., float.h - found
-- Looking for localeconv
-- Looking for localeconv - found
-- Looking for ceil in m
-- Looking for ceil in m - not found
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Looking for PTHREAD_MUTEX_RECURSIVE
-- Looking for PTHREAD_MUTEX_RECURSIVE - not found
-- Performing Test C99_MATH
-- Performing Test C99_MATH - Failed
-- PROJ_PLATFORM_NAME                       = win32
-- PROJ_COMPILER_NAME                       = msvc-9.0
-- PROJ4_TESTS                              = ON
```

**Comment by kbevers** [comment]
Is this build from the source distribution or from master?

**Comment by zedxxx** [comment]
It was from source. I thought that this fix was already in the latest release.

Building from master is ok. Sorry for disturbing.
