### ISSUE TITLE
Segfaults in PR #693 - help needed

### ISSUE THREAD

**Issue by busstoptaktik** [OSGeo/PROJ#701]
Currently, I'm working om PR #693, which heavily modifies the get_init function in `pj_init.c`. The intention with the work is to implement fully free-format transformation/operation descriptions, while also improving the maintainability of that corner of the code.

PR #693, among other things, also addresses issue #697 by eliminating stack allocation of large objects.

Merging PR #693 will also result in a more tractable platform for solving issue #700.

Unfortunately, I experience some annoying segmentation faults in the CI builds on Travis and AppVeyor, which I cannot provoke on my development platform (gcc version 7.1.0, x86_64-posix-seh-rev1, Built by MinGW-W64 project, and running under Windows 10)

So I'm going through some pretty obnoxious remote, asynchronous debugging currently, basically adding debugging printout all over the code, to follow what's going on on the CI platforms.

This is a slow, and not very clean proces, so any help from people able to reproduce the CI segfaults would be much appreciated.

On **Travis**, the segfault appears around line

        init_info = proj_init_info("epsg");

in the function `pj_cart_selftest` in `gie.c` - (build/test log available [here](https://travis-ci.org/OSGeo/proj.4/jobs/314587299)).

On **AppVeyor**, `gie.exe`, during processing `more_builtins.gie` dies with `Command exited with code -1073741819` half way through printing a line of "-", when finalizing the tests for `proj=geoc ellps=GRS80` (build/test log available [here](https://ci.appveyor.com/project/OSGeo/proj-4/build/1.0.1220/job/kx9d48gm4qen2e06)).

Very different symptoms, so all in all it looks like somewhere I have smashed either the heap or the stack (or both) and that the place where the symptom pops up may have nothing to do with where its root cause is.

But not being able to reproduce the symptom locally (where all tests run smoothly) makes it very hard to debug, although I suspect the bug is trivial once located.

So any help you may offer, by direct debugging or strategical advice, is much appreciated.

**Comment by rouault** [comment]
@busstoptaktik You should invest in a Linux VM with Valgrind. That's a few hours time investment that will save you years of debugging ;-)

```
init=epsg:metadata
+init=epsg:metadata
==19842== Invalid read of size 1
==19842==    at 0x4C30F62: strlen (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19842==    by 0x4E8BB4E: append_defaults (pj_init.c:277)
==19842==    by 0x4E8BEB7: pj_get_init (pj_init.c:341)
==19842==    by 0x4EAA561: proj_init_info (proj_4D_api.c:794)
==19842==    by 0x407A16: pj_cart_selftest (gie.c:1745)
==19842==    by 0x403C32: builtins (gie.c:546)
==19842==    by 0x405238: dispatch (gie.c:871)
==19842==    by 0x4034C1: process_file (gie.c:348)
==19842==    by 0x403227: main (gie.c:294)
==19842==  Address 0x9 is not stack'd, malloc'd or (recently) free'd
==19842== 
```

With a closer look, the issue is that the proj returned by the following (line 276 of pj_init.c) is a NULL pointer:
```
proj = pj_param_exists (start, "proj");
    if (strlen (proj->param) < 6)
        return start;
```
Alternatively, you could try DrMemory ( http://drmemory.org/ ) that works on Windows

**Comment by busstoptaktik** [comment]
Thanks, @rouault - that was one bug now corrected, although some still remain. I have now installed Docker and will go on finding a recent Valgrind Dockerfile (or perhaps just run Ubuntu under Docker and have every build tool readily accessible), to chase down what bugs remain.

So thanks for both active debugging and good advice!

**Comment by busstoptaktik** [comment]
Update: I have now checked PR #693 on the folowing platforms:

Ubuntu 16.04, with and without Valgrind - cannot provoke failure, no alarming reports from Valgrind

Windows 10 using MinGW64, with and without DrMemory - cannot provoke failure, no alarming reports from DrMemory

Windows 10 using MS Visual Studio 2017, cl version 19.12 - cannot provoke failure

So all in all a failure that jumps up readily on the CI platforms, but which I cannot reproduce locally. If anyone can, please let me know how you did.

**Comment by busstoptaktik** [comment]
@rouault, @schwehr and @kbevers, thanks for helping with this nasty bug. Everything runs smoothly now!

**Comment by busstoptaktik** [comment]
@rouault, @schwehr and @kbevers, thanks for helping with this nasty bug. Everything runs smoothly now!
