### ISSUE TITLE
Add gie tests in 'make check'

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#702]
Currently the following tests are run after 'make check' in travis/install.sh. It would be good to have them as part of 'make check' itself, to ease local development

```
PROJ_LIB=$GRIDDIR ./src/gie ./test/gie/builtins.gie
PROJ_LIB=$GRIDDIR ./src/gie ./test/gie/more_builtins.gie
PROJ_LIB=$GRIDDIR ./src/gie ./test/gie/deformation.gie
PROJ_LIB=$GRIDDIR ./src/gie ./test/gie/axisswap.gie
PROJ_LIB=$GRIDDIR ./src/gie ./test/gie/ellipsoid.gie
PROJ_LIB=$GRIDDIR ./src/gie ./test/gie/GDA.gie
```

**Comment by kbevers** [comment]
I am actually already working on this. My main objective was to convert the GIGS tests to the gie framework, and then add them to cmake/autotools. I already got a working cmake setup, but I hit a roadblock (#700) when converting the GIGS tests and it got put on the back-burner. I'll push a PR with at least the Cmake setup later today or tomorrow.
