### ISSUE TITLE
Remove 'free_format' element from the OPTARGS object

### ISSUE THREAD

**Issue by busstoptaktik** [OSGeo/PROJ#709]
The semantics of the `free_format` element is unclear, as remarked by @schwehr in a comment to #693. And since a minor restructuring of the code can eliminate the need for it, it should go.

**Comment by kbevers** [comment]
Duplicate of https://github.com/OSGeo/proj.4/issues/699

**Comment by busstoptaktik** [comment]
Oops! Repeating myself myself :-)
