### ISSUE TITLE
C language support?  C89, C99, and/or C11

### ISSUE THREAD

**Issue by schwehr** [OSGeo/PROJ#710]
Would Proj consider moving to C99?  And maybe having a roadmap for C11?

Whether the project is up for those or not, it would be great to have a statement as to why.  Having an explanation would be helpful for those new to the project's code base.  

I also don't see anything in the `.travis.yml` that states a version of C.  If C89 is the target, then it seems that CI should have a test run that is explicitly C89.

Sorry if this is rehashing the topic, but it's not obvious coming into the code base.

https://github.com/OSGeo/proj.4/pull/693/files#r155818506

> aaronpuchert 9 days ago  Contributor
> As long as we stick with C89, we can't assume having strncpy. It's only available since C99 
> and the compiler will not make it available when we pass -std=c89, regardless of whether 
> it is supported.

I only see this in the README:

> ANSI X3.159-1989 C code.  Site must have ANSI C compiler and header files.

**Comment by kbevers** [comment]
> Would Proj consider moving to C99? And maybe having a roadmap for C11?

Probably not, but I am happy to discuss it. I am not up to speed with the current state of affairs regarding how widespread availability of C99 and C11 is. Obviously this is not a big issue on "normal" computers, but what about embedded systems like GNNS receivers?

> Whether the project is up for those or not, it would be great to have a statement as to why. Having an explanation would be helpful for those new to the project's code base.

I think the main reason for sticking with C89 is that it more or less guarantees portability. PROJ is a fundamental library which is used all over the place. It is very likely that embedded devices are used to run PROJ on. 

> I only see this in the README:

There's also [CONTRIBUTING.md](https://github.com/OSGeo/proj.4/blob/master/CONTRIBUTING.md#programming-language) which quite clearly states: "*PROJ.4 is developed strictly in ANSI C 89.*"

> I also don't see anything in the .travis.yml that states a version of C. If C89 is the target, then it seems that CI should have a test run that is explicitly C89.

It's not super obvious, but we set the C-standard in [CMakelists.txt](https://github.com/OSGeo/proj.4/blob/master/CMakeLists.txt#L25-L34). Wether that is picked up properly by Travis I don't know. I don't see a problem in adding `-std=c89` to the Travis setup.

**Comment by schwehr** [comment]
I have to admit that I don't know about C99 and C11 support.  I left the land of C and embedded systems back in the 90's.  This stackoverflow post and the answers are all pretty old...

https://stackoverflow.com/questions/139479/how-universally-is-c99-supported

I saw a while back that ESR started using C99 booleans for NTPsec: 

- http://esr.ibiblio.org/?p=6881
- https://blog.ntpsec.org/2017/01/03/getting-past-c.html
- https://github.com/ntpsec/ntpsec/blob/master/devel/hacking.txt#L37

**Comment by busstoptaktik** [comment]
But Microsoft has been foot-dragging in the Visual C support of C99, although some improvement has happened the last few years, older versions of the compilers are strictly C89/C90.

Even if MS pull their act together and land support for C99 before its 20 years birthday, we would probably have to wait another 5 years before realistically changing.

So for a long time, we will have to stick to C89. Horrible as it is, we must keep on working around the tripwires provided to us by the geniuses from Redmond.

**Comment by schwehr** [comment]
Roger.  Thanks for the explanation.  As usual, MSVC makes me sad.
