### ISSUE TITLE
geodtest fails on 32-bit windows

### ISSUE THREAD

**Issue by kbevers** [OSGeo/PROJ#715]
In #705 I have added the CMake tests to the AppVeyor CI suite. It trips up on the 32 bit targets. The error depends on which compiler is used. 

**Environment: BUILD_TYPE=cmake, VS_VERSION=Visual Studio 12; Platform: x86**
```
assertEquals fails: 1.834519e+007 != 1.834519e+007 +/- 2.5e-009
GeodSolve59 fail: 1
```

**Environment: BUILD_TYPE=cmake, VS_VERSION=Visual Studio 11; Platform: x86
Environment: BUILD_TYPE=cmake, VS_VERSION=Visual Studio 10; Platform: x86**
```
1/22 Test  #1: geodesic-test ....................***Failed    0.02 sec
assertEquals fails: 180 != -180 +/- 5e-006
GeodSolve61 fail: 1
```

I have not been able to reproduce the errors on my system. Probably because I am using the latest version of Visual Studio, which is not used on AppVeyor. 

Can these errprs be ignored since they only show up on more or less deprecated system architecures, or do we need to find a solution?

**Comment by kbevers** [comment]
Ping @cffk

**Comment by cffk** [comment]
I'll take a look!

**Comment by kbevers** [comment]
Thanks

**Comment by cffk** [comment]
The fix is straightforward:
* work around bugs in Visual Studio 1[012] implementations of fmod and sin with an arg of -0.0;
* relax an overly strict test in GeodSolve59.

I will push fixes this evening or tomorrow.
