### ISSUE TITLE
testing specific error codes on failure in gie doesn't work

### ISSUE THREAD

**Issue by kbevers** [OSGeo/PROJ#738]
The following should result in a failed test, but doesn't.

```
<gie>

operation   proj=urm5 n=5               # this returns PJD_ERR_N_OUT_OF_RANGE
expect      failure pjd_err_no_args     # this should result in a failed test

</gie>
```
Output from `gie`: 
```
λ gie fail-on-purpose.gie
-------------------------------------------------------------------------------
Reading file 'fail-on-purpose.gie'
-------------------------------------------------------------------------------   
proj=urm5 n=5                                                                     
-------------------------------------------------------------------------------   
total:  1 tests succeeded,   0 tests failed.                                      
-------------------------------------------------------------------------------   
```

It seems that `gie` in reality doesn't check if the returned error code matches the expected error code, and only checks if an error was received.

**Comment by busstoptaktik** [comment]
The syntax is

    expect      failure errno pjd_err_no_args

(note the **errno**). So the issue really is that I should write some more documentation. Currently it is "documented" by this comment in line 739:

            /* Option: Fail with an expected errno
                    (syntax: expect failure errno -33) */
