### ISSUE TITLE
Oblique Mercator can return NaN due to floating point error

### ISSUE THREAD

**Issue by kevinmehall** [OSGeo/PROJ#740]
With certain projections like `+proj=omerc +lat_0=39.6240459927611 +lonc=-106.0679650078805 +alpha=90 +k=1 +x_0=30515.1349056 +y_0=15222.3849984 +gamma=89.81222232007278 +ellps=WGS84 +units=ft +no_defs`, `proj` returns NaN for all coordinates on some platforms.

I've tracked down the source of this NaN to [the line](https://github.com/OSGeo/proj.4/blob/53b30f10c6e8d74a79b5d0763a53c5e1732e34b7/src/PJ_omerc.c#L185) `P->lam0 = lamc - asin(.5 * (F - 1. / F) * tan(gamma0)) / Q->B;` in PJ_omerc.c.

On Ubuntu 14.04 with GCC 4.8.4, the `.5 * (F - 1. / F) * tan(gamma0)` argument to `asin` ends up being `1.000000000000000222044604925031` which is greater than 1, resulting in `NaN`, while on macOS, it is `1.000000000000000000000000000000` and works properly.

I originally discovered this in gdalwarp, where it causes the following message when the NaN is cast to int:

```
Creating output file that is -2147483648P x -2147483648L.
ERROR 1: Attempt to create -2147483648x-2147483648 dataset is illegal,sizes must be larger than zero.
```

**Comment by kevinmehall** [comment]
I just reproduced this on Ubuntu 16.04 with proj 4.9.2 from Ubuntu's `proj-bin` package, which was presumably compiled with Ubuntu 16.04's GCC 5.4.0.

```
~ % proj
Rel. 4.9.2, 08 September 2015
usage: proj [ -beEfiIlormsStTvVwW [args] ] [ +opts[=arg] ] [ files ]
~ % echo -106.0679650078805 39.6240459927611 | proj +proj=omerc +lat_0=39.6240459927611 +lonc=-106.0679650078805 +alpha=90 +k=1 +x_0=30515.1349056 +y_0=15222.3849984 +gamma=89.81222232007278 +ellps=WGS84 +units=ft
nan	nan
```

I will also try compiling with an even more recent GCC.

**Comment by kevinmehall** [comment]
Also on NixOS with GCC 7.2.0, latest proj.4 from git:

```
$ nix-shell -p stdenv coreutils gcc7 git autoconf automake libtool which --pure
[nix-shell:/tmp]$ gcc -v
Using built-in specs.
COLLECT_GCC=/nix/store/z0ks81pzk2khcma5r1gzm8n12sad14z2-gcc-7.2.0/bin/gcc
COLLECT_LTO_WRAPPER=/nix/store/z0ks81pzk2khcma5r1gzm8n12sad14z2-gcc-7.2.0/libexec/gcc/x86_64-unknown-linux-gnu/7.2.0/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: 
Thread model: posix
gcc version 7.2.0 (GCC) 
[nix-shell:/tmp]$ git clone https://github.com/OSGeo/proj.4.git
[...]
[nix-shell:/tmp]$ cd proj.4/
[nix-shell:/tmp/proj.4]$ git rev-parse HEAD
53b30f10c6e8d74a79b5d0763a53c5e1732e34b7
[nix-shell:/tmp/proj.4]$ ./autogen.sh 
[...]
[nix-shell:/tmp/proj.4]$ ./configure
[...]
[nix-shell:/tmp/proj.4]$ make
[...]
[nix-shell:/tmp/proj.4]$ echo -106.0679650078805 39.6240459927611 | src/proj +proj=omerc +lat_0=39.6240459927611 +lonc=-106.0679650078805 +alpha=90 +k=1 +x_0=30515.1349056 +y_0=15222.3849984 +gamma=89.81222232007278 +ellps=WGS84 +units=ft
nan	nan
```

**Comment by kevinmehall** [comment]
Edit: ran the wrong test case. Also fails when compiled with clang 4.0.1 on NixOS.

**Comment by busstoptaktik** [comment]
This seems to be a fairly widespread problem, and one that Gerald Evenden had anticipated and solved by introducing the guarded arc-trig functions in aasincos.c

I'll try to repair this in a moment, by switching `asin` to `aasin`. The guarded `aasin` is a bit slower than raw `asin`, but since all calls to `asin` are in the setup code, it will not affect the general run time.

@kevinmehall - could you please check that this works? On my Windows 10, system I ran your test example,

    $  echo -106.0679650078805 39.6240459927611 | bin\Debug\proj_d +proj=omerc +lat_0=39.6240459927611 +lonc=-106.0679650078805 +alpha=90 +k=1 +x_0=30515.1349056 +y_0=15222.3849984 +gamma=89.81222232007278 +ellps=WGS84 +units=ft

And got this reply:

    100115.27       49942.21

Is this what you'd expect?

**Comment by kevinmehall** [comment]
Thanks! I can confirm this fix works both with the `proj` command above, and when linked into GDAL, for the original geoTIFF file where I discovered this problem.
