### ISSUE TITLE
axis parameter in PJ_axisswap buggy

### ISSUE THREAD

**Issue by busstoptaktik** [OSGeo/PROJ#741]
This gie test:
```
operation   proj=axisswap axis=nue
tolerance   0.000001 m
accept      1 2 3
expect      3 1 2
```
fails with:
```
FAILURE in whatever.gie(10):
expected: 3 1 2
got:      2.000000000   3.000000000   1.000000000
```

**Comment by busstoptaktik** [comment]
(@kbevers actually the bug seems to be in the development version of gie - these quadruple negations are really hard to get right).

Closing this, as unfounded.

**Comment by kbevers** [comment]
It is likely that there's a bug somewhere, but in this case it seem to be your test that is wrong. Don't know if you are still using that, though.

Nevertheless, in the `+axis` -> `+order` conversion, n=2, u=3 and e=1. So the returned result is correct in the above test.

**Comment by busstoptaktik** [comment]
Accept: n=1 u=2 e=3 since +axis=nue, so output should be 312, (enu) but the output is 231, i.e. (uen) - or am I more confused than I think?

**Comment by busstoptaktik** [comment]
Probably just another element of cascaded inversions in gie. In the forward direction, nue=123 should be swapped to enu, i.e. 312.

**Comment by busstoptaktik** [comment]
> Probably just another element of cascaded inversions in gie. In the forward direction, nue=123 should be swapped to enu, i.e. 312.

Well, actually not: It appears there is a bug in the handling of the `+axis` parameter, due to a subtle semantic difference in the meaning of the `+axis` and `+order` parameters:

The `+order` parameter ***pre**scribes* which input coordinate should go to which position on output

The `+axis` parameter ***de**scribes* the order of input coordinates, making it up to axisswap to determine where they should go on output.

(behaviour in the forward direction, that is)

Essentially, in the 3D cases, these operations are mutual inverses. So when `+axis` is specified, forward and inverse methods change place.

The reason this was not caught in the `axisswap.gie` test cases is that it only contained cases where n,e are swapped - not any where u is swapped with one of e,n, and a mutual swap of two is identically treated in forward and inverse directions.

Due to problems running `git stash` here, I will have to correct this as part of the work on PR #731. Hope you'll live with it: We got to get this wrapped up to get ready for RC-0.

UPDATE: Repaired by setting P->inverted to 1 when `+axis` is specified. This works as intended, and leaves room for inline update later, if considered necessary. Otherwise, I will close this as #731 is merged.

UPDATE2: Reverted this, as the entire analysis seems wrong, and related to a multi layered number of inversions - in other words: One of the bugs, where you can correct the bug by introducing the same bug once more.

Currently, however, I believe the bug has been corrected by undoing unneeded inversions.

**Comment by busstoptaktik** [comment]
Closing (see UPDATE2 above)
