### ISSUE TITLE
Incorrect definition of CRS EPSG 5456 and EPSG 5457

### ISSUE THREAD

**Issue by edurojasr** [OSGeo/PROJ#742]
my name is Eduardo Rojas Rodríguez I am a Geographer specialized in GIS, I live in Costa Rica and I work for SOLTIG who are the official commercial support of QGIS in Costa Rica. 

In the most current library of PROJ4. I realized that the definition of EPSG 5456 and EPSG 5457 are incorrect

so I kindly want to request a replacement of definitions

EPSG 5456 current definition in PROJ4: (**incorrect**) 
+proj=lcc +lat_1=10.46666666666667 +lat_0=10.46666666666667 
+lon_0=-84.33333333333333 +k_0=0.99995696 +x_0=500000 +y_0=271820.522 
+ellps=clrk66 +towgs84=205,96,-98,0,0,0,0 +units=m +no_defs 

EPSG 5457 current definition in PROJ4: (**incorrect**) 
+proj=lcc +lat_1=9 +lat_0=9 +lon_0=-83.66666666666667 +k_0=0.99995696 
+x_0=500000 +y_0=327987.436 +ellps=clrk66 +towgs84=205,96,-98,0,0,0,0 
+units=m +no_defs 

must be replaced by

EPSG 5456: Ocotepeque 1935 / Costa Rica Norte (**correct definition**) 
+proj=lcc +lat_0=10.46666666666667  +lat_1=9.933333333 +lat_2=11 
+lon_0=-84.3333333333 +k_0=0.99995696 +x_0=500000 +y_0=271820.522 
+ellps=clrk66 +towgs84=213.116,9.358,-74.946,1.140,-2.980,3.100,-5.22 
+units=m +no_defs 

EPSG: 5457: Ocotepeque 1935 / Costa Rica Sur (**correct definition**) 
+proj=lcc +lat_0=9 +lat_1=8.4666666667+lat_2=9.533333333 
+lon_0=-83.666666667 +k_0=0.99995696 +x_0=500000 +y_0=327987.436 
+ellps=clrk66 +towgs84=213.116,9.358,-74.946,1.140,-2.980,3.100,-5.22 
+units=m +no_defs 

thank you very much

**Comment by kbevers** [comment]
[The discussion on the mailing list](http://lists.maptools.org/pipermail/proj/2018-January/007950.html) has concluded that the two systems are in fact not defined incorrectly in the `epsg` file.
