### ISSUE TITLE
pj_get_def() broken in 5.0.0

### ISSUE THREAD

**Issue by rsbivand** [OSGeo/PROJ#744]
`pj_get_def()` truncates output. In sp/rgdal, CRS are checked by running through `pj_get_def` to trap errors and to add in missing defaults. @edzer, sf does the same in checking CRS validity.

```
#include <stdio.h>
#include <proj_api.h>

int main(void) {

	projPJ pj;
        pj = pj_init_plus("+proj=longlat");
        printf("description: %s\n", pj_get_def(pj, 0));
        pj_free(pj);
        exit(0);
}
```

5.0.0:

```
$ gcc -I/usr/local/include -L/usr/local/libs -lproj -o CRS_test CRS_test.c
$ ./CRS_test
description:  +ellps=WGS84
```

4.9.3 (same executable):

```
$ ./CRS_test
description:  +proj=longlat +ellps=WGS84
```

**Comment by rsbivand** [comment]
The only change in `pj_pr_list.c` is:
```
    if (!definition)
        return NULL;
```
after `pj_malloc` so something has changed in `P->params` when accessing the defaults.

It also truncates "+proj=longlat +ellps=WGS84" to "+ellps=WGS84", so I'm afraid that it isn't the `share/proj/proj_def.dat` lookup. With:
```
"+proj=stere +lat_0=52.15616055555555 +lon_0=5.38763888888889 +k=0.999908 +x_0=155000 +y_0=463000 +ellps=bessel +towgs84=565.237,50.0087,465.658,-0.406857,0.350733,-1.87035,4.0812 +units=m"
```
the 5.0.0 `pj_get_def` gives:
```
description:  +lat_0=52.15616055555555 +lon_0=5.38763888888889 +k=0.999908 +x_0=155000 +y_0=463000 +ellps=bessel +towgs84=565.237,50.0087,465.658,-0.406857,0.350733,-1.87035,4.0812 +units=m
```
Putting `+proj=` as the last component, it also gets dropped, so the new structure of PJ reached through the old API drops the +proj parameter as if by design.

**Comment by kbevers** [comment]
It is somewhere else, yes. The behaviour can also be seen just by using `proj`:

```
λ proj.exe -V +proj=merc +lat_0=23
#Mercator
#       Cyl, Sph&Ell
#       lat_ts=
# +lat_0=23 +ellps=WGS84
#--- following specified but NOT used
# +proj=merc
#Final Earth figure: ellipsoid
#  Major axis (a): 6378137.000
#  1/flattening: 298.257224
#  squared eccentricity: 0.006694379990
```

Nice catch. I'll try find the root cause for this.

**Comment by rsbivand** [comment]
Confirmed that b6c3d16 fixes missing tag issues in rgdal, thanks!
