### ISSUE TITLE
autoconf / configure not working

### ISSUE THREAD

**Issue by edzer** [OSGeo/PROJ#745]
I'm trying to install this, but get (ubuntu 17.04):
```
$ autoconf
configure.ac:9: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:10: error: possibly undefined macro: AM_CONFIG_HEADER
configure.ac:21: error: possibly undefined macro: AM_PROG_LIBTOOL
```
and then
```
./configure
configure: error: cannot find install-sh, install.sh, or shtool in . "."/.
```
and after copying `install.sh` from ./travis
```
$ ./configure
./configure: line 2198: AM_INIT_AUTOMAKE: command not found
./configure: line 2199: syntax error near unexpected token `src/proj_config.h'
./configure: line 2199: `AM_CONFIG_HEADER(src/proj_config.h)'
```
I read `README` and `INSTALL` and the error messages above, but none of them help me getting close to the first steps of installing your release candidate.

**Comment by rsbivand** [comment]
I suspect `automake` - I think I remember that from trying to build proj4 5.0.0 in November.

**Comment by kbevers** [comment]
You are building from the git repo, yes? Try `./autogen.sh` instead of `autoconf`

**Comment by edzer** [comment]
`./autogen.sh` followed by `automake`, followed by `./configure` worked. Some hints to this somewhere might make sense if you want people to test from here -  or do you rather want testers to wait for pre-release tar balls?
