### ISSUE TITLE
master regression: pj_get_def() removes +init= parameters

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#752]
With master, pj_get_def("+init=....") somethings returns "+proj=... other_parameters", whereas proj 4.x returns "+init=.... +proj=... other_parameters". This breaks a regression test in GDAL. I'm not sure if this is in an intended change or not. This could be easily fixed on the GDAL side as well

**Comment by kbevers** [comment]
I think this is a consequence of using the new `pj_param_exists()` function which doesn't change the `used` variable of the parameter. Since it also returns the parameter it checks for I think it should mark the parameter as used. I'll make a PR for this.
