### ISSUE TITLE
Windows: 'LP': redefinition; different type modifiers

### ISSUE THREAD

**Issue by c0nk** [OSGeo/PROJ#782]
LP is a typedef declared in the standard window headers. This makes it a compile error to include <windows.h> and <proj.h> together. Would it be possible to rename LP to PJ_LP to avoid this for the 5.0 release? If so, it would make sense to prefix UV XY, XYZ, UVW, LPZ with PJ_ as well.

**Comment by kbevers** [comment]
Way ahead of you: https://github.com/OSGeo/proj.4/pull/781

**Comment by c0nk** [comment]
Sweet, good work.
