### ISSUE TITLE
cmake and PROJ4 version compatibility

### ISSUE THREAD

**Issue by cffk** [OSGeo/PROJ#796]
The version compatibility code in ``proj4-config-version.cmake`` is as follows

    if (PACKAGE_FIND_VERSION VERSION_EQUAL PACKAGE_VERSION)
      set (PACKAGE_VERSION_EXACT TRUE)
    elseif (PACKAGE_FIND_VERSION VERSION_LESS PACKAGE_VERSION
      AND PACKAGE_FIND_VERSION_MAJOR EQUAL PACKAGE_VERSION_MAJOR)
     set (PACKAGE_VERSION_COMPATIBLE TRUE)

This means that ``find_package(PROJ4 4.9)`` *won't* find version 5.x.  I think that this is probably OK.  But I'm highlighting the issue in case we want this to succeed.  (And that's easy to do.)

**Comment by hobu** [comment]
> This means that `find_package(PROJ4 4.9)` won't find version 5.x.

I think this is ok

**Comment by kbevers** [comment]
I reckon this was solved with the merge of #789. Please re-open if I have misunderstood the purpose of this issue.
