### ISSUE TITLE
Remove legacy CMake target name "proj"

### ISSUE THREAD

**Issue by kbevers** [OSGeo/PROJ#802]
In #789 @cffk lays out the plan to move PROJ into a namespace that follows current best practice. This ticket schedules part 3 of the plan to the PROJ 7.0.0 release where only one CMake target will be available onwards. This breaks backwards compatibility. The target is PROJ4::proj and PROJ4_LIBRARIES = PROJ4::proj.

**Comment by kbevers** [comment]
@cffk I have assigned this ticket to you in case you want to change the wording to something more accurate. Feel free to unassign yourself if you are happy with the description above.

**Comment by cffk** [comment]
@kbevers This is fine.  Feel free to remind me about this again when 7.0.0 is imminent.

**Comment by kbevers** [comment]
You will be duly notified in the beginning of 2020 :)

**Comment by mwtoews** [comment]
> You will be duly notified in the beginning of 2020 :)

Oh look, the future has finally arrived! @cffk are you OK to proceed with this?

**Comment by cffk** [comment]
Sure, I'll undertake this.  It might also be a good time to revisit the
decision made a couple of years ago to stick with "PROJ4" as the
cmake project name.  Perhaps, we can make it that there's a
graceful transition from PROJ4 to PROJ.

**Comment by kbevers** [comment]
Yes, it would be nice to smoothly transition into just "PROJ". I'll let you guys come with a suggestion for how to best to do that (you understand CMake a lot better than I do!).
