### ISSUE TITLE
Add user-specifiable output format in cct

### ISSUE THREAD

**Issue by kbevers** [OSGeo/PROJ#807]
In `proj` and `cs2cs` we have the option to add the `-f` flag and specify how output coordinates are printed on screen. This should also be possible in `cct`. Preferably in a way that avoids recreating https://github.com/OSGeo/proj.4/issues/124.

The most important thing here is to let users control the number of decimals `cct` returns.

**Comment by busstoptaktik** [comment]
I intend to implement this by letting the user specify required precision **in meter**, e.g. specifying millimetric resolution by saying -p 0.001, -p mm or -p 1e-3.

For linear output, this translates straightforwardly to number of decimals.

For angular output I would probably start by saying 1 degree == 100000 m, so -p mm would translate into 8 decimals.

**Comment by kbevers** [comment]
Just to make things clear, this is best handled by @busstoptaktik's approach. Ideally this would also be extended to `proj` and `cs2cs` at some point.

**Comment by sgh** [comment]
Ok. So `-p 1e-4` would give 9 decimals on angles if I follow you correctly?

**Comment by rouault** [comment]
@busstoptaktik The approximation 1 degree == 100000 m only holds for Earth, and PROJ is definitely used with other celestial bodies. That would mean we would need to examine the pipeline to fetch the first mention of a semi-major axis ?

**Comment by kbevers** [comment]
> That would mean we would need to examine the pipeline to fetch the first mention of a semi-major axis ?

Yes. Should be quite easy since the main `PJ` object always has ellipsoid parameters attached to it. In case of pipelines there is the possibility that the "main ellipsoid" isn't the same as the ellipsoid representing the output coordinates but I am betting it will always at least resemble the celestial body that it is meant to represent. So, `deg_length = 2 * M_PI * P->a * 1/360` should be good enough for this application.

**Comment by busstoptaktik** [comment]
> So, deg_length = 2 * M_PI * P->a * 1/360 should be good enough for this application.

Yes, that was what I intended, although for semimajor axes in the Earth like interval 6200 km-6600 km, I would default directly to L<sub>deg</sub>=100 km

**Comment by kbevers** [comment]
> although for semimajor axes in the Earth like interval 6200 km-6600 km, I would default directly to Ldeg=100 km

So you would have a special case for Earth and do it generically for longer/shorter semimajor axes?

**Comment by busstoptaktik** [comment]
> So you would have a special case for Earth and do it generically for longer/shorter semimajor axes?

Depending on the rounding employed (I have not checked in detail), it is probably not be necessary to special case it. What I want to avoid, however, is getting a different number of decimals when requesting the same base unit (mm, cm, etc.) for, say, the Hayford ellipsoid vs. the GRS80 ellipsoid.

**Comment by sgh** [comment]
From a non-geodesist perspective (me) it would be much easier and cleaner just to specify the extra number of decimals in the output. I guess it all depends on what reason people have wanting that extra resolution.

**Comment by kbevers** [comment]
> What I want to avoid, however, is getting a different number of decimals when requesting the same base unit (mm, cm, etc.) for, say, the Hayford ellipsoid vs. the GRS80 ellipsoid.

I think you'll be fine if you round to say the nearest kilometer:

```
In [6]: 2*math.pi*6370997*(1/360) / 1000
Out[6]: 111.19487428468118

In [7]: 2*math.pi*6378245*(1/360) / 1000
Out[7]: 111.32137574886573

In [8]: 2*math.pi*6378137*(1/360) / 1000
Out[8]: 111.31949079327359
```

That's calculated for semimajor axes of `sphere`, `hayford` og `GRS80`.

**Comment by kbevers** [comment]
> From a non-geodesist perspective (me) it would be much easier and cleaner just to specify the extra number of decimals in the output. I guess it all depends on what reason people have wanting that extra resolution.

I have had this in the back of my mind the last couple of days. I think it's a fine balance between forcing users of the software to think about what they are doing, ease of use and what is simply just practical. Specifying a set amount of decimals  ticks the last two boxes. The method suggested here ticks the first and to some extend the last two.

Seeing as these two approaches to determining how `cct` outputs coordinates are not mutually exclusive we should consider having both. Using `-d` for a set amount of decimals and `-p` for setting the desired level of precision of the output, possibly returning a variable number of decimals. Both `-d` and `-p` are unused in `proj` and `cs2cs` so this could even be extended to those applications giving room to eventually removing the `-f` which poses a potential security risk (as described in #124).

@busstoptaktik, @rouault, @sgh What are you thoughts on this?

**Comment by rouault** [comment]
@kbevers Yes I was thinking that having both decimal control and precision control could solve all use cases

**Comment by sgh** [comment]
It sound great. At least I can implement `-d` in both proj,cct and probably also cs2cs. `-p` is a bit more tricky since it requires an extension to the api to query the contents of `PJ` - unless we wan just include the private headers (I guess that is ok)

**Comment by kbevers** [comment]
I take that as a yes to move on with both.

> At least I can implement -d in both proj,cct and probably also cs2cs

@sgh That would be very appreciated, thanks. I believe `proj` and `cs2cs` are quite similar in this regard.

> -p is a bit more tricky since it requires an extension to the api to query the contents of PJ - unless we wan just include the private headers (I guess that is ok)

This would be a good occasion to extend [`PJ_PROJ_INFO`](https://proj4.org/development/reference/datatypes.html#c.PJ_PROJ_INFO) with some ellipsoid parameters. Or possibly adding a `proj_ellps_info` function that returns a struct with all the details.

**Comment by busstoptaktik** [comment]
> ... adding a `proj_ellps_info` function that returns a struct with all the details.

By and large, that struct is embedded in the PJ-object, cf. the section "ellipsoid parameters" around line 300 of `projects.h`.

When introducing all the esoteric parameters, I considered making it an actual struct, rather than a section of the `PJ` object, but that would change the access syntax from `P->a` to something like `P->ellipsoid_parameters.a` or  (introducing another level of indirection) `P->ellipsoid_parameters->a`, and similar for other ellipsoidal parameters (using C++ inheritance this would probably be simpler).

Under all circumstances, I think that the entire block of esoteric parameters should be returned by `proj_ellps_info`: They are there because, through the history of geodesy, each has shown to be useful for some computation or another (like some expressions are simpler when written terms of eccentricity, while some are simpler - or converge faster - in terms of flattening).

While not actually costly to compute, computing them once during construction of `PJ`, then amortizing the cost over (say) the transformation of a million points is preferable to having to recompute at each call to `proj_trans`. Also, it centralized the computation of ellipsoidal parameters, rather than potentially repeating the stuff everywhere needed (YAGNI or not :-)).

**Comment by busstoptaktik** [comment]
@kbevers opined:
> I think you'll be fine if you round to say the nearest kilometer

Actually it's even simpler:

111000/0.001 (i.e. mm) = 111000000,
log10(111000000) = 8.04, so

`floor (log10 (L/q))`, or maybe
`floor (log10 (L/q) + 0.5)`,


where `L` is the length of one degree, and `q` is the quantification desired, should do the job. No rounding needed before the `floor` operation

**Comment by sgh** [comment]
hmm ... cs2cs uses `-d` for debuglevel. What do you propose to do about that?

**Comment by kbevers** [comment]
Hmm... I didn't even realize that. That feature does not seem to have been documented previously so I doubt many is aware of it's existence (I wasn't at least...).

In the long run I would like to see `proj`, `cs2cs` and `cct` converge towards similar interfaces so I think it is worthwhile to remap the `-d` option of `cs2cs`. I suggest remapping the current `-d` to `-D` and using `-d` for setting the number of decimals. @busstoptaktik @rouault please share your thoughts on this approach.

**Comment by rouault** [comment]
I wasn't aware at all of cs2cs -d. Undocumted indeed so unlikely to break people. That said, I'm wondering what the future of cs2cs is. If pj_transform() is ultimately removed (proj 7 ?), will it also be the case of cs2cs ?

**Comment by kbevers** [comment]
> That said, I'm wondering what the future of cs2cs is. If pj_transform() is ultimately removed (proj 7 ?), will it also be the case of cs2cs ?

I imagine that we will be keeping it around as a CLI front for `proj_create_crs_to_crs()` when `pj_transform()` is gone. They are meant to serve similar purposes after all. `cs2cs` is useful to users that want a simple way to transform between two CRS's and I don't see that need going away anytime soon. With your GDALbarn work it has the potential to be a lot better than what it is currently. We may need to extend it to 4D at some point though.

**Comment by busstoptaktik** [comment]
@kbevers said:
>  I suggest remapping the current -d to -D and using -d for setting the number of decimals. @busstoptaktik @rouault please share your thoughts on this approach.

Alternatively, keep the undocumented `-d` thingy, and use `-D` for setting number of decimals?

**Comment by kbevers** [comment]
> Alternatively, keep the undocumented -d thingy, and use -D for setting number of decimals?

That is also an option. And certainly better in terms of continuity. Still, I prefer to use the slightly simpler to type `-d` for the functionality that will be used the most. Unless you have a strong resistance to that approach I think we should go with `-d`. Agree?

**Comment by busstoptaktik** [comment]
> Unless you have a strong resistance to that approach I think we should go with -d. Agree?

No hard preference - I think neither -d and -D will be often-used. If @sgh is willing to do the option-swapping, it's fine with me - if not, the (very slightly) simpler approach of keeping -d and introducing -D for decimals would be fine as well: I defer to whatever @kbevers  and @sgh can agree on
