### ISSUE TITLE
Pole encircling logic in geod_polygon_addedge is bad

### ISSUE THREAD

**Issue by cffk** [OSGeo/PROJ#812]
This test (soon to be added to `geodtest.c`)

    static int AddEdge1() {
      /* Check fix to transitdirect vs transit zero handling inconsistency */
      struct geod_geodesic g;
      struct geod_polygon p;
      double area;
      int result = 0;
      geod_init(&g, wgs84_a, wgs84_f);
      geod_polygon_init(&p, 0);
      geod_polygon_addpoint(&g, &p, 0.0, 0.0);
      geod_polygon_addedge(&g, &p, 90.0, 1000.0);
      geod_polygon_addedge(&g, &p,  0.0, 1000.0);
      geod_polygon_addedge(&g, &p,-90.0, 1000.0);
      geod_polygon_compute(&g, &p, 0, 1, &area, 0);
      result += assertEquals(area, 1000000.0, 0.01);
      return result;
    }

should return 1000000.00 m^2 as the area.  Instead it gets -2.550328e+14
m^2.  The problem is in inconsistent treatment of longitude = 0 by
geod_polygon_addedge and geod_polygon_addpoint.  I have this fixed in my
code base and will be making a pull request this weekend.  (I'm wanting
also to add additional tests to improve the code coverage.)

This is an outright *BUG* and I'm hoping it can make it into
release 5.0.0.  Nothing in the rest of the proj code base calls
`geod_polygon_addedge`, so incorporating this last-minute fix should be
low-risk.

**Comment by kbevers** [comment]
Sounds like a reasonable thing fix to include in 5.0.0, although very last minute.

I was going to put out RC5 this afternoon.  Can you give a rough estimate on when you expect the fix to be ready? I know you said the weekend, but when in the weekend? I don't want to prolong the release process too much if it can be avoided. March 1st is still the release date and I want to give people some time for testing as well.

**Comment by cffk** [comment]
I'll make the pull request Saturday morning (my time) -- around midday
in Western Europe.  Maybe I'll do the bug fix and the single test before
midnight today (Thurs), with the additional coverage tests (in geodtest.c) on
Sat morning.
