### ISSUE TITLE
mac osx geodtest fails

### ISSUE THREAD

**Issue by mikehagerty** [OSGeo/PROJ#831]
I seem to have the same issue as #826 (geodtest fail on intel) on mac OS X 10.10 (gcc-4.9):

> more src/test-suite.log
==================================================
   PROJ.4 Projections 5.0.0: src/test-suite.log
==================================================
#TOTAL: 1
#PASS:  0
#SKIP:  0
#XFAIL: 0
#FAIL:  1
#XPASS: 0
#ERROR: 0
FAIL: geodtest
==============

assertEquals fails: 180 != -180 +/- 5e-06
GeodSolve61 fail: 1
FAIL geodtest (exit status: 1)

gcc does not appear to like the -fp-model precise CFLAG.
This appears to be an intel flag that doesn't work with mac (?)

Also, from what I can tell, 'precise' is suppose to be the default setting
for GCC/CLANG.

Any suggestions would be appreciated.

Thanks!

**Comment by cffk** [comment]
There are two tests of lon2 == -180 in GeodSolve61 and only one of them is failing.  They are on lines 523 and 528 of geodtest.c.  Could you please figure out which one is failing?  Also could you try the test with all optimization turned off (-O0)?

Also can you check whether this problem happens with the previous version of proj?

Thanks.

**Comment by cffk** [comment]
The test failure you're seeing is consistent with `sin(-0.0)` returning `0.0` instead of `-0.0`.  Perhaps you can check this on your system.  I already have a workaround for this bug (that's what it is) for old versions of Visual Studio; see line 248 in geodesic.c.  If this is the problem, then could you figure out how to modify the test at line 248 to include your system?  (While you're about it, could you also determine whether `fmod(-0.0, 360.0)` returns `-0.0`?)

**Comment by mikehagerty** [comment]
Hi Charles,

Sorry, I just saw your mails.

1. It's the first test (line 523) that fails.

2. sine(-0.0) looks right:

  MTH line 523: sin(0.0)=0.000000 sin(-0.0)=-0.000000

3. -O0 (optimization off) didn't fix it.

It's late here, I'll try to look at it tomorrow.

Cheers,
-Mike

**Comment by mikehagerty** [comment]
Correction:

3. Turning off optimization (-O0) *does* fix the test fail.  I must not
have been done a clean compile last night.

Cheers,
-Mike

**Comment by cffk** [comment]
Please apply these patches (to print out some debuggining information)

[patch.txt](https://github.com/OSGeo/proj.4/files/1776203/patch.txt)

and run the tests again (with optimizations turned on), e.g., with

    make clean && make && ./bin/geodtest

and post the results.  Thanks.

**Comment by mikehagerty** [comment]
Here it is (the "MTH" lines are my debug msgs left in)

mth@Mikes-MBP [~/mth/Programs/zpkg_git/proj.4]> m src/test-suite.log
==================================================
   PROJ.4 Projections 5.0.0: src/test-suite.log
==================================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: geodtest
==============

azi1: -3e-18
azi1 rounded: -0
salp1: 0
salp0: 0
somg1: 0
A3c -0.0000000
E HAVE_C99_MATH: 1 1
somg2: 0
flags & GEOD_LONG_UNROLL 32768
sig12 1.568808
atan2(ssig2, csig2) 2.352527
atan2(l->ssig1, l->csig1) 0.7837189
atan2(E * somg2, comg2), 3.141593
atan2(E * l->somg1, l->comg1) 0
omg12 3.141593
MTH line 522: lat2=45.306319 result=0
assertEquals fails: 180 != -180 +/- 5e-06
MTH line 523: lon2=180.000000 result=1 should be -180
MTH line 523: sin(0.0)=0.000000 sin(-0.0)=-0.000000
salp0: -0
somg1: -0
A3c 0.0000000
E HAVE_C99_MATH: -1 1
somg2: -0
flags & GEOD_LONG_UNROLL 32768
sig12 1.568808
atan2(ssig2, csig2) 2.352527
atan2(l->ssig1, l->csig1) 0.7837189
atan2(E * somg2, comg2), 3.141593
atan2(E * l->somg1, l->comg1) 0
omg12 -3.141593
MTH line 528: lon2=-180.000000 result=1
GeodSolve61 fail: 1
FAIL geodtest (exit status: 1)

**Comment by cffk** [comment]
It's definitely looking like `sin(-0.0)` is returning `+0.0`.  Perhaps your
test before didn't uncover the problem because the compiler evaluated
the sine of a constant expression.

So please try again, changing the `_MSC_VER` conditional in the function
`sincosdx` from

    #if defined(_MSC_VER) && _MSC_VER < 1900

to

    #if 1 /* defined(_MSC_VER) && _MSC_VER < 1900 */

(There's a similar conditional in `AngNormalize`.  Make sure you change
the one in `sincosdx`.)

**Comment by cffk** [comment]
@mikehagerty Any luck running this test?  (I'm dependent on you, since I can't run this compiler!)

**Comment by mikehagerty** [comment]
Hi Charles,
Sorry for the delay - mail from github seems to get automatically sorted
into my Updates folder
which I rarely check.

Anyhow, your fix (below) does in fact work - all tests passed!

So maybe sin(x) = +0.0 when x=-0.0 ... but not if x is defined as a
constant (?)
Maybe when you use x as above, it's not exactly zero and that tips it over.

Cheers,
-Mike

**Comment by cffk** [comment]
@mikehagerty All I need now is to figure out how to detect your compiler.  Please send me the output of

    gcc -dM -E - < /dev/null

which prints out all the predefined macros.

**Comment by mikehagerty** [comment]
Attached is the gcc output.

Cheers,
-Mike

**Comment by cffk** [comment]
@mikehagerty The attachment got swallowed somewhere.  Please attach directly on the github web site (or E-mail to charles@karney.com).

**Comment by cffk** [comment]
@mikehagerty I propose the following patch (to an unmodified geodesic.c):

    diff --git a/src/geodesic.c b/src/geodesic.c
    index 23557b5c..8cb9cc2e 100644
    --- a/src/geodesic.c
    +++ b/src/geodesic.c
    @@ -245,7 +245,8 @@ static void sincosdx(real x, real* sinx, real* cosx) {
       r *= degree;
       /* Possibly could call the gnu extension sincos */
       s = sin(r); c = cos(r);
    -#if defined(_MSC_VER) && _MSC_VER < 1900
    +#if (defined(_MSC_VER) && _MSC_VER < 1900) || \
    +  (defined(__APPLE__) && __APPLE__ && !(defined(__clang__) && __clang__))
       /*
         Before version 14 (2015), Visual Studio had problems dealing
         with -0.0.  Specifically
    @@ -253,6 +254,10 @@ static void sincosdx(real x, real* sinx, real* cosx) {
           VC 12       and 64-bit compile:  sin(-0.0)        -> +0.0
         AngNormalize has a similar fix.
         python 2.7 on Windows 32-bit machines has the same problem.
    +
    +    A similar problem infects Mac OS X 10.10 (gcc 4.9).  The
    +      __APPLE__ && !__clang__
    +    test is an attempt to capture this.
       */
       if (x == 0) s = x;
     #endif

Please check that this indeed fixes the problem.

**Comment by mikehagerty** [comment]
This seems to work, thanks!

By the way, if I try to do a clean install by cloning from github,
there is no ./configure or ./Makefile present.
I realize these have to be generated from autogen or autoconf or something
similar, but there are no
instructions in the INSTALL file.

I got it working at one point, but today I can't remember how I did that,
so I had to copy the src/
dir into my working dir to compile.

Anyhow, an added instruction step or two before 'make' (or cmake) in the
INSTALL file would be helpful
(e.g., how to generate ./configure).

Cheers!
-Mike

**Comment by kbevers** [comment]
>By the way, if I try to do a clean install by cloning from github,
there is no ./configure or ./Makefile present.
I realize these have to be generated from autogen or autoconf or something
similar, but there are no
instructions in the INSTALL file.


It is in the README: https://github.com/OSGeo/proj.4/blob/master/README.md#building-from-the-git-repository

You could argue that the INSTALL file is instructions for building from the source distribution only.

**Comment by cffk** [comment]
@mikehagerty I don't like my solution (making the `#if` condition more
complicated) because (a) I doubt the new condition is exactly right and
(b) I still don't understand why you're getting this behavior while, on
my Mac OS X system (admittedly a different version), I don't.

Perusing the various flags the gcc compiler takes I notice two that are
relevant to this case:

    -fsigned-zeros
    -fno-associative-math

These are both the default flags.  However if you're running with

    -funsafe-math-optimizations

then this implies

    -fno-signed-zeros
    -fassociative-math

So could you (a) check whether you're compiling with
`-funsafe-math-optimizations` and (b) try adding `-fsigned-zeros
-fno-associative-math` to the flags for the C compiler.

Thanks.

**Comment by mikehagerty** [comment]
Hi Charles,

So, I'm a bit rusty on my Makefiles (and I haven't made the switch to cmake
yet, except for a few projects), but it seems to me
that the CFLAGS are being set explicitly in both proj.4/Makefile and
proj.4/src/Makefile.

I added the "-fsigned-zeros -fno-associative-math" flags as you suggested
to both Makefiles, then
recompiled the source and re-ran the test.  It failed:

assertEquals fails: 180 != -180 +/- 5e-06
GeodSolve61 fail: 1
FAIL geodtest (exit status: 1)

I can see on the stdout messages that the CLFAGS used are:

CFLAGS=-g -O2 -DHAVE_C99_MATH=1 -fsigned-zeros -fno-associative-math

It seems like if -funsafe-math-optimizations was somehow implicitly set,
these would override it (?)

Can I ask what version gcc you are using with your mac osx ?  If I'm
feeling ambitious I can upgrade and
see if it fixes it.

Cheers,
-Mike

**Comment by cffk** [comment]
I don't have the latest OS on my Mac.  Here what I get with

    $ gcc --version

    Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
    Apple LLVM version 8.0.0 (clang-800.0.42.1)
    Target: x86_64-apple-darwin15.6.0
    Thread model: posix
    InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

You will see that the backend is clang (the default, I assume, when I installed XCode).  The Mac is not my main platform, so I don't offhand know all the ins and outs of switching to a different backend.

**Comment by cffk** [comment]
@mikehagerty I'd like to see this issue addressed first as a compiler
issue, either determining which flags are needed to fix the problem or
reporting it as a compiler bug.

I believe that the following simple C program, `test0.c`, should
illustrate the bug:

    #include <stdio.h>
    #include <math.h>

    int main() {
      double x, y, z;
      while (scanf("%lf", &x) == 1) {
        y = sin(x);
        z = 0.0 + x;
        printf("%.2f %.2f %.2f\n", x, y, z);
      }
    }

Compile and run this with

    cc -O2 -o test0 test0.c -lm && echo -e "0.0\n-0.0" | ./test0

(modify the compiler name and add additional compiler flags, if
necessary).  With a well-behaved compiler, this should print:

    0.00 0.00 0.00
    -0.00 -0.00 0.00

Could you report what you get?

**Comment by mikehagerty** [comment]
Hi Charles,

I'm glad you posted your gcc info.  You have the apple backend (llvm) from
Xcode.
Thus far, I have been doing all building/testing with gcc4.9.1 installed
from
the Fink package manager (the info is below).  It doesn't use the llvm
backend.

However, I just tried switching compilers to the llvm (same version as
yours) and
the tests pass.

Also, I tried out the test0.c code you suggested, with the original
non-llvm compiler and
the outputs are exactly as you indicated.

I'll post the two compiler infos below.
I can't remember the arguments for/against llvm, but I was under the
impression that
non-llvm gcc was more portable/general (or maybe llvm is no longer updated
in Xcode ?).

Cheers,

-Mike

*1. The non-llvm gcc:*

mth@Mikes-MBP [~/mth/Programs/zpkg_git/proj.4]> gcc -v
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/sw/lib/gcc4.9/libexec/gcc/x86_64-apple-darwin13.3.0/4.9.1/lto-wrapper
Target: x86_64-apple-darwin13.3.0
Configured with: ../gcc-4.9.1/configure --prefix=/sw
--prefix=/sw/lib/gcc4.9 --mandir=/sw/share/man
--infodir=/sw/lib/gcc4.9/info
--enable-languages=c,c++,fortran,lto,objc,obj-c++,java --with-gmp=/sw
--with-libiconv-prefix=/sw --with-isl=/sw --with-cloog=/sw --with-mpc=/sw
--with-system-zlib --x-includes=/usr/X11R6/include
--x-libraries=/usr/X11R6/lib --program-suffix=-fsf-4.9
Thread model: posix
gcc version 4.9.1 (GCC)

mth@Mikes-MBP [~/mth/Programs/zpkg_git/proj.4]> gcc --version
gcc (GCC) 4.9.1
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

*2. The llvm (Xcode) version*:
mth@Mikes-MBP [~/mth/Programs/zpkg_git/proj.4]> /usr/bin/gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr
--with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

**Comment by cffk** [comment]
Presumably there's a more complex version of test0.c (perhaps copying the function sincosdx from geodesic.c) that exhibits the bug `sin(-0.0) = 0.0`?

However, you seem to have a sufficiently quirky setup, that I propose to ignore this issue until I get some better information on how to fix it.
