### ISSUE TITLE
Switch #include <proj(...).h> to #include "proj(...).h"

### ISSUE THREAD

**Issue by busstoptaktik** [OSGeo/PROJ#841]
... to avoid including an old, already installed `proj.h`, `proj_api.h` and `projects.h` when building a new version of the library.

Not realizing the extent of this (due to misconstructed grep pattern, when searching for additional cases), I introduced a single correction in 20e5610911a6d6231121eb3c0d3c38330f8d708e

Given the number of actual cases, this is probably only a minor problem, which will only show during in-tree builds. So I believe repairing it can wait until we have a number of tasks requiring a full pass over the source (I can think of a few, and will add issues for those)

**Comment by kbevers** [comment]
> So I believe repairing it can wait until we have a number of tasks requiring a full pass over the source 

Please don't do that. One commit, one change. Otherwise debugging can become a nightmare.

**Comment by busstoptaktik** [comment]
> One commit, one change. Otherwise debugging can become a nightmare

In this case I would tend to agree, since the change can be implemented by a one line `sed` script which (modulo some platform dependent escape magic for the angle brackets) reads:

    sed -i "s/^<proj.h^>/""proj.h""/" *.c *.h

There is, however, some upcomming changes [1], [2], [3] (not yet written up as issues), where the changes will be akin to a total phase shift of the architecture.

In these cases I see no other way than altering the X macro magic in `pj_list.c`/`pj_list.h`, to introduce the sweeping changes in a manageable subset of the library (to get to something testable fast), then gradually expand the coverage to the full code base.

The phase shifting changes I mentioned above are:

**[1] Change the internal plumbing to be 4D only.**

This will simplify everything significantly, but will also change the way the library plumbing communicates with each of the `PJ_xxx.c` operator implementations (and require a re-engineering of PJ_helmert.c).

**[2] Get rid of the X macro magic in `pj_list.c`/`pj_list.h`**

Introducing a single interfacing object, returned by an interface function in each operator (`PJ_xxx.c`) implementation. This will improve the decoupling between the plumbing layer and the operator implementations, and it will potentially make it possible to implement user defined operations.

**[3] Get rid of the `OPERATION` macro and its specializations.**

Handle allocation and initialization as a single step procedure. This is the last element of the "get rid of obscure macros" work initialized 2 years ago.

---

Each of these projects will require a number of interrelated changes, that essentially could be seen as individual changes, but which individually renders the code base dysfunctional and untestable.

Hence no other obvious way around this than seeing the entire phase shift as "one change", handled in (essentially) one commit, because introducing them from the start in a "full version" of the library will be prohibitively extensive.

**Comment by kbevers** [comment]
> In this case I would tend to agree, since the change can be implemented by a one line sed script

I was talking about this specific case. Of course it is not always possible to keep it simple, although it should be strived for when ever possible.

> There is, however, some upcomming changes [1], [2], [3] (not yet written up as issues), where the changes will be akin to a total phase shift of the architecture.

Do you mind writing these up before you get started? I think it might be a good idea to openly discuss the approach first.

**Comment by busstoptaktik** [comment]
> Do you mind writing these up before you get started? I think it might be a good idea to openly discuss the approach first.

I will definitely write them up as issues for discussion.

Here I was just taking the opportunity to get started by writing a brief outline. Each of these changes is **huge** in extent, and need a bit of experimentation and clarification before I'll get around to put them in a form suitable for discussion.

Up until the shipping of 5.0.0, finding time for this has been impossible, and it will probably take a few more weeks before I get around to do the initial experiments.
