### ISSUE TITLE
clang-tidy nit: proj_trans has inconsistent declaration

### ISSUE THREAD

**Issue by schwehr** [OSGeo/PROJ#842]
[readability-inconsistent-declaration-parameter-name](http://clang.llvm.org/extra/clang-tidy/checks/readability-inconsistent-declaration-parameter-name.html):

    function 'proj_trans' has 1 other declaration with different parameter names
    src/proj_internal.h:76:12: the 1st inconsistent declaration seen here
    src/proj_internal.h:76:12: differing parameters are named here: ('obs'), in the other declaration: ('coord')

I see:

    egrep 'PJ_COORD +proj_trans +[(]' *
    proj.h:PJ_COORD proj_trans (PJ *P, PJ_DIRECTION direction, PJ_COORD coord);
    proj_4D_api.c:PJ_COORD proj_trans (PJ *P, PJ_DIRECTION direction, PJ_COORD coo) {
    proj_internal.h:PJ_COORD   proj_trans   (PJ *P, PJ_DIRECTION direction, PJ_COORD obs);

**Comment by kbevers** [comment]
Nice catch.

I don't think there's any reason for declaring the function in `proj_internal.h` actually. Otherwise `coo` should be replaced by `coord`.
