### ISSUE TITLE
How to check for errors when calling proj_trans using the new API?

### ISSUE THREAD

**Issue by urschrei** [OSGeo/PROJ#846]
Using the old API, it was possible to check whether a call to `pj_transform` returned `0` or something else. If it was something else, that number could be passed to ` pj_strerrno` to get more details.  
What's the recommended approach for calls to `proj_trans` when using the v5.0 API?

**Comment by kbevers** [comment]
A function matching `pj_strerrno` hasn't been added to the new API yet. You should be able to use include `proj_api.h` alongside `proj.h` and then use `pj_strerrno` to get a text representation of the error message. I'll look into adding a similar function to the new API in 5.1.0.

**Comment by urschrei** [comment]
Oh, great. How do I check whether `proj_trans` has returned an error, though?

**Comment by kbevers** [comment]
See the docs: http://proj4.org/development/reference/functions.html#error-reporting

**Comment by urschrei** [comment]
I completely missed that. Thank you!
