### ISSUE TITLE
Sample (and same code in QuickStart Guide) doesn't compile / run

### ISSUE THREAD

**Issue by macdew** [OSGeo/PROJ#897]
The file examples/pj_obs_api_mini_demo.c, which is replicated in the QuickStart Guide, has a few issues:

1. lines 59 & 61: proj_trans_coord does not exist.  Looks like it should be proj_trans?
2. Line 60: b.en should be b.enu?
3. Line 62: b.lp should be b.lpzt?

**Comment by kbevers** [comment]
Fixed in https://github.com/OSGeo/proj.4/commit/445fdebcc29b909c8008ae8b4ff46c25aeba1e18

> Line 62: b.lp should be b.lpzt?

`b.lp`, `b.lpz` and `b.lpzt` are all valid options here.
