### ISSUE TITLE
Update JNI binding to new Proj.4 API

### ISSUE THREAD

**Issue by desruisseaux** [OSGeo/PROJ#903]
Java Native Interface (JNI) binding currently uses the old Proj.4 API, together with access to some structures not formally documented as public API. Those JNI binding should be upgraded to the new Proj.4 API.

This mapping is accessible to Java developers through the `org.proj4.PJ` Java class. With the new Proj version number, we may need to rename the package name, for example `org.osgeo.proj`.

Note: `PJ` is used by the `geoapi-proj4` module, but that module has never been formally released by the Open Geospatial Consortium (OGC). Up to now, it was only provided on GitHub as an example of GeoAPI implementation. That module my be part of GeoAPI 3.1 release (again mostly as an example), or alternatively it could move directly in the Proj project.

Related discussion in issue #900.

**Comment by desruisseaux** [comment]
Some first observations:

* Package name is currently `org.proj4`. Do the project name has been renamed as "Proj", or does it stay "Proj.4"? In the former case and given that Proj is now an OSGeo project, the package name could be renamed as `org.osgeo.proj`. That would be closer to consistency with the Java version of that library, which is located in the `org.osgeo.proj4j` package. It would be an incompatible change however.
* File `src/org_proj4_Projections.h` is obsolete and can be deleted.
* https://github.com/opengeospatial/geoapi/issues/26 needs to be merged to `src/jniproj.c`.
* What is the license exactly for Proj?

**Comment by desruisseaux** [comment]
Deletion of `src/org_proj4_Projections.h` submitted by pull request #956.

**Comment by desruisseaux** [comment]
Some questions for the next steps:

* What should be the version number of the JAR file? Should it follow Proj version numbers or should it have different numbers on the basis that it will be updated less often?
* If the JAR file version number follows Proj version number, is there a way to know the Proj version at build time? (e.g. an environment variable). The intend is to inject correct information in the `META-INF/MANIFEST.MF` file.
* The `org_proj4_PJ.h` file is currently in the `src/` directory. Would it be okay to move it to the `jniwrap/org.osgeo.proj/` directory? (would be slightly more convenient for `javac` - but only as a minor point). If yes, do I only need to change the paths in `Makefile.am` and `lib_proj.cmake` (in addition of `jniproj.c` of course) before to run `configure` again, or is there something else I need to know?

**Comment by kbevers** [comment]
> What should be the version number of the JAR file? Should it follow Proj version numbers or should it have different numbers on the basis that it will be updated less often?

I guess it depends on how much the C and Java API's can be expected to be out of alignment. If the Java API always will be up to date with the C API I think it is fine to just use the same version numbers. If the Java API is only updated every other release or so maybe it is best to maintain separate version numbers. What do you think is best?

> If the JAR file version number follows Proj version number, is there a way to know the Proj version at build time? (e.g. an environment variable). The intend is to inject correct information in the META-INF/MANIFEST.MF file.

The version number can be read from `proj.h`. I don't know if that is usefull though.

> The org_proj4_PJ.h file is currently in the src/ directory. Would it be okay to move it to the jniwrap/org.osgeo.proj/ directory? (would be slightly more convenient for javac - but only as a minor point). If yes, do I only need to change the paths in Makefile.am and lib_proj.cmake (in addition of jniproj.c of course) before to run configure again, or is there something else I need to know?

Please do. Yes, you will have to update both Autotools and CMake makefiles in `src`. And make corresponding updates in `jniwrap` of course. I don't think there is anything else you need to do.

**Comment by desruisseaux** [comment]
After more though, I propose to keep the version number distinct. In part because fetching the number from the `proj.h` file in an Ant script is uneasy, but also (more fundamentally) because the Java bridge are expected to be updated less often than PROJ, and the same JAR file should be compatible with a range of PROJ releases. Instead I propose to document the relationship like in this [README file from the merge request](https://github.com/Geomatys/proj.4/tree/54f0513aed8a82e75f6442b4b03900c47f1c3621/jniwrap#versions).

**Comment by rouault** [comment]
Old JNI bindings have been removed from master
