### ISSUE TITLE
Fuzzing with gie

### ISSUE THREAD

**Issue by schwehr** [OSGeo/PROJ#905]
I'm at about 65-70% test coverage with Proj in my custom env.  Getting gie wired up to my test environment has been a big win and I very much appreciate the work that went into it!

I was thinking that fuzzing with the gie code would be nice in that I can contribute test cases back to the proj gie library when the fuzzer comes up with anything interesting (after a little bit of tidying, I'm sure).  This would also make the gie code more robust to mistakes by humans :) 

To do that, I would need to be able to build gie.c without main, call a setup function, loop over the lines the fuzzer provides calling dispatch on each, then call a cleanup. 

This could be done either in gie.c with a preprocessor define or by splitting gie.c into 2 files.  While I could just use the gie binary from the fuzzer, it would be painfully slow to write the data to a file (or pass by stdin) and creating a child process for each iteration.

Thoughts?  I poked at the idea for a few minutes, but I mostly just made a mess as I don't think well in C89 (my head keeps trying to rewrite everything as C++14) and don't really know proj very well.

**Comment by busstoptaktik** [comment]
@schwehr, this sounds like a worthwhile improvement.

I have a long list of gie action items, and would like to do something about this one as well.

Unfortunately I'm hit by a rather aggressive flu, so my current activity level is very low. I'll look into it when I'm getting back on my feet.

In the meantime, can you add a few more words about what needs to be done for this to work for you?

**Comment by schwehr** [comment]
No rush! Hope you recover quickly. I'll try to put down some more soon.

**Comment by schwehr** [comment]
If we could change the file io lib to read from an array of lines that are preloaded and disable the builtin tests, I think that would be most of it.

**Comment by kbevers** [comment]
You definitely need a way to call gie from code, that's a given, and shouldn't be too hard to set up.  If gie implemented the `projFileAPI` (in an updated version for the `proj.h` API of course) instead of using the stdio functions for reading files directly, I think you should be able to do more or less what ever you want. The idea being that in your code you could call something to the effect of `gie_parse_file(some-bogus-file)`  and then control what is presented to gie that way. 

This is definitely not the simplest way to achieve what you want, but it would be nice because we would then have actual code that demonstrate how the FileAPI is used as well as being able to test that it works as expected.

@schwehr what do you think about this slightly different approach?

**Comment by rouault** [comment]
Folks, have you looked at test/fuzzers/standard_fuzzer.cpp that is used by oss-fuzz ? A similar thing could be done using the 4D API.

**Comment by schwehr** [comment]
standard_fuzzer.cpp is definitely awesome.  I used it for documentation when I wrote my simple (and now crusty) [proj4_fuzzer.cc](https://github.com/schwehr/gdal-autotest2/blob/master/cpp/third_party/proj/proj4_fuzzer.cc)

I was thinking that a gie based fuzzer would:
- give test cases that could be put into the gie test dir after cleanup
- catch troubles that come from running multiple things through proj
- give test coverage for gie.c

For my custom world,  I'm currently at 74% and 228 untested lines for gie.c.  For proj4 overall, I'm at 74% coverage with 3882 untested lines.  gie.c is my largest chunk of uncovered lines.  And just because a line is covered, doesn't mean there isn't still trouble lurking.   More coverage means I'm catch trouble with less work as I migrate patches from upstream into the local env... and gie test cases have been an awesome win for.me.  I just wrote this this morning to try to catch a few more lines... boring stuff gets the job done. 

```python
  def testBanner(self):
    filepath = os.path.join(FLAGS.test_srcdir,
                            'third_party/proj4/tests/testdata',
                            'banner.gie')
    cmd = [self.gie, filepath]
    result = subprocess.check_output(cmd, stderr=subprocess.STDOUT)
    self.assertIn('---\nhello', result)
    self.assertIn('---\nworld', result)

  def testEcho(self):
    filepath = os.path.join(FLAGS.test_srcdir,
                            'third_party/proj4/tests/testdata',
                            'echo.gie')
    cmd = [self.gie, filepath]
    result = subprocess.check_output(cmd, stderr=subprocess.STDOUT)
    self.assertIn('echo.gie\'\nfoo\nbar\n---', result)

  def testMissingEnd(self):
    filepath = os.path.join(FLAGS.test_srcdir,
                            'third_party/proj4/tests/testdata',
                            'missing-gie-end-tag.gie')
    cmd = [self.gie, filepath]
    result = subprocess.check_output(cmd, stderr=subprocess.STDOUT)
    self.assertIn('Missing \'</gie>\' cmnd', result)

  def testMissingStart(self):
    filepath = os.path.join(FLAGS.test_srcdir,
                            'third_party/proj4/tests/testdata',
                            'missing-gie-start-tag.gie')
    cmd = [self.gie, filepath]
    result = subprocess.check_output(cmd, stderr=subprocess.STDOUT)
    self.assertIn('Missing \'<gie>\' cmnd', result)

  def testMissingSkip(self):
    filepath = os.path.join(FLAGS.test_srcdir,
                            'third_party/proj4/tests/testdata',
                            'skip.gie')
    cmd = [self.gie, filepath]
    result = subprocess.check_output(cmd, stderr=subprocess.STDOUT)
    self.assertNotIn('Should not print', result)
```
