### ISSUE TITLE
Transform from LLA to ORTHO with WGS84 gives sphere instead of ellipsoid

### ISSUE THREAD

**Issue by Felix-neko** [OSGeo/PROJ#909]
I want to convert my coodrinates from `lon, lat` to `x, y` of orthographic projection. I tried to use `PyProj` to do it, but it uses sphere, not ellipsoid. Here it is:

    lonlat_proj = pyproj.Proj(proj="longlat", ellps="WGS84")
    lat = 90
    lon = 0
    alt = 0

    # ECEF IS OKAY
    ecef_proj = pyproj.Proj(proj="geocent", ellps="WGS84")
    ortho_proj = pyproj.Proj(proj="ortho", lat_0=0, lon_0=0, ellps="WGS84")

    # ORTHO IS NOT!!!
    x, y, z = pyproj.transform(lonlat_proj, ecef_proj, lon, lat, alt)
    print(x, y, z)
    # Gives: 3.918e-10 (okay), 0.0, 6356752.314 (okay, it's earth semiminor)

    x_ortho, y_ortho = pyproj.transform(lonlat_proj, ortho_proj, lon, lat)
    print(x_ortho, y_ortho)
    # Gives: 0.0 (okay), 6378137,0 (earth SEMIMAJOR instead of semiminor)
    # WHY?!!

How can I cope with it?

**Comment by kbevers** [comment]
The orthographic projection is only implemented for the sphere in PROJ. You can control the radius of the sphere with the `+R` or `+a` options. See the examples below.

```
$ echo 0 90 0|./bin/proj -V +proj=ortho +lat_0=0 +lon_0=0 +ellps=WGS84
#Orthographic
#	Azi, Sph.
# +proj=ortho +lat_0=0 +lon_0=0 +ellps=WGS84
#Final Earth figure: sphere
#  Radius: 6378137.000
 0
Longitude: 0dE [ 0 ]
Latitude:  90dN [ 90 ]
Easting (x):   0.00
Northing (y):  6378137.00
Meridian scale (h) : 0.00001000  ( -100 % error )
Parallel scale (k) : 1.00000000  ( -7.777e-09 % error )
Areal scale (s):     0.00001000  ( -100 % error )
Angular distortion (w): 179.275
Meridian/Parallel angle: 90.00000
Convergence : 0d [ 0.00000000 ]
Max-min (Tissot axis a-b) scale error: 1.00000 0.00001
```

```
$ echo 0 90 0|./bin/proj -V +proj=ortho +lat_0=0 +lon_0=0 +R=6356752.31
#Orthographic
#	Azi, Sph.
# +proj=ortho +lat_0=0 +lon_0=0 +R=6356752.31
#--- following specified but NOT used
# +ellps=WGS84
#Final Earth figure: sphere
#  Radius: 6356752.310
 0
Longitude: 0dE [ 0 ]
Latitude:  90dN [ 90 ]
Easting (x):   0.00
Northing (y):  6356752.31
Meridian scale (h) : 0.00001000  ( -100 % error )
Parallel scale (k) : 1.00000000  ( -7.777e-09 % error )
Areal scale (s):     0.00001000  ( -100 % error )
Angular distortion (w): 179.275
Meridian/Parallel angle: 90.00000
Convergence : 0d [ 0.00000000 ]
Max-min (Tissot axis a-b) scale error: 1.00000 0.00001
```

**Comment by Felix-neko** [comment]
Oy vey iz mir.....

*crying*
