### ISSUE TITLE
gie skip should not complain about a missing </gie> when there is a </gie>

### ISSUE THREAD

**Issue by schwehr** [OSGeo/PROJ#922]
In the nit category of bugs...

`cat third_party/proj4/tests/testdata/skip.gie`

```
===============================================================================
Purpose: Test gie skip tag that stops processing the rest of the gie file.
===============================================================================

<gie>

skip
echo Should not print

</gie>
```

```
gie third_party/proj4/tests/testdata/skip.gie
-------------------------------------------------------------------------------
Reading file 'third_party/proj4/tests/testdata/skip.gie'
-------------------------------------------------------------------------------
total:  0 tests succeeded,  0 tests skipped,  0 tests failed.
File 'third_party/proj4/tests/testdata/skip.gie':Missing '</gie>' cmnd - bye!
-------------------------------------------------------------------------------
```

**Comment by kbevers** [comment]
Not sure why this happens, but thanks for reminding me that I have forgotten to add the `skip` and `echo` commands to the gie docs. Will do that later today.

Edit: Added in https://github.com/OSGeo/proj.4/commit/053b7e3e45b0ce60cde462a9d590afd6d4682cd1

**Comment by kbevers** [comment]
Here's a very basic solution to this. I don't think it is the best solution but it does fix the problem in a hurry. Since we don't care about anything after `skip` it doesn't really matter that we set the tag-level artificially. I'll defer to @busstoptaktik on this.

```diff
diff --git a/src/gie.c b/src/gie.c
index 8c735b88..6ffd92a4 100644
--- a/src/gie.c
+++ b/src/gie.c
@@ -964,6 +964,7 @@ Indicate that the remaining material should be skipped. Mostly for debugging.
 ******************************************************************************/
     T.skip = 1;
     (void) args;
+    F->level = 2;
     return 0;
 }
```

**Comment by busstoptaktik** [comment]
@kbevers: I actually think this is probably the best way of doing this. A comment indicating why `F->level` is set to 2 (`/* Silence complaints about missing </gie> element */`, or somesuch) would probably be useful.

**Comment by kbevers** [comment]
Alright. I'll apply that later today then. Thanks.

**Comment by schwehr** [comment]
Thanks!

**Comment by kbevers** [comment]
You are welcome. Now get back to making more gie tests! :)
