### ISSUE TITLE
compile error with cmake 2.8.12 CMP0010

### ISSUE THREAD

**Issue by Wsine** [OSGeo/PROJ#944]
```
-- ==> add_subdirectory(localization)
CMake Warning (dev) at localization/3rdparty/proj.4/CMakeLists.txt:29 (set):
  Syntax error in cmake code at

    /home/wsine/catkin_ws/src/localization/3rdparty/proj.4/CMakeLists.txt:29

  when parsing string

    ${{CMAKE_C_FLAGS}} -Wall -Wextra -Wswitch -Wshadow \
      -Wunused-parameter -Wmissing-prototypes -Wmissing-declarations -Wformat \
      -Wformat-security

  syntax error, unexpected cal_SYMBOL, expecting $end (128)

  Policy CMP0010 is not set: Bad variable reference syntax is an error.  Run
  "cmake --help-policy CMP0010" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

```

my environment is 
```
~/catkin_ws » cmake --version
cmake version 2.8.12.2

------------------------------------------------------------

~/catkin_ws » gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by cffk** [comment]
The problem is that cmake 2.x doesn't recognize "\\" as a string continuation character.  This usage should be avoided in cmake files (until we are sure that everyone has cmake 3.x installed).

**Comment by Wsine** [comment]
@cffk are there any solutions for me to use proj.4 with cmake version 2.x?

**Comment by cffk** [comment]
For sure we need to be thinking about making CMake 3.x a requirement at some point.  However line continuation isn't enough of a reason to force the switch.  So I recommend removing the line continuations from the CMake files.

**Comment by kbevers** [comment]
@cffk I have removed the line continuations in #948. When do you recommend not supporting CMake2 in more? PROJ v. 6 or v. 7? Or even later?

**Comment by cffk** [comment]
There's no burning need to make this change at this point.   Maybe wait until RHEL and other Linux distros which have well-defined end-of-life criteria have all stopped using cmake 2.x for supported releases.
