### ISSUE TITLE
pj_is_nan or pj_isnan - pick one

### ISSUE THREAD

**Issue by schwehr** [OSGeo/PROJ#959]
```
egrep 'pj_is_?nan' *
pj_math.c:int pj_isnan (double x) {
proj_internal.h:#define pj_is_nan isnan
proj_internal.h:int pj_is_nan (double val);
proj_math.h:int     pj_isnan(double x);
proj_math.h:#define isnan   pj_isnan
```

**Comment by kbevers** [comment]
The definition in `proj_internal.h` should be removed. The PROJ specific `isnan` implementation has been moved to `proj_math.h`/`pj_math.c`. It is only there so it can be aliased as `isnan` when C99 math function are unavailable.
