### ISSUE TITLE
CGVD2013 support

### ISSUE THREAD

**Issue by tveinot** [OSGeo/PROJ#963]
National Resources Canada has released the CGVD2013 geoid model on their website but it isn't available as a .gtx format. Is there a way to convert it? I googled this quite a lot and couldn't find anything to do the conversion from gsb to gtx using ArcGIS, QGIS, GRASS Tools, or gvSIG. Is there something else I can try or could CGVD2013 be incorporated into the project where it is made available online?
Thanks;
Tyler

**Comment by kbevers** [comment]
Are you sure the geoid model is released as a gsb file? Files with that extension are usually NTv2 files which are used for grid shifts that maps between two horizontal datums. The files includes two bands (four, really). 

GTX files only include one band and are usually used for geoid models. It is not clear how a 2D model (lat/long, horizontal) should be mapped to a 1D model (z, vertical). I reckon that is why you have a hard time finding a way to achieve that goal. Are you certain that the Canadian geoid model is released as a gsb file?

**Comment by SilverSloth** [comment]
Probably those geoidgrid files are in BYN format. This tool  https://www.eye4software.com/hydromagic/documentation/manual/utilities/geoid-file-conversion/ might convert to an ascii format that you can then manipulate into AAIGrid (Esri grid *.asc) then convert using gdal_translate, from command prompt or using it via QGIS. Nodata value to give in the ascii before translating to GTX I think is -88.8888.

I wonder how common BYN is versus GTX.

**Comment by kbevers** [comment]
Sounds like that solves the problem.
