### ISSUE TITLE
In PROJ 5.0, you can no longer reproject world-wide layers (e.g. XYZ tile services) into local CRS-es

### ISSUE THREAD

**Issue by borysiasty** [OSGeo/PROJ#964]
I'm not sure where exactly is the source of the problem, but there is a bad regression in GDAL and QGIS if they are compiled against PROJ 5.0:

With Proj 4.9, it was possible to reproject world-wide layers into local (national) CRS-es. Even if it doesn't make any sense to reproject the whole world, it's essenstial to be able to reproject just the area of interest. For example, the area of Poland could be projected from EPSG:3857 or EPSG:4326 into a Polish national  EPSG:2180 - even if the source layer covers the whole world:

gdalwarp -t_srs EPSG:2180 -te 100000 100000 900000 800000 world_3857.tif poland_2180.tif

It works if GDAL is compiled against PROJ 4.9, but with PROJ 5 it fails with error:

ERROR 1: Too many points (1681 out of 1681) failed to transform, unable to compute output bounds.

Also QGIS can no longer transform OSM tiles and other world-wide XYZ and WMS services for its projects working in EPSG:2180 (and other local CRSes I tested randomly). What works with 4.9, with PROJ 5.0 throws this error:

https://github.com/qgis/QGIS/blob/master/src/core/qgscoordinatetransform.cpp#L541

In both cases it seems the whole extent is (unnecesarilly?) reprojected - but for PROJ 4.9 it just wasn't blocking.

**Comment by kbevers** [comment]
Are you experiencing this problem with PROJ master? If not you have probably run into [this problem](https://github.com/OSGeo/proj.4/pull/955).

**Comment by borysiasty** [comment]
Thanks a lot @kbevers, that's it! QGIS works fine with master. I didn't test gdalwarp, but my case looks exactly like that bug. 

Is there any chance to backport the fix to 5.0? I can do a PR.

**Comment by kbevers** [comment]
We're releasing 5.1.0 around June 1st so I don't really want to bother with backporting bugs and issueing a patch release so close to a scheduled release. A request for a patch of the OSGeo4W package has been made but without response so far.

**Comment by borysiasty** [comment]
Ok, thanks a lot!
