### ISSUE TITLE
Error in Swiss datumgrids

### ISSUE THREAD

**Issue by chicoff** [OSGeo/PROJ#972]
there is an error in the init file "nad/CH" , the nadgrid_name chenyx06etrs.gsb does't match with the filename CHENYX06_etrs.gsb

**Comment by sebastic** [comment]
The [download link](http://www.swisstopo.admin.ch/internet/swisstopo/en/home/topics/survey/lv03-lv95/chenyx06/distortion_grids.html) in the comments of `nad/CH` is outdated, the current URL is:

 https://shop.swisstopo.admin.ch/en/products/geo_software/GIS_info

The two files available for download there provide different contents than the old one:

 * `chenyx06_ntv2.zip` (NTv2 grid CH1903/LV03 -> CH1903+/LV95)
   Provides: `CHENYX06a.asc` & `CHENYX06a.gsb`

 * `chenyx06_etrs_ntv2.zip` (NTv2 grid ETRF93/ETRS89 -> CH1903/LV95)
   Provides: `CHENYX06_etrs.asc` & `CHENYX06_etrs.gsb`

Just changing the filename in the `nadgrids` option may be sufficient:
```diff
--- a/nad/CH
+++ b/nad/CH
@@ -18,6 +18,6 @@
 #
 <metadata> +origin=Swisstopo +lastupdate=2012-02-27
 # CH1903/LV03
-<1903_LV03>  +proj=somerc +lat_0=46.95240555555556 +lon_0=7.439583333333333 +k_0=1 +x_0=600000 +y_0=200000 +ellps=bessel +units=m +nadgrids=chenyx06etrs.gsb +no_defs
+<1903_LV03>  +proj=somerc +lat_0=46.95240555555556 +lon_0=7.439583333333333 +k_0=1 +x_0=600000 +y_0=200000 +ellps=bessel +units=m +nadgrids=CHENYX06_etrs.gsb +no_defs
 # CH1903
-<1903> +proj=longlat +ellps=bessel +nadgrids=chenyx06etrs.gsb +no_defs  <>
+<1903> +proj=longlat +ellps=bessel +nadgrids=CHENYX06_etrs.gsb +no_defs  <>
```
Other options in the definition may need to be updated too.

If you need the old datumgrid files for comparison, you can find them in the old Debian package:

 https://sources.debian.org/src/proj/4.8.0-5/debian/datumgrids-ch.shar/

You need [`sharutils`](https://www.gnu.org/software/sharutils/) to unpack the file with:
```
unshar -c -d /tmp datumgrids-ch.shar
```
