### ISSUE TITLE
mysys-cxx17 yields redefinition error fro 'pj_acquire_lock/pj_release_lock' in 'pj_mutex'

### ISSUE THREAD

**Issue by michael-herwig** [OSGeo/PROJ#976]
For build output and configuration please have a look [here](https://ci.appveyor.com/project/michael-herwig/hunter/build/job/555h2gh9ng7km8r1).

*  `v5.0.1`
* `cmake version 3.11.1`
* `polly msys-cxx17`

```
/C/projects/hunter/_testing/Hunter/_Base/170b107/1dcee15/24e8f10/Build/PROJ4/Source/src/pj_mutex.c:190:6: error: redefinition of 'pj_acquire_lock'
 void pj_acquire_lock()
      ^~~~~~~~~~~~~~~
/C/projects/hunter/_testing/Hunter/_Base/170b107/1dcee15/24e8f10/Build/PROJ4/Source/src/pj_mutex.c:113:6: note: previous definition of 'pj_acquire_lock' was here
 void pj_acquire_lock()
      ^~~~~~~~~~~~~~~
/C/projects/hunter/_testing/Hunter/_Base/170b107/1dcee15/24e8f10/Build/PROJ4/Source/src/pj_mutex.c:204:6: error: redefinition of 'pj_release_lock'
 void pj_release_lock()
      ^~~~~~~~~~~~~~~
/C/projects/hunter/_testing/Hunter/_Base/170b107/1dcee15/24e8f10/Build/PROJ4/Source/src/pj_mutex.c:147:6: note: previous definition of 'pj_release_lock' was here
 void pj_release_lock()
      ^~~~~~~~~~~~~~~
/C/projects/hunter/_testing/Hunter/_Base/170b107/1dcee15/24e8f10/Build/PROJ4/Source/src/pj_mutex.c:215:6: error: redefinition of 'pj_cleanup_lock'
 void pj_cleanup_lock()
      ^~~~~~~~~~~~~~~
/C/projects/hunter/_testing/Hunter/_Base/170b107/1dcee15/24e8f10/Build/PROJ4/Source/src/pj_mutex.c:155:6: note: previous definition of 'pj_cleanup_lock' was here
 void pj_cleanup_lock()
      ^~~~~~~~~~~~~~~
make[5]: *** [src/CMakeFiles/proj.dir/build.make:2237: src/CMakeFiles/proj.dir/pj_mutex.c.obj] Error 1
make[5]: Leaving directory '/c
```

**Comment by rouault** [comment]
@michael-herwig Do you mind retesting with https://github.com/rouault/proj.4/commit/291a96613e9a244e455229dbff4e2dbdc8cab9c9 applied ?

**Comment by michael-herwig** [comment]
Yes i'll give it a try tomorrow. By the way is there a special reason for the verions number still beeing [5.0.0](https://github.com/OSGeo/proj.4/blob/master/CMakeLists.txt#L60) while there is already a [5.0.1](https://github.com/OSGeo/proj.4/releases/tag/5.0.1) release? Otherwise I could open another ticket.

**Comment by rouault** [comment]
> is there a special reason for the verions number still beeing 5.0.0 while there is already a 5.0.1 release?

The version number has been bumped in the 5.0 branch that was used to prepare 5.0.1 (https://github.com/OSGeo/proj.4/commit/5ad2227c56b87a4237089511e9b3e7b49b4d80ab). The version numbers in master are 'undefined' until it is close to release time. So they will be bumped to 5.1.0 at some point

**Comment by kbevers** [comment]
> The version numbers in master are 'undefined' until it is close to release time. So they will be bumped to 5.1.0 at some point

Likely within the next week or two. After release of 5.1 I intend to bump version numbers for unreleased code to 5.2 straight away. The current way is too confusing.

**Comment by michael-herwig** [comment]
All good :)

* https://ci.appveyor.com/project/michael-herwig/hunter/build/1.0.5
* https://travis-ci.org/michael-herwig/hunter/builds/375260655
