### ISSUE TITLE
Unused variable 'xy' in PJ_chamb.c:53

### ISSUE THREAD

**Issue by michael-herwig** [OSGeo/PROJ#977]
For a full analyzer output please have a look [here](https://travis-ci.org/michael-herwig/hunter/jobs/374980003#L3073).

```
src/PJ_chamb.c:53:8: warning: Value stored to 'xy' during its initialization is never read
    XY xy = {0.0,0.0};
       ^~   ~~~~~~~~~
```

**Comment by rouault** [comment]
Has been fixed in master per cde489ce64556e0ad5fa5da64bcb8fd88aee4c39
