### ISSUE TITLE
Difference of cs2cs doc example

### ISSUE THREAD

**Issue by mwtoews** [OSGeo/PROJ#981]
While reviewing the docs (#980), I noticed that the example for `cs2cs` now has a slightly different output. Testing with either 4.9.3 or current master, I get the same output:
```
cs2cs +proj=latlong +datum=NAD83 +to +proj=utm +zone=10 +datum=NAD27 -r <<EOF
> 45d15'33.1" 111.5W
> 45d15.551666667N -111d30
> +45.25919444444 111d30'000w
> EOF
1402285.98	5076292.42 -0.00
1402285.98	5076292.42 -0.00
1402285.98	5076292.42 -0.00
```
but the documentation currently has an expected output:
```
1402285.99      5076292.42 0.000
```
I'm not sure which version provided this output, but should there be any concern? If no, I may update the example in the docs to reflect the current expected value.

**Comment by kbevers** [comment]
I think it should be updated. I am slightly annoyed by the minus zero, but I guess it is correct to indicate that the number in fact is less than zero before the rounding to two decimals.
