### ISSUE TITLE
Support for Chinese pseudo-datums?

### ISSUE THREAD

**Issue by Artoria2e5** [OSGeo/PROJ#982]
Electronic maps published in China have all their coordinates obfuscated by adding noise, effectively forming a new "GCJ-02" lat/lon datum based on WGS84 lat-lon coordinates. There also exists a further transformed version called BD-09, used by Baidu. (Baidu also has a variant web mercator in some polynominals; nobody knows how it works, and luckily nobody uses them.) The algorithms can be see [in this file](https://commons.wikimedia.org/wiki/File:PRcoords_Cheatsheet.pdf), with roundtrip-ability measured [in this demo](https://artoria2e5.github.io/PRCoords/demo).

Despite the obvious "BS" nature of these datums, many people unfortunately inadvertently use them by interacting with "legal" map sources like Google Maps and Bing Maps. Perhaps proj.4 should implement these datums so they can be as easily processed? (How should the files be organized?)

**Comment by kbevers** [comment]
Yeah, I am not super keen on these BS datums. The webmercator is in the same category and we support that so if there is an obvious need for the Chinese BS-datums maybe we should include those as well. I am not going to implement it myself but if a PR shows up I will consider merging it.

Are these pseudo-datums considered stable or do the Chinese authorities change them from time to time?

**Comment by Artoria2e5** [comment]
They are fortunately stable. My main concern about file organization is that these datums would mean implementing two transformations, in C, that each only serves a single datum.

**Comment by Artoria2e5** [comment]
I was talking about how I should put the things under `src/` and document them. Most of the transformations/projections under `src` are documented as a singular projection independently and reused across reference systems, but the best I can do for the obfuscating ones in the pseudo-datums is to just say, for example, "used by `china:gcj02`". There won't be any tunable parameters for them, as the projection basically defines the datum. That feels very strange judging by the rest of the project.

* * *

By the way, what is the usual desirable round-trip accuracy? The "fast" (one-iter) method for inverse gcj (i.e. gcj to "wgs") is usually 1 to 2 meters off, and the "fast" (one-iter, modified) method for inverse bd (i.e. bd to gcj) is usually 1 decimeter off. These can be indefinitely improved by more iterations, but the source data is never that good to justify sub-decimiter accuracy anyway.

**Comment by kbevers** [comment]
I would take a look at the [webmercator](https://github.com/OSGeo/proj.4/blob/a751fcc49b6542245e57707488fcbeff7a22fb6a/src/PJ_merc.c#L90-L104) and [CalCOFI](https://github.com/OSGeo/proj.4/blob/master/src/PJ_calcofi.c) projections for examples of how to handle these pseudo-datums. Please note this pull request refactoring the CalCOFI projection: #987.

Roundtrip accuracy would ideally be a lot better than 1 meter. That is a lot of error to introduce when transforming back and forth a few times, which is not an uncommon thing to do in GIS use for instance. But in the end it comes down to what is possible within the given system. Many legacy systems can't deliver that kind of accuracy for instance. Nothing you can do about that really.

**Comment by melitakennedy** [comment]
I don't use PROJ except for sometimes trying to help other people use it, but are you sure you want to put in code that can used to break Chinese laws or regulations? It doesn't matter if you're working in or out of China. Any data with GCJ-02 or BD-09 coordinates is technically under the control of the Chinese government.

Esri has not added any type of support for GCJ-02 because of that. Disclosure: I work for Esri.

**Comment by hobu** [comment]
> Any data with GCJ-02 or BD-09 coordinates is technically under the control of the Chinese government.

This situation is completely silly.

> Esri has not added any type of support for GCJ-02 because of that.

This stance seems prudent for PROJ as well.

**Comment by kbevers** [comment]
> Any data with GCJ-02 or BD-09 coordinates is technically under the control of the Chinese government.

I had missed that point. Let's drop this. Thanks for pointing it out.

**Comment by Artoria2e5** [comment]
> are you sure you want to put in code that can used to break Chinese laws or regulations

Hell yeah. In FOSS we conditionally break patent laws (with compile-time switches, of course) and cryptographic export control, so why not break this too?

> Any data with GCJ-02 or BD-09 coordinates is technically under the control of the Chinese government.

The degree of "control" given is not as "bad" as ownership or anything -- it is, at worst, comparable to some form of export control on the data, with qualifications requred for creating such data. In many cases the application of GCJ-02 itself is seen as a means of removing the clearance levels required to access geographic measurements and clearing them for public consumption. Since it is an export-control-like measure, why care about them once they are already outside?

**Comment by Artoria2e5** [comment]
> Because PROJ is in products that are used within China.

See FreeType's handling of subpixel rendering patents: just hide it behind some macros that are not defined by default.

**Comment by rouault** [comment]
Turns out this issue came back again in https://rasterio.groups.io/g/main/topic/reprojecting_geotiff_to/75556600?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,75556600
I was thinking that perhaps a plugin architecture for PROJ could help to deal with this. The problematic code could live in its own repository, so PROJ would not be tainted by it

**Comment by Artoria2e5** [comment]
Yeah, the tainted stuff do appear in a lot of places. I am thinking about making a bunch of PROJCS with a fake ESGI number 888xxx. (Because 888 is a... lucky Chinese number.)

I think proj4js can be a good first step since it seems to have a (private for now?) API for adding projections.

The C version of some "plugin API" will involve some function pointer stuff.

**Comment by Artoria2e5** [comment]
FWIW, the proj4js mockup is in https://runkit.com/artoria2e5/proj4-plugin-prcoords.
