### ISSUE TITLE
pj_units.c:pj_get_units_ref() is unused, remove when projects.h is made private

### ISSUE THREAD

**Issue by schwehr** [OSGeo/PROJ#983]
Or at least deprecated?

**Comment by kbevers** [comment]
Well, it is declared in `projects.h` so we better keep it around until that goes away from the public API. We have already deprecated everything in `projects.h` so no need to more in that regard.

I am changing the title of this issue and adding it to the 6.0.0 milestone so we don't forget to get rid of `pj_get_units_ref().

**Comment by schwehr** [comment]
There doesn't seem to be anything in `projects.h` saying that it is deprecated.  And it seems that `projects.h` is full of critical stuff (like the #defines for error codes).  I'm confused.

**Comment by kbevers** [comment]
It was announced with the 5.0.0 release:

https://github.com/OSGeo/proj.4/blob/a751fcc49b6542245e57707488fcbeff7a22fb6a/NEWS#L294-L315

Also it has been stated for many years in the header of `projects.h` that it is a private header file:

https://github.com/OSGeo/proj.4/blob/a751fcc49b6542245e57707488fcbeff7a22fb6a/src/projects.h#L1-L6

I agree that the communication could be better here. It has been thoroughly discussed on the mailing list though. You are welcome to improve the situation.
And you are absolutely right, `projects.h` has a bunch of critical stuff. It will still be kept around but just not installed for users. It is limiting us from changing a lot of what should have been internal implementation details so I am looking forward to not having it around anymore.
