### ISSUE TITLE
Multiple definitions of the same thing

### ISSUE THREAD

**Issue by schwehr** [OSGeo/PROJ#991]
PJ_isea looks like most of the trouble.  But there are likely other repetitions that should be removed.

```
egrep '[^-0-9](3\.14|1\.57|6\.28)' *
geocent.c:#define PI         3.14159265358979323e0
PJ_isea.c:#  define M_PI 3.14159265358979323846
PJ_isea.c:#define DEG90 1.57079632679489661922
PJ_krovak.c:#define S90 1.570796326794896  /* 90 deg */
projects.h:#define M_PI            3.14159265358979323846
projects.h:#define M_PI_2          1.57079632679489661923
projects.h:#define M_TWOPI         6.28318530717958647693   /* 2*pi */
```

```
(egrep '#define.*180' * ; egrep -i 'torad|todeg' *.h ) | sort -u
PJ_isea.c:#define DEG180 M_PI
PJ_isea.c:#define DEG2RAD (M_PI/180.0)
PJ_isea.c:#define RAD2DEG (180.0/M_PI)
proj.h:double proj_todeg (double angle_in_radians);
proj.h:double proj_torad (double angle_in_degrees);
proj_internal.h:#define PJ_TODEG(rad)  ((rad)*180.0/M_PI)
proj_internal.h:#define PJ_TORAD(deg)  ((deg)*M_PI/180.0)
proj_internal.h:#ifndef PJ_TODEG
proj_internal.h:#ifndef PJ_TORAD
```

**Comment by kbevers** [comment]
Thanks for reporting these. Surprised that PI is not defined in more places after all.

`PJ_isea.c` is just a big mess. I've been to the library to borrow a copy of the orignal paper by Snyder so I can clean that mess up properly. Unfortunately no test data...

**Comment by schwehr** [comment]
I can try to dump interesting cases from my fuzzer corpus if that is helpful for generating test cases.  I so need to work on my gie fuzzer so I can make proper test cases at scale

**Comment by kbevers** [comment]
Closed with https://github.com/OSGeo/proj.4/commit/446a4d67f35db27036ae16f0490dbc45228a20b5
