### ISSUE TITLE
Error message enum

### ISSUE THREAD

**Issue by schwehr** [OSGeo/PROJ#993]
The error messages currently are just #defines.  It would be good to have the option to use an enum instead.  This would also help track down where bare literals are being used for error conditions.  Also, I think there should be a symbol for no error and possibly also a we don't know code of some sort.

**Comment by kbevers** [comment]
I don't understand this. Can you add some context?

**Comment by schwehr** [comment]
e.g. https://github.com/OSGeo/gdal/blob/master/gdal/ogr/ogr_core.h#L273

```C++
#ifdef STRICT_OGRERR_TYPE
/** Type for a OGR error */
typedef enum
{
    OGRERR_NONE,                       /**< Success */
    OGRERR_NOT_ENOUGH_DATA,            /**< Not enough data to deserialize */
    OGRERR_NOT_ENOUGH_MEMORY,          /**< Not enough memory */
    OGRERR_UNSUPPORTED_GEOMETRY_TYPE,  /**< Unsupported geometry type */
    OGRERR_UNSUPPORTED_OPERATION,      /**< Unsupported operation */
    OGRERR_CORRUPT_DATA,               /**< Corrupt data */
    OGRERR_FAILURE,                    /**< Failure */
    OGRERR_UNSUPPORTED_SRS,            /**< Unsupported SRS */
    OGRERR_INVALID_HANDLE,             /**< Invalid handle */
    OGRERR_NON_EXISTING_FEATURE        /**< Non existing feature. Added in GDAL 2.0 */
} OGRErr;
#else
/** Type for a OGR error */
typedef int OGRErr;

#define OGRERR_NONE                0       /**< Success */
#define OGRERR_NOT_ENOUGH_DATA     1       /**< Not enough data to deserialize */
#define OGRERR_NOT_ENOUGH_MEMORY   2       /**< Not enough memory */
#define OGRERR_UNSUPPORTED_GEOMETRY_TYPE 3 /**< Unsupported geometry type */
#define OGRERR_UNSUPPORTED_OPERATION 4     /**< Unsupported operation */
#define OGRERR_CORRUPT_DATA        5       /**< Corrupt data */
#define OGRERR_FAILURE             6       /**< Failure */
#define OGRERR_UNSUPPORTED_SRS     7       /**< Unsupported SRS */
#define OGRERR_INVALID_HANDLE      8       /**< Invalid handle */
#define OGRERR_NON_EXISTING_FEATURE 9      /**< Non existing feature. Added in GDAL 2.0 */

#endif
```

**Comment by kbevers** [comment]
Okay, I understand. It makes sense to me. I am not sure how simple this would be to implement. I think adapting this in the new API would be more or less straight forward but I don't think we can retro-fit enum error codes to `proj_api.h` (e.g. `pj_transform()` returns error codes as ints). And since everything behind the scenes is quite tangled together I fear this could be difficult to achieve.

**Comment by schwehr** [comment]
When I get more time, I can make a PR.  It's not too hard to do and I will leave the default to be the existing behavior / API with an int

**Comment by aaronpuchert** [comment]
Generally I'm a big fan of enumerations. One problem though is that sometimes system error codes are used (most prominently `ENOMEM`) which are defined in system headers and not in `projects.h`. I don't see how that would work with the pattern above.

**Comment by schwehr** [comment]
Errr...  this sounds like we are in a not so good place.  It would be better to have compile time checking to make sure we don't introduce numbers that aren't handled in switch statements and such.

 /usr/include/asm-generic/errno.h

https://github.com/OSGeo/proj.4/pull/1044/files demonstrates what scares me a bit:

```
proj_context_errno_set(ctx, ENOMEM);
```

Followed by 
```
proj_context_errno_set(ctx, PJD_ERR_NO_ARGS);
```

Looking at what we have:
```
egrep -h 'pj_ctx_set_errno|pj_default_destructor' *.[ch] | grep -v '[(][)]' | perl -p -e 's/^\s+//g' | perl -p -e 's/\( /\(/g' | perl -p -e 's/ \)/\)/g' | perl -p -e 's/return //g' | perl -p -e 's/ \(/\(/g' | grep -v PJD_ | sort -u
/* pj_default_destructor actually *is* what is pointed to    */
/* pj_default_destructor, which is supposed */
Companion to pj_default_destructor(below). Deallocates a linked list
P->destructor = pj_default_destructor;                   \
if(!(Q->en = pj_enfn(P->es))) pj_default_destructor(P, ENOMEM);
pj_ctx_set_errno(ctx, 0);
pj_ctx_set_errno(ctx, ENOMEM);
pj_ctx_set_errno(ctx, err);
pj_ctx_set_errno(ctx, errlev);
pj_ctx_set_errno(ctx, errno);
pj_ctx_set_errno(ctx,0);
pj_ctx_set_errno(pj_get_ctx((PJ *) P), 0);
pj_ctx_set_errno(pj_get_ctx(P), -17);
pj_ctx_set_errno(pj_get_ctx(P), errlev);
pj_default_destructor(P, 0);
pj_default_destructor(P, ENOMEM);
pj_default_destructor(PIN, ENOMEM);
pj_default_destructor(PIN, proj_errno(PIN));
```

It looks like 0 and ENOMEM are the only two things missing from PJD_ERR.  We could make `PJD_ERR_NO_ERROR = 0` and `PJD_ERR_ENOMEM = ENOMEM` when we use the enum and `#define`.  If we user more of the error numbers, we can map them into PJD_ERR_.  

What do you think?

Also it looks like there are still one or more literal `-17`'s floating around.

```
egrep '[-]17[^0-9.f]' *.c | egrep -v 'pjd_|Thomas|non-conv'
pj_transform.c:        pj_ctx_set_errno( pj_get_ctx(P), -17 );
pj_transform.c:        return -17;
proj_etmerc.c:    Q->utg[2] = np*(-17/480.0 + n*(  37/840.0 + n*(  209/4480.0  +
```

**Comment by rouault** [comment]
> PJD_ERR_ENOMEM = ENOMEM

I'd suggest *not* using Unix constants in the PROJ API. Better create our own PJD_ERR_ENOMEM to some fixed value independant of the OS.

**Comment by schwehr** [comment]
+1 to @rouault 's suggestion of not using errno.h.  Users can always translate to system error numbers if they want to.

**Comment by schwehr** [comment]
And there are some other sneaky ones I missed.  e.g.

```
egrep 'errno = E' src/*
src/PJ_horner.c:            errno = EINVAL;
src/PJ_horner.c:        errno = EDOM;
src/PJ_horner.c:            errno = EINVAL;
src/PJ_horner.c:        errno = EDOM;
src/proj_strtod.c:        errno = EFAULT;
src/proj_strtod.c:        errno = EINVAL;
src/proj_strtod.c:        errno = ERANGE;
```

**Comment by aaronpuchert** [comment]
> It looks like 0 and ENOMEM are the only two things missing from PJD_ERR. We could make `PJD_ERR_NO_ERROR = 0` and `PJD_ERR_ENOMEM = ENOMEM` when we use the enum and #define.

That looks like it could work. We just duplicate all POSIX error codes that are currently used.

> I'd suggest not using Unix constants in the PROJ API. Better create our own PJD_ERR_ENOMEM to some fixed value independant of the OS.

Users might compare to ENOMEM in their code. Not sure if that causes problems with backwards compatibility.

About the others:
* `EINVAL` -> `PJD_ERR_INVALID_ARG` ?
* `EDOM` -> there are some `PJD_ERR_*_OUT_OF_RANGE` codes, does one fit?
* `EFAULT` seems to be some kind of internal error.
