### ISSUE TITLE
Doc task: tidy up gh-pages branch

### ISSUE THREAD

**Issue by mwtoews** [OSGeo/PROJ#996]
Older website documentation pages like https://proj4.org/projections/utm.html (source: https://github.com/OSGeo/proj.4/blob/gh-pages/projections/utm.html) still exist, even though they were moved/merged/etc. months ago. Search engines still pick these up (e.g.) search "proj4 utm".

I think it is better to manually `git rm` a few of these pages/directories in the gh-pages branch. And we know redirects don't work (#953), so when they are gone—they are gone.

**Comment by kbevers** [comment]
This is a good idea. I wonder if it would be better to simply just delete the branch and create a new one? I am not sure what the consequence of that would be though. It would free up some of the disk space that branch is currently occuppying (the many versions of proj4.pdf add up over time).

**Comment by mwtoews** [comment]
fixed by a1b1e1ea32f8f5f6c6184afe64b8be1c6884e28b (#1060)
